- swarm/api/http/server.go
- swarm/api/http/server_test.go
This PR fixes #18007 in which a HTTP 200 OK is returned when a signature in a feed update POST API call is missing or incomplete.
Tests have been updated to enforce this behavior.
> swarm/api: Fix #18007, missing signature should return HTTP 400

- core/chain_makers.go
- eth/downloader/downloader_test.go
- eth/downloader/testchain_test.go
This change reworks the downloader tests so they share a common test
blockchain instead of generating a chain in every test. The tests are
roughly twice as fast now.
> eth/downloader: speed up tests by generating chain only once

- swarm/network/kademlia.go
- swarm/network/kademlia_test.go
- swarm/network/stream/delivery.go
- swarm/network/stream/delivery_test.go
This PR implements changes RequestFromPeers so it won't try  to use peers marked as LightNodes, and makes sure LightNodes won't be  stored in the AddressBook. It's part of a bigger initiative for enabling Swarm Light Nodes. For more information, see https://hackmd.io/s/ry1kbJZfm
closes https://github.com/ethersphere/go-ethereum/pull/967
> swarm/network: light nodes are not dialed, saved and requested from

- p2p/enode/node.go
- p2p/metrics.go
Change the type of the metered connection's `id` field from `string` to `enode.ID`.
> p2p: preserve enode.ID type in the metered connection

- core/vm/logger_test.go
- eth/tracers/tracer_test.go
Both vm.dummyStatedb and tracers.dummyStatedb contain github.com/ethereum/go-ethereum/core/state.StateDB, and StateDB contains sync.Mutex, so sync.Mutex is passed by value. It is better to pass it as pointer. Otherwise, there may be deadlock risk if lock being passed into the two functions as a copied value is used in future.
> GetRefund function: sync.Mutex is passed by value.

- common/compiler/solidity.go
Like the title mentions this PR adds some fields to the Contract struct. 
Namely
- RuntimeCode
- SrcMap
- SrcMapRuntime
- I added RuntimeCode as a field to the contract struct, as Code also resides here it feels like the most logical place to have it
- SrcMap and SrcMap runtime are both located in the ContractInfo struct. I did this as like the other fields in that struct, it concerns data about how the contract has been compiled and provides information on it.
closes #17999
> common/compiler: capture runtime code and source maps

- internal/web3ext/web3ext.go
I wanted to give `eth_getProof` a test drive but found that it wasn't available in the console provided by `geth attach` so added it to `web3ext`.  It's not 100% clear to me when I should add methods to `web3ext` vs. `internal/jsre/deps/web3.js` (followed by a `go generate`), so I'm happy to change this PR to do the changes in `web3.js` instead if preferred.
Both ways give me the same result (I elided the proof values below with `"..."` to keep this PR text from being too long, in the actual output the correct hex strings are output.
```
> eth.getProof("0x09d8b66c48424324b25754a873e290cae5dca439", ["0x0"], "latest")
{
accountProof: ["...", "...", "...", "...", "...", "...", "...", "..."],
address: "0x09d8b66c48424324b25754a873e290cae5dca439",
balance: "0x0",
codeHash: …
```
> internal/web3ext: Add eth.getProof

- consensus/ethash/api.go
- consensus/ethash/ethash.go
- consensus/ethash/ethash_test.go
- consensus/ethash/sealer.go
Currently geth will generate several mining works in a single mining round, so that it can create some confusion to miner since in the `getWork` API, only `powhash`, `seedhash` and `target` are returned.
In this PR, we introduce a new package field hex encoded `block number` to let miner identify the working packages for different rounds.
> consensus: extend getWork API

- core/state/statedb.go
The lock in StateDB is useless. It's only held in Copy, but Copy is safe
for concurrent use because all it does is read.
> core/state: remove lock

- metrics/registry.go
- p2p/metrics.go
This PR creates a separate global registry for the individually metered peers in order to prevent the overflooding of the metrics.
> metrics, p2p: add ephemeral registry

- p2p/simulations/http_test.go
- p2p/simulations/network.go
- p2p/simulations/network_test.go
- swarm/network/simulations/discovery/discovery_test.go
This PR makes it possible to selectively add and remove services from snapshot generated from simulations discovery test. 
It also prunes connection objects that have status down from the generated snapshots.
Note; this uses sleeps for the `TestSnapshotExplicit` test because the timing of peer events and actual changes in state in the simulated nodes seems to be imprecise (and the test in itself is very simple). Fixing this will be a separate PR.
> p2p/simulations, swarm/network: Custom services in snapshot

- swarm/storage/ldbstore.go
- swarm/storage/ldbstore_test.go
- swarm/storage/localstore.go
- swarm/storage/localstore_test.go
Access count was not incremented when chunk was retrieved
from cache. So the garbage collector might have deleted the most
frequently accessed chunk from disk.
> swarm/storage: fix access count on dbstore after cache hit

- swarm/storage/ldbstore.go
- swarm/storage/ldbstore_test.go
- swarm/storage/localstore.go
- swarm/storage/schema.go
On file access LDBStore's tryAccessIdx() function created a faulty
GC Index Data entry, because not indexing the ikey correctly.
That caused the chunk addresses/hashes to start with '00' and the last
two digits were dropped. => Incorrect chunk address.
Besides the fix, the commit also contains a schema change which will
run the CleanGCIndex() function to clean the GC index from erroneous
entries.
Note: CleanGCIndex() rebuilds the index from scratch which can take
a really-really long time with a huge DB (possibly an hour).
> swarm/storage: fix garbage collector index skew

- rpc/doc.go
Changed "send" to "send," in two places
> rpc: fix typo

- les/serverpool.go
This is an apparent typo. So no test cases are provided. 
It seems like the code did not cover `poolEntry`'s RLP coding.
> les: fix pubkey index typo

- internal/ethapi/api.go
Changed "signTransactions" to "signTransaction"
> internal: fix typo in comments

- swarm/storage/ldbstore.go
- swarm/storage/ldbstore_test.go
Current migration from `purity` to `halloween` tries to load the whole db into memory. That's bad news. This PR fixes that, by chunking up the index processing in batches of 4096.
> swarm/storage: Batched database migration

- core/blockchain.go
- core/rawdb/accessors_chain.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
This PR contains the downloader-specific things from https://github.com/ethereum/go-ethereum/pull/17973 . However, the change in strategy (to hone in on the remote head, instead of the local head) may not be the best strategy without changing the how blockchain import works. 
This PR separates out the strategy into a separate method, with testcases, so it's pretty easy to make changes to it and ensure that a given strategy matches what is expected (it is currently pretty difficult to understand exactly what will happen).
> downloader: different sync strategy

- cmd/swarm/access_test.go
- cmd/swarm/export_test.go
- cmd/swarm/feeds_test.go
- cmd/swarm/fs_test.go
- cmd/swarm/run_test.go
- cmd/swarm/upload_test.go
Updated tests to use a global cluster, instead of starting one within each test.
Improvement of ~1min. to `/cmd/swarm` test package.
> cmd/swarm: speed up tests - use global cluster

- cmd/swarm/swarm-smoke/main.go
- cmd/swarm/swarm-smoke/upload_and_sync.go
This PR is updating the way we invoke the smoke tests for the Swarm clusters.
Production gateways is located at:
https://swarm-gateways.net
Other temporary gateways are located under the stg.swarm-gateways.net endpoint.
> cmd/swarm/swarm-smoke: fix smoke tests url scheme to fit new k8s setup

- swarm/storage/localstore.go
So that we only see the log message when we actually have to migrate.
Plus: fix lint failure (how did it pass CI if it fails locally for me... o.O)
>  swarm/storage: move 'running migrations for' log line

- whisper/whisperv5/peer_test.go
- whisper/whisperv6/peer_test.go
Whisper's `TestSimulation` is very flaky lately on macOS on Travis.
This PR is adding a bunch of logs for the errors returned, so that we can try to figure out why the test is flaky and fix it. It seems to be flaky both under `whisperv5` and `whisperv6` packages.
---
For reference, see https://travis-ci.org/ethereum/go-ethereum/jobs/456978160
```
--- FAIL: TestSimulation (0.19s)
peer_test.go:142: failed to start server 15.
FAIL
coverage: 57.6% of statements
FAIL	github.com/ethereum/go-ethereum/whisper/whisperv5	13.730s
```
> whisper: log errors on failed tests

- whisper/mailserver/mailserver.go
This should reduce the occurences of travis failures on MacOS
Also fix some linter warnings.
> whisper/mailserver: reduce the max number of opened files

- swarm/network/stream/common_test.go
- swarm/network/stream/snapshot_sync_test.go
- swarm/network/stream/syncer_test.go
This PR has been discussed and reviewed here https://github.com/ethersphere/go-ethereum/pull/1009.
> swarm: use swarm/mock/mem as mock global store

- core/blockchain.go
This PR improves the current bad block reports that gets shown in the console. 
Example:
```
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}
Number: 79589
Hash: 0x29f38d3e0b76d14d48b0e21cbf5c094f8f721f2908eb492de610b9f907dff3f1
0: cumGasUsed: 21000 gasUsed: 21000 cAddress 0x0000000000000000000000000000000000000000 status 1 txHash 0xe18b4c8e1b1777c865deeed6ec9418aa52d2ec3567f7e2192d7041630daa41fa logs [] bloom 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
> Better bad block printouts

- core/blockchain.go
- core/blockchain_insert.go
- core/blockchain_test.go
- node/node.go
- p2p/discover/table.go
This PR addresses some shortcomings in the blockchain downloader and block processing, specifically the behaviour around (invalid) long sidechains, as happened during the Ropsten constantinople HF.
> Rework blockchain import

- trie/database.go
Geth's in-memory pruning mechanism keeps a reference about how many `parents` a trie node has. 
When geth is running on a machine with a large cache allowance, this cache can become very large, and during certain circumstances, the parent counter would overflow. 
Example of what happens with bittrex wallets when the number of references exceed `65535` during a period when a lot of contracts were created, all referencing the codehash `0xce3220..`
```
parent=829a04a370589f53...                                              child.parents=65535 parent.children=1
INFO [11-22|13:50:17.664] trie/database adding reference           child/codehash=0xce33220..                                                        parent=90e152f8135795ea... …
```
> trie/database: fix overflow in parent tracking

- .travis.yml
Some tests have been failing lately on macOS on Travis due to `too many open files`.
This PR is increasing the open file limits.
From:
```
$ sudo sysctl kern.maxfiles
kern.maxfiles: 12288
$ sudo sysctl kern.maxfilesperproc
kern.maxfilesperproc: 10240
$ sudo launchctl limit maxfiles
maxfiles    256            unlimited
$ ulimit -n
256
```
To:
```
$ sudo sysctl -w kern.maxfiles=$NOFILE
kern.maxfiles: 12288 -> 20480
$ sudo sysctl -w kern.maxfilesperproc=$NOFILE
kern.maxfilesperproc: 10240 -> 20480
$ ulimit -n
20480
```
> travis: increase open file limits on macOS

- cmd/swarm/config_test.go
- cmd/swarm/fs.go
- cmd/swarm/fs_test.go
- cmd/utils/flags.go
- Have `${DataDir}/bzzd.ipc` as IPC path default.
- Respect the `--datadir` flag.
- Keep only the global `--ipcpath` flag and drop local as flags might overwrite each other.
fixes https://github.com/ethersphere/go-ethereum/issues/795
**Shall we use `utils.SetNodeConfig()` or rather export `utils.setIPC()` and `utils.setDataDir`?**
`SetNodeConfig()` does much more than what we need and also produces an extra log line:
`INFO [11-15|13:29:06.369] Maximum peer count                       ETH=25 LES=0 total=25
`. However the `fs` commands still remain fast and we don't have to export extra functions. 
**Should we have our own `SwarmIPCPathFlag`?**
If yes we won't be able to use the `utils` lib but we can set a `DefaultValue` what will be visible in help (template).
> cmd/swarm: FUSE do not require --ipcpath

- eth/handler_test.go
TestBroadcastBlock fails occasionally when the CI builder is under heavy load. Increase the
timeout slightly to avoid such failures.
> eth: increase timeout in TestBroadcastBlock

- core/blockchain.go
If `bc.GetBlock()` return nil, it will crash at the next loop because `(*head).Root()` == `nil.Root()`.
> core: return error if repair block failed

- params/config.go
Fixes failing testcases after https://github.com/ethereum/go-ethereum/pull/18162 by also adding the change to `TestChainConfig`. Note, though, it's actually still wrong internally, since some chains are generated with AllEthashProtocolChanges whereas chainmaker uses TestChainConfig. So a proper fix would be to ensure that we use the same config. It happens to work now (and previously) because the two are equal.
> config: add constantinople block to testchainconfig

- les/fetcher.go
This PR fixes a bug in the fetcher syncing logic. When nextRequest decided to sync it always did set f.syncing to true and it was left on true even if requestDistributor.queue failed to queue the syncing request and it did not start at all (and therefore also never finished). Now nextRequest does not change the flag, just returns its suggestion, then syncLoop sets it later if the queueing has succeeded.
Note: there is a version with debug prints included for testing purpose:
https://github.com/zsfelfoldi/go-ethereum/tree/fetcher-sync-fix-debug
> les: fix fetcher syncing logic

- swarm/api/api.go
this PR improves the cryptic error returned to the user when a manifest entry is not found.
fixes https://github.com/ethersphere/go-ethereum/issues/726
> swarm/api: improve not found error msg

- tests/state_test.go
This allows running state tests with any EVMC compatible EVM.
> tests: Add flag to use EVMC for state tests

- p2p/protocols/accounting.go
- p2p/protocols/accounting_simulation_test.go
- p2p/protocols/reporter.go
- p2p/protocols/reporter_test.go
- swarm/swap/swap.go
- swarm/swarm.go
The first p2p accounting PR https://github.com/ethereum/go-ethereum/pull/17951 introduced a couple of metrics for the accounting (accounted bytes sent/received, accounted messages sent/received, etc.).
Those metrics though were not persisted, and would be reset after every node restart.
These are metrics of interest to the end user, and represent (crypto-)economic indicators, which may give her insights to how her node is performing in terms of profitability.
This PR introduces functionality to persist these metrics to a DB.
The set of metrics can be extended later if required.
> Accounting metrics reporter

- cmd/swarm/feeds.go
- cmd/swarm/feeds_test.go
This PR fixes https://github.com/ethersphere/go-ethereum/issues/979. The CLI will now return with an error if attempting to update a manifest that does not match the signer.
> cmd/swarm: update should error on manifest mismatch

- swarm/network/protocol.go
- swarm/network/protocol_test.go
- swarm/network/stream/syncer_test.go
This PR increases the BZZ protocol version number.
The streamer version had been previously increased, resulting in BZZ version match and peers at kademlia level connecting, but streamer version mismatch.
This resulted in the `peer = nil` bug when requesting peers for chunks, as the kademlia peers would be iterated (BZZ, thus peers were connected) but the correspondent stream protocol peer was not found (version mismatch).
It also adds two tests to prove the version mismatch problem. These tests may be removed if the general version mismatch problem of BZZ-subprotocols will be addressed.
Closes https://github.com/ethersphere/go-ethereum/issues/999
> Increase bzz version

- p2p/protocols/protocol.go
p2p/protocols/protocol.go   the comments has minor typo.
> p2p:  fix minor comments typo

- eth/downloader/downloader.go
The binary search based ancestor lookup doesn't work for light clients. The reason is that a light client will inject a random header (the one stored in the CHT) and will want to sync from that point onward. A binary search will however try to find the common ancestor from `[HEAD-90K, REMOTE_HEAD]`. Mapping that interval to our header chain would look something like `[nil, nil, nil, nil, nil, CHT_HEADER, nil]`. You can't binary search on this.
The only proper solution is to start from the current header and set the floor of the binary search either to the `HEAD-90K` limit, or to the earliest ancestor that we do have in our database. Unfortunately there's no way to actually find that apart from traversing the chain backward, so that's what this PR does. It also caches the result so we …
> eth/downloader: fix light client cht binary search issue

- core/vm/evm.go
- tests/init.go
Apart from updating the tests to the most recent source, this also adds the following to a `STATICCALL`:
```
evm.StateDB.AddBalance(addr, bigZero)
```
This makes `STATICCALL` perform touch-delete. It appears that both parity and aleth is implemented like this. 
Although it's a simple fix, I just wanted to call some attention to this fact, and ask -- is that really the Right Way to consider `STATICCALL`? 
cc @chriseth @sorpaas @winsvega @chfast @ehildenb  @pipermerriam @vbuterin 
Edit to add : this is not an issue for mainet, but could potentially be an issue for other networks, if empties are created and then not cleaned up before transitioning to byzantium.
> tests, core: update tests and make STATICCALL cause touch-delete

- les/flowcontrol/control.go
This PR removes a line in the code that doesn't seem to be doing anything. Consider the body of the `recalcBV` function:
```go
func (peer *ClientNode) recalcBV(time mclock.AbsTime) {
dt := uint64(time - peer.lastTime)
if time < peer.lastTime {
dt = 0
}
peer.bufValue += peer.params.MinRecharge * dt / uint64(fcTimeConst)
if peer.bufValue > peer.params.BufLimit {
peer.bufValue = peer.params.BufLimit
}
peer.lastTime = time
}
```
In the original code, it's called twice in a row with the same `time` value. The second execution will be equivalent to:
```go
dt := 0
peer.bufValue += 0
peer.lastTime = peer.lastTime
```
... which is a no-op, so it should be safe to remove it.
> les/flowcontrol: remove a no-op line in the code

- mobile/big.go
The mobile type BigInts lacked the constructor, that led to inability to create an instance of that type in mobile apps.
> mobile: added constructor for BigInts

- p2p/server.go
“fmt“  is unnecessary，and poor performance
> p2p: fmt is bad choice

- swarm/pss/api.go
- swarm/pss/pss_test.go
Previously, the `pss_sendRaw` method had different datatypes for the api call than `pss_sendAsym` and `pss_sendSym`. This PR makes the interfaces uniform.
> swarm/pss: Add same api interface for all Send* methods

- signer/core/api.go
Fixes typo of method name in comment in `signer/core/api.go`.
> signer/core: Fixes typo of method name in comment.

- cmd/puppeth/puppeth.go
- cmd/puppeth/wizard_intro.go
Fixes https://github.com/ethereum/go-ethereum/issues/17976.
Puppeth explicitly checked that users didn't supply spaces or hyphens in the network names, but it did not do so for uppercase letters. Apparently however docker (or docker compose, not sure) rejects image names with capital letters, so we need to forbid those too.
> cmd/puppeth: enforce lowercase network names

- swarm/network/stream/delivery.go
Change log level for when a chunk can not be retrieved.
Usually this happens after a timeout, and it means that the chunk is not existing in a network (404).
Closes issue https://github.com/ethersphere/go-ethereum/issues/954
> swarm/network/stream: Debug log instead of Warn for retrieval failure

- swarm/api/http/middleware.go
This PR adds a resetting timer metric to HTTP requests.
fixes https://github.com/ethersphere/go-ethereum/issues/1045
> swarm/api/http: add resetting timer metrics to requests

- core/blockchain.go
- eth/api_backend.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/api_backend.go
- miner/worker.go
This fixes on of the many issues with `vm.Config`. When mining is enabled the VM config is different in the miner worker.
In general, there is too many places where `vm.Config` is naively constructed without any options just because some function requires it.
Moreover, it probably should not be passed by value.
I can have some suggestions how to solve it.
EDIT:
I also added a workaround for EthAPI (last commit).
cc @gballet 
Fixes an issue observable in #17954
> eth, miner: Take VM config from BlockChain

- p2p/simulations/network.go
- swarm/network/hive.go
- swarm/network/simulation/kademlia_test.go
This PR addresses the issue when loading a snapshot does not wait for all connections to be established.
Changes:
1. p2p/simulatons.Network.Load function now listens on "connect" events and waits for all connections from the snapshot
2. swarm/network.Hive.Run does not call NotifyPeer if the Discovery is disabled
3. swarm/network/simulation.TestWaitTillHealthy test must use discovery to pass
Change _2._ is required for change _1._ and change _3._ is needed because of the change _2._
Change _2._ is required as establishing a large number of connections takes exponentially more time on snapshot loading with peer notifications. This change is apparently the correct behaviour in respect to the Discovery option. But ti requires that discovery is enabled in TestWaitTillHealthy test.
> swarm: snapshot load improvement

- cmd/utils/flags.go
Supersedes https://github.com/ethereum/go-ethereum/pull/17597, as it can achieve the same results without any flags (i.e. automagically), whilst also ensuring we don't accidentally go over any OS limits (panic in leveldb).
Fast sync benchmarks, 4096 cache, i3.2xlarge (post sync):
The curious thing here is that memory usage seems to be a lot lower and more stable, which is an interesting find. Why would more file descriptors cause less memory? Perhaps there's some issue in leveldb which leaks memory, at least temporarily? **Idea: perhaps it's the transaction pool, not the database!**
Full sync bnchmarks, 2084 cache, i3.2xlarge:
The speed seems to be more or less the same (4h difference over the course of 4 days, might as well just be a slightly different machine). Database IO wise the …
> cmd/utils: max out the OS file allowance, don't cap to 2K

- node/config.go
This solves an old TODO comment and fixes #16346. We now print a warning
when static-nodes.json, trusted-nodes.json or any of the 'old geth resources' are found.
> node: warn when using deprecated config/resource files

- params/config.go
This PR enables the Constantinople hard fork on mainnet at block 7080000 per https://github.com/ethereum/EIPs/pull/1642 .
It also enables the fork on the Rinkeby testnet at block 3660663, scheduled a week before the mainnet hard fork (i.e. around the 9th of January).
> params: set mainnet and Rinkeby Constantinople fork blocks

- cmd/evm/runner.go
- cmd/evm/staterunner.go
- core/vm/logger_json.go
- eth/api_tracer.go
- internal/web3ext/web3ext.go
This PR adds `debug` methods to dump out traces from blocks and/or individual transactions. 
When @karalabe implemented tracing, the intended usecase was to enable long-running tracers that could stream results back via a subscription channel. However, when investigating e..g consensus errors and/or bad blocks, that format is not very good.
* The existing generic tracer framework collects all result data (per block) into a big blob in memory, before streaming. For a large trace, such as the `205K` steps in the recent Ropsten-fork, the full output from the tracer was `2.4GB`, which can easily crash many nodes. 
* The existing callTracer does not confirm to `std-json`, which is 
* `jsonl` not `json`, to allow for streaming output
* Uses `op` for string-representation of opcode, instead of …
> core/vm, eth: add standard json tracing into filesystem dumps

- core/blockchain.go
- node/node.go
- rpc/ipc.go
there are three changes for the commit:
1. remove "conn.RemoteAddr()" in rpc/ipc.go, because it always `null` for the ipc call.
2. add "IPC" at some places in rpc/ipc.go
3. change "endpoint" -> "url" in node/node.go, just for a consistency with other places.
> node,rpc: remove unused log in ipc listener function

- light/trie_test.go
Most probably a copy/paste kind of error.
Found with gocritic `dupArg` checker.
> light: fix duplicated argument in bytes.Equal call

- swarm/network/networkid_test.go
Previously the changed iterator compared the bytes of `enode.ID` to bytes of `BzzAddr.OAddr`. While this coincidentally was correct since the same value is used in both, it's not semantically correct and may cause confusion in evaluating the test later.
> swarm/network: Correct ambiguity in compared addresses

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/backend.go
- eth/config.go
- eth/handler.go
- eth/handler_test.go
- eth/helper_test.go
As discussed with @holiman in #17935.
I'm not sure what the issue I was running into was last time where I thought I needed to do this for the bootnodes, I didn't run into that issue this time when testing.
I think the only remaining question I have is does this need to be implemented for light clients as well?
> cmd, eth: add support for `--whitelist <blocknum>=<hash>`

- cmd/faucet/faucet.go
- cmd/puppeth/module_ethstats.go
- cmd/puppeth/module_explorer.go
- cmd/puppeth/module_faucet.go
- cmd/puppeth/module_nginx.go
- cmd/puppeth/module_node.go
- cmd/puppeth/module_wallet.go
This PR fixes a regression in the faucet code which caused the bootnode to be added only if it was **invalid**. It also updates `puppeth` to support deploying via the newest `docker_compose`, which broke the container names it generates. Lastly the PR also exposes UDP on the faucet.
Fixes: https://github.com/ethereum/go-ethereum/issues/18257, https://github.com/ethereum/go-ethereum/issues/18214, https://github.com/ethereum/go-ethereum/issues/18122, https://github.com/ethereum/go-ethereum/issues/18086.
> cmd/faucet, cmd/puppeth: fix enode and compose regressions, expose UDP

- cmd/geth/config.go
- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/config.go
- les/backend.go
This PR makes it possible to postpone the constantinople hardfork without having to build new clients and requiring people to upgrade. 
```
[user@work go-ethereum]$ build/bin/geth --nodiscover --maxpeers 0 --override.constantinople=8900000
INFO [12-10|16:15:24.837] Maximum peer count                       ETH=0 LES=0 total=0
INFO [12-10|16:15:24.837] Starting peer-to-peer node               instance=Geth/v1.8.20-unstable-b2aac658/linux-amd64/go1.11.2
INFO [12-10|16:15:24.837] Allocated cache and file handles         database=/home/user/.ethereum/geth/chaindata cache=512 handles=2048
INFO [12-10|16:15:24.946] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 …
```
> geth/core/eth: implement constantinople override flag

- swarm/storage/feed/handler.go
- swarm/storage/feed/handler_test.go
- swarm/storage/feed/request.go
- swarm/storage/feed/request_test.go
- swarm/storage/localstore.go
- swarm/storage/localstore_test.go
- swarm/storage/types.go
I noticed that most code using `Validate()` was unfolding a given chunk rather than just passing the chunk variable itself. Refactored code so that the interface looks like this:
```go
type ChunkValidator interface {
Validate(chunk Chunk) bool
}
```
> swarm/storage: simplify ChunkValidator interface

- rpc/http.go
This PR adds `application/json-rpc` as accepted content type for the server. 
@ligi Please try it out and see if it works for you (I haven't actually tested the code :) )
> rpc: add application/json-rpc as accepted content type, fixes #18293

- p2p/discv5/net.go
q.target is the hash that needs to be found, no need to hash again.
> p2p/discv5: don't hash findnode target in lookup against table

- .github/no-response.yml
- .github/stale.yml
I put the new label names (that include colons) in quotes to avoid possible problems with the yaml parser.
> .github: change issue bot config for new label names

- swarm/storage/feed/handler.go
- swarm/storage/feed/handler_test.go
- swarm/storage/feed/timestampprovider.go
Approved at https://github.com/ethersphere/go-ethereum/pull/1056
> swarm/storage/feed: remove unused code

- swarm/network/stream/snapshot_sync_test.go
- swarm/network/stream/visualized_snapshot_sync_sim_test.go
The Tests in `swarm/network/stream/visualized_snapshot_sync_sim_test.go`, which contain special tests for the frontend visualizer, were broken after some recent refactor of the `swarm/network/simulation` package, because they are disabled with `t.Skip()`.
This PR fixes those tests. They are still disabled with `t.Skip()` though.
In any case, they need to be run with `-tags=withserver` or they will be ignored anyway. Reason is that these tests actually wait for a frontend signal (`POST /runsim`) to actually start.
The frontend is at https://github.com/ethersphere/simple-p2p-d3.
Use the `snapshot-sync-frontend` branch for correct interaction with this backend.
> Update visualized snapshot test

- eth/downloader/downloader.go
This PR fixes an issue that was surfaced by https://github.com/ethereum/go-ethereum/issues/18317. where the `InsertChain` method in `blockchain.go` sometimes, when it needs to preprocess blocks to import a sidechain, will return an index that is out-of-bounds. 
The importer will put together a new list of blocks to import, which is a superset of the blocks delivered from the downloader, and the indexing will be off.
> downloader: fix edgecase where returned index is OOB for downloader

- swarm/pss/forwarding_test.go
- swarm/pss/pss.go
- swarm/pss/pss_test.go
Forward() function forwards a pss message to the peer(s) based on recipient address according to the following algorithm.
If the recipient address (or partial address) is within the neighbourhood depth of the forwarding node, then it will be forwarded to all the nearest neighbours of the forwarding node. In case of partial address, it should be forwarded to all the peers matching the partial address, if there are any; otherwise only to one peer, closest to the recipient address. In any case, if the message forwarding fails, the node should try to forward it to the next best peer, until the message is successfully forwarded to at least one peer.
> swarm/pss: forwarding function refactoring

- accounts/abi/bind/bind.go
The case of generated java functions did not follow the [java convention](https://www.oracle.com/technetwork/java/codeconventions-135099.html) in spite of claiming to do it in the comments.
> accounts/abi: fix case of generated java functions

- rpc/ipc_unix.go
Issue https://github.com/ethereum/go-ethereum/issues/18278
Issue https://github.com/ethereum/go-ethereum/issues/16342
@adamschmideg The ticket says log a warning but I feel this should this not just log it as an error instead? It will always fail anyway.
I don't think I can test that log.warn was called in golang.
108 chars fails. 107 chars passes.
> Warn the user when the path name is too long for the ipc endpoint on linux

- swarm/storage/types.go
- swarm/storage/types_test.go
This PR changes Proximity function in storage package to successfully pass all test cases in a newly added TestProximity function. Current Proximity function returns MaxPO value for MaxPO-9 to MaxPO-1 (last 8 bins of MaxPO bins, or last byte) instead lower values.
For example, for MaxPO=16 the test will fail with incorrect values for bins 8-15 with value 16 for all of them, and for MaxPO=32 bins 24-31 will have value of 32.
This is a resubmission of https://github.com/ethersphere/go-ethereum/pull/1079 PR.
> swarm: Change Proximity function and add TestProximity test

- .travis.yml
- appveyor.yml
- internal/build/util.go
Release notes: https://golang.org/doc/devel/release.html#go1.11.minor ([with hash](https://go.googlesource.com/go/+/go1.11.2/doc/devel/release.html#44))
> travis, appveyor: bump to Go 1.11.4

- accounts/abi/bind/base.go
- accounts/abi/bind/base_test.go
Enables binding to called methods on the previous blocks.
> accounts/abi/bind: add optional block number for calls

- swarm/api/http/middleware.go
- swarm/docker/Dockerfile
- swarm/docker/run-smoke.sh
- swarm/docker/run.sh
Copying `Dockerfile` to `swarm/docker`, so that we can automatically build `ethdevops/swarm:edge` on `push` to `master` with buddy.works (currently enabled only on `ethersphere` org).
> swarm/docker: Dockerfile for swarm:edge docker image

- internal/ethapi/api.go
As described in #2880, for anyone using `abigen` contract bindings to submit concurrent transactions, there is a race condition such that it is possible for two concurrent transactions to be submitted with the same nonce if the first transaction is still pending when the second transaction is submitted.
`transact` in https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L176 uses `PendingNonceAt` which invokes the `GetTransactionCount` API method. Currently, `GetTransactionCount` uses `StateAndHeaderByNumber` to get the nonce from the pending state. But, only the miner knows the pending state so if the local node is not a miner, then the state used to get the nonce will not include any pending transactions that the sender has submitted.
This is not a problem for …
> internal/ethapi: ask transaction pool for pending nonce

- cmd/geth/config.go
https://github.com/ethereum/go-ethereum/issues/18279
Checks if there is an argument passed to `geth dumpconfig` if so the function will write to that file instead of outputting to stdout
> Changed dumpConfig function to optionally save to file

- swarm/shed/db.go
- swarm/shed/example_store_test.go
- swarm/shed/field_uint64.go
- swarm/shed/field_uint64_test.go
- swarm/shed/index.go
- swarm/shed/index_test.go
The original PR discussion is on https://github.com/ethersphere/go-ethereum/pull/1070.
This PR addresses only shed package changes from localstore PR https://github.com/ethersphere/go-ethereum/pull/1032 in order to reduce the number of changes in that PR.
- Rename IndexItem type to Item.
- Change Index DecodeValue signature to include shed.Item decoded from database key. This information is available in iterator functions, and is needed when mock store is injected in localstore retrieval index.
- Add Uint64Field Dec and DecInBatch functions to complement Inc and IncInBatch.
- Merge Index IterateAll and IterateFrom into one function Iterate and add option to iterate on a subset of Index keys that have common prefix by specifying it in IterateOptions. This is needed for localstore pull …
> swarm: Shed Index and Uint64Field additions

- .github/CODEOWNERS
Approved at https://github.com/ethersphere/go-ethereum/pull/1089
---
For many packages we have only one code owner and their approval is a must when merging a PR. What happens when these people go on vacation for example? (see ethereum#18386) - we won’t be able to merge anything in swarm/api/http when @justelad is on vacation.
We must add at least 2-3 code owners to every single package, or get rid of them altogether.
I don’t really like adding many code owners, because then you have a PR with 4-5 reviewers, and no-one feels responsible for reviewing the PR.
Therefore I suggest we remove all the codeowners from .github. What do you think?
I think we all have a good idea of who knows which part of the codebase best, and can make a good educated guess who to add as a reviewer, without the …
> github: remove swarm github codeowners

- swarm/network/simulation/events_test.go
- swarm/network/simulation/http_test.go
- swarm/network/stream/delivery_test.go
- swarm/network/stream/intervals_test.go
- swarm/network/stream/snapshot_sync_test.go
- swarm/network/stream/syncer_test.go
- swarm/storage/netstore_test.go
This changes were approved in PR https://github.com/ethersphere/go-ethereum/pull/1090.
> swarm: Fix T.Fatal inside a goroutine in tests

- swarm/network/discovery.go
- swarm/network/hive.go
- swarm/network/hive_test.go
- swarm/network/kademlia.go
- swarm/network/kademlia_test.go
- swarm/network/networkid_test.go
- swarm/network/stream/delivery.go
- swarm/network/stream/messages.go
- swarm/network/stream/snapshot_sync_test.go
- swarm/pss/pss.go
- swarm/pss/pss_test.go
This PR eliminates the third boolean argument from the iterator function given to kademlia peer iterators `EachAddr` and `EachConn`. 
closes https://github.com/ethersphere/go-ethereum/issues/1042
> swarm/network: remove isproxbin bool from kad.Each* iterfunc

- swarm/network/kademlia.go
- swarm/network/kademlia_test.go
- swarm/network/networkid_test.go
- swarm/network/simulation/example_test.go
- swarm/network/simulation/kademlia.go
- swarm/network/simulation/kademlia_test.go
- swarm/network/simulation/simulation.go
- swarm/network/simulations/discovery/discovery_test.go
- swarm/network/simulations/overlay.go
- swarm/network/stream/delivery_test.go
- swarm/network/stream/intervals_test.go
- swarm/network/stream/snapshot_retrieval_test.go
- swarm/network/stream/snapshot_sync_test.go
- swarm/network/stream/syncer_test.go
- swarm/network/stream/visualized_snapshot_sync_sim_test.go
- swarm/network_test.go
- swarm/pss/client/client_test.go
- swarm/pss/notify/notify_test.go
- swarm/pss/pss_test.go
Rerun of https://github.com/ethersphere/go-ethereum/pull/1074 due to history/rebasing issues.
Now includes rename of `MinProxBinSize`
> swarm/network: Rename minproxbinsize, add as member of simulation

- core/blockchain.go
- core/rawdb/accessors_metadata.go
- eth/backend.go
> core, eth: fix database version

- swarm/pot/address.go
- swarm/pot/pot.go
- swarm/pot/pot_test.go
-    bugfix for pot.remove() function
-    new tests for pot.remove()
-    fixed the comments
> swarm/pot: pot.remove fixed

- swarm/network/kademlia.go
- swarm/pot/pot.go
- swarm/pot/pot_test.go
Second parameter (int) was removed from each() and eachFrom(), since it does not contain any meaningful value. 
Related functions refactored accordingly.
This PR is clone of https://github.com/ethersphere/go-ethereum/pull/1120
fixes https://github.com/ethersphere/go-ethereum/issues/1104
> swarm/pot: each() functions refactored

- cmd/evm/main.go
- cmd/evm/runner.go
This adds `--vm.evm` flag to `evm` tool. The same flag is supported by `geth` and `go test`.
> cmd/evm: Add --vm.evm flag to support EVMC

- swarm/network/networkid_test.go
This changes are approved in https://github.com/ethersphere/go-ethereum/pull/1122.
> swarm: Fix data race in TestNetworkID test

- swarm/storage/netstore_test.go
This PR fixes ethersphere/go-ethereum#1117. It just adds a mutex to protect mockNetFetcher on change. This is a fetcher used only in tests, so no performance degradation in production is introduced. The change is small and simple, so the PR is submitted directly to the ethereum repo.
> swarm: Fix mockNetFetcher data races in storage

- core/blockchain.go
- core/blockchain_test.go
- light/lightchain.go
- light/lightchain_test.go
Possibly fixes https://github.com/ethereum/go-ethereum/issues/18421 and https://github.com/ethereum/go-ethereum/issues/18388.
The block chain and light chain currently have two mutexes that protect its internal state: `mu` and `chainmu`. The `mu` supposed to protect internal state from getting corrupted whilst `chaimu` from multiple modifications to the chain. However, modifying the internal state **is equivalent to** modifying the chain. 
Most of our code ended up only locking `mu` (e.g. Rollback, SetHead), which although weren't chain insertions, they could really screw up the inserter. The reason this didn't blow up earlier is because most of these method calls are serialized by the downloader, hiding the ticking time bomb. Apparently a side chain import PR managed to destabilize the …
> core, light: get rid of the dual mutexes, hard to reason with

- swarm/network/protocol.go
- swarm/network/protocol_test.go
This PR addresses a data race warning in regards to TestBzzHandshakeLightNode test.
The warning was generated since the test was accessing without synchronisation on the handshake which was stored in the hive as a pointer. Without waiting on the actual handshake process to finish (wait on the channel), there is no guaranty that the `LightNode` value won't mutate.
fixes https://github.com/ethersphere/go-ethereum/issues/1115
> swarm/network: fix data race warning on TestBzzHandshakeLightNode

- swarm/network/stream/stream.go
handleOfferedHashesMsg() contained a data race:
- read => in a goroutine, call to c.batchDone()
- write => in the main thread, write to c.sessionAt
c.batchDone() contained a call to c.AddInterval(). Client was a value
receiver for AddInterval. So on c.AddInterval() call the whole client
struct got copied (read) while one of its field was modified in
handleOfferedHashesMsg() (write).
fixes ethersphere#1086
> swarm/network: fix data race in stream.(*Peer).handleOfferedHashesMsg()

- swarm/network/fetcher.go
- swarm/network/fetcher_test.go
**Problem**
Let's say TestA() and TestB() was started right after each other.
TestA() called `go Fetcher.run(ctx)` (read: searchTimeout), on test
completion the context was cancelled, but the test did not wait for
goroutine termination. Test(B) started by modifying searchTimeout
(write).
**Solution**
Let's just store searchTimeout on the Fetcher struct and change the package var (default) to const (thread-safe).
**Alternative (almost) solution**
The above could have been solved by (little ugly, more complex)
waitGroups. However that would have not work for TestFetcherFactory.
As fetcherFactory.New()starts a goroutine inside it's body without
providing a way for clear termination. (We did not want to modify the
interface for this one, as we think the unclean termination does not
cause a …
> swarm/network: fix data race in fetcher_test.go

- core/blockchain.go
receipts may be null for very short time in some condition. For this case, we should not add the null value into cache. Because you will not get the right result if you keep requesting that receipt.
> fix bug:  get transaction receipt returns null

- cmd/swarm/swarm-smoke/upload_and_sync.go
Some metrics for time measures were using `Counter`, which was wrong.
Fixed by using `ResettingTimer`
> cmd/swarm/swarm-smoke: use ResettingTimer instead of Counters for times

- p2p/simulations/events.go
- p2p/simulations/network.go
This PR addresses a data race caused by copying the node struct when creating a node event. This copy is done without synchronisation thus causing the data race warning.
Passing the underlying pointer instead eliminates the warning.
fixes https://github.com/ethersphere/go-ethereum/issues/1110
> p2p/simulations: fix data race on swarm/network/simulations

- eth/api_tracer.go
It was noticed when investigating https://github.com/ethereum/go-ethereum/issues/18331 that the `debug_ standardTraceBlockToFile` did not properly flush files before closing them. This PR fixes that
> eth: properly flush files in standardTraceBlockToFile

- .github/CODEOWNERS
I am adding myself to the codeowners of p2p/simulations and p2p/protocols packages.
> .github: add @janos as codeowner for p2p/simulations and p2p/protocols

- accounts/abi/reflect.go
- accounts/abi/unpack_test.go
In this PR, interface as the abi unpack destination is allowed. 
It means user could pass a pointer to an empty interface (v) to the `abi.Unpack(v interface{}, data []byte)` method in order to unpack values returned from contract method calls **without needing to know the type of the returned values beforehand**(Copy from #18480 issue description).
Also this PR fix #18480
> accounts/abi: allow interface as the destination

- eth/fetcher/fetcher_test.go
- miner/worker_test.go
- p2p/protocols/protocol_test.go
- p2p/protocols/reporter_test.go
This PR fixes a couple of testcases that from time to time error on travis. 
```
--- FAIL: TestInvalidNumberAnnouncement63 (0.06s)
fetcher_test.go:628: peer with invalid numbered announcement not dropped
--- FAIL: TestEmptyWorkEthash (1.06s)
worker_test.go:228: new task timeout
--- FAIL: TestReporter (0.04s)
reporter_test.go:69: Expected counter to be 12, but is 0
--- FAIL: TestProtocolHook (0.02s)
protocol_test.go:273: Expected peer ID to be set correctly, but it is not
```
Mostly it's timeouts, but there's one change in `protocol_test.go` that is changed 'semantically'. 
The test expects a certain order of events, and sometimes it seems to arrive in a different order. I changed the test to accept any order, but I'm not sure if that is a false positive or an actual error that should be …
> tests: tune flaky tests that error in travis occasionally

- swarm/swarm.go
This PR addresses data race described in https://github.com/ethersphere/go-ethereum/issues/1154.
Swarm PR https://github.com/ethersphere/go-ethereum/pull/1155.
Global variable startTime was used concurrently. But given the nature of its usage it just have to be specific to a Swarm instance, and it does not require a lock:
- Swarm.Start is not called in parallel
- Swarm.updateGauges is always called after the startTime is set
> swarm: fix a data race on startTime

- core/vm/gas_table.go
- params/protocol_params.go
Minor fixes:
- core/vm/gas_table: fix minor comment typo
- core/vm/gas_table: Use ExpGas param in gasExp computation
- params/protocol_params: Fix JumpdestGas comment
> Minor fixes

- accounts/usbwallet/trezor.go
- console/bridge.go
Trezor 1 with passphrase protection requires an additional authentication step when opening the wallet. Change `Open` and return the relevant error if the Trezor asks for a passphrase.
- Modify `bridge.go` as well to reflect the additional authentication.
- If an empty passphrase is specified when opening the Trezor while waiting for `ErrTrezorPassphraseNeeded` it'll use an empty passphrase which should be supported.
_(Trezor Model T will ask the user to directly specify the PIN and passphrase on screen AFAIK similar to how the Ledger works)_
_(apologies for any noob mistakes in the PR - first one for go-ethereum and in general in golang)_
cc @karalabe
> accounts/usbwallet: support trezor passphrases

- swarm/storage/ldbstore_test.go
fixes ethersphere/go-ethereum#1118
`TestLDBStoreCollectGarbage` data race fixed with locks (only needed in tests)
`testLDBStoreRemoveThenCollectGarbage` fails unreliably when run with `-race` flag. As waitGC() does not work as expected, it might just continue (not block) if GC is not
running already. We might end up with or without a chunk, depending
on goroutine scheduling. As localstore rewrite is at the finish line and this blocks
ethersphere#741 => Skip.
> Fix race in TestLDBStoreCollectGarbage and disable flaky testLDBStoreRemoveThenCollectGarbage

- cmd/utils/flags.go
This PR is adding a `if url != ""` check, prior to trying to parse the `enode` from the command-line arguments.
Currently there is no way to specify that we want to have an empty bootnodes list in the resulting `cfg.BootstrapNodes` - you can either override the bootnodes list with entries, or use the provided defaults, but never use an empty list.
When we start a new deployment, and start a new bootnode, we might want it to not try to connect to any peers.
> cmd: allow empty bootnodes flag override

- light/lightchain.go
This change unbreaks the build and removes racy access to
disableCheckFreq. Even though the field is set while holding
the lock, it was read outside of the protected section.
> light: fix disableCheckFreq locking

- p2p/protocols/protocol_test.go
- p2p/testing/protocoltester.go
- swarm/network/protocol_test.go
- swarm/network/stream/common_test.go
- swarm/network/stream/delivery_test.go
- swarm/network/stream/lightnode_test.go
- swarm/network/stream/streamer_test.go
This PR removes an unused `testing.T` parameter from the p2p protocol tester
> p2p, swarm: remove unused testing.T in protocol tester

- metrics/registry.go
- p2p/protocols/accounting.go
- p2p/protocols/reporter_test.go
- swarm/metrics/flags.go
reviewed and approved in https://github.com/ethersphere/go-ethereum/pull/1107
> swarm/metrics: Send the accounting registry to InfluxDB

- cmd/bootnode/main.go
Also say that cmd/bootnode is not for production use.
Fixes #18252.
> cmd/bootnode: print node URL on startup

- .travis.yml
- appveyor.yml
Release notes: https://golang.org/doc/devel/release.html#go1.11.minor ([with hash](https://go.googlesource.com/go/+/go1.11.5/doc/devel/release.html#70))
```bash
fd -H -t f -exec sed -i 's|go1.11.4|go1.11.5|g' {} \
```
> travis, appveyor: bump to Go 1.11.5

- swarm/pss/notify/notify_test.go
This PR fixes an out of memory issue https://github.com/ethersphere/go-ethereum/issues/1165#issuecomment-457606374 in pss notify test TestStart by shutting down the network at the end of the test. Nodes were not closed leaving databases open after the test is done.
> swarm: fix oom in pss notify test

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/swarm/swarm-smoke/main.go
- cmd/utils/flags.go
- cmd/utils/flags_test.go
- swarm/metrics/flags.go
This PR is replacing the `metrics.influxdb.host.tag` cmd-line flag with `metrics.influxdb.tags` - a comma-separated key/value tags, that are passed to the InfluxDB reporter, so that we can index measurements with multiple tags, and not just one `host` tag.
This will be useful for Swarm, where we want to index measurements not just with the host tag, but also with `bzzkey` and `git commit` version (for long-running deployments).
> cmd/utils: allow for multiple influxdb flags

- core/types/block.go
When using Google App Cloud, the `go-app-builder` will complain because an "unsafe" package import: 
```
go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/ethereum/go-ethereum/core/types/block.go from GOPATH
```
To get the size of `Header` interface, this PR changes the "unsafe" package for "encoding/binary" to get the size of a struct.
> Removes "unsafe" package in exchange for binary.Size({} interface)

- build/ci.go
dput --passive should make repo pushes from Travis work again.
dput --no-upload-log works around an issue I had while uploading locally.
debuild -d says that debuild shouldn't check for build dependencies when
creating the source package. This option is needed to make builds work
in environments where the installed Go version doesn't match the
declared dependency in the source package.
> build: tweak debian source package build/upload options

- p2p/protocols/protocol.go
The race occurred in the `!p.Inbound()` case if `send()`
did return an error.
Write 1: in handle closure `rhs = msg` (goroutine)
Write 2: `return nil, error` => `nil` is written to `rhs` (main thread)
fixes ethersphere/go-ethereum#1160
---
I did not manage to write a reliable (commitable) test to show the issue. See https://github.com/ethersphere/go-ethereum/issues/1160#issuecomment-457589898 for the hacky way.
> p2p/protocols: fix rare data race in Peer.Handshake()

- p2p/protocols/reporter.go
P2P protocols reporter saves metrics to disk on periodic intervals. This change prevents possible metrics loss when more metrics are measured between the last reporter.run ticker tick and AccountingMetrics.Close call.
> p2p/protocols: fix possible metrics loss in AccountingMetrics

- p2p/discover/node.go
- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/discover/udp.go
- p2p/discover/udp_test.go
- p2p/enode/nodedb.go
- p2p/enode/nodedb_test.go
This change resolves multiple issues around handling of endpoint proofs.
The proof is now done separately for each IP and completing the proof
requires a matching ping hash.
Also remove waitping because it's equivalent to sleep. waitping was
slightly more efficient, but that may cause issues with findnode if
packets are reordered and the remote end sees findnode before pong.
Logging of received packets was hitherto done after handling the packet,
which meant that sent replies were logged before the packet that
generated them. This change splits up packet handling into 'preverify'
and 'handle'. The error from 'preverify' is logged, but 'handle' happens
after the message is logged. This fixes the order. Packet logs now
contain the node ID.
> p2p/discover, p2p/enode: rework endpoint proof handling, packet logging 

- cmd/swarm/swarm-smoke/feed_upload_and_sync.go
- cmd/swarm/swarm-smoke/main.go
- cmd/swarm/swarm-smoke/sliding_window.go
- cmd/swarm/swarm-smoke/upload_and_sync.go
- cmd/swarm/swarm-smoke/upload_speed.go
- cmd/swarm/swarm-smoke/util.go
This PR adds a smoke test that tries to assert the overall network capacity of a given Swarm cluster.
The test constantly pumps the same file size into the cluster and tries to download the uploaded hashes until it fails, then reports the depth of the network in number of files as a result.
This test is currently triggered through a cron job which is not ideal since the time it takes for the network to fail on an uploaded hash is very high (`4 hours` on a `10 node` cluster with `1000 chunk` store size). Ideally this test should be run as a _one-off_ at least until we figure the cron intervals in which it is supposed to run in.
closes https://github.com/ethersphere/go-ethereum/issues/1095
previously discussed in https://github.com/ethersphere/go-ethereum/pull/1136
example k8s deployment …
> cmd/swarm/swarm-smoke: sliding window test

- swarm/network/hive_test.go
Fixes https://github.com/ethersphere/go-ethereum/issues/1161 https://github.com/ethereum/go-ethereum/issues/18513 ... The bug was that by passing `n=1` to the second protocol tester, an additional node was created.
----
While adding comments to the tests in this file in an attempt to explain what they do, I also uncovered a synchonicity discrepancy in the `TestRegisterAndConnect` test. This theoretically makes it pass before connection has been made. I added the fix to this PR.
It would perhaps be more correct to add a `TestConnected` method to `ProtocolSession` (along the lines of `TestDisconnected`) instead of the connect test loop in `TestRegisterAndConnect` that I've added here. However, if this is the only place we care about whether connection is actually up maybe it could just stay …
> swarm/network: Remove extra random peer, connect test sanity, comments

- cmd/swarm/swarm-smoke/sliding_window.go
- cmd/swarm/swarm-smoke/upload_and_sync.go
- cmd/swarm/swarm-smoke/upload_speed.go
- cmd/swarm/swarm-smoke/util.go
This PR is removing the measurement for `total time` in each individual command, because this is already part of the `wrapCli` wrapper, which wraps every command.
It also changes `Counter` to `ResettingTimer` for measuring the `total time`.
It also removes colouring in the logs, so that smoke test logs are readable when we aggregate them in Elastic Search.
> cmd/swarm/swarm-smoke: remove wrong metrics

- swarm/network/stream/delivery.go
- swarm/network/stream/delivery_test.go
Swarm PR https://github.com/ethersphere/go-ethereum/pull/1170
This PR should fix stream capability problems reported on travis https://travis-ci.org/ethersphere/go-ethereum/jobs/485364722#L808.
```
ERROR[01-28|12:13:08.749|swarm/network/stream/delivery.go:266] Delivery.RequestFromPeers: peer doesn't have stream cap. we should have returned at sp == nil 
ERROR[01-28|12:13:18.259|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=c23331d32a5c1e2c err="shutting down"
ERROR[01-28|12:13:18.259|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=c23331d32a5c1e2c err="shutting down"
ERROR[01-28|12:13:18.259|swarm/network/stream/peer.go:91]      Message send error, dropping peer        peer=c23331d32a5c1e2c err="shutting down" …
```
> swarm: fix flaky delivery tests

- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/discover/udp.go
This change clears up confusion around the two ways in which nodes
can be added to the table.
When a neighbors packet is received as a reply to findnode, the nodes
contained in the reply are added as 'seen' entries if sufficient space
is available.
When a ping is received and the endpoint verification has taken place,
the remote node is added as a 'verified' entry or moved to the front of
the bucket if present. This also updates the node's IP address and port
if they have changed.
> p2p/discover: improve table addition code

- eth/api_tracer.go
This PR is on top of https://github.com/ethereum/go-ethereum/pull/18502 . 
The tracers, when computing the statedb in various places, told the `statedb.Finalise` method to delete empty objects, and did not check whether EIP 158/161 was activated. 
This causes erroneous traces for historic transactions, as seen in https://github.com/ethereum/go-ethereum/issues/18331
EDIT: rebased now that https://github.com/ethereum/go-ethereum/pull/18502 is merged
> eth: make tracers respect pre-EIP158/161 rules

- common/compiler/solidity_test.go
The test for the `common/compiler` package fails because the string that is fed into `solc` doesn't declare a solidity pragma. This declaration is needed in `solc >=0.4.0`.
It might be better to replace `>0.0.0` for `>=0.4.0`.
> common/compiler: fixed testSource

- accounts/accounts.go
- accounts/accounts_test.go
- accounts/external/backend.go
- accounts/keystore/wallet.go
- accounts/usbwallet/wallet.go
- cmd/clef/main.go
- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- consensus/clique/clique.go
- consensus/clique/snapshot_test.go
- eth/backend.go
- internal/ethapi/api.go
- node/config.go
- signer/core/api.go
- signer/core/api_test.go
- signer/core/auditlog.go
This PR is still a bit of a WIP, but I think it can be a good first step. It implements an additional backend for the account manager. The backend integrates with `clef`, and invokes an external signer for operations. 
It currently can sign only transactions, for more advanced usages, such as signing Clique headers and/or data, we'll wait for the PR from @PaulRBerg to get implemented into `clef`. 
Also some other things are missing, and could be added later on:
I'm not sure if the current scheme for `Accounts.URL` is the best, not quite sure how it is intended (e..g, should we have wallet URL be the same as the Backend URL? -- and should we really expose the plain backend URL or use some indirection, such as a hash or the remote url? )
> External signer API (first iteration)

- swarm/network/simulations/discovery/discovery_test.go
- swarm/storage/common_test.go
- Remove log from tests producing 1.5k lines per run
- Increase timeout so test won't fail with `-race`
> Small improvements to better work with Travis+`-race`

- swarm/pss/forwarding_test.go
- swarm/pss/pss_test.go
closes https://github.com/ethersphere/go-ethereum/issues/1190
> swarm/pss: Remove pss service leak in test

- swarm/storage/filestore.go
- swarm/storage/filestore_test.go
This PR adds an endpoint to `FileStore` which allows to get a list of hashes for a given file.
It has been discussed in the swarm team at https://github.com/ethersphere/go-ethereum/pull/1185 and reopened here for merging.
It is part of the solution for issue https://github.com/ethersphere/go-ethereum/issues/1099
> swarm: Get all chunk references for a given file

- cmd/puppeth/wizard_genesis.go
This PR fixes two tiny puppeth bugs:
* When Petersburg was explicitly enabled (i.e. different block), the wizard always tried to fall back to the Constantinople number, even if Petersburg was different. This PR fixes it so it only defaults to Constantinople if Petersburg is nil.
* A minor bug that surfaces is also fixed whereby the genesis wasn't saves to puppeth's config after fork rule updates.
> cmd/puppeth: handle pre-set Petersburg number, save changed fork rules

- cmd/faucet/faucet.go
- cmd/geth/chaincmd.go
- cmd/geth/consolecmd.go
- cmd/geth/main.go
- cmd/swarm/main.go
- console/console_test.go
- miner/stress_clique.go
- miner/stress_ethash.go
- mobile/geth.go
- node/config_test.go
- node/node.go
- node/node_example_test.go
- node/node_test.go
- node/service_test.go
- p2p/simulations/adapters/inproc.go
- p2p/simulations/network.go
This PR is a second take on fixing the AccountsManager leak on node.Node. The first PR was rejected https://github.com/ethereum/go-ethereum/pull/18505.
Fixes: https://github.com/ethersphere/go-ethereum/issues/1142.
Swarm PR: https://github.com/ethersphere/go-ethereum/pull/1194.
While performing the test described in https://github.com/ethersphere/go-ethereum/issues/1142 issue, a large number of gorutines were created and not terminated. Stack trace shows many goroutines:
```
goroutine 3370 [select]:
github.com/ethereum/go-ethereum/accounts.(*Manager).update(0xc0000b7520)
/Users/janos/go/src/github.com/ethereum/go-ethereum/accounts/manager.go:95 +0x22a
created by github.com/ethereum/go-ethereum/accounts.NewManager
/Users/janos/go/src/github.com/ethereum/go-ethereum/accounts/manager.go:68 …
```
> node, p2p/simulations: fix node.Node AccountsManager leak

- mobile/types.go
Adds the ability to create new contracts from the mobile package.  It follows the same signature as NewContractCreation as in the types package w tweaks along the lines of what NewTransaction is doing in the mobile pkg.
> mobile - adds ability to create transactions for creating contracts

- light/lightchain.go
Currently half the files use `lc` and the other half use `self` for the receiver variable name. This adopts `lc` as it is is more idiomatic golang.
> light: make LightChain receiver names consistent

- contracts/chequebook/api.go
- contracts/chequebook/cheque.go
- contracts/chequebook/contract/chequebook.go
- contracts/ens/contract/ens.go
- contracts/ens/ens.go
- swarm/swarm.go
In the contracts directory, I have updated the variable names for receivers generating a golint warning regarding use of generic names like this or self.
> contracts/*: golint updates for this or self warning

- cmd/swarm/swarm-smoke/feed_upload_and_sync.go
- cmd/swarm/swarm-smoke/main.go
- cmd/swarm/swarm-smoke/sliding_window.go
- cmd/swarm/swarm-smoke/upload_and_sync.go
- cmd/swarm/swarm-smoke/upload_speed.go
- cmd/swarm/swarm-smoke/util.go
- swarm/testutil/file.go
This PR is:
1. Removing the `generateEndpoints` methods, and just uses the `hosts` provided to the command. Then we can target easily `http` or `ws` or any other endpoint, depending on what command we run.
2. Updating `wrapCliCommand` to NOT abstract the timeout handling per command.
3. Reverting changes to the `upload` method, so that we have access to the actual random content used in the smoke tests (necessary so that we can get all chunk hashes, in case of fetch failure).
Also adds logs for duration of tests and global test identifier.
> cmd/swarm/swarm-smoke: refactor generateEndpoints

- cmd/utils/flags.go
- common/size.go
- common/size_test.go
- core/blockchain.go
- core/blockchain_insert.go
- eth/backend.go
- ethdb/database.go
This is a partial solution for https://github.com/ethereum/go-ethereum/issues/16237 and https://github.com/ethereum/go-ethereum/issues/18984 so that archive mode does not hog the write cache memory allowance, since it doesn't keep dirty stuff in memory either way. Might as well use all that memory for the read cache.
It does not yet fully address the issue, since we also need a mechanism to move dirty stuff into the write cache on commit, so don't close the linked issues on merge.
Benchmark running on [mon08/mon09](https://app.datadoghq.com/dashboard/u6g-jmw-28b/experimental-64-vs-master-129-2?to_ts=1549376820000&tpl_var_exp=mon08.ethdevops.io&live=true&is_auto=false&tpl_var_master=mon09.ethdevops.io&tile_size=m&from_ts=1549373220000&page=0). I'm not seeing any significant enough …
> cmd/utils, eth: relinquish GC cache to read cache in archive mode

- internal/ethapi/api.go
Using a node which isn't particularly synced at all
```
INFO [02-07|12:03:31.676] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}"
...
INFO [02-07|12:03:31.714] Loaded most recent local header          number=249053 hash=049228…c4077c td=1067030628162730226 age=3y5mo1w
INFO [02-07|12:03:31.714] Loaded most recent local full block      number=0      hash=d4e567…cb8fa3 td=17179869184         age=49y9mo3w
INFO [02-07|12:03:31.714] Loaded most recent local fast block      number=248199 hash=2ee315…410c90 td=1061919596019900131 age=3y5mo1w
```
This PR changes the behaviour to use eip-155 replay …
> ethapi: default to use eip-155 protected transactions

- core/blockchain.go
- core/blockchain_test.go
- core/chain_makers.go
This PR adds a testcase to reproduce the crash in #18977. What happens is 
1. A chain `A` has `N` blocks at td `Ta`. 
2. A sidechain `B` has `M` blocks at td `Tb`. `Tb` > `Ta`. 
3. However, the `B` chain consists of a lot _more_ blocks, so that at the point where `Tb` surpasses `Ta`, the block number is more than `128` blocks ahead of the head of `A`.  
Todo: @karalabe take it from here and make the test pass. 
---
@karalabe: Done.
The issue was that when we import very long sidechains, we only reorg the canonical numbers **after** we exceed the local chain's TD. The pruner however used canonical numbers to figure out which trie to commit when. Since canonical numbers are unavailable until sidechain import is actually done, the pruner accessed non-indexed headers and crashed.
The fix is …
> core: repro #18977

- swarm/network/fetcher.go
- swarm/network/fetcher_test.go
- swarm/network/stream/delivery.go
- swarm/network/stream/messages.go
- swarm/network/stream/peer.go
- swarm/network/stream/stream.go
- swarm/storage/chunker.go
- swarm/storage/feed/testutil.go
- swarm/storage/netstore.go
- swarm/storage/netstore_test.go
This PR is an incremental part of https://github.com/ethersphere/go-ethereum/issues/1181 whose description is:
> At the moment if you send a GET request to Swarm for a specific content, you don't get proper tracing information in Jaeger, because the context propagation is broken.
> We need to fix this, so that we can see detailed traces of specific GET (or POST) requests and compare fast requests to slow requests in order to understand why we have a high variance for upload/download in smoke tests.
----
Specifically, the effect of this PR should be that the current context path is in correct hierarchical order:
1. HTTP GET
2. LazyChunkReader Read/Size/Seek
3. Stream request
4. Stream deliver
Furthermore, within the stream package it also makes sure the trace span finish executes _after_ …
> swarm/network, swarm/storage: Preserve opentracing contexts

- swarm/pss/client/client_test.go
- swarm/pss/forwarding_test.go
- swarm/pss/notify/notify_test.go
- swarm/pss/pss.go
- swarm/pss/pss_test.go
- swarm/pss/types.go
PSS message format conform with Whisper v.6
clone of https://github.com/ethersphere/go-ethereum/pull/1207
fixes https://github.com/ethersphere/go-ethereum/issues/663
> swarm/pss: transition to whisper v.6

- swarm/network/networkid_test.go
- swarm/network/simulations/overlay_test.go
- swarm/network/stream/snapshot_retrieval_test.go
- swarm/storage/common_test.go
- swarm/storage/ldbstore_test.go
- swarm/storage/memstore_test.go
- couple of context timeout adjustments so tests won't exceed context deadline when running on Travis with `-race`
- decreased the node count for `TestOverlaySim` simulations so that we won't run out of memory on Travis
- I removed a few unused method parameters
relates to: https://github.com/ethersphere/go-ethereum/issues/741
> swarm: CI race detector test adjustments

- swarm/docker/Dockerfile
Creating separate images for `swarm`,  `swarm-smoke` and `swarm global-store`.
Each image can be build individually by using the `--target` flag during `docker build`.
> swarm/docker: add global-store and split docker images

- .travis.yml
- build/ci-notes.md
- build/ci.go
- build/dput-launchpad.cf
This switches PPA uploads to SFTP because Travis doesn't support FTP anymore. Keys are already configured on both Launchpad and Travis, so uploads should start working right after this PR is merged.
> build: use SFTP for launchpad uploads

- accounts/external/backend.go
- cmd/clef/intapi_changelog.md
- cmd/clef/main.go
- cmd/clef/tests/testsigner.js
- internal/ethapi/api.go
- internal/web3ext/web3ext.go
- signer/core/api.go
- signer/core/cliui.go
- signer/core/signed_data.go
- signer/core/stdioui.go
This is a follow-up PR to fix issues after the merging of external-signer, bidirectional communication and implementation of eip 712/192. 
It contains
One thing still remaining is to display remote and local address for ipc communication, but that can be left for a later PR.
> clef: make external signing work + follow up fixes

- cmd/clef/extapi_changelog.md
- cmd/clef/intapi_changelog.md
- cmd/clef/main.go
- signer/core/api.go
- signer/core/api_test.go
- signer/core/auditlog.go
- signer/core/cliui.go
- signer/core/stdioui.go
- signer/core/types.go
- signer/core/uiapi.go
- signer/rules/rules.go
- signer/rules/rules_test.go
This is a follow-up PR after https://github.com/ethereum/go-ethereum/pull/19003 . 
This PR implements bidirectional communication between clef and the UI. It resurrects most of the methods from the personal namespace in geth:
- `clef_listWallets` 
- `clef_listAccounts`
- `clef_listWallets`
- `clef_deriveAccount`
- `clef_importRawKey`
- `clef_openWallet`
- `clef_chainId`
- `clef_setChainId`
- `clef_export`
- `clef_import`
It also thus removed `Export` from the external namespace.
> clef: bidirectional communication with UI

- rpc/stdio.go
This is a very simple PR that makes it possible to use `stdio` communication over custom channels, not only os.stdin and stdout. 
This makes it possible to use a stdio connection from the UI, who wants to use the `clef` process `stdin/stdout` as communication channels for json-rpc. So this PR only makes it possible for the UI to reuse the bidirectoinal library in go-ethereum, and doesn't actually change anything in go-ethereum.
> rpc: make stdio usable over custom channels

- swarm/pss/protocol.go
release mutex before returning from the function
clone of https://github.com/ethersphere/go-ethereum/pull/1218
> swarm/pss: mutex lifecycle fixed

- swarm/storage/filestore.go
This PR fixes the `HashExplorer` concurrency bug introduced with PR https://github.com/ethereum/go-ethereum/pull/19002.
fixes ethersphere/go-ethereum#1206
> swarm/storage: fix HashExplore concurrency bug ethersphere#1211

- accounts/abi/bind/backends/simulated.go
- accounts/abi/bind/backends/simulated_test.go
We are writing a little tool that allows us to poll for a transaction to complete and would like to test it using the SimulatedBackend. It did not yet have `TransactionByHash` function that ethclient.Client has, so this PR adds it and allows SimulatedBackend to conform to TransactionReader interface.
> add TransactionByHash to SimulatedBackend

- swarm/swarm.go
This PR addresses a goroutine leak in test environment that would appear in the edge case where multiple tests would call the same service' Start method.
fixes https://github.com/ethersphere/go-ethereum/issues/1156 by introducing cleanup functions to allow for custom shutdown callbacks.
> swarm: fix uptime gauge update goroutine leak

- swarm/network/stream/delivery_test.go
- swarm/network/stream/snapshot_retrieval_test.go
- swarm/storage/netstore.go
this PR addresses a possible race when shutting down the netstore while fetchers are still running.
fixes https://github.com/ethersphere/go-ethereum/issues/1197 by iterating over the fetchers and cancelling them then wait for the cancellation to propagate.
> swarm/storage/netstore: add fetcher cancellation on shutdown

- eth/tracers/tracers_test.go
> eth/tracers: enforce mixed caps variable names

- light/odr_util.go
- light/trie.go
> light: enforce mixed caps variable names

- common/fdlimit/fdlimit_windows.go
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/22371334/job/33r0511n4v64pya4#L147
> common/fdlimit: fix windows build

- swarm/network/kademlia.go
- swarm/network/kademlia_test.go
- swarm/network/simulation/kademlia.go
- swarm/network/simulations/discovery/discovery_test.go
This PR introduces a new implementation for saturation.
Saturation is a prerequisite to consider a network healthy.
This is reflected with the new `Healthy()` method.
A new function `isSaturated()` has been added, which will check the list of unsaturated bins (array of `int`) and return a `bool`, `true` for saturated and `false` for not.
It is considered saturated if the length of the array is zero (equivalent to all bins below depth have the saturation criteria fulfilled) and the `depth` is equal to the length of the `peersPerBin`.
A bin is saturated if we have connections >= `MinBinSize` or, if there are less connections than `MinBinSize`, the number of connections corresponds to the available number of peers in the `PeerPot`.
Closes …
> swarm/network: Saturation check for healthy networks

- core/tx_pool_test.go
> core: enforce mixed caps variable names

- console/console.go
> console: prefer nil slices over zero-length slices

- cmd/abigen/main.go
- cmd/geth/monitorcmd.go
- cmd/geth/usage.go
- cmd/swarm/access.go
- cmd/swarm/access_test.go
- cmd/swarm/fs.go
- cmd/swarm/swarm-smoke/sliding_window.go
- cmd/utils/flags.go
> cmd/*: prefer nil slices over zero-length slices

- swarm/storage/ldbstore.go
This PR fixes a broken GC metric that was wrongly reported to InfluxDB
> swarm/storage: fix influxdb gc metrics report

- swarm/pss/keystore.go
- swarm/pss/protocol.go
- swarm/pss/pss.go
split pss and keystore.
keystore-related code moved to a separate file.
clone of https://github.com/ethersphere/go-ethereum/pull/1222
fixes https://github.com/ethersphere/go-ethereum/issues/1214
> swarm/pss: refactoring

- p2p/simulations/connect.go
- p2p/simulations/events.go
- p2p/simulations/http_test.go
- p2p/simulations/mocker_test.go
- p2p/simulations/network.go
- p2p/simulations/network_test.go
- swarm/network/simulation/node.go
- swarm/network/simulation/node_test.go
- swarm/network/simulation/service.go
- swarm/network/simulation/simulation_test.go
- swarm/network/simulations/overlay_test.go
- swarm/state/dbstore.go
This PR wraps the `Node.Up` field value by using a getter and setter with granular locking. 
`Node.Up` was often accessed concurrently without an accurate locking mechanism; Instead, a lock was placed on the entire `Network`. In addition, a proper lock was missed at certain points, which in turn caused a possible data race. 
fixes https://github.com/ethersphere/go-ethereum/issues/1146
> p2p, swarm: fix node up races by granular locking

- vendor/github.com/allegro/bigcache/bigcache.go
- vendor/github.com/allegro/bigcache/entry_not_found_error.go
- vendor/github.com/allegro/bigcache/queue/bytes_queue.go
- vendor/github.com/allegro/bigcache/shard.go
- vendor/vendor.json
This PR updates bigcache after some unknown hero fixed a couple of data-corruption bugs (ref https://github.com/allegro/bigcache/pull/119 )
> vendor: update bigcache

- cmd/swarm/swarm-smoke/main.go
- cmd/swarm/swarm-smoke/upload_and_sync.go
Swarm now has a `GetAllReferences()` call, which can return a list of all references for a given file, and the `Has(chunkAddresses []storage.Address)` RPC endpoint, through which a node can be queried if it is locally storing the set of chunk references in the parameters.
This PR implements ticket https://github.com/ethersphere/go-ethereum/issues/1196, which requests that for debugging purposes, if a smoke test times out, the set of nodes in a cluster is queried for each of the references of the test file, in order to evaluate which of the nodes does not have the requested chunks.
It is thus only relevant in the realm of the smoke test.
> cmd/swarm/swarm-smoke: Trigger chunk debug on timeout

- node/config.go
- node/node.go
> node: prefer nil slices over zero-length slices

- swarm/swarm.go
A regression has occurred at some point in `swarm:Swarm` service object, where the call for adding devp2p protocols to `Pss`. Has disappeared. This PR reinstates this call, and also adds a nugget of golang regime compliance for pointer receiver names.
> swarm: Reinstate Pss Protocol add call through swarm service

- rpc/websocket.go
This corrects the previous change which broke the build and
was pushed to master by accident. 
This closes #16608.
> rpc: fixup change to not verify websocket origin

- cmd/clef/main.go
- eth/config.go
- node/defaults.go
since windows XP `$APPDATA (%APPDATA%)` is used.
Please see also
- http://environmentvariables.org/AppData
- https://www.askvg.com/list-of-environment-variables-in-windows-xp-vista-and-7/
for normal windows native environment, `%HOME%(C:\Users\foobar) + \AppData\Roaming` is correctly interpreted as `%APPDATA%`, but for cygwin/msys2 environment or powershell, `%HOME%` is `/home/foobar/` and `%HOME%` + `\AppData\Roaming` is not `%APPDATA%` anymore.
Simply using `%APPDATA%` fix this issue.
> eth, node: use APPDATA env to support cygwin/msys correctly

- crypto/signature_cgo.go
- crypto/signature_nocgo.go
Package crypto works with or without cgo, which is great. However, to make it
work without cgo required setting the build tag `nocgo`. It's common to disable
cgo by instead just setting the environment variable `CGO_ENABLED=0`. Setting
this environment variable does _not_ implicitly set the build tag `nocgo`. So
projects that try to build the crypto package with `CGO_ENABLED=0` will fail. I
have done this myself several times. Until today, I had just assumed that this
meant that this package requires cgo.
But a small build tag change will make this case work. Instead of using `nocgo`
and `!nocgo`, we can use `!cgo` and `cgo`, respectively. The `cgo` build tag is
automatically set if cgo is enabled, and unset if it is disabled.
You can test this change by running:
CGO_ENABLED=0 go test …
> crypto: fix build when CGO_ENABLED=0

- trie/database.go
- trie/proof.go
- trie/sync.go
- trie/sync_test.go
> trie: prefer nil slices over zero-length slices

- eth/api_tracer.go
Simplifies the transaction presense check to use a function to
determine if the transaction is present in the block provided
to trace, which originally had a redundant parenthesis and used
a `exist` flag to dictate control flow.
> eth: extract check for tracing transaction in block file

- p2p/simulations/network_test.go
> p2p/simulations: enforce mixed caps variable names

- accounts/abi/bind/backends/simulated.go
- accounts/abi/bind/backends/simulated_test.go
- accounts/abi/bind/base_test.go
addresses feedback provided after the merge from the PR https://github.com/ethereum/go-ethereum/pull/19026
* adds mutex lock/unlock to `TransactionByHash`
* adds copyright header to simulated_test.go (file added in the prior PR) and base_test.go (was missing before my PR)
* removes named returns from `TransactionByHash`
* removes blank lines
> accounts/abi: mutex lock in TransactionByHash and code cleanup

- downloads/index.html
This PR modifies the release listing code to first gather all the releases from potentially multiple Azure blobstore pages and only then run the injection. Fixes https://github.com/ethereum/go-ethereum/issues/19042.
> downloads: handle multi-page results from Azure

- swarm/network/kademlia.go
- swarm/network/stream/stream.go
This PR fixes a leak discovered in https://github.com/ethersphere/go-ethereum/issues/1233. The reason is not terminated goroutines from the stream NewRegistry function. This change handles their termination.
To verify the fix: `time go test -v -race -run TestGetSubscriptionsRPC -count 1000 github.com/ethereum/go-ethereum/swarm/network/stream`
Swarm PR: https://github.com/ethersphere/go-ethereum/pull/1237
fixes: ethersphere/go-ethereum#1233
> swarm/network/stream: fix a goroutine leak in Registry

- swarm/network/protocol.go
- swarm/network/protocol_test.go
Resolves https://github.com/ethersphere/go-ethereum/issues/1219 (see description below) by extracting the remote address of the `p2p.Peer` and overwriting the `BzzAddr.UAddr` if they differ.
This is a temporary fix awaiting ENR refactor.
---
Example; Nodes `A`, `B` and `C` are started without `--nat` flag. Their enode strings _used in the swarm handshake_ will all have localhost.
You find a subnet ip for `A` that's reachable from `B` and `C`. You replace the localhost in the enode string with this ip. Then you execute RPC call `admin.addPeer` with that enode string to `B` and `C`. 
**Result: `B` and `C` will have connected to `A`, but not have connected to each other.**
It seems that in the discovery protocol, `B` and `C` still "convince" A that they exist on localhost, and when A …
> swarm/network: Use actual remote peer ip in underlay

- swarm/network/stream/delivery.go
- swarm/network/stream/messages.go
- swarm/network/stream/peer.go
- swarm/network/stream/stream.go
- swarm/storage/filestore_test.go
- swarm/storage/netstore.go
- swarm/swarm.go
- swarm/tracing/tracing.go
This PR addresses https://github.com/ethersphere/go-ethereum/issues/1209 (see copy of description below) which is an incremental part of https://github.com/ethersphere/go-ethereum/issues/1181
Until now, the spans are only valid within internal peer contexts, but we may want to trace durations from _node makes request_ to _node received delivery_. 
According to `opentracing` support, if a `Span` is to persist across asynchronous operations, it's the requester's responsibility to _remember_ the `Span` and `Finish()` it accordingly. In other words, a `Span` cannot be recalled after passing through the `tracer.Inject()`/`tracer.Extract()` serialization, only _new_ spans (`ChildOf()`, `FollowFrom()`) can be created from the `SpanContext` that's passed on.
To this end, I've introduced a "store" …
> swarm/network: Keep span across roundtrip

- swarm/network/simulations/discovery/discovery_test.go
- swarm/network/stream/delivery_test.go
- swarm/network/stream/snapshot_retrieval_test.go
- swarm/network/stream/snapshot_sync_test.go
- swarm/network/stream/streamer_test.go
- swarm/network/stream/syncer_test.go
- swarm/network/stream/visualized_snapshot_sync_sim_test.go
- swarm/network_test.go
- swarm/storage/common_test.go
- swarm/storage/localstore/gc_test.go
- swarm/storage/localstore/subscription_pull_test.go
- swarm/testutil/norace.go
- swarm/testutil/race.go
The goal is to make all tests stable and passing on Travis with `-race` flag. ASAP. We might create separate tickets to remove skip/resource restrictions on tests.
Travis has limited resources. We mostly hit memory limitations, but sometimes time limits, too. With `testutil.RaceEnabled` bool we can detect if we are running with `-race` and skip resource heavy tests cases, while still keeping the smaller ones to benefit from race detection.
fixes https://github.com/ethersphere/go-ethereum/issues/1226
> Ci race detector handle failing tests

- cmd/swarm/global-store/global_store_test.go
This PR addresses issue with timeouts in cmd/swarm/global-store tests on windows. A subprocess needs to be terminated using Kill method not Interrupt.
fixes: ethersphere/go-ethereum#1229
> swarm: fix global-store cmd tests on windows

- swarm/storage/ldbstore.go
The current loop continuation condition is always true as a uint8
is always being checked whether it is less than 255 (its maximum
value). Since the loop starts with the value 1, the loop termination
can be guarranteed to exit once the value overflows to 0.
> swarm/storage: fix loop bound for database cleanup

- common/fdlimit/fdlimit_freebsd.go
cast limit.Cur (int64) to uint64, fix test and compilation error
> common/fdlimit: Fix compilation error in freebsd, Raise returns uint64

- core/blockchain.go
- core/blockchain_test.go
This PR adds some testcases regarding sidechain import, specifcally trying to repro the situation described in #19105. 
- A sidechain is imported, but the chain contains a few blocks which are already in the canon chain.
- Those blocks would trigger a `ErrKnownBlock` error, and be ignored, 
- After that, the first sidechain block would not wind up in `insertSideChain`, which depends on the first block to have been an `errPrunedAncestor` error. 
This PR addresses that by removing already canonical blocks from the chain to be inserted, in the pre-flight check in `InsertChain`.
> blockchain: more tests for sidechain import, fixes #19105

- core/blockchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/accessors_indexes.go
- core/rawdb/accessors_indexes_test.go
- core/rawdb/schema.go
- core/types/gen_log_json.go
- core/types/log.go
- core/types/receipt.go
- eth/backend.go
- les/handler.go
- les/handler_test.go
- les/protocol.go
This PR drop some unnecessary fields in `Recepit`, `TxLookup` and `TransactionLog` structs to save database storage.
> core: remove unnecessary fields in log

- swarm/network/stream/stream.go
- swarm/network/stream/syncer.go
This PR addresses issue described in https://github.com/ethersphere/go-ethereum/issues/1242 where a panic is raised when leveldb database is closed while iterator is active.
This changes do not fix the issue completely but make it much less possible. Preventing handling messages after stream Registry is closed reduces the possibility of this case drastically. The second change addresses the termination of iterator when the database is closed. It is still possible that the panic will raise but much less likely.
The complete way to prevent this panics is to wait for all messages to be handled inside Registry Close method. But, this would require a wait group which can not be used correctly only inside the stream package. There is a data race between waitgroup Wait and Add methods if they …
> swarm/network/stream: protect SetNextBatch iterator after close

- swarm/shed/db.go
This PR simplifies the cancelation of shed meter function that runs in the background. Since the quitChan was only closed in the code, it return value was always a nil channel causing the deadlock in send at the end of that function. All of the log messages are the same as the errors passed to the channel that were never read from.
fixes: ethersphere/go-ethereum#1250
> swarm/shed: fix a deadlock in meter function

- .travis.yml
If repo name changes, the android build will fail as the package path is no longer `github.com/ethereum/go-ethereum`. 
The fix is to make the symlink explicitly point to `go-ethereum`.
> .travis.yml: make build independent of repo name

- .travis.yml
- build/travis_keepalive.sh
We had more than a dozen of Data Races in Swarm code base. Go has a nice builtin race detector tool. So we should have a CI job that leverages the tool.
*Notes*:
- Some jobs are freshly restricted to `repo = ethereum/go-ethereum `. That is just an improvement, I can let go. I noticed the mentioned job run on my fork, they still passed (strangely), but I did not have the credentials.
- The most important part is only (intended) to impact [ethersphere/go-ethereum], but this is still a common code base so we need more reviewers.
resolves ethersphere/go-ethereum#741
resolves ethersphere/go-ethereum#1102
> travis.yml: add race detector job for Swarm

- swarm/storage/localstore/gc.go
- swarm/storage/localstore/gc_test.go
- swarm/storage/localstore/localstore.go
- swarm/storage/localstore/localstore_test.go
- swarm/storage/localstore/subscription_pull_test.go
- swarm/storage/localstore/subscription_push_test.go
This PR addresses the issue with sending error to an errChan while inside a mutex lock in readPullSubscriptionBin test function. This PR does not address why that error happened since this errors are reproducible only on travis with race detector. Additionally, this PR includes closing of localstore DB in one test and one benchmark that was missed earlier.
Pull subscription tests are enabled for travis with race detector, even a different error should be returned by this tests, which I only expect and cannot reproduce.
Swarm PR https://github.com/ethersphere/go-ethereum/pull/1253.
fixes: ethersphere/go-ethereum#1245
> swarm: Fix localstore test deadlock with race detector

- cmd/swarm/global-store/explorer.go
- cmd/swarm/global-store/explorer_test.go
- cmd/swarm/global-store/global_store.go
- cmd/swarm/global-store/global_store_test.go
- cmd/swarm/global-store/main.go
- swarm/storage/mock/db/db.go
- swarm/storage/mock/db/db_test.go
- swarm/storage/mock/explorer/explorer.go
- swarm/storage/mock/explorer/explorer_test.go
- swarm/storage/mock/explorer/headers_test.go
- swarm/storage/mock/explorer/swagger.yaml
- swarm/storage/mock/mem/mem.go
- swarm/storage/mock/mem/mem_test.go
- swarm/storage/mock/mock.go
- swarm/storage/mock/rpc/rpc.go
- swarm/storage/mock/rpc/rpc_test.go
- swarm/storage/mock/test/test.go
This PR changes mock.GlobalStore implementations to implement keys and nodes listings with pagination. This requires changing the internal storage structure for mem and db implementations. And rpc implementation requires only two values returned by the listing methods in order to be rpc method. Because of that types KeysResponse and NodesResponse are added.
This PR also integrates new methods into global-store binary by exposing the http api (mock/explorer) that can be accessed by browser or other clients to inspect chunk distribution. The api definition is represented in swagger.yaml.
Reviews can be split into two parts, one that addresses changes to the existing mock.GlobalStore implementations db, mem and rpc; and one that addresses the new functionality used in global-store binary …
> swarm: mock store listings

- swarm/network/simulation/node.go
This PR addresses the issue with coping `upMu` mutex that was recently added to the p2p/simulations.Node.
```sh
$ go vet github.com/ethereum/go-ethereum/swarm/network/simulation                                                        (git)-[master] 
swarm/network/simulation/node.go:225: range var n copies lock: github.com/ethereum/go-ethereum/p2p/simulations.NodeSnapshot contains github.com/ethereum/go-ethereum/p2p/simulations.Node contains sync.RWMutex
```
Swarm PR: https://github.com/ethersphere/go-ethereum/pull/1261
> swarm/network/simulation: do not copy node mutex in UploadSnapshot

- rlp/decode.go
This pr introduces a pool of Stream objects to eliminate the need to reallocate memory for every new Stream. It should help to improve the performance of every call to Decode and Decode bytes. 
New streams will be allocated whenever needed.
> rlp: pool decode streams

- swarm/pss/client/client_test.go
- swarm/pss/handshake.go
- swarm/pss/handshake_test.go
- swarm/pss/keystore.go
The HandshakeController.symKeyIndex map was accessed concurrently.
Since insufficient test coverage the race is not detected every time.
However, running TestClientHandshake a 100 times seems to be enough to
reproduce the race.
Note: I've chosen HandshakeController.lock to protect
HandshakeController.symKeyIndex as that was already protected in a few
functions by that lock.
Additionally:
- removed unused testStore
- enabled tests in handshake_test.go as they pass
- removed code duplication by adding getSymKey()
Swarm PR: https://github.com/ethersphere/go-ethereum/pull/1266
fixes https://github.com/ethersphere/go-ethereum/issues/1255
fixes https://github.com/ethersphere/go-ethereum/issues/1270
> swarm/pss: fix data race on HandshakeController.symKeyIndex

- .travis.yml
- build/ci.go
Fixes Android builds broken due to https://github.com/golang/mobile/commit/ca80213619811c2fbed3ff8345accbd4ba924d45.
**Note, this PR enabled the Android build job. That's a temporary thing to see whether builds work properly without having to merge. I'll revert that change when builds are green.**
> travis, build: switch to NDK 19b, fix gomobile builds

- swarm/chunk/chunk.go
- swarm/chunk/proximity_test.go
- swarm/storage/chunker.go
- swarm/storage/common_test.go
- swarm/storage/error.go
- swarm/storage/hasherstore.go
- swarm/storage/ldbstore.go
- swarm/storage/ldbstore_test.go
- swarm/storage/localstore.go
- swarm/storage/localstore/gc_test.go
- swarm/storage/localstore/index_test.go
- swarm/storage/localstore/localstore.go
- swarm/storage/localstore/localstore_test.go
- swarm/storage/localstore/mode_get.go
- swarm/storage/localstore/mode_get_test.go
- swarm/storage/localstore/mode_put.go
- swarm/storage/localstore/mode_put_test.go
- swarm/storage/localstore/mode_set.go
- swarm/storage/localstore/mode_set_test.go
- swarm/storage/localstore/retrieval_index_test.go
- swarm/storage/localstore/subscription_pull.go
- swarm/storage/localstore/subscription_pull_test.go
- swarm/storage/localstore/subscription_push.go
- swarm/storage/localstore/subscription_push_test.go
- swarm/storage/localstore_test.go
- swarm/storage/netstore_test.go
- swarm/storage/pyramid.go
- swarm/storage/types.go
Allow localstore package to be imported in store package
by moving all chunk related types, variables and functions
to the chunk package and aliasing them into the storage package
for backward compatibility. With this, localstore package does
not import anything from storage package allowing the localstore
to be implemented into storage types.
This PR is required for localstore integration into NetStore and other
storage types. This is the minimal change to break a cyclic import between
storage and localstore. Type aliases and assignments in storage package
can be removed and reimported from the chunk package in other packages
that use them, but this would make a larger PR to review. Maybe that can
be done later as a separate task.
Tests are passing locally, and I assume that this PR can …
> swarm/chunk: move chunk related declarations to chunk package

- vendor/github.com/syndtr/goleveldb/leveldb/db.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_snapshot.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_transaction.go
- vendor/github.com/syndtr/goleveldb/leveldb/session.go
- vendor/github.com/syndtr/goleveldb/leveldb/table.go
- vendor/github.com/syndtr/goleveldb/leveldb/version.go
- vendor/vendor.json
This PR includes a leveldb fix for long time compaction.
The upstream PR is [here](https://github.com/syndtr/goleveldb/pull/264). Open this PR for experiment right now.
> vendor: update leveldb

- .travis.yml
- Dockerfile
- Dockerfile.alltools
- appveyor.yml
- common/fdlimit/fdlimit_darwin.go
- common/fdlimit/fdlimit_windows.go
- core/tx_pool_test.go
- crypto/bn256/cloudflare/main_test.go
- crypto/bn256/google/main_test.go
- internal/build/util.go
Release notes: https://golang.org/doc/go1.12
> Upgrade to Go 1.12

- cmd/swarm/swarm-snapshot/create.go
- cmd/swarm/swarm-snapshot/create_test.go
- cmd/swarm/swarm-snapshot/main.go
- swarm/network/simulation/kademlia.go
- swarm/network/simulation/kademlia_test.go
addresses https://github.com/ethersphere/go-ethereum/issues/1263
This PR corrects two problems with the existing `WaitTillHealthy` implementation.
1. The healthy check only called `ConnectNN`, should instead call `Healthy()`
2. The kademlias being checked were only from the nodes that were _up_ at the time. It should instead include all nodes that are in the simulation.
> swarm/network: WIP consider all nodes for healthy iteration

- node/defaults.go
This avoids path inconsistencies on Windows XP.
Hat tip to @MicahZoltu for catching this so quickly.
> node: require LocalAppData variable

- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/enode/nodedb.go
- p2p/enode/nodedb_test.go
I added localItemKey for this purpose in #18963, but then
forgot to actually use it. This changes the database layout
yet again and requires bumping the version number.
> p2p/enode: use localItemKey for local sequence number

- core/types/log.go
- core/types/receipt.go
https://github.com/ethereum/go-ethereum/pull/17106 reworked our database schema to store less redundant data. To cater for old nodes upgrading, loading the data was extended to first try to access new formats, and if that fails, try the old format.
The log and receipt decoder was unfortunately not implemented fully correctly, as they were operating on an RLP stream. If the loader that tried to access the new format fails, it already advanced the RLP stream and read the first few bytes, so the legacy format decoder would always fail.
This PR fixes it by first loading the entire next RLP raw item from the stream, and then attempting to decode the entire thing first in the new format, then in the legacy one.
> core/types: fix receipt legacy decoding

- crypto/bn256/cloudflare/mul_arm64.h
Pull in https://github.com/cloudflare/bn256/pull/4 to fix the R18 reservation on ARM64 introdued in Go 1.12 https://github.com/golang/go/issues/26110.
> crypto/bn256/cloudflare: pull in upstream fix for Go 1.12 R18

- build/deb/ethereum-swarm/deb.rules
- build/deb/ethereum/deb.rules
Launchpad by default sets the `$HOME` directory to `/sbuild-nonexistent`, which does not exist. The idea is that builders should not touch anything in HOME. Unfortunately Go 1.11+ uses `$HOME/.cache/go-build` by default as a build cache, failing with a permission denied error.
This PR points the build cache to `/tmp`. No idea if this will work or not.
> build/deb: use custom cache for PPA builder

- cmd/swarm/main.go
- swarm/api/inspector.go
- swarm/network/kademlia.go
This PR is re-enabling p2p discovery, but disabling the dynamic dialling functionality - the reason why we didn't want to have the p2p discovery in the first place.
The reason for this is - the `hive` protocol and the `Kademlia` table implementation on Swarm side does not update the underlay addresses of peers. More specifically `Kademlia.Register` does not update the underlay addresses ever, but `Kademlia.On` and `Kademlia.Off` do. This means that sometimes we are left with outdated destinations for nodes in our state store.
The `p2p` package handles that with:
```
err := t.dial(srv, t.dest)
if err != nil {
log.Trace("Dial error", "task", t, "err", err)
// Try resolving the ID of static nodes if dialing failed.
if _, ok := err.(*dialError); ok && t.flags&staticDialedConn != 0 {
if …
```
> swarm: enable p2p/discovery and disable dynamic dialling

- swarm/network/protocol.go
- swarm/network/protocol_test.go
Reverts ethereum/go-ethereum#19137 due to panics when we get an IP that is not IPV4.
> swarm: Revert "swarm/network: Use actual remote peer ip in underlay"

- build/ci.go
This PR adds `clef` to the alltools docker image, and also to the `deb` packages. I'm not 100% sure I've done everything that's needed, nor how to properly verify that it works as intended. 
We can wait with this one until https://github.com/ethereum/go-ethereum/pull/19112 and https://github.com/ethereum/go-ethereum/pull/19047 are merged
> build: add clef to alltools and deb

- p2p/simulations/network.go
- swarm/network/stream/common_test.go
- swarm/network/stream/delivery_test.go
- swarm/network/stream/snapshot_retrieval_test.go
- swarm/network/stream/snapshot_sync_test.go
- swarm/network/stream/streamer_test.go
- swarm/network/stream/syncer_test.go
This PR introduces a series of bug fixes which would prevent longrunning tests to succeed.
These tests need to be enabled with the `longrunning` flag, and were up to today ignored.
We can deploy these tests now to the kubernetes test environment, allowing to have better insights about network behavior with bigger networks.
> Enable longrunning tests to run

- accounts/keystore/keystore.go
- accounts/usbwallet/hub.go
> accounts/*: prefer nil slices over zero-length slices

- consensus/clique/snapshot_test.go
I copy-pasted a test but forgot to update it. The test above the "bad" one tested that voters who are deauthorized don't get to influence future votes by voting to drop someone. The "bad" test should have tested the same thing for voting to add someone. Fixed it here.
> consensus/clique: fix test copy paste error, test what's documented

- p2p/protocols/accounting_simulation_test.go
`TestAccountingSimulation` had a race condition.
This PR fixes that race condition
fixes https://github.com/ethersphere/go-ethereum/issues/1285
> p2p/protocols: Fix race condition in TestAccountingSimulation

- swarm/network/stream/streamer_test.go
`TestGetSubscriptionsRPC` was subject to flaky behavior: https://github.com/ethersphere/go-ethereum/issues/1234
This was mainly due to timing issues: `syncUpdateDelay` affects the test, as after this `time.Duration`, syncing is kicked off again (it is a loop in `updateSyncing()`), so the number of requested subscriptions would change.
This PR introduces a check which allows counts only to happen in the first run
> swarm/network/stream: Fix flaky tests in GetSubscriptionsRPC test

- swarm/shed/db.go
- swarm/shed/index.go
- swarm/shed/index_test.go
- swarm/storage/localstore/mode_has.go
- swarm/storage/localstore/mode_has_test.go
This PR adds a new functionality required by other components to check if the chunk is stored. Hasser have no modes, since it has only one mode of operation which is not changing the state of database.
This PR is cherry picked from the localstore storage integration branch as an isolated feature.
Swarm PR https://github.com/ethersphere/go-ethereum/pull/1283
> swarm: localstore hasser

- cmd/clef/README.md
- cmd/clef/datatypes.md
- cmd/clef/intapi_changelog.md
- cmd/clef/main.go
- signer/core/api.go
- signer/core/api_test.go
- signer/core/cliui.go
- signer/core/signed_data.go
- signer/core/signed_data_test.go
- signer/core/stdioui.go
- signer/rules/rules.go
- signer/rules/rules_test.go
- signer/storage/storage.go
This PR will will break existing UIs, since it changes all calls like `ApproveSignTransaction` to be on the form `ui_approveSignTransaction`. 
This is to make it possible for the UI to reuse the json-rpc library from go-ethereum, which uses this convention.
Also, this PR removes some unused structs, after import/export were removed from the external api (so no longer needs internal methods for approval) 
One more breaking change is introduced, removing passwords from the `ApproveSignTxResponse` and the likes. This makes the manual interface more like the rulebased interface, and integrates nicely with the credential storage. Thus, the way it worked before, it would be tempting for the UI to implement 'remember password' functionality. The way it is now, it will be easy instead to tell …
> signer: changes the stdio jsonrpc to use legacy namespace conventions

- accounts/usbwallet/wallet.go
Although current two implementations(ledgerDriver, trezorDriver) of interface driver.Close do not actually return any error. Instead, they only return nil.
But since the declaration of Close function returns error, it is better to check the returned error in case in future some new implementation of Close function returns error and we may forget to modify the function which invokes Close function at that time.
> usbwallet: check error returned by driver close

- eth/downloader/statesync.go
Supersedes https://github.com/ethereum/go-ethereum/pull/19010, fixes https://github.com/ethereum/go-ethereum/issues/18525.
> eth/downloader: fix nil droppeer in state sync

- cmd/swarm/config.go
This PR fixes an edge case where the in-memory cache size flag was ignored when the size was set to `0`. As a result the cache could not be disabled.
fixes https://github.com/ethersphere/go-ethereum/issues/1267
> cmd/swarm: do not ignore cache size=0

- swarm/storage/localstore/gc_test.go
- swarm/storage/localstore/localstore.go
This PR adds a missing synchronization to TestDB_gcSize test, where recently introduced writeGCSizeWorkerDone was not read in that test to ensure that all writeGCSizeWorker iterations were finished, but not to call writeGCSize function when closing the database. This PR adds function closeWithOptions to ensure that future changes will be affective in both production code and test.
This failures were only detected on Travis.
fixes: https://github.com/ethersphere/go-ethereum/issues/1287
> swarm/storage/localstore: fix synchronization in TestDB_gcSize

- swarm/network/fetcher.go
- swarm/network/stream/peer.go
- swarm/storage/netstore.go
This PR is fixing the relationship between `stream.send.request` and `stream.handle.retrieve` spans and also stopping sibling spans when a chunk gets delivered.
> swarm: fix relationship between spans in open tracing

- p2p/protocols/accounting_simulation_test.go
- p2p/protocols/protocol_test.go
- p2p/testing/protocoltester.go
dummyHook's fields were concurrently written by nodes and read by
the test. The simplest solution is to protect all fields with a mutex.
Enable: TestMultiplePeersDropSelf, TestMultiplePeersDropOther as they
seemingly accidentally stayed disabled during a refactor/rewrite
since 1836366ac19e30f157570e61342fae53bc6c8a57.
resolves ethersphere/go-ethereum#1286
> p2p/protocols: fix data race in TestProtocolHook

- core/state/statedb.go
The account state root will never be `crypto.Keccak256Hash(nil)`. Since the empty tire root would be an empty hash (an all zero 32-byte array), an array is initialized to all zero array in stead of nil as the case in slice. The empty account root will only be `crypto.Keccak256Hash(Hash{})`, which is equal to `0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421`. So essentially, the root of a trie will never be nil, but it would be all zero hash before commit and `emptyRoot` after commit an empty trie.
I think is mistake was introduced unintentionally by the author, the object was to filter out empty accounts and never reference to them. Because it does not incur fatal error but a slight performance degrade for reference to empty trie, this problem is not unveiled before …
> state: fix emptyStatet to emptyRoot

- README.md
the user with the problem in #19246 tried to build with 1.9.1 which failed - make the README reflect this and prevent users falling in the same trap
> README: Mention go 1.10 as minumum - context #19246

- core/block_validator.go
- core/blockchain.go
- core/blockchain_insert.go
- core/blockchain_test.go
- core/types.go
This is a tiny PR to use headers in a few places where we used blocks previously, but were unnecessary.
> core: use headers only where blocks are unnecessary

- eth/downloader/downloader.go
This PR fixes the light syncing for some light clients starting syncing with a super low checkpoint(less than 3 * epoch).
> eth/downloader: fix ancestor searching for light syncing

- accounts/abi/bind/bind_test.go
- accounts/abi/bind/topics.go
- accounts/abi/bind/topics_test.go
This is a cleaned up (cherrypicked) alternative to https://github.com/ethereum/go-ethereum/pull/18957 . 
Per https://solidity.readthedocs.io/en/v0.5.3/abi-spec.html:
"bytes<M>: enc(X) is the sequence of bytes in X padded with trailing zero-bytes to a length of 32 bytes"
> bind: Static byte arrays should be right-padded

- cmd/swarm/run_test.go
- cmd/utils/flags.go
this PR adds a flag that empties the bootnodes array so that tests don't connect to our production environment.
> cmd/swarm: dont connect to bootnodes in tests

- swarm/shed/vector_uint64.go
- swarm/shed/vector_uint64_test.go
This PR adds a new field type to shed Uint64Vector, which is stores numerically identified integer counters for counting the number of chunks in every proximity order bin.
This PR reduces the change size of localstore integration PR.
Swarm PR https://github.com/ethersphere/go-ethereum/pull/1295
> swarm/shed: add vector uint64 field

- cmd/swarm/swarm-smoke/upload_and_sync.go
If one node of the deployment is offline, we are still interested in the distribution of chunks across the rest of the nodes.
> cmd/swarm/swarm-smoke: do not fail if a node does not respond to rpc

- swarm/network/simulation/kademlia.go
- swarm/network/simulation/kademlia_test.go
- swarm/pss/prox_test.go
- swarm/pss/pss.go
- swarm/pss/snapshot_test.go
Tests the message propagation in simulated networks.
based on https://github.com/ethersphere/go-ethereum/pull/1284
supercedes https://github.com/ethersphere/go-ethereum/pull/1016
closes https://github.com/ethersphere/go-ethereum/issues/987
closes https://github.com/ethersphere/go-ethereum/issues/1298
> swarm/pss: negihbourhood addressing simulation tests

- graphql/graphql.go
- graphql/schema.go
This PR reflects changes in the graphql EIP:
- Introduces a new type in the schema, `Pending`, accessible from the query object. This object encapsulates information about pending transactions.
- Moves the `account`, `call` and `estimateGas` functions from the query object to the `Block` and `Pending` objects.
Due to Geth backend API limitations, these methods can only be called on the pending state and on canonical blocks. I've added an enum to the `Block` type tracking canonical status, and an error to be emitted if someone tries, eg, using `call` on an uncle.
> graphql: Updates to graphql support to match EIP1767

- dashboard/assets/package.json
- dashboard/assets/yarn.lock
Fixing security vulnerabilities introduced by JS sub-dependencies by upgrading the `yarn.lock` file.
* `rm yarn.lock`
* `yarn install`
* `go generate dashboard`
```
for d in "lodash" "extend" "atob" "deep-extend" "cryptiles" "sshpk" "hoek" ; do yarn why $d ; done
yarn why v1.13.0
[1/4] Why do we have the module "lodash"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "lodash@4.17.11"
info Reasons this module exists
- "@babel#core" depends on it
- Hoisted from "@babel#core#lodash"
- Hoisted from "react-hot-loader#lodash"
- Hoisted from "eslint-plugin-import#lodash"
- Hoisted from "eslint-plugin-flowtype#lodash"
- Hoisted from "eslint#lodash"
- Hoisted from "webpack-merge#lodash"
- Hoisted from "recharts#lodash"
- Hoisted from …
```
> dashboard: fix github alerts

- les/handler.go
- light/lightchain.go
This PR echoes a variety of trie errors (that should not really occur, but if they do, we should definitely not silently ignore their occurrence) as warning logs.
The PR also reorganizes the proof serving code to have less nesting and instead fail on errors soon. 
Lastly, the PR also removes the `State()` method from the light server interfaces, as the light server doesn't really access the current state (which is what the point of `State()` is) rather it only needs the state **cache**. Might as well surface exactly what's needed.
> les, light: verbose errors on state retrieval issues

- les/handler.go
- les/peer.go
This PR fixes two light server bugs:
- peer.id format was wrong, it was a hex string converted to hex again
- a part of the error handling of reply send was missing, causing deadlocks at peer disconnection
> les: fix light server bugs

- cmd/swarm/swarm-smoke/main.go
- cmd/swarm/swarm-smoke/upload_and_sync.go
- metrics/influxdb/influxdb.go
- swarm/network/fetcher.go
- swarm/network/priorityqueue/priorityqueue.go
- swarm/network/stream/delivery.go
- swarm/network/stream/peer.go
- swarm/network/stream/stream.go
- swarm/storage/chunker.go
- swarm/storage/netstore.go
- swarm/swarm.go
- vendor/github.com/opentracing/opentracing-go/CHANGELOG.md
- vendor/github.com/opentracing/opentracing-go/Makefile
- vendor/github.com/opentracing/opentracing-go/README.md
- vendor/github.com/opentracing/opentracing-go/globaltracer.go
- vendor/github.com/opentracing/opentracing-go/propagation.go
- vendor/vendor.json
This PR is:
1. Updating our vendored OpenTracing Go library.
2. Adding an `inputSeed` flag to the smoke tests, so that we can reproduce an exact upload to a given Swarm deployment.
3. Executing `trackChunks` both on successful and on failed smoke test runs, so that we can compare between them.
4. Reducing amount of `Debug` and `Trace` logs in some packages.
5. Adding a timeout to the InfluxDB HTTP client, so that we don't wait indefinitely in case of a blocking InfluxDB metrics report call.
6. Adding a timer around the `f()` (generally a `p2p.Send()` call) in our priority queue.
7. Making the `stream` API private.
> swarm/network: measure time of messages in priority queue

- swarm/network/simulation/kademlia.go
- swarm/network/simulation/kademlia_test.go
- swarm/network/simulation/node.go
- swarm/network/simulation/node_test.go
- swarm/network/stream/snapshot_retrieval_test.go
- swarm/network/stream/snapshot_sync_test.go
- swarm/network/stream/streamer_test.go
- swarm/pss/prox_test.go
WaitTillSnapshotRecreated is used instead of WaitTillHealthy in case snapshot was loaded from file.
based on https://github.com/ethersphere/go-ethereum/pull/1303
closes https://github.com/ethersphere/go-ethereum/issues/1298
> p2p/simulations: wait until all connections are recreated when uploading snapshot

- trie/database.go
This is a tiny optimization that replaces the default [`fnv64a`](https://github.com/allegro/bigcache/blob/master/fnv.go) hasher with a custom hasher. The idea being, that since our keys are already hashes, we can use those directly instead of hashing it one extra time.
This will panic if a key shorter than `8` bytes is used, but at least currently, all `Set` operations are on the form `db.cleans.Set(string(hash[:]), enc)` where `hash` is a `common.Hash`, which is always `32` bytes.
> trie: disable fnv64a hashing of hashes for bigcache

- les/server.go
This PR fixes a bug in the LES server which caused it to send new block announcements to the same peer multiple times instead of once for every peer. Eventually it also triggered a disconnection from the "lucky" client because receiving many useless announcements is considered an error.
> les: fix block announcements

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- core/blockchain.go
- core/state/state_object.go
- core/state/statedb.go
- metrics/metrics.go
This PR splits block import metrics further into EVM execution time and various trie operation measurements (account/storage read/update/hash/commit).
Since these measurements are in the tight loop, they are placed behind an optional `--metrics.expensive` flag to support enabling them on benchmarkers, but not on live nodes being monitored for health checks.
> core: split out detailed trie access metrics from insertion time

- appveyor.yml
- internal/build/util.go
Travis is now using `go: 1.12.x` so doesn't need a PR every patch version bump.
Release notes: https://golang.org/doc/devel/release.html#go1.12.minor
> appveyor, Dockerfile: upgrade to Go 1.12.1

- metrics/metrics.go
This PR fixes a bug where the `--metrics` flag accidentally disabled `--metrics.expensive` if it was placed before it on the CLI arg list.
> metrics: fix expensive metrics flag processing

- core/blockchain.go
This PR fixes the incorrect subtractions for the split trie metrics. This resulted in certain high level metrics reporting larger values than real, and some smaller, going down to negative.
> core: split trie op metrics from the correct chain metrics

- core/tx_pool.go
This PR supersedes https://github.com/ethereum/go-ethereum/pull/16713 and https://github.com/ethereum/go-ethereum/pull/19216 , and resolves #19212.
It's more or less same as #19216 in the end, but with some more logging and documentation about the root cause. 
It's very easy to replicate the bug thanks to the reports above, 
```
build/bin/geth  --dev --dev.period 1
```
```
> build/bin/geth attach /tmp/geth.ipc
> miner.stop(); debug.setHead(web3.toHex(eth.blockNumber -5));miner.start()
```
> core: make txpool handle reorg due to setHead

- whisper/whisperv6/envelope.go
- whisper/whisperv6/envelope_test.go
This PR fixes two issues in the PoW calculation of a Whisper envelope, compared to the [spec](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-627.md) (see PoW Requirements):
* The pow is supposed to take the leading number of zeroes (i.e. most significant zeroes) and what it did was to take the number of trailing zeroes (i.e. least significant zeroes). It has been fixed to match what the spec and Parity does.
* The spec expects to use the size of the RLP encoded envelope, and it took something else, as described in https://github.com/ethereum/go-ethereum/issues/18070
> whisper: Fix PoW calculations to match the spec

- core/blockchain.go
- core/headerchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_indexes.go
- core/rawdb/table.go
- core/state/statedb.go
- ethdb/batch.go
- ethdb/database.go
- ethdb/leveldb/leveldb.go
- ethdb/memorydb/memorydb.go
- light/nodeset.go
- trie/database.go
This PR is a more advanced form of the dirty-to-clean cacher (https://github.com/ethereum/go-ethereum/pull/18995), where we reuse previous database write batches as datasets to uncache, saving a dirty-trie-iteration and a dirty-trie-rlp-reencoding per block.
> core, ethdb, trie: mode dirty data to clean cache on flush

- eth/api_tracer.go
Without this, the tracer will eventually run out of founds.
Fixes #19337
I am not sure whether this fix is correct. But it worked in my small usecase.
> Fixed tracing of the chain in api_tracer.go

- eth/api.go
- eth/api_backend.go
- eth/api_tracer.go
- eth/backend.go
Both the `eth.Ethereum` and the `eth.PrivateDebugAPI` stored the chain config. But the chain config can already be retrieved from the `blockchain`, which is available in both. This resulted in 3 different ways to retrieve the same configuration, which is just messy. I've removed the individual fields, making it available only from upstream `blockchain`.
> eth: remove redundant chain config fields

- core/blockchain.go
- core/rawdb/accessors_chain.go
- core/state/statedb.go
- core/state_processor.go
- core/types/gen_receipt_json.go
- core/types/gen_tx_json.go
- core/types/receipt.go
- miner/worker.go
Solves https://github.com/ethereum/go-ethereum/issues/15210 without changing consensus, in a backwards compatible way, by adding the block location fields from ReadReceipt to the Receipt struct. 
Update: In particular this improves consistency between the go client interface and the [json rpc spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt) and allows go clients to use transaction receipts to watch for block confirmations for particular transactions - see #15210.
> types, rawdb, core, miner: add block location fields to receipt

- contracts/ens/cid.go
- contracts/ens/cid_test.go
as per the discussion in https://github.com/ensdomains/ens-app/issues/113 (ENS Manager integration of EIP-1577), we are going to use `keccak256` instead of `bmt` for ENS `contentHash`es
> contracts/ens: revert bmt to keccak256

- accounts/abi/type.go
- accounts/abi/type_test.go
This PR adds the original name of the tuple component as the json-structtag.
Today, if the ABI specifies components with names `firstParameter` and `secondParameter`, go-ethereum will create a struct with fields `FirstParameter` and `SecondParameter`. Marshalling this struct directly results in a json with capitalised keys. 
Here, we add the original name found in the ABI specification as the name of the keys in the marshalled json such that the json will have keys `firstParameter` and `secondParameter`.
I find this handy when marshaling arguments to functions.
> accounts/abi:  json-structtag for tuples

- core/tx_pool.go
This is a cleaned up version of https://github.com/ethereum/go-ethereum/pull/19224, without the accidental followup commits in it.
> core: cache tx signature before obtaining lock

- accounts/abi/abi.go
- accounts/abi/abi_test.go
- accounts/abi/argument.go
- accounts/abi/bind/base.go
- accounts/abi/bind/base_test.go
- accounts/abi/bind/topics.go
- accounts/abi/unpack.go
This PR introduces an `abi.UnpackIntoMap` method which can be used to unpack an event without having had to first define a `struct` with matching field names to unpack it into. This allows for dynamic unpacking of event logs using a contract's ABI. Additionally, since the purpose of this method is to trade some type safety for flexibility, this method uses a `bind.parseTopicsIntoMap` function which allows for unpacking of event logs which have an indexed string. 
While it makes sense to me that we want to exclude strings and other types of unbound size from `topics`, there is nothing stopping this from being implemented on the contract side of things (and it [is](https://etherscan.io/address/0x6090A6e47849629b7245Dfa1Ca21D94cd15878Ef#code)) so I think it would be good to have a method to …
> add methods to abi that allow for the generic unpacking of event logs into map[string]interface{}

- core/vm/gas_table.go
- core/vm/gas_table_test.go
previous overflow condition is too big to use.
0x7FFFFFFFF squre operation is overflowed uint64.
0x7FFFFFFFF^2 = 0x3F FFFF FFF0 0000 0001
the minimal number cause uint64 overflow is 0x100000000^2 = (uint64) 0
test code is 
func main() {
var min_overflow uint64
var mem_sz uint64
var word_sz uint64
min_overflow = 0x100000000
fmt.Printf("result of 0x%X square op is 0x%X\n", min_overflow, min_overflow*min_overflow)
mem_sz = 0x1FFFFFFFE0
word_sz= (mem_sz+31)/32
fmt.Printf("mem_sz is 0x%X, word sz is 0x%X\n", mem_sz, word_sz)	
}
> core/vm: Correct the Memory Gas Overflow condition

- swarm/network/discovery.go
- swarm/network/discovery_test.go
- swarm/network/hive_test.go
- swarm/network/protocol.go
- swarm/network/protocol_test.go
The current swarm hive would in some occasions not connect to peers in shallow bins causing unhealthy connectivity
The reason is that needed shallow peers are not sent to nodes beyond connection's proximity order.
The initial response to subPeersMsg needs to be modified to allow enumeration of peers up to the advertised depth not the connection PO.
This PR introduces a one-liner fix to this bug.
It also adds extensive protocol exchange tests for initial subPeersMsg-peersMsg exchange
It modifies bzzProtocolTester to allow pregenerated overlay addresses
> swarm/network:   hive bug: needed shallow peers are not sent to nodes beyond connection's proximity order

- core/blockchain.go
I believe `insertChain` should be the internal implementation of the exported function `InsertChain`.
> core: fix the typo in the insertChain comment

- console/console.go
- rpc/handler.go
The `eth.coinbase` JavaScript property can return an error (throw in JS) if there are no accounts present. This PR handles that throw in the console welcome message. The same is done for `admin.datadir` if the `admin` namespace is not exposed.
In addition, the PR also reworks the printout so the welcome message is constructed first and only afterwards printed to avoid log messages getting intermingled with console printout.
> console: handle eth.coinbase throws

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_insert.go
- core/blockchain_test.go
- core/state_prefetcher.go
- core/types.go
- core/vm/interpreter.go
- eth/backend.go
- eth/config.go
I need the clean cache fix (https://github.com/ethereum/go-ethereum/pull/19307) in first, then this PR can be benchmarked on top.
> core: prefetch next block state concurrently

- cmd/clef/main.go
- cmd/faucet/faucet.go
- cmd/geth/main.go
- consensus/clique/clique.go
- consensus/ethash/algorithm_test.go
- consensus/ethash/consensus.go
- consensus/ethash/consensus_test.go
- core/blockchain.go
- core/blockchain_insert.go
- core/chain_makers.go
- core/evm.go
- core/genesis.go
- core/headerchain.go
- core/types/block.go
- core/types/block_test.go
- core/types/gen_header_json.go
- ethstats/ethstats.go
- graphql/graphql.go
- graphql/schema.go
- internal/ethapi/api.go
- light/lightchain.go
- miner/worker.go
- mobile/types.go
- tests/block_test_util.go
- tests/difficulty_test_util.go
- tests/gen_btheader.go
- tests/gen_difficultytest.go
This PR simplifies timestamps to be `uint64` instead of `big.Int`s.
> all: simplify timestamps to uint64

- core/vm/logger.go
`snapstot` -> `snapshot`.
`snaptshot` -> `snapshot`.
> core/vm: fix typos in comments

- accounts/manager.go
- cmd/geth/accountcmd.go
- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/api_backend.go
- eth/backend.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/api_backend.go
- les/backend.go
- node/config.go
- node/node.go
- node/service.go
- rpc/http.go
- signer/core/api.go
> accounts, cmd, internal: disable unlock account as default

- core/blockchain.go
- core/blockchain_test.go
This PR fixes two things:
1. When a block is inserted as a side block while becoming the canonical block later, all logs belong to this block should emit a `reborn` event.
2. When a block becomes the uncle block from the canonical block,  all logs belong to this block will be marked as `REMOVED`. While this block becomes the canonical block again because of double reorg(but now this block is not the head), all logs belong to this block should emit a `reborn` event.
> core: re-emit new log event when logs rebirth

- core/state/statedb.go
- core/vm/interface.go
This PR introduces a fix to `state.ForEachStorage` function. 
Since before inserting data into trie, there is an additional RLP encode operation. 
While in the `state.ForEachStorage` function, it relies on the trie iterator to iterate all leaf nodes(aka state data), but the rlp decode operation is missing there.
> core/state: fix state iterator

- trie/database.go
- trie/database_test.go
The meta root is used as an aggregator for block root hashes, there's no point in retrieving it.
> trie: there's no point in retrieving the metaroot

- params/config.go
Sets the Rinkeby St. Petersburg fork block to `4321234`, estimated to hit around the 4th of May, 2019.
> params: set Rinkeby Petersburg fork block (4th May, 2019)

- consensus/ethash/consensus.go
- core/types/block.go
- core/types/block_test.go
This PR contains two small tweaks to uncle validation. 
1. If there are no uncles, we don't have to build the data structure containing the 7-generation ancestors during `VerifyUncles`. I guesss that all blocks are probably in the blockCache already, but it's still useless. 
2. If there are no uncles, we don't have to rlp-hash the `nil`. If we just return the emptyhash directly, the op takes `2.93 ns` instead of `1277 ns` on my machine.
> consensus,core: shortcut uncle validation

- p2p/discover/table.go
This resolves a minor issue where neighbors responses containing less
than 16 nodes would bump the failure counter, removing the node. One
situation where this can happen is a private deployment where the total
number of extant nodes is less than 16.
Issue found by @jsying.
> p2p/discover: bump failure counter only if no nodes were provided

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/api_backend.go
- eth/config.go
- graphql/graphql.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/api_backend.go
This PR adds a CLI-configurable global gas cap on `eth_call` and `eth_estimateGas`. Although node operators should not expose rpc api to untrusted users (like, the internet), even with http level load balancing in front it is difficult to protect against dos via eth_call variants.
This makes it possible to enforce a cap on the gas that a caller can use, by using the flag `rpc.gascap`
Start geth
```
build/bin/geth --dev --rpc --rpc.gascap 33000
```
Caller:
```
[user@work go-ethereum]$ curl 127.0.0.1:8545 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"data":"0x641fffffffe06000f3","gas":"0xffffffffffffffff"},"latest"]}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"out of gas (gas capped at: 33000)"}}
```
Server: 
```
WARN …
```
> eth, les, geth: implement cli-configurable global gas cap for RPC calls

- signer/core/signed_data.go
- signer/core/signed_data_test.go
This fixes an issue I noticed with #17789 (cc @PaulRBerg) which resulted in a bad `PrettyPrint` of the `Domain` struct when attempting to debug message signing.
The original code makes the assumption that setting a key in a map to `nil` results in a noop, however in Go the key is still added to the map with its value set to nil, which yields a value showing up in `TypedData.Format()` even though it may not be specified by the user's `TypedData` struct.
This PR fixes this, moving `domain.ChainId` from the map's initializer down to a separate if statement which checks the existance of `ChainId`'s value, similar to the rest of the fields, before adding it. I've also included a new test to demonstrate the issue
> Fix EIP-712 domain map containing unused field

- cmd/geth/main.go
- params/version.go
- swarm/version/version.go
I assume these flags were not meant to be removed in 1.8.24.
Fixes #19415
> Revert flag removal

- rpc/handler.go
> rpc: cancel root context after all requests are served

- p2p/rlpx.go
- p2p/rlpx_test.go
I have found it before. and I guess there was a problem in my request.
I think "our" parameter doesn't be used anywhere. If problem still exist, please let me know.
Thanks a lot
> p2p/rlpx.go: remove useless parameter

- accounts/scwallet/wallet.go
When the user need to pair their smartcard, je message currently displayed is `Unpaired, waiting for PUK`, which corresponds to an older version of the card app. Later versions expect a pairing password, so this PR makes sure the correct instruction is displayed.
> accounts/scwallet: fix card pairing instruction message

- les/handler.go
- les/handler_test.go
- les/peer.go
- les/txrelay.go
- params/version.go
- swarm/version/version.go
This PR backports the new transaction cost calculation (including the size cost correction for large transactions which is now used by latest servers too). It also adds a verification for required message types in the announced cost table.
> les: fix SendTx cost calculation and verify cost table

- metrics/exp/exp.go
- metrics/prometheus/collector.go
- metrics/prometheus/handler.go
- metrics/prometheus/prometheus.go
Hi, guys!
* added 2 flags:
```
--metrics.prometheus             Enable prometheus HTTP server
--metrics.prometheus.addr value  Prometheus server listening address (default: "localhost:9455")
```
* when `--metrics.prometheus` flag provided, start http server which returns internal  geth metrics by http in prometheus format; log output:
```
≻ ./build/bin/geth --metrics --metrics.prometheus
INFO [06-26|04:18:12.544] Enabling metrics collection
INFO [06-26|04:18:12.544] Starting prometheus http server          addr=localhost:9455
INFO [06-26|04:18:12.546] Maximum peer count                       ETH=25 LES=0 total=25
```
* example of response https://gist.github.com/chapsuk/60b90b042526bb25a03da12d3326b0fb
* i'm wrote small sample for testing and build dashboard: …
> metrics/prometheus: added prometheus metrics

- cmd/swarm/access_test.go
- cmd/swarm/run_test.go
- cmd/swarm/upload_test.go
- swarm/api/client/client_test.go
- swarm/api/http/test_server.go
- swarm/storage/ldbstore_test.go
**Summary**
* This PR fixes some process (+memory) and file descriptor leaks.
* It also disables `TestClientUploadDownloadRawEncrypted` and `TestLDBStoreCollectGarbage` as those tests are known to be flaky with `-race`.
**A few details** 
* We got rid of the 'global' `testCluster` from `cmd/swarm/run_test.go`. => That adds some time to test runs, but answers the question: who is responsible for cleanup.
* To counterbalance the slowdown, nodes are started in parallel now. => At the end we are just 7s slower on Travis, but we freed up 10% of CI memory after the tests complete.
Note:
* We were leaking process, so even when the test binary exited some processes continued running and consumed significant memory. That is more of a problem locally than on an ephemeral CI environment.
* …
> cmd/swarm: fix resource leaks in tests

- node/config.go
If `--signer` is used, currently geth will continue without the external signer in case the external signer is not present (ipc not present or http port not open). This PR changes it so that geth fails instead of falling back to local keystore.
> node: do not continue if 'signer' is used but connection fails

- swarm/storage/feed/handler.go
- swarm/storage/feed/lookup/lookup.go
- swarm/storage/feed/lookup/lookup_test.go
* This PR adds context handling/cancellation to Swarm's Feed lookup algorithm.
* Fix Feeds lookup bug corner case
          With ❤ from [Epic Labs](https://www.epiclabs.io)
The Lookup function now admits a `context`. This allows for the algorithm process to be stopped by the caller, or otherwise given a deadline/timeout.
Fix a lookup bug whereupon a bad hint placed next to a good update would fool the lookup algorithm having it potentially fail in finding the last update. This is a very infrequent case and probably has not been experienced, but could happen. We detected this while reviewing the algorithm code.
A test was added to cover this case.
> swarm/storage/feed: add context handling/cancellation to Swarm Feeds lookup, fix bad hint lookup bug

- les/peer.go
- les/peer_test.go
This PR adds a verification for required message types in the announced cost table.
> les: check required message types in cost table

- les/commons.go
This PR fixes the node ID string encoding in the p2p.Protocol.PeerInfo function provided by the LES protocol handler. The bug caused admin.peers to report les: "handshake" even after the handshake finished successfully.
> les: fix p2p.Protocol.PeerInfo

- cmd/geth/chaincmd.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/handler.go
- eth/handler_test.go
- eth/peer.go
- eth/sync.go
- les/handler.go
- light/lightchain.go
- light/postprocess.go
- params/config.go
Fast sync is susceptible to a grieving version of an eclipse attack, where a malicious remote node attempts to get a new Geth node to fast sync to some small chain, before a real heavy chain is discovered in the network. This results in Geth falling back to full sync for the main chain, taking too much time.
This attack can only be meaningfully mounted against nodes which are properly exposed on a public IP address (i.e. not firewalled, not NATed). Even then, it's a race against the node finding good peers fast enough, in which case the attack doesn't work any more.
There is no economic advantage in pulling this attack off, only causing sync annoyance. That said, there is currently a number of (at least 4 identified, maybe more) Parity nodes at `207.148.5.229`, which are doing variations …
> eth, les, light: enforce CHT checkpoints on fast-sync too

- cmd/geth/chaincmd.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/handler.go
- eth/handler_test.go
- eth/peer.go
- eth/sync.go
- les/handler.go
- light/lightchain.go
- light/postprocess.go
- params/config.go
- params/version.go
- swarm/version/version.go
Backport of https://github.com/ethereum/go-ethereum/pull/19468
> [1.8.27 backport] eth, les, light: enforce CHT checkpoints on fast-sync too

- cmd/geth/main.go
- cmd/utils/flags.go
- trie/database.go
In the trie write cache we didn't track a few internal metadata fields. This can cause a higher memory use than the actual allowance. As the allowance is grown, the "unaccounted for" space also grows at the same rate. This is bad because it prevents users from setting memory limits close to their actual system limits. This PR aims to track all the meta fields that we use during trie write caching. 
Memory usage is promising, it chops off about as much RAM as the allowance of the dirty cache.
**Another benchmark that we need however is how the db usage evolves with this. We definitely will write more data to disk, would be good to put a number on it.**
> trie: approximate the wasted cache metaspace closer

- swarm/network/simulation/node.go
- swarm/pss/prox_test.go
- swarm/pss/pss_test.go
Apparently, the problems were caused by a blocked channel. Reading function exits, another function writes to the channel, and it's blocked, since nobody reads.
clone of https://github.com/ethersphere/go-ethereum/pull/1319
also, closes https://github.com/ethersphere/go-ethereum/issues/1308
> Flaky TestProxNetwork fixed

- accounts/accounts.go
- accounts/external/backend.go
- accounts/hd.go
- accounts/keystore/wallet.go
- accounts/scwallet/wallet.go
- accounts/usbwallet/wallet.go
- cmd/geth/main.go
- signer/core/api.go
The crux of this PR is adding support for the new Ledger derivation path (standardised), opposed to the old one they used.
This could have been done trivially (https://github.com/ethereum/go-ethereum/issues/17387), at the expense of dropping support for the old paths. That's not really an option, because it would result in people losing default access to those accounts and freaking out (even though they could be recovered manually).
An alternative approach proposed was in https://github.com/ethereum/go-ethereum/pull/19358, which introduced a CLI flag to switch between the old and new paths. That doesn't fly either because the use all of a sudden needs to be aware of deterministic wallet internals just to use a HW wallet.
This PR takes a more complex approach that keeps the dirty details …
>  accounts: switch Ledger derivation path to canonical one

- core/blockchain.go
- core/rawdb/accessors_indexes.go
- core/rawdb/accessors_indexes_test.go
Transaction hashes now store a reference to their corresponding
block number as opposed to their hash. In benchmarks this was
shown to reduce storage by over 12 GB.
The main limitation of this approach is that transactions on
non-canonical blocks could never be looked up, however that is
currently not supported.
The database version has been upgraded to version 5 and the
transaction lookup process is backwards-compatible with the
prior two transaction lookup formats prexisting in the
database instance. Tests have been added to ensure this.
> core: lookup txs by block number instead of block hash

- cmd/utils/flags.go
- node/defaults.go
This is a tiny PR to bump the default peer count form 25 to 50. This is especially helpful during fast sync (reduces sync time by 2 hours) as it permits more concurrent state retrievals to be running. On the flip side, it does increase baseline network chatter post-sync from 40 to 80KB/s.
> cmd/utils, node: switch over default peer count to 50

- internal/ethapi/api.go
This PR introduces functionality to enable gas estimation for transaction signing or sending.
Currently, the gas is not specified, then geth will use a hardcoded value(90k) as the default gas value. In this PR, geth will use `EstimateGas` function instead.
> internal/ethapi: estimate gas usage automatically.

- eth/handler.go
- eth/sync.go
There are malicious nodes in the network which try to feed short chains to newly syncing nodes. This has multiple downsides. One of them (causing fast sync to be disabled) was fixed recently.
Another downside appears for full and archive sync. If a malicious node feeds us a short chain, after finishing downloading it, we start accepting transactions into the pool. This triggers the pending block creation and also wastes precious disk IO and CPU resources on reconstructing the pending block over and over and over again while syncing.
This PR enforces the CHT hard coded snapshot on full and archive syncs to when enabling transaction processing:
* If we complete a sync cycle, but are still below the checkpoint, there's no point to accept transactions as we know there are many more blocks to …
> eth: enforce chain above CHT before accepting txs into the pool

- consensus/clique/clique.go
- consensus/consensus.go
- consensus/ethash/consensus.go
- core/chain_makers.go
- core/state_processor.go
- miner/worker.go
This PR removes some overhead work done during block import, where we uselessly assemble a block which is then thrown away. 
In [state processor](https://github.com/ethereum/go-ethereum/blob/master/core/state_processor.go#L79)
```golang
// Finalize the block, applying any consensus engine specific extras (e.g. block rewards)
p.engine.Finalize(p.bc, header, statedb, block.Transactions(), block.Uncles(), receipts)
```
`ethash/consensus.go`:
```golang
// Finalize implements consensus.Engine, accumulating the block and uncle rewards,
// setting the final state and assembling the block.
func (ethash *Ethash) Finalize(chain consensus.ChainReader, header *types.Header, state *state.StateDB, txs []*types.Transaction, uncles []*types.Header, receipts []*types.Receipt) (*types.Block, error) {
// …
```
> consensus,core,miner: avoid overhead of creating a new block

- eth/api_backend.go
- ethclient/ethclient_test.go
- les/api_backend.go
Supersedes https://github.com/ethereum/go-ethereum/pull/15762 . It was not properly goimport-formatted, so I fixed that and refactored it a bit more. Thanks @shbli for the PR! 
---------------------------
For release notes:
This change makes getBalance, getCode, getStorageAt, getProof, call, getTransactionCount return an error if the block number in the request doesn't exist. getHeaderByNumber still returns `null` for missing headers.
> eth, les: add error when accessing missing block state

- internal/testlog/testlog.go
- p2p/discover/common.go
- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v4_udp_lookup_test.go
- p2p/discover/v4_udp_test.go
This change restructures the internals of p2p/discover to make room for
the discv5 code which will soon be added to this package.
- packet type names now have a "V4" suffix.
- ListenUDP returns *UDPv4 instead of *Table. This technically breaks
the API but the only caller in go-ethereum is package p2p, which uses
a compatible interface and doesn't need changes.
- The internal transport interface is changed to make Table reusable for v5.
- The 'lookup' code moves from table to transport. This required
updating the lookup unit test to use udpTest instead of a custom transport
The first commit adds the package "internal/testlog" which I've been using since 2017.
> p2p/discover: split out discv4 code

- trie/proof.go
- trie/proof_test.go
The security guarantee of merkle proof is: malicious attacker can't create fake data with valid hash.
It is correct for root hash checking, but for the remaining node checking, we should compare the hash and keccak256(value) first, otherwise e.g attacker can temper the value of leaf node.
> trie: fix merkle proof

- core/blockchain.go
- core/blockchain_test.go
This PR adds a test where we
1. Have a chain [0 ... N .. X]
2. Reorg to shorter but heavier chain [0 ... N ... Y]
3. Then there should be no canon mapping for the block at height X
The headerchain insertion ensures that future 'stale' canon hashes are deleted, however, this is not done by blockchain when inserting blocks. This can lead to an inconsistent chain history, and would typically not appear on mainnet, but only in scenarios where 
- Forks/sidechains can be pretty long, 
- Difficulty varies wildly
The above two points especially concern Clique networks. 
Running this test yields
```
=== RUN   TestReorgToShorterRemovesCanonMapping
--- FAIL: TestReorgToShorterRemovesCanonMapping (0.04s)
blockchain_test.go:1871: expected block to be gone: 80
blockchain_test.go:1874: expected header …
```
> core: add test to demonstrate canonicality confusion

- accounts/keystore/key.go
- accounts/keystore/passphrase.go
- cmd/geth/accountcmd.go
- cmd/geth/accountcmd_test.go
- internal/ethapi/api.go
- signer/core/api.go
Fixes https://github.com/ethereum/go-ethereum/issues/19165
Running `geth account new`:
```
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat passphrase: 
Your new key was generated
Address: {adbb1348ab38e354ca79f7284701d701d02b351c}
Please backup your key file!
Path:    {/home/user/.ethereum/keystore/UTC--2019-04-25T11-07-21.800464724Z--adbb1348ab38e354ca79f7284701d701d02b351c}
Please remember your password!
``` 
In `geth console` running `personal.newAccount()`:
```
Passphrase: 
Repeat passphrase: 
INFO [04-25|13:53:24.946] Your new key was generated               address=0xbD8603B63EaC7633987e1F331D542a5e99dA4418
WARN [04-25|13:53:24.946] Please backup your key file! …
```
> accounts, cmd, internal, signer: add note about backing up the keystore

- consensus/clique/clique_test.go
- core/blockchain.go
- core/chain_makers.go
This PR fixes an issue during reimporting old blocks on a Clique network after a node crash.
The root of the issue is that Clique doesn't have block subsidy, so it can happen that two consecutive blocks have the same state (e.g. no transactions, self-transactions with 0 gas price, self-transactions by the miner).
If the node crashes (we lose the recent state), Geth will rewind the head block to the first one that we do have the state for. From that point onward, we try to reprocess all the blocks. If however two **previously known** blocks have the same state, processing the first one will also complete the second. Currently the block importer rejects the second with a "known block" error, since it doesn't expect this scenario (it rewound because no state was present, how did the state …
> core: fix import errors on clique crashes + empty blocks

- swarm/network/stream/snapshot_retrieval_test.go
This PR adds a pure retrieval test to the snapshot retrieval tests.
Up to today, the retrieval tests were uploading chunks randomly to nodes and then trying to download those chunks from every node. To upload chunks, the FileStore.Store() function was being used - essentially uploading chunks to individual nodes directly. For retrieval to work in such a scenario, we need to have syncing enabled in order for chunks to be stored at their actual expected nodes.
This new test bypasses syncing by evaluating which chunk would be expected to be at which node, then storing chunks directly in those nodes's LocalStore - essentially simulating syncing by accessing stores directly (simulation framework allows that). This way, the test simulation run can switch off syncing and directly starts …
> swarm/network/stream: add pure retrieval test

- swarm/metrics/flags.go
This PR is starting the runtime metrics collector alongside our application metrics.
I think for now we don't need fine-grained flags to enable one or the other - generally if someone is interested in metrics of Swarm currently, they are probably interested in all kinds of metrics.
I've already added a Grafana dashboard to display some of these.
This will be useful when we review the chunker fix that @jmozah submitted, AFAIK some of it is a fix for goroutine leaks.
> swarm/metrics: track runtime metrics

- cmd/swarm/export_test.go
- swarm/network/simulation/kademlia_test.go
Due to an underlying problem with windows tests we have to skip this test until the issue is resolved in order to not block other users of the CI.
> cmd/swarm: skip export test on windows builds

- p2p/discover/table.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
This PR fixes a race where table loop would self-lookup before returning from constructor
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e5c57]
goroutine 366 [running]:
github.com/ethereum/go-ethereum/p2p/discover.(*UDPv4).lookup(0xc0003c7a80, 0xd68ef85fa6bffa2e, 0x15c4ae6f4fcf3994, 0x866cafdc3250963, 0xeab8debbf12d1d74, 0xafe4f862677775d3, 0x86b9c414031113c9, 0xbfdeddd14dab098c, 0xc55787c859379260, 0x8, ...)
/work/src/github.com/ethereum/go-ethereum/p2p/discover/v4_udp.go:329 +0x2a7
github.com/ethereum/go-ethereum/p2p/discover.(*UDPv4).lookupSelf(0xc0003c7a80, 0xc88eb8, 0xc00037e960, 0x0)
/work/src/github.com/ethereum/go-ethereum/p2p/discover/v4_udp.go:309 +0xb5 …
```
> p2p/discover: fix nil-dereference due to race

- les/costtracker.go
- les/peer.go
- les/peer_test.go
This PR fixes cost table updates by AnnounceMsg. Instead of overwriting the entire table (which also allowed sending an incomplete table) we only update entries that are present in the update. Entries for unknown message codes are discarded.
> les: fixed cost table update

- eth/api_backend.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/api_backend.go
- les/backend.go
- les/handler.go
- les/handler_test.go
- les/helper_test.go
- les/odr.go
- les/odr_requests.go
- les/odr_test.go
- les/peer.go
- les/protocol.go
- les/txrelay.go
- light/odr.go
- light/odr_util.go
This PR implements an ODR request for retrieving transaction status and adds it to the API backend so that it is used by GetTransactionByHash and GetRawTransactionByHash. From the user perspective this means that eth.getTransaction and eth.getRawTransaction will now work in light mode too.
Solves https://github.com/ethereum/go-ethereum/issues/19063
> les, light: implement ODR transaction lookup by hash

- rlp/decode.go
- rlp/decode_test.go
- rlp/encode.go
- rlp/encode_test.go
- rlp/typecache.go
These changes fix two corner cases related to internal handling of types
in package rlp:
- The "tail" struct tag can only be applied to the last field. The check for this
was wrong and didn't allow for private fields after the field with the tag.
- Unsupported types (e.g. structs containing int) which implement either
the Encoder or Decoder interface but not both couldn't be encoded/decoded.
Also fixes #19367
> rlp: fixes for two corner cases and documentation

- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v4_udp_lookup_test.go
- p2p/discover/v4_udp_test.go
This change implements [EIP-868]. The UDPv4 transport announces support
for the extension in ping/pong and handles enrRequest messages.
There are two uses of the extension: If a remote node announces support
for EIP-868 in their pong, node revalidation pulls the node's record.
The Resolve method requests the record unconditionally.
[EIP-868]: https://eips.ethereum.org/EIPS/eip-868
>  p2p/discover: add support for EIP-868 (v4 ENR extension)

- swarm/storage/localstore/subscription_pull.go
- swarm/storage/localstore/subscription_push.go
These traces are too spammy. We should address them as part of https://github.com/ethersphere/go-ethereum/issues/1393
We should also be trying out traces and spans in deployments, before adding them to the code.
> swarm/storage: disable open tracing on indices

- accounts/accounts.go
- signer/core/signed_data.go
This PR is in support of https://github.com/ethereum/go-ethereum/pull/17578 , to make use of Clef and EIp-191 to sign data with intended validators. 
With this PR, the signature can be obtained thus: 
This is the request data : 
```json
{
"id": 68,
"method": "account_signData",
"params": [
"data/validator",
"0x8a8eafb1cf62bfbeb1741769dae1a9dd47996192",
{
"address": "0xdeadfeeedcafe000000000000000000000000cff",
"message": "0x000000e3a2e0b25d72c2fc6e35a7f853cdacb193b4b4f95c606accf7f8fa8415283582c7"
}
]
}
```
It the `0x000000e3a2e0b25d72c2fc6e35a7f853cdacb193b4b4f95c606accf7f8fa8415283582c7` is, in that case, the `sectionId` and the `hash` we want to sign. That data cannot be validated by clef, it's application-speciic data. However, the `address` of the intended validator …
> accounts,signer: better support for EIP-191 intended validator

- build/ci.go
This PR is disabling automatic builds for Swarm packages, and basically decoupling the Swarm release process from Geth.
From now on until we split the Swarm codebase from the Geth repo, we will issue manually releases of Swarm.
> build: disable swarm packages

- core/rawdb/freezer.go
- core/rawdb/freezer_table.go
- eth/downloader/downloader.go
The freezer and the downloader contain a few atomic `uint64` fields. Fun fact:
> On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned. https://golang.org/pkg/sync/atomic/#pkg-note-BUG
This PR moves the atomics in the freezer and downloader to the head of the struct to ensure 64bit alignment.
Fixes https://github.com/ethereum/go-ethereum/issues/19590.
> core/rawdb, eth/downloader: align 64bit atomic fields

- build/ci.go
Changes:
- `lanchpad` becomes `Launchpad`
> build/ci.go: fix a typo

- crypto/bn256/cloudflare/bn256.go
The `Marshal` functions for elements in `G1` and in `GT` were not checking if the pointer to the group element was nil or not. Hence, a panic was thrown in we called these functions from a nil pointer.
For `G2`, a check was written. I added the check to the `G1` and `GT` functions.
```
e := new(G1)
res := e.Marshal()
```
> crypto: Added checks for nil pointers in Marshal functions

- accounts/usbwallet/hub.go
The current Ledger Nano X USB product ID is `0x0004`. Enabling that seems to have been enough to support it (thank you @LedgerHQ for retaining the original USB protocol).
The second two sets of IDs are based on [announced upcoming firmware changes](https://www.ledger.com/2019/05/17/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/ ). We'll need to double check after those arrive whether the bridge is still functional or not. Based on the promises in the blog post to keep the protocols, hopefully the ID enumeration here will be enough.
> accounts/usbwallet: enable the Nano X and upcoming Ledger IDs

- eth/backend.go
- les/backend.go
- les/handler.go
- les/helper_test.go
- les/server.go
- les/ulc.go
- les/ulc_test.go
This PR introduces protection for les server which will reject all light client connection
if the node is not synced.
Since light client usually tries to retrieve and verify the data based on the latest block hash. 
If the server is not synced, it will only increase the pressure of server and server can't return 
any meaningful response.
> eth, les: reject light client connection is server is not synced

- core/blockchain.go
This PR prevents the genesis block been deleted during the freezer-style fast sync.
> core: never delete genesis block

- core/rawdb/freezer.go
This is a counterpart to https://github.com/ethereum/go-ethereum/pull/19617 to ensure that the genesis block is never deleted from leveldb. The reasoning is that it's healthy to always know which network the database is on. It also fixes an issue in `geth init` that reset the freezer due to a missing genesis block in leveldb.
Fixes https://github.com/ethereum/go-ethereum/issues/19627.
> core/rawdb: keep genesis in key-value store for full sync too

- accounts/keystore/watch.go
- accounts/keystore/watch_fallback.go
With `GOOS=darwin` and `CGO_ENABLED=0`, the accounts/keystore package currently fails to build. This change causes that build permutation to succeed instead, by enabling the no-op fallback for file watching.
> accounts/keystore: enable fallback Darwin w/o CGO

- common/prque/prque.go
- common/prque/sstack.go
- core/blockchain.go
- core/rawdb/accessors_indexes.go
- core/rawdb/freezer_reinit.go
Our previous code reinitialized a new database from an old freezer sequentially. This turned out to be quite a heavy operation, taking `1h56m59.818s` for mainnet. This PR attempts to make block and transaction hashing concurrent.
> Freezer reimport fast

- accounts/scwallet/wallet.go
The remaining PUK count wasn't displayed in the console's status message.
There was another issue with the length of the PIN and PUK not being checked. If they are under their minimum length (6 and 12 respectively) the card will not decrease the retry count - and confuse the user. As a result, there will be a data. With this PR, the user is now warned that their input is too short.
> accounts/scwallet: Display PUK retry count

- cmd/abigen/main.go
Fix for https://github.com/ethereum/go-ethereum/issues/19292
Fix to allow using `abigen --pkg` flag with standard input.
See https://github.com/ethereum/go-ethereum/issues/17647#issuecomment-443110907 and https://github.com/ethereum/go-ethereum/issues/17647#issuecomment-464965285 for discussion
> cmd/abigen: allow using `abigen --pkg` flag with standard input

- crypto/bn256/cloudflare/constants.go
- crypto/bn256/cloudflare/gfp6.go
Hi everyone,
Just looked at the `constants.go` file in the bn256 library used from Cloudflare, and I wonder how these parameters were generated? Did you follow the first steps of the `Algorithm 1` in https://eprint.iacr.org/2005/133.pdf, and ran the function `P(x) = 36x^4 + 36x^3 + 24x^2 + 6x + 1` until you found the smallest `u ~ 2^(m/4)` st `log_2(P(-u)) = m` (where I assume that `m` was set to `256`)? These parameters were set to these values to match with `libsnark` I guess but I do not find a paper that specifies how they were generated (maybe I am missing something obvious?)
Moreover, the given `u` does not factor in `1868033^3`, but factors in `u = 3 * 13 * 29 * 983 * 11003 * 405928799` so I removed the comment that was initially written by the Cloudflare people I assume (since the …
> crypto: Removed comment section referring to Cloudflare's bn curve parameters

- accounts/scwallet/README.md
- accounts/scwallet/hub.go
Changes the URL scheme in the console from `pcsc://` to `keycard://` as there might be more than one system that uses PCSC while we exclusively support Status' keycard stuff at the moment.
> accounts/scwallet: change sc url scheme to keycard

- swarm/api/http/server.go
This PR fixes a small bug where a requested ENS name with `bzz-hash` would return a `404` when the underlying hash that was pointed to does not exist. It will now return the hash that is pointed to by the ENS entry without asserting its existence on Swarm.
fixes https://github.com/ethersphere/go-ethereum/issues/1401
> swarm/api/http: fix bzz-hash to return ens resolved hash directly

- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_test.go
- les/api.go
- les/costtracker.go
- les/csvlogger/csvlogger.go
- les/distributor.go
- les/execqueue.go
- les/flowcontrol/control.go
- les/flowcontrol/manager.go
- les/flowcontrol/manager_test.go
- les/freeclient.go
- les/freeclient_test.go
- les/handler.go
- les/handler_test.go
- les/helper_test.go
- les/peer.go
- les/peer_test.go
- les/protocol.go
- les/retrieve.go
- les/server.go
- les/servingqueue.go
LES/3 specs: https://github.com/zsfelfoldi/devp2p/blob/les3/caps/les.md
This PR improves LES server overload protection by adding a tiny protocol extension to handle transient faults better. It introduces the concept of "freezing" clients for a short time (1-2 seconds) by sending a Stop/Resume message pair. This can be considered a non-breaking protocol change because the previous version of the mechanism dropped some peers instantly in case of a significant transient overload. Old clients who do not understand these new messages will disconnect themselves which is basically the same effect while new clients can stay connected.
Freeze is initiated by the serving queue when the sum of recent and queued request costs exceeds a limit. The job of the flow control is to reduce the frequency of …
> les, les/flowcontrol: implement LES/3

- les/freeclient.go
This PR fixes an issue in the free client pool.
This issue is caused by **free client pool** itself. System sets the `totalCap` to a very low value which lower than the `freeClientCap`, so that the `connectedLimit` in `freeClientPool` is 0.
When `freeClientPool` tries to register a new peer, it failed and then call the `unregister` callback which tries to evict an non-exist peer from the `freeClientPool`.
> les: short circuit in the unregister if peer is not registered

- swarm/network/stream/syncer.go
- swarm/storage/localstore/subscription_pull.go
- swarm/storage/localstore/subscription_pull_test.go
This PR is fixing a bug in SubscribePull where on occasion it would skip the chunk pointed to by the `since` cursor.
1. SubscribePull has always been accepting a closed interval with respect to its arguments `since` and `until` - the godoc has been amended.
2. https://github.com/ethersphere/go-ethereum/issues/1375 is fixed as a result.
---
The bug this PR is addressing is that if on first iteration, the iterator within `SubscribePull` returns chunks - then the behaviour of `SubscribePull` is correct.
However if on first iteration, the iterator returns no chunks, and the `since` chunk is stored after the subscription is established, then it the chunk pointed at by `since` is not returned by the iterator, because `first` is set to `false`, and the item is skipped.
> swarm/storage: fix SubscribePull to not skip chunks

- ethclient/ethclient.go
- ethclient/ethclient_test.go
TransactionInBlock always crashes if json is nil and there was an error.
It tries to access fields `From` and `BlockHash` of the nil object.
> ethclient: ensure tx json is not nil before accessing it

- cmd/utils/flags.go
If `pcscd` isn't present on the system, an error will be displayed that confuses users:
```
ERROR[06-04|14:59:45.281] Failed to verify smartcard daemon path   path=/var/run/pcscd/pcscd.comm err="stat /var/run/pcscd/pcscd.comm: no such file or directory"
```
Instead of reporting an error, it is just displayed as information so that users won't attribute all their woes to it.
> scwallet: don't error when pcsc socket is missing

- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/statesync.go
This PR makes the syncing error more obvious which is more friendly to node maintainer.
> eth/downloader: make syncing error obvious

- cmd/geth/main.go
- cmd/geth/retesteth.go
- cmd/geth/retesteth_copypaste.go
`geth retesteth` will start HTTP RPC server that will respond to retesteth, and is currently capable of executing and passing all blockchain tests (except those with touching 0x3 precompile). Most state tests (without mining reward) pass - 62 failing. Filling (generating) of the tests works, but some problems need to be fixed on the retesteth's side.
Merging this would help Dmitry to run this and iterate better over the combination of retesteth + geth
> cmd: Add retesteth command (to support execution and generation of tests via retesteth)

- cmd/clef/main.go
- signer/core/api.go
- signer/core/api_test.go
As discussed in Berlin, enable smartcard signatures in `clef` in a separate PR.
> cmd/clef: Enable smartcard hub

- eth/protocol_test.go
In our fork of go-ethereum, we use a different default NetworkId and `protocol_test.go` fails. 
Change is simple but given i'm totally newbie, please let me know if my understanding is not right.
> eth: check for DefaultConfig.NetworkId in test

- vendor/github.com/gballet/go-libpcsclite/doc_darwin.go
- vendor/vendor.json
MacOS has its own vresion of PCSC buried into their [crypto token framework](https://developer.apple.com/documentation/cryptotokenkit/tksmartcard?language=objc), which has precedence over the PCSC-lite daemon. Hence, no readers are returned and `geth` doesn't report any wallet.
A platform-specific solution needs to be implemented, which is going to take time and shouldn't block 1.9. In any case, the search for the PCSC daemon path should be prevented, so that no irrelevant error message gets displayed.
> scwallet: Disable macos support

- cmd/devp2p/discv4cmd.go
- cmd/devp2p/enrcmd.go
- cmd/devp2p/main.go
- p2p/discover/table.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
This is a new tool for debugging p2p issues. It supports a few
basic tasks for now, but many more things can and will be added
in the near future.
devp2p enrdump            -- prints ENRs readably
devp2p discv4 ping        -- checks if a node is up
devp2p discv4 requestenr  -- gets a node's record
devp2p discv4 resolve     -- finds a node through the DHT
> cmd/devp2p: add devp2p debug tool 

- cmd/bootnode/main.go
- cmd/faucet/faucet.go
- cmd/utils/flags.go
- cmd/wnode/main.go
- les/serverpool.go
- les/ulc.go
- node/api.go
- node/config.go
- p2p/discover/v4_udp_test.go
- p2p/enode/localnode.go
- p2p/enode/localnode_test.go
- p2p/enode/node.go
- p2p/enode/node_test.go
- p2p/enode/urlv4.go
- p2p/enode/urlv4_test.go
- p2p/enr/enr.go
- p2p/enr/enr_test.go
- p2p/enr/entries.go
- p2p/server.go
- whisper/whisperv6/api.go
This PR adapts p2p/enr and p2p/enode to the final version of EIP-778 (https://github.com/ethereum/EIPs/pull/2097). It also changes all invocations of enode.ParseV4 to enode.Parse, allowing signed ENRs to be set as bootnodes and static peers.
> p2p/enode: improve IPv6 support, add ENR text representation

- accounts/abi/bind/auth.go
Currently user need to handle their keys manually in order to create TransactOpts. 
This utility function should improve the workflow for users that let their keys be handled by a keystore.
> Accounts: added transactorFromKeyStore

- core/rawdb/freezer_table.go
Fixes freezer on Windows.
Summary:
The O_APPEND flag in the Go implementation for windows removes the rights to truncate a file.
A workaround was implemented where O_APPEND was avoided, but writes force a Seek to end of file.
> core/rawdb: avoid O_APPEND

- core/blockchain.go
- core/headerchain.go
- core/rawdb/freezer.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_table_test.go
- core/tx_list.go
- core/tx_pool.go
- eth/downloader/statesync.go
- ethdb/leveldb/leveldb.go
- metrics/cpu.go
- metrics/cpu_syscall.go
- metrics/cpu_windows.go
- metrics/metrics.go
- p2p/metrics.go
- p2p/server.go
While porting over our Datadog metrics to a Grafana dashboard I've hit various missing data. Turned out that on Datadog we have access to the RPC APIs too (as well as the datadog agent on the host), so we used those to pull various infos. That is problematic if we use InfluxDB/Prometheus + Grafana, because those won't have RPC calling capabilities, nor local agents beside Geth.
This PR tries to surface the required counters through the proper metrics subsysem:
* Track the head header, receipt and block via gauges. This gives us access to the sync status without RPC.
* Track the pending, queued and local transactions via counters. This gives us access to txpool stats without RPC.
* Track memory usage and database/freezer sizes. This gives us access to some general system stats without a …
> core, ethdb, metrics, p2p: expose various counter metrics for grafana

- eth/backend.go
- les/handler.go
- les/handler_test.go
- les/peer.go
- les/server.go
This PR rejects all stale les request if the server is not "archive" mode.
The rationale behind this: searching a non-exist key in leveldb is expensive. So that it can leave an attack vector that attacker can constructor "stale" request to drain out the capacity of server.
> eth, les: reject stale request

- p2p/dial.go
- p2p/dial_test.go
- p2p/netutil/addrutil.go
- p2p/peer.go
- p2p/peer_test.go
- p2p/server.go
- p2p/server_test.go
- p2p/util.go
- p2p/util_test.go
The dialer limits itself to one attempt every 30s. Apply the same limit
in Server and reject peers which try to connect too eagerly. The check
against the limit happens right after accepting the connection.
This PR also makes unit test logging work in package p2p.
> p2p: enforce connection retry limit on server side

- ethclient/ethclient.go
- ethclient/ethclient_test.go
- internal/ethapi/api.go
EIP-695 was written in 2017. Parity and Infura have support for this
method and we should, too.
> ethclient, internal/ethapi: add support for EIP-695 (eth_chainId)

- les/handler.go
If a request comes in with the same missing block hash in all requests, the check `if request.BHash != lastBHash ` is false for all requests after the first one, and `root` is unset. This PR aborts if that happens
> les/handler: avoid lookup missing state

- accounts/abi/bind/auth.go
renamed NewKeyStoreFromTransactor to NewKeystoreTransactor
fixed godoc
as requested by @karalabe cc @gballet
> accounts: rename NewKeystoreTransactor

- les/handler.go
- les/handler_test.go
- les/peer.go
This PR is based on #19689.
This PR introduces a very simple reputation system on the server side. If a client sends too much invalid request(e.g. request some non-exist data), it will be kicked out.
The rationale here is: A client should send the requests to servers which can serve the requests. 
The server will push the new head announcements steadily. This information is totally enough for clients to manage their requests.
>  les: reject client connection if it makes too much invalid req

- p2p/server.go
```text
DEBUG[06-13|11:29:29.658] Adding p2p peer            id=6ff68d1c2df1fcb1 conn=dyndial addr=51.77.141.55:30303 peers=1 name=Pirl/v1.8.27-v6-mast...
DEBUG[06-13|11:29:29.677] Removing p2p peer          id=6ff68d1c2df1fcb1 conn=dyndial addr=51.77.141.55:30303 peers=0 duration=19.777ms req=true err="subprotocol error"
```
> p2p: add more info to peer addition and removal logs

- docs/index.md
The issue on page: https://geth.ethereum.org/docs/ wrong path to static files.
> Resolve issue with wrong static path on /docs/ page

- accounts/keystore/keystore_test.go
> accounts/keystore: fix #19707, avoid keyword as variable name

- accounts/abi/bind/backends/simulated.go
Fixes https://github.com/ethereum/go-ethereum/issues/19699.
> accounts/abi/bind/backends: use EIP155 on the simulated chain

- signer/fourbyte/validation.go
Remove some stutter in a warning message as reported in #19687
> clef: fix stutter in warning message

- miner/worker.go
When the miner (not mining) receivew event feeds from the txpool, it tries to add it to the pending state. Most often, the pending state is already full, and new transactions does not actually make it into the pending block. If that happens, we can avoid updating the snapshot, which is a pretty expensive operations, creating a full new block (deep copying and hashing) and deep-copying the state.
> miner: don't update pending state when no transactions are added

- rpc/client.go
When cancelling the context for a call on a HTTP-based client while the
call is running, the select in requestOp.wait may hit the <-context.Done()
case instead of the <-op.resp case. This doesn't happen often -- our
cancel test hasn't caught this even though it ran thousands of times
on CI since the RPC client was added.
Fixes #19714
> rpc: fix rare deadlock when canceling HTTP call context

- core/tx_pool.go
- core/tx_pool_test.go
This change moves internal queue re-shuffling work in TxPool to a background
goroutine, TxPool.runReorg. Requests to execute runReorg are accumulated
by the new scheduleReorgLoop. The new loop also accumulates transaction events.
The motivation for this change is making sends to txFeed synchronous.
Fixes #19192
> core: move TxPool reorg and events to background goroutine

- p2p/simulations/adapters/exec.go
`EnableMsgEvents` options for p2p config are currently hardcoded for `ExecAdapter`. This is change is required to be able to enable it using the `adapters.NodeConfig` directive.
> p2p/simulations: Enable access to MsgEvents with execadapter

- core/vm/evm.go
- internal/ethapi/api.go
This PR fixes https://github.com/ethereum/go-ethereum/issues/19186 
Problem: on `eth_call` and derivates using the same mechansm, there's a timeout that can trigger at any time. We currently do not signal this to the user, thus returning erroneous values when execution is aborted. 
This PR addresses thsi in a somewhat opportunistic way, since the timeout happens async in another goroutine. When we return from the actuall call, we check if the `Cancel` has been called on the `evm`. There is a tiny chance that the cancel was called _after_ the execution finished correctly, but it's bettter to error on the safe side than how we do it now (and the chances of that happening are really quite slim). 
Example when running this PR in `geth --dev console`, using an eternal loop (`jumpdest; push 0, …
> Detect and return error on eth_call on timeout 

- rpc/client.go
- rpc/client_test.go
This PR updates a comment about the maximum client subscription buffer to reflect changes made previously, and fixes a test that wouldn't fail when `wantError == true` but execution did not return an error.
Triggering the desired error currently requires input >= ~500 over the max on my machine. Happy to drill into that further and/or break up these commits into two PRs if desirable, but was hoping to collect feedback first. Thanks!
> rpc: fix subscription buffer documentation and test

- accounts/abi/abi.go
- accounts/abi/abi_test.go
adding the method `EventById` to the ABI, that allows to retrieve the event given a topic hash. Use case is similar to the method `MethodById`: given a transactoionReceipt with a log slice and the contract ABI, `EventById` returns the corresponding event "object" matching the log's topic field.
> abi: adding the method EventById and its test

- cmd/evm/runner.go
- cmd/evm/staterunner.go
- cmd/geth/chaincmd.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/state/dump.go
- core/state/state_test.go
- eth/api.go
Currently, doing a dump of the entire state results in a ~9G large json file, which is very heavy to process. 
This PR makes it possible to dump out the state in a more machine-friendly manner, whereby the dump output consists of a stream of json-objects, the first line containing the state `root`, and each line afterwards representing an account in the trie. Thus, a consumer of the resulting output does not need to have the full 9 Gb in memory during processing, nor does the `geth` export node.  
Existing functionality:
```
build/bin/geth --datadir /tmp/foo  dump  0  | head
WARN [11-13|21:37:49] No etherbase set and no accounts found as default 
INFO [11-13|21:37:49] Allocated cache and file handles         database=/tmp/foo/geth/chaindata cache=128 handles=1024
INFO [11-13|21:37:49] …
```
> core/state, cmd/geth: Streaming json output for  command

- cmd/evm/runner.go
This PR fixes two minor things in the `evm` binary
- Validate length of hex input. 
- Accept `0x`-prefix on hex input
It also closes #18041 
Invalid length:
```
[user@work evm]$ ./evm --debug --code "585" run
Invalid input length for hex data (3)
```
Prefixed by `0x`:
```
[user@work evm]$ ./evm --debug --code "0x5858" run
Code is 0x5858
0x
PC              pc=00000000 gas=10000000000 cost=0
PC              pc=00000001 gas=9999999998 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000000
STOP            pc=00000002 gas=9999999996 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000001
00000001  0000000000000000000000000000000000000000000000000000000000000000
```
Not prefixed:
```
[user@work evm]$ ./evm --debug --code "5858" …
```
> cmd/evm: evm input minor fixes

- whisper/whisperv6/envelope.go
- whisper/whisperv6/envelope_test.go
As noted by @kdeme in #18070 the calculation of the nonce is not what is specified in [EIP-627](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-627.md) and that adds to the list of incompatibilities with Parity's version.
> whisper: PoW calculations as specified in EIP-627

- eth/handler.go
- eth/handler_test.go
- eth/sync.go
This PR fixes a fast sync panic under this scenario:
The user previously synced the data via fast sync, but the fast sync was not completed.
Later the user tries to sync the data again with **full sync**. In this case, geth will convert the 
sync mode to **fast sync** quietly while the `syncBloom` is not initialized.
> eth: fix sync bloom panic

- les/handler_test.go
> les: prefer nil slices over zero-length slices

- accounts/abi/abi.go
- accounts/abi/abi_test.go
- accounts/abi/bind/base_test.go
I'm writing a test tool for Ethereum smart contract based on go-ethereum. 
The implementation in `abi.UnmarshaIJSON(data)` uses the Go map to store Method, which will overwrite the previous method.
Thus, when use it, I can only get the last overloaded function/method and event.
> accounts/abi: Fix method overwritten by same name methods.

- cmd/clef/README.md
- cmd/clef/datatypes.md
- cmd/clef/extapi_changelog.md
- cmd/clef/intapi_changelog.md
- cmd/clef/main.go
- cmd/clef/pythonsigner.py
- cmd/clef/rules.md
- cmd/clef/tutorial.md
- signer/core/api.go
- signer/core/cliui.go
- signer/core/signed_data.go
- signer/rules/rules.go
- signer/rules/rules_test.go
- signer/storage/aes_gcm_storage.go
- signer/storage/aes_gcm_storage_test.go
- signer/storage/storage.go
The goal of this PR was to refresh the Clef tutorial so it's up to date with the current code base. Apart from making sure all the code snippets, command, rules, etc. run, I've also tried to make the tutorial a bit more rounded, adding a few more sections + explanations.
During the refresh, I've noticed and fixed a few issues, please take a look at these in particular:
* When running `clef init`, if there's already a `masterseed.json`, I abort immediately. Previously we asked the user for the full passphrase entry and only afterwards failed (we still check afterwards too).
* When running `clef setpw`, the PR changes the stored key to the check-summed address (also modifies the counterpart that loads the password to use the checksum). Previously there was an issue here because the read …
> cmd/clef, signer: refresh tutorial, fix noticed issues

- core/chain_indexer.go
This PR fixes a bug in the chain indexer that caused repeated "chain reorged during section processing" errors under some rare circumstances.
https://github.com/ethereum/go-ethereum/blob/master/core/chain_indexer.go#L400
Here processSection checks for each processed header whether is parentHash equals the last block hash. The parent of the first block in a section is compared against the last section head which is passed as a parameter.
https://github.com/ethereum/go-ethereum/blob/master/core/chain_indexer.go#L333
The last section head is passed here which is assumed to be canonical bacause a reorg should theoretically trigger a rollback of stored sections. The problem is that this is not guaranteed to happen before the new section processing begins. If there is a stored section whose …
> core: fix chain indexer reorg bug

- core/chain_indexer.go
This PR fixes an issue in chain indexer. Currently chain indexer will
validate whether the stored data is canonical by comparing section head
and canonical hash. But the header of the checkpoint may not exist in
the database. We should skip validation for sections below the
checkpoint.
> core: fix chain indexer

- core/blockchain.go
This PR fixes a panic in current fast sync.
The fixed scenario is:
* 1. Node is inserting some ancient receipts(e.g. 100->120) and wait for the `chainMu`
* 2. At the same time, `Rollback` happens which reverts all inserted ancient data(e.g. 120->90)
* 3. Step(1) obtains the `chainMu` and set the fast head as 120. 
Next time fast sync happens, the `td` relative with height 120 is missing. Panic happens.
For more information, check the panic log:
https://gist.github.com/rjl493456442/a0c905cf575e9e74afbdab7a7ac9b8ae
TODO:
Not sure how much performance hit it will introduce. Later we should try to reduce the granularity of lock. Instead of having a global lock `chainMu` in `blockchain`, we need maintain more locks to guarantee better concurrency
> core: fix fast head updating logic

- vendor/github.com/karalabe/usb/usb_disabled.go
- vendor/vendor.json
Update the vendored `karalabe/usb` package to ensure that `geth` builds on OpenBSD.
> vendor: update karalabe/usb to fix CGO=0 builds

- accounts/abi/bind/auth.go
- accounts/external/backend.go
- cmd/checkpoint-admin/common.go
- cmd/checkpoint-admin/exec.go
- cmd/checkpoint-admin/main.go
- contracts/checkpointoracle/oracle.go
- les/sync_test.go
- signer/core/cliui.go
This PR integrates clef into checkpoint oracle. So that we can relay all signing operations to clef to get rid of keyfile.
> accounts, cmd, contracts, les: integrate clef for transaction signing

- cmd/geth/main.go
- trie/sync_bloom.go
This is a workaround for an issue with `sigar` in OpenBSD. I have created an issue to track the problem deeper: #19792.
> cmd/geth: wrong memory size sanitizing on OpenBSD

- core/blockchain.go
When we ran a 1.8 fast-sync, aborted and went over to 1.9, the db migration which shoves from leveldb to ancients caused a _huge_ memory spike. 
This is because it went through ~4M blocks, and stored each block in `deleted` during the process. 
This PR for now only changes it to store the same amont of `numberHash` objects in memory. Still a lot of objects, but should be a lot smaller in memory. 
Original mem usage:
We should do a more proper fix to incrementally process the blocks, instead of doing it in one go.
> core: lessen mem-spike during 1.8->1.9 conversion

- core/types/block.go
- eth/fetcher/fetcher.go
- eth/handler.go
- eth/protocol.go
- les/handler.go
- les/protocol.go
This PR adds some hardening in the lower levels of the protocol stack, to bail early on invalid data. Primarily, attacks that this PR protects against are on the  "annoyance"-level, which would otherwise write a couple of megabytes of data into the log output, which is a bit resource intensive.
> eth, les: add sanity checks for unbounded block fields

- p2p/protocol.go
- p2p/server.go
This entry was an experiment, but we're moving on to the
entry-per-protocol model instead.
> p2p: remove "cap" enr entry

- p2p/discover/table.go
Make it select from all live nodes instead of selecting the heads of random buckets.
> p2p/discover: improve randomness of ReadRandomNodes

- cmd/puppeth/module_explorer.go
- cmd/puppeth/wizard_dashboard.go
- cmd/puppeth/wizard_explorer.go
- cmd/puppeth/wizard_network.go
This PR integrate an open-source blockchain explorer `blockscout` into the puppeth.
Now puppeth can provide explorer service for PoA based chain and PoW based chain
> cmd/puppeth: integrate blockscout

- core/state/statedb_test.go
The random argument should be spread to args. Current code only randomly generates the first argument and the second one is always 0.
> core/state: fix db test random args

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/config.go
- eth/gen_config.go
- les/costtracker.go
This PR is based on #19814.
This PR encapsulates all les relative options and categories these options into `LES`.
> cmd: encapsulate les relative cli options

- eth/api_tracer.go
When calling `debug_storageRangeAt` on an empty block, geth returns an error "tx index 0 out of range for block ...". This fixes storageRangeAt for empty blocks.
cc @jwasinger
> eth: fix storageRangeAt for empty blocks

- cmd/geth/retesteth.go
- eth/api.go
- eth/api_test.go
**WIP** Adds a debug API method `AccountRangeAt` which returns all accounts in the state for a given block and transaction index.
> eth: add debug_accountRange

- common/bitutil/bitutil_test.go
…nation
Gollvm has very aggressive dead code elimination that completely
removes one of these two benchmarks.  To prevent this, use the
result of the benchmark (a boolean), and to be "fair", make the
transformation to both benchmarks.
To be reliably assured of not removing the code, "use" means
assigning to an exported global.  Non-exported globals and
//go:noinline functions are possibly subject to this optimization.
> common/bitutil: use result of TestBytes to prevent dead code elimination

- core/tx_noncer.go
- core/tx_pool.go
> core: fix write concurrency in txpool

- cmd/puppeth/genesis_test.go
- core/rawdb/freezer_table_test.go
- crypto/ecies/ecies_test.go
- eth/downloader/downloader_test.go
- eth/filters/bench_test.go
- les/api_test.go
- p2p/discv5/sim_test.go
- signer/core/signed_data_test.go
- signer/rules/rules_test.go
- signer/storage/aes_gcm_storage_test.go
This PR is attampt to replace fmt.Print* to t.Log* in tests or b.Log* in benchmark. Here are the details:
- fmt.Printf -> t.Logf or b.Logf
- fmt.Println -> t.Log or b.Log
> all: replace fmt.Print* calls with t.Log* in tests

- accounts/usbwallet/wallet.go
Currently in ~~`clé`~~ `clef`, the derivation process reuses the same derivation path array as input to the `Derive` function. That `Derive` function creates an account and keeps a pointer to the derivation path for other purposes.
Since the derivation path gets updated each time `Derive` is called, all accounts end up having the rug pulled from under their feet: the derivation path they point to will be that of the first non-valid account.
So this PR simply makes sure that one derivation path is allocated each time.
> signer/core: fix reference issue in key derivation

- accounts/abi/abi_test.go
- core/types/transaction_test.go
- crypto/ecies/ecies_test.go
- rpc/websocket_test.go
This is a follow up to #19670, cleaning up those call sites a bit more.
> all: replace t.Log(); t.FailNow() with t.Fatal()

- core/genesis.go
Supersedes https://github.com/ethereum/go-ethereum/pull/19744 (abandoned by its author).
> core: check error before accessing potentially nil block

- internal/ethapi/api.go
A while back we've switched `ethdb.Database` from a LevelDB backed struct to an interface. Some code was accidentally left in that still assumed the old structs/methods. This PR fixes on such instance where the `debug.chaindbProperty` got borked:
```
> debug.chaindbProperty("leveldb.stats")
WARN [07-18|16:08:30.756] Served debug_chaindbProperty             reqid=9 t=116.452µs err="chaindbProperty does not work for memory databases"
Error: chaindbProperty does not work for memory databases
at web3.js:3143:20
at web3.js:6347:15
at web3.js:5081:36
at <anonymous>:1:1
```
vs. this PR
```
> debug.chaindbProperty("leveldb.stats")
Compactions
Level |   Tables   |    Size(MB)   |    Time(sec)  |    Read(MB)   |   Write(MB)
-------+------------+---------------+---------------+---------------+------- …
```
> internal/ethapi: fix debug.chaindbProperty

- p2p/peer.go
This PR adds the `ENR` field to the `PeerInfo`.
> p2p: add ENR to PeerInfo

- cmd/clef/rules.md
- cmd/clef/tutorial.md
- crypto/secp256k1/libsecp256k1/src/asm/field_10x26_arm.s
- eth/tracers/internal/tracers/evmdis_tracer.js
- internal/jsre/deps/web3.js
Fix typos across **go-ethereum** repository
**Fixed Files**
```
go-ethereum/cmd/clef/rules.md:73:21: "libary" is a misspelling of "library"
go-ethereum/cmd/clef/tutorial.md:230:226: "specifing" is a misspelling of "specifying"
go-ethereum/crypto/secp256k1/libsecp256k1/src/asm/field_10x26_arm.s:26:54: "Agressive" is a misspelling of "Aggressive"
go-ethereum/eth/tracers/internal/tracers/evmdis_tracer.js:17:24: "sufficent" is a misspelling of "sufficient"
go-ethereum/internal/jsre/deps/web3.js:2234:41: "adress" is a misspelling of "address"
go-ethereum/internal/jsre/deps/web3.js:2245:41: "adress" is a misspelling of "address"
go-ethereum/internal/jsre/deps/web3.js:2265:41: "adress" is a misspelling of "address"
go-ethereum/internal/jsre/deps/web3.js:2288:41: "adress" is a misspelling of …
```
> Fix typos across go-ethereum repository

- cmd/geth/retesteth.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_table_test.go
Add error handling where we assign err a value, but don't check for it being nil.
> Added missing error checks

- cmd/clef/main.go
- cmd/geth/retesteth.go
- contracts/checkpointoracle/oracle_test.go
- eth/downloader/downloader.go
- p2p/simulations/adapters/exec.go
- signer/core/signed_data.go
- whisper/mailserver/server_test.go
- whisper/whisperv6/peer.go
Fixed assigning values to variables we don't end up using.
> Fixed ineffectual assignments

- cmd/faucet/faucet.go
I recognize that the Rinkeby faucet is meant to give allowances every 8, 24, or 72 hours depending on the user's selection.  I think the basic idea is that if someone needs a bunch more, they can come back on a regular interval.
This feature request is to not change the published interval, but to be a bit less strict about it, so that users coming back after the specified number of hours are less likely to see a super-strict message like this:
Do we as a community really think it's important to enforce the published lags down to the microsecond? 
My suggestion is that the actual gap until the next allowance be shorter than the published interval by 5 minutes.   Then users who need more testnet ether can set and use a recurring reminder more effectively.
I believe the attached commit would …
> cmd/puppeth: add grace period to faucet timeout

- eth/api_backend.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- internal/web3ext/web3ext.go
- les/api_backend.go
> eth, internal, les: add getHeaderBy* APIs

- .travis.yml
Build will not run unless the linter passes. Every job is grouped with `stage: build` except for the linter job `stage: lint`. Upon lint success, every build test is run in parallel as usual.
Fix: #19722
> Travis-CI Enforce Linting Before Build

- internal/ethapi/api.go
> ineternal/ethapi: wrap block size with hex.Uint64

- eth/api_backend.go
- graphql/graphql.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/api_backend.go
This PR mainly wants to improve the efficiency of graphQL on the light client.
We all know that light client only maintains the header chain and retrieve the missing part of blockchain by request. So for some graphQL request which only requires some fields in header, we definitely don't want to resolve the whole block(no matter from database for full node or from network for light client).
For the most API function which only needs the header, this PR offers the `resolveHeader` function which access header directly.
> eth, graphql, internal/ethapi, les: polish and improve graphql

- internal/ethapi/api.go
This change ensures 'blockHash', 'blockNumber' and 'transactionIndex'
are set to null for pending transactions. This behavior is required by
the Ethereum JSON-RPC spec.
Fixes #19897
> internal/ethapi: return null inclusion info for pending transactions

- accounts/abi/bind/backends/simulated.go
- accounts/abi/bind/backends/simulated_test.go
- accounts/abi/bind/bind_test.go
- accounts/abi/bind/util_test.go
- contracts/checkpointoracle/oracle_test.go
- les/helper_test.go
Support closing a simulated backend to avoid leaking the blockchain's update goroutine.
> accounts/abi/bind: support closing a simulated backend

- ethdb/memorydb/memorydb.go
We don't manually trigger compaction anywhere in the code (mostly because we don't delete anything). However, when we start deleting stuff and manually compacting (e.g. my future snapshot work), `ethdb.Database.Compact` is expected to work with all database backends.
Currently compaction fails for `memorydb` because it's not implemented. However, it doesn't need to be implemented because the `memorydb` is always compact anyway. This PR replaces the error with a noop. This is needed for tests that touch code that compacts.
> ethdb/memorydb: allow noop compact on memdb

- accounts/abi/abi.go
- accounts/abi/abi_test.go
- accounts/abi/bind/base.go
- accounts/abi/bind/bind.go
- accounts/abi/bind/bind_test.go
- accounts/abi/bind/template.go
- accounts/abi/event.go
- accounts/abi/event_test.go
- accounts/abi/method.go
- accounts/abi/pack_test.go
- signer/fourbyte/abi.go
The abi package already supports function overload by adding a suffix to the overloaded function name.
But it uses the function name with suffix to calculate signature(both for the event and method).
This PR fixes it by adding a new field named `RawName`. Now we can use `RawName` to calcuate all signatures but use `Name` to distinguish different overloaded function.
> accounts/abi, signer/fourbyte: fix incorrect signature

- core/vm/contracts.go
- core/vm/evm.go
- params/config.go
- params/protocol_params.go
This PR implements the gas cost adjustments in [EIP-1108](https://eips.ethereum.org/EIPS/eip-1108). Commit messages outline how this is done; currently the Istanbul block is `nil` in all cases, and precompiles are not hooked up to the [tracer `isPrecompiled` check](https://github.com/keep-network/go-ethereum/blob/master/eth/tracers/tracer.go#L393). It's not immediately clear where Istanbul should be switched to “on” before the relevant block, basically, so this PR adds the plumbing and switching on it, but doesn't activate it anywhere.
Opening this a touch early as to see whether this direction makes sense (it is based it on feedback from last year's #17644 from @ngrinkevich), or if there's a different approach worth pursuing.
> params, core/vm: Istanbul EIP-1108 gas costs implementation

- core/vm/eips.go
- core/vm/interpreter.go
- core/vm/jump_table.go
- core/vm/opcodes.go
- params/protocol_params.go
- tests/state_test_util.go
This PR is on top of https://github.com/ethereum/go-ethereum/pull/19735 (and is actually quite small). It adds support for EIP 1884, and makes use of the simplified chain management from #19735. It makes it possible to run statetests with e.g. `Constantinople+1884`, and thus apply 1884 without having `Istanbul` defined. 
This PR creates `core/vm/eips.go` where any minor new eips can be added. Minor == eips that only 
- Add or remove opcodes, or  
- redefine opcode costs
For more invasive EIPs, that would modify the block validation or execution engine outside of the evm (e.g. progpow), this refactoring won't help much.
> Eip 1884 v3

- core/vm/eips.go
- core/vm/opcodes.go
Implementation of 1344. This PR is built on top of https://github.com/ethereum/go-ethereum/pull/19743 , which contains some necessary framework. 
Neither of these PRs actually enable it for Istanbul (that needs a follow-up PR). So in that sense, they should both be fairly safe to merge. 
cc @fubuloubu  (only the last commit is relevant)
> Eip 1344 (ChainID opcode)

- core/state/state_object.go
- core/state/statedb.go
- graphql/graphql.go
- internal/ethapi/api.go
This PR implements the feature required by #19836 
The JSON RPC spec of this API is
**eth_call**
Executes a new message call with a set of overloaded contract code.
**Parameters**
**1. Object** - The transaction call object
`from`: DATA, 20 Bytes - (optional) The address the transaction is sent from.
`to`: DATA, 20 Bytes - The address the transaction is directed to.
`gas`: QUANTITY - (optional) Integer of the gas provided for the transaction execution. eth_call consumes zero gas, but this parameter may be needed by some executions.
`gasPrice`: QUANTITY - (optional) Integer of the gasPrice used for each paid gas
`value`: QUANTITY - (optional) Integer of the value sent with this transaction
`data`: DATA - (optional) Hash of the method signature and encoded parameters. For details see …
> graphql, internal/ethapi: extend eth_call

- accounts/errors.go
- accounts/external/backend.go
- accounts/keystore/keystore.go
- accounts/keystore/plain_test.go
- accounts/keystore/testdata/keystore/README
- cmd/clef/README.md
- cmd/clef/main.go
- cmd/clef/tutorial.md
- cmd/ethkey/README.md
- cmd/ethkey/changepassword.go
- cmd/ethkey/main.go
- cmd/ethkey/message_test.go
- cmd/ethkey/utils.go
- cmd/geth/accountcmd.go
- cmd/geth/accountcmd_test.go
- cmd/puppeth/wizard_faucet.go
- cmd/puppeth/wizard_node.go
- cmd/wnode/main.go
- console/bridge.go
this skips doccomments and variablenames to minimize impact. It does
however include a rename of the `ethkey` `changepassphrase` parameter
> Ref #19906 - replace passPHRASE with passWORD in any user interactions

- core/bench_test.go
- core/state_transition.go
- core/tx_pool.go
- light/txpool.go
- params/protocol_params.go
- tests/transaction_test_util.go
Reown from https://github.com/liorgold2/go-ethereum/pull/1
> core, light, params: implement eip2028

- common/compiler/solidity.go
in the  solidity contacts import paths, default to support relative path：" ./  ../  . " .
> common/compiler: support relative import paths

- p2p/discv5/node_test.go
- p2p/enode/urlv4_test.go
> p2p/enode, p2p/discv5: fix URL parsing test for go 1.12.8

- signer/fourbyte/fourbyte.go
New signatures from ethereum/lists
> fourbyte: updates

- appveyor.yml
Release notes: https://golang.org/doc/devel/release.html#go1.12.minor
BTW: Might be worth waiting for https://github.com/karalabe/usb/pull/6
> appveyor: bump to Go 1.12.9

- core/blockchain.go
- core/blockchain_test.go
This PR fixes a problem which we've seen on the monitoring nodes
```
WARN [08-20|11:36:00.080] Reduced total capacity                   maxFreePeers=153
INFO [08-20|11:36:07.994] Imported new chain segment               blocks=1  txs=104  mgas=8.003  elapsed=9.274s    mgasps=0.863   number=8386921 hash=5c37c8…03da03 age=15m52s   dirty=201.49MiB
INFO [08-20|11:36:16.709] Deep froze chain segment                 blocks=10 elapsed=1.344s    number=8296920 hash=19882b…ac6077
INFO [08-20|11:36:26.607] Imported new chain segment               blocks=1  txs=107  mgas=7.828  elapsed=18.613s   mgasps=0.421   number=8386922 hash=9e95e0…7fcadd age=16m4s    dirty=201.60MiB
INFO [08-20|11:36:46.553] Imported new chain segment               blocks=3  txs=290  mgas=23.962 elapsed=19.945s   mgasps=1.201 …
```
> blockchain: fix flaw in block import

- crypto/blake2b/blake2b_f_fuzz.go
- crypto/blake2b/blake2b_ref.go
When separating out `F` from the hasher, I made `f` itself the platform specific function, and converted the hasher to a global generic one. I forgot to remove the non-amd64 old version.
> crypto/blake2b: fix non-amd64 builds

- core/blockchain.go
metrics chain reorg for `len(oldChain) > 1`
> core: log chain reorg/split metrics

- ethdb/dbtest/testsuite.go
- ethdb/leveldb/leveldb_test.go
- ethdb/memorydb/memorydb_test.go
- ethdb/testsuite.go
Hi there, I've been experimenting with different ethdb backend implementations and I found it helpful to write an ethdb testsuite to clarify and exercise nuances about some of the different interfaces that can be used by all the backends.
- Move the existing tests from memorydb into a generalized testsuite that can be run by any ethdb backend implementation.
- Add several more test cases to clarify some non-obvious nuances when implementing a custom ethdb backend, such as the behaviour of `NewIteratorWithPrefix` vs `NewIteratorWithStart`.
- Add leveldb to the testsuite using in-memory storage for fast execution.
> ethdb: Add testsuite for ethdb backends

- cmd/utils/customflags.go
- cmd/utils/flags.go
As reported under #19453 - this copies cli(.v1).printHelp but
* changes `minwidth` to `40`
* replaces `fmt.Fprintf` with `log.Crit`
> cmd/utils: customize cli.HelpPrinter to fix alignment

- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/config.go
- les/client.go
This is a clone of https://github.com/ethereum/go-ethereum/pull/18273 to support overriding the Istanbul fork block until it passes.
> cmd, core, eth, les: support --override.istanbul

- les/benchmark.go
- les/clientpool.go
- les/clientpool_test.go
- les/peer.go
- les/server.go
- les/server_handler.go
- les/test_helper.go
> les: wait all task routines before drop the peer

- eth/api.go
This is a minor change in `admin.exportChain`, to disallow overwriting existing files. The `admin` namespace really should not be open against external attackers, but if it happens to be, better safe than sorry.
> eth: disallow overwrite files via admin.exportChain

- docs/index.md
This fixes #20014. The sidebar entry for `managing accounts`, has a typo.
> Fix typo in sidebar for account management

- internal/ethapi/api.go
- internal/web3ext/web3ext.go
This PR adds `eth.fillTransaction`, which is useful if signing is done outside of the actual node. 
Below is a reference about what methods exist today (we might want to make it into a table and place in the docs)
Example when using `geth --dev`, which does not really have a sensible GPO. 
```
> eth.fillTransaction({"to":"0x17Ff1b635D4A1E4Ba1377E06d1dD0e1C9015FB5f", value:"100", from:"0x17Ff1b635D4A1E4Ba1377E06d1dD0e1C9015FB5f"})
{
raw: "0xdf80018252089417ff1b635d4a1e4ba1377e06d1dd0e1c9015fb5f6480808080",
tx: {
gas: "0x5208",
gasPrice: "0x1",
hash: "0xea7d97f5fe68d9fc638410cf134f3785ef690330660069252e5d7bb2f122f6c7",
input: "0x",
nonce: "0x0",
r: "0x0",
s: "0x0",
to: "0x17ff1b635d4a1e4ba1377e06d1dd0e1c9015fb5f",
v: "0x0",
value: "0x64"
}
}
```
| Namespace  | Function            | …
> internal/ethapi: implement fillTransaction

- cmd/utils/flags.go
current default for light.maxpeers=100 - after this change it's 10 for clients
this doesn't propagate to `--help` but I think dynamic defaults currently don't really fit in the flags definition
> cmd/utils: reduce light.maxpeers default for clients to 1/10th

- common/types.go
- graphql/graphiql.go
Fixes https://github.com/ethereum/go-ethereum/issues/20041.
Fixes graphiql content type.
> common, graphql: fix hash/address decoding + UI content type

- core/rawdb/freezer.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_table_test.go
- core/tx_pool.go
- metrics/gauge.go
- p2p/metrics.go
I've added a lot of metrics to Influx/Grafana and saw that some charts started going into negative numbers (like peer counts). After digging into them, the issue is that we kind of interchangeably used `counters` and `gauges` in our code, mainly because *counters* had "useful" `Inc()` and `Dec()` ops.
Turns out that this is a big no-no, as time series databases and charting libs use and visualize counters completely differently than gauges. Gauges are allowed to go up and down, but counters should only be ever incremented (the `go-metrics` library API completely misses this point by having a `Dec()` op on a counter).
Long story short, the reason we didn't see this issue with Prometheus/Grafana was because the Prometheus reporting actually reported counters as gauges (ha-ha, should fix …
> core, metrics, p2p: switch some invalid counters to gauges

- common/bytes.go
- core/state/state_object.go
- core/state/state_object_test.go
I noticed this wile investigating the state a bit. What we currently do before RLP-encoding a slot value is to call `TrimLeft`:
```golang
func TrimLeft(s []byte, cutset string) []byte {
return TrimLeftFunc(s, makeCutsetFunc(cutset))
}
```
... which dynamically creates a `cutSetFunction` . 
Then it calls `TrimLeftFunc`, which: 
```golang
// TrimLeftFunc treats s as UTF-8-encoded bytes and returns a subslice of s by slicing off
// all leading UTF-8-encoded code points c that satisfy f(c).
func TrimLeftFunc(s []byte, f func(r rune) bool) []byte {
```
It interprets the data as `UTF-8` encoded data, and parses runes. 
In our case, it's the wrong abstraction, what we want to do here is simply trim leading zeroes, which has nothing whatsoever to do with `UTF-8` and runes. 
This PR replaces that …
> core/state: optimize some internals during encoding

- tests/state_test_util.go
This is a small PR which makes easier to use the test-framework to 'seal' tests, i.e, given a test, find out what the post-state root and logs are. The current existing `Run` method throws errors if the test is wrong, so it's a bit cumbersome to actually find out what the values _should_ be. This PR alleviates that.
> tests: expose internal method

- Makefile
- build/ci.go
- cmd/geth/consolecmd_test.go
- cmd/geth/run_test.go
- crypto/ecies/ecies_test.go
- internal/build/util.go
- les/api_test.go
- p2p/simulations/http_test.go
- tests/init_test.go
- tests/state_test.go
Most of these changes are related to the Go 1.13 changes to flag handling. The release notes
say: 
> Testing flags are now registered in the new Init function, which is invoked by the generated main function for the test. As a result, testing flags are now only registered when running a test binary, and packages that call flag.Parse during package initialization may cause tests to fail. 
Work around this new restriction by introducing TestMain functions in all packages which previously parsed flags during init.
> all: make unit tests work with Go 1.13

- rlp/decode.go
- rlp/decode_test.go
- rlp/doc.go
- rlp/encode.go
- rlp/encode_test.go
- rlp/encoder_example_test.go
- rlp/typecache.go
In both encoder and decoder, the rules for encoding nil pointers were a
bit hard to understand, and didn't leave much choice. Since RLP allows
two empty values (empty list, empty string), any protocol built on RLP
must choose either of these values to represent the null value in a
certain context.
This change adds choice in the form of two new struct tags, "nilString"
and "nilList". These can be used to specify how a nil pointer value is
encoded. The "nil" tag still exists, but its implementation is now
explicit and defines exactly how nil pointers are handled in a single
place.
Another important change in this commit is how nil pointers and the
Encoder interface interact. The EncodeRLP method was previously called
even on nil values, which was supposed to give users a choice of how
their …
> rlp: improve nil pointer handling

- core/blockchain_test.go
- core/state/state_object.go
- core/state/statedb.go
- core/state/statedb_test.go
Byzantium removed the intermediate hashes to avoid having to reconstruct the state tries after each transaction. We indeed avoid hashing all the intermediate tries now (which saves CPU time), but we still reconstruct the tries in memory.
There's no reason for this, since subsequent transactions might modify the same slots. Pushing the updates into the storage tries after each transaction also makes it impossible to make these concurrent, since any single transaction will not modify enough accounts to make it worthwhile.
This PR lays the groundwork for the concurrency PR later on, where we cache all the writes in memory, and only push into the real tries if must (intermediate root or commit).
> core/state: accumulate writes and only update tries when must

- common/mclock/mclock.go
- common/mclock/simclock.go
- common/mclock/simclock_test.go
- les/balance.go
This change adds tests for the virtual clock and aligns the interface
with the time package by renaming Cancel to Stop. It also removes the
binary search from Stop because it complicates the code unnecessarily.
> common/mclock: clean up AfterFunc support

- cmd/evm/runner.go
This is a tiny change, so the `evm` can more easily be used to try out opcodes introduced after Frontier... (note: `AllEthashProtocolChanges` does _not_ contain future forks, like Istanbul)
> cmd/evm: make evm default to all ethash protocol changes

- core/tx_pool.go
The LES server handling seems to put a strain on the txpool. One such point which takes very long time seems to be checking `Status` of a transaction. 
This PR changes the lock section of `Status`, to perform better when a transaction is missing. In that case, we don't need to obtain the full `pool.mu.RLock`, since the `all.Get` operation is already mutex:ed internally. 
LES always only checks the status of the transactions one at a time, so even if the transactions are present in the pool, this particular change does not degrade performance a lot -- before this PR, the LES server caused the lock to be obtained `N` times, which is the case even after.
> txpool: smaller lock portion

- core/tx_pool.go
- core/tx_pool_test.go
Fixes a regression introduced in https://github.com/ethereum/go-ethereum/pull/20081.
The above mentioned PR moved transaction deduplication out of the global pool lock. Unfortunately, I didn't take care with the returned errors, losing a return value for every known transaction. This PR fixes the returned error slice to have a valid value for known transactions too.
> core: fix tx dedup return error count

- core/forkid/forkid_test.go
- params/config.go
Activates Istanbul hardfork:
- Ropsten on `6485846` (Oct 2)
- Görli on `1561651` (Oct 30)
Some sources:
- https://github.com/goerli/testnet/issues/60#issuecomment-532200530
- https://twitter.com/hudsonjameson/status/1174336671342575617
- https://twitter.com/a4fri/status/1173939316101386240
I recommend a release once merged.
Thanks. :pray: 
Ref #19919 
Ref https://github.com/paritytech/parity-ethereum/pull/11068
> params: activate Istanbul on Ropsten, Rinkeby and Görli

- core/state/state_object.go
- core/state/statedb.go
- core/state/statedb_test.go
Fixes https://github.com/ethereum/go-ethereum/issues/20106.
A PR in v1.9.4 (https://github.com/ethereum/go-ethereum/pull/19953) introduced an optimization whereby instead of merging dirty slots into the account/storage tries after each transaction (originally needed for intermediate root), we just flatten them into a plain "pending" map, accumulating writes until we actually need to touch the tries. The benefit is that post-Byzantium, we don't hash the dirty data into the tries until we actually reach the end of the block.
The approach taken in the above PR was to introduce a "pending" map into both the state object and state database to track "transaction boundaries". Unfortunately, tracking yet another place where dirty data ends up in is trickier than I anticipated and introduced two …
> core/state: revert noop finalise, fix copy-commit-copy

- dashboard/dashboard.go
I found it a bit annoying that I couldn't see easily where I could access the dashboard, so this PR adds that info to the logs. 
```
INFO [09-24|10:07:21.980] New local node record                    seq=2 id=7c38e6b9bf1e0c03 ip=127.0.0.1 udp=30303 tcp=30303
INFO [09-24|10:07:21.980] Starting dashboard                       host=localhost port=8080
```
> dashboard: log dashboard url

- les/checkpointoracle.go
- les/client_handler.go
- les/sync.go
- les/sync_test.go
Fixes #20097
The panic is caused by a stupid bug: I forget to initialize the checkpoint passed by client backend in client handler.
Besides, this PR downgrade the sync to `lightSync` if oracle backend is not available and no hardcoded checkpoint is configured.
> les: fix checkpoint sync

- core/blockchain.go
- core/headerchain.go
- eth/api_backend.go
- graphql/graphql.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/api_backend.go
- light/lightchain.go
- rpc/types.go
- rpc/types_test.go
This adds support for [EIP-1898](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1898.md) and supersedes https://github.com/ethereum/go-ethereum/pull/19459 which I forgot was based on 1.8.x.
As mentioned in #19394 there's a couple scenarios where I could see this being useful:
As a DApp developer, I might have logic like:
```golang
result := eth_call({....}, "latest")
// do some potentially slow processing w/ result
// send another RPC a couple seconds later
balance := eth_getBalance(0xsomeAdress, "latest")
```
The issue above is that `"latest"` could refer to totally different blocks.  So next one tries:
```golang
latest := eth_getBlockByNumber("latest", false)
result := eth_call({....}, latest.Number)
// do some potentially slow processing w/ result
// send another RPC a couple …
```
> internal/ethapi: support block number or hash on state-related methods

- core/state/statedb_test.go
The Leak Test intend to demonstrate `state.IntermediateRoot` doesn't actually write cache into cacheDB, while Commit did. However,in both test, it did not commit the trie database to persistent database. Which means the persistent database will always be empty in any scenario. Thus, the original test would always iterator empty persistent database no matter you use `state.Commit` or `state.IntermediateRoot`.  Which makes these test meaningless. Here added the trie database commit method and make this test match its intention.
> core/state: fix database leak tests

- p2p/message.go
- p2p/peer.go
- p2p/rlpx.go
Measures the Snappy compressed wire traffic belonging to individual subprotocols, down to the message type level.
```
"p2p/egress.count": 45975,
"p2p/egress.fifteen-minute": 47.08913611676422,
"p2p/egress.five-minute": 137.58761808377292,
"p2p/egress.mean": 897.3968326322948,
"p2p/egress.one-minute": 594.8198589965016,
"p2p/egress/eth/63/0x00.count": 2153,
"p2p/egress/eth/63/0x00.fifteen-minute": 16.843303813216284,
"p2p/egress/eth/63/0x00.five-minute": 19.683540466014865,
"p2p/egress/eth/63/0x00.mean": 51.209709917385624,
"p2p/egress/eth/63/0x00.one-minute": 35.49422974548988,
"p2p/egress/eth/63/0x01.count": 82,
"p2p/egress/eth/63/0x01.fifteen-minute": 16.128931842674525,
"p2p/egress/eth/63/0x01.five-minute": 15.600162561811711,
"p2p/egress/eth/63/0x01.mean": 4.23382797404747, …
```
> p2p: measure subprotocol bandwidth usage

- build/ci.go
- tests/block_test.go
- tests/init_test.go
- tests/state_test.go
This PR updates the tests, let's see what Travis says about it
> update tests for istanbul

- cmd/bootnode/main.go
For #17579, when generating a key, if the `-writeaddress` flag is passed, print out the address that was generated, and then `os.Exit(0)` is called.   
If `-writeaddress` is not passed in, then the `return` will happen as it did before this change.
Example with `-writeaddress`:
```
$ ./build/bin/bootnode -genkey /tmp/tmp.txt -writeaddress
f53dd1d94cd2e0b2d0386ee4bfd1d12c4c471eb68133b6e509074f4dc6cd64e1e8e4a36d5c447857200235f572b3ecd5f7d743ebffc54ea8387677f5e09b3b9a
$
```
Without `-writeaddress`:
```
$ ./build/bin/bootnode -genkey /tmp/tmp.txt
$ 
```
@karalabe I don't have permission to formally add reviewers, please review if possible.  Or is there a team I can mention to request a review?
> cmd/bootnode: fix exit behavior with -genkey

- cmd/utils/flags.go
In Geth, we have two sources for configuration:
(1) Config file
(2) Command line flag
Basically geth will first resolve config file and then overwrite
configs with command line flags.
This issue is: geth should only overwrite configs if flags are truly
set. So before we apply any flag to configs, `GlobalIsSet` check
is necessary.
> cmd/utils: fix command line flag resolve

- core/blockchain_test.go
- core/genesis.go
- params/config.go
This PR prevents users from misconfiguring their nodes so that fork ordering is not preserved. 
With this PR:
```
$ f=chain_bad.json ; cat $f;  ~/go/src/github.com/ethereum/go-ethereum/build/bin/geth --datadir /tmp/baxz init $f 2>/dev/null
{
"config": {
"byzantiumBlock": 0,
"chainId": 11,
"eip155Block": 0,
"eip158Block": 0,
"homesteadBlock": 0
},
"alloc":{
"0x56a60d978e8830363d6a2c000fbf64c84b8d6875":{
"balance" : "1000000000000000000000000000"
}
},
"difficulty": "0x2000",
"gasLimit": "0xffffffff",
"nonce": "0x0000000000000000",
"coinbase": "0x0000000000000000000000000000000000000000",
"mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"extraData": …
```
> params: check fork ordering when initializing new genesis, fixes #20136

- p2p/dnsdisc/client.go
- p2p/dnsdisc/client_test.go
- p2p/dnsdisc/sync.go
- p2p/dnsdisc/tree.go
- p2p/dnsdisc/tree_test.go
This updates the DNS TXT record format to the latest changes in ethereum/EIPs#2313.
> p2p/dnsdisc: update to latest EIP-1459 spec

- p2p/simulations/adapters/types.go
- p2p/simulations/network.go
- p2p/simulations/network_test.go
- `32ff12e` - Adds two extra flags to adapters.NodeConfig; `bootNode` and `lightNode`. 
Upon creating a simulation node service, `adapters.ServiceContext.Config` can be checked for these flags and the service can be configured accordingly.
I figured this was more appropriate than using ENR records, but please correct me if I am wrong.
- `ae1a9a8` - Builds upon `32ff12e` by checking the `NodeConfig` flags during `NewNodeWithConfig()` and indexes said node into appropriate 'sub' mappings. The sub mappings for light and boot nodes are then used to allow for the fetching and manipulation of said node types.
Furthermore, `GetNodes()` is modified into a variadic function, to allow for the exclusion of specified `enode.ID`s.
The new test function, `TestMultiNodeRetrieval` confirms the …
> p2p/simulations: add node properties support and utility functions

- metrics/README.md
Metrics: change links in README.md to https
> metrics: change links in README.md to https

- miner/worker_test.go
This PR adds a new unit test in miner package which will create some blocks from miner and then import into another chain. In this way, we can ensure all blocks generated by Geth miner obey consensus rules.
> miner: add generate and import unit test

- accounts/abi/bind/base.go
The gas price was not passed to the `EstimateGas` function. As a result, conditional execution paths depending on `tx.gasprice` could be not correctly processed and we could get invalid gas estimates for contract function calls.
> accounts/abi/bind: take into account gas price during gas estimation

- cmd/evm/runner.go
This way, the output of `evm compile` can be used directly in `evm
--codefile code.txt run`, without stripping the trailing newline first.
> cmd/evm: remove surrounding whitespace in hex input code

- core/state/sync_test.go
- eth/downloader/statesync.go
- trie/sync.go
- trie/sync_test.go
When we flush a batch of trie nodes into database during the state
sync, we should guarantee that all children should be flushed before
parent.
Actually the trie nodes commit order is strict by: children -> parent.
But when we flush all ready nodes into db, actually we don't need order
anymore since
(1) they are all ready nodes(no more dependency)
(2) underlying database(e.g. leveldb) can provide write atomicity
> trie: remove node ordering slice in sync batch

- core/asm/compiler.go
- core/asm/compiler_test.go
This pull request fixes several issues in the ASM parser:
- If label `@foo` resolves to `0x123`, then `PUSH @foo` is assembled as `PUSH 0x12300000` rather than `PUSH 0x00000123`.
- When parsing the instruction `PUSH @foo`, PC is incremented by 6 (1 + 5), rather than 5 (1 + 4), since there is no implicit `PUSH` as with `JUMP @foo`.
- `JUMP` with no argument is not allowed, though it could be useful to jump to a label whose address is stored on the stack.
> core/asm: assembly parser label fixes

- cmd/devp2p/crawl.go
- cmd/devp2p/discv4cmd.go
- cmd/devp2p/dnscmd.go
- cmd/devp2p/main.go
- cmd/devp2p/nodeset.go
- cmd/devp2p/nodesetcmd.go
- core/forkid/forkid.go
- p2p/dial.go
- p2p/dial_test.go
- p2p/discover/common.go
- p2p/discover/lookup.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_lookup_test.go
- p2p/discover/v4_udp.go
- p2p/enode/iter.go
- p2p/enode/iter_test.go
- p2p/protocol.go
- p2p/server.go
- p2p/server_test.go
This change adds a new abstraction, `discutil.Iterator`, which is a potentially infinite sequence of nodes. The Discovery v4 listener is extended to provide an iterator over a random walk of the DHT. This new iterator is used to retrieve dial candidates in `p2p.Server`, replacing the call to `LookupRandom`.
Protocol implementations can add their own iterators into the discovery 'mix' by setting the new `DialCandidates` field of `p2p.Protocol` to a non-nil value.
This change also introduces the `discv4 crawl` subcommand for cmd/devp2p. This command creates or updates a JSON node set by running the random walk iterator for a certain duration.
> p2p: dial using node iterator

- core/forkid/forkid.go
- core/forkid/forkid_test.go
This PR adds special casing for 2 fork scenarios that we can didn't differentiate in the original fork id code but scenarios that we do have enough information to do. These were described by @ritzdorf in https://github.com/ethereum/EIPs/issues/2125#issuecomment-542188956 and a solution sketched in https://github.com/ethereum/EIPs/issues/2125#issuecomment-543049010.
The PR does not change the fork ID spec/format, just makes validation a tad smarter.
> core/forkid: add two clauses for more precise validation

- miner/worker_test.go
Fix the unit test of miner which can timeout sometime.
> miner: increase import time allowance

- core/forkid/forkid.go
- eth/handler.go
- eth/handler_test.go
- eth/helper_test.go
- eth/peer.go
- eth/protocol.go
- eth/protocol_test.go
This PR extends the `eth` protocol's handshake with a `fork id` field as defined in https://eips.ethereum.org/EIPS/eip-2124, and bumps the version number to `eth/64` (old `eth/63` is supported side by side of course).
The fork ID was designed to help split the network in case some nodes upgrade and some don't, but both chains progress (typical for test nets during hard forks). With this code in place, Ropsten would now (Istanbul forking) be able to cleanly split itself between updated nodes and non-updated ones.
> eth: eth/64 - extend handshake with with fork id

- core/forkid/forkid_test.go
- params/config.go
This PR enables istanbul for mainnet at block `9069000`
> params: configure mainnet istanbul block 9069K

- les/balance.go
- les/balance_test.go
- les/clientpool.go
- les/clientpool_test.go
- les/odr_test.go
- les/request_test.go
- les/server.go
- les/sync_test.go
- les/test_helper.go
This PR changes `les/clientpool` a bit. Mainly for the refactoring.
The notable change is: the negative balance formula is changed. Under the new formula, all expenses will be calculated in **seconds**
For example, if a free client connects 60s, then the negative balance is `math.Log(60) ~= 4`. After 4 hours, the negative balance is dropped to 0 and discarded by pool.
| Seconds | Math.Log(seconds) |
| ------- | ----------------- |
| 1       | 0                 |
| 5       | 1.6               |
| 10      | 2.3               |
| 60      | 4.1               |
| 300     | 5.7               |
| 3600    | 8.2               |
| 7200    | 8.0                |
Besides, in this PR, nodeDB is introduced. It's a version database which stores all client connection records and balances. Since …
> les: rework clientpool

- core/vm/contracts.go
- core/vm/contracts_test.go
- core/vm/instructions.go
- core/vm/instructions_test.go
- core/vm/memory.go
- eth/tracers/tracer.go
This PR avoids copying memory during calls, and instead passes memory slices by reference. The `input` in execution should not ever be modified, but I'm not 100% sure that this is always respected (particularly I haven't looked in depth into whether alll of our precompiles respects this -- EDIT: `ecRecover` did not, fixed).
If this PR works out, it might be worth it to add a new type `type ReadonlyMem []byte`, and pass that around instead of a raw slice, to make it more obvious that this type should not be modified.
This PR is (so far) mainly for benchmarking, and validating that we can indeed sync through the history without any hiccups.
> core/evm: avoid copying memory for input in calls

- les/clientpool.go
- les/clientpool_test.go
- les/distributor.go
- les/distributor_test.go
- les/odr_test.go
- les/sync_test.go
- les/test_helper.go
- light/postprocess.go
First, this PR fixes a few issues of unit tests which depends on the timeout mechanism.
Like: 
- https://travis-ci.org/ethereum/go-ethereum/jobs/607539832#L480: 
this error I guess is relative with timeout. The original timeout of ODR is 200ms. So it's very easy to return a `timeout` error in travis 
- https://travis-ci.org/ethereum/go-ethereum/jobs/607539830#L559
the `lazyQueue` sometimes may not pop items in strict order. 
Besides, this PR tries to slim down the unit tests of les
> les: fix and slim the unit tests of les

- p2p/peer_test.go
`maybe` must return true probabilistically, but always return false. Therefore, the 50% probability is corrected to be true.
> p2p: fix bug in TestPeerDisconnect

- miner/worker_test.go
`worker_test` tends to fail because on a timeout on travis. This PR increases that timeout.
> miner: increase worker test timeout

- internal/web3ext/web3ext.go
- les/api.go
- les/balance.go
- les/clientpool.go
- les/clientpool_test.go
- les/server.go
This PR implements the LES server API. These are the functions provided for server capacity/balance/priority management (see descriptions in api.go):
```
func (api *PrivateLightServerAPI) ServerInfo() map[string]interface{} {
func (api *PrivateLightServerAPI) ClientInfo(ids []enode.ID) map[enode.ID]map[string]interface{} {
func (api *PrivateLightServerAPI) PriorityClientInfo(start, stop enode.ID, maxCount int) map[enode.ID]map[string]interface{} {
func (api *PrivateLightServerAPI) UpdateBalance(id enode.ID, value int64, add bool, meta string) error {
func (api *PrivateLightServerAPI) SetClientParams(ids []enode.ID, params map[string]interface{}) error {
func (api *PrivateLightServerAPI) SetDefaultParams(params map[string]interface{}) error {
func (api *PrivateLightServerAPI) …
```
> les: implement server priority API

- cmd/faucet/faucet.go
golang.org/x/net/websocket is unmaintained, and we have already
switched to using github.com/gorilla/websocket for package rpc.
> cmd/faucet: use github.com/gorilla/websocket

- .travis.yml
- build/ci.go
Even though the ARM build works relatively well when running for a PR, it fails systematically during a push build.
This PR adds some probes to investigate the difference between the two execution environments, and also reduces the build concurrency in order to find out if this is the root cause of the issue.
> build: gather info to investigate why builds fail on ARM

- params/config.go
> params: finish sentence in comment

- cmd/evm/main.go
- cmd/evm/runner.go
Some inputs might be too large to pass on the command-line.
> cmd/evm: Allow loading input from file

- .travis.yml
This is a continuation of #20281, that fixed the build. Now, the tests are failing in the same fashion and this PR is a first attempt at fixing this new problem.
> travis: Remove traces and use travis_wait in ARM build

- core/state_transition.go
This signature variable name reflects a spec'd change
in gas cost for creating contracts as documented in EIP2 (Homestead HF).
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md#specification
> core: s/isEIP155/isEIP2/ (fix IntrinsicGas signature var name)

- internal/web3ext/web3ext.go
- les/api.go
- les/balance.go
- les/clientpool.go
- les/clientpool_test.go
This PR renames UpdateBalance to AddBalance because now it only does relative modification (addition). The return value is also simplified.
Latest API docs: https://github.com/ethereum/go-ethereum/pull/20303
> les: rename UpdateBalance to AddBalance and simplify return format

- build/ci.go
Adds flag akin to -coverage flag enabling the test runner
to use go test's -v flag, signaling verbose test log output.
> build: add test cmd flag -v for verbose logs

- consensus/clique/api.go
This PR introduces `clique_status` which gives info about the health of the clique network. 
- Which signers are currently active, and have signed blocks in the last `N` (set to 64) blocks? 
- How many blocks has each signer signed? 
- What is the difficulty in the last `N` blocks, compared to the theoretical max ? 
It's currently a bit PITA to find out how a clique network is performing, and it can easily happen that sealers drop off -- and everything is 'fine' until one more signer drops off, and the network suddenly halts. 
This is WIP, but before I polish it (e.g. lowercase json), I'd like some feedback / proposals for things to have here. 
Currently: 
```
[user@work go-ethereum]$ echo '{"jsonrpc":"2.0","method":"clique_status","params":[],"id":1}' | nc -U /tmp/geth.ipc | jq .
{ …
```
> consensus/clique: add clique_status API method

- cmd/ethkey/changepassword.go
Found by staticcheck.
```
cmd/ethkey/changepassword.go:80:52: SA9002: file mode '600' evaluates to 01130; did you mean '0600'? (staticcheck)
if err := ioutil.WriteFile(keyfilepath, newJson, 600); err != nil {
^
```
> cmd/ethkey: fix file permissions in changepassword command

- p2p/netutil/net.go
This fixes the following staticcheck warning:
```
p2p/netutil/net.go:215:37: SA1021: use net.IP.Equal to compare net.IPs, not bytes.Equal (staticcheck)
return nb <= len(ip) && bytes.Equal(ip[:nb], other[:nb])
^
```
> p2p/netutil: fix staticcheck warning

- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
This PR adds an additional check for data retrieved from ancient db.
Since ancient db only maintains the canonical data, so hash is dropped.
Whenever we retrieve some data from ancient db, we should compare
the hash if it's given by user.
> core/rawdb: check hash before return data from ancient db

- .travis.yml
For some reason, Travis works fine when pushing a pull request, and stalls when building master.
It makes no sense to stall a potential release because of this, especially since arm builds will be checked during the pull request. I'm going to do all my builds on a different repo so as not to pollute master, then bring the issue to Travis when I have gathered enough information.
> travis: deactivate arm build during push

- ethclient/ethclient.go
```
ethclient/ethclient.go:517:62: common.ToHex is deprecated: use hexutil.Encode instead.  (SA1019)
```
> ethclient: remove use of common.ToHex

- cmd/wnode/main.go
```
cmd/wnode/main.go:168:28: common.ToHex is deprecated: use hexutil.Encode instead.  (SA1019)
cmd/wnode/main.go:301:37: common.ToHex is deprecated: use hexutil.Encode instead.  (SA1019)
```
> cmd/wnode: remove uses of common.ToHex

- event/feed.go
```
event/feed.go:45:2: field closed is unused (U1000)
```
> event: remove unused field 'closed'

- .github/CODEOWNERS
Anton is unfortunately no longer with us :cry: Remove him from the CODEOWNERS.
> .github: remove 'nonsense' from CODEOWNERS 

- whisper/whisperv6/filter_test.go
- whisper/whisperv6/peer_test.go
This fixes the following warnings:
```
whisper/whisperv6/filter_test.go:39:6: func InitDebugTest is unused (U1000)
whisper/whisperv6/filter_test.go:312:2: this value of env is never used (SA4006)
whisper/whisperv6/peer_test.go:215:3: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
```
> whisper/whisperv6: fix staticcheck warnings

- p2p/simulations/adapters/exec.go
- p2p/simulations/adapters/inproc_test.go
- p2p/simulations/http.go
- p2p/simulations/mocker_test.go
- p2p/simulations/network_test.go
This fixes the following warnings:
```
p2p/simulations/adapters/exec.go:149:2: field key is unused (U1000)
p2p/simulations/adapters/inproc_test.go:37:2: the goroutine calls T.Fatal, which must be called in the same goroutine as the test (SA2002)
p2p/simulations/adapters/inproc_test.go:37:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
p2p/simulations/adapters/inproc_test.go:82:2: the goroutine calls T.Fatal, which must be called in the same goroutine as the test (SA2002)
p2p/simulations/adapters/inproc_test.go:82:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
p2p/simulations/adapters/inproc_test.go:145:2: the goroutine calls T.Fatal, which must be called in the same goroutine as the test …
```
> p2p/simulations: fix staticcheck warnings

- internal/web3ext/web3ext.go
- les/client.go
- light/lightchain.go
This updates the JS clique API wrappers and makes them work with `--syncmode=light`.
> internal/web3ext, les: update clique JS and make it work with the light client

- rpc/client_test.go
- rpc/doc.go
- rpc/handler.go
- rpc/json.go
- rpc/service.go
- rpc/subscription.go
- rpc/testservice_test.go
- rpc/types.go
- rpc/websocket_test.go
There is no technial reason for this restriction because package reflect
can create values of any type. Requiring parameters and return values to
be exported causes a lot of noise in package exports.
Also fixes the following staticcheck warnings:
```
rpc/json.go:157:6: type connWithRemoteAddr is unused (U1000)
rpc/subscription.go:279:43: error should be returned as the last argument (ST1008)
rpc/testservice_test.go:84:39: error should be returned as the last argument (ST1008)
rpc/types.go:100:20: error strings should not be capitalized (ST1005)
```
> rpc: remove 'exported or builtin' restriction for parameters

- miner/miner.go
- miner/worker.go
- miner/worker_test.go
Let's see whether the unit tests are passed or not
> miner: fix data race in tests

- cmd/puppeth/genesis.go
- cmd/puppeth/genesis_test.go
- cmd/puppeth/testdata/stureby_parity.json
Due to https://github.com/paritytech/parity-ethereum/pull/11039, the spec of parity has to be updated.
> cmd/puppeth: update chain spec of parity

- internal/ethapi/api.go
A user ( @sarvesh-ost ) reported that doing `estimateGas` with clef as a backend caused it to prompt for approval 26 times. 
This PR changes the gas estimator so it resolves the address to use only once, not once for each execution. 
@sarvesh-ost  , could you please check if this solves the issue?
> internal/ethapi: don't query wallets at every execution of gas estimation

- cmd/puppeth/genesis.go
Refactors to use existing BlockNonce type instead of
hand-rolled bytes logic.
> cmd/puppeth: x-spec nonce data type, use types.BlockNonce

- cmd/puppeth/ssh.go
Related to https://github.com/ethereum/go-ethereum/issues/16997 , this PR makes puppeth nicer when user tries to respond `y` instead of `yes` to a query
> cmd/puppeth: make ssh prompt more user-friendly

- common/hexutil/json.go
This fixes the following staticcheck warnings:
```
common/hexutil/json.go:89:19: error strings should not be capitalized (ST1005)
common/hexutil/json.go:223:19: error strings should not be capitalized (ST1005)
common/hexutil/json.go:287:19: error strings should not be capitalized (ST1005)
```
> common/hexutil: improve GraphQL error messages

- build/ci.go
The `ci.go` has an external dependency that's not a build dependency. The PPA uploader omitted this one import, causing the builds to fail. This PR forces all the dependencies of `ci.go` to be added to the downloaded modules too.
> build: pull in ci.go dependencies for the PPA builder

- core/blockchain.go
- core/types/block.go
This was only used in one place. This code predates sort.Slice, and converting
the call site to sort.Slice is less code.
This fixes the following staticcheck warnings:
```
core/types/block.go:400:7: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self" (ST1006)
core/types/block.go:413:7: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self" (ST1006)
core/types/block.go:414:7: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self" (ST1006)
core/types/block.go:417:7: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self" (ST1006)
```
> core/types: remove BlockBy sorting code

- accounts/abi/bind/backends/simulated_test.go
This fixes a staticcheck warning:
```
accounts/abi/bind/backends/simulated_test.go:75:2: this value of tx is never used (SA4006)
```
> accounts/abi/bind/backends: remove unused assignment

- accounts/abi/abi_test.go
- accounts/abi/event_test.go
This fixes the following warnings:
```
accounts/abi/abi_test.go:930:68: common.ToHex is deprecated: use hexutil.Encode instead.  (SA1019)
accounts/abi/event_test.go:176:3: field value is unused (U1000)
accounts/abi/event_test.go:362:6: type testResult is unused (U1000)
accounts/abi/event_test.go:368:6: type testCase is unused (U1000)
```
> accounts/abi: fix staticcheck warnings

- trie/database.go
- trie/trie_test.go
This fixes the following staticcheck warnings:
```
trie/database.go:100:18: func rawNode.canUnload is unused (U1000)
trie/database.go:109:22: func rawFullNode.canUnload is unused (U1000)
trie/database.go:134:23: func rawShortNode.canUnload is unused (U1000)
trie/database.go:867:21: func (*Database).verifyIntegrity is unused (U1000)
trie/database.go:889:21: func (*Database).accumulate is unused (U1000)
trie/trie_test.go:320:6: type countingDB is unused (U1000)
```
> trie: remove unused code

- core/asm/lex_test.go
- core/asm/lexer.go
Numbers were already allowed when creating labels, just not when
referencing them.
> core/asm: allow numbers in labels

- go.mod
- go.sum
- trie/database.go
This PR replaces the bigCache with fastCache. 
FastCache is mainly for reducing the memory usage which is really nice for us. 
Besides, fastCache can also support cache dump and reload, so that we 
don't need the warm time to re-fill the cache when we restart.
> vendor, trie: replace bigCache with fastCache

- rlp/decode.go
- rlp/decode_test.go
This removes the following warnings:
```
rlp/decode.go:35:2: error var EOL should have name of the form ErrFoo (ST1012)
rlp/decode_test.go:357:2: field x is unused (U1000)
rlp/decode_test.go:357:5: field y is unused (U1000)
rlp/decode_test.go:810:3: field private is unused (U1000)
```
> rlp: fix staticcheck warnings

- p2p/discover/lookup.go
This is a hotfix for an issue where peer discovery would busy-wait in the lookup
iterator when the node is offline for a while.
> p2p/discover: slow down lookups on empty table

- les/api.go
This PR fixes a deadlock caused by double-locking the clientpool mutex. When requesting info for a disconnected node `getPosBalance` uses the lock and it was called from the callback of `forClients` where the lock is already held.
> les: fix clientInfo deadlock

- cmd/abigen/main.go
- cmd/checkpoint-admin/main.go
- cmd/clef/main.go
- cmd/ethkey/main.go
- cmd/evm/main.go
- cmd/utils/flags.go
solved errors if help flag is provided in some modules such as ethkey
> cmd: fix command help messages in modules

- consensus/ethash/algorithm_test.go
- consensus/ethash/api.go
- consensus/ethash/ethash.go
- consensus/ethash/sealer.go
- consensus/ethash/sealer_test.go
The original idea behind this change was to remove a use of the
deprecated CancelRequest method. Simply removing it would've been an
option, but I couldn't resist and did a bit of a refactoring instead. All
remote sealing code was contained in a single giant function. The refactoring
is to extract remote sealing into its own object, remoteSealer.
> consensus/ethash: refactor remote sealer

- internal/web3ext/web3ext.go
Add `debug_accountRange` to web3ext so that it can be accessed in geth console.
> internal/web3ext: add debug_accountRange

- accounts/abi/pack.go
During our race tests we found the following bug. Since U256() is a destructive function this might overwrite our input parameters.
We correctly clone the input parameters in the other cases.
> accounts/abi/bind: fix destructive packing of *big.Int

- trie/database.go
This is needed to help better compare the snapshotter PR with master.
> trie: track dirty cache metrics, track clean writes on commit

- p2p/enode/iter.go
currently Node() has a data race with Next()
<details><summary>Stack Trace</summary>
<p>
```
Write at 0x00c0001e3748 by goroutine 94:
github.com/ethereum/go-ethereum/p2p/enode.(*sliceIter).Close()
/home/asdf/go/src/github.com/ethereum/go-ethereum/p2p/enode/iter.go:101 +0x85
github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).Close()
/home/asdf/go/src/github.com/ethereum/go-ethereum/p2p/enode/iter.go:191 +0x124
github.com/ethereum/go-ethereum/p2p/enode.TestFairMixEmpty()
/home/asdf/go/src/github.com/ethereum/go-ethereum/p2p/enode/iter_test.go:155 +0x38a
testing.tRunner()
/snap/go/4762/src/testing/testing.go:909 +0x199
Previous read at 0x00c0001e3748 by goroutine 15:
github.com/ethereum/go-ethereum/p2p/enode.(*sliceIter).Node() …
```
> p2p/enode: prevent data race in sliceIter

- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- consensus/ethash/consensus.go
- core/forkid/forkid_test.go
- core/genesis.go
- eth/backend.go
- eth/config.go
- les/client.go
- params/config.go
WIP, this implements https://github.com/ethereum/EIPs/pull/2384, which nudges the difficulty bomb another 4M blocks (9M in total). 
cc @shemnon
> consensus/ethash, params: implement eip-2384: bump difficulty bomb

- docs/_install-and-build/Installing-Geth.md
As mentioned in https://github.com/ethereum/go-ethereum/issues/20255 this PR removes run steps from the install guide, and keeps it purely about installing
> [DOCS] Remove run steps from install guide

- accounts/abi/bind/backends/simulated.go
- core/events.go
- eth/api_backend.go
- eth/filters/api.go
- eth/filters/bench_test.go
- eth/filters/filter.go
- eth/filters/filter_system.go
- eth/filters/filter_system_test.go
- eth/filters/filter_test.go
- internal/ethapi/backend.go
- les/api_backend.go
- miner/miner.go
- miner/worker.go
This fixes the following staticcheck warnings:
```
eth/filters/api.go:56:13: SA1019: event.TypeMux is deprecated: use Feed  (staticcheck)
mux       *event.TypeMux
^
eth/filters/filter.go:35:14: SA1019: event.TypeMux is deprecated: use Feed  (staticcheck)
EventMux() *event.TypeMux
^
eth/filters/filter_system.go:92:13: SA1019: event.TypeMux is deprecated: use Feed  (staticcheck)
mux       *event.TypeMux
^
internal/ethapi/backend.go:46:14: SA1019: event.TypeMux is deprecated: use Feed  (staticcheck)
EventMux() *event.TypeMux
^
accounts/abi/bind/backends/simulated.go:79:42: SA1019: event.TypeMux is deprecated: use Feed  (staticcheck)
events:     filters.NewEventSystem(new(event.TypeMux), &filterBackend{database, blockchain}, false),
^
accounts/abi/bind/backends/simulated.go:467:38: SA1019: …
```
> eth/filters: remove use of event.TypeMux for pending logs

- cmd/devp2p/dnscmd.go
- go.mod
- p2p/dnsdisc/client.go
- p2p/dnsdisc/client_test.go
- p2p/dnsdisc/sync.go
- p2p/dnsdisc/sync_test.go
- p2p/dnsdisc/tree.go
- p2p/dnsdisc/tree_test.go
These changes make it possible to use DNS-based discovery as a node discovery source in p2p.Server. There are a couple of other improvements to p2p/dnsdisc in this PR:
- The client now rate-limits DNS requests using golang.org/x/time/rate.
- Link handling is much simpler and has higher test coverage.
- TestIteratorLinkUpdates is stabler and doesn't fail on 1/50 runs anymore.
> p2p/dnsdisc: add enode.Iterator API

- cmd/abigen/main.go
This is a fix for #20418 
Solidity has a `combined_json` output with the following schema:
```
{
"filename:contractname": { ... }
...
}
```
In the case of vyper, it's only:
```
{
"filename": { ... }
...
}
```
This PR sanitizes the output if such a case is detected. I will also open an issue in the vyper repo.
> cmd/abigen: Sanitize vyper's combined json names

- eth/api.go
- internal/web3ext/web3ext.go
I was playing w/ the block importing/exporting logic today to get a better understanding of how it worked, and realized that the only way currently to export blocks is to use `admin_exportChain` (which exports the entire chain) or `geth export` (which requires the node to be stopped since only one process can have access to the leveldb).
So, this simply adds a new `admin_exportBlocks` RPC that takes the same arguments as `geth export` but can be done while the node is running.
> eth, internal/web3ext: add optional first and last arguments to the `admin_exportChain` RPC.

- cmd/evm/main.go
- cmd/evm/runner.go
The --bench flag uses the testing.B to execute the EVM bytecode many times and get the average exeuction time out of it.
> cmd/evm: Add --bench flag for benchmarking

- les/peer.go
- les/server_handler.go
This PR explicitly detects in server mode if the other peer is another server. In this case it disables block announcements and short-circuits the protocol handler, sends and expects no messages but does not actively disconnect.
Fixes https://github.com/ethereum/go-ethereum/issues/17556
> les: do not disconnect another server

- docs/_rpc/ns-txpool.md
A very long time ago we changed the txpool to only maintain 1 transaction per account per nonce. We've never updated the docs accordingly.
Fixes https://github.com/ethereum/go-ethereum/pull/20511.
> docs: fix txpool APIs to get rid of lists-per-nonces

- rpc/websocket.go
Allow instantiating a  RPC websocket client using a custom dialer so a user can use custom dial options. 
This is similar to the `DialHTTPWithClient` which allows instantiating a RPC http client with a custom http client.
> rpc: add DialWebsocketWithDialer

- cmd/geth/consolecmd_test.go
To test the console's welcome message, an instance of `geth` is started. If the test detects an invalid output, it will panic and not execute `geth.Interrupt` so the instances are left running.
> cmd/geth: fix forked exe leak in console tests

- internal/ethapi/api.go
I have fixed removed the `totalDifficulty` field from API `eth_getUncleByBlockHashAndIndex` as suggested in #19024. Also, I have made a change in block number of `eth_getBlockByNumber("pending")`. Now, block number will be marked `null` because parity also does the same. 
Fixes: #19024 and #19332
> internal/ethapi: fix encoding of uncle headers and pending blocks

- trie/node_test.go
- trie/trie_test.go
add some unit tests for node.go
> add node.go unit test file node_test.go

- whisper/whisperv6/peer.go
This PR fixes Whisper module, Ticker leak caused when Peer node is disconnected
> whisper/whisperv6: fix peer time.Ticker leak

- eth/backend.go
I was following the code for creating a New ethereum object and I found this part little confusing, like creating first the backend with nil gpo to later set it, if not important just discard. 
Thanks
> eth: refactor creation of EthAPIBackend

- internal/testlog/testlog.go
This changes the unit test logger to print the actual file and line
number of the logging call instead of "testlog.go:44".
Output of 'go test -v -run TestServerListen ./p2p' before this change:
=== RUN   TestServerListen
--- PASS: TestServerListen (0.00s)
testlog.go:44: DEBUG[01-08|15:16:31.651] UDP listener up         addr=127.0.0.1:62678
testlog.go:44: DEBUG[01-08|15:16:31.651] TCP listener up         addr=127.0.0.1:62678
testlog.go:44: TRACE[01-08|15:16:31.652] Accepted connection     addr=127.0.0.1:62679
And after:
=== RUN   TestServerListen
--- PASS: TestServerListen (0.00s)
server.go:868: DEBUG[01-08|15:25:35.679] TCP listener up         addr=127.0.0.1:62712
server.go:557: DEBUG[01-08|15:25:35.679] UDP listener up         addr=127.0.0.1:62712
server.go:912: TRACE[01-08|15:25:35.680] …
> internal/testlog: print file+line number of log call in test log

- core/state/statedb.go
This PR adds some more verbosity to a `panic` that occurred in https://github.com/ethereum/go-ethereum/issues/20539 . Makes no sense not to be as verbose as possible on panics.
> core/state: add more verbosity to panic

- core/tx_list.go
- core/tx_pool.go
- core/tx_pool_test.go
This change allows transactions of bigger than 32KB. To prevent DoS over the tx pool (the original reason to limit the transaction size), this change should not introduce any additional memory consumption over the original implementation. Thus instead of the straightforward solution of enlarging the hard-coded limit, it introduces slots in the tx pool. The size of the tx pool is limited by the number of slots. Each slot is of size up to 32KB, and each transaction can now take up to 4 slots. The eviction of underpriced transactions stays the same as before, in particular, a 4-slot transaction can evict 4 1-slot transactions even in the case it is slightly more profitable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> core/tx_pool: count tx size in slots, bump max size ot 4x32 Kb

- eth/handler.go
- eth/handler_test.go
Malformed blocks are detected and rejected by the chain inserter. If however a malformed block is broadcast to us, we only do PoW checks and quickly forward it to keep latency down. This is unfortunate, because PoW does not protect against a bad body, so every new valid PoW is an opportunity to propagate a (one!) malformed block through the network.
This PR fixes it by moving a malformation detection into block receiption (propagation is the only place where an entire block is transmitted in assembled form, the rest of the protocol already uses split headers/bodies). Long term if we rework block propagation to be smarter, even this one instance can be dropped.
The PR currently just silently discards these blocks, but long term we want to drop the offending peer altogether for protocol …
> eth: check propagated block malformation on receiption

- core/tx_pool.go
This PR 'cripples' the tx size that was increased by https://github.com/ethereum/go-ethereum/pull/20352 . The reasoning is that we've been seeing some crashes on nodes with many peers, related to tx pools, and would like to wait with bumping the tx size too much until EIP-2464 has been adopted: https://github.com/ethereum/EIPs/issues/2465
> core: set max tx size down to 2 slots (64KB)

- eth/handler_test.go
Failure https://travis-ci.org/ethereum/go-ethereum/jobs/636889602#L710 : 
```
ok  	github.com/ethereum/go-ethereum/crypto/ecies	0.061s	coverage: 75.9% of statements
ok  	github.com/ethereum/go-ethereum/crypto/secp256k1	1.472s	coverage: 30.6% of statements
--- FAIL: TestBroadcastBlock (7.12s)
handler_test.go:634: block broadcast to 3 peers, expected 4
FAIL
coverage: 28.0% of statements
FAIL	github.com/ethereum/go-ethereum/eth	17.103s
ok  	github.com/ethereum/go-ethereum/eth/downloader	41.391s	coverage: 78.3% of statements
```
This might fix it, at least make it less common
> eth: increase timeout to fix a spurious travis test failure

- .golangci.yml
- build/checksums.txt
- build/ci.go
The `arm64` linter build seems to be broken, and indeed the `arm64` version of `golangci` is not available for this platform. This PR upgrades the ci build to match the latest version, that has support for `arm64`.
> build: upgrade golangci to 1.22.2

- p2p/server.go
This is a temporary fix for a problem which started happening when the
dialer was changed to read nodes from an enode.Iterator. Before the
iterator change, discovery queries would always return within a couple
seconds even if there was no Internet access. Since the iterator won't
return unless a node is actually found, discoverTask can take much
longer. This means that the 'emergency connect' logic might not execute
in time, leading to a stuck node.
> p2p: ensure Server.loop is ticking even if discovery hangs

- cmd/devp2p/dns_cloudflare.go
- cmd/devp2p/dns_route53.go
- cmd/devp2p/dns_route53_test.go
- cmd/devp2p/dnscmd.go
This works around the 32k RDATA character limit per change request.
> cmd/devp2p: submit Route53 changes in batches

- core/blockchain.go
- core/headerchain.go
- light/lightchain.go
This PR changes the way to write chain data.
Now we can classify the chain data into two parts:
* Header chain data
* Block chain data
The reason we classify it is: 
* for light client, it only maintains the header chain
* for sync, we write header chain first and then fulfill the remaining data like body and receipts.
So that there are two separate data structures `headerchain` and `blockchain`.
The pain point is both `header chain data`  and `block chain data` are divided into several components
For `header chain`, we have:
* header
* total difficulty
* hash -> number mapping
For `block chain`, we have:
* header
* total difficulty
* hash -> number mapping
* body
* receipts
So in order to ensure the integrity of the chain data, all the components have to be written in an atomic way.
So …
> core: write chain data in atomic way

- trie/database.go
- trie/trie_test.go
Replaces https://github.com/ethereum/go-ethereum/pull/20527 , this one does not contain all the other experimental fluff. 
In the trie database, there are several operations that recursively walk children of nodes, and collect them into lists of hashes. ~~This means that on the leaf level, all the upper levels hold N lists with hashes. So at root level, the list contains all leaf hashes, at level below, a list with 1/16th of the entries, and so on.~~
This PR changes it to walk the nodes with a callback instead. Needs to be benchmarked and tested IRL, of course. 
before
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/trie
BenchmarkDerefRootFixedSize/10-6                   61821             19229 ns/op           14609 B/op         38 allocs/op …
```
> Database cachednode callback walk

- core/chain_indexer_test.go
This PR fixes unit tests of chain indexers.
In #19748 we fix an issue in chain indexer when it tries to run reorg. The change is the given `head` in `newHead` function is the `common ancestor` of new head header and previous head header. So `head` is still considered valid. The change merged is using `known := (head + 1) / c.sectionSize` to calculate the section index which need to be reverted instead of using `head/c.sectionSize`.
But we don't change the unit test, this PR just follow the original merged change.
Fixes #20497
> core: fix indexer unit test

- cmd/devp2p/main.go
- cmd/geth/main.go
- internal/debug/flags.go
- log/handler.go
We added this for the dashboard, which is gone now. The
handler never really worked well and had data race and file
handling issues.
> log: delete RotatingFileHandler

- cmd/abidump/main.go
- signer/fourbyte/abi.go
- signer/fourbyte/validation.go
This PR implements `abidump`, a utility to parse calldata against the fourbyte directory database. 
```
[user@work abidump]$ ./abidump 
Error: one argument needed
Usage: ./abidump <hexdata>
Parses the given ABI data and tries to interpret it from the fourbyte database.
```
```
[user@work abidump]$ ./abidump a9
WARNING: Transaction data is not valid ABI (missing the 4 byte call prefix)
```
```
[user@work abidump]$ ./abidump a9059cbb
WARNING: Transaction contains data, but provided ABI signature could not be verified: signature "function transfer(address , uint256 ) returns()" matches, but arguments mismatch: abi: cannot marshal in to go type: length insufficient 0 require 32
```
```
[user@work abidump]$ ./abidump a9059cbb000000000000000000000000ea0e2dc7d65a50e77fc7e84bff3fd2a9e781ff5c000000 …
```
> cmd: implement abidump

- cmd/geth/retesteth.go
Retesteth was kind of illogical, when blocks were imported `[1,2,3a,4,3b]`, it thought that `3b` was the canon head (since Importblocks does not return an error if a side-block is imported). 
This PR removes the separate blockNumber counter from the API, and uses the actual current head from `blockchain` when needed. 
Requested by @winsvega , PTAL if this fixes your issues.
> cmd/geth/retesteth: use canon head instead of keeping alternate count

- cmd/evm/disasm.go
Even though the `evm` utility has `--input value` as a global option, the `disasm` subcommand does not use it. This PR enables the usage of the `--input` switch as an input method.
> cmd/evm: accept --input for disasm command

- cmd/geth/consolecmd_test.go
- console/bridge.go
- console/console.go
- console/console_test.go
- go.mod
- go.sum
- internal/jsre/completion.go
- internal/jsre/completion_test.go
- internal/jsre/jsre.go
- internal/jsre/jsre_test.go
- internal/jsre/pretty.go
As #19761 was becoming too complex and also really hard to rebase, I have decided to break the switch into several sub-PR to make it easier to review.
This is the first PR, in which only the console is switched to goja. The signer still uses otto and the tracer still uses duktape.
Closes #14649
> console, internal/jsre: use goja

- rpc/client.go
When running geth with external signer (Clef), if Clef is restarted, the first call to Clef always fail but the subsequent calls work fine.
In `rpc/client.go`, when any error like `EOF` is sent to `readErr` channel, `conn` will be closed but `c.writeConn` is not set to nil. If a new request comes after `conn` is closed, it must fail once before it will try to reconnect. This fix is to set `c.writeConn = nil` when `readErr` is received and `conn` is closed.
> rpc: reset writeConn when conn is closed on readErr

- cmd/geth/config.go
- rpc/endpoints.go
```text
$ geth --rpc --rpcapi foo
...
Fatal: Error starting protocol stack: invalid API "foo" in whitelist (available: admin, debug, web3, eth, txpool, personal, ethash, net, les)
```
Resubmit of #20468 
Fixes #20467
> rpc: check module availability at startup

- go.mod
- go.sum
- signer/rules/rules.go
- signer/rules/rules_test.go
> signer/rules: use goja and remove otto

- cmd/geth/retesteth.go
By request from @winsvega , this PR defaults to dao support when mining in retesteth, and also purges transactionpool when rewinding the head.
> retesteth: clean txpool on rewind, default dao support

- params/bootnodes.go
The C++ bootnode has been gone since long, and we're switching the Goerli bootnode over to a different machine (with elastic IP this time, so next time we don't have to change the entry).
> params: update bootnode list

- eth/tracers/tracer.go
- eth/tracers/tracer_test.go
This PR adds regression tests for the panics outlined in https://github.com/ethereum/go-ethereum/issues/20611.
This PR is **not** providing a fix for https://github.com/ethereum/go-ethereum/issues/20611.
cheers,
tin
> tracers: avoid panic on invalid arguments 

- core/evm.go
- core/vm/runtime/env.go
- core/vm/runtime/runtime_test.go
I've realized that https://github.com/ethereum/go-ethereum/pull/19319 might never make it in. It's quite big. 
So, here's a very small PR which, although not as awesome as that one, is still a lot better than the way things work currently.
> Improved blockhash caching

- cmd/geth/chaincmd.go
- cmd/geth/main.go
Adds `geth dumpgenesis` command, which writes the configured genesis in JSON format to _stdout_.
This provides a way to generate the data (structure and content) that can then be used with the `geth init` command.
```
$ ./build/bin/geth dumpgenesis | jj -p | head -30
{
"config": {
"chainId": 1,
"homesteadBlock": 1150000,
"daoForkBlock": 1920000,
"daoForkSupport": true,
"eip150Block": 2463000,
"eip150Hash": "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0",
"eip155Block": 2675000,
"eip158Block": 2675000,
"byzantiumBlock": 4370000,
"constantinopleBlock": 7280000,
"petersburgBlock": 7280000,
"ethash": {}
},
"nonce": "0x42",
"timestamp": "0x0",
"extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
"gasLimit": "0x1388",
"difficulty": …
```
> cmd/geth: add 'dumpgenesis' cmd

- trie/hasher.go
- trie/iterator.go
- trie/proof.go
- trie/secure_trie.go
- trie/trie.go
This is a follow-up to https://github.com/ethereum/go-ethereum/pull/20481 , which implements 
- Counting updates to the trie, 
- Paralellizing the hashing operation, if the number of changes exceed 99 items. 
The benchmarks below are against https://github.com/ethereum/go-ethereum/pull/20481
```
[user@work trie]$ benchstat serial_hash.txt paralell_hash.txt 
name                  old time/op    new time/op    delta
Hash-6                  6.56µs ±16%    4.34µs ± 3%  -33.79%  (p=0.016 n=5+4)
HashFixedSize/10-6      63.1µs ± 1%    63.6µs ± 3%     ~     (p=0.310 n=5+5)
HashFixedSize/100-6      295µs ± 1%     257µs ± 1%  -12.74%  (p=0.008 n=5+5)
HashFixedSize/1K-6      3.41ms ± 9%    2.43ms ± 8%  -28.93%  (p=0.008 n=5+5)
HashFixedSize/10K-6     39.3ms ± 7%    28.1ms ± 5%  -28.42%  (p=0.008 …
```
> Parallel hashing

- cmd/devp2p/dns_route53.go
- cmd/devp2p/dns_route53_test.go
For longer records and subtree entries, the deployer created two
separate TXT records. This doesn't work as intended because the client
will receive the two records in arbitrary order. The fix is to encode
longer values as "string1""string2" instead of "string1", "string2".
This encoding creates a single record on AWS Route53.
> cmd/devp2p: fix Route53 TXT record splitting

- internal/ethapi/api.go
…block
Ref: https://github.com/ethereum/go-ethereum/pull/20460 
Fixes: https://github.com/ethereum/go-ethereum/issues/20587 , https://github.com/ethereum/web3.py/issues/1572
> internal/ethapi: return non-null "number" for pending block

- graphql/graphql.go
- graphql/schema.go
The feature update allows the graphql api endpoint to retrieve transaction signature R,S,V parameters.
> graphql: add transaction signature values

- docs/_interface/Command-Line-Options.md
- docs/_interface/FAQ.md
This doesn't fix the underlying issue, but does make it easier to find a workaround and any indications of progress towards a more robust handling of password files.  Documentation was [requested](https://github.com/ethereum/go-ethereum/issues/19905#issuecomment-520755645) in the issue discussion.
Note: This is not against the `master` branch because that branch lacks the modified documentation files.
> [DOCS] add note about unicode BOM in password files

- rpc/client.go
- rpc/client_test.go
> rpc: add error when call result parameter is not addressable

- signer/core/signed_data.go
Hi,
This PR is for accepting `bytes32` of TypedData, especially TypedDataMessage in it.
I got the following error when I use `bytes32` in the message data of EIP712.
```
unknown type 'bytes32'
```
I just added `bytes32` check conditions into `isPrimitiveTypeValid`.
> Add conditions for bytes32 at isPrimitiveTypeValid

- common/mclock/mclock.go
- common/mclock/simclock.go
- common/mclock/simclock_test.go
These methods can be helpful when migrating existing timer code.
> common/mclock: add NewTimer and Timer.Reset

- les/server_handler.go
When the light server disconnects due to not being synced, it gives no reason for that. Provide that reason in a debug log message.
> les: log disconnect reason when light server is not synced

- event/feed.go
In event/feed.go,
func `Send()`, `f.mu.Lock()` is on L135,
and `f.mu.Unlock()` is on L143.
However, there is a panic on L141.
If the panic is executed, f.mu will still be locked even after recovery.
The fix is to add `f.mu.Unlock()` before panic.
> event: add missing unlock before panic

- accounts/abi/bind/backends/simulated.go
Hey,
currently the simulated backend ignores the blockNumber parameter and returns an error whenever it is non-nil and not equal to the current blockNumber. Unfortunately this prohibits us from querying older states (especially code) of the blockchain.
> accounts/abi/bind/backends: add support for historical state

- event/subscription.go
- event/subscription_test.go
- p2p/simulations/adapters/exec.go
`subscribe()` in event/subscribe.go and `Stop()` in p2p/simulations/adapters/exec.go share a same problem:  some goroutines in these functions will be leaked in certain cases (unsub for `subscribe()`, and timeout for `Stop()`).
In `subscribe()`, the send operation `subscribed <- err` on L115 will be blocked forever when `unsub` is selected. Thus the child goroutine leaks and always occupies the memory.
Adding one buffer to the channel will make the send operation never block the child goroutine,
and it will not change semantic.
The same is true for `Stop()`.
In `Stop()`, although `Kill()` is called on timeout,
I am not sure if the child goroutine will be in the same process or not. Here is the annotation of `Kill()`, in /os/exec.go:
```
// Kill causes the Process to exit immediately. Kill …
```
> event, p2p/simulations/adapters: use buffered channel to avoid goroutine leak

- accounts/manager.go
As the [https://golang.org/pkg/sync/](https://golang.org/pkg/sync/) says about RLock:
`It should not be used for recursive read locking; a blocked Lock call excludes new readers from acquiring the lock.`
So double read lock should also be avoided.
The first RLock is `am.lock.RLock()` in func `Wallet()`, the second RLock is in its callee func `Wallets()`.
The fix is to add a new func `walletsNoLock()` and let `Wallet()` and `Wallets()` call it.
> accounts: add walletsNoLock to avoid double read lock

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/backend.go
- eth/config.go
- eth/discovery.go
- eth/gen_config.go
- node/node.go
- node/service.go
- node/service_test.go
- params/bootnodes.go
This change adds auto-configuration of DNS discovery URLs for supported networks.
Users can override the enrtree:// entry points using the `--discovery-urls` flag (suggestions for
better names are welcome). Package eth applies this setting by injecting nodes from the given DNS roots as dial candidates.
The change works as-is, but will work a lot better in combination with #20592 because nodes found through DNS will be dialed faster.
The default lists live on the ethdisco.net domain and their content is tracked
at https://github.com/ethereum/discv4-dns-lists
> cmd/geth: enable DNS discovery by default

- core/blockchain.go
This PR fixes an issue with the prefetcher, where several things were not properly given to the closure. WHen importing blocks very fast, e.g. `import blocks.rlp` on goerli, it could happen that the prefetcher closure did not start until _after_ the state was already pruned, leading to a panic.
> blockchain: ensure state exists for prefetcher

- cmd/faucet/faucet.go
In cmd/faucet/faucet.go,
`f.reqs` is protected by `f.lock.Lock()` or `f.lock.Rlock()` at five places.
The only place where it is not protected is on L367 in func `apiHandler()`.
This may cause data race when `apiHandler()` and other func like `refresh()` where `f.reqs` is written to are called in parallel.
The fix is to use `f.lock.Rlock()` to protect `f.reqs`.
> cmd/faucet: protect f.reqs with Rlock to prevent data race

- p2p/metrics.go
- p2p/peer.go
- p2p/rlpx.go
- p2p/server.go
This event was added for the dashboard, but we don't need it anymore
since the dashboard is gone.
> p2p: remove MeteredPeerEvent

- cmd/ethkey/generate.go
- cmd/ethkey/message_test.go
This fixes occasional failures of the test under heavy load, i.e. when running many tests in parallel.
Before:
```
=== RUN   TestMessageSignVerify
--- PASS: TestMessageSignVerify (2.78s)
```
After:
```
=== RUN   TestMessageSignVerify
--- PASS: TestMessageSignVerify (0.52s)
```
> cmd/ethkey: speed up test by using weaker scrypt parameters

- eth/handler.go
- eth/handler_test.go
Currently we always propagate a block/transaction to at least 4 peers, even if the square root is less (e.g. if I have 5 peers, I will propagate to 4, not just to 2). As far as I know this was added when there was no announcement mechanism at all (i.e. eth/60).
I think this is misguided:
* If a node is so unhealthy that it barely has a few connections, there's no point in pushing even more load onto it.
* Every node will surely broadcast to at least 1 more peer (`sqrt(whatever_gt_1) >= 1`) and the announces will cover any gaps for super degenerate topologies.
* If a node is healthy, it will **always** happen (when broadcast saturates the network) that most of its peers already sent it a block/tx, so `PeersWithoutBlock` and `PeersWithoutTx` will return a small subset of peers. With the …
> eth: don't enforce minimum broadcast, fix broadcast test

- p2p/dnsdisc/client_test.go
- p2p/dnsdisc/sync.go
This adds additional logic to re-resolve the root name of a tree when a
couple of leaf requests have failed. We need this change to avoid
getting into a failure state where leaf requests keep failing for half
an hour when the tree has been updated.
> p2p/dnsdisc: re-check tree root when leaf resolution fails

- common/mclock/simclock_test.go
- eth/handler_test.go
- p2p/server_test.go
- rpc/client_test.go
In server_test.go,
Goroutine may leak because sending to `accept` is blocked on L141 when `select` on L156 selects timeout on L204. Although `t.Error()` is called in this case, it won't stop the leaking, because "[Calling FailNow does not stop those other goroutines.](https://golang.org/pkg/testing/#T.FailNow)". The fix is to replace the unbuffered channel with a buffered channel (buffer size 1), and the semantic is not changed.
There are 5 bugs following the same pattern and fix in #20663.
> all: fix goroutine leaks in unit tests by adding 1-elem channel buffer

- les/serverpool.go
We previously added the bootstrap nodes as candidates in p2p/dial.go, but this
feature was removed in #20592. This change adds it back for LES since there are
too few peers for it to work without this.
> les: add bootstrap nodes as initial discoveries

- core/vm/eips.go
- params/protocol_params.go
I was doing some bench marking and analysis surrounding some of the recent EIPs. While tinkering with EIP-1884 I accidentally created a split on a private network between Parity, Besu and Geth, where Parity and Geth forked together with SLOAD_GAS of 200 rather than 800. After investigating, I discovered that EIP-2200 was "technically" incorrectly implemented.
EIP-1884 and EIP-2200 both adjust `SLOAD_GAS` from `200` to `800` - but the current implementation of EIP-2200 assumes that  EIP-1884 is already implemented, and only adjusts `SSTORE`.
This PR adds the EIP-1884 `SLOAD_GAS` changes to EIP-2200.
There is a [Sibling PR](https://github.com/paritytech/parity-ethereum/pull/11474) in Parity
> core/vm: use dedicated SLOAD gas constant for EIP-2200

- go.mod
- go.sum
The new goja version supports the 'escape' and 'unescape' built-in functions.
This fixes #20693
> go.mod: upgrade goja to latest

- docs/_rpc/server.md
The error message if you call a non-whitelisted namespace is slightly misleading, so I added a note about the error you receive.
> [DOCS] Clarify calling non-whitelisted namespace

- eth/fetcher/tx_fetcher_test.go
This PR fixes an accidental randomness leftover in the tx fetcher tests, which caused CI to fail on certain PRs. The values were the actual ones randomized by the correct run.
> eth/fetcher: remove randomness from test data

- eth/downloader/queue.go
Fixed inconsistency and also potential data race in eth/downloader/queue.go:
e.g. In eth/downloader/queue.go:
`q.receiptPendPool` is read/written 10 times; 9 out of 10 times it is protected by q.lock.Lock(); 1 out of 10 times it is read without a Lock, which is in func CancelReceipts() on L579.
A data race may happen when `CancelReceipts()` and other func like `Revoke()` are called in parallel.
The fix is to move lock from func `cancel()` to its caller `CancelReceipts()`.
The other bugs and fixes are similar.
Note that there is an FP for eth/downloader/peer.go in PR [20650](https://github.com/ethereum/go-ethereum/pull/20650). I remove the changes in peer.go and start a new PR here.
> eth/downloader: fix possible data race by inconsistent field protection

- internal/ethapi/api.go
This PR fixes #20685 by defaulting to nil-account.
> internal/ethapi: default to 0x00-account instead of local accounts for calls

- les/benchmark.go
- les/client.go
- les/client_handler.go
- les/clientpool.go
- les/commons.go
- les/distributor.go
- les/distributor_test.go
- les/fetcher.go
- les/handler_test.go
- les/odr.go
- les/odr_requests.go
- les/odr_test.go
- les/peer.go
- les/peer_test.go
- les/request_test.go
- les/retrieve.go
- les/server.go
- les/server_handler.go
- les/serverpool.go
- les/servingqueue.go
- les/sync.go
- les/sync_test.go
- les/test_helper.go
- les/txrelay.go
- les/ulc_test.go
This is the second big refactor PR for les package.
In this PR, peers are separated into two types: **serverPeer** and **clientPeer**. The former refers to the peers of `light_client`. The latter refers to the peers of `les_server`.
> les: separate peer into clientPeer and serverPeer

- mobile/bind.go
This was missing because we forgot to wrap it when bind.CallOpts.From as added.
Fixes: #18034
> mobile: add CallOpts.SetFrom

- crypto/bn256/bn256_slow.go
> crypto/bn256: fix import line

- docs/_interface/JavaScript-Console.md
"eth attach" should be "geth attach"
A letter missing
> "eth attach" should be "geth attach"

- eth/peer.go
The `fail` channels in the transaction announcement and broadcast loops were blocking, which meant that any announcement started must be allowed to finish before exiting the broadcaster. This was not the case as a peer drop concurrently closed the peer's termination channel and aborted the send. Depending on the ordering of the event, the outer broadcaster method might have reacted to the `p.term` closure faster, never reading the failure from `fail`.
One way to solve it would be to track any pending requests and only return from the outer method when the goroutine requests finish. This PR takes a simpler approach by converting the `fail` from a blocking channel to a notification one. This way if the sending goroutine is left dangling, it will just write into a noop channel.
> eth: fix transaction announce/broadcast goroutine leak

- cmd/geth/retesteth.go
some extreme tests take really long block processing time
http timeouts must be increased for test execution
> increase geth retesteth default http timeouts

- docs/_dapp/tracing.md
This should be an easy typo and can be immediately fixed. Correct me if I'm wrong.
> [DOCS] fix typo of syncing mode "fast" -> "full"

- go.mod
- go.sum
This revision of go-duktype fixes the following warning emitted while building or testing go-ethereum on Ubuntu 19.10 x64, and go version 1.13.8
```
duk_logging.c: In function ‘duk__logger_prototype_log_shared’:
duk_logging.c:184:64: warning: ‘Z’ directive writing 1 byte into a region of size between 0 and 9 [-Wformat-overflow=]
184 |  sprintf((char *) date_buf, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ",
|                                                                ^
In file included from /usr/include/stdio.h:867,
from duk_logging.c:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 25 and 85 bytes into a destination of size 32
36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
| …
```
> go.mod: update gopkg.in/olebedev/go-duktape to fix sprintf warnings

- core/rawdb/table.go
- core/rawdb/table_test.go
This PR fixes the issues in `TableDatabase`.
TableDatabase is a wrapper of underlying `ethdb.Database` with an additional prefix. 
The prefix is applied to all entries it maintains. However when we try to retrieve entries
from it we don't handle the key properly. In theory the prefix should be truncated and
only user key is returned. But we don't do it in some cases, e.g. the iterator  and batch
replayer created from it. So this PR is the fix to these issues.
> core/rawdb: fix table database

- eth/handler.go
- eth/sync.go
This PR fixes a regression introduced in v1.9.0 by the freezer, unfortunately that regression was completely silent and was surfaced only by b9c90c5581934454aa71af5b4b668c37b67d92fc.
The symptom is when a miner is started against an empty database, instantly mines a block, and then fast syncs... crashing. Since the node mined a block, it's current head block is 1, with `hashA`. Fast sync will start and dump a whole lot of data into the freezer/ancient database (including block 1, with `hashB`). Later on, any code that accesses the `currentBlock`, will want data belonging to `hashA`, but the freezer only has data belonging to `hashB`.
The crash is due to the sync code accessing the current block and then it's TD, which is returned as `nil`, since the hash doesn't match (the crash is due to …
> eth: when triggering a sync, check the head header TD, not block

- core/rawdb/freezer_table_test.go
Fixes: Condition is always 'false' because 'err' is always 'nil'
> core/rawdb: fix freezer table test error check

- internal/web3ext/web3ext.go
Fixes a tiny regression introduced by https://github.com/ethereum/go-ethereum/pull/20318, which caused the `clique` API calls in the console to not accept empty arguments (or `'latest`) any more (I mean, it accepted, but defaulted to block 0, instead of the chain head).
Fixes https://github.com/ethereum/go-ethereum/issues/20772
> internal/web3ext: fix clique console apis to work on missing arguments

- core/blockchain.go
> core: simplify atomic store after writeBlockWithState

- cmd/clef/main.go
- node/node.go
This PR fixes and issue where, if you specify `--rpcport=0`, you get
```
HTTP endpoint opened                     url=http://127.0.0.1:0 cors= vhosts=localhost
```
Port `0` means "hey OS, please give me a free port". We should output the actual
port given to us by the OS in this case.
With this PR:
```
INFO [03-20|10:11:00.749] IPC endpoint opened                      url=/tmp/geth.ipc
INFO [03-20|10:11:00.749] HTTP endpoint opened                     url=http://127.0.0.1:43157/ cors= vhosts=localhost
...
INFO [03-20|10:11:02.546] HTTP endpoint closed                     url=http://127.0.0.1:43157
INFO [03-20|10:11:02.546] IPC endpoint closed                      url=/tmp/geth.ipc
```
```
DEBUG[03-20|10:10:16.333] HTTP registered                          namespace=account
INFO …
```
> node, cmd/clef: report actual port used for http rpc

- eth/api_backend.go
- internal/ethapi/api.go
- les/api_backend.go
This fixes #16999 , but it may cause problem in other areas. Not sure what do do here...
> internal/ethapi: don't set sender-balance to maxuint, fixes #16999

- metrics/cpu_disabled.go
- metrics/cpu_enabled.go
Fix https://github.com/ethereum/go-ethereum/issues/20814.
It doesn't make much sense to do monitoring on mobile platforms. Instead of trying to fix `gosigar` to run on iOS, we can just disable CPU metrics on iOS altogether.
> metrics: disable CPU stats (gosigar) on iOS

- cmd/devp2p/dnscmd.go
This increases the TTL on tree root records to enable some caching.
It also decreases the TTL on the leaves to a saner value.
> cmd/devp2p: tweak DNS TTLs

- cmd/devp2p/dns_route53.go
- cmd/devp2p/dns_route53_test.go
Turns out the way RDATA limits work is documented after all,
I just didn't search right. The trick to make it work is to count UPSERTs
twice.
> cmd/devp2p: be very correct about route53 change splitting

- core/blockchain.go
- eth/backend.go
- eth/bloombits.go
- eth/handler.go
- eth/helper_test.go
- eth/protocol_test.go
- eth/sync.go
- eth/sync_test.go
Most goroutines started by eth.Ethereum didn't have any shutdown sync at
all, which lead to weird error messages when quitting the client.
This change improves the clean shutdown path by stopping all internal
components in dependency order and waiting for them to actually be
stopped before shutdown is considered done. In particular, we now stop
everything related to peers before stopping 'resident' parts such as
core.BlockChain.
Fixes #18495
> eth: improve shutdown synchronization

- les/peer.go
> les: fix dead lock

- core/tx_pool.go
As the title says. 
cc  @GuthL
> core: bump txpool tx max size to 128KB

- core/blockchain.go
- core/state/snapshot/account.go
- core/state/snapshot/conversion.go
- tests/block_test_util.go
This PR implements a snapshot vs trie reconciliation after running blockchain tests, to ensure that the state-according-to-snapshot is consistent with the state-according-to-trie.
> snapshotter/tests: verify snapdb post-state against trie

- cmd/clef/intapi_changelog.md
- cmd/clef/main.go
- signer/core/api.go
- signer/core/uiapi.go
This makes it possible to create accounts via CLI. Since we don't have any good UIs, what the heck
> cmd/clef: add newaccount command

- .travis.yml
If cocoapod build/deploy fails (which it always does now), the job is displayed as failing, but the whole build is considered passed, like [this build](https://travis-ci.org/github/adamschmideg/go-ethereum/builds/668380425)
> travis: allow cocoapods deploy to fail

- whisper/whisperv6/message_test.go
Got this failure on an unrelated PR: 
```
?   	github.com/ethereum/go-ethereum/whisper/shhclient	[no test files]
--- FAIL: TestWatchers (10.55s)
filter_test.go:627: failed Wrap with seed 1585143261: failed to reach the PoW target, specified pow time (1 seconds) was insufficient.
FAIL
```
So here's a random change that fixes it, but I guess @gballet will have to determine if it also perhaps negatively influences the actual test being performed... ? 
Before this PR:
```
=== RUN   TestWatchers
--- PASS: TestWatchers (5.29s)
```
all whisperv6 tests:
```
ok      github.com/ethereum/go-ethereum/whisper/whisperv6       14.140s
```
After this PR:
```
=== RUN   TestWatchers
--- PASS: TestWatchers (0.70s)
```
All:
```
ok      github.com/ethereum/go-ethereum/whisper/whisperv6       8.309s
```
> whisper/whisperv6: decrease pow requirement in tests

- metrics/timer_test.go
This test failed if the desired 50 milliseconds becomes either
1. below 35 ms, or
2. above 145 ms
Example:
```
--- FAIL: TestTimerFunc (0.15s)
timer_test.go:51: tm.Max(): 35e6 > 151151814 || 151151814 > 145e6
FAIL
```
The test failed due to what appers to be fluctuations in `time.Sleep`, which is
_not_ the actual method under test (native to golang)
This change modifies it so we compare the metered Max to the actual time instead
of the desired time.
I'm not 100% sure if this test is actually a test worth having, nor if my changes
screw with what we're trying to test here.
> metrics: make flawed test less flawed

- cmd/evm/runner.go
- Dump stats also for --bench flag.
- From memory stats only show number and size of allocations. This is what `test -bench` shows. I doubt others like number of GC runs are any useful, but can be added if requested.
- Now the mem stats are for single execution in case of --bench.
> cmd/evm: Rework execution stats

- accounts/abi/unpack.go
- accounts/abi/unpack_test.go
cleanup and using Bit() instead of Cmp() to compare numbers
> accounts/abi: faster unpacking of int256

- cmd/geth/genesis_test.go
This PR fixes the genesis tests that were flaky. 
The tests spat out 
```
test_cmd.go:250: (stderr) Fatal: Failed to write genesis block: genesis has no chain configuration
```
The first test should have failed ever since https://github.com/ethereum/go-ethereum/commit/37dd9086ec491900311fc39837f4a62ef5fd3a4a, three years ago. 
However,  _after_  a test unsuccessfully did a `geth init` (thus, not writing the genesis successfully) the test continued, and started geth, -- which then used the _default_ init-config: the mainnet. 
And the tests passed, because the query checked the genesis nonce. And the testcases were using the same nonce as mainnet does. Doh!
Tests are now changed to use other nonces. I also removed the first test, since we also have a _different_ test to ensure that we …
> cmd/geth: fix bad genesis test

- crypto/ecies/ecies.go
- crypto/ecies/ecies_test.go
- crypto/ecies/params.go
See commit message.
Also removed an errant println.
> crypto/ecies: improve concatKDF

- rpc/handler.go
- rpc/metrics.go
> rpc: add metrics for generic json rpc

- mobile/bind.go
It's better to reuse the existing code to create a keyed transactor
than to rewrite the logic again.
> mobile: remove duplicated code

- common/prque/lazyqueue_test.go
- console/console.go
- event/event_test.go
- miner/worker_test.go
- rpc/client_test.go
- rpc/subscription_test.go
In console/console.go,
Goroutine may leak because sending to `scheduler` is blocked in the child goroutine when other cases are selected when recv. Even if a `t.Error()` is called in other cases, it won't stop the leaking, because "[Calling FailNow does not stop those other goroutines.](https://golang.org/pkg/testing/#T.FailNow)".
Here, we cannot simply change the buffer size to 1 as the cases in [PR 20666](https://github.com/ethereum/go-ethereum/pull/20666) because the semantic may change. 
The fix is to add a stop chan, which notifies the child thread to return when the parent thread closes it on completion. 
Similar tricks are applied to channel `successes` in miner/worker_test.go, channel `loopErr` and `newBlock` in rpc/subscription_test.go, and channel `errc` in rpc/client_test.go. …
> all: fix a bunch of inconsequential goroutine leaks

- internal/ethapi/api.go
`CallArgs.ToMessage` is used to convert between `ethapi.CallArgs` and `types.Message`.
It reduces the length of the DoCall method by about half by abstracting out the conversion between the CallArgs and the Message. This should improve the code's maintainability and reusability.
The method is exported because I use it elsewhere but I can make it private upon request. I can also make any other changes necessary to get this merged because it will improve my QOL long-term.
Note: https://github.com/ethereum/go-ethereum/pull/20783 happened during my development but I believe I have merged its changes.
> internal/ethapi: CallArgs.ToMessage method

- core/vm/eips.go
- core/vm/instructions.go
- core/vm/instructions_test.go
- core/vm/interpreter.go
- core/vm/intpool.go
- core/vm/jump_table.go
- core/vm/runtime/runtime_test.go
This PR does two things: 
1. Remove the atomic check for aborting, and does it only every 100 steps, 
2. Refactors the way we pass params to opcode execution. 
Before this PR, every opcode takes `(pc *uint64, interpreter *EVMInterpreter, contract *Contract, memory *Memory, stack *Stack)`. When we implement EIP-2315, subroutines, it will be `(pc *uint64, interpreter *EVMInterpreter, contract *Contract, memory *Memory, stack *Stack, retStack *ReturnStack)`. And it starts getting silly, plus is an overhead in execution speed. 
This PR bundles `contract, memory, stack` into a struct, which represents a call context (i.e: whenever a call derivative is used, we get a new memory, new stack, and new contract ). Later on we can jam the returnstack in there aswell. 
I don't think it's ready for …
> core/vm: use a callcontext struct

- .github/ISSUE_TEMPLATE.md
The issue template referred to the obsolete gitter channel. Replace it with Discord.
> .github: change gitter reference to discord link in issue template

- cmd/devp2p/crawl.go
- cmd/devp2p/discv4cmd.go
- cmd/devp2p/discv5cmd.go
- cmd/devp2p/main.go
- p2p/discover/common.go
- p2p/discover/lookup.go
- p2p/discover/node.go
- p2p/discover/table.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_lookup_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v4_udp_test.go
- p2p/discover/v5_encoding.go
- p2p/discover/v5_encoding_test.go
- p2p/discover/v5_session.go
- p2p/discover/v5_udp.go
- p2p/discover/v5_udp_test.go
- p2p/enode/nodedb.go
- p2p/enode/nodedb_test.go
This adds an implementation of the current discovery v5 spec.
There is full integration with cmd/devp2p and enode.Iterator in this version. In theory we could enable the new protocol as a replacement of discovery v4 at any time. In practice, there will likely be a few more changes to the spec and implementation before this can happen.
> p2p/discover: add initial discovery v5 implementation

- accounts/scwallet/wallet.go
- build/checksums.txt
- build/ci.go
- cmd/puppeth/module_wallet.go
- core/tx_pool_test.go
- eth/downloader/downloader_test.go
- p2p/discv5/net.go
- whisper/mailserver/mailserver.go
This is required to make linting work with Go 1.14. The upgrade contains
a new version of the gosimple linter, which apparently has a new rule to
detect unnecessary uses of `fmt.Sprintf`. The new warnings are fixed in this
PR.
> build: upgrade to golangci-lint 1.24.0
