- docs/_clef/Rules.md
- docs/_clef/Tutorial.md
- docs/_clef/datatypes.md
Update the clef documentation to align with @karalabe 's updates
> docs: fix #19860, align clefdocs

- cmd/clef/tutorial.md
hat tip to @evertonfraga for spotting this
> Fix typo introduced in #19932

- cmd/geth/consolecmd.go
- cmd/geth/main.go
> cmd/geth: setup up cache and metrics when starting node

- tests/block_test.go
- tests/init.go
- tests/state_test.go
> tests: update from ethereum/tests

- cmd/clef/README.md
> Spelling correction

- accounts/usbwallet/ledger.go
- consensus/clique/clique.go
- core/genesis.go
- core/types/transaction_signing.go
- crypto/crypto.go
- crypto/signature_cgo.go
- crypto/signature_nocgo.go
- internal/ethapi/api.go
- miner/worker_test.go
- p2p/rlpx.go
- whisper/whisperv6/doc.go
> crypto: add SignatureLength constant and use it everywhere

- rpc/gzip.go
- rpc/http.go
This fixes both nitpicks from #19357 - building on top of the original PR
> rpc: enable compression on HTTP transport

- README.md
Change chainId in genesis block to 8888 from 0 per Moriteru in https://ethereum.stackexchange.com/a/28082/40230.
> Change chainId in genesis block to 8888 from 0

- docs/_install-and-build/Build-from-Source.md
- docs/_install-and-build/Installation-Instructions-for-Mac.md
- docs/_install-and-build/Installation-Instructions-for-Ubuntu.md
- docs/_install-and-build/Running-in-Docker.md
- docs/getting-started.md
- docs/getting-started/index.md
Here is my initial ideas for a getting started overhaul. I couldn't quite figure out your Jekyll setup to get this to render or appear in menus, might need some guidance on that.
I created a top level "getting started" guide that covers an introduction, common install options, basic terminology, and then some first commands.
Potential todos / next steps:
- Add an intro to why use Geth (might be covered elsewhere)
- Potentially add some more details in a few places
- Continue polishing the various links linked to from this page. Started some.
- Think about next steps for commands / using Geth, and add a link
- I have some style and terminology questions (i.e. what word to use for certain terms as there's inconsistency), but that can wait.
And of course any feedback you all may have.
> Initial Getting Started ideas

- README.md
Change wording per PR https://github.com/ethereum/go-ethereum/pull/20001 review comment.
>  Change ReadMe wording per PR review comment

- eth/backend.go
> eth/backend: remove unused field

- vendor/github.com/karalabe/usb/appveyor.yml
- vendor/github.com/karalabe/usb/hidapi/windows/hid.c
- vendor/vendor.json
Fixes https://github.com/ethereum/go-ethereum/issues/20073
> vendor: pull in USB Windows fixes

- log/README.md
Changed http:// to https:// on links in log/README.md
> Changed http:// to https:// on links in log/README.md

- dashboard/README.md
Changed http:// to https:// on links in dashboard/README.md
> dashboard: change links in README to https

- eth/downloader/downloader.go
Found a race: 
```
[user@work downloader]$ go test -run TestMultiProtoSynchronisation64Fast -v -race
=== RUN   TestMultiProtoSynchronisation64Fast
=== PAUSE TestMultiProtoSynchronisation64Fast
=== CONT  TestMultiProtoSynchronisation64Fast
Write at 0x00c0058350c8 by goroutine 59:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFastSyncContent()
/home/user/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1636 +0x94f
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func7()
/home/user/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:520 +0x4a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1() …
```
> eth/downloader: fix data race in downloader

- _config.yml
- _data/sidebar.yml
- docs/_getting-started/index.md
After Berlin docs restructure, this re-adds new getting started guide. Next steps in progress.
> [DOCS] Add Getting started guide

- docs/_install-and-build/Installing-Geth.md
Post Berlin docs changes, this PR reviews the install doc to fit to new Getting started guide and general review.
> [DOCS] Review Install doc

- cmd/devp2p/nodesetcmd.go
- core/forkid/forkid.go
Minor API polish that went out of sync due to multiple PRs touching the forkid.
> cmd/devp2p, core/forkid: make forkid.Filter API uniform

- appveyor.yml
Related: https://github.com/karalabe/usb/pull/12
> appveyor: bump to Go 1.13.4

- docs/_rpc/ns-les.md
This PR adds a description of the LES server and checkpoint API.
There was a minor modification in a call format since latest master:
https://github.com/ethereum/go-ethereum/pull/20304
> [DOCS] add les API description

- consensus/clique/api.go
Also unexport the status struct.
> consensus/clique: fix struct tags for status API

- tests/transaction_test_util.go
> tests: enable TransactionTests Istanbul case

- docs/_developers/devguide.md
This removes a bunch of outdated info from the developer guide and wraps
the text so it's easier to edit. The 'Contributing' section is now at
the top.
> [DOCS] Update Developer Guide

- cmd/geth/misccmd.go
> cmd/geth: remove network id from version cmd

- docs/_developers/dns-discovery-setup.md
This adds setup instructions for the DHT crawler and DNS node list publishing tools.
> [DOCS] add DNS discovery setup guide

- miner/stress_clique.go
- miner/stress_ethash.go
1.to build stress tests
Depends-On: 6269e5574c024bb82617b33f673550231b3a3b37
> miner: add dependencies for stress tests

- core/genesis.go
> core: removed old invalid comment

- .travis.yml
- _includes/head.html
Add Matomo tracking as used on blog.ethereum.org
> [DOCS] add Matomo analytics

- .travis.yml
> .travis.yml: use latest macOS 10.14 image

- eth/backend.go
Reverts ethereum/go-ethereum#20476
> Revert "eth: refactor creation of EthAPIBackend"

- build/ci.go
- build/deb/ethereum/deb.rules
Will this change fix the Launchpad PPA build? Let's find out!
> build: put GOPATH in /tmp on launchpad

- p2p/server.go
Resubmit of #20559
Fixes #20558
> p2p: wait for listener goroutines on shutdown

- docs/_interface/Managing-your-accounts.md
If you use `NewAccount` console says there is no such function
> [DOCS] Use correct account creation function

- cmd/geth/retesteth.go
to better check the generated blockchain tests, use block retrival by hash.
> retesteth add eth_getBlockByHash() 

- rpc/endpoints.go
This removes the error added in #20597 in favor of a log message at
error level. Failing to start broke a bunch of people's setups and is
probably not the right thing to do for this check.
> rpc: remove startup error for invalid modules, log it instead

- cmd/clef/tutorial.md
> Correct Clef typo

- rpc/http.go
minor corrections to a typo and re-worded a comment for consistent grammar
( this is a test PR for @fjl and @gballet )
>  rpc: correct typo and reword comment for consistency

- tests/difficulty_test.go
Includes difficulty tests for EIP2384 aka MuirGlacier.
> tests: update tests/testdata@develop, include EIP2384 config

- cmd/checkpoint-admin/README.md
> cmd/checkpoint-admin: add doc

- eth/handler_test.go
- les/peer_test.go
> les: fix flaky test

- trie/database.go
This is an alternative fix to the root issue of #20920. The trie database reuses an internal buffer, which can result in corrupt data when RPC endpoints request data simultaneously as other operations query the same preimage data.
> trie: fix concurrent usage of secKeyBuf, ref #20920

- core/headerchain.go
the issue #20930
core: the conditions of reorg are different between writeBlockWithState and WriteHeader
> core: fix the condition of reorg

- go.mod
- go.sum
1. nil pointer fix in Get() method
2. go.mod added
3. double declare fix in ContainsOrAdd()
4. add some useful methods
> go.mod: upgrade to golang-lru v0.5.4

- trie/proof_test.go
Fixes failure likes this https://travis-ci.org/github/ethereum/go-ethereum/jobs/683332663
> trie: fix TestBadRangeProof unit test

- core/state/dump.go
This PR includes the cherry-picked commit from https://github.com/ethereum/go-ethereum/issues/20981, with formatting on top.
> core/state: include zero-address in state dump if present

- build/nsis.install.nsh
> build: Fix CLI params for windows LNK files

- docs/_getting-started/dev-mode.md
Update dev mode tutorial to give more realistic getting started steps, in this case, connecting to another application.
Closes https://github.com/ethereum/go-ethereum/issues/20397
> [DOCS] Update dev mode tutorial

- core/rawdb/chain_iterator.go
```
INFO [05-12|16:19:19.073] Unindexing transactions                  blocks=txs LOG15_ERROR= total=1563886 elapsed=9.000s
```
> core/rawdb : log format fix for Unindexing transaction

- consensus/ethash/sealer_test.go
Rel https://github.com/ethereum/go-ethereum/pull/17526
`TestRemoteMultiNotify` was a flaky test. Sometimes it passed, sometimes not. See below for reproduction.
```sh
> go test -run '^TestRemoteMultiNotify$' -count 1 ./consensus/ethash
ok      github.com/ethereum/go-ethereum/consensus/ethash        0.171s
> go test -run '^TestRemoteMultiNotify$' -count 100 ./consensus/ethash
panic: Log in goroutine after TestRemoteMultiNotify has completed
goroutine 460 [running]:
testing.(*common).logDepth(0xc00010a300, 0xc0001e8000, 0x69, 0x3)
/home/ia/go1.13.5.linux-amd64/go/src/testing/testing.go:678 +0x406
testing.(*common).log(...)
/home/ia/go1.13.5.linux-amd64/go/src/testing/testing.go:658
testing.(*common).Logf(0xc00010a300, 0x98c0d1, 0x2, 0xc000704de0, 0x1, 0x1) …
```
> consensus/ethash: fix flaky test by reading seal results

- core/forkid/forkid.go
> core: fix typo in comments

- internal/web3ext/web3ext.go
fix a regression introduced in PR #19645
> internal/web3ext: add missing params to the debug_accountRange

- eth/downloader/peer.go
> fix peer Unregister peerSet unlock

- eth/handler.go
- eth/peer.go
> eth: don't block if transaction broadcast loop is returned

- eth/api_tracer.go
fixes https://github.com/ethereum/go-ethereum/issues/21082
> eth: returned revert reason in traceTx

- go.mod
- go.sum
The final PR that contains the necessary fix to build on DragonflyBSD
> go.mod: bump gopsutil version

- accounts/external/backend.go
- signer/core/types.go
> accounts/external: remove dependency on internal/ethapi

- .github/CODEOWNERS
This PR removes legacy code owners and adds new ones.
> .github: Change Code Owners

- ethstats/ethstats.go
Fixes https://github.com/ethereum/go-ethereum/issues/21345 (we didn't reconnect on failure).
The PR also fixes the underlying issue on Goerli stats reporting, where the upstream JavaScript stats server started sending system heartbeat packets that we choked on. The PR listens and handles the system pings from now on.
> ethstats: fix reconnection issue, implement primus pings

- go.mod
- go.sum
This PR updates `uint256` to `v1.1.1`
> deps: update uint256 to v1.1.1

- params/config.go
This PR upgrades the CHTs to latest value.
> params: upgrade CHTs

- accounts/abi/bind/backends/simulated.go
- accounts/abi/bind/backends/simulated_test.go
cleaned doc errors, camel case refactors and anonymous parameter assignments
> accounts/abi/bid/backends:

- .github/CODEOWNERS
left out of the whisper removal PR
> .github: remove whisper from CODEOWNERS

- docs/_rpc/server.md
closes https://github.com/ethereum/go-ethereum/issues/21519
> [DOCS] Update http server docs with new flags

- light/odr.go
Current description is from `TrieRequest`.
> light: fix wrong description of ChtRequest

- p2p/enode/node.go
> p2p/enode: remove unused code

- node/rpcstack.go
- node/rpcstack_test.go
> node: fix websocket connection header check

- trie/stacktrie.go
- trie/trie_test.go
This PR polishes the commit function of stacktrie a bit.
> trie: polish commit function

- eth/handler.go
- p2p/peer.go
- p2p/server.go
Alternative to https://github.com/ethereum/go-ethereum/pull/21689
> eth, p2p: use truncated names 

- docs/_interface/JavaScript-Console.md
> pages: update doc not to refer to Otto

- docs/_rpc/server.md
> pages: fix typo in rpc example

- core/blockchain_insert.go
Fixed the elapsed time calculation of the periodic report function.
> core: fix blockchain insert report time interval calculation

- core/state/statedb.go
> core/state: maintain one more diff layer

- common/bitutil/compress_fuzz.go
- tests/fuzzers/keystore/keystore-fuzzer.go
- tests/fuzzers/rlp/rlp_fuzzer.go
- tests/fuzzers/stacktrie/trie_fuzzer.go
- tests/fuzzers/txfetcher/txfetcher_fuzzer.go
Work in progress to improve the fuzzers a bit
- Correct returnvalues, 
- Fix false positive in stacktrie
- remove unwanted logs in tx_fetcher
> tests/fuzzers: improve the fuzzers

- metrics/cpu_enabled.go
> metrics: fix the panic for reading empty cpu stats

- cmd/clef/main.go
- cmd/utils/flags.go
- console/bridge.go
- core/headerchain.go
- crypto/bls12381/g1.go
- crypto/bls12381/g2.go
- les/benchmark.go
- les/lespay/server/balance.go
- les/lespay/server/balance_tracker.go
- les/lespay/server/prioritypool.go
- les/odr_requests.go
- les/serverpool.go
- les/serverpool_test.go
- p2p/nat/nat.go
- p2p/nodestate/nodestate_test.go
- p2p/simulations/network.go
- rlp/encode_test.go
- rpc/client.go
- trie/committer.go
**Changes:**
* Simplify nested complexity
* If an `if` blocks ends with a `return` statement then remove the `else` nesting.
Most of the changes has also been reported in `golint` https://goreportcard.com/report/github.com/ethereum/go-ethereum#golint
> simplify nested complexity and if blocks ending with a return statement

- _layouts/default.html
- static/styles/custom/default.css
closes https://github.com/ethereum/go-ethereum/issues/19949
> docs: reenabled syntax highlighting

- docs/_rpc/ns-debug.md
I was using these notes for information on how to use the JS tracer and noticed a few things were out-of-date. This PR should bring the docs on-par with the code in master.
> docs: update traceTransaction docs

- index.html
fixes some broken links on the website
> docs: fixed links

- README.md
> README.md: Replace wiki links with new doc pages

- .github/CONTRIBUTING.md
> .github: Replace wiki links with new doc pages

- node/node.go
Small nitpick - this PR renames the `startNetworking` method to `openEndpoints` for less confusion as startNetworking doesn't imply that RPC http/ws/gql endpoints also get started in this process.
I could also rename it to `startEndpoints` or something that works better.
> node: rename `startNetworking` to `openEndpoints`

- docs/_interface/metrics.md
closes https://github.com/ethereum/go-ethereum/issues/21524
> docs: add metric page

- crypto/bls12381/arithmetic_fallback.go
- crypto/signify/signify_fuzz.go
fixes some ineffectual assignments, lints the signify fuzzer
> crypto: fix ineffectual assignments

- common/prque/prque_test.go
- common/prque/sstack_test.go
For some reason the tests and benchmarks were not pulled in for the priority queue package when we vendored it. Pull those too so chances are tested properly.
> common/prque: pull in tests and benchmarks from upstream

- docs/_interface/peer-to-peer.md
closes https://github.com/ethereum/go-ethereum/issues/16646
> docs: explain trusted nodes

- internal/flags/helpers.go
On a side node: wondering if we really need the copyright 2 times in there
> cmd, geth: CLI help fixes

- _config.yml
- _layouts/redirect.html
- docs/_dapp/mobile-accounts.md
- docs/_dapp/native-accounts.md
- docs/_getting-started/dev-mode.md
- docs/_getting-started/private-net.md
- docs/_install-and-build/Installing-Geth.md
- docs/_interface/FAQ.md
- docs/_interface/mining.md
- docs/_interface/peer-to-peer.md
- docs/_legacy/Contract-Tutorial.md
- docs/_rpc/ns-admin.md
- docs/_rpc/ns-debug.md
- index.html
- redirects/dev-mode.md
- redirects/private-net.md
Fix things that where reported via:
https://validator.w3.org/checklink?uri=http%3A%2F%2Fgeth.ethereum.org%2Fdocs%2F&hide_type=all&recursive=on&depth=10&check=Check
> docs: fix some broken links

- core/blockchain.go
> core: aiming genesis when middle block is missing

- accounts/scwallet/README.md
Things have changed a bit since the replacement of otto with goja. This PR updates the documentation,
> accounts/scwallet: update documentation

- internal/ethapi/api.go
Would've pushed this on a more relevant branch but didn't find one
> internal/ethapi: comment nitpick

- cmd/utils/flags.go
> cmd/utils: fix txlookuplimit exclusive check for archive node

- cmd/devp2p/internal/ethtest/types.go
This PR makes it a bit easier to debug hive failures
> cmd/devp2p: better testcase failure output for ethtests

- go.mod
- go.sum
https://github.com/syndtr/goleveldb/pull/351
> go.mod: upgrade goleveldb to commit 64b5b1c

- go.mod
- go.sum
https://github.com/huin/goupnp/commit/0ca763054c8882de233e45d2f61d8be91f86e536
> go.mod: upgrade goupnp to commit 0ca76305

- docs/_dapp/native-bindings.md
closes https://github.com/ethereum/go-ethereum/issues/22489
> docs: remove mention of godep

- cmd/geth/chaincmd.go
> cmd/geth: check block range against chain head in export cmd

- eth/ethconfig/config.go
closes https://github.com/ethereum/go-ethereum/issues/22556
> eth: dump rpc gas cap and tx fee cap

- docs/_vulnerabilities/vulnerabilities.json
- docs/_vulnerabilities/vulnerabilities.json.minisig
Enough time has passed, it's time to disclose these
> Security disclosures

- go.mod
- go.sum
> go.mod: upgrade gopsutils to fix OpenBSD/arm64 build

- README.md
> README.md: update commands table, add note about web3.js version

- go.mod
- go.sum
This updates go.mod for the addition of golang.org/x/sync.
> go.mod: go mod tidy

- build/ci.go
This fixes a regression introduced in #22804
> build: fix iOS framework build

- docs/_interface/Command-Line-Options.md
https://geth.ethereum.org/docs/interface/command-line-options is currently out of date
>  gh-pages: match geth --help in v1.10.3

- core/blockchain_test.go
- core/state_processor_test.go
This PR fixes two errors that regressed when 1559 was merged.
> core: fix failing tests

- les/client_handler.go
- les/fetcher.go
- les/odr.go
- les/retrieve.go
- les/txrelay.go
This is a nobrainer PR, just wanted to get it out of the way for the reverse downloader.
> les: generate random nums directly, not via strange conversions

- ethstats/ethstats.go
Trivial but helpful to understanding.
> ethstats: fix typo in comment

- cmd/devp2p/internal/ethtest/suite.go
Fixes this failure: https://travis-ci.com/github/ethereum/go-ethereum/jobs/508659817#L470
> cmd/devp2p/internal/ethtest: ignore block announcement in tx test

- eth/ethconfig/config.go
> eth/ethconfig: flip the default from fast to snap sync

- go.mod
- go.sum
https://github.com/VictoriaMetrics/fastcache/commit/3fbe8ccb42ecf703ea89800235ab7bbe3d0cb345
> go.mod: upgrade to fastcache v1.6.0

- core/gen_genesis.go
- core/genesis.go
Follow up to https://github.com/ethereum/go-ethereum/pull/23013
See also https://github.com/ethereum/tests/pull/881
> core: change baseFee into baseFeePerGas in genesis json

- docs/_getting-started/index.md
I spent some time getting it wrong and writing notes about it so other people will get it right the first time.
> Usability updates

- cmd/geth/les_test.go
Previously the test waited a second and then would fail if geth had not
started. This caused the test to fail intermittently. This change checks
for geth 10 times over a 5 second period and then fails if geth is still
not available.
> cmd/geth: Make les test probe for geth instance

- eth/gasprice/gasprice.go
> eth/gasprice: fix typo in comment

- docs/_dapp/mobile-accounts.md
- docs/_dapp/mobile.md
- docs/_dapp/native-accounts.md
- docs/_dapp/native-bindings.md
- docs/_dapp/native.md
- docs/_dapp/tracing-filtered
- docs/_dapp/tracing-filtered.md
- docs/_dapp/tracing.md
The JavaScript tracing tutorial and a TOC order for the _dapp page.
> Tracing tutorial

- les/servingqueue.go
I have no idea how the servingqueue works, but it seems we have a shutdown hang, seen on our goerli clique sealer node. I took a stack dump as it was shutting down, and it seems to be stuck on waiting for that token channel:
```
goroutine 181 [chan receive, 107 minutes]:
github.com/ethereum/go-ethereum/les.(*servingQueue).threadController(0xc020698240)
github.com/ethereum/go-ethereum/les/servingqueue.go:174 +0x13c
created by github.com/ethereum/go-ethereum/les.(*servingQueue).threadCountLoop
github.com/ethereum/go-ethereum/les/servingqueue.go:341 +0x71
goroutine 970536 [semacquire]:
sync.runtime_Semacquire(0xc0206982a8)
runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0206982a0)
sync/waitgroup.go:130 +0x65
github.com/ethereum/go-ethereum/les.(*servingQueue).stop(...) …
```
> les: avoid shutdown hang

- docs/_interface/peer-to-peer.md
Documents what was raised in #23112
I'm not sure if this page is the best place to add this section, but didn't find a better alternative
> docs: add section about config file

- docs/_rpc/ns-clique.md
> Typo in ns-clique.md

- core/headerchain.go
> core: fix flaw in setHead

- docs/_rpc/ns-miner.md
Format copied from miner_setGasPrice
> Add miner_setGasLimit

- internal/web3ext/web3ext.go
This PR removes some unused console APIs, specifically the APIs of swarm and whisper.
> internal/web3ext: remove unused console APIs

- docs/_getting-started/private-net.md
Removes link to Private Network page that is on the Private Network page
TL;DR link on page links to itself
> Fix broken link

- README.md
is now snap and not fast anymore
> Fix default sync mode in README

- cmd/clef/main.go
- node/rpcstack.go
> node, cmd/clef: remove term "whitelist"

- core/state/trie_prefetcher_test.go
Adds unit tests for the prefetcher, tests basic functionality
> core/state: add trie prefetcher tests

- docs/_rpc/ns-debug.md
This PR fixes the description of `debug_traceCall` RPC.
> docs: fix debug_traceCall description

- signer/core/apitypes/types.go
> signer/core/apitypes: remove dependency on internal/ethapi

- cmd/devp2p/internal/ethtest/suite_test.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/peer.go
- eth/handler.go
- eth/handler_eth_test.go
- eth/protocols/eth/handler.go
- eth/protocols/eth/handler_test.go
- eth/protocols/eth/handlers.go
- eth/protocols/eth/handshake_test.go
- eth/protocols/eth/peer.go
- eth/protocols/eth/protocol.go
- eth/sync.go
- eth/sync_test.go
- les/client_handler.go
> Revert "Revert "eth: drop eth/65, the last non-reqid protocol version""

- les/client_handler.go
- les/fetcher.go
- les/fetcher_test.go
- les/odr_test.go
- les/server_handler.go
- les/sync_test.go
- les/test_helper.go
- les/ulc_test.go
This PR fixes all the data race in les tests.
> les: fix data race issues in les package

- docs/postmortems/2021-08-22-split-postmortem.md
This adds the as-yet draft post mortem to our repo
> docs: add post-mortem

- README.md
Updated example genesis.json configuration section, added londonBlock within config.
> Added londonBlock to example genesis cfg

- docs/_interface/mining.md
-  this helps to align and address the 90% question often asked around the internet and our Discord and why we wrote more helpful detail in our FAQ about syncing.
> [DOCS] add text about eth.syncing status check in mining tutorial

- docs/_rpc/pubsub.md
reogranization updated to reorganization on pub/sub md
> Update pub/sub for wrong word

- docs/_interface/mining.md
> eth.syncing update

- p2p/discover/v4wire/v4wire.go
> p2p: fix typo in v4wire.go

- eth/gasprice/gasprice.go
> eth/gasprice: sanitize max header and block history

- eth/api.go
> eth: fix typo in comment

- cmd/geth/dbcmd.go
> cmd/geth/dbcmd: add ancient flag

- core/vm/instructions_test.go
- core/vm/stack.go
This function is only used for testing.
> core/vm: Remove Stack.pushN

- README.md
closes https://github.com/ethereum/go-ethereum/issues/24088
> README: remove mentions of snap sync

- trie/sync.go
mispelled words in comments: th enext
> spelling mistake

- accounts/accounts.go
Change two instances of the word `calulcated` to `calculated`.
> Fix Comment

- accounts/accounts.go
Corrected Some Mistakes in Spelling in comments.
> corrected spelling mistakes

- go.mod
- go.sum
including timeout customized added
https://github.com/jackpal/go-nat-pmp/commit/5d7eea0e53b70d7c2d7320ccf7aa275ec318be71
> go.mod : go-nat-pmp v1.0.2

- go.mod
- go.sum
https://github.com/deckarep/golang-set/compare/v1.7.1...v1.8.0
> go.mod : golang-set-v1.8.0, go.mod added & cardinality check for subset

- cmd/utils/flags.go
Fixes https://github.com/ethereum/go-ethereum/issues/24279
> cmd/utils: fix regression placing dev mode datadir readonly

- core/rawdb/accessors_state.go
This PR fixes an issue on master, which broke the pipeline
> core/rawdb: fix typo

- _layouts/default.html
Updates copyright year to 2022.
> [DOCS]: Update copyright year

- docs/_rpc/batch.md
We can possibly add a compression section to this page too
> docs: add page on batch requests

- build/ci.go
Also specify EOL dates of all listed releases.
> build: add Ubuntu 21.10 PPA target

- crypto/bls12381/swu.go
implmentation -> implementation
> Fix typo in swu.go

- eth/protocols/snap/sync.go
Fixes https://github.com/ethereum/go-ethereum/issues/24500
> eth/protocols/snap: avoid estimating infinite percentage

- build/ci.go
- internal/build/download.go
on windows it is a zip not a tarball
afterwards it works on windows:
> build: fix linter install on windows

- eth/catalyst/api.go
fix the error message which was extremely confusing
> eth/catalyst: fix log message

- docs/_interface/peer-to-peer.md
> [DOCS] Fix geth --genesis flag error

- core/types/block.go
- core/types/gen_header_json.go
"miner" is not set for pending block responses in some cases.
Fixes #24632
> core/types: make "miner" optional in Header JSON

- docs/_getting-started/index.md
> getting-started: fix typo

- docs/_rpc/pubsub.md
See https://github.com/ethereum/go-ethereum/issues/24699#issuecomment-1103622858
> doc: clarify what newHeads emits

- eth/filters/api.go
Minor PR to remove mux and quit fields which seem unused.
> eth/filters: remove unused struct fields

- accounts/errors.go
- accounts/hd.go
> accounts: fix typo in comments

- docs/_interface/FAQ.md
Some minor spelling and grammar changes.
> docs: FAQ fixes and some info about snap sync

- docs/_getting-started/index.md
Changed 'accoutns' to 'accounts'
> docs: fixed typo

- docs/_getting-started/index.md
Corrected a few typos while reading the documentation.
> docs: Fixed typos

- docs/_vulnerabilities/vulnerabilities.json
- docs/_vulnerabilities/vulnerabilities.json.minisig
Updates the vulnerabilities.json and the signature
> docs: update vulnerability info

- docs/_rpc/ns-debug.md
See https://github.com/ethereum/go-ethereum/issues/24808
> docs: add some undocumented debug methods

- core/tx_pool.go
reverse the order of address in queue (specific disscussion in #24907)
> core: fix the order of address in queue 

- docs/_dapp/tracing.md
> fix typo: Update tracing.md

- docs/_interface/Private-Network.md
fix typo in private-network.md
> docs: fix typo in private-network.md

- docs/_rpc/ns-debug.md
This method was added in https://github.com/ethereum/go-ethereum/pull/24773.
> debug: add getRawReceipts

- params/config.go
No LES server for Ropsten, no own server either to pull the data from.
> params: update CHTs for Geth 1.10.18

- docs/_interface/merge.md
adds some details and tidies up the merge page, as requested by @s1na.
> add info to merge page

- node/rpcstack_test.go
Might fix https://ci.appveyor.com/project/ethereum/go-ethereum/builds/43736113/job/2x08lmn1px7nx9l8#L969 . The problem is that since the ci machines are pretty crappy, we create the testcases with offset +6 seconds, and expect that to be out of the time-window in the future. 
But it takes a while to get to that testcase, and at that point it's no longer in the future. So this PR restructures it a bit so we create the testcases nearer to when they get run, as opposed to creating them before we even spin up the server.
> node: make jwt test less dependent on time

- go.mod
- go.sum
> go.mod: clean up

- eth/tracers/js/internal/tracers/4byte_tracer_legacy.js
> eth/tracers: fix typo in 4byte_tracer_legacy.js

- params/config.go
> params: update ropsten terminal total difficulty block

- accounts/url_test.go
accounts/url: add test logic what check null string to parseURL() #25011 
It's recreated PR from #25013.
Sorry for the trouble.
> accounts: increase parseURL test coverage

- docs/_interface/merge.md
See announcement: https://blog.ethereum.org/2022/06/03/ropsten-merge-ttd/
> merge: fix ropsten ttd

- docs/_interface/JavaScript-Console.md
> JavaScript-Console.md: Web3.jc -> Web3.js & missing full stop

- cmd/faucet/faucet.go
> cmd/faucet: more verbose message about private posts

- core/tx_pool.go
> core: fix typo in txpool

- core/rawdb/database.go
> core: fix a typo in the comment

- common/prque/lazyqueue.go
> common/prque: fix typo

- docs/_dapp/native-accounts.md
mostly relatively light changes to the account management page, bringing it into line with the rest of the dapp developer docs.
> docs: update go account management page

- trie/hasher.go
> Fix parallel typo in trie/hasher.go

- core/state/state_object.go
- eth/tracers/logger/logger.go
The PR for reduce the map resizing.
> core, eth: pre-allocate in Copy()

- params/bootnodes.go
Somehow we forgot setting this
> params: enable DNS discovery on Sepolia too

- docs/_rpc/ns-admin.md
- docs/_rpc/ns-clique.md
- docs/_rpc/ns-debug.md
- docs/_rpc/ns-miner.md
- docs/_rpc/ns-net.md
- docs/_rpc/ns-personal.md
- docs/_rpc/ns-txpool.md
Based on this list: https://github.com/ethereum/go-ethereum/pull/25134#issuecomment-1161816961
> doc: add missing API methods

- accounts/abi/selector_parser.go
> accounts/abi: fix typo in comment

- p2p/netutil/error_test.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
> delete minor unreachable code caused by t.Fatal

- params/config.go
> params: change Merge config to print simpler message

- docs/_rpc/ns-personal.md
Removes unmatched closing parenthesis
> Fix Typo: ))) -> ))

- cmd/puppeth/module.go
- cmd/puppeth/module_explorer.go
- cmd/puppeth/module_faucet.go
- cmd/puppeth/module_node.go
Signed-off-by: Delweng <delweng@gmail.com>
> cm/puppeth: fix the issue of ethstats maybe doesn't contains `:`

- common/compiler/solidity.go
> common/compiler:add json.Unmarshal err check

- graphql/graphql.go
- graphql/service.go
This creates some infrastructure to share resources between graphql API objects.
> graphql: embed *Resolver instead of backend interface

- node/config_test.go
Signed-off-by: Delweng <delweng@gmail.com>
> node/config: rm not used path.Join

- docs/_clef/apis.md
minor changes, mostly just making the layout consistent and updating links.
> docs: clef/apis 

- docs/_clef/CliqueSigning.md
Refining page ready for inclusion on new website. Mirroring content changes here too.
Mostly stylistic and layout changes.
> docs: tidy up Clef Clique signing page

- README.md
docs: specify execution client
> docs: specify execution client

- eth/catalyst/api.go
Would crash all nodes post merge, can I get a 1m bounty now?
Thanks to Mario for catching it on hive
> eth/catalyst: prevent division by zero

- trie/proof.go
- trie/secure_trie.go
- trie/stacktrie.go
- trie/trie.go
We get a lot of reports of "Unhandled trie error", which can be output from several different places. This PR makes it so we can determine which location causes the problem(s).
> trie: better error reporting

- eth/tracers/js/goja.go
> eth/tracers/js: fill in refund field

- docs/_interface/Private-Network.md
fix unlock account desc in Private-Network desc
update .gitignore
> fix unlock account desc in Private-Network desc

- eth/tracers/api_test.go
This PR fixes a broken test in codebase.
> eth/tracer: fix broken test

- accounts/abi/unpack.go
> accounts/abi: fix typo in error message

- graphql/graphql.go
- graphql/graphql_test.go
- graphql/service.go
Fixes #25583 (for a second time, hopefully last time 😄)
> graphql: fixes missing tx logs

- eth/handler.go
This PR should fix a *very* rare data race where a peer responds to a CHT challenge, but the node shutting down exactly at the wrong moment removes the handler whilst the response is waiting in queue. That case would prevent the node from finishing the shutdown.
This PR fixes https://github.com/ethereum/go-ethereum/issues/25775 and is an alternative to https://github.com/ethereum/go-ethereum/pull/25793, which wilst would fix the symptom, does not address the root cause.
> eth: fix a rare datarace on CHT challenge reply / shutdown

- docs/_interface/consensus-clients.md
- docs/_interface/merge.md
Updates because merge is now in the past!
> docs: update merge pages now merge is done

- docs/_interface/hardware.md
add new page for hardware requirements
also intended to be included on new site
> docs: add hardware requirements page

- docs/_interface/sync-modes.md
Breaking out info on sync modes into dedicated page. 
Also intend for this to be page on new site.
> docs: add page on sync modes

- accounts/abi/bind/backends/simulated.go
- accounts/abi/bind/backends/simulated_test.go
> accounts/abi/bind/backends: fix AdjustTime to respect Fork

- docs/_interface/consensus-clients.md
> [doc] typo oeprators -> operator

- docs/_interface/mining.md
updates mining page to bring it up to date post-merge.
> docs: update mining page for post-merge

- common/math/modexp.go
- core/vm/contracts.go
- oss-fuzz.sh
- tests/fuzzers/modexp/modexp-fuzzer.go
Some optimizations for modexp special cases
> common/math: optimized modexp (+ fuzzer)

- eth/filters/api.go
- eth/filters/filter_system.go
- eth/filters/filter_system_test.go
- ethclient/gethclient/gethclient.go
- ethclient/gethclient/gethclient_test.go
> eth/filters, ethclient/gethclient: add fullTx option to pending tx filter

- docs/_install-and-build/Installing-Geth.md
> docs, Fix typo in Installing-Geth.md

- rpc/websocket.go
This is to cater for more node providers
> rpc: decrease websocket ping interval

- internal/web3ext/web3ext.go
Ooops, the saga continues. Fixes regression in #26266.
> internal/web3ext: fix eth_call in console 2

- docs/_interface/JavaScript-Console.md
argument does to follow  `TransactionConfig` interface.
> correct typo in JavasScript-Console gh-page.

- docs/_evm-tracing/builtin-tracers.md
- docs/_evm-tracing/custom-tracer.md
- docs/_evm-tracing/js-tutorial.md
- docs/_rpc/ns-debug.md
Small update to the tracing docs:
- Updated methods to include tracerConfig
- Moved JS tracing tutorial to own page
- Moved JS tracing reference from the API page to custom tracers page
> docs: update tracing docs

- build/ci.go
Adds support for Kinetic in Launchpad
> build: add support for Ubuntu 22.10 (Kinetic Kudu)

- cmd/geth/main.go
- internal/flags/helpers.go
> Update copyright year to 2023

- cmd/devp2p/internal/v4test/discv4tests.go
This PR adds a pong validation on the `bond` function
> cmd/devp2p/internal/v4test: add pong validation in bond

- cmd/evm/README.md
- cmd/evm/transition-test.sh
This PR contains the remaining changes suggested in #26111, but integrated via the generator-script.
> cmd/evm: update documentation

- README.md
PR to add a couple of suggested improvements for the **Adding a new documentation page** section
> [website] docs: README improvements

- tests/state_test_util.go
Replaces #26456 which was erroneously made off my fork master branch
> tests: fix DIFFICULTY error in state executor

- eth/catalyst/tester.go
Fix the fullsync tester in case the provided target is a pre-merge block.
> eth/catalyst: trigger beacon sync directly with provided chain head

- docs/developers/geth-developer/contributing.md
> [website] fix typo

- core/beacon/types.go
- eth/catalyst/api.go
- eth/catalyst/api_test.go
Spec: ~~https://github.com/ethereum/execution-apis/pull/146/files~~ https://github.com/ethereum/execution-apis/pull/218/files
Will undraft + add tests once the spec is merged
> eth/catalyst: implement engine_getPayloadBodies* methods

- README.md
readme: Ethereum is Proof-of-Stake now
> README: remove text about GPU mining

- src/constants.ts
Updates constant for new repo path
> [website] Update LAST_COMMIT_BASE_URL

- light/txpool_test.go
https://github.com/golang/go/wiki/CodeReviewComments#receiver-names
> light: fix receiver name from Python style to Go

- ethdb/pebble/pebble.go
Currently the callbacks are against a `nil` database instance, causing a panic.
Initialize the `db` before referencing it's methods.
> ethdb/pebble: fix nil callbacks

- docs/interacting-with-geth/rpc/ns-debug.md
fixes missing ns_debug method described here #26366
> [website]: fix missing method in ns_debug

- docs/developers/geth-developer/disclosures.md
https://geth.ethereum.org/public/docs/vulnerabilities/vulnerabilities.json => https://geth.ethereum.org/docs/vulnerabilities/vulnerabilities.json
https://geth.ethereum.org/public/docs/vulnerabilities/vulnerabilities.json.minisig => https://geth.ethereum.org/docs/vulnerabilities/vulnerabilities.json.minisig
> [website]: Fix 404 links

- docs/fundamentals/databases.md
- docs/getting-started/installing-geth.md
- docs/interacting-with-geth/rpc/ns-debug.md
- docs/tools/puppeth.md
- src/components/UI/docs/MDComponents.tsx
- src/utils/childrenIsAnImage.ts
- src/utils/index.ts
This PR makes images clickable and open full size version on new tab.
**Preview:** https://deploy-preview-26680--geth-website.netlify.app/docs/developers/dapp-developer/dev-mode#compile-and-deploy
Fixes #26478
> feat: expand doc images on click 

- eth/filters/filter_system.go
Succeeds https://github.com/ethereum/go-ethereum/pull/26686 and alternative to https://github.com/ethereum/go-ethereum/pull/26688
> eth/filters: replace atomic pointer with value

- docs/fundamentals/config-files.md
- src/data/documentation-links.yaml
Adds page explaining how to start Geth with a) shell scripts and b) a config file
Also renames the page "Peer-to-peer" to "Connecting to Peers"
> [website]: add page on config files

- docs/fundamentals/databases.md
adds short section on using pebble backend
> [website]: add note on pebble to databases page

- ethclient/ethclient.go
This fixes a regression introduced by #26723.
Fixes #26816.
> ethclient: fix panic when requesting missing blocks

- netlify.toml
- redirects.js
Adds redirects.json file for Netlify
Fixes: https://github.com/ethereum/go-ethereum/issues/26538
> [Fix] [website] redirects not working

- eth/catalyst/api.go
I found this warn when browsing the logs of my Ethereum full node (execution: geth 1.11.4, consensus: prysm 3.2.2)
I reviewed the code of the corresponding version of prysm, it will no longer exchange transition configuration when PoS transition is complete.（https://github.com/prysmaticlabs/prysm/blob/v3.2.2/beacon-chain/execution/check_transition_config.go#L96）
Therefore, in the current situation, the value of the variable lastTransitionUpdate in geth can only change once at most and will not change.
> eth/catalyst: improve consensus heartbeat

- go.mod
- go.sum
Ensure arm64 frame sizes are 8 (mod 16)
https://github.com/golang/snappy/commit/fa5810519dcbfaa60974183cbe11c6c0d050a23d
> go.mod : snappy deps update

- tests/fuzzers/rlp/rlp_fuzzer.go
> test/fuzzers: fuzz rlp handling of big.Int and uint256.Int

- les/client_handler.go
- les/peer.go
- les/server_handler.go
- les/test_helper.go
- les/ulc_test.go
use atomic.Bool for frozen and serving status in les.peerCommons
> les: use atomic type

- p2p/discover/v5_udp.go
Fixes a lint nit which is currently making appveyor fail
> p2p/discover: fix lint nit

- docs/developers/dapp-developer/native-bindings.md
fixes #27207 this is my first osc please do leave out comments :)
> website: rectifed RPC connection docs

- docs/developers/evm-tracing/built-in-tracers.md
To address the question in #27208
> website: details for diffMode of prestateTracer

- ethdb/dbtest/testsuite.go
- ethdb/memorydb/memorydb.go
> ethdb/dbtest: use slices package for sorting

- internal/jsre/deps/web3.js
> internal/jsre: fix typos

- cmd/evm/testdata/13/readme.md
- cmd/evm/testdata/2/readme.md
- cmd/evm/testdata/23/readme.md
- cmd/evm/testdata/3/readme.md
- cmd/evm/testdata/4/readme.md
- cmd/evm/testdata/5/readme.md
> cmd/evm: fix typos

- consensus/clique/api.go
> consensus/clique: fix typo in comment

- common/math/big.go
> common/math: fix typo in comment

- docs/developers/evm-tracing/built-in-tracers.md
- docs/developers/geth-developer/disclosures.md
- docs/fundamentals/index.md
- docs/fundamentals/peer-to-peer.md
- docs/fundamentals/private-network.md
- docs/interacting-with-geth/javascript-console-contracts.md
- docs/interacting-with-geth/javascript-console.md
- docs/interacting-with-geth/rpc/ns-personal.md
- docs/interacting-with-geth/rpc/ns-txpool.md
- docs/monitoring/dashboards.md
- docs/monitoring/metrics.md
- docs/monitoring/understanding-dashboards.md
- docs/resources.md
- docs/tools/clef/clique-signing.md
- docs/tools/clef/rules.md
This PR fixes some typos throughout the website.
Typos were detected using [cspell](https://cspell.org/) and manual review.
> website: fix typos

- core/chain_makers.go
- internal/ethapi/testdata/eth_getBlockReceipts-block-with-blob-tx.json
- internal/ethapi/testdata/eth_getBlockReceipts-block-with-contract-create-tx.json
- internal/ethapi/testdata/eth_getBlockReceipts-block-with-dynamic-fee-tx.json
- internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-contract-call-tx.json
- internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-transfer-tx.json
- internal/ethapi/testdata/eth_getBlockReceipts-tag-latest.json
- internal/ethapi/testdata/eth_getTransactionReceipt-blob-tx.json
- internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-tx.json
- internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-with-access-list.json
- internal/ethapi/testdata/eth_getTransactionReceipt-dynamic-tx-with-logs.json
- internal/ethapi/testdata/eth_getTransactionReceipt-normal-transfer-tx.json
- internal/ethapi/testdata/eth_getTransactionReceipt-with-logs.json
Fixes an error in tests of internal/ethapi.
> core: add BeaconRoot to header in GenerateChain

- accounts/abi/method.go
- accounts/abi/method_test.go
- accounts/abi/unpack.go
the fix is the same with #27816
> account/abi: convert if-else-if chain to tagged switch

- docs/developers/dapp-developer/native.md
1. Fix typo
2. Fix slice of common.Hash slice syntax.
3. Clarify how the hex string for the `Transfer` event is computed so the code matches with the description.
> Website:  Amend /docs/developers/dapp-developer/native:

- core/rawdb/databases_non64bit.go
Fixing a regression introduced in https://github.com/ethereum/go-ethereum/pull/27836
> core/rawdb: fix 32bit build

- core/state/statedb.go
This fixes a missing import that broken master
> core/state: fix missing import

- miner/stress/clique/main.go
> miner/stress/clique: fix typo

- core/state/state_object.go
- core/state/statedb.go
- eth/api_debug.go
- eth/api_debug_test.go
- internal/ethapi/api.go
It's a following PR based on #28025 
This PR improves the function description, simplify the logic, as a prepare step for further refactor.
> core/state: simplify storage trie update and commit

- docs/_vulnerabilities/vulnerabilities.json
- docs/_vulnerabilities/vulnerabilities.json.minisig
Vuln update after releasing advisory https://github.com/ethereum/go-ethereum/security/advisories/GHSA-ppjg-v974-84cm
> docs: vulnerabilities update

- public/docs/vulnerabilities/vulnerabilities.json
- public/docs/vulnerabilities/vulnerabilities.json.minisig
Update the _correct_ place, not only the [wrong](https://github.com/ethereum/go-ethereum/pull/28065)
> docs: vulnerabilities update (#28065)

- docs/fundamentals/security.md
> fundamentals/security: discourage public exposure of API 

- consensus/misc/gaslimit.go
> consensus/misc: fix min gas limit error message

- cmd/geth/genesis_test.go
This PR unborks master
see e..g https://ci.appveyor.com/project/ethereum/go-ethereum/builds/48252874/job/hriykyyd3soi0pd2
> cmd/geth: fix failing test

- go.mod
- go.sum
https://github.com/Consensys/gnark-crypto/security/advisories/GHSA-pffg-92cg-xf5c
> go.mod: update gnark lib to fix a malleability issue

- docs/fundamentals/private-network.md
> website: fix private network e2e example

- ethclient/ethclient.go
No idea how this got lost for such a long time. Neither how nobody noticed it.
> ethclient: fix forwarding 1559 gas fields

- Dockerfile.alltools
Keep it in sync with `Dockerfile`
> build: update Go to 1.21

- cmd/geth/snapshot.go
Fixes a regression introduced by #28256
> cmd/geth: fix build error

- eth/api_backend.go
- internal/ethapi/api.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
Get rid of a completely useless return parameter...
> eth, internal/ethapi: drop some weird indirection

- interfaces.go
Fixes TODO mentioned by @fjl   https://github.com/ethereum/go-ethereum/blob/2a2013014c46844728421a1acc5ad40ca823414b/interfaces.go#L32
> ethereum: remove TODO comment about subscription

- core/types/receipt_test.go
- ethdb/pebble/pebble.go
- go.mod
- go.sum
The dependency was not really used anyway, so we can get rid of it
> ethdb/pebble: remove a dependency

- cmd/evm/runner.go
closes https://github.com/ethereum/go-ethereum/pull/28691
> cmd/evm:  default to mirror mainnet forks enabled

- README.md
Replaced broken Github link proper badge.
> docs: fix badge in README

- docs/fundamentals/databases.md
- docs/fundamentals/mining.md
- docs/fundamentals/security.md
- docs/monitoring/understanding-dashboards.md
Found few errors while reading the docs on the website, hope I can be of any help.
Have a nice evening.
> chore(website): fix some typos

- tests/state_test.go
- tests/state_test_util.go
Updates the reference tests to the latest version
> tests: update reference tests

- miner/payload_building_test.go
> Fix typo in payload_building_test.go

- go.mod
- go.sum
> This release adds compatibility with Go 1.21.
> deps: update memsize

- ethclient/simulated/options.go
this PR:https://github.com/ethereum/go-ethereum/pull/28933 intrudce this typo.
> ethclient/simulated:fix typo

- docs/developers/dapp-developer/native-bindings.md
When working though some of the developer documentation, I found a code snippet that did not work. It looks like there were a few typos in the code.  While fixing, I also updated to remove deprecated usages.
> website: fix dapp-dev native-bindings simulator code

- cmd/utils/history_test.go
Fix a breakage incurred when I merged #28824
> cmd/utils: fix merge-breakage in test

- core/txpool/blobpool/blobpool.go
- go.mod
- go.sum
Fixes https://github.com/ethereum/go-ethereum/issues/28990
> core/txpool/blobpool: update the blob db with corruption handling

- docs/developers/dapp-developer/dev-mode.md
* Fix http cors issue when setup developer mode with remix URL
> website: fix developer mode tutorial

- triedb/pathdb/database.go
> triedb/pathdb: fix panic in recoverable

- internal/ethapi/api_test.go
> internal/ethapi: impl accessList conversion in tests to remove TODO

- core/types/transaction_signing.go
> core/types: reuse signtx

- rlp/iterator.go
> rlp: remove a meaningless todo

- miner/payload_building.go
Adds a debug level log if the payload building failed for whatever reason
> miner: add additional log

- docs/developers/dapp-developer/dev-mode.md
- docs/fundamentals/account-management.md
Fix initialize Clef command，use --configdir to specify Clef config directory
> website: fix account management

- Makefile
Adjust the makefile file and modify PHONY
Delete: android ios evm
Add: lint
Mobile: help
> Makefile: delete unused PHONY

- cmd/evm/runner.go
> cmd/evm: reopen the statedb for dumping

- core/txpool/blobpool/limbo.go
Fixes https://github.com/ethereum/go-ethereum/issues/29303.
> core/txpool: repair the limbo Billy too on unclean shutdowns

- trie/utils/verkle.go
Reduce a repetitive div calculation.
> trie/utils: change Div+Mod to DivMod

- p2p/nat/natpmp.go
- p2p/nat/natupnp.go
> p2p/nat: fix typos in comments

- core/vm/contracts_test.go
> core/vm: add KZG benchmark

- build/update-license.go
> build: fix string compare for SortFunc

- consensus/clique/snapshot.go
- trie/tracer.go
> trie, consensus/clique: use maps.Clone

- p2p/simulations/adapters/inproc.go
> p2p/simulations/adapters: use maps.Clone

- public/docs/vulnerabilities/vulnerabilities.json
- public/docs/vulnerabilities/vulnerabilities.json.minisig
See https://github.com/ethereum/go-ethereum/security/advisories/GHSA-4xc9-8hmq-j652
> docs: update vulns

- trie/sync.go
Since @rjl493456442 has changed the function `isDelete` to `valid` in #29485 , its comments need to be updated too.
> trie: update the `valid` function comments

- docs/developers/dapp-developer/native-accounts.md
- docs/developers/evm-tracing/custom-tracer.md
- docs/fundamentals/private-network.md
- docs/fundamentals/pruning.md
- docs/getting-started/index.md
- docs/getting-started/installing-geth.md
- docs/interacting-with-geth/rpc/ns-debug.md
fix typos/grammar.
remove duplicated/unnecessary words.
> [website]: update docs

- eth/gasprice/feehistory.go
I added some comments about recently released codes. [(#29644)](https://github.com/ethereum/go-ethereum/pull/29644)
> eth/gasprice: add comment to constant

- core/state/snapshot/generate.go
- core/state/snapshot/snapshot.go
Reverts ethereum/go-ethereum#29995
> Revert "core/state/snapshot: tiny fixes"

- docs/fundamentals/index.md
This PR
- adds missing parts to the index list of fundamentals.
- removes light client part as it no longer exists.
> [Website]: update the index of fundamentals

- docs/developers/index.md
This PR makes content consistent with sidebar
- update the content of links
- change the order of evm-tracing & Geth-developers
- move the contributing part to a seperate place
> [Website]: update introduction of developer doc

- docs/fundamentals/peer-to-peer.md
- docs/interacting-with-geth/rpc/index.md
- docs/monitoring/understanding-dashboards.md
> [Website]: fix broken links

- docs/developers/index.md
Fix a strange link, try to fix deployment error
> docs/devel: fix link

- beacon/light/sync/update_sync_test.go
adding simple tests for lock and firstUnlocked method from rangeLock type
> beacon/light/sync: basic tests for rangeLock

- .travis.yml
Debugging https://github.com/ethereum/go-ethereum/issues/28987#issuecomment-2307175785 , this PR would tell us the state of the vcs after the first build.
> build: debug travis build

- docs/developers/geth-developer/contributing.md
I just want to trigger website rebuild, to get around #30309
> update to rebuild website

- docs/postmortems/2021-08-22-split-postmortem.md
Update 2021-08-22-split-postmortem
> doc: update 2021-08-22-split-postmortem

- funding.json
Adds a list of funding identifiers.
> funding.json: add funding information file

- core/blockchain_test.go
un-borks a compilation error from a recent merge to master
> core: fix compilation error

- funding.json
Now that verification is done, we can remove the funding information.
> all: remove funding verifier

- core/tracing/hooks.go
> core/tracing: update hooks.go

- core/rawdb/accessors_metadata.go
Reverts ethereum/go-ethereum#30433
> Revert "core/rawdb: remove unused transition status state accessors"

- internal/ethapi/api.go
> internal/ethapi: fix gascap 0 for eth_simulateV1

- internal/web3ext/web3ext.go
These API modules have been removed already. This is dead code.
> internal/web3ext: rm unused modules

- swarm/README.md
Swarm moved out more than 5 years ago, time to let it go.
> swarm: nuke this leftover

- .gitignore
Clean out some ancient stuff from git ignore.
> gitignore: get rid of some relics

- eth/tracers/js/goja.go
While looking at some mem profiles from `evm` runs, I noticed that `goja` compilation of the bigint library was present. The bigint library compilation happens in a package `init`, whenever the package `eth/tracers/js` is loaded. This PR changes it to load lazily when needed. 
It becomes slightly faster with this change, and slightly less alloc:y. 
Non-scientific benchmark with 100 executions: 
```
time for i in {1..100}; do ./evm --code 6040 run; done;
```
current `master`:
```
real    0m6.634s
user    0m5.213s
sys     0m2.277s
```
Without compiling bigint
```
real    0m5.802s
user    0m4.191s
sys     0m1.965s
```
> eth/tracers/js: avoid compiling js bigint when not needed

- core/state/statedb_hooked.go
> core/state: small fix in hooked statedb

- .travis.yml
> travis: build and upload RISC-V docker images too

- core/vm/instructions.go
Deleting an unnecessary comment.
> core/vm: remove unnecessary comment

- core/state/access_list.go
- core/state/statedb_test.go
Remove superfluous function wrapping.
> core/state: remove pointless wrapper functions

- core/types/hashing_test.go
improvement:
i) change `fmt.Printf` to `t.Log`
ii) fix the `printList` json output format error
> core/types: improve printList in DeriveSha test

- eth/catalyst/api.go
Refer to: https://github.com/ethereum/execution-apis/pull/623
> eth/catalyst: fail on duplicate request types

- consensus/misc/eip4844/eip4844.go
- core/genesis_test.go
- params/config.go
- tests/init.go
Prevents crashes when running execution spec tests for osaka
> params: add osaka blob schedule

- .github/workflows/go.yml
> .github: downgrade go for lint step

- crypto/crypto.go
closes https://github.com/ethereum/go-ethereum/issues/26240
> crypto: add comment to FromECDSAPub

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
It's that time of the cycle, should have this ready to go for mainnet Prague release.
> cmd,eth,les: replace Cancun override flag with Prague

- tests/block_test.go
- tests/state_test.go
- tests/transaction_test.go
- tests/transaction_test_util.go
Get the re-filled tests (plus removal of outdated EIP-2537 tests)
> tests: update ethereum/tests to v17.0

- docs/developers/dapp-developer/native-bindings-v2.md
- Website builds are currently failing because of this
> Fix invalid frontmatter

- p2p/discover/v5_udp.go
- p2p/discover/v5_udp_test.go
- p2p/discover/v5wire/encoding.go
Alternative to #31111 for testing.
> p2p/discover: repeat WHOAREYOU challenge when handshake in progress

- core/txpool/locals/tx_tracker_test.go
- core/txpool/txpool.go
Fixes https://github.com/ethereum/go-ethereum/issues/31451
> core/txpool: reject stale transaction for local tracking

- core/txpool/locals/tx_tracker_test.go
- core/txpool/txpool.go
- eth/api_backend.go
> core/txpool: fix nonce assignment in local tracker

- cmd/clef/rules.md
- cmd/evm/README.md
- cmd/evm/eest.go
- eth/downloader/skeleton.go
- internal/guide/guide_test.go
Corrected usecases to use cases
Corrected blockshashes to block hashes
Corrected gnerated to generated
Corrected signalling to signaling
Corrected out to our
> all: fix typos in docs and comments

- .github/CODEOWNERS
Thank you, @holiman, for being an integral part of the Go-Ethereum 
and for your invaluable contributions over the years.
This will always be your home and you're welcome back anytime!
> all: remove martin from CODEOWNERS

- core/forkid/forkid_test.go
- params/config.go
https://eips.ethereum.org/EIPS/eip-7600#activation
Timestamp: `1746612311`
Fork id: `0xc376cf8b`
> params: add prague timestamp for mainnet

- cmd/evm/internal/t8ntool/execution.go
- core/chain_makers.go
- core/state_processor.go
- internal/ethapi/simulate.go
- miner/worker.go
see: https://github.com/ethereum/pm/issues/1450#issuecomment-2800911584
> core: fail execution if system call fails to execute

- beacon/params/networks.go
This PR adds the electra beacon chain configuration for mainnet.
> beacon/params: add mainnet electra config

- beacon/engine/types.go
- eth/catalyst/api.go
Fixes https://github.com/ethereum/go-ethereum/issues/31737
> beacon/engine: omit empty witness in payload response

- .mailmap
- AUTHORS
Hello all,
I'm no longer actively involved in blockchain development, but I figured that I should update my AUTHOR attribution, considering my name (and gender) has changed since I last contributed.
I'd be happy to verify my ownership of the old email address(es) if required.
> AUTHORS, .mailmap: update name and email attribution

- cmd/geth/main.go
- cmd/utils/flags.go
- cmd/utils/flags_legacy.go
They were not widely used in users setups.
> cmd: remove deprecated LES flags

- cmd/utils/flags.go
> cmd/utils: remove duplicate code for influxDB tags

- eth/tracers/js/goja.go
- eth/tracers/js/tracer_test.go
Add testcase for toWord with different input length
> eth/tracers: Improve test coverage for toWord

- crypto/signature_cgo.go
- crypto/signature_nocgo.go
tinygo is having problems compiling the C implementation
> crypto: fallback to native signature implementation in tinygo

- .gitea/workflows/release.yml
Trying to make the docker build work
> .gitea: update release build actions

- core/vm/contracts.go
Implements the updated gas cost changes introduced in https://github.com/ethereum/EIPs/commit/5cdd75157d78522bde8dc58977717c14cd7f2789
> core/vm: implement updates to modexp gas cost changes in eip 7883

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
replace `--override.prague` with `--override.osaka`
> all: replace override.prague with osaka

- internal/jsre/deps/web3.js
- rpc/client.go
- rpc/subscription_test.go
Similar to https://github.com/ethereum/go-ethereum/pull/31856, remove the not availabe shh, swarm modules in the console.
> internal: remove the not availabe shh, swarm modules

- core/vm/eips.go
https://github.com/ethereum/EIPs/commit/a794de3fcf71bb8c71e8bafdba11f63133ce4516
> core/vm: update gas cost of CLZ to five

- eth/downloader/beaconsync.go
- eth/downloader/skeleton.go
> eth/downloader: improve nil pointer protection

- core/state_processor_test.go
- params/protocol_params.go
Updates the tx gas limit cap to the new parameter (2^24) https://github.com/ethereum/EIPs/pull/9986/files
> params: update tx gas limit cap

- p2p/rlpx/rlpx.go
Replace manual byte-by-byte XOR implementation with the optimized bitutil.XORBytes function. This improves performance by using word-sized operations on supported architectures while maintaining the same functionality. The optimized version processes data in bulk rather than one byte at a time
> p2p/rlpx: optimize XOR operation using bitutil.XORBytes

- version/version.go
> version: release v1.16.2

- crypto/kzg4844/kzg4844.go
https://github.com/golang/go/issues/60088
> crypto/kzg4844: use reflect.TypeFor

- beacon/merkle/merkle.go
https://github.com/golang/go/issues/60088
> beacon/merkle: use reflect.TypeFor

- signer/core/apitypes/types.go
https://github.com/golang/go/issues/60088
> signer/core/apitypes: simplify reflect []byte creation

- p2p/config.go
it can be 0 after the Merge update
> p2p: update MaxPeers comment

- eth/catalyst/api.go
Return the exposed methods in `ConsensusAPI` by reflection.
> eth/catalyst: return methods by reflect

- triedb/pathdb/reader.go
Fixes https://github.com/ethereum/go-ethereum/issues/32474
> triedb/pathdb: improve err message in historical state reader

- internal/web3ext/web3ext.go
> internal/web3ext: remove deprecated method debug_seedHash

- node/node.go
fix problematic function name in comment
> node: fix problematic function name in comment

- beacon/light/request/scheduler.go
- core/filtermaps/indexer.go
- core/state/reader.go
- core/verkle_witness_test.go
- core/vm/program/program.go
- crypto/kzg4844/kzg4844_ckzg_cgo.go
- crypto/kzg4844/kzg4844_gokzg.go
- eth/handler.go
- p2p/enode/iter.go
- triedb/pathdb/iterator.go
- triedb/pathdb/states.go
Fix problematic function name in comment.
Do my best to correct them all with a script to avoid spamming PRs.
> all: fix problematic function name in comment

- core/state/statedb_hooked.go
> core/tracing: fix selfdestruct 6780 balance change emit

- core/tracing/CHANGELOG.md
Update all the accumulated changes
> core/tracing: update changelog

- cmd/geth/snapshot.go
- cmd/utils/cmd.go
- tests/state_test.go
- tests/state_test_util.go
> cmd, tests: fix snapshot dump and export-preimages

- core/txpool/blobpool/blobpool.go
This is a small improvement on  #32656 in case Add was called with multiple type 3 transactions,
adding transactions to the pool one-by-one as they are converted.
Announcement to peers is still done in a batch.
> core/txpool/blobpool: convert and add one-by-one

- core/txpool/validation.go
- core/txpool/validation_test.go
- eth/api_backend_test.go
closes https://github.com/ethereum/go-ethereum/issues/32722
> core/txpool: add eip2681 check for incoming transactions

- trie/sync.go
This is a minor memory allocation optimization for the sync path construction
> trie: optimize array allocation during sync path construction
