accounts/abi/argument.go
accounts/abi/bind/topics.go
accounts/abi/bind/topics_test.go
accounts/abi/unpack.go

Refactored topics to remove big type switch, now uses ToGoType from abi/argument
rel: https://github.com/ethereum/go-ethereum/issues/20275

accounts/abi/bind: Refactored topics 

---

cmd/geth/accountcmd_test.go
crypto/crypto.go
crypto/crypto_test.go

Invoking `geth account import key.prv`
Old error message: `Failed to load the private key: unexpected EOF`
New error message: `Failed to load the private key: key file too short, want 64 hex characters`
Note: it was OK to provide a longer key than expected. Now it's an error too.

crypto: improve error messages in LoadECDSA

---

accounts/abi/bind/topics.go
accounts/abi/bind/topics_test.go

Setting up filters/subscriptions for negative values was broken.
Following solidity code could not be properly queried for:
```
pragma solidity >=0.4.22 <0.7.0;
contract Eventer {
event TestInt8(int8 indexed out1, int8 indexed out2);
event AnonEvent(address, address);
function getEvent() public {
// set to 2,3 for functioning filter
emit TestInt8(-2, -3);
}
```
Go test code:
```
func TestNegativeEvent(t *testing.T) {
ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
defer cancel()
backend, sk := getSimBackend()
transactor := bind.NewKeyedTransactor(sk)
_, _, eventer, err := DeployEventer(transactor, backend)
assert.NoError(t, err)
tx, err := eventer.GetEvent(transactor)
backend.Commit()
assert.NoError(t, err)
receipt, err := bind.WaitMined(ctx, backend, tx) …
```

accounts/abi/bind: fixed erroneous filtering of negative ints

---

internal/web3ext/web3ext.go
les/benchmark.go
les/client.go
les/client_handler.go
les/lespay/client/api.go
les/lespay/client/requestbasket.go
les/lespay/client/requestbasket_test.go
les/lespay/client/timestats.go
les/lespay/client/timestats_test.go
les/lespay/client/valuetracker.go
les/lespay/client/valuetracker_test.go
les/peer.go
les/protocol.go
les/txrelay.go
les/utils/expiredvalue.go
les/utils/expiredvalue_test.go
p2p/enode/node.go

This PR adds service value measurement statistics to the light client. It also adds a private API that makes these statistics accessible. A follow-up PR will add the new server pool which uses these statistics to select servers with good performance.
This document describes the function of the new components:
https://gist.github.com/zsfelfoldi/3c7ace895234b7b345ab4f71dab102d4

les, les/lespay/client: add service value statistics and API

---

README.md

Currently with 1.10 you cannot build anymore as you get this error:
```
env GO111MODULE=on go run build/ci.go install ./cmd/geth
build/ci.go:61:2: cannot find package "github.com/cespare/cp" in any of:
/usr/lib/go-1.10/src/github.com/cespare/cp (from $GOROOT)
/home/ligi/go/src/github.com/cespare/cp (from $GOPATH)
build/ci.go:62:2: use of internal package not allowed
Makefile:16: recipe for target 'geth' failed
make: *** [geth] Error 1
```
so updating the minimum version here

README: update min go version to 1.13

---

.travis.yml
Dockerfile
Dockerfile.alltools
appveyor.yml
build/checksums.txt

Fixes https://github.com/ethereum/go-ethereum/issues/20734, both upstream issues have been patched, first in Go 1.14.1 and the second in Go 1.14.2.
---
I've pushed a second commit that adds `GO111MODULE=on` to travis and appveyor. These are a bit of a bummers, but Go 1.14 still defaults to `auto` on module support, which reverts to GOPATH mode if running in a gopath, which is baad https://github.com/golang/go/issues/38196

travis, appveyor, build, Dockerfile: bump Go to 1.14.2

---

core/rawdb/freezer_table.go

closes https://github.com/ethereum/go-ethereum/issues/20420

core/rawdb: fix data race between Retrieve and Close

---

cmd/utils/cmd.go
common/bytes.go
common/bytes_test.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_snapshot.go
core/rawdb/database.go
core/rawdb/table.go
core/rawdb/table_test.go
core/state/iterator_test.go
core/state/snapshot/disklayer_test.go
core/state/snapshot/iterator.go
core/state/snapshot/wipe.go
core/state/snapshot/wipe_test.go
core/state/statedb_test.go
eth/filters/bench_test.go
eth/handler_test.go
ethdb/dbtest/testsuite.go
ethdb/iterator.go
ethdb/leveldb/leveldb.go
ethdb/memorydb/memorydb.go
les/clientpool.go
trie/iterator_test.go
trie/proof_test.go
trie/sync_bloom.go

This PR changes the way the Iteratee interface is defined. Previously, we had
```
NewIteratorWithPrefix(prefix []byte)
NewIteratorWithStart(start []byte)
```
But no good way to get a prefixed iterator with a given start position. As that was missing, a lot of code made one of two mistakes: 
1. Use `NewIteratorWithStart( prefix ++ start)`. This solution is wrong; consider the prefix `0x0a` and start `0x00`. The returned iterator would also return e.g `0x0b`, as it is after `a` in the keyspace. 
2. Use `NewIteratorWithPrefix( prefix ++ start)`. This is also wrong. Consider the prefix `0x0a` and start `0x01`. This iterator would miss a key at `0x0a02`, since `0x0a01` is not a prefix to `0x0a02`. 
I replaced both of these with 
```
NewIteratorWith(prefix, start []byte)
```

core/state/snapshot: implement disk iterator seek

---

p2p/discover/v5_udp.go
p2p/discover/v5_udp_test.go

Adds two new receiver methods to `UDPV5` which are `AllNodes` and `LocalNode`. 
`AllNodes` returns all the nodes stored in the local table; this is useful for the purposes of metrics collection and also debugging any potential discovery issues with other discoveryV5 implementations.
`LocalNode` returns the raw local node object to the caller. The reason for exposing this is so that users can modify and set/delete new key-value entries from our local record. This is required when so as to update your local enr with any new information and remove outdated ones from it.

p2p/discover: add new methods to udpV5

---

event/event.go

Function [`del()`](https://github.com/BurtonQin/go-ethereum/blob/255e927d0b31dab9e9b339672349b01d8eb3cc17/event/event.go#L117-L129) locks on `mux.mutex` but unlocks on `s.mux.mutex.Unlock()`. `s` comes from the input parameter.
The only caller of del() is [`Unsubscribe()`](https://github.com/BurtonQin/go-ethereum/blob/255e927d0b31dab9e9b339672349b01d8eb3cc17/event/event.go#L179), where the same `s` is provided as the input in `s.mux.del(s)`.
I think we cannot depend on the input to guarantee the consistency of Lock and Unlock.
Can we change `del()` to use the same mutex for `Unlock` and `Lock`, following other functions like [`Subscribe()`](https://github.com/BurtonQin/go-ethereum/blob/255e927d0b31dab9e9b339672349b01d8eb3cc17/event/event.go#L56) and …

event: fix inconsistency in Lock and Unlock

---

core/state/snapshot/iterator.go
core/state/snapshot/snapshot.go

There are two forgetting Unlock bugs fixed in this PR:
1. In `func Account()`,
https://github.com/ethereum/go-ethereum/blob/648b0cb7144feec13391f8e587866e9d47a75548/core/state/snapshot/iterator.go#L124-L132
`it.layer.lock.RUnlock()` is forgot before return and panic.
2. In `func diffToDisk()`,
https://github.com/ethereum/go-ethereum/blob/648b0cb7144feec13391f8e587866e9d47a75548/core/state/snapshot/snapshot.go#L421-L426
`base.lock.Unlock()` is forgot before panic.

snapshot: add Unlock before return/panic

---

core/state/snapshot/iterator.go
core/state/snapshot/iterator_test.go

This PR fixes an issue in the account iterator for difflayers (disk layers are correct). 
A seek operation to `0x00..` would never return a theoretical key at that location, so the seek op must be inclusive, not exclusive.

core/state/snapshot: make difflayer account iterator seek operation inclusive

---

README.md
accounts/keystore/keystore.go
accounts/keystore/keystore_test.go
cmd/geth/accountcmd_test.go

Calling keystore.Import or keystore.ImportECDSA might result in a race.
If they are called in parallel, they both check whether a key is already in the keystore.
The keystore is empty so both threads insert their key into the keystore.
This however results in a keystore that contains a key twice.
I personally do not like the additionally mutex in the structure, but I currently don't see another way to do this.
additional: Tests for exporting/importing keys
closes https://github.com/ethereum/go-ethereum/issues/19575#event-3230244782

accounts/keystore: fix race-condition in Import/ImportECDSA

---

les/odr_requests.go
trie/proof.go
trie/proof_test.go

It's the feature to prove a range of consecutive data maintained by trie. 
The algo of range proof is quite simple:
- Use 2 edge proofs to recover two edge paths
- Unset all internal references(hashnode, embedded nodes) if the node is covered by the range
- Re-construct the trie with given range data
- Compare the root hash, ensure they are same
If any gapped in the data range, it can be detected since all internal nodes have been unset.

trie: initial implementation for range proof

---

core/state/snapshot/iterator_binary.go
core/state/snapshot/iterator_test.go

This PR fixes an issue in the `binaryIterator`.
In the original implementation, the binary iterator doesn't search "diskLayer" which will lead to miss lots of valid entries.

core/state/snapshot: fix binary iterator

---

p2p/enode/urlv4.go

p2p/enode: update code comment
Since commit b90cdbaa79cfe438aab0f1389d35980f3d38ec84 it's possible to specify enode Url using domain name, but under code comment it still mentionned that only IP Address is allow.

p2p/enode: update code comment

---

eth/downloader/downloader.go
eth/sync.go

Fixes https://github.com/ethereum/go-ethereum/issues/20975
I still managed to hang it once, but not general, so there might be something still in there, but at least most hangs are fixed.

eth: fix shutdown regression to abort downloads, not just cancel

---

cmd/clef/main.go
cmd/geth/retesteth.go
node/endpoints.go
node/node.go

Rather than just closing the underlying network listener to stop our HTTP servers (including WebSocket), use [the graceful shutdown procedure](https://pkg.go.dev/net/http?tab=doc#Server.Shutdown), waiting for any in-process requests to finish.
Don't return the `net.Listener` to callers of `node.StartHTTPEndpoint`, as the `net/http.Server` assumes responsibility for the `net.Listener` lifecycle once fed to [`(*Server).Serve`](https://pkg.go.dev/net/http?tab=doc#Serve).

node: shut down all node-related HTTP servers gracefully

---

core/chain_indexer.go

In core/chain_indexer.go,
The first lock is `c.lock.Lock()` in func `AddChildIndexer()`.
Then the func calls `indexer.newHead()`, where the second lock is called.
If `c == indexer`, then this is a double lock.
https://github.com/ethereum/go-ethereum/blob/1aa83290f5052ce275fc4f36b909a721afe6037a/core/chain_indexer.go#L240-L242
The fix adds a condition before the first lock: if `c == indexer`, then directly returns.
Since `AddChildIndexer()` is a public func, I think it is necessary to add this checking to prevent developers from mistakenly passing `ChainIndexer` itself to the function.

core: add skip in AddChildIndexer() to avoid double lock

---

rpc/client_example_test.go

Correct call to eth_getBlockByNumber. Fixes error:
```
can't get latest block: missing value for required argument 1
```
Properly unmarshall JSON. Fixes errors like this:
```
can't get latest block: math/big: cannot unmarshal "\"0xc5311\"" into a *big.Int
```

rpc: make ExampleClientSubscription work with the geth API

---

core/blockchain_test.go

This is a resubmit of https://github.com/ethereum/go-ethereum/pull/20668 which rewrites
the problematic test without any additional goroutines. It also documents the test better.
The purpose of this test is checking whether log events are sent correctly when importing
blocks. The test was written at a time when blockchain events were delivered asynchronously,
making the check hard to pull off. Now that core.BlockChain delivers events synchronously
during the call to InsertChain, the test can be simplified.

core: improve TestLogRebirth

---

docs/_getting-started/index.md

Adding an alternative command since some people are unable to connect with 'geth attach' command by itself.

[DOCS] add note about HTTP attach in getting started guide

---

rpc/http.go
rpc/http_test.go

When receiving an HTTP GET request with no content and no URL query, we assume the client may be a health check probe, and process the request without complaint. We had been omitting the HTTP status code in our otherwise empty response, though, which aggravates some HTTP
clients. Instead, respond with HTTP status code 200, indicating the request was accepted and processed successfully.

rpc: Respond to empty JSON-RPC requests with an HTTP OK status code

---

log/format.go
signer/core/cliui.go
signer/core/signed_data.go
signer/fourbyte/abi.go
signer/fourbyte/validation.go

This PR modifies core logging facilities and clef console handler to properly escape character sequences

log: properly escape character sequences

---

core/state/snapshot/account.go
core/state/snapshot/conversion.go
core/state/snapshot/difflayer.go
core/state/snapshot/difflayer_test.go
core/state/snapshot/generate.go
core/state/snapshot/iterator.go
core/state/snapshot/iterator_binary.go
core/state/snapshot/iterator_fast.go
core/state/snapshot/iterator_test.go
core/state/snapshot/snapshot.go
core/state/snapshot/snapshot_test.go
core/state/statedb.go
tests/block_test_util.go

This PR implements the storage iterator for snapshot.
Note: it has passed all consensus tests and it's verified in `goerli` testnet

core/state/snapshot: implement storage iterator

---

core/state/snapshot/journal.go

The snapshot journal uses RLP to serialize the in-memory diff layers on shutdown/restart. An RLP serialize and deserialize round however loses the nil-ness of a byte slice, converting it to empty: https://play.golang.org/p/bAxBMJrryYz
This PR converts the empty slices back to nil, since the snapshotter depends on nils explicitly. It is fine to do this because an "empty" account rlp blob makes no sense, and empty values are not stored in storage tries either.

core/state/snapshot: fix journal nil deserialziation

---

core/state/snapshot/conversion.go
go.sum

This PR fixes an issue in the trie-generator reporter.
Whenever any progress statistic is recorded, we should
update the reporter status atomically even the current
slot hash is empty(it's a valid use case. e.g. last time we
record progress data is in account storage, then 
"curAccount" = "A", "curSlot" = "S0" is recorded. However
this time we are in the state trie, then we should update 
the status to `curAccount` = "B", "curSlot" = "EMPTY"

core/state/snapshot: fix trie generator reporter

---

accounts/external/backend.go

This PR fills the account-cache from an externals signer, if that hasn't already been done. Fixes #20995
Bug repro below (but I only include the results for this PR): 
gethsign.json:
```json
cat gethsign.json
{
"method": "eth_sign",
"params": [ "0xD38018ac06AE8394C2a0Ed55BfDc3EE76e0Aa55C", ""],
"id": 67
}
```
Start `clef` with: `build/bin/clef --keystore ~/tmp/fookeys`
Start `geth` with `build/bin/geth --nodiscover --maxpeers 0 --signer /home/user/.clef/clef.ipc`
Then send a request (without having touched the console) : `cat gethsign.json | nc -U /home/user/.ethereum/geth.ipc`
Clef output:
```
-------- List Account request--------------
A request has been made to list all accounts.
You can select which accounts the caller can see
[x] …
```

accounts/external: fetch external accounts

---

les/peer_test.go

Similar to PR #20961
`testing.Fatal()/FailNow()/SkipNow()/...` can only be used in test goroutine.
`t.Fatal()/Fatalf()/FailNow()` "[must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test.](https://golang.org/pkg/testing/#T.FailNow)"
The fix directly returns `err` to replace the `t.Fatal()` in the child goroutine of test. 
`err` will be passed to `errCh2` and the test goroutine will receive it and call `t.Fatal()`.

les: remove invalid use of t.Fatal in TestHandshake

---

accounts/accounts.go
accounts/external/backend.go

With this PR, the outputs from `eth.sign` is identical regardless of whether
`clef` is used as backend, or a regular keystore.
Keystore:
```
[user@work go-ethereum]$ build/bin/geth --nodiscover --maxpeers 0 --keystore=~/tmp/fookeys console
```
```
// unlock first
>  eth.sign("0xD38018ac06AE8394C2a0Ed55BfDc3EE76e0Aa55C","")
"0x324b5f7e6be13118848225da6b0c18fd80d2759952ba3d55d15de01bb36d5a0808141daa1b50ea216e99d1cb855446c86462244b63baa610f8d8d77740c09a3c1c"
```
Clef:
```
[user@work go-ethereum]$ build/bin/geth --nodiscover --maxpeers 0 --signer /home/user/.clef/clef.ipc console
```
```
> eth.sign("0xD38018ac06AE8394C2a0Ed55BfDc3EE76e0Aa55C","")
"0x324b5f7e6be13118848225da6b0c18fd80d2759952ba3d55d15de01bb36d5a0808141daa1b50ea216e99d1cb855446c86462244b63baa610f8d8d77740c09a3c1c"
```

accounts/external: convert signature v value to 0/1

---

docs/_interface/JavaScript-Console.md

Simply noted a typo, "when" instead of "with"

Correct typo

---

cmd/evm/staterunner.go
eth/tracers/tracers_test.go
tests/state_test.go
tests/state_test_util.go
tests/vm_test_util.go

A while back we added support for testing the snapshots via the consensus tests too. Unfortunately we only added generating the snapshots, but didn't add journalling them onto disk (which also cleans up the generator goroutines). That lead to all tests leaking out a snapshot goroutine.
This PR fixes it by properly tearing down all the generators.

tests: cleanup snapshot generator goroutine leak

---

core/state/snapshot/conversion.go

Fixes an iterator leak in snapshot/trie verification

core/state/snapshot: release iterator after verification

---

build/ci.go

The consensus test suite is getting eerily close to the 5 minute runtime mark. It also exceeds that on AppVeyor, so this PR bumps the limit back to the default 10 mins.

build: raise test timeout back to 10 mins

---

tests/state_test.go

One consensus test is doing a 1MB EVM alloc for 1024 stack descends. which is 1GB RAM (at 855 billion gas). Disable this to avoid nuking CI.

tests: skip consensus test using 1GB RAM

---

cmd/geth/main.go

If a 32bit Geth is ran on a system with a lot of RAM (e.g. AppVeyor 32bit test), Geth will bump the memory request to 4GB, which will cause an OOM since we cannot address that much. This PR adds a fine tuning so that if we're on a 32 bit platform (or rather have 32 bit pointers), then we cap the memory Geth will use accordingly.
I'm unsure what the correct value is. The theoretical max in 4GB RAM, Windows I know only allows about 3 to be used.

cmd/geth: handle memfixes on 32bit arch with large RAM

---

eth/peer.go

Since implementing tx announcement, we've spun up a goroutine even for `eth<65` peers. Whilst they are harmless, they make debugging goroutine leaks hard as they fill up the stack traces with noise. This PR just doesn't spin them up n the first place. The shutdown is fine as there's no individual tracking and the async announce sends are already properly limited to `eth65+`.

eth: skip transaction announcer goroutine on eth<65

---

eth/backend.go

geth created a snapshot despite no --snapshot given on command line, because it's activated by snapshot cache size greater than 0

Fix snapshot surprise

---

eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/queue.go
trie/sync.go

eth/downloader: minor typo fixes in comments

---

core/tx_pool_test.go

As the [https://golang.org/pkg/sync/](https://golang.org/pkg/sync/) says about RLock:
`It should not be used for recursive read locking; a blocked Lock call excludes new readers from acquiring the lock.`
So double read lock should also be avoided.
In core/tx_pool_test.go,
func `validateTxPoolInternals()` calls `pool.mu.RLock()`.
https://github.com/ethereum/go-ethereum/blob/1aa83290f5052ce275fc4f36b909a721afe6037a/core/tx_pool_test.go#L99-L101
Then it calls `pool.Nonce()`, where the second `pool.mu.RLock()` resides.
https://github.com/ethereum/go-ethereum/blob/1aa83290f5052ce275fc4f36b909a721afe6037a/core/tx_pool_test.go#L120
https://github.com/ethereum/go-ethereum/blob/1aa83290f5052ce275fc4f36b909a721afe6037a/core/tx_pool.go#L429-L431
The fix is to use the code inside `Nonce()` directly …

core: avoid double-lock in tx_pool_test

---

core/state/snapshot/difflayer.go

The storage iterator caches sorted slots into the diff layer when iterating. There was a tiny omission where we didn't check whether an account is referenced by a layer at all or not, rather always created the sorted slots. This meant that we ended up creating sorted empty lists for every account in the state.

core/state/snapshot: don't create storage list for non-existing accounts

---

accounts/abi/bind/template.go

Currently the java generator generates invalid input on pure/view functions
that have no return type. e.g. `function f(uint u) view public {}`
This is not a problem in practice as people rarely ever write functions like this.

accounts/abi/bind: add void if no return args specified

---

core/state/statedb.go
core/state/statedb_test.go

We should abort committing/writing to the trie if we have had a previous error while loading stuff

core/state: abort commit if errors have occurred

---

core/state/statedb.go

The PR https://github.com/ethereum/go-ethereum/pull/21039 introduced a regression, apparently because we did not have a shortcut for the emptycodehash when called from e.g. `EXTCODEHASH`. This caused an internal db error every time it was invoked on an account without code. 
Previously, we silently ignored that, but with the changes in #21039, we suddenly started caring about it, and thus rejected blocks/peers.

core/state: avoid statedb.dbErr due to emptyCode

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go
internal/ethapi/api.go

accounts/abi/bind/backend, internal/ethapi: recap gas limit with balance

---

core/state/state_object.go
core/state/statedb.go

Functionally this is a noop change, but code readability wise it moves the special case handling of GetCode and GetCodeSize side by side to avoid the same logic being scattered across two files.

core/state: make GetCodeSize mirror GetCode implementation wise

---

console/bridge.go

A few things were broken on the bridge. Before this PR:
```
> admin.sleepBlocks(1,1)
GoError: expected number as second argument
at native
at <eval>:1:21(4)
> admin.sleep() //crash
> personal.unlockAccount() // crash
> personal.sign() //crash
```
With this PR:
```
>  admin.sleepBlocks(1,1)
true
> admin.sleep()
GoError: usage: sleep(<number of seconds>)
at native
at <eval>:1:1(2)
> personal.unlockAccount()
GoError: usage: unlockAccount(account, [ password, duration ])
at native
at <eval>:1:1(2)
> personal.sign()
GoError: usage: sign(message, account, [ password ])
at native
at <eval>:1:1(2)
```

console: fix some goja-related crashes/errors in the bridge

---

core/rawdb/database.go
core/rawdb/freezer.go

When you call db.Close(), it was closing the leveldb database first, then closing the freezer, but never stopping the freezer process. This could cause the freezer to attempt to write to leveldb after leveldb had been closed, leading to a crash with a non-zero exit code. 
This can be a problem, for example, when running with the --exitwhensynced flag and checking the exit code to make sure it synced properly. If the freezer process is running when it catches up with the network and shuts down, it can cause a failed error code. This is rare, but we do see it occasionally. The database is generally fine when this happens, but we'd like to avoid a non-zero exit code.
This change adds a quit channel to the freezer, and freezer.Close() will not return until the freezer process has stopped. …

core/rawdb: Stop freezer process as part of freezer.Close()

---

p2p/dial.go
p2p/discover/v4_udp.go
p2p/simulations/adapters/types.go

We already have a check like this for UDP ports, add a similar one in
the dialer. This prevents dials to port zero and it's also an extra
layer of protection against spamming HTTP servers.
Fixes #20937

p2p: add low port check in dialer 

---

core/blockchain_test.go

Fixes some tests that became bad in https://github.com/ethereum/go-ethereum/pull/20302

core/tests: fixup blockchain tests

---

les/peer.go
les/server_handler.go

Fix the issue like 
```
goroutine 1775696068 [semacquire, 3413 minutes]:
sync.runtime_SemacquireMutex(0xc045c3b744, 0x1065c00, 0x1)
/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc045c3b740)
/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
/usr/local/go/src/sync/mutex.go:81
github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg.func2(0x62888cdf70726b39, 0x1, 0xc064ea2580, 0x8694d)
/go-ethereum/les/server_handler.go:237 +0x362
github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg.func4(0xc12a418520, 0xc0e631fd00, 0xc08b1fe588, 0xc1964d37a0, 0xc09f33e330, 0xc0022b67d0, 0xc045c3b680, 0xc0e631fd80, 0x1)
/go-ethereum/les/server_handler.go:429 +0x265
created by github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg …
```

les: drop the message if the entire p2p connection is stuck

---

core/rawdb/chain_iterator.go

```
core/rawdb/chain_iterator.go:20:2: imported and not used: "math"
```

core/rawdb | remove unused math

---

accounts/abi/argument.go
accounts/abi/bind/base.go
accounts/abi/bind/base_test.go
accounts/abi/bind/bind.go
accounts/abi/bind/template.go
accounts/abi/bind/topics_test.go
accounts/abi/bind/util.go
accounts/abi/bind/util_test.go
accounts/abi/topics.go
accounts/abi/topics_test.go
accounts/abi/unpack.go

The topic functionality is imo better suited for the abi package than the bind package.
Additional: more tests, slight changes in bind and templates (reduce duplicated logic).

accounts/abi: accounts/abi/bind: Move topics to abi package

---

accounts/abi/abi_test.go
accounts/abi/type.go

In solidity it is possible to create the following contract:
```
contract Overloader {
struct F { uint _f; uint __f; uint f; }
function f(F memory f) public {}
}
```
This however resulted in a panic in the abi package.
Closes https://github.com/ethereum/go-ethereum/issues/21049

accounts/abi: allow overloaded argument names

---

core/blockchain.go

Fixes #20239
It fixes this scenario which may lead to `losing receipts`.
* Running Geth for clique chain(rinkeby, ropsten)
* Crash(without commit the latest state)
* Restart, rewind the `CurrentBlock` to a lower point which has the available relevant state
* Start to sync, import a batch of blocks via `insertSideChain`
* This batch blocks contain some "unknown" blocks, we commit them without "receipts"
* The "sidechain" longer than the "canonical" one, re-insert them for state generation
* But if there is an "empty" block, the first block will also complete this empty one since the state root is same.
* Skip reinsert the "empty" block, we lose the receipt entry
So the issue happens only when we run a clique chain and the block is empty. So the fix can always insert an empty receipt slice …

core: fix missing receipt

---

cmd/clef/main.go
cmd/puppeth/wizard_genesis.go

Correcting a couple of log messages that are missing the field name in the arguments. This will prevent output that would otherwise occur in the logs, like:
`LOG15_ERROR="Normalized odd number of arguments by adding nil"`

Corrections to logged error messages.

---

cmd/clef/README.md
cmd/clef/main.go
cmd/devp2p/dnscmd.go
cmd/ethkey/utils.go
cmd/geth/accountcmd.go
cmd/geth/chaincmd.go
cmd/geth/main.go
cmd/wnode/main.go
console/bridge.go
console/console.go
console/console_test.go
console/prompt/prompter.go
signer/core/cliui.go

This PR uses a better terminal input for passwords, plus makes it possible to avoid boot-up warning. 
Before this PR, piping input would cause `inappropriate ioctl for device`, for some reason: 
```
yes only_for_demo | ./build/bin/clef --keystore pretixkeys/ newaccount
INFO [04-22|05:47:57.152] Starting clef                            keystore=pretixkeys/ light-kdf=false
DEBUG[04-22|05:47:57.152] FS scan times                            list=83.283µs set=1.699µs diff=2.31µs
Please enter a password for the new account to be created (attempt 0 of 3)
> ERROR[04-22|05:47:57.152] Failed to read password                  err="inappropriate ioctl for device"
```
This PR uses instead the terminal from liner, already in use by the geth-codebase, and also makes it possible to avoid having to type …

cmd/clef, signer/core: password input fixes

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go

In accounts/abi/bind/backends/simulated.go,
Four functions `CodeAt()`, `BalanceAt()`, `NonceAt()`, `StorageAt()` call `stateByBlockNumber()`.
https://github.com/ethereum/go-ethereum/blob/1aa83290f5052ce275fc4f36b909a721afe6037a/accounts/abi/bind/backends/simulated.go#L143-L147
But before that, they all hold `b.mu.Lock()`.
Then func `stateByBlockNumber()` calls `b.BlockByNumber()`, where the second `b.mu.Lock()` resides.
https://github.com/ethereum/go-ethereum/blob/1aa83290f5052ce275fc4f36b909a721afe6037a/accounts/abi/bind/backends/simulated.go#L131-L135
https://github.com/ethereum/go-ethereum/blob/1aa83290f5052ce275fc4f36b909a721afe6037a/accounts/abi/bind/backends/simulated.go#L242-L244
The fix is to add a No-Lock version of `BlockByNumber()`: `blockByNumberNoLock()`.
Then we call …

accounts: add blockByNumberNoLock() to avoid double-lock

---

go.sum
trie/proof.go
trie/proof_test.go

In this PR, range proof is improved.
Originally we only allow range proof with two existent edge proofs. 
However in the real use cases, it's quite common that the first edge
proof might point to a non-existent node. So in this PR, non-existent
left edge proof is allowed.
Besides, there are a few corner cases handled:
- The range is empty, and the left edge proof is a non-existent proof. In this case 
the function will verify whether there still exist some leaves on the right side. If
so, then return the error.
- The range only has one element, no matter the left edge proof is existent one or not
- The range has all the elements, the edge proofs can be nil

trie: improve range proof

---

miner/miner.go

```
receiver name should be a reflection of its identity; don't use generic names such as "this" or "self" (ST1006)
```

miner: replace use of 'self' as receiver name

---

core/vm/contract.go

This PR changes how jumpdest analysis is stored: previously, an analysis bitmap was always stored by _either_ by hash in a map, _or_ as a member on the `contract` itself (if it was initcode). 
With this PR, we store it on the object itself, which saves us a map lookup, which actually makes a difference if a lot of looping is done.  
This change was originally part of https://github.com/ethereum/go-ethereum/pull/20787, but since it's not related to `uint256`, we decided to make it a separate PR instead. 
```
name          old time/op    new time/op    delta
SimpleLoop-6     201ms ± 2%     172ms ± 2%  -14.24%  (p=0.000 n=9+8)
name          old alloc/op   new alloc/op   delta
SimpleLoop-6    52.0kB ± 0%    52.0kB ± 0%     ~     (p=1.000 n=10+10)
name          old allocs/op  new allocs/op …
```

core/vm: improve jumpdest lookup

---

cmd/utils/flags.go

This fixes a regression introduced in #20758.

cmd/utils: fix default DNS discovery configuration

---

metrics/prometheus/collector.go
metrics/prometheus/collector_test.go

The integrated Prometheus exporter generates output considered invalid by the `expfmt` parser of the Prometheus common library (v0.9.1):  https://pkg.go.dev/github.com/prometheus/common@v0.9.1
The output at latest master (0b63915430e5921722004345228c5239a8784d6b) looks like this for histograms.
```
test_histogram {quantile="0.5"} 0
test_histogram {quantile="0.75"} 0
test_histogram {quantile="0.95"} 0
```
Applications dependent on `expfmt` package will fail to decode go-ethereum metrics.
This is an error trace seen in the latest InfluxDB 2.0 beta.
```
error	Unable to gather	{"log_id": "0MjOKNZG000", "error": "reading text format failed: text format parsing error in line 4: second TYPE line for metric name \"test_histogram\", or TYPE reported after samples"}
```
The behavior can be traced …

metrics/prometheus: define TYPE once, add tests

---

ethdb/leveldb/leveldb.go

I think it should be a litter better use ```timer``` than ```time.After``` in long term loops.

ethdb/leveldb: use timer instead of time.After

---

consensus/clique/clique.go

unified clique err variable name

unified clique variable name

---

.travis.yml
eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/queue.go

This PR makes use of [go 1.13](https://blog.golang.org/go1.13-errors) error handling, wrapping errors and using `errors.Is` to check a wrapped root-cause. 
It also removes the travis-builders for 1.11 and 1.12. 
OBS: This makes removes suppor for `golang < 1.13` in go-ethereum!
This new error handling in this PR is mainly concerning the downloader, where we previously used one error to cover a multitude of causes, and which makes it a PITA to figure out why our travis tasks fail from time to time.

eth/downloader: more context in errors

---

cmd/geth/main.go
go.mod
go.sum
metrics/cpu_enabled.go

This PR removes any use of the [`gosigar`](https://github.com/elastic/gosigar) library in geth and replaces it with [`gopsutil`](https://github.com/shirou/gopsutil) as `gosigar` is relatively unmaintained and presented a couple issues: 
* building geth with cgo disabled on Darwin would exit with the following errors: 
```bash
../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:20:11: cpuUsage.Get undefined (type Cpu has no field or method Get)
../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:30:13: cpuUsage.Get undefined (type Cpu has no field or method Get)
../../../../pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:49:10: l.Get undefined (type LoadAverage has no field or method Get) …
```

metrics: replace gosigar with gopsutil

---

core/vm/contract.go
core/vm/eips.go
core/vm/errors.go
core/vm/gen_structlog.go
core/vm/instructions.go
core/vm/instructions_test.go
core/vm/interpreter.go
core/vm/logger.go
core/vm/logger_json.go
core/vm/logger_test.go
core/vm/opcodes.go
core/vm/runtime/runtime_test.go
core/vm/stack.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go

Towards an implementation of [EIP-2315](https://eips.ethereum.org/EIPS/eip-2315).  Idea is just to push the PC on a returns stack for a JUMPSUB, and pop it for the RETURNSUB.  The basic logic for the operators is in place, but not the boilerplate of adding a `returns *Stack` argument to every other opcode.  (If that is even a good idea.)  Other stuff is missing, like the stack itself, and what is here is surely buggy.

EIP-2315: JUMPSUB for the EVM

---

p2p/discover/node.go
p2p/discover/v4_lookup_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v4wire/v4wire.go
p2p/discover/v4wire/v4wire_test.go

This moves all v4 protocol definitions to a new package, p2p/discover/v4wire.
The new package will be used for low-level protocol tests.

p2p/discover: move discv4 encoding to new 'v4wire' package

---

rpc/websocket.go

This adds a background loop for websocket connections which pings the server every minute while the connection is idle.
For #21126

rpc: send websocket ping when connection is idle

---

console/bridge.go
console/bridge_test.go

Arguments checks were panicing if the argument was either `null` or `undefined`. This PR adds checks for handling this special case, as well as a couple unit tests to make sure that the panic doesn't occur.
Fixes #21097.

console: handle undefined + null in console funcs

---

core/tx_pool.go

Adjust the position of added newly transactions events in TxPool to reduce the pool lock time

core: collect NewTxsEvent items without holding reorg lock

---

accounts/keystore/keystore.go
cmd/faucet/faucet.go

Twitter swapped their UI to have a React frontend and use an API to retrieve the tweet contents. This broke the faucet because we just scrape to avoid needing an API key. This PR switched over to the non-javascript Twitter site to keep the old functionality going (until they nuke it I guess).
Fixes #21166

acounts/keystore, cmd/faucet: fix faucet double import, fix twitter url

---

accounts/keystore/keystore.go
cmd/faucet/faucet.go

Fixes https://github.com/ethereum/go-ethereum/issues/21166 again.
This PR modified the account import so that if an old account already exists, it at least tells us what the address is. The URL we're not able to return if there are multiple old accounts existing. Maybe in that case we should error out with an even fancier issue, but that's getting even more messy that we currently are.
If there's only one previously existing account, then keystore operations will still succeed without the URL, so that should be fine-ish. This whole scenario is a bit messy tbh.

cmd/faucet: delete old keystore when importing new faucet key

---

node/config.go

Fix typo on node.Config toml tags

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go
console/bridge.go
graphql/graphql.go
internal/ethapi/api.go
rpc/client_test.go
rpc/errors.go
rpc/handler.go
rpc/json.go
rpc/server_test.go
rpc/testservice_test.go
rpc/types.go

Allows to return the proper revert reason for eth_call.
fixes https://github.com/ethereum/go-ethereum/issues/19027
fixes https://github.com/ethereum/go-ethereum/issues/21150
fixes https://github.com/ethereum/go-ethereum/issues/21082
Outputs: 
```
{
"id": 1,
"error": {
"code": -32000,
"message": "some error"
}
}
```

internal/ethapi: return revert reason for eth_call

---

cmd/ethkey/changepassword.go
cmd/ethkey/generate.go
cmd/ethkey/inspect.go
cmd/ethkey/message.go
cmd/ethkey/utils.go

Add the `--passwordfile` flag to the `ethkey generate` keyfile command, the `--passwordfile` is used to make the command non-interactive, e.g.`ethkey generate --privatekey privatekey --passwordfile password.txt`

cmd/ethkey: support --passwordfile in generate command

---

core/state/state_object.go
core/state/statedb.go

Apparently Go's escape analysis is not the brightest tool in the shed. If a method gets a hash/account as a method argument, and the internal `[]byte` representation is accessed within the method via `[:]`, escape analysis faults and the argument will be copied. Within the `state` package, this means that even if we access already cached objects, the method will do an extra allocation because the non-cached path used `[:]`. By changing those invocations into `.Bytes()`, escape faults happen only at those call sites and we avoid the copying the arguments for most cases.
Running the SnailTracer benchmark drives this PR home.
Master:
```
EVM gas used:    1615266220
allocations:     300194
allocated bytes: 134674020
```
PR:
```
EVM gas used:    1615266220
allocations:     2195
allocated …
```

core/state: avoid escape analysis fault when accessing cached state

---

accounts/abi/error.go
accounts/abi/type.go
accounts/abi/unpack.go

Change the private `abi.Type.getType()` method to public.
The `abi.Type.Type` field has been made private in 1.9.14 as the `getType()` method. This breaks some code including the project we were working on which relies on it quite heavily. As this change is keeping backward compatibility and a simple change, I think it is worth it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethereum/go-ethereum/21157)

accounts/abi: make GetType public again

---

eth/downloader/downloader_test.go
miner/worker_test.go

This PR fixes a test that was sometimes failing on travis, example
```
downloader_test.go:686: failed to synchronise blocks: retrieved hash chain is invalid: InsertHeaderChain: unknown parent at first position, parent of number 577
```
I was able to repro it by inserting the following: 
```
func (dl *downloadTester) InsertHeaderChain(headers []*types.Header, checkFreq int) (i int, err error) {
time.Sleep(500 * time.Millisecond)
...
```
It turns out that since we don't have checkpoints, the remote head determined the ancient-limit. So things were written directly to ancients, however, since the insertion of headers vs receipts was a bit racy, it sometimes happened that receipts were written before the next batch of headers arrive.  
When the next batch of headers arrived, we failed to …

eth/downloader: fix spuriously failing tests

---

go.mod
go.sum

It seems the good folks over at `uint256` did a new awesome release: https://github.com/holiman/uint256/releases/tag/v1.1.0 
Got to get some of that goodness!

deps: update uint256 to 1.1.0

---

core/tx_pool.go

Once we detect an invalid transaction during recovering signatures, we should
directly exclude this transaction to avoid validating the signatures hereafter.
This should optimize the validations times of transactions with invalid signatures
to only one time.

core: filter out txs with invalid signatures as soon as possible

---

core/rawdb/freezer_table.go
core/rawdb/freezer_table_test.go

resolve https://github.com/ethereum/go-ethereum/issues/21211

core/rawdb: fix misplaced tailId and itemOffset in freezer

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
eth/api_backend.go
eth/config.go
eth/gen_config.go
internal/ethapi/api.go
internal/ethapi/backend.go
les/api_backend.go

This PR adds a CLI flag to cap the maximum gas price.

cmd, eth, internal, les: add gasprice cap

---

go.mod
go.sum

```Use faster copy when not overlapping #48```
https://github.com/golang/snappy/pull/48
```Faster overlapping copies #49```
https://github.com/golang/snappy/pull/49

go.mod | snappy deps

---

core/rawdb/freezer.go

The ancients variable in the freezer is a list of hashes, which identifies all of the hashes to be frozen. The slice is being allocated with a capacity of `limit`, which is the number of the last block this batch will attempt to add to the freezer. That means we are allocating memory for all of the blocks in the freezer, not just the ones to be added.
If instead we allocate `limit - f.frozen`, we will only allocate enough space for the blocks we're about to add to the freezer. On mainnet this reduces memory usage by about 320 MB.

core/rawdb: Fix high memory usage in freezer

---

p2p/peer.go
p2p/rlpx.go

This is a backport from the `snap` PR. It enabled P2P network packet frequency metrics too, not just combined bandwidth metrics. The goal is to have an insight into latency issues (e.g. fast sync RTT delays) and detect if something is doing crazy networking even if it's not a particular hit on the total traffic.
TL;DR This PR is the first two columns of:

p2p: measure packet throughput too, not just bandwidth

---

cmd/devp2p/keycmd.go
cmd/devp2p/main.go

These commands mirror the key/URL generation functions of cmd/bootnode.
$ devp2p key generate mynode.key
$ devp2p key to-enode mynode.key -ip 203.0.113.21 -tcp 30304
enode://78a7746089baf4b8615f54a5f0b67b22b1...

cmd/devp2p: add commands for node key management

---

crypto/secp256k1/secp256.go

Just the 128bit int change:
```
name       old time/op  new time/op  delta
pkg:github.com/ethereum/go-ethereum/crypto/secp256k1 goos:darwin goarch:amd64
Sign-8      114µs ± 1%    67µs ± 8%  -41.64%  (p=0.000 n=9+10)
Recover-8   203µs ± 2%   115µs ± 1%  -43.59%  (p=0.000 n=9+7)
```
Just the endomorphism change:
```
name       old time/op  new time/op  delta
pkg:github.com/ethereum/go-ethereum/crypto/secp256k1 goos:darwin goarch:amd64
Sign-8                 114µs ± 1%   112µs ± 1%   -1.71%  (p=0.000 n=9+9)
Recover-8              203µs ± 2%   156µs ± 2%  -23.25%  (p=0.000 n=9+10)
```
Both changes:
```
name       old time/op  new time/op  delta
pkg:github.com/ethereum/go-ethereum/crypto/secp256k1 goos:darwin goarch:amd64
Sign-8      114µs ± 1%    63µs ± 7%  -44.66%  (p=0.000 n=9+10)
Recover-8 …
```

crypto/secp256k1: enable 128-bit int code and endomorphism optimization

---

trie/database.go

Currently all preimages are copied twice, once while inserting into the cache and once when we flush the cache to disk.
This PR removes the second copy which reduces allocated memory by quite a bit. 
On my half synced node on goerli the memory allocated at this point was ~190MB.

trie: reduce allocs in insertPreimage

---

core/vm/contracts.go
core/vm/contracts_test.go

During testing on Yolov1 we found that the way geth calculates the discount
is not in line with the specification. Basically what we did is calculate
128 * Bls12381GXMulGas * discount / 1000 whenever we received more than 128 pairs
of values. Correct would be to calculate k * Bls12381... for k > 128.

core/vm: fix incorrect computation of discount

---

cmd/geth/chaincmd.go

The import command should not return a 0 status
code if the import finishes prematurely because
of an import error.
Returning the error causes the program to exit with 1
if the err is non nil.
In case multiple errors are encountered during the import of >1 files, the last is returned (although it doesn't make much of a difference, it just becomes the final error printed on exit).

cmd/geth: import command exit with status code 1 if import returns error

---

docs/_dapp/native-accounts.md

NewManager has a different signature and requires a backend.

Update "Go Account Management" doc

---

cmd/utils/flags.go

Without use of `Global`, these flags didn't actually modify
miner configuration, since we weren't grabbing from the
proper context scope, which should be global (vs. subcommand).

utils: fix ineffectual miner config flags

---

cmd/clef/main.go
cmd/ethkey/changepassword.go
cmd/ethkey/utils.go
cmd/geth/accountcmd.go
cmd/utils/prompt.go
cmd/utils/prompt_test.go

cmd/clef/main.go: line 920
> TODO: there are many `getPassPhrase` functions, it will be better to abstract them into one.
Obviously, there are many `getPassPhrase` functions in:
1. cmd/clef/main.go
2. cmd/geth/accountcmd.go
3. cmd/ethkey/utils.go
I abstract them into one so that makes the code more elegant and concise.
**The new function is in this file: `cmd/utils/prompt.go`.**
*For test:*
``` shell
go test -v cmd/utils/prompt_test.go cmd/utils/prompt.go cmd/utils/cmd.go
```
Thanks for your review!

cmd: abstract `getPassPhrase` functions into one

---

common/math/integer.go
core/tx_list.go
core/tx_list_test.go
core/tx_pool.go
core/types/block.go
core/types/transaction.go
crypto/crypto.go
eth/gasprice/gasprice.go
trie/committer.go
trie/hasher.go

This is a subset of the changes proposed in https://github.com/ethereum/go-ethereum/pull/21232 as 21232 contains some more debatable changes, while all changes in this PR are straightforward. 
The keccak changes for example reduce the following:
```
7258327   73857933 (flat, cum) 13.14% of Total
7258327    7258327    132:func rlpHash(x interface{}) (h common.Hash) {
.    7442671    133:	hw := sha3.NewLegacyKeccak256()
.   44829329    134:	rlp.Encode(hw, x)
.   14327606    135:	hw.Sum(h[:0])
.          .    136:	return h
.          .    137:}
```
to pretty much zero allocations per rlpHash, an improvement by 13%

core: types: less allocations when hashing and tx handling

---

go.mod
go.sum

This PR updates the `golang.org/x/net` and `golang.org/x/crypto` dependencies to prevent build failure

go mod: update golang.org/x/net and golang.org/x/crypto

---

eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/modes.go

There was a race condition between `downloader.synchronize()` and `Progress` `syncWithPeer` `fetchHeight` `findAncestors` and `processHeaders`
This PR changes the behavior of the downloader a bit.
Previously the functions `Progress` `syncWithPeer` `fetchHeight` `findAncestors` and `processHeaders` read the syncMode anew within their loops. Now they read the syncMode at the start of their function and don't change it during their runtime. 
I think this is safe, as we shouldn't switch the syncMode while they are running, and if so we shouldn't react to the switch but keep on running the syncMode that we started with.
cc @mvdan 
(hopefully) fixes https://github.com/ethereum/go-ethereum/issues/21196

eth/downloader: fixes data race between synchronize and other methods

---

rlp/encode.go

In this commit we introduce a pool for listheads which reduces the total allocations from geth during fast sync by ~11%.
This commit has obviously consequences not only for fast sync, fast sync was just the way I benchmarked.
Before this commit:
```
.          .    184:func (w *encbuf) list() *listhead {
200805352  200805352    185:lh := &listhead{offset: len(w.str), size: w.lhsize}
10121      10121    186:w.lheads = append(w.lheads, lh)
.          .    187:return lh
.          .    188:}
```
After:
```
.          .    192:func (w *encbuf) list() *listhead {
.          .    193:lh := listheadPool.Get().(*listhead)
.          .    194:lh.offset = len(w.str)
.          .    195:lh.size = w.lhsize
706        706    196:w.lheads = append(w.lheads, lh)
.          .    197:return lh
. …
```

rlp: pool listheads to reduce allocations

---

common/math/integer.go
core/tx_list.go
core/tx_list_test.go
core/tx_pool.go
core/tx_pool_test.go
core/types/transaction.go

```
BenchmarkPendingDemotion100-16       	 6804576	       173 ns/op	       0 B/op	       0 allocs/op
BenchmarkPendingDemotion1000-16      	 6309848	       174 ns/op	       0 B/op	       0 allocs/op
BenchmarkPendingDemotion10000-16     	 7006021	       176 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion100-16       	358416355	         3.38 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion1000-16      	365451259	         3.37 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion10000-16     	377171361	         3.33 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolBatchInsert100-16       	      38	  27382746 ns/op	  607269 B/op	    8177 allocs/op
BenchmarkPoolBatchInsert1000-16      	       5	 259864088 ns/op	 5861854 B/op	   83225 allocs/op …
```

core, txpool: less allocations when handling transactions

---

cmd/utils/flags.go
core/tx_pool_test.go
eth/api_backend.go
eth/config.go
eth/gen_config.go
internal/ethapi/api.go
internal/ethapi/backend.go
les/api_backend.go

This PR does two things: 
1. make geth use a default rpc gascap of ~~`50M`~~ `25M` gas. To disable it, it needs to be set explicitly to zero. 
2. Make the error message returned to RPC caller friendlier. If the server caps the gas, making something fail, we previously returned e.g. "intrinsic gas too low" (without telling the caller that it's because we capped it). Now we also say what gas was _actually_ used during execution, in that particular case. 
Explicitly set the gas cap:
`build/bin/geth --dev --rpc.gascap 1 --rpc`:
```
[user@work go-ethereum]$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"from": "0x0000000000000000000000000000000000000001", "to":"0x0000000000000000000000000000000000000002", …
```

rpc, internal/ethapi: default rpc gascap at 25M + better error message

---

internal/ethapi/api.go

This PR fixes an error introduced with default rpc gascap, which is very noticable if a LES-server is run. 
Example output, with some extra info in the warnings: 
```
Jul 01 23:23:51 bootnode-aws-eu-west-1-001 geth WARN [07-01|21:23:51.229] Caller gas above allowance[1], capping requested=9223372036854775807 cap=25000000 to=0x9a9070028361F7AAbeB3f2F2Dc07F82C4a98A02a data=0x4d6a304c from=0x0000000000000000000000000000000000000000
Jul 01 23:23:51 bootnode-aws-eu-west-1-001 geth WARN [07-01|21:23:51.246] Caller gas above allowance[1], capping requested=9223372036854775807 cap=25000000 to=0x9a9070028361F7AAbeB3f2F2Dc07F82C4a98A02a data=0x4d6a304c from=0x0000000000000000000000000000000000000000
Jul 01 23:23:51 bootnode-aws-eu-west-1-001 geth WARN [07-01|21:23:51.267] Caller gas above …
```

internal/ethapi: default gas to maxgascap, not max int64

---

console/console.go
internal/ethapi/api.go

This PR is an alternative to https://github.com/ethereum/go-ethereum/pull/21267 . 
It also fixes a flaw in our regexp which failed to prevent `personal.importRawKey` from winding up in the console history. 
Fixes https://github.com/ethereum/go-ethereum/issues/21266
Tests: 
```
> personal.importRawKey("49a7b37aa6f6645917e7b807e9d1c00d4fa71f18343b0d4122a4d2df64dd6fee", "aa")
WARN [06-30|20:34:44.763] Served personal_importRawKey             reqid=9 t="222.009µs" err="local keystore not used"
Error: local keystore not used
at web3.js:6347:37(47)
at web3.js:5081:62(37)
at <eval>:1:22(5)
> personal.unlockAccount("0x8a8eafb1cf62bfbeb1741769dae1a9dd47996192","")
WARN [06-30|20:35:13.851] Served personal_unlockAccount            reqid=10 t="250.828µs" err="local keystore not used"
GoError: Error: …
```

ethapi: don't crash when keystore-specific methods are called but external signer used

---

cmd/geth/chaincmd.go
cmd/geth/main.go
cmd/utils/flags.go
internal/debug/flags.go
metrics/exp/exp.go
mobile/geth.go

ExpVar and Prometheus metrics endpoints were bundled and dependent with `--pprof`.
Since [`--pprof` exposes sensitive/vulnerable behavior](https://blog.ethereum.org/2019/07/10/geth-v1-9-0/#metrics-collection), this change allows the user the configure a metrics endpoint independent of the pprof endpoint.
Adds the following flags:
```go
// MetricsHTTPFlag defines the endpoint for a stand-alone metrics HTTP endpoint.
// Since the pprof service enables sensitive/vulnerable behavior, this allows a user
// to enable a public-OK metrics endpoint without having to worry about ALSO exposing
// other profiling behavior or information.
MetricsHTTPFlag = cli.StringFlag{
Name: "metrics.addr",
Usage: "Enable stand-alone metrics HTTP server listening interface",
Value: "127.0.0.1",
}
MetricsPortFlag = …
```

cmd/geth: allow configuring metrics HTTP server on separate endpoint

---

build/ci.go
internal/build/azure.go

Fixes https://github.com/ethereum/go-ethereum/issues/20855 . Server delivers listings at max 5K items, so we need to iterate to get the full listing. This is a problem, since it makes the 'purge' operation only delete maybe 1K items on every run. Currently, we're at `5604` items that are _not_ supposed to be deleted, so even if we run it multuple times, it's possible that we never actually are able to delete the last items (if the listing only ever shows us 5K non-deletable items).

build/ci: handle split up listing

---

core/types/block_test.go
rlp/encode.go
rlp/encode_test.go
rlp/typecache.go

This change further improves the performance of RLP encoding by removing
allocations for `big.Int` and `[...]byte` types. I have added a new benchmark
that measures RLP encoding of `types.Block` to verify that performance is
improved.
Here are the results as measured on my flimsy 1.2GHz Intel Core m3:
```
name           old time/op    new time/op    delta
EncodeBlock-4    68.6µs ± 6%    50.2µs ± 7%  -26.81%  (p=0.000 n=15+15)
name           old alloc/op   new alloc/op   delta
EncodeBlock-4    9.73kB ± 0%    0.06kB ± 1%  -99.34%  (p=0.000 n=11+15)
name           old allocs/op  new allocs/op  delta
EncodeBlock-4       465 ± 0%         1 ± 0%  -99.78%  (p=0.000 n=15+15)
```

rlp: reduce allocations for big.Int and byte array encoding

---

cmd/utils/flags.go
node/config.go

cmd, node: dump empty value config

---

cmd/clef/README.md

Changes include:
* Updates response docs for `account_new`, `account_list`, `account_signTransaction`
* Removes `account_import`, `account_export` docs
* Adds `account_version` docs
* Updates request docs for `ui_approveListing`, `ui_approveSignData`, `ui_showInfo`, `ui_showError`, `ui_onApprovedTx`
* Adds `ui_approveNewAccount`, `ui_onInputRequired` docs

cmd/clef: Update README with external v6.0.0 & internal v7.0.1 APIs

---

go.mod
go.sum

https://github.com/golang/snappy/pull/53
Tested on an AWS m6g.large (ARMv8.2):
```
name              old time/op    new time/op     delta
WordsDecode1e1-2    29.2ns ± 0%     26.2ns ± 1%   -10.51%  (p=0.000 n=9+10)
WordsDecode1e2-2     187ns ± 0%      107ns ± 0%   -42.78%  (p=0.000 n=7+10)
WordsDecode1e3-2    2.16µs ± 1%     0.95µs ± 0%   -55.85%  (p=0.000 n=10+10)
WordsDecode1e4-2    30.1µs ± 0%     10.4µs ± 2%   -65.40%  (p=0.000 n=10+10)
WordsDecode1e5-2     348µs ± 0%      168µs ± 0%   -51.86%  (p=0.000 n=10+9)
WordsDecode1e6-2    3.47ms ± 0%     1.71ms ± 0%   -50.66%  (p=0.000 n=10+10)
WordsEncode1e1-2    19.4ns ± 0%     21.7ns ± 1%   +12.06%  (p=0.000 n=8+10)
WordsEncode1e2-2    2.09µs ± 0%     0.25µs ± 0%   -88.14%  (p=0.000 n=9+10)
WordsEncode1e3-2    6.67µs ± 1%     2.49µs ± 0% …
```

go.mod: upgrade to github.com/golang/snappy with arm64 asm

---

eth/downloader/downloader.go
eth/downloader/statesync.go

When we restart a statesync, we simply let the old one die, and start a new one. 
In one deferred statement, while the old one is exiting, we mark all active (peers where we have an outstanding request that we're waiting for) as 'idle'. 
The effect of marking it immediately as 'idle' is that the new statesync immediately schedules something for it. Now, in most cases, the peer will actually send something back. When these two conditions are met: 
- The new sync has scheduled a new request, and 
- The previous request is delivered, 
Then we will look at the data, and tag it as 'unexpected'. The (stale) delivery will start the cycle again, since we set it to 'idle' once more, and the whole thing will repeat. Sometimes, when this error occurs, tasks will be rescheduled to other peers, and …

eth/downloader: fix peer idleness tracking when restarting statesync

---

common/math/integer.go

This is a resubmit of https://github.com/ledgerwatch/turbo-geth/pull/556.
The performance benefit of this change is negligible, but it does remove
a TODO.

common/math: use math/bits intrinsics for Safe*

---

README.md
cmd/geth/consolecmd_test.go
cmd/geth/les_test.go
cmd/puppeth/module_explorer.go
cmd/puppeth/module_wallet.go

This PR removes mention and use of deprecated `rpc` and `ws` flags (see #20935) from geth documentation and tests. Removing the use of the deprecated flags will reduce log pollution for the tests and will also prevent the tests from breaking in the future once the flags are fully deprecated and no longer valid command line args.

cmd/geth, cmd/puppeth: replace deprecated rpc and ws flags in tests and docs

---

light/postprocess.go

Fixes a lint regression from #19570

light: goimports -w

---

p2p/discv5/net.go

https://github.com/ethereum/go-ethereum/blob/b8dd0890b3dbc5d3c1b71a0f5de026b46993a851/p2p/discv5/net.go#L1100-L1110
Function `ping` will check the pending `pingEcho` before sending the ping request, current code has the issue of a lot of nodes stuck in `verifyinit` state (does not fallback to `unknown` state) which will lead to the node will have a lot of `deferredQueries` and can not be consumed then lead to the situation of `discv5` package consumes a lot of memory.

p2p/discv5: unset pingEcho on pong timeout

---

README.md

Pkg.go.dev is a new destination for Go discovery & docs, so I updated the link to point to this new location.

README.md: point Go API reference link to pkg.go.dev

---

internal/ethapi/api.go

This extends the txfeecap check to more transaction sending APIs.

internal/ethapi: cap txfee for SignTransaction and Resend

---

p2p/discover/table.go
p2p/discover/table_test.go

This fixes a corner case in discv5. The issue cannot happen in discv4
because it performs IP checks on all incoming node information.

p2p/discover: require table nodes to have an IP

---

cmd/abigen/main.go
cmd/checkpoint-admin/main.go
cmd/clef/README.md
cmd/clef/main.go
cmd/ethkey/main.go
cmd/evm/main.go
cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
internal/flags/helpers.go

This PR updates the flag descriptions in the `README` of clef and also changes the `rpcport` flag to `http.clefport` (since the default is 8550 rather than 8545 as is the default for regular http).
**QUESTION**
Should we allow the legacy flag for port (`rpcport`) to still be valid and hide it when displaying flags with `--help` ?

cmd/clef: change --rpcport to --http.port and update docs

---

core/tx_list.go
core/tx_pool.go
core/tx_pool_test.go

This PR contains some of the commits from the (now reverted) https://github.com/ethereum/go-ethereum/pull/21232 , leaving out the erroneous conversions to `uint64`
```
[user@work core]$ benchstat pool.before pool.after 
name                         old time/op    new time/op    delta
PoolBatchInsert100-6           8.52ms ± 2%    8.50ms ± 2%     ~     (p=1.000 n=5+5)
PoolBatchInsert1000-6          99.2ms ± 1%   101.3ms ± 2%     ~     (p=0.190 n=4+5)
PoolBatchInsert10000-6          1.17s ± 9%     1.17s ±12%     ~     (p=1.000 n=5+5)
PoolBatchLocalInsert100-6       350ms ± 5%      31ms ± 3%  -91.20%  (p=0.008 n=5+5)
PoolBatchLocalInsert1000-6      5.15s ± 8%     0.40s ± 2%  -92.19%  (p=0.016 n=5+4)
PoolBatchLocalInsert10000-6     36.5s ± 2%      3.0s ± 4%  -91.84%  (p=0.036 n=3+5)
name …
```

transaction pool optimizations

---

cmd/evm/internal/t8ntool/flags.go
cmd/evm/internal/t8ntool/transition.go
cmd/evm/main.go
cmd/evm/runner.go
cmd/evm/staterunner.go
core/state/statedb.go
core/vm/contracts.go
core/vm/contracts_test.go
core/vm/evm.go
core/vm/gen_structlog.go
core/vm/instructions.go
core/vm/interface.go
core/vm/interpreter.go
core/vm/logger.go
core/vm/logger_json.go
core/vm/logger_test.go
core/vm/runtime/runtime.go
core/vm/runtime/runtime_test.go
core/vm/stack.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go
trie/secure_trie.go

This PR is a bit experimental, and contains a lot of reductions in allocations. It's based off of five different benchmarks
- Staticcall to identity precompile.
- Call to identity precompile, 
- A pretty 'normal' loop which does nothing other than loop (no calls)
- A 0-value call to an EOA (no code)
- A 0-value call to a contract which immediately reverts
In most cases, allocations could be brought down to a constant, exceptions being call to nonexist and call to reverting, where allocs scale linearly with the number of calls made (however, this PR still reduces the amount by a lot). 
```
[user@work go-ethereum]$ benchstat before.txt after.txt 
name                                   old time/op    new time/op    delta
SimpleLoop/staticcall-identity-100M-6     115ms ± 1%      62ms ± 1% …
```

core/vm: less allocations for various call variants 

---

core/genesis.go

In order to make testing in --dev mode more used, and support more cases, I changed the `gasLimit` in `--dev` mode to 9 milion. Mainnet currenly supports almost 10m, which is much closer to it.

 core: set gasLimit in '--dev' mode to be 9000000

---

accounts/abi/bind/backends/simulated.go
internal/ethapi/api.go

internal, accounts: fix funding check when estimate gas

---

core/vm/eips.go
core/vm/interpreter.go
core/vm/jump_table.go

This is a funky heuristic optimization based on the ideas from https://github.com/ethereum/go-ethereum/pull/21180. I'm not entirely sure why this makes our tight loop faster, but the snail tracer has a 5% speed gain vs master.
I was benchmarking via
```
$ evm --statdump --codefile snailtracer.hex run  1>/dev/null
```
Where the snail tracer is https://gist.github.com/karalabe/dc2fd6add66341c60e7cc96b91ba0f76

core/vm: use pointers to operations vs. copy by value

---

les/api.go
les/clientpool.go
les/clientpool_test.go

In les/clientpool.go:
1. line 53
```go
connectedBias = time.Minute * 3
```
2. line 97
```go
disableBias       bool           // Disable connection bias(used in testing)
```
3. line 282
```go
bias := connectedBias
if f.disableBias {
bias = 0
}
```
Obviously, we can combine the two into one. Here are some explanation:
1.  `time.Duration(0)` means disabled connection bias, other duration means abled connection bias. 
2.  Expose LES api `SetConnectedBias` for configuring the value.
3.  Bias less than zero is illegal.
By this way, the code implements the configuration API elegantly.
*For test:*
```shell
go test -v ./les/
```
Thanks for your review!

les: make clientPool.connectedBias configurable

---

core/types/gen_log_json.go
core/types/log.go
ethclient/ethclient.go
ethclient/ethclient_test.go

https://github.com/ethereum/go-ethereum/issues/21175

ethclient: serialize negative block number as "pending"

---

whisper/whisperv6/whisper_test.go

This PR modifies whisper tests to remove the use of `t.Fatalf` where formatting is not necessary and also includes more information in errors where it is meaningful.

whisper/whisperv6: improve test error messages

---

cmd/utils/flags.go

Fixes https://github.com/ethereum/go-ethereum/pull/21323#issuecomment-661718638.
We've updated the dev mode genesis block to seed some new precompiles. Unfortunately, in dev mode with persistent database we didn't load the genesis from disk, rather always regenerated it and it just happened to match the one on disk. With the changed seeding, any old persisted dev chain became unloadable because of a genesis mismatch.
This PR fixes it by checking the provided data directory for an already initialized chain, and if so, dev mode uses that and does not try to generate a new genesis spec.

cmd/utils: reuse existing genesis in persistent dev mode

---

cmd/geth/usage.go
cmd/utils/flags.go

Prior to this change --dev (developer) mode
generated one account with an empty password,
irrespective of existing --password and --miner.etherbase
options.
This change makes --dev mode compatible with these
existing flags.
--dev mode may now be used in conjunction with
--password and --miner.etherbase flags to configure
the developer faucet using an existing keystore or
in creating a new account.
---
```sh
> cat demo-dev-ks.sh 
#!/usr/bin/env bash
set -x
rm -rf ./ks
mkdir ks
echo "mypassphrase" > pass.txt
./build/bin/geth --keystore=./ks --password=./pass.txt account new
./build/bin/geth --keystore=./ks --password=./pass.txt account new
./build/bin/geth --keystore=./ks --password=./pass.txt account new
addr=$(cat ./ks/* | jq -r '.address' | tail -2 | head -1)
./build/bin/geth --dev …
```

cmd/utils: implement configurable developer (--dev) account options

---

build/ci.go

Fixes this issue:
```
~/d/e/s/g/e/go-ethereum >> make ios
env GO111MODULE=on go run build/ci.go xcode --local
/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/bin
>>> /usr/local/Cellar/go/1.14.4/libexec/bin/go get golang.org/x/mobile/cmd/gomobile golang.org/x/mobile/cmd/gobind
go: found golang.org/x/mobile/cmd/gobind in golang.org/x/mobile v0.0.0-20200721161523-bcce01171201
go: found golang.org/x/mobile/cmd/gomobile in golang.org/x/mobile v0.0.0-20200721161523-bcce01171201
>>> /Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/bin/gomobile init
/Users/fjl/develop/eth/src/github.com/ethereum/go-ethereum/build/bin/gomobile: go install golang.org/x/mobile/cmd/gobind failed: exit status 1
cannot install, GOBIN must be an absolute path
util.go:45: exit status 1 …
```

build: fix GOBIN for gomobile commands

---

mobile/bind.go

This fixes the iOS framework build by naming the second parameter of the
Signer interface method. The name is important because it becomes part
of the objc method signature.
Fixes #21340

mobile: fix build on iOS

---

core/tx_pool.go
core/tx_pool_test.go

This PR is the successor of #21119 by dropping the `beats` field in txpool.
@holiman @villanuevawill Please take a look if the PR is good to you guys.
**If we want to merge this PR, please don't squash into a single commit, would be nice to keep the commit from vill**

core: fix queued transaction eviction

---

cmd/clef/docs/setup.md
cmd/faucet/faucet.html
signer/storage/aes_gcm_storage.go

and Markdown Path correction + html fix

Fix posible nil exeption

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
core/blockchain.go
core/genesis.go
core/state/database.go
eth/api_tracer.go
eth/backend.go
eth/config.go
eth/gen_config.go
light/postprocess.go
trie/database.go

This PR enables the cache dump and reload from a disk journal. 
Accumulate more entries in memory will help us to speed up. However
warm-up the cache can take a few minutes. So disk based journal can help 
a lot.
Besides all entries we maintain in the cache is contract code and trie nodes.
The key of entries is essentially the hash of value. So we can blindly reload the
entries from journal and don't need to take care of the validity of data.

cmd, core, eth, light, trie: dump clean cache periodically

---

cmd/geth/retesteth.go
consensus/clique/api.go
consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/consensus.go
consensus/ethash/ethash.go
consensus/ethash/sealer.go
eth/fetcher/block_fetcher.go
eth/fetcher/block_fetcher_test.go
eth/fetcher/tx_fetcher.go
eth/handler.go
les/client.go
les/client_handler.go
les/clientpool.go
les/fetcher.go
les/fetcher_test.go
les/odr_test.go
les/peer.go
les/server.go
les/server_handler.go
les/test_helper.go
les/utils/expiredvalue.go
les/utils/expiredvalue_test.go

This PR refactors the `light/fetcher` which reuses underlying `eth/fetcher`.
This PR is based on the #19991, would be nice to merge this one first.

les: implement new les fetcher

---

consensus/clique/clique.go
consensus/consensus.go
miner/worker.go

This is a cosmetic update.
+ Update documentation (I hope few updates here are making it more clear)
+ extract common functionality from 2 lengthy functions in `miner/worker.go` - this improves readability and can also help with testing.

Small optimizations

---

eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/peer.go

eth/downloader: remove eth62

---

build/ci.go

Disable symbol table and DWARF generation by default.
Trimpath if compiling with Go >= 1.13
On latest release 1.9.17, this reduces build size by 10MB+
Before:
```
$ ls -lh bin/
38M Jul 25 23:01 geth1.9.17_default
```
After:
```
28M Jul 25 23:11 geth1.9.17_patch
```
Trimpath also enhances privacy by stripping the full path of the source code location.
To see what I mean, run this on the binary:
```
strings geth | grep $(whoami)
```

build: use -trimpath flag when building executables

---

core/tx_pool.go
core/types/transaction.go
core/types/transaction_test.go

This PR changes the sorting of pool transactions with the same gas price.
Previously transactions were sorted randomly (due to the way go maps work).
Now they are sorted by the time that they were added to the mempool in ascending order.
This is supposed to remove the incentive for spamming transactions to backrun a tx (#21350).
---
Potential cons of this solution:
* This provides stronger incentives for miner collusion than the current solution

core: sort txs at the same gas price by received time

---

rpc/client.go
rpc/client_test.go
rpc/http.go

rpc: add SetHeader method to Client

---

signer/core/signed_data.go
signer/core/signed_data_test.go

This seems to be partially fixed by #19303, however the `.validate()` method of `TypedDataDomain` still errors out when there is no chain ID. 
According to [EIP 712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md#definition-of-domainseparator), `chainId` is optional. 
I have removed the non-nil check and changed it so that validate only rejects completely empty domains. Tests included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethereum/go-ethereum/21306)

TypedData.EncodeData should not reject a Domain without a ChainId

---

signer/core/signed_data.go
signer/core/signed_data_internal_test.go

I've come across a lot of input TypedData where bytes and bytesX is encoded as a hex string (`0x...`).
This adds support for parsing those inputs in the `TypedData.EncodePritimitiveValue` method. 
Tests are included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethereum/go-ethereum/21307)

signer: EIP 712, parse `bytes` and `bytesX` as hex strings + correct padding

---

cmd/devp2p/enrcmd.go

Add the last line to what `devp2p enrdump ...` prints:
```
Node ID: 42a31d1a2ab3ad2cf79670255444926a333a3de4259e57d39a387b60b274b982
Record has sequence number 15 and 6 key/value pairs.
"eth"       c7c68480cb8ad480
"id"        "v4"
"ip"        18.211.172.244
"secp256k1" a10361e8a477bdb61e09fc10f43a0a9a139f72282d04ea8f8b4bf341694cc1abb26f
"tcp"       30332
"udp"       30332
URLv4: enode://61e8...3c54fd@18.211.172.244:30302
```

cmd/devp2p: print enode:// URL in enrdump

---

core/tx_pool.go

when runReorg, we may copy the dirtyAccounts' accountSet cache to promoteAddrs
in which accounts will be promoted, however, if we have reset request at the
same time, we may reuse promoteAddrs and modify the cache content which is
against the original intention of accountSet cache. So, we need to make a new
slice here to avoid modify accountSet cache.

core: avoid modification of accountSet cache in tx_pool

---

ethstats/ethstats.go

See  #21403 for more details. This PR adds a mutex around the writes

ethstats: avoid concurrent write on websocket, fixes #21403

---

p2p/nat/nat.go
p2p/nat/natupnp.go

This adds a lock around requests because some routers can't handle
concurrent requests.
Fixes #21370

p2p/nat: limit UPNP request concurrency

---

core/blockchain.go

Often it's useful to wrap errors to provide more contextual information about errors. Go `errors` standard library have few convenient functions to inspect wrapped errors: [errors.Is](https://godoc.org/errors#Is) and [errors.As](https://godoc.org/errors#As).
`consensus` package defines few constant errors (eg `consensus.ErrUnknownAncestor`), which don't carry much information. 
In a fork I'm developing, I'm wrapping errors from `consensus` package, but this breaks some of the `core` functionality, as it is using static checks, which is not very scaleable (functional wise). For start I would like to port some of this changes here and maybe in the future we can wrap errors.

core: use errors.Is for consensus errors check

---

eth/downloader/downloader_test.go

This PR adds baseline tests to the downloader for the eth/65 protocol.

downloader: add eth65 tests

---

cmd/geth/chaincmd.go

cmd/geth: fix import / export issues related to DB unavailability

---

core/vm/contract.go

This change was actually introduced in https://github.com/ethereum/go-ethereum/pull/21123/files , but was lost when subroutines were introduced in https://github.com/ethereum/go-ethereum/commit/cd57d5cd38ef692de8fbedaa56598b4e9fbfbabc#diff-6eafc1c0af4b6eeba491f9b4d56c12b4 .

core/vm: avoid map lookups for accessing jumpdest analysis

---

cmd/geth/chaincmd.go
cmd/geth/config.go

Related to #21412, fixes database unavailability issues stemming from the eth service and <chain command> trying to open node's DB simultaneously.

cmd/geth: fixes db unavailability for chain commands

---

eth/peer.go

The wrong variable was used for limiting maxQueuedTxAnns. At the moment this was fine because both have the same value.

core: Use maxQueuedTxAnns for to limit the number of transactions announced

---

les/checkpointoracle/oracle.go

Whenever a les-client connected to a server, the server internally did an RPC-call on each handshake. This was quite resource intensive, and was fixed  in https://github.com/ethereum/go-ethereum/pull/21285  which prevented it from doing so more than once per minute. 
However, the PR was a bit lacking -- if the call failed, which might be the case during syncing, the fix actually made the situation worse. Not only did it still do RPC request for each handshake, the added lock also forces those rpc requests to be made serially. 
This PR addresses that.

les: update checktime even if check fails

---

eth/downloader/statesync.go

The state sync delivery time was accounted as the time the response reached the trie node data processor. But that's wrong, because the processor might be blocked processing a previous response from someone else. That would mean that with enough load on the processor, the delivery times will get pushed more and more out, causing the RTT calculations to be totally off.

eth/downloader: save the correct delivery time for state sync

---

eth/downloader/statesync.go

Fixes two codepaths missing from https://github.com/ethereum/go-ethereum/pull/21427

eth/downloader: set deliverytime on drops and timeouts too

---

ethstats/ethstats.go

Tiny change, fixes a corner-case in ethstats. If there are multiple URLs, and the first one(s) fail, but a later one works, the first error will prevail and prevent the connection from being established.

ethstats: overwrite old errors

---

eth/downloader/statesync.go

There's an issue in statesync, which can cause the `spindown` to become blocked. Example trace: 
```
goroutine 61 [select, 25 minutes]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spindownStateSync(0xc003576000, 0xc011a80c88, 0xc050990000, 0xf3, 0x100, 0xc15126c3c0, 0xc0ee278ae0)
github.com/ethereum/go-ethereum/eth/downloader/statesync.go:226 +0x298
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).runStateSync(0xc003576000, 0xc125033f40, 0x0)
github.com/ethereum/go-ethereum/eth/downloader/statesync.go:131 +0x1002
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).stateFetcher(0xc003576000)
github.com/ethereum/go-ethereum/eth/downloader/statesync.go:85 +0x47
created by github.com/ethereum/go-ethereum/eth/downloader.New …
```

eth/downloader: allow all timers to exit

---

tests/init.go

Both parity and nethermind defined yolob1 as `Berlin`, so this PR enables us to run the same statetests (for fuzzing)

tests: add Berlin-definition identical to YOLOv1

---

cmd/geth/les_test.go

This happens from time to time: https://travis-ci.org/github/ethereum/go-ethereum/jobs/714468056#L853  . 
I think it's simply that the les server hasn't had time to kick the previous les client out, so this PR adds a little wait before checking it. This PR also removes usb, and and skips starting HTTP uselessly (since the tests uses the ipc pipe anyway)

cmd/geth/tests: try to fix spurious travis failure in les tests

---

cmd/evm/README.md
cmd/evm/internal/t8ntool/execution.go
cmd/evm/internal/t8ntool/flags.go
cmd/evm/internal/t8ntool/transition.go
cmd/evm/main.go
cmd/evm/transition-test.sh

This PR adds two features requested in https://github.com/ethereum/go-ethereum/issues/21373 
- output basedir, 
- txhash into the name of the tracefile
Closes #21373

cmd/evm: statet8n output folder + tx hashes on trace filenames

---

core/blockchain.go
core/blockchain_repair_test.go
core/blockchain_rollback_test.go
core/blockchain_sethead_test.go
core/blockchain_test.go
core/headerchain.go
core/rawdb/accessors_chain.go
core/rawdb/database.go
core/rawdb/freezer.go
core/rawdb/schema.go
eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/sync.go
trie/sync.go

This PR is a major tech debt repayment. Over the years we kept hacking in various logic into Geth as to what happens when some blocks need to be deleted (fast sync rollback, crash recovery, user sethead). Fast sync rollbacks worked fine since their use was limited. Crash recovery generally worked ok, unless you underflown into the freezer. SetHead was a Russian roulette.
This PR bites the bullet and sorts this issue out by writing up a gigantic test suite with all the possible state combinations from which Geth might want to rewind it's chain and what the expected result is. The PR also unifies the 3 different rollback methods (which just for the fun of it used one another), and rather makes a single `SetHead` that works for every use case. The PR ended up fixing a significant number of …

core: define and test chain reparation cornercases

---

metrics/meter.go
metrics/meter_test.go

Previously the temp variable was not updated properly after summing it to count.
This meant we had astronomically high metrics, now we zero out the temp whenever we
sum it onto the snapshot count
fixes a bug introduced in https://github.com/ethereum/go-ethereum/pull/21446

metrics: zero temp variable in  updateMeter

---

eth/downloader/downloader.go
eth/handler.go
trie/sync_bloom.go

This PR is an experiment. While syncing, there's an immense read-pressure on the filesystem, especially when the node has a lot of peers. 
The read-preesure comes from
- processing children of state-responses. For each `state`, it needs to lookup if the child hashes exist. 
- processing `getNodeData` from peers. Each peer may have up to send up to `384` outstanding lookups. These are handled sequentially in the eth/handler.go. 
This PR uses the `stateBloom` filter that's already used by the sync, to avoid lookups to disk in the cases where we do not have the hash. Judging from some of the graphs, it looks like non-existing lookups account for ~50% of all `getNodeData` lookups (the number _will_ vary wildly based on how far along the sync process is)

eth/downloader, eth/handler: utilize sync bloom for getNodeData

---

core/state/snapshot/generate.go
core/state/snapshot/journal.go
core/state/snapshot/snapshot.go

The snapshotter operates on state (roots) and is oblivious to blocks. This is needed because there's really no notion of a block inside the state snapshot or the statedb and introducing them would make things extremely messy. This however creates a weird corner case:
- The state GC operates on blocks and dereferences state that is 128 blocks old.
- The snapshotter operates on states and flattens state that is 128 depths old.
If two blocks have the same state root (Clique empty block), these two 128 concepts will go out of sync. The snapshotter will still maintain 128 unique states, but that will correspond to more than 128 blocks. Essentially the snapshotter's disk layer will reference state that does not exist in trie form any more.
This is completely fine in normal mode of operation. …

core/state/snapshot: reduce disk layer depth during generation

---

core/rawdb/freezer_table.go

When we originally implemented the freezer, it was disallowed to roll back items from it. In theory Geth will never do it itself during normal mode of operation, but in practice the user can call SetHead and Geth can roll back during fast sync. With the unified rollback handling, all these paths use the same code that printed the warning. This resulted in 2000 truncation warnings printed every time fast sync failed (2K headers rolled back).
This PR changes the behavior so that if only a single item is removed (SetHead will remove one-by-one since it needs to do additional maintenance after each), the log level is Debug, not Warn. If the freezer gets corrupted and a lot of data is removed we will still see the large truncation warnings.

core/rawdb: only complain loudly if truncating many items

---

graphql/graphql.go
graphql/schema.go

example
```graphql
query {
chainID
}
```

graphql: add query for chainID

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go

fixes https://github.com/ethereum/go-ethereum/issues/16655
In this PR we change the way AdjustTime works on the simulated backend. Previously you could adjust the timestamp of a pending block that has transactions in it. This PR disallows this. If you want to adjust the time, call AdjustTime and `sim.Commit()` to apply the adjustment.

accounts/abi/bind/backends: Disallow AdjustTime for non-empty blocks

---

core/state/statedb.go
core/state/sync.go
eth/downloader/downloader.go
trie/committer.go
trie/sync.go
trie/trie.go
trie/trie_test.go

We've seen for a while that the bootnodes go OOM while fast syncing. Lately this became more and more pronounced, so it was clear that we have some memory issues in state sync. This PR addresses 3 independent issues:
- State sync expands the account and storage tries depth first. This ensures that we keep as little of it in memory as possible and flush completed subtries to disk quickly. In the case of the bootnodes however, they are running with 250 full node peers. Even though the trie.Sync is depth first, with so many peers available to retrieve from, the trie got expanded too heavily breadth wise too. This resulted in a notable memory usage.
- The PR fixes this by limiting each state trie depth to a maximum of 16K active fetches. This way at worse we can have 128 (64 account + 64 …

core/state, eth, trie: stabilize memory use, fix memory leak

---

accounts/abi/type.go
accounts/abi/type_test.go

e.g. for "Tuple[2]" type, the element of the array is a tuple type and the size of the tuple may not be 32.

accounts/abi: fix a bug in getTypeSize method

---

console/bridge.go

Fixes #21417 - console call `personal.sign()` is bridged incorrectly to `unlockAccount()`.

internal: fix personal.sign()

---

eth/downloader/queue.go

I think this info is more a DEBUG related information then an INFO, and it is for me a little bit annoying to have that so often during syncronization. If it must remains an INFO, maybe it can be slow down to a print every 5-10 minutes or so.

"Downloader queue stats" is now provided once per minute

---

go.mod
go.sum

1. Initialise Function.prototype also when it's being set or deleted. Fixes https://github.com/dop251/goja/commit/3d32615791671be7e2cfb6f08f7872d8de0961c5
2. Made nested structs addressable if possible. Closes https://github.com/dop251/goja/commit/ebfbf88ae3f7b4d3929fad07fdaf3001cbcf209a
3. Fixed objectGoSliceReflect.getStr() and delete(). https://github.com/dop251/goja/commit/c3769ba23d73e45c74bd7cfa22029bd09714d4cf
4. [fea] add push support for goslice_reflect object https://github.com/dop251/goja/commit/794ceddc9009ebc03e7cc178973f3288a589cdce
5. Use strings.Trim instead of regex to trim unicodeString https://github.com/dop251/goja/commit/7bb4acfa4c6ef02f47bdac4f7dc3d5ef5dec4ac5
6. Array.prototype.sort(): correctly handle float return value …

go.mod: goja update

---

eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/queue.go
eth/downloader/queue_test.go
eth/downloader/testchain_test.go

This changes how the downloader works, a  little bit. Previously, when block sync started, we immediately started filling up to 8192 blocks. Usually this is fine, blocks are small in the early numbers. The threshold then is lowered as we measure the size of the blocks that are filled. 
However, if the node is shut down and restarts syncing while we're in a heavy segment, that might be bad.  This PR introduces a more conservative initial threshold of 2K blocks instead.

eth/downloader: change intial download size

---

core/state/sync_test.go
eth/downloader/statesync.go
trie/secure_trie.go
trie/sync.go
trie/sync_test.go
trie/trie.go

This is a small prep PR that separates trie node and byte code scheduling in `trie.Sync` and also starts tracking the Merkle paths belonging to a specific trie request. The goal is to prepare the code for `snap` sync, which has these two concepts separated and will also work on trie paths, not on hashes.
The "paths" pointing to a specific trie node (returned by `trie.Sync.Missing`) are either 1-tuple if the trie node belongs to the account trie; or a 2-tuple if it's a storage trie node. Partial paths (i.e. last items of both tuples) are stored in compact-encoded form, since they need to be able to represent odd nibbles. The first item of the 2-tuple (account hash) is simple binary encoding because we know it's always 32 bytes.
The reason for using 2-tuple instead of 1 long concatenated …

core, eth, trie: prepare trie sync for path based operation

---

eth/api.go
eth/api_tracer.go
internal/web3ext/web3ext.go

fixes https://github.com/ethereum/go-ethereum/issues/20515
The `debug_traceCall` method lets you run an `eth_call` on top of a given block. The block can be specified either by hash or by number. It takes the same input object as a eth_call.
It returns the same output as `debug_traceTransaction`. A tracer can be specified as a third argument, similar to `debug_traceTransaction`.
`Object` - The transaction call object
- `from`: `DATA`, 20 Bytes - (optional) The address the transaction is sent from.
- `to`: `DATA`, 20 Bytes - The address the transaction is directed to.
- `gas`: `QUANTITY` - (optional) Integer of the gas provided for the transaction execution. eth_call consumes zero gas, but this parameter may be needed by some executions.
- `gasPrice`: `QUANTITY` - (optional) Integer of the …

eth: added trace_call to trace on top of arbitrary blocks

---

accounts/usbwallet/wallet.go
signer/core/api.go

The derivation path used by ledger was changed, at some point, from being on the form 
`m/44'/60'/0'/0` into `m/44'/60'/0'/0/0`. 
This was also changed in geth, and the self-derivation added in https://github.com/ethereum/go-ethereum/pull/19438 was clever enough 
to use a chainreader: if it found that accounts on the old path were non-zero, then it kept deriving them. 
However, that doesn't work well in an offline-ish mode, or in conjunction with `clef`. 
This PR modifies it so that 
- For `geth`, the first will-be-skipped account is displayed in the log, so the user can more easily manually add/use the account.
- For `clef`, instead of deriving `10` default paths, we import `5` default and `5` legacy.
geth output:
```
> INFO [09-04|19:36:47.421] New wallet appeared …
```

accounts/usbwallet, signer/core: show accounts from ledger legacy derivation paths

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go

fixes some stylistic choices introduced in https://github.com/ethereum/go-ethereum/pull/21514

accounts/abi/bind/backends: reverted some stylistic changes

---

eth/downloader/downloader.go
eth/downloader/downloader_test.go

Fixes https://github.com/ethereum/go-ethereum/issues/21505.
There is a notion of rollbacks during fast sync, where recent blocks that might not be clean are deleted from the database on a sync failure. This is needed to avoid attacks on fast sync since we're not running transactions.
For light sync however, rollbacks are pointless because there's no batch of full blocks imported on top to validate them. As long as the PoW checks out, light clients will take the node's word for it.
This PR disables the rollback mechanism for light syncs, which was causing crashes in the light txpool due to deleting headers that it imported before. Interestingly, the issue was that the rollback mechanism wasn't disabled after initial sync (opposed to fast sync switching to full sync).

eth/downloader: only roll back light sync if not fully validating

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
eth/config.go
eth/gasprice/gasprice.go

cmd, eth: offer maxprice flag for overwritting price cap

---

go.mod

golang.org/x/sync is not used in this module.
Run `go mod tidy`

go.mod: remove golang.org/x/sync

---

ethclient/ethclient.go

This adds a new client method `BlockNumber` to fetch the most recent block number off the chain

ethclient: add BlockNumber method

---

cmd/geth/config.go

cmd/geth: print warning when whisper config is present in toml

---

miner/miner.go
miner/miner_test.go
miner/worker.go

This PR changes several different things:
* Adds test cases for the miner loop
* Stops the worker if it wasn't already stopped in `worker.Close()`
* Uses channels instead of atomics in the `miner.update()` loop

miner: use channels instead of atomics in update loop

---

miner/miner.go
miner/miner_test.go

fixes a regression introduced in https://github.com/ethereum/go-ethereum/pull/21536

miner: fix regression, add test for starting while download

---

Dockerfile
Dockerfile.alltools

graphql server uses 8545 port which shared with http jsonrpc server since v1.9.19

dockerfile: remove 8547 port

---

les/lespay/client/fillset_test.go
les/serverpool.go
p2p/nodestate/nodestate.go
p2p/nodestate/nodestate_test.go

This PR adds an extra guarantee to NodeStateMachine: it ensures that all immediate effects of a certain change are processed before any subsequent effects of any of the immediate effects on the same node. In the original version, if a cascaded change caused a subscription callback to be called multiple times for the same node then these calls might have happened in a wrong chronological order.
For example:
- a subscription to `flag0` changes `flag1` and `flag2`
- a subscription to `flag1` changes `flag3`
- a subscription to `flag1`, `flag2` and `flag3` was called in the following order:
- `[flag1]` -> `[flag1, flag3]`
- `[]` -> `[flag1]`
- `[flag1, flag3]` -> `[flag1, flag2, flag3]`
This happened because the tree of changes was traversed in a "depth-first order". Now it is traversed in a …

p2p/nodestate: ensure correct callback order

---

eth/tracers/internal/tracers/call_tracer.js

Added the fields `to`, `from` and `value` to the tracer when the op is `SELFDESTRUCT`. This lets us figure out how much ETH was self destructed and helps with accounting. 
Example of trace before:
```
{
"type":"CREATE",
"from":"0x874b54a8bd152966d63f706bae1ffeb0411921e5",
"to":"0xf191a640b0bfeb316cf3df5961896d502445414d",
"value":"0x1",
"gas":"0x3c0c4",
"gasUsed":"0x7533",
"input":"0x60fdff61000080610011600039610011565b6000f3",
"output":"0x",
"time":"79.869µs",
"calls":[
{
"type":"SELFDESTRUCT"
}
]
}
```
Example of trace after:
```
{
"type":"CREATE",
"from":"0x874b54a8bd152966d63f706bae1ffeb0411921e5",
"to":"0xf191a640b0bfeb316cf3df5961896d502445414d",
"value":"0x1",
"gas":"0x3c0c4",
"gasUsed":"0x7533",
"input":"0x60fdff61000080610011600039610011565b6000f3",
"output":"0x", …
```

Updated call_tracer to be more descriptive

---

rlp/raw.go
rlp/raw_test.go

This can be useful when working with raw RLP data. I want this function because the rules around integers in RLP are too complicated to just use `SplitString` and decode the resulting byte slice.

rlp: add SplitUint64

---

COPYING

When the license was added to the repository, its text was changed (some
sections at the end removed) and, worse, the authors of go-ethereum
tried to claim copyright on the license text.
The correct way to apply GPL to a project is to copy it verbatim.
This change reverts the text of the GPL to the original.
Fixes #21567.

COYPING: restore the full text text of GPL

---

core/blockchain.go
core/rawdb/accessors_indexes.go
core/rawdb/accessors_indexes_test.go
core/rawdb/chain_iterator.go
light/txpool.go

With this PR there's only a single function for writing the tx lookup index, and another one for deleting. Also, to be coherent with the others reading and writing db helper functions, the default function names mean now _by hash_ while _by block_ must be now explicit.

Single point of maintenance for writing and deleting tx lookup indexes

---

params/config.go
params/config_test.go

...if it is at the same block as ConstantinopleBlock
This is to enable private chains running on older Geth release `1.8.27` with `Constantinople` fork enabled (but not `Petersburg`) to apply `Petersburg` retroactively when upgrading to Geth 1.9.
Reference comments in another PR that was raised originally: https://github.com/ethereum/go-ethereum/pull/21447

Allow setting PetersburgBlock before chain head

---

cmd/utils/flags.go

closes https://github.com/ethereum/go-ethereum/issues/21560

cmd/utils: use preconfigured testnet flags instead of networkid

---

core/rawdb/database.go

Add counters to the stats from inspect command.
These counters are useful to better understand what's inside LevelDB and they can be useful to better answer some recurrent questions about geth stats like _how many state entries I must download before having a synced full node_? (see https://github.com/ethereum/go-ethereum/issues/14647)
This is a preview of the output, based on a goerli synced full node:
```zsh
❯ ./build/bin/geth --goerli inspect
INFO [08-27|13:51:50.845] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-27|13:51:50.845] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-27|13:51:50.848] Set global gas cap                       cap=25000000
INFO [08-27|13:51:50.848] Allocated cache and file …
```

cmd/geth: added counters to the geth inspect report

---

eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/testchain_test.go

When we've implemented fast sync, we picked a static pivot block and kept it indefinitely. This worked well because we didn't have state pruning, and any (recent) block we picked, it was sure to remain available until we finished syncing.
Eventually we've implemented in-memory GC, which caused stale state to gradually disappear from the network. Although the head of the state trie was garbage collected quote fast (15 mins), most of the trie remained constant throughout sync. Thus it was fine to pick a static pivot block, keep syncing that, and only dynamically bump it when we've approached the chain head. This could be done via an easy hack where the block collector pushes the pivot forward if it accumulates more than 64 blocks after the old pivot.
Unfortunately, with snap sync, the …

eth/downloader: dynamically move pivot even during chain sync

---

cmd/clef/main.go
cmd/geth/retesteth.go
cmd/utils/customflags.go
cmd/utils/flags.go

Reuse some functions.
Thanks for your review!

cmd/clef, cmd/geth: use SplitAndTrim from cmd/utils

---

trie/proof_test.go

Fixes https://travis-ci.org/github/ethereum/go-ethereum/jobs/720766814

trie: fix bad range proof

---

trie/proof.go
trie/proof_test.go

This PR adds the support for empty range proof.

trie: support empty range proof

---

internal/ethapi/api.go

This PR adds an optional parameter to EstimateGas to be in lne with the json-rpc specification.
Now you can choose to estimate your gas usage based on the pending block or the latest block, which ever might suite you best.
The JSON RPC spec of this API is
eth_estimateGas
Generates and returns an estimate of how much gas is necessary to allow the transaction to complete.
**Parameters**
**1. Object** - The transaction call object
`from`: DATA, 20 Bytes - The address the transaction is sent from.
`to`: DATA, 20 Bytes - (optional) The address the transaction is directed to.
`gas`: QUANTITY - (optional) Integer of the gas provided for the transaction execution. eth_call consumes zero gas, but this parameter may be needed by some executions.
`gasPrice`: QUANTITY - (optional) Integer of the …

internal/ethapi: add optional parameter blockNrOrHash to estimateGas

---

trie/proof.go
trie/proof_test.go

This PR extends the range proof. Now both edge proofs are allowed to be non-existent proof.
It means, whatever the edge keys are selected(e.g. first as `0x0000...0000`, last as `0xffff...ffff`), then give the batch in this range, we can always prove the correctness.

trie: extend range proof

---

cmd/devp2p/internal/ethtest/chain.go
cmd/devp2p/internal/ethtest/suite.go
cmd/devp2p/internal/ethtest/types.go
cmd/devp2p/main.go
cmd/devp2p/rlpxcmd.go
core/forkid/forkid.go
core/forkid/forkid_test.go
eth/discovery.go
eth/handler.go
eth/helper_test.go
eth/protocol_test.go

This PR adds a test framework for the eth protocol, with the following basic tests: 
- `GetBlockBodies`
- `GetBlockHeaders`
- `Status`
- `Ping`
- and a block propagation test `Broadcast`

cmd/devp2p: add eth protocol test suite

---

cmd/devp2p/internal/ethtest/suite.go

Lower eth protocol version from 65 to 64 to allow openethereum support.

cmd/devp2p/internal/ethtest: lower protocol version to 64

---

params/config.go

Unfortunately left Ropsten out. There's no LES server publicly available and I don't want to hold up the release while we sync a full Ropsten node.

params: update CHTs for Geth v1.9.22

---

mobile/big.go

closes https://github.com/ethereum/go-ethereum/issues/16364
Usage:
```java
BigInt b = new BigInt("1234", 10);
log(b.toString());
```

mobile: added constructor for big int

---

core/vm/gas_table.go
params/protocol_params.go

This PR removes some composite variables we had laying around, concerning EIP-2200. The [spec](https://eips.ethereum.org/EIPS/eip-2200) only defines four variables: 
```
SLOAD_GAS: changed from 200 to 800.
SSTORE_SET_GAS: 20000, not changed.
SSTORE_RESET_GAS: 5000, not changed.
SSTORE_CLEARS_SCHEDULE: 15000, not changed.
```
Our implementation was based on an older version of net-sstore-gas-metering, or, well, for whatever reason used composite variables. When implementing eip-2929, this composition caused problems -- and generally doesn't really make sense (since the compiler can synthesize constants for us).

core/vm, params: make 2200 in line with spec

---

core/tx_list.go

As per the documentation for golang heap, heap Pop can cause a memory leak if the element that is returned is a pointer and is not set to nil. This causes the pointer to be held by the underlying array, such that it cannot be garbage collected.

eth, core: free pointer from slice after popping element from price heap

---

internal/web3ext/web3ext.go

1. let `eth_getBlockByNumber` and `eth_getBlockByNumber` support default value of the second param 
2. format the first param of `eth_getBlockByNumber`
let them have the same behaver as `getBlock` in web3.js

internal/web3ext: improve eth_getBlockByNumber and eth_getBlockByHash api

---

Makefile
build/ci.go

closes https://github.com/ethereum/go-ethereum/issues/16127
closes https://github.com/ethereum/go-ethereum/issues/20941
Build the .aar and -sources.jar locally using `make android` and include them in your project.
See https://stackoverflow.com/questions/20994336/android-studio-how-to-attach-javadoc

build: keep geth-sources.jar build result for JavaDoc

---

core/block_validator.go
core/types/derive_sha.go
eth/downloader/queue.go
eth/handler.go
trie/database.go
trie/encoding.go
trie/encoding_test.go
trie/stacktrie.go
trie/stacktrie_test.go

This has the updated version of stacktrie, with `Commit`.

trie: Derivesha with stacktrie

---

trie/committer.go
trie/hasher.go
trie/trie.go
trie/trie_test.go

This RP contains some polish for trie committer.

trie: polish committer

---

trie/trie_test.go

We recently merged the stacktrie, to hash elements in a trie in a more memory friendly manner. The stacktrie has support for Commit, shoving nodes into a database, which we are currently not using. 
However, we didn't have any good tests for commit-sequences, until I added them in https://github.com/ethereum/go-ethereum/pull/21351 . This PR extends the commit-sequence tests to also cover the stacktrie.

trie: add Commit-sequence tests for stacktrie commit

---

core/state/snapshot/generate.go
core/state/snapshot/generate_test.go

The snapshot generator failed to check for errors returned by the account and storage trie iterators, so a missing trie node would go unnoticed and the gap incorporated into the snapshot. Since there's no way to recover from a missing trie node, one possibility is to stop the generator and run without snapshots (eventually failing anyway) or alternatively stop Geth altogether. 
Although the second solution seems saner (and was also my first choice), it is much riskier in case of a code bug, which could result in Geth terminating. This PR thus went with simply printing an error and suspending generation. It is expected that generation will resume after every new block and error the same way. It will result in a nasty slew of Error messages for the user, but their Geth node would remain …

core/state/snapshot: stop generator if it hits missing trie nodes

---

core/bloombits/generator.go
core/bloombits/generator_test.go

This PR optimizes the bloombit generator a bit. It unrolls a loop and avoids branching on every potential setting of a bit. 
EDIT: It also performs drastically better when blooms are less saturated
```
name                old time/op    new time/op    delta
Generator/empty-6     7.72ms ± 1%    0.91ms ± 3%  -88.27%  (p=0.000 n=9+8)
Generator/random-6    28.9ms ± 1%    15.2ms ± 1%  -47.44%  (p=0.000 n=9+9)
```
The existing testcase was pretty good. I tested with some intentional (and unintentional) errors, and each one was immediately detected.

core/bloombits: faster generator

---

core/types/bloom9.go
core/types/bloom9_test.go

This supersedes #21616 and closes #18092
The bloom filter was very suboptimal, and more or less broken. 
```
name                 old time/op    new time/op    delta
Bloom9-6               1.41µs ±17%    0.09µs ±10%  -93.75%  (p=0.008 n=5+5)
Bloom9Lookup-6         1.75µs ±15%    0.69µs ± 5%  -60.45%  (p=0.008 n=5+5)
CreateBloom/small-6    7.29µs ± 4%    2.86µs ± 0%  -60.76%  (p=0.016 n=5+4)
CreateBloom/large-6     701µs ±20%     280µs ± 2%  -59.96%  (p=0.008 n=5+5)
name                 old alloc/op   new alloc/op   delta
CreateBloom/small-6    7.50kB ± 0%    0.26kB ± 0%  -96.48%  (p=0.008 n=5+5)
CreateBloom/large-6     676kB ± 0%      26kB ± 0%  -96.21%  (p=0.008 n=5+5)
name                 old allocs/op  new allocs/op  delta
CreateBloom/small-6      58.0 ± 0%       9.0 ± 0%  -84.48% …
```

core/types: optimize bloom filters

---

signer/core/api.go

Now using empty lists instead of `nil` solves #21674

signer/core: don't mismatch reject and no accounts

---

p2p/discover/v5_encoding.go

For some reason, using the shared hash causes a cryptographic
incompatibility when using Go 1.15. I noticed this during the
development of Discovery v5.1 when I added test vector verification.
This is a temporary fix. There is nothing wrong with it, it's just a
tiny bit slower than before.

p2p/discover: remove use of shared hash instance for key derivation

---

eth/downloader/downloader.go

Fixes #21557
`AncientLimit` in downloader is only used in `FAST SYNC`. However, during the fast sync setup, we will reassign the value anyway. So cleanup is meaningless and can cause data race. So this PR removes the cleanup logic.

eth/downloader: fix data race around the ancientlimit

---

eth/downloader/queue.go

This pr speeds up fast sync by ~3% for me. Additional benching would be good.

eth/downloader: cache parent hash instead of recomputing

---

core/tx_pool.go

As reported by Hwanjo Heo, there is an off-by-one error when blending the new-errors into the error-slice in the txpool.

core/tx_pool: fix off-by-one error

---

accounts/accounts.go
accounts/scwallet/wallet.go
accounts/usbwallet/wallet.go
consensus/clique/snapshot_test.go
core/state/state_object.go

accounts, consensus, core: fix some typos in comments

---

console/bridge.go

The first time `lastNumber` is assigned with an actual block number should not count.
Fixes #21621

console: fix admin.sleepBlocks() call

---

accounts/keystore/file_cache.go
core/chain_indexer.go
eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/helper_test.go
les/txrelay.go
miner/unconfirmed.go

These RWMutex are not use `RLock()`, they are only use `Lock()`, so replace them with `Mutex`

all: replace RWMutex with Mutex in places where RLock is not used

---

consensus/clique/clique.go

1. the `func CalcDifficulty` method is only used in it's own package, so change the scope to it's own package.
2. the comment is the same as the `ethash` package previously,  modify it as the `clique` algorithm discribed.

consensus/clique: unexport calcDifficulty and improve comment

---

trie/stacktrie.go

This PR fixes an issue found by @rjl493456442 , where stacktrie can become corrupted if used in parallel. This happens since the `child` is returned _before_ the rlp-encoding (https://github.com/ethereum/go-ethereum/blob/45a46b82218536ffe20d635d7f2c6ff30ce46379/trie/stacktrie.go#L313)  is finished, when a fullnode is processed: https://github.com/ethereum/go-ethereum/blob/45a46b82218536ffe20d635d7f2c6ff30ce46379/trie/stacktrie.go#L307 
A paralell stacktrie may write into the same underlying slice, right before the rlp-encoding has begun. 
This PR fixes that by not reusing the `val` slice

trie: fix flaw in stacktrie pool reuse

---

internal/web3ext/web3ext.go

this PR improves some api and fix a bug:
1. improve some param's input format, let them support `Number`. 
2. fix a tiny typo:  `inputFormatters `->`inputFormatter`
3. improve `debug_printBlock ` output.
before change, the `debug_printBlock` output: 
```
> debug.printBlock(2)
"(*types.Block)(0xc0000beea0)({\n header: (*types.Header)(0xc0010706c0)({\n  ParentHash: (common.Hash) (len=32 cap=32) 0x6ccfac8baea9c2829d9e302403c4a3523504fe088ee3a860e6ee4536d0c92888,\n  UncleHash: (common.Hash) (len=32 cap=32) 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347,\n
......
```
after change: 
```
> debug.printBlock(2)
(*types.Block)(0xc041222000)({
header: (*types.Header)(0xc04121e480)({
ParentHash: (common.Hash) (len=32 cap=32) …
```

internal/web3ext: improve some web3 apis

---

miner/miner.go
miner/miner_test.go

Alternative version of https://github.com/ethereum/go-ethereum/pull/21653 , which does not have the double-select loop.

miner: don't interrupt mining after successful sync

---

accounts/keystore/keystore_test.go

The TestWalletNotifications test sporadically fails on travis.
This is because we shutdown the event collection before all events are received.
~~Adding a small timeout (10 milliseconds) allows the collector to be scheduled
and to consume all pending events before we shut it down.~~
ex: https://travis-ci.org/github/ethereum/go-ethereum/jobs/733709675

accounts/keystore: add timeout to test to prevent failure on travis

---

miner/miner.go
miner/miner_test.go

When restarting a goerli signer, we got this: 
```
Oct 14 10:45:54 goerli-aws-eu-west-2-001 geth ERROR[10-14|08:45:54.089] Refusing to mine without etherbase 
```
I think the underlying cause is that the miner had a regression: in case mining wasn't possible (due to sync), the etherbase was not set. This PR fixes it and adds a testcase. 
This could have more severe consequences: if the etherbase is initially set to something, and changed to something else _while sync is in progress_ , the latter 'set' is ignored, and the original is kept.

miner: set etherbase even if mining isn't possible at the moment

---

core/vm/gen_structlog.go
core/vm/logger.go

closes https://github.com/ethereum/go-ethereum/issues/21709

core/vm: marshall returnData as hexstring in trace logs

---

cmd/geth/consolecmd_test.go
console/console.go

This PR adds an interrupt counter to the local console so that one `^C` will cause the console to be cleared, but two `^C`s in a row will cause console termination.

console: don't exit on ctrl-c, only on ctrl-d

---

miner/miner_test.go

Previously this test helper contained a race condition.
Also it used clique in the chainconfig but ethash as an engine, which was strange.
It now uses the same chainconfig everywhere which mitigates the race.

miner: fixed race condition on chainconfig

---

core/blockchain.go
core/rawdb/chain_iterator.go
core/rawdb/chain_iterator_test.go

This PR tracks the background transaction indexer into the wait group for better exception handling.
Besides, this PR makes the `indexing` and `unindexing` stoppable. 
Also it improves the `unindexing` a bit. Originally `unindexing` will tag the tail to the given parameters
and then unindex transactions out of order. Now it's changed. All unindexing operations are sorted
and we can periodically tag the tail. The benefit of this change is we won't leave indices in the database
if the exception happens during the unindexing

core: track and improve tx indexing/unindexing

---

eth/api.go

If neither block number nor hash is specified by the call to AccountRange, then both the if and else if branches will be skipped over, such that stateDb will be nil when IteratorDump is called in the return statement.
It appears that the unmarshaller for BlockNumberOrHash does not guarantee that one of the two must be valid.

Fix potential nil pointer error from blockNrOrHash in AccountRange

---

accounts/usbwallet/ledger.go

After upgrading the Ledger Ethereum app to v1.4.0 the other day, I was no longer able to sign transactions with my Ledger using clef - the error message returned by clef was:
```
Ledger v1.4.0 doesn't support signing this transaction, please update to v1.0.3 at least
```
The version check logic did not take into account the second digit (i.e. the '4' in v1.4.0) - this one line patch corrects this.

accounts/usbwallet: fix ledger version check

---

cmd/geth/consolecmd.go

Closes #21748 by correcting the datadir path used in the `geth attach` command with the `--yolov2` flag

bug: fix dir path in geth attach for yolov2 network

---

accounts/abi/bind/base.go

closes https://github.com/ethereum/go-ethereum/issues/21739

accounts/abi/bind: restore error functionality

---

core/blockchain.go
core/blockchain_repair_test.go
core/blockchain_sethead_test.go
core/blockchain_snapshot_test.go
core/rawdb/accessors_snapshot.go
core/rawdb/schema.go
core/state/snapshot/disklayer_test.go
core/state/snapshot/generate.go
core/state/snapshot/journal.go
core/state/snapshot/snapshot.go
tests/state_test_util.go

This PR tries to improve the snapshot journal recovery mechanism by rewinding the HEAD block.
Snapshot generation is super expensive which can take more than 10 hours. While currently the
snapshot is quite fragile and will be invalid if any Geth crash happens. In this case, it just murders
the usability of the snapshot.
This PR tries to reuse the existent disk layer and recover the missing or broken diff layers so that
rebuild can be avoided in most cases.

core: improve snapshot journal recovery

---

common/bytes.go
internal/ethapi/api.go

This changes the default behaviour of ToHexArray and with it the behaviour of eth_getProof.
Previously we encoded an empty slice as 0, now the empty slice is encoded as 0x.
~~Also it introduces the hexutil package into common so it might not be so good after all~~

common: remove usage of deprecated function

---

core/blockchain_snapshot_test.go
core/state/snapshot/journal.go

When we meet the snapshot journal consisted with:
- disk layer generator with new-format
- diff layer journal with old-format
The base layer should be returned without error.
The broken diff layer can be reconstructed later
but we definitely don't want to reconstruct the
huge diff layer.

core/state/snapshot: fix journal recovery

---

cmd/devp2p/discv4cmd.go
cmd/devp2p/discv5cmd.go
cmd/devp2p/rlpxcmd.go
cmd/devp2p/runtest.go
internal/utesting/utesting.go
internal/utesting/utesting_test.go

[TAP](https://testanything.org) is a text format for test results. Parsers for it are available in many languages, making it easy to consume. I want TAP output from our protocol tests because the Hive wrapper around them needs to know about the test names and their individual results and logs. It would also be possible to just write this info as JSON, but I don't want to invent a new format.
You can see what this does by running the following commands:
```
go build ./cmd/geth ./cmd/devp2p
./geth --maxpeers 0
./devp2p discv4 test -remote <enode-URL>
```
It should print:
```
TAP version 13
1..14
ok 1 Ping/Basic
ok 2 Ping/WrongTo
ok 3 Ping/WrongFrom
ok 4 Ping/ExtraData
ok 5 Ping/ExtraDataWrongFrom
ok 6 Ping/PastExpiration
ok 7 Ping/WrongPacketType
ok 8 Ping/BondThenPingWithWrongFrom
ok 9 …
```

internal/utesting: implement TAP output

---

tests/fuzzers/stacktrie/debug/main.go
tests/fuzzers/stacktrie/trie_fuzzer.go
tests/fuzzers/trie/trie-fuzzer.go
trie/stacktrie.go
trie/stacktrie_test.go
trie/trie_test.go

This PR contains an almost functional stacktrie-fuzzer, which fuzzes stacktrie against the regular trie. The problem with the fuzzer is that it immediately hits crashes. 
Example of one such vector has been added in stacktrie_test.go, and it would be good if we got that resolved. 
Also, while implementing the fuzzer, I found that theoretical tries with roots small enough to be `<32 bytes` do not get committed to the db. This has been fixed, and a testcase for it has been added. 
@gballet please help me figure out why the test `TestUpdate` fails, and also verify the fix for `Commit` (cc @rjl493456442 )

trie, tests/fuzzers: implement a stacktrie fuzzer + stacktrie fixes

---

.travis.yml

Go 1.13 is not officially supported any more, stop wasting CI resources on it.

travis: drop Go 1.13 builders as it's not supported any more

---

core/blockchain_snapshot_test.go
core/state/snapshot/generate.go
core/state/snapshot/journal.go
core/state/snapshot/snapshot.go

This PR fixes a data corruption in the snapshot mechanism if it crashes mid-storage.
The generator works by iterating the state trie and pushing the account/storage leaf data directly to disk. To avoid thrashing the database, the generator accumulates writes into a batch and only flushes to disk after a certain threshold is exceeded. When the generator flushes to disk, it's internal progress marker is also updates so that it knows where to continue from if it's interrupted.
The bug was that the marker was **not** written to disk at the same time as the data batch, rather was kept in memory and only flushed on shutdown. This however means that in case of a crash (or Ctrl+C without waiting for graceful shutdown), if the generator was in progress, then the database would go out of sync, the …

core/state/snapshot: update generator marker in sync with flushes

---

consensus/ethash/algorithm.go

This is a follow-up to https://github.com/ethereum/go-ethereum/pull/21793 , fixing the percentage progress report. 
Before this PR (with the actual work skipped, hence the quick speeds): 
```
[user@work go-ethereum]$ ./build/bin/geth makedag 22000000 ./dag
INFO [11-09|11:43:21.019] Generating ethash verification cache     epoch=733 percentage=69 elapsed=3.000s
INFO [11-09|11:43:22.444] Generated ethash verification cache      epoch=733 elapsed=4.425s
INFO [11-09|11:43:22.503] Generating DAG in progress               epoch=733 percentage=0  elapsed=58.463ms
INFO [11-09|11:43:22.565] Generating DAG in progress               epoch=733 percentage=1  elapsed=120.784ms
INFO [11-09|11:43:22.633] Generating DAG in progress               epoch=733 percentage=2  elapsed=188.635ms
INFO …
```

consensus/ethash: fix the percentage progress report

---

oss-fuzz.sh

This PR 
1. moves the oss fuzzing configuration/build from oss-fuzz into go-ethereum, making it simpler for us to make changes and updates (it is a prerequisite for a follow-up PR against oss-fuzz to have any effect).
Current script, for reference: https://github.com/google/oss-fuzz/blob/master/projects/go-ethereum/build.sh

scripts: move oss-fuzz script to go-ethereum

---

consensus/ethash/algorithm.go

If DAG size is exceeding the maximum 32 bit unsigned value, the DAG generation will produce incorrect results due to an index overflow. This PR converts all index calculations to 64 bit, which implicitly also fixes the addressing overflow.

consensus/ethash: use 64bit indexes for the DAG generation

---

.travis.yml
build/ci.go

This fixes cross-build and mobile framework failures.
It also disables the mac test builder because it was failing
all the time in hard to understand ways and we can't afford
it anymore under Travis CI's new pricing.

build: fix regressions with the -dlgo change

---

crypto/bn256/bn256_fuzz.go
crypto/bn256/cloudflare/bn256.go

Fixes the problem with the bn256-fuzzer being extremely "hit-and-miss", where it hits roughly only 1 in 80 million or so... 
Also fixes a minor issue in the library which causes a nil deref on too short inputs

crypto/bn256: improve bn256 fuzzer

---

crypto/bn256/google/constants.go

Updates the comment for `u`. Previously the comment referred to the bn256 curve. However ethereum uses the alt_bn curve. 
Unfortunately `u` can not be put into a nice form of `u = x^3` as with the `u` used in bn256.
closes https://github.com/ethereum/go-ethereum/issues/21595

crypto/bn256: better comments for u, P and Order

---

accounts/abi/bind/backends/simulated.go
cmd/evm/internal/t8ntool/execution.go
cmd/geth/retesteth.go
core/evm.go
core/state_prefetcher.go
core/state_processor.go
core/state_transition.go
core/vm/evm.go
core/vm/gas_table_test.go
core/vm/instructions.go
core/vm/instructions_test.go
core/vm/logger_test.go
core/vm/runtime/env.go
core/vm/runtime/runtime.go
eth/api_backend.go
eth/api_tracer.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go
eth/tracers/tracers_test.go
les/api_backend.go
les/odr_test.go
light/odr_test.go
tests/state_test_util.go
tests/vm_test_util.go

As you can see, this is a mixed bag, ring tx are way faster, while other benchmarks are a bit slower
This PR:
```
BenchmarkInsertChain_empty_memdb-8            	    4575	    306455 ns/op	  178274 B/op	     510 allocs/op
BenchmarkInsertChain_empty_diskdb-8           	    3570	    351276 ns/op	  182059 B/op	     532 allocs/op
BenchmarkInsertChain_valueTx_memdb-8          	    3625	    373037 ns/op	  203530 B/op	     684 allocs/op
BenchmarkInsertChain_valueTx_diskdb-8         	    3140	    376081 ns/op	  207843 B/op	     705 allocs/op
BenchmarkInsertChain_valueTx_100kB_memdb-8    	    1000	   1521589 ns/op	  746068 B/op	     684 allocs/op
BenchmarkInsertChain_valueTx_100kB_diskdb-8   	     758	   1472932 ns/op	 1056727 B/op	     709 allocs/op
BenchmarkInsertChain_uncles_memdb-8 …
```

core, all: split vm.Context into BlockContext and TxContext

---

accounts/abi/bind/template.go

The Raw field is not set in Parse* methods.
It is set everywhere else in the template code.
This PR sets it.

accounts/abi: template: set events Raw field in Parse methods

---

docs/vulnerabilities/vulnerabilities.json
docs/vulnerabilities/vulnerabilities.md

This PR contains a document describing a proposed disclosure policy, along with a machine-readable json-file with vulnerability disclosures. 
The idea is to publish this on our github pages. After that, 
- We can add some optional geth self-check, e.g. `geth selfcheck` which could check if the node is vulnerable to any known vulnerabilities, 
- We can add checks on https://forkmon.ethdevops.io/, to show information about nodes which suffers from vulnerabilities, 
- We can add information on the download-page, by flagging versions with known vulnerabilities.

docs/vulnerabilities: vulnerability disclosure docs and json

---

crypto/bn256/cloudflare/bn256.go
crypto/bn256/google/bn256.go
crypto/bn256/google/constants.go

Refined comments according to #19577, #21595, and #21836

crypto/bn256: refine comments according to #19577, #21595, and #21836

---

consensus/ethash/algorithm.go

I ran into a weird issue when fuzzing github.com/prysmaticlabs/prysm, reported here: https://github.com/golang/go/issues/40397.
Some of the feedback I received from @mdempsky was:
> It's only safe to use *reflect.SliceHeader as a pointer to an actual slice-typed variable. You should never have a value or variable of type reflect.SliceHeader.
So I've fixed that issue in this PR.

consensus/ethash: fix usage of *reflect.SliceHeader

---

cmd/geth/les_test.go

Funky error on windows (AppVeyor)
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/36290884/job/hl96887y9fba9ph4#L728
```
les_test.go:109: lightserver rpc connect: no known transport for URL scheme "c"
```
Foo? 
```golang
ipcpath := filepath.Join(g.geth.Datadir, "geth.ipc")
g.rpc, err = rpc.Dial(ipcpath)
if err != nil {
t.Fatalf("%v rpc connect: %v", name, err)
}
```
It does use `--datadir C:\Users\appveyor\AppData\Local\Temp\1\geth-test470899768`, but the ipc path is
```
test_cmd.go:250: (stderr) INFO [11-13|10:19:06.780] IPC endpoint opened                      url=\\.\pipe\geth.ipc
```
However, the test just uses datadir, and `C` is interpreted as the protocol. This PR fixes that, I think, but let's see what the appveyor build says.

cmd/geth: fix les test on windows

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
core/blockchain.go
core/genesis.go
core/state/database.go
core/state/state_test.go
eth/api_test.go
eth/api_tracer.go
eth/backend.go
eth/config.go
eth/gen_config.go
light/postprocess.go
trie/database.go
trie/secure_trie.go

This PR offers an advanced command line flag for not saving preimages of trie keys.
It's useful for node operators to reduce *a few* disk usage if the preimages are unnecessary.

all: disable recording preimage of trie keys

---

node/rpcstack_test.go
rpc/websocket.go

Fixes issue: **Browser attack mitigation is overly specific** (converted to PR with potential implementation of suggested fix.)
Geth version: Seen in 1.9.10, 1.9.18
OS & Version: Win10
When using the command line flags `--ws --ws.origins localhost` (along with ws.port and ws.api, dropping the dots for older versions), websocket requests from localhost in the browser will be accepted.  
Websocket requests from a browser on localhost are rejected, because the browser sets the origin to something like the full string "https://localhost:8540" and [this code](https://github.com/ethereum/go-ethereum/blob/90dedea40fc174c914ef038b8b480c2c0ff031b9/rpc/websocket.go#L100) just naiively checks to see if that exact origin string is in the set of origins permitted by the command-line flag.
1. Run Geth …

node: support expressive origin rules in ws.origins

---

cmd/geth/accountcmd_test.go
cmd/geth/les_test.go
cmd/geth/run_test.go
internal/cmdtest/test_cmd.go
node/rpcstack.go
rpc/endpoints.go
trie/trie_test.go

This PR does several things to fix tests on 32-bit systems and windows (edited)
- changes some random to avoid using `big.Rand`, see https://github.com/golang/go/issues/42701 for more info. 
- changes a constant `int` to `uint64` so it compiles on 32-bit systems
- ensures that the same-folder-rooted windows-pipes (`\\.\pipe\`) don't conflict, but instead are differentiated by filename
- speeds up the tests a bit, by making newly-launched shortlived geth instances use less memory, no usb and disabled ipc
- adds identifier to stdout-output for the tests, so the outputs are easier to interpret and distinguish which is which
Non-test changes: 
- Makes IPC registration less verbose on debug level, 
- Makes IPC launch error be shown (it was previously never output, the Start sequence just …

trie, rpc, cmd/geth: fix tests on 32-bit and windows + minor rpc fixes

---

crypto/bn256/bn256_fuzz.go

The bn256 multiplication was unbounded, which caused the oss-fuzz executor to multiply for 30 seconds before exiting. Let's avoid that

crypto/bn256: fix bn256Mul fuzzer to not hang on large input

---

p2p/server.go

Related to #https://github.com/ethereum/go-ethereum/issues/21877 .
In the event that we've (temporarily) run out of file handles, the p2p server will spinloop on trying to `Accept`. This PR adds a little sleep, to not spin quite so fast, and also to consider the "temporary" error permanent after 2 seconds. 
Without this fix, `12M` log entries about temporary read error: 
```
archive@archive:~$ cat dump2.log | grep "Temporary read error" | wc -l
12832728
```

p2p: avoid spinning loop on out-of-handles

---

les/flowcontrol/control.go
les/utils/weighted_select.go

This PR fixes a flow control vulnerability that can cause a WRS weight overflow. It came up with les/4 (already fixed on my branch) but can affect old clients too. It also adds overflow protection and a proper error log to WRS.
Fixes https://github.com/ethereum/go-ethereum/issues/21820
Supersedes https://github.com/ethereum/go-ethereum/pull/21821

les/utils: protect against WeightedRandomSelect overflow

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/vulnerability.md

Removes this warning:
Also might guide some people that might not be aware to https://bounty.ethereum.org in case of a vulnerability.
And sets some labels automatically.
closes #20024

github: Add new style of issue-templates

---

cmd/faucet/faucet.go

This is trying to resolve this ticket: https://github.com/ethereum/go-ethereum/issues/21532

cmd/faucet: improve handling of facebook post url

---

les/server_handler.go

This PR fixes a bug in GetProofsV2 request serving that could potentially cause a panic because of `header` being `nil`.

les: fix GetProofsV2 bug

---

cmd/devp2p/internal/ethtest/large.go
cmd/devp2p/internal/ethtest/suite.go
cmd/devp2p/internal/ethtest/types.go

In these tests we create large announcements (announcements with numbers of ~ 2mb), and send them to the CuT
Prepare your geth node:
```
rm -rf build/datadir/
geth --http --http.port 8546 --nodiscover --datadir ./build/datadir init cmd/devp2p/internal/ethtest/testdata/genesis.json
geth --http --http.port 8546 --nodiscover --datadir ./build/datadir import cmd/devp2p/internal/ethtest/testdata/halfchain.rlp.gz
geth --http --http.port 8546 --nodiscover --datadir ./build/datadir --nat=none --networkid 19763 --verbosity 5 
```
Run the tests:
```
./devp2p rlpx eth-test enode://d789f40e3ebb0d7f80f52ef1c6a81c2b773c8b163d982ec4216041843046b0316f9c25c374be4703db7c17660601784cc5e4fb7c6f5b29ded81ff2ec651486fa@127.0.0.1:30303 internal/ethtest/testdata/fullchain.rlp.gz …
```

cmd/devp2p/internal/ethtest: add 'large announcement' tests

---

p2p/discover/v5_udp.go

Currently there is a deadlock that is exhibited whenever we received a response packet after the timeout of a particular call has passed. This can potentially lead to a deadlock. Over the past few months, multiple prysm nodes would suddenly stop being able to find and connect with new peers after a few days. 
Some examples:
https://github.com/prysmaticlabs/prysm/issues/6746
https://github.com/prysmaticlabs/prysm/issues/7220
Below is a goroutine dump for when the node was 'stuck' and without peers again. 
[goroutine.txt](https://github.com/ethereum/go-ethereum/files/5546465/goroutine.txt)
This goroutine dump has been filtered to only include traces relevant to go-ethereum. If you dig through the traces, it becomes obvious that the main dispatch routine is deadlocked. The routine is stuck …

p2p/discover: fix deadlock in discv5 message dispatch

---

accounts/hd.go
accounts/hd_test.go
signer/core/api.go

Existing code in clef enumerated Ledger Live accounts by starting with m/60' are enumerated by starting at `m/44'/60'/0'/0/0` and then incrementing the last component to `m/44'/60'/0'/0/1`, `m/44'/60'/0'/0/2`, ... `m/44'/60'/0'/0/N`.
However this failed to find any account after the first one as Ledger Live increments the third component rather than the fifth component i.e. `m/44'/60'/0'/0/0`, `m/44'/60'/1'/0/0`, `m/44'/60'/2'/0/0`, ... `m/44'/60'/N'/0/0`.
This patch corrects Ledger Live account derivation but leaves the existing derivation for Ledger Legacy and non-Ledger devices.
Additionally, this patch increases enumeration depth to ten accounts each for Ledger Legacy and Ledger Live - in my case, I currently use six accounts on Ledger Live and the existing limit of five each for …

accounts, signer: fix Ledger Live account derivation path (clef)

---

cmd/geth/accountcmd_test.go
cmd/geth/consolecmd_test.go
cmd/geth/dao_test.go
cmd/geth/genesis_test.go
cmd/geth/les_test.go

This PR fixes a lot of the tests in `cmd/geth` so they run faster and consume less memory, which should improve the appveyor/travis speeds. The tests run about twice as fast on my laptop. 
- Adds `nousb`
- Lower the cache to `64`
- Use `syncmode=full`, avoid allocating fast-sync bloom
- Use `ropsten` instead of mainnet. No alloc-portion makes writing the genesis quicker
- Combine the three welcome-attachers to use one instance 
- Make les server use lightkdf during import

cmd/geth: make tests run quicker + use less memory and disk

---

p2p/nodestate/nodestate.go

This PR fixes a deadlock reported here: https://github.com/ethereum/go-ethereum/issues/21925
The cause is that many operations may be pending, but if the close happens, only one of them gets awoken and exits, the others remain waiting for a signal that never comes. 
Here's a pretty crappy test that hangs on `master` but works fine with this patch, and demonstrates this behaviour. It needs to be fixed up to be less chronistic (channel-based?) if we want to get the test in also: 
```golang
func TestDeadlock(t *testing.T) {
mdb, clock := rawdb.NewMemoryDatabase(), &mclock.Simulated{}
s, _, _ := testSetup([]bool{false, false, false, false}, nil)
ns := NewNodeStateMachine(mdb, []byte("-ns"), clock, s)
ns.Start()
startedCh := make(chan bool)
// some operation takes a lot of time
go func() {
err …
```

p2p/nodestate: fix deadlock

---

cmd/utils/flags.go
eth/backend.go
eth/discovery.go
les/client.go
les/enr_entry.go

This PR fixes the --nodiscover option (LES ENR filter was looking for the wrong field in the config).
Fixes https://github.com/ethereum/go-ethereum/issues/21880

les: fix nodiscover option

---

eth/api_tracer.go

This fixes an error that can be hit when tracing and using e.g. `reexec=100`. Due to an anonymous struct, the `config.Overrides ` can trigger a nil deref since it _actually_ references `config.LogConfig.Overrides`, and ` config.LogConfig` is `nil` if only `reexec` is specified but nothing else. 
Example crash: 
```
INFO [11-11|13:37:27.158] Historical state regenerated             block=11234872 elapsed=50m20.275461793s nodes=1.54GiB preimages=92.71MiB
ERROR[11-11|13:37:27.158] RPC method debug_standardTraceBlockToFile crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 1089318128 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1(0xc01538f740, 0x1e, 0xc27acb1d58)
github.com/ethereum/go-ethereum/rpc/service.go:200 +0xba
panic(0x11a5f00, …
```

eth: fix error in tracing if reexec is set

---

cmd/devp2p/nodesetcmd.go

This PR adds a filter to filter out snap peers from a set of nodes. 
```
go run .  nodeset filter nodes.json -eth-network mainnet -snap | jq ".[] | .record" 
"enr:-KO4QE8DeESXiEKUDzeg4P1Eu4xR1kLCPSIJgGD6LQnya-0acIB3OFK-PhvubvESpbttKpkT3YfFSIuVy4Cha6v12vCBuYNldGjHxoTgKemRgIJpZIJ2NIJpcIRoKtkZg2xlc8CJc2VjcDI1NmsxoQNdbXzSDW2ku4Oh0oyttdQJtk7fMUwDNd9ljBpU4yx8SoRzbmFwwIN0Y3CCdl-DdWRwgnZf"
"enr:-KS4QDu27qjyNzpZxiWJ3QKh1XLOSiF1knJ_CzETUzIekDKtWCThgZ1DpnjopgyhdEpxRWgdmDPNX8kgINer330qYWOCAQqDZXRox8aE4CnpkYCCaWSCdjSCaXCEI570l4NsZXPAiXNlY3AyNTZrMaECJ5lE2NzUKN_6p0NvJcoMpDrhnnvPlKj7fRZBZR-S0SGEc25hcMCDdGNwgnZfg3VkcIJ2Xw"
"enr:-KO4QKv24uhwkS612lV6JLStvQw50hHLpY7X3T2-IycGyAbZJMxKhB0Q4QiwEnAOKvzgp3j8Nv5g6h70IwQHk-aZiOWBhINldGjHxoTgKemRgIJpZIJ2NIJpcIQ056Vsg2xlc8CJc2VjcDI1NmsxoQJxUXH1BQirqIrs0SUK85KkWjMK-R17k …
```

cmd/devp2p: add node filter for snap + fix arg error

---

core/vm/runtime/runtime.go

This line is duplicated, though it doesn't cause any issues. 
You can check the actual discussion with @holiman [here](https://github.com/ethereum/go-ethereum/pull/21509#discussion_r535541122).

core/vm/runtime: remove duplicate line

---

accounts/abi/bind/backends/simulated.go
core/blockchain_test.go
core/state_processor.go
core/state_processor_test.go
core/state_transition.go
core/tx_pool_test.go
light/lightchain_test.go
miner/worker.go

A lot of times when we hit 'core' errors, the information provided is insufficient. Example, a corrupted state: 
```
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, YOLO v2: <nil>, Engine: ethash}
Number: 11275362
Hash: 0x336c355d70331fd9dd7b1ab39ccdf4f619ba8709c604190c5589ba278b145aca
Error: nonce too high
##############################
```
We miss several pieces of information: what account has `nonce too high`, and what transaction in that block was offending? 
This PR adds that information, using the new type of wrapped errors. 
It also adds a testcase which (partly) verifies …

core: improve contextual information on core errors

---

les/utils/expiredvalue.go

This is a PR meant to check if go 1.15 fixed the floating point conversion error described in https://github.com/ethereum/go-ethereum/issues/20921, disregard for now

les: cosmetic rewrite of the arm64 float bug workaround

---

crypto/secp256k1/dummy.go
crypto/secp256k1/libsecp256k1/contrib/dummy.go
crypto/secp256k1/libsecp256k1/dummy.go
crypto/secp256k1/libsecp256k1/include/dummy.go
crypto/secp256k1/libsecp256k1/src/dummy.go
crypto/secp256k1/libsecp256k1/src/modules/dummy.go
crypto/secp256k1/libsecp256k1/src/modules/ecdh/dummy.go
crypto/secp256k1/libsecp256k1/src/modules/recovery/dummy.go

Go won't vendor C files if there are no Go files present in the directory. Workaround is to add dummy Go files.
Approach from: crawshaw/sqlite#88
Fixes: ethereum/go-ethereum#20232

crypto/secp256k1: add workaround for go mod vendor

---

accounts/abi/bind/auth.go
accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go
accounts/abi/bind/base.go
accounts/abi/bind/bind_test.go
contracts/checkpointoracle/oracle_test.go
les/sync_test.go
les/test_helper.go
mobile/bind.go

This commit enables users to specify which signer they want to use while creating their transactOpts.
Previously all contract interactions used the homestead signer. Now a user can specify whether they
want to sign with homestead or EIP155 and specify the chainID which adds another layer of security.
closes https://github.com/ethereum/go-ethereum/issues/16484
This PR changes the interface of New{}Transactor, so it is a breaking change for everyone who uses the bind package to create their signer.

accounts/abi/bind: allow to specify signer on transactOpts

---

common/types.go
common/types_test.go

The default formatter, which is "%v", will print out common.Address as a list of integers. 
e.g, Address  0xB26f2b342AAb24BCF63ea218c6A9274D30Ab9A15 would be print as [178 111 43 52 42 171 36 188 246 62 162 24 198 169 39 77 48 171 154 21]
the Address struct overrides `fmt.Stringer` interface for better logging output.
However when using fmt.(Fp|Sp|P)rintln and fmt.(Fp|Sp|P)rint functions where no format string provided, `fmt.Formatter` override will take precedence and use the default formatter instead of trying to call the `String()` function which defeats the purpose for the `fmt.Stringer` override.
Also the "%s" print out is confusing in current code.
Hence I think it would be better to override the default formatter "%v" and "%s"'s behavior in its `fmt.Formatter` override.
PS1: One …

common: improve printing of Hash and Address

---

core/blockchain.go
core/headerchain.go
core/headerchain_test.go
light/lightchain.go

This PR is a rewrite of https://github.com/ethereum/go-ethereum/pull/19456. It does a couple of things. 
The first commit contains a testcase for how the headerchain behaves in certain aspects. Running that on a non -modified master, yields a few errors; 
```
=== RUN   TestHeaderInsertion
t=2020-08-21T09:32:13+0200 lvl=info msg="Imported new block headers" count=64 elapsed=1.470ms number=64 hash=0xf2036d795873749f13e0abb674f7001813c8fc2593cf5cc3779a89094a54359d age=51y4mo2w
t=2020-08-21T09:32:13+0200 lvl=info msg="Imported new block headers" count=0  elapsed="234.946µs" number=64 hash=0xf2036d795873749f13e0abb674f7001813c8fc2593cf5cc3779a89094a54359d age=51y4mo2w ignored=64
t=2020-08-21T09:32:13+0200 lvl=info msg="Imported new block headers" count=32 elapsed="782.077µs" number=96 …
```

core,les: headerchain import in batches

---

cmd/geth/testdata/vcheck/vulnerabilities.json
cmd/geth/version_check_test.go

This PR adds a test to help check regexps, and the corresponding fix for the signatures is here: https://github.com/ethereum/go-ethereum/pull/21961

cmd/geth: add test to verify regexps in version check

---

.travis.yml
build/ci.go
crypto/signify/signify.go
crypto/signify/signify_test.go

This fixes some issues in crypto/signify and makes release signing work.
The archive signing step in ci.go used getenvBase64, which decodes the key data.
This is incorrect here because crypto/signify already base64-decodes the key.

crypto/signify, build: fix archive signing with signify

---

p2p/enode/nodedb.go

The database panicked for invalid IPs. This is usually no problem
because all code paths leading to node DB access verify the IP, but it's
dangerous because improper validation can turn this panic into a DoS
vulnerability. The quick fix here is to just turn database accesses
using invalid IP into a noop. This isn't great, but I'm planning to
remove the node DB for discv5 long-term, so it should be fine to have
this quick fix for half a year.
Fixes #21849

p2p/enode: avoid crashing for invalid IP

---

les/client_handler.go
les/odr.go
les/odr_requests.go
les/retrieve.go
les/sync.go
les/sync_test.go
light/odr.go
light/odr_util.go
light/trie.go

This PR removes the legacy hacks to retrieve the header without CHT Proof.
It's an important step to retrieve the block header that the checkpoint oracle signatures are attached in that block.
However, this step is executed before applying the "unverified" checkpoint, so it means the block header is not covered
by local CHT.
In order to retrieve the "untrusted" block header, originally, the hack is applied that we still use the `CHTRequest` because the corresponding header will still be returned no matter the proving is succeeded or not. It's really ugly.
Now this PR proposes another approach to use the `GetBlockHeadersMsg` directly. Normally this message is used in the syncing only, but it can also be used to retrieve a single header without proof.
What's more, this separated function …

les, light: remove untrusted header retrieval in ODR

---

core/state/sync_test.go
trie/sync_test.go

This PR fixes what I _think_ is a flaw in two testcases, and brings down the exec-time from ~40s on my laptop, to ~8s for `trie/TestIncompleteSync`. 
The `checkConsistency` was performed over and over again on the _complete_ set of nodes, not just the recently added. So it had a quadratic runtime, basically. 
@rjl493456442 please correct me if it looks like I misinterpreted the test

core, trie: speed up some tests with quadratic processing flaw

---

les/client_handler.go
les/peer.go
les/peer_test.go
les/protocol.go
les/server_handler.go

This PR introduces the forkid to the les protocol and also bump the les protocol version to les4.
The forkId will be used in the handshake and all the incompatible peers will be rejected in the first place.

les: introduce forkID

---

les/utils/expiredvalue.go

The previous fix  #21960 converted the float to an intermediate signed int, before attempting the uint conversion. Although this works, this doesn't guarantee that other architectures will work the same.

les: rework arm64's undefined workaround

---

eth/downloader/downloader_test.go
miner/worker.go

**Description**
***The bug in miner/worker.go***
In miner/worker.go, there are two goroutine using channel `w.newWorkCh`: newWorkerLoop() sends to this channel, and mainLoop() receives from this channel. Only the receive operation is in a select.
However, `w.exitCh` may be closed by another goroutine. This is fine for the receive since receive is in select, but if the send operation is blocking, then it will block forever.
This commit puts the send in a select, so it won't block even if `w.exitCh` is closed.
***The bug in eth/downloader/downloader_test.go***
Similarly, there are two goroutines using channel `errc`: the parent that runs the test receives from it, and the child created at line 573 sends to it.
If the parent goroutine exits too early by calling `t.Fatalf()` at line 614, then …

miner, test: fix potential goroutine leak

---

cmd/faucet/faucet.go
cmd/puppeth/module_faucet.go
cmd/puppeth/wizard_faucet.go

This PR adds support for using Twitter API to query the tweet and author details. There are two reasons behind this change:
1) Twitter will be deprecating the legacy website on 15th December. The current method is expected to stop working then.
2) More importantly, the current system uses Twitter handle for spam protection but the Twitter handle can be changed via automated calls. This allows bots to use the same tweet to withdraw funds infinite times as long as they keep changing their handle between every request. The Rinkeby as well as the Goerli faucet are being actively drained via this method. This PR changes the spam protection to be based on Twitter IDs instead of usernames. A user can not change their Twitter ID.

cmd/faucet: use Twitter API instead of website

---

core/tx_list.go
core/tx_pool.go
core/tx_pool_test.go

Fixes #21174
```
Master
goos: darwin
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core
BenchmarkInsertRemoteWithAllLocals
BenchmarkInsertRemoteWithAllLocals-4   	       1	5516987671 ns/op
PASS
```
```
PR
goos: darwin
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core
BenchmarkInsertRemoteWithAllLocals
BenchmarkInsertRemoteWithAllLocals-4   	      25	  45455161 ns/op
PASS
```

core/txpool: remove "local" notion from the txpool price heap

---

consensus/ethash/consensus.go
consensus/ethash/consensus_test.go
consensus/ethash/difficulty.go
oss-fuzz.sh
tests/fuzzers/difficulty/debug/main.go
tests/fuzzers/difficulty/difficulty-fuzz.go

This PR is very safe, and doesn't actually do anything. 
While I was investigating header import (https://github.com/holiman/headerimport/blob/main/README.md ) , I noticed that there is a lot of time spent (allocations spent) on calculating the difficulty. 
This PR adds re-written difficulty calculators, which are based on `uint256`. It also adds a fuzzer + oss-fuzz integration for the new fuzzer. It does differential fuzzing between the new and old calculators. 
Note: this PR does not actually enable the new calculators. 
Anyway, if travis looks green, we could merge this and have it fuzzed, and later decide whether about enabling it.
Oh, and there are some benchmarks too, `u256-xx` are the new ones, `big-xx` are the old: 
```
BenchmarkDifficultyCalculator …
```

consensus/ethash: implement faster difficulty calculators

---

consensus/clique/clique.go
consensus/ethash/consensus.go

Small refactor of the FinalizeAndAssemble function in both consensus engines.

consensus: refactor FinalizeAndAssemble to use Finalize

---

accounts/abi/bind/bind_test.go
accounts/abi/bind/template.go

In this [PR](https://github.com/ethereum/go-ethereum/commit/420b78659bef661a83c5c442121b13f13288c09f#diff-491a4b89b4d4d78f4266f59f3d03b8af43c172fdacb8c529558f604f6c29b373R306) the template was changed which ended up producing code like:
```
var out []interface{}
err := _NonExistentStruct.contract.Call(opts, &out, "Struct")
outstruct := new(struct {
A *big.Int
B *big.Int
})
outstruct.A = out[0].(*big.Int)
outstruct.B = out[1].(*big.Int)
return *outstruct, err
```
which will panic instead of returning an error if the contract doesn't exist. I moved the error handling up before the indexing to avoid that (analogous to how non-struct responses are handled)

abi/bind: fix error-handling in generated wrappers for functions returning structs

---

cmd/abigen/main.go

update the `abigen --alias` flag help info, give an example to make it more clear
related issue: https://github.com/ethereum/go-ethereum/issues/21846
closes: https://github.com/ethereum/go-ethereum/issues/21846

doc: clarify abigen alias flag usage

---

cmd/geth/accountcmd_test.go

Two tests in our codebase use the `t.Parallel()` in an unsafe way which results in only the last test in a test table being executed.
For example master prouduces:
```
=== RUN   TestDeliverHeadersHang
=== PAUSE TestDeliverHeadersHang
=== CONT  TestDeliverHeadersHang
=== RUN   TestDeliverHeadersHang/protocol_63_mode_full
=== PAUSE TestDeliverHeadersHang/protocol_63_mode_full
=== RUN   TestDeliverHeadersHang/protocol_63_mode_fast
=== PAUSE TestDeliverHeadersHang/protocol_63_mode_fast
=== RUN   TestDeliverHeadersHang/protocol_64_mode_full
=== PAUSE TestDeliverHeadersHang/protocol_64_mode_full
=== RUN   TestDeliverHeadersHang/protocol_64_mode_fast
=== PAUSE TestDeliverHeadersHang/protocol_64_mode_fast
=== RUN   TestDeliverHeadersHang/protocol_64_mode_light
=== PAUSE …
```

cmd/geth: fixed parallelized tests

---

eth/protocols/eth/handler_test.go

Have removed magic numbers, have replaced it with the variables usage from the protocol.go
```go
// eth protocol message codes
const (
StatusMsg          = 0x00
NewBlockHashesMsg  = 0x01
TransactionMsg     = 0x02
GetBlockHeadersMsg = 0x03
BlockHeadersMsg    = 0x04
GetBlockBodiesMsg  = 0x05
BlockBodiesMsg     = 0x06
NewBlockMsg        = 0x07
GetNodeDataMsg     = 0x0d
NodeDataMsg        = 0x0e
GetReceiptsMsg     = 0x0f
ReceiptsMsg        = 0x10
// New protocol message codes introduced in eth65
//
// Previously these message ids were used by some legacy and unsupported
// eth protocols, reown them here.
NewPooledTransactionHashesMsg = 0x08
GetPooledTransactionsMsg      = 0x09
PooledTransactionsMsg         = 0x0a
)
```

eth/protocols/eth: remove magic numbers in tests

---

core/bloombits/matcher_test.go
core/bloombits/scheduler_test.go

`eth` tests on appveyor were `52s` before this PR,  `bloombits` at `13s`. Let's see what they land on with this PR -- it's definitely much faster on my machine

eth, core: speed up some tests

---

cmd/utils/flags.go
les/odr_requests.go
les/peer.go
les/protocol.go

This PR allows tx unindexing in les/4 light server mode.
A few more upgrades might be added to les/4 but the goal is to keep the number of changes low while satisfying the requirements stated in https://github.com/ethereum/go-ethereum/issues/21876
Most of the upgrades needed for incentivization (including UDP communication) should go into les/5.
Features that might be added to the les/4 upgrade (up for debate):
- forkID; see https://github.com/ethereum/go-ethereum/pull/20227
- reduced minimum capacity in order to serve more clients
- request/reply metainfo channel; see https://github.com/zsfelfoldi/go-ethereum/commit/48c7ec938f43e618bbce3334557dfeae9073f7ee (parts of this commit are related to lespay request serving which should definitely go into the next upgrade)
Note: the metainfo …

les: les/4 minimalistic version

---

cmd/faucet/faucet.go

closes https://github.com/ethereum/go-ethereum/issues/22017

cmd/faucet: sort requests by newest first

---

eth/backend.go
internal/ethapi/api.go
les/client.go

During the snap and eth refactor, the net_version rpc call was falsely deprecated.
This reenables the net_version RPC handler as most eth2 nodes and other software
depends on it.
closes https://github.com/ethereum/go-ethereum/issues/22059
closes https://github.com/ethereum/go-ethereum/issues/22057
closes https://github.com/ethereum/go-ethereum/issues/22034

internal/ethapi: re-add net_version RPC method

---

oss-fuzz.sh
tests/fuzzers/bitutil/compress_fuzz.go
tests/fuzzers/bn256/bn256_fuzz.go
tests/fuzzers/runtime/runtime_fuzz.go

This is one step towards getting coverage reports, a'la https://github.com/google/oss-fuzz/issues/4847 . 
A couple of our fuzzers reside within the go-ethereum core codebase. This is fine, except that in order to not include them in regular builds, they've been tagged with `// +build gofuzz`, to only be included in the fuzzed images. 
However, the coverage reports are based on runinng regular `go test ... ` on a testcase which simply feeds the corpus through the `Fuzz` function. And the `Fuzz` function is not visible in that case, since the build-tag is not active when not running via `go-fuzz`. 
So a better approach is to move the fuzzers into `tests/`, and remove the build tag. 
We still have some other cases where it's more difficult to move them, since the fuzzing relies on …

common,crypto: move fuzzers out of core

---

README.md

The legacy dot-org URL was displaying a message about the repository
having migrated to the dot-com service, which now covers open-source
projects as well.

README.md: update Travis badge

---

tests/fuzzers/bitutil/compress_fuzz.go

This PR fixes a false positive reported by oss-fuzz. The fuzzer took the input as 'compressed' data, and expected unpack + pack to yield the same result. 
However, un-compressed data at size `1024` can be interpreted as "compressed (but not really)", and thus there's no change when decompressing it. When we compress it again, however, it becomes _actually_ compressed.

tests/fuzzers: fix false positive in bitutil fuzzer

---

cmd/geth/consolecmd.go

cmd/geth: Replace wiki links with new doc pages

---

eth/filters/api.go

eth/filters: Replace wiki links with new doc pages

---

eth/downloader/queue.go

In downloader queue update (#21263), the invalid chain error assignment is removed. 
So, the invalid chain error checking is not necessary anymore.

eth/downloader: removed unnecessary invalid chain error check

---

docs/_dapp/native-accounts.md
docs/_dapp/tracing.md

Fixes some links in the dapps section of the docs. They were being referenced by id which jekyll couldn't handle for some reason. Strangely links in some other pages are also referenced by id but work fine (e.g. `developers/devguide`). I couldn't figure out the difference.

docs: fix links in dapps pages

---

accounts/abi/bind/bind_test.go

fix Newfallback test
related issue https://github.com/ethereum/go-ethereum/issues/22049

accounts/abi/bind: fix NewFallback test

---

core/state/snapshot/generate.go

fixed typo gethring -> gathering at `core/state/snapshot/generate.go`

snapshot: fixed typo; gethring -> gathering

---

SECURITY.md

Add links to go-ethereum's GitHub release page.

SECURITY.md: link to release page

---

cmd/faucet/README.md
cmd/faucet/faucet.go
cmd/puppeth/module_faucet.go
cmd/puppeth/wizard_faucet.go

Twitter closed down their old website, which the faucet used to retrieve tweets from. This PR extends the faucet to support the old v1.1 API beside the newer v2 (not generally available yet) and fixes `puppeth` to support deploying the faucet again (is broken on master, the Dockerfile template is invalid). The PR also adds a readme to the faucet to help anyone else wishing to deploy it outside of `puppeth`.

cmd: support v1.1 Twitter API in faucet, fix puppeth

---

miner/worker.go

This PR removes a logic in the miner, which was originally intended to help temporary testnets based on ethash from "running off into the future". If the difficulty was low, and a few computers started mining several blocks per second, the ethash rules (which demand 1s delay between blocks) would push the blocktimes further and further away. 
The solution was to make the miner sleep while this happened. 
Nowadays, this problem is solved instead by PoA chains, and it's recommended to let testnets and devnets be based on clique instead. The existing logic is problematic, since it can cause stalls within the miner making it difficult for remote workers to submit work if the channel is blocked on a sleep.

miner: avoid sleeping in miner

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go

As discussed during standup, this PR turns USB off by default and deprecates `--nousb`. It introduces the inverse option `--usb`.
The goal of this PR is to initiate a removal of the account system from geth and move it into clef, as well as reduce the reliance of geth on C dependencies.

cmd/geth: usb is off by default

---

common/compiler/solidity.go

Solidity 0.8.0 changes the way that output is marshalled. This patch allows to parse both
the legacy format used previously and the new format.
See also https://docs.soliditylang.org/en/breaking/080-breaking-changes.html#interface-changes
closes https://github.com/ethereum/go-ethereum/issues/22041

common/compiler: fix parsing of solc output with solidity v.0.8.0

---

eth/downloader/queue_test.go

The testcases are enhanced for downloader queue and removed some comments.
This PR is derived from klaytn/klaytn#834.

eth/downloader: enhanced test cases for downloader queue

---

graphql/graphql.go
graphql/graphql_test.go

This PR updates the return values for `estimateGas` and `cumulativeGas` to decimal rather than hexadecimal, as defined by the [spec](https://eips.ethereum.org/EIPS/eip-1767).

graphql: return decimal for `estimateGas` and `cumulativeGas` queries 

---

core/state/snapshot/conversion.go
core/state/snapshot/difflayer.go
core/state/snapshot/difflayer_test.go
core/state/snapshot/disklayer.go
core/state/snapshot/disklayer_test.go
core/state/snapshot/iterator.go
core/state/snapshot/iterator_binary.go
core/state/snapshot/iterator_fast.go
core/state/snapshot/snapshot.go
trie/database.go

snapshot, trie: fixed typos, mostly in snapshot pkg

---

eth/protocols/snap/sync.go

Supersedes https://github.com/karalabe/go-ethereum/pull/42 
This (hopefully) fixes a flaw, where a remote peer rejects the request. Previously, we would seemingly not reschedule the request, until the next sync cycle. For some reason, which I'm not fully clear about, it could get stuck for hours (my NUC was stuck on the same things for >12 hours), requesting (and getting rejected) the same segments from the same peer(s). 
This PR reverts the request if the remote side cannot deliver, so it can be rescheduled for another peer. 
Example output when running it
```
DEBUG[12-04|11:28:11.318] Persisted set of healing data            bytes=40.43KiB [134/1839]
DEBUG[12-04|11:28:11.318] Peer rejected trienode heal request      peer=2d1f1ff2 reqid=2436914576115805419
DEBUG[12-04|11:28:11.318] …
```

snap: track revertals when peer rejects request

---

cmd/faucet/faucet.go

About a year ago we switched over the websocket library in the faucet from Go's implementation to the Gorilla library. Unfortunately the former was thread safe whilst the latter was not, and we didn't update the faucet code to add mutexes. This was undetected for quite a long time since our faucet auto-restarts, so an occasional crash was just silently ignored.
Fixes
```
panic: concurrent write to websocket connection
goroutine 179 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc01f4879e0, 0x1, 0x0, 0x0, 0x0, 0xc000053c00, 0x0)
github.com/gorilla/websocket@v1.4.1-0.20190629185528-ae1634f6a989/conn.go:597 +0x60e
github.com/gorilla/websocket.(*messageWriter).Close(0xc01f4879e0, 0x8, 0xc0135d0d28)
github.com/gorilla/websocket@v1.4.1-0.20190629185528-ae1634f6a989/conn.go …
```

cmd/faucet: fix websocket race regression after switching to gorilla

---

eth/protocols/snap/sync.go
eth/protocols/snap/sync_test.go

This PR optimises the hashing a bit during the snap response verification. We use a `hash` only temporarily, to verify against the request, and can thus reuse the same buffer, and avoid an alloc and copy. We can also use the `keccatState` to avoid a second alloc+copy via `Read` instead of `Sum`.
Benchmark for checking `10K` items with 100 bytes of data each: 
```
BenchmarkHashing/old
BenchmarkHashing/old-6         	     100	  20599259 ns/op	 5120510 B/op	   30002 allocs/op
BenchmarkHashing/new
BenchmarkHashing/new-6         	     219	   5355205 ns/op	     480 B/op	       2 allocs/op
```

eth/protocols/snap: speed up hash checks

---

cmd/faucet/faucet.go
cmd/faucet/faucet_test.go

The full website uses AJAX. Switch over to the mobile site for scraping the infos.

cmd/faucet: switch Facebook auth over to mobile site

---

les/txrelay.go

This PR removes the restriction in the transaction propagation. 
Previously, the transaction will only be sent to the specific peer for one time. This approach is not robust enough, espeically when the peerset is small. Round-of-robin is enough for distributing the transaction to the network.
In this PR, the propagation logic is simplied a lot. Whenever the light client tries to broadcast transactions, it just picks a few peers with Round-of-robin algo.

les: remove transaction propagation limits

---

cmd/faucet/faucet.go
cmd/faucet/faucet.html

The faucet sometimes croaks. When a client connects to the faucet, quite a lot of data is shipped.
Every 15s or so, `~56Kb` of request-data is sent, and `1.5Kb` block data is sent. In the example here, half a megabyte in 2.5 minutes. 
And this is for every individual user who has the page open in a tab -- so 100 concurrent users means the server has a lot of work to do. This PR reuses the encoded json messages that goes out to the clients, to make things a little bit speedier. 
Caveat: I haven't tested it...

cmd/faucet: fix nonce-gap problem

---

ethclient/ethclient_test.go

This PR extends the ethclient test suite and increases code coverage of the ethclient
package from ~15% to >55%. These tests act as early smoke tests to signal issues in the
RPC-interface. E.g. if a functionality like eth_chainId or eth_call breaks, the test
will break.

ethclient: better test suite for ethclient package

---

eth/downloader/downloader_test.go

Running this cmd:
```
go test -timeout 420s -count 1 -race github.com/ethereum/go-ethereum/eth/downloader
```
was giving race condition issues.
This PR fixes the minor race condition in the tests.

eth/downloader: fix race condition in tests

---

eth/handler.go
eth/peerset.go

eth: improve log message

---

graphql/schema.go

This PR fixes a graphql error with unmarshalling int32 into `Long`. This issue was noticed thanks to a graphql test failure on Hive (`graphql_blocks_byFrom`).

graphql: fix issue with unmarshalling int32 into `Long` type

---

eth/api.go
internal/web3ext/web3ext.go

This PR changes the `chainId()` method of the public eth api to return the eth config's `chainID` regardless of sync status. 
Sync status was previously required by the `chainId()` method in order to return the proper chainID, due to the following condition: 
```go
config.IsEIP155(api.e.blockchain.CurrentBlock().Number())
```
causing the incorrect `chainID` to be returned by the `chainId()` method for both Rinkeby and Ropsten (and private chains).
This PR also adds an `isEIP155()` method to the public ethereum API so one can check if the chain is at or beyond the EIP155 fork block.
closes https://github.com/ethereum/go-ethereum/issues/20894

eth: change chainID method to return chainID from config or error if before EIP-155

---

cmd/utils/flags.go

Resolves https://github.com/etclabscore/core-geth/issues/273. 
I believe this issue will be equivalent at ethereum/go-ethereum since this logic is unmodified.
jsre.JSRE already handles establishing preload
file paths relative to the 'assets' path (aka docroot),
where it joins the assets dir and the file path if relative,
or uses the file path only if absolute.
The duplication of this logic by MakeConsolePreloads
caused preloaded files to have paths which contained
duplicate references to the assets dir path.
Date: 2020-12-30 08:25:01-06:00

cmd/utils: avoid making console preloads absolute

---

cmd/geth/accountcmd_test.go
cmd/geth/consolecmd_test.go
cmd/geth/dao_test.go
cmd/geth/genesis_test.go
cmd/geth/les_test.go
cmd/utils/flags.go
miner/stress_clique.go
miner/stress_ethash.go
node/api_test.go
node/config.go
p2p/simulations/adapters/exec.go
p2p/simulations/adapters/inproc.go

USB enumeration still occured. Make sure it will only occur if `--usb` is set.

cmd/utils: don't enumerate usb when --usb isn't set

---

graphql/graphql_test.go

This solves _one_ graphql spurious error, but not both of them. 
```
graphql_test.go:38: could not create new node: datadir already used by another process
--- FAIL: TestBuildSchema (0.00s)
```

graphql: fix spurious error in test

---

consensus/ethash/ethash_test.go

It seems that the 2 second timeout is not enough for travis
```
--- FAIL: TestTestMode (2.00s)
ethash_test.go:53: sealing result timeout
FAIL
coverage: 70.2% of statements
FAIL	github.com/ethereum/go-ethereum/consensus/ethash	11.261s
```
https://travis-ci.com/github/ethereum/go-ethereum/jobs/457951964
https://travis-ci.com/github/ethereum/go-ethereum/jobs/469377305
https://travis-ci.com/github/ethereum/go-ethereum/jobs/469031088

consensus/ethash: increase seal timeout for tests

---

graphql/graphql_test.go

In go `1.14`, the graphql tests runs really fast: 
```
go test . -run TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful -v  --count 20
=== RUN   TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful
--- PASS: TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful (0.00s)
=== RUN   TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful
--- PASS: TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful (0.00s)
=== RUN   TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful
--- PASS: TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful (0.00s)
=== RUN   TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful
--- PASS: TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful (0.00s)
=== RUN   TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful
--- PASS: TestGraphQLHTTPOnSamePort_GQLRequest_Unsuccessful (0.00s)
=== RUN …
```

graphql: fix spurious travis failure

---

core/state/snapshot/generate.go

Currently the snapshot generator only logs every 8 seconds while it's processing the account trie (possibly a regression, I surely know it logged for storage tries too at one time). The generator however does not log while it's crunching through a storage trie.
If the node is receiving blocks, this is fine, because every block interrupts the generator and will resume it afterwards, forcing a log anyway. However, if no blocks are arriving (e.g. benchmarking with networking disabled), the generator will not print anything until it gets done with a contract. With contracts weighting gigabytes on mainnet, that amounts to hours of potential "no log" scenarios, which is not a good UX.
This PR adds a log back so that the generator will log if it was crunching a storage trie for too long too.

core/state/snapshot: add generation logs to storage too

---

eth/protocols/eth/broadcast.go

This seems to be a bug. Usually the two values are the same but when they are not this can cause a negative starting position. It looks like this was copied from above but the variable name was not changed.

Fix queue slicing

---

les/benchmark.go
les/handler_test.go
les/odr_requests.go
les/server_handler.go

This PR has two changes in the les protocol.
- the `auxRoot` is not supported. See https://github.com/ethereum/devp2p/issues/171 for more information
- the empty response will be returned in `GetHelperTrieProofsMsg` request if the merkle proving is failed
- note, for backward compatibility, the empty merkle proof as well as the request auxiliary data will still be returned in les2/3 protocol no matter the proving is successful or not
- the proving failure can happen e.g. request the proving for a non-included entry in helper trie(unstable header)

les: remove useless protocol defines

---

cmd/geth/config.go
cmd/utils/flags.go
metrics/config.go

closes https://github.com/ethereum/go-ethereum/issues/22007
```
./geth --metrics --metrics.influxdb  dumpconfig
```

cmd/geth: dump config for metrics

---

core/blockchain_snapshot_test.go
core/state/snapshot/generate.go
core/state/snapshot/journal.go

This PR fixes a flaw in the snapshot.
```
0. Have a good snapshot
1. Start geth without --snapshot, import a few blocks
2. Start geth with --snapshot, it starts deleting it
3. Crash
4. Restart Geth
WARN [01-12|20:47:02.323] Loaded snapshot journal                  diskroot="fc6ca8…0440f3" diffs=unmatched
[...]
BAD BLOCK
```
In the snapshot, we have three different components:
- snapshot root: indicates the state hash of the disk layer
- snapshot generator: indicates the status of the snapshot disk layer(generating, wiping, done)
- snapshot diff layer journal
In step 0, we have a complete snapshot, so the snapshot generator is marked as "DONE"
In step 1, we introduce the gap between the snapshot and chain, the snapshot becomes useless
In step 2, we try to wipe the entire stale snapshot
The …

core/state/snapshot: write snapshot generator in batch

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/cmd.go
cmd/utils/diskusage.go
cmd/utils/diskusage_windows.go
cmd/utils/flags.go

Adding warnings of low free disk space left and graceful shutdown when there is not enough space left.

cmd/geth: Graceful shutdown if disk is full

---

eth/config.go
eth/gen_config.go
les/client_handler.go
les/commons.go
les/sync.go
les/sync_test.go
les/test_helper.go

This PR introduces a new config field `SyncFromCheckpoint` for light client. 
In some special scenarios, it's required to start synchronization from some arbitrary checkpoint or even from the scratch. So this PR offers this flexibility to users so that the synchronization start point can be configured.
There are two relevant configs: `SyncFromCheckpoint` and `Checkpoint`.
- If the `SyncFromCheckpoint` is true, the light client will try to sync from the specified checkpoint.
- If the `Checkpoint` is not configured, then the light client will sync from the scratch(from the latest header if the database is not empty)
Additional notes: these two configs are not visible in the CLI flags but only accessable in the config file.
Example Usage:
```
[Eth]
SyncFromCheckpoint = true
[Eth.Checkpoint] …
```

eth, les: add new config "syncFromCheckpoint"

---

go.mod
go.sum

https://github.com/hashicorp/golang-lru/commit/80c98217689d6df152309d574ccc682b21dc802c

go.mod: upgrade to golang-lru v0.5.5

---

accounts/abi/bind/backends/simulated.go
core/blockchain.go
core/state/database.go
core/state/state_object.go
core/state/state_test.go
core/state/statedb.go
core/state/statedb_test.go
core/state/trie_prefetcher.go
crypto/crypto.go
crypto/crypto_test.go
eth/api_tracer.go
miner/worker.go

This is part 2 of https://github.com/ethereum/go-ethereum/pull/20796. It's very much work in progress, and a bit hacky. 
Feedback regarding the design is appreciated

core: improve trie updates (part 2)

---

eth/backend.go
eth/filters/api.go
eth/filters/filter_system_test.go
les/client.go

This PR adds a test reproducing #22131. It fails reliably on my machine but I could increase the tx bombardment time range to increase the odds of hitting the bug.

eth/filters: fix potential deadlock in filter timeout loop

---

event/subscription.go
event/subscription_test.go

Added a possibility to pass a custom callback function which will be invoked on subscription error.
This change will allow clients to receive the original subscription error and perform some additional actions like logging to make debugging easier.

event: resubscribe with error handler

---

trie/proof.go
trie/proof_test.go

Fixes the issue described https://github.com/ethereum/go-ethereum/pull/22179#issuecomment-763672300
It's a special case that the trie only has a single trie node and the range proof only contains a single element.
```
TRACE[01-20|15:53:31.702] Fetching range of accounts               id=nice-a reqid=4037200794235010051 root="c2661f…b0463a" origin="000000…000000" limit="0fffff…ffffff" bytes=512.00KiB
TRACE[01-20|15:53:31.702] Delivering range of accounts             id=nice-a reqid=4037200794235010051 hashes=1 accounts=1 proofs=1 bytes=210.00B
panic: interface conversion: trie.node is nil, not *trie.fullNode
goroutine 20 [running]:
github.com/ethereum/go-ethereum/trie.unsetInternal(0xa5c2a0, 0xc00007ed70, 0xc00002b9a0, 0x41, 0x41, 0xc00002b9f0, 0x41, 0x41, 0x20, 0xa5c1a0) …
```

trie: fix range prover

---

common/mclock/mclock.go
common/mclock/mclock.s
go.mod
go.sum

It takes three lines of code to get to runtime.nanotime, no need to pull a dependency for that.

common/mclock: remove dependency on github.com/aristanetworks/goarista

---

eth/downloader/downloader.go
eth/handler.go
eth/protocols/snap/peer.go
eth/protocols/snap/protocol.go
eth/protocols/snap/sync.go
eth/protocols/snap/sync_test.go

This is a work in progress - the tests now just hang, which isn't ideal. However, the tests do enable some fairly deep testing of the snap protocol, and the reason I rebased it again and am working on it, is to see if it can be used to trigger https://github.com/ethereum/go-ethereum/issues/22172. 
Also, in general, I think it would be good to have these kinds of fairly high-level protocol tests.

eth/protocols/snap: snap sync testing

---

graphql/graphql.go
graphql/graphql_test.go

This PR fixes the `Status` field to be decimal instead of a hex string, as called for by the [spec](https://eips.ethereum.org/EIPS/eip-1767).

graphql: change receipt status to decimal instead of hex

---

go.mod
go.sum

This updates the goupnp dependency, fixing https://github.com/huin/goupnp/issues/33

go.mod: upgrade github.com/huin/goupnp

---

core/state/snapshot/difflayer.go

- data size check loop can be merged with sanity check routine.

snapshot: merge loops for better performance

---

eth/handler.go
eth/peerset.go
eth/sync.go
p2p/peer.go

This PR attempts to reseve half the peer slots for `snap/1` peers, if we're actively trying to perform a snap sync. 
Some caveats
- If we're just running `--snapshot`, but `syncmode=fast`, then it should do nothing
- If we're running `--snapshot`, and`syncmode=snap`, but are done syncing, it should do nothing

eth, eth/downloader,p2p: reserve half peer slots for snap peers during snap sync

---

internal/ethapi/api.go

Open for discussion, not sure if we should add this or not.
This PR adds some more infos to the logs when submitting a tx. The idea being that the current logs are enough to find the tx infos if it gets listed in some block explorer, but if it does not (e.g. lost tx or nonce gap), there's no way to see what was being submitted. This can cause problems debugging nonce issues and/or resubmitting lost txs manually.

internal/ethapi: print tx details when submitting

---

core/state/dump.go

@winsvega reported a [crash](http://retesteth.ethdevops.io/results/log//2021-01-24-1611447623-t8ntool.txt) found via retesteth, introduced in commit #ddadc3d2 . 
Repro:
`alloc.json`: 
```json
{
"a94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
"balance": "0x5ffd4878be161d74",
"code": "0x",
"nonce": "0xac",
"storage": {
"0x0a": "0x01"
}
},
"0x8a8eafb1cf62bfbeb1741769dae1a9dd47996192":{
"balance": "0xfeedbead",
"nonce" : "0x00"
}
}
```
WIthout this PR: 
```
./evm t8n --input.alloc=./alloc.json --input.txs=./testdata/1/txs.json --input.env=./testdata/1/env.json --output.alloc=stdout
INFO [01-24|13:33:13.295] rejected tx                              index=1 hash="0557ba…18d673" from=0x8A8eAFb1cf62BfBeb1741769DAE1a9dd47996192 error="nonce too low: address …
```

core/state: fix panic in state dumping

---

consensus/ethash/consensus.go
core/headerchain.go
core/rawdb/freezer_table.go

This is a follow up to https://github.com/ethereum/go-ethereum/pull/21471. 
Charts and niceties can be found here: https://github.com/holiman/headerimport/blob/main/README.md
This PR implements the following modifications
- Do not shortcut check if block is present, thus avoid disk lookup
- Don't check hash ancestry in early-check (it's still done in parallel checker)
- Don't check for abort between every header EDIT: this optimization was reverted
- Don't check `time.Now` for every single header
TLDR: With these changes, writing 1M headers goes down to `62s` for 1M headers, from `106s` on (old) master, and `80s` on PR 21471.

core: speed up header import

---

accounts/scwallet/securechannel.go
go.mod
go.sum

github.com/wsddn/go-ecdh is a wrapper package for ECDH with any elliptic curve.
Since 'generic' ECDH is not required in accounts/scwallet (the curve is always secp256k1),
we can just use the standard library and our own crypto libraries to perform
ECDH and save a dependency.

accounts/scwallet: use go-ethereum crypto instead of go-ecdh

---

rpc/client.go

It never worked, whisper uses polling.

rpc: deprecate Client.ShhSubscribe

---

les/utils/limiter.go
les/utils/limiter_test.go
les/utils/weighted_select.go

This PR is a separated part of the les4 code in order to make the review process easier.

les/utils: UDP rate limiter

---

cmd/clef/main.go

Fixes an issue with file permissions on windows. I'm not a "windows" guy, and don't know what the _proper_ way would be to ensure correct permissions, so this PR just disables the check. 
I've searched and didn't find any obvious results on what the corresponding check for windows would be (pointers appreciated).

cmd/clef: don't check file permissions on windows, closes #20123

---

docs/_interface/Managing-your-accounts.md

Typo: the `'` char was located at the wrong place. 
The`curl` command, without specifying the content-type headers, complains about invalid content type.

Typo in curl command, include content-type header

---

docs/_dapp/native-bindings.md

Misspelling of words

---

eth/handler.go
eth/handler_eth.go
eth/handler_eth_test.go
eth/handler_snap.go
eth/peer.go
eth/peerset.go
eth/protocols/eth/handler.go
eth/protocols/eth/protocol.go
eth/protocols/snap/handler.go
eth/protocols/snap/protocol.go
eth/sync.go
eth/sync_test.go
p2p/peer.go

In the current code, a peer is allowed to join both on the `eth` and `snap` protocols. Although both protocol handlers enforces that `snap-requires-eth`, this is done with a timeout mechanism after the peer was added to all internal structs. Since we allowed a peer to (maliciously) connect with only `snap`, we needed the snap handler to clean out the peer on disconnect, similar to how `eth` does when peer is dropped. This resulted in double-cleanups during normal disconnects since both protocols tries to racily clean.
This PR solves the issue by adding doing eth/snap registration in two phases. Snap is registered as a protocol extension in the peerset and eth consumes (or blocks until it can) this registration. Only then will eth proceed. All submodule (downloader, syncer, fetcher) …

eth: check snap satelliteness, delegate drop to eth

---

core/tx_pool.go

This pr fixes an issue where local transactions that were included in the chain before a `SetHead` could not be replayed since the txpool still had the old statedb after the `setHead` and would reject them with `nonce to low`.
For a repro see the linked issue
resolves: https://github.com/ethereum/go-ethereum/issues/19346

core: properly reset the statedb on sethead

---

consensus/clique/clique.go
consensus/consensus.go
consensus/ethash/algorithm_test.go
consensus/ethash/consensus.go
consensus/ethash/ethash_test.go

`VerifySeal` became unreferenced when the remote miner API was moved into the consensus engine package.
For the eth2 merge, it would make my life a bit simpler not to have to care about that, since all I have to care about is disable the call to `verifySeal` in `VerifyHeader` once the merge block has passed.

consensus: Remove seal verification from the consensus engine interface

---

cmd/utils/flags.go

This PR enables snapshots (not snap sync! we need serving it first by a critical mass) by default. It can be disabled via `--snapshot=false`. I don't want to add another flag since we expect this to be the norm. no no need to further bloat the API surface.

cmd/utils: enable snapshots by default

---

core/state/pruner/pruner.go

I split up the compactor to have periodic progress reports, but unfortunately I messed it up and instead of having ranges of `0x0` to `0x1`, `0x1` to `0x2` I had `0x00` to `0x01` and `0x01` to `0x02`. Thus I only compacted 1/16th of the entire range. This PR solves it by shifting the prefix byte to the high bits.

core/state/pruner: fix compaction after pruning

---

core/state/pruner/pruner.go

Fix for https://github.com/ethereum/go-ethereum/pull/22291#discussion_r572263644

core/state/pruner: fix compaction range error

---

internal/debug/flags.go

This PR adds a switch `--logjson` which if enabled makes the client format logs with JSON.
Something I'm not clear about is if setting `glogger` needs to be done in `init`. I had to move it to `Setup` to have access to the flags. Could this have an unintended consequence?
Fixes #21926

internal/debug: add switch to format logs with json

---

accounts/abi/abi_test.go
accounts/abi/bind/bind_test.go
accounts/abi/bind/template.go

There was a dormant error with structured inputs that failed unpacking.
This commit fixes the error by switching from regular casting to the better abi.ConvertType function.
It also adds a test for calling a view function that returns a struct
closes https://github.com/ethereum/go-ethereum/issues/22219

accounts/abi/bind: fixed unpacking error

---

cmd/utils/flags.go
eth/ethconfig/config.go

https://twitter.com/peter_szilagyi/status/1358767100995784704 .
This PR changes the default number of indexed transaction from infinite to the most recent 1 year (assuming block times of around 13-14s).
The reasoning behind this change is that currently on mainnet there are over 1 billion transactions. Just tracking the `hash->blocknum` mapping weighs 33GB on the database (requires SSD speeds due to the hash keying) and represents 3/5th of the database entry count, which makes trie operations and compactions exceedingly expensive.
Without any form of pruning, the transaction index dataset grows indefinitely. We must bite the bullet and have normal full nodes retain meaningful history, but not indefinite.
Operators still wishing to index all transactions since genesis can run geth with …

cmd/utils, eth/ethconfig: unindex txs older than ~1 year

---

cmd/devp2p/README.md

This PR fixes the documentation for the eth test suite, as the `fullchain.rlp` file is now named `chain.rlp`.

cmd/devp2p: fix documentation for eth-test

---

core/blockchain.go

When adding the background trie prefetcher, I've used defers to make sure the prefetchers are stopped irrelevant what error path the importer exits on. Learnt once again that defer in a loop is a horrible idea, because it kept references to old state imported in the same batch. On the Shanghai attack range, this caused a temporary memory blowup, which if enough blocks were imported in a single batch could cause a significant RAM spike.
Shoutout to [Michael](https://twitter.com/michael1011at/status/1359817492873568262) for finding this issue.

core: fix temp memory blowup caused by defers holding on to state

---

les/handler_test.go
les/odr_test.go
les/protocol.go
les/request_test.go
les/test_helper.go

This PR enables LES/4, allowing connection to tx unindexed servers and fixing TestPriorityClient.

les: enable les/4 and add tests

---

.golangci.yml
cmd/utils/diskusage.go

Workaround to get geth to build on FreeBSD. Fixes #22309.

cmd/utils: add workaround for FreeBSD statfs quirk

---

cmd/geth/consolecmd.go

cmd/geth: fix js unclean shutdown

---

docs/_clef/apis.md
docs/_dapp/tracing.md
docs/_developers/devguide.md
docs/_getting-started/dev-mode.md
docs/_getting-started/index.md
docs/_getting-started/private-net.md
docs/_interface/Command-Line-Options.md
docs/_interface/JavaScript-Console.md
docs/_interface/Private-Network.md
docs/_interface/mining.md
docs/_rpc/ns-debug.md
docs/_rpc/ns-eth.md

Updating docs according to #22263 (issue: #22141)

gh-pages: remove mention of deprecated flags

---

rpc/client_test.go

Fixes #22314.
The `TestClientNotificationStorm` test checks that a storm of client notification subscriptions is detected and an error is returned. For whatever reason, FreeBSD seems to handle the storm a tiny bit better than other systems, and therefore no error is raised. Bumping the number of requests by 1000 causes the expected buffer flood and an error is correctly reported.

rpc: increase the number of subscriptions in storm test

---

trie/sync.go

This PR fixes
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7ed606]
goroutine 2907 [running]:
github.com/ethereum/go-ethereum/trie.(*SyncBloom).Add(0x0, 0xc023631818, 0x20, 0x20)
/work/src/github.com/ethereum/go-ethereum/trie/sync_bloom.go:161 +0x26
github.com/ethereum/go-ethereum/trie.(*Sync).Commit(0xc01b891e00, 0x159fb40, 0xc007dd3180, 0x40, 0xc0236319f8)
/work/src/github.com/ethereum/go-ethereum/trie/sync.go:316 +0x18c
github.com/ethereum/go-ethereum/eth/downloader.(*stateSync).commit(0xc035672a00, 0x1, 0xc00032bc00, 0x0)
/work/src/github.com/ethereum/go-ethereum/eth/downloader/statesync.go:417 +0x99 …
```

trie: fix bloom crash on fast sync restart

---

core/state/snapshot/snapshot.go
core/state/snapshot/snapshot_test.go

This is a relatively tiny change with non-obvious refactors.
Fixes an issue where the snapshot based state pruner fails due to not enough diff layers.
The snapshots have a `Cap` functionality, which takes the snapshot tree (disk layer + diff layer tree on top) and limits it to a number of requested layers, merging anything above the limit downwards. The goal of `Cap` is to ensure that we always have 128 recent block's state available in memory, but anything above that can be pushed to disk. Turns out the definition of "retain 128 layers" is not that obvious.
Before diving into the problem, an important detail is that although snapshots have 2 types of layers (diskLayer backed by the database and diffLayer backed by memory), it actually differentiates the bottom most diffLayer from the …

core/state/snapshot: ensure Cap retains a min number of layers

---

eth/downloader/downloader.go
eth/protocols/snap/protocol.go
eth/protocols/snap/sync.go

https://github.com/ethereum/go-ethereum/pull/22179 introduced a slight regression when defining a new `errCancelled` error for snap sync. Whilst differentiating success from cancellation might be necessary, the downloader specifically handled state cancellations, which the new cancellation type broke. This PR just ensures that the downloader reacts the same way to snap and fast sync terminations.

eth: fix snap sync cancellation

---

eth/handler.go
eth/protocols/eth/broadcast.go

This PR optimizes the broadcast loop. Instead of iterating twice through a given set of transactions to weed out which peers have and which do not have a tx, to send/announce transactions, we do it only once.

eth/handler, broadcast: optimize tx broadcast mechanism

---

core/state/statedb.go

This PR attempts to fix an issue that was found on YoloV3, where the sealer does not deliver on the `snap/1` protocol. The reason for this, is that the `state` which the miner operates on does not have access to the `snap`, and thus is forced to use the trie-backend for reading and cannot write updates to the snapshot tree 
On mainnet, that would be bad, because whenever a miner mines a block, it would cause a gap in the snapshot tree, making the miner fall out of sync with the snapshot and essentially nuking the snapshot functionality. Perhaps also going into regenerate-mode again and again. 
This PR is a hacky first attempt to fix it. It does address the issue, but perhaps not optimally so, and there's an open question how we should handle the case where the `snapDestructs` are …

core/state: copy the snap when copying the state

---

rlp/decode.go
rlp/decode_test.go

@fjl (since you appear a lot in the rlp git history): This fixes a bug resulting from the combination of three factors:
1. `encReader.Read()` returning `EOF` when a successful read (i.e. where `len(b)` bytes were read) reaches the end.  This, in itself, is not a bug, since the docs for `io.Reader` say returning EOF in such cases is allowed (but not required). See https://github.com/ethereum/go-ethereum/blob/1489c3f4942aa50bb97659d800e9c2840f285dfc/rlp/encode.go#L271-L280
2. `Stream.readFull()` giving `ErrUnexpectedEOF` when it gets an `EOF`, even if the read was successful (i.e. if `len(buff)` bytes were read). See https://github.com/ethereum/go-ethereum/blob/1489c3f4942aa50bb97659d800e9c2840f285dfc/rlp/decode.go#L954-L956
3. An inconsistency in `bufio.Reader.Read()` in whether or not it …

rlp: handle case of normal EOF in Stream.readFull()

---

node/rpcstack.go

This PR does two things: 
- ~~If `geth --dev --ws --ws.port 0 --http --http.port 0` is used, then ws and http are both randomized, to different ports.~~
- If `geth --dev --ws --ws.port 9999 --http --http.port 9999`, then it shows in the logs that, yes, websocket is up, even if it's on the same port. 
```
INFO [02-11|10:00:53.477] WebSocket enabled                        url=ws://127.0.0.1:9999
INFO [02-11|10:00:53.477] HTTP server started                      endpoint=127.0.0.1:9999 prefix= cors= vhosts=localhost
```

node: show websocket url in logs

---

p2p/dnsdisc/client.go
p2p/dnsdisc/client_test.go
p2p/dnsdisc/sync.go

In the random sync algorithm used by the DNS node iterator, we first pick a random
tree and then perform one sync action on that tree. This happens in a loop until any
node is found. If no trees contain any nodes, the iterator will enter a hot loop spinning
at 100% CPU.
The fix is complicated. The iterator now checks if a meaningful sync action can
be performed on any tree. If there is nothing to do, it waits for the next root record
recheck time to arrive and then tries again.
Fixes #22306

p2p/dnsdisc: fix hot-spin when all trees are empty

---

les/client.go
les/clientpool.go
les/commons.go
les/server.go
les/vflux/server/balance_test.go
les/vflux/server/balance_tracker.go

This PR fixes a light server bug that was introduced by the refactoring of the client pool and adds a unit test. The exponential balance expiration did not work correctly because the expirer state was saved on shutdown but not loaded at startup, therefore the calculated balance values were off. Luckily currently only the negative balances of free clients were used in production so the only issue this bug has caused was that some free clients were treated unfairly by some servers. Still, this bug can negatively affect the usability of LES so this fix should be merged and deployed to the bootnodes ASAP.
Note: the PR also moves client balances to a new and separate database. I wanted to do this change anyways because the balances do not belong to the chain db and this is a good moment …

les: fix balance expiration

---

go.mod
les/handler_test.go
les/peer.go
les/protocol.go
les/server_handler.go
les/server_requests.go
les/test_helper.go
oss-fuzz.sh
tests/fuzzers/les/debug/main.go
tests/fuzzers/les/les-fuzzer.go

This PR refactors the LES server handler in order to make fuzzer testing possible and implements the fuzzer.
Replaces https://github.com/ethereum/go-ethereum/pull/22173 and https://github.com/ethereum/go-ethereum/pull/22237

tests/fuzzers/les: add fuzzer for les server handler

---

les/server_handler.go
les/server_requests.go

This PR cleans up the server handler a bit. But essentially nothing changed.

les: clean up server handler

---

cmd/geth/chaincmd.go
cmd/geth/dbcmd.go
cmd/geth/main.go
cmd/utils/flags.go
core/rawdb/database.go
ethdb/leveldb/leveldb.go
internal/flags/helpers.go

This PR supersedes https://github.com/ethereum/go-ethereum/pull/21991 and https://github.com/ethereum/go-ethereum/pull/21887 (those PRs contain more info and examples. 
This PR introduces
- `db.put` to put a value into the database
- `db.get` to read a value from the database
- `db.delete` to delete a value from the database
- `db.stats` to check compaction info from the database
- `db.compact` to trigger a db compaction
It also moves `inspectdb` to `db.inspect`

cmd/geth: add db commands: stats, compact, put, get, delete

---

cmd/geth/main.go
cmd/utils/flags.go
eth/api_backend.go
eth/backend.go
internal/ethapi/api.go
internal/ethapi/backend.go
les/api_backend.go
les/client.go
node/config.go

This PR prevents users from submitting transactions without EIP-155 enabled.
Replay protection is important so we should gently force our users to use it.
It changes the JSON-RPC API quite significantly, so if you see the "only replay-protected (EIP-155) transactions allowed over RPC" error, you know that you need to update your signer.
To test:
```go
cl, sk := getRealBackend()
fakeTx := types.NewTransaction(0, common.HexToAddress(ADDR), big.NewInt(0), 21000, big.NewInt(1), nil)
noneip, err := types.SignTx(fakeTx, types.HomesteadSigner{}, sk)
if err != nil {
panic(err)
}
if err := cl.SendTransaction(context.Background(), noneip); err != nil {
fmt.Println(err) // Prints "only replay-protected (EIP-155) transactions allowed over RPC"
}
eip155, err := types.SignTx(fakeTx, …
```

internal/ethapi: disable sending of non eip155 replay protected tx

---

cmd/utils/flags.go

This PR is another feature flip for 1.10, disabling the collection of trie preimages by default. These are only used by Remix debugging and there's no reason to have everyone track them. It shaves off about 5GB of a mainnet node. Note, existing data will not be cleaned from disk.

cmd/utils: disable caching preimages by default

---

eth/protocols/snap/sync.go

I accidentally left the snap sync resumption logs on Error to see what's going on without the noise. This PR lowers it back down to debug.

eth/protocols/snap: lower abortion and resumption logs to debug

---

cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go
les/server.go

This PR adds a more CLI flag, so that the les-server can serve light clients even the local node is not synced yet.
This functionality is needed in some testing environments(e.g. hive). After launching the les server, no more blocks will be imported so the node is always marked as "non-synced".

cmd, eth, les: enable serving light clients when non-synced

---

cmd/devp2p/README.md
cmd/devp2p/internal/ethtest/eth66_suite.go
cmd/devp2p/internal/ethtest/eth66_suiteHelpers.go
cmd/devp2p/internal/ethtest/suite.go
cmd/devp2p/internal/ethtest/transaction.go
cmd/devp2p/internal/ethtest/types.go
cmd/devp2p/rlpxcmd.go
go.mod

This PR adds the eth66 test suite to the devp2p rlpx test suite, duplicating the tests found in the eth test suite and also adding a few eth66-specific tests.

cmd/devp2p: add eth66 test suite

---

internal/web3ext/web3ext.go
les/client.go
les/client_handler.go
les/peer.go
les/vflux/client/queueiterator_test.go
les/vflux/client/serverpool.go
les/vflux/client/serverpool_test.go
les/vflux/client/valuetracker.go
les/vflux/client/valuetracker_test.go

This PR moves the server pool into the `les/vflux/client` package where the rest of the peer logic is, leaving package `les` for client functionality and protocol implementation. The value tracker is also created by the server pool. Only the `NodeValueTracker` of individual connected nodes is referenced by `serverPeer` in order to provide service quality feedback for the peer logic.
Replaces https://github.com/ethereum/go-ethereum/pull/22297
Fixes https://github.com/ethereum/go-ethereum/issues/22259
Note: a subsequent PR will move the `clientPool` into `les/vflux/server`, removing all peerset related complexity and all references to `NodeStateMachine` from package `les`.

les: move server pool to les/vflux/client

---

rpc/http_test.go
rpc/testservice_test.go
rpc/websocket.go
rpc/websocket_test.go

This makes the WebSocket message size limit independent of the
limit used for HTTP requests.

rpc: add separate size limit for websocket

---

cmd/geth/config.go
cmd/geth/main.go
cmd/puppeth/wizard_genesis.go
cmd/utils/flags.go
core/forkid/forkid_test.go
core/genesis.go
core/state_transition.go
core/tx_pool.go
core/types/transaction_signing.go
core/vm/contracts.go
core/vm/evm.go
core/vm/interpreter.go
core/vm/jump_table.go
core/vm/runtime/runtime.go
eth/backend.go
eth/ethconfig/config.go
eth/tracers/api.go
les/client.go
light/txpool.go
params/config.go
tests/init.go
tests/state_test_util.go

Block number decisions: https://github.com/ethereum/pm/issues/248#issuecomment-782106181
Berlin hard fork details: https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/berlin.md

all: define and enable the Berlin hard fork on all networks

---

docs/_rpc/ns-debug.md

We didn't have `debug.traceCall` documented, so I lifted it over from https://github.com/ethereum/go-ethereum/pull/21338 . @MariusVanDerWijden PTAL

document debug.traceCall

---

core/state/pruner/pruner.go

```
root@mon02:/datadrive# docker run -v /datadrive:/datadir -it ethereum/client-go  --datadir=/datadir/geth  snapshot prune-state                                                                  ...  
INFO [02-26|12:40:18.730] Iterating state snapshot                 accounts=0 slots=0 elapsed="118.987µs"
INFO [02-26|12:40:26.730] Iterating state snapshot                 accounts=126708 slots=186080 elapsed=8.000s      eta=2h5m46.954s
INFO [02-26|14:00:38.239] Iterated snapshot                        accounts=119817571 slots=414421589 elapsed=1h20m19.509s
INFO [02-26|14:00:59.508] Writing state bloom to disk              name=/datadir/geth/geth/statebloom.0xef2542a6cd3a64ca7188de8d682a3fad85c9e9e732df20a4d99da177263a7fa4.bf.gz
INFO [02-26|14:03:32.428] State bloom filter committed …
```

core/state: fix eta calculation on pruning

---

common/prque/lazyqueue.go
common/prque/lazyqueue_test.go
les/client.go
les/clientpool.go
les/clientpool_test.go
les/enr_entry.go
les/server.go
les/vflux/client/serverpool.go
les/vflux/client/serverpool_test.go
les/vflux/requests.go
les/vflux/server/balance.go
les/vflux/server/balance_test.go
les/vflux/server/prioritypool.go
les/vflux/server/prioritypool_test.go
les/vflux/server/service.go
p2p/discover/v5_udp.go
p2p/discover/v5_udp_test.go
p2p/nodestate/nodestate.go

This PR implements the first one of the "lespay" UDP queries which is already useful in itself: the capacity query. The server pool is making use of this query by doing a cheap UDP query to determine whether it is worth starting the more expensive TCP connection process.

les: UDP pre-negotiation of available server capacity

---

core/rawdb/chain_iterator.go

This PR fixes an issue in the transaction indexer. The case is that: if there is NO transaction included in the `unindexed` blocks, so the database batch is empty. But in this case, the indexing tail should be updated anyway.

core/rawdb: fix the transaction indexer

---

params/config.go

Ropsten is not updated. According to the devp2p crawler, there is only one LES server in the rospten. My client can't get connected anyway. So there is no difference to update or not.

params: update chts

---

core/forkid/forkid_test.go
params/config.go

Since there's some contention around Berlin, this PR removes all the hard coded block numbers until there's consensus. We don't want to hold up the v1.10.0 release for a potentially unknown amount of time.

core/forkid, params: unset Berlin fork number

---

les/client.go
les/vflux/client/serverpool.go
les/vflux/client/serverpool_test.go

This PR fixes a panic caused by the ServerPool UDP pre-negotiantion when --nodiscover is specified.

les: fix nodiscover option on the client side

---

tests/block_test.go
tests/gen_stenv.go
tests/gen_sttransaction.go
tests/gen_vmexec.go
tests/state_test.go
tests/state_test_util.go

Updates marshalling and execution for the new access list format in the state tests
depends on https://github.com/ethereum/go-ethereum/pull/21502

Access list state test format

---

build/ci.go

Fix a build regression caused by updating builders to Bionic, and failing due to an incompatible `debsrc` behavior.

build: fix PPA failure due to updated debsrc

---

core/forkid/forkid_test.go
params/config.go

Reverts ethereum/go-ethereum#22413, inserting the originally decided Berlin block numbers back.

Revert "core/forkid, params: unset Berlin fork number"

---

core/types/transaction.go

Current master allocates a lot of unnecessary big integers when comparing gas prices.
Since the tx_list (part of the txpool) relies heavily on comparing transactions by gas price, this does ~1.6% of all allocations unnecessarily. 
This PR directly compares the inner gas prices without creating a new big int in the process
```
Total: 479893007
ROUTINE ======================== github.com/ethereum/go-ethereum/core/types.(*Transaction).GasPrice in github.com/ethereum/go-ethereum/core/types/transaction.go
10764599   15876467 (flat, cum)  3.31% of Total
.          .    256:
.          .    257:// Gas returns the gas limit of the transaction.
.          .    258:func (tx *Transaction) Gas() uint64 { return tx.inner.gas() }
.          .    259:
.          .    260:// GasPrice returns the gas …
```

core/types: reduce allocations in GasPriceCmp

---

les/client.go
les/server.go

This _might_ solve https://github.com/ethereum/go-ethereum/issues/22458

les: add trailing slash to metric namespace

---

p2p/enr/enr.go
p2p/enr/enr_test.go

Given a list with less than two elements, DecodeRLP returned rlp.EOL,
leading to decoding issues in outer decoders.

p2p/enr: fix decoding of incomplete lists

---

cmd/geth/snapshot.go

When syncing with an non-default ancient data directory, the `snapshot` sub-commands aren't usable because Geth can't open the database. This PR adds the missing `--database.ancient` flags to the `snapshot` sub-commands

cmd: add ancient datadir flag to snapshot subcommands

---

eth/state_accessor.go
eth/tracers/api.go
les/state_accessor.go

....during tracing. Fixes https://github.com/ethereum/go-ethereum/issues/22475

eth/state, les/state, et/tracers: properly init statedb accesslist

---

les/server_requests.go
les/test_helper.go
tests/fuzzers/les/les-fuzzer.go

The oss-fuzz fuzzer has been reporting some failing testcases for les. They're all spurious, and cannot reliably be reproduced. However, running them showed that there was a goroutine leak: the tests created a lot of new clients, which started an exec queue that was never torn down. 
This PR fixes the goroutine leak, and also a log message which was erroneously formatted. 
`
WARN [03-08|10:35:15.880] GetBlockHeaders skip overflow attack     id=0000000000000000 conn= current=0 skip=18446744073709551615 next=0 attacker="[123 10 32 32 34 101 110 111 100 101 34 58 32 34 101 110 111 100 101 58 47 47 110 117 108 108 46 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 …

tests/fuzzers: fix goroutine leak in les fuzzer

---

core/types/hashing.go
core/types/hashing_test.go
core/types/receipt.go
core/types/transaction_signing.go

Responding to these comments: 
* https://github.com/ethereum/go-ethereum/pull/21502/files#r579010962
* https://github.com/ethereum/go-ethereum/pull/21502/files#r579021565
* https://github.com/ethereum/go-ethereum/pull/21502/files#r579023510
* https://github.com/ethereum/go-ethereum/pull/21502/files#r578983734

core/types: improve comments in new EIP-2718 code

---

core/rawdb/chain_iterator.go
core/rawdb/chain_iterator_test.go
rlp/iterator.go

In reference to https://github.com/ethereum/go-ethereum/issues/22453 
While investigating that, I found that the transaction indexer / unindexer used a shortcut to do hashing: writing the raw `rlp` into the hasher, without going via object-form. This is a neat trick to save some cycles, however, due to the new hashing format of typed transaction, it does not produce correct hashes any longer. 
This PR therefore changes that, removes the use of rlp-direct-to-hasher and instead parses the full object form of the block body, and afterwards does a full hashing. The `rlp.ListIterator` is currently still left in there, perhaps we want to revisit that optimization later and reapply it. 
This PR also adds better log output, so we can see what blocks are causing problems.

core/rawdb: fix transaction indexing/unindexing hashing error

---

les/api.go

This PR improves the LES priority API functions by accepting both raw hex node IDs (like before) and full enode strings.
Now each of the following forms are accepted:
```
les.addBalance("8d3797578a393adbe77af76c6d0f6fee8c4d402d235ad9fa93f8f20eb9bc0dad", 10000000000000)
les.addBalance("0x8d3797578a393adbe77af76c6d0f6fee8c4d402d235ad9fa93f8f20eb9bc0dad", 10000000000000)
les.addBalance("enode://4f3fb4e87c51057126d79ea0473bb7432b056456737e77e9977c5a72268b31a42dcaf2b7f0c03bc656fb0b8da093490c22cdc972494c9801f0858e5a903c693b@127.0.0.1:37214", 10000000000000)
```

les: allow either full enode strings or raw hex ids in the API

---

cmd/devp2p/internal/ethtest/eth66_suiteHelpers.go

This PR fixes an issue with the eth66 test suite where, during a `readAndServe` when the test is manually responding to `GetBlockHeader` requests, it now responds with a `BlockHeaders` eth66 packet that includes the inbound request ID.

cmd/devp2p/internal/ethtest: return request ID in BlockHeaders response

---

ethclient/ethclient_test.go

The `wantErr` field was disused, and the error
returned by ec.HeaderByNumber was not properly
tested.
This simplifies the error checking using
`errors.Is` and asserts that getting an expected
missing header returns `ethereum.NotFound`.
Also adds a nil check condition for header.Number
before using big.Int's Sign method.
Date: 2021-03-17 07:57:26-05:00

ethclient: fix error handling for header test

---

accounts/abi/bind/base.go

Adding the DryRun option to bind.TransactOpts will cause transact to return before sending the transaction. Allows checking signatures and cost.

abi/bind: add an option to dry run a transaction

---

consensus/ethash/ethash.go

remove unnecessary variable definition

consensus/ethash: remove unnecessary variable definition

---

p2p/dnsdisc/tree.go

Fixes https://github.com/ethereum/go-ethereum/issues/22532 
The calculation for maxChildren was wrong:
```
300 / 16 * (13 / 8) == 30
```
Should have been
```
300 / (16 * (13 / 8)) == 11
```
After fixing this, I also bumped `300` a bit, so instead of `11` we land at `13` as the max.

p2p/dnsdisc: fix flaw in dns size calculation

---

core/chain_indexer_test.go

Fixes #22318
I managed to reproduce the issue by commenting out this [line](https://github.com/ethereum/go-ethereum/blob/6ec15610443b28eabf665199f1dc5be2b3e3f7cb/core/chain_indexer_test.go#L228) to make [both](https://github.com/ethereum/go-ethereum/blob/6ec15610443b28eabf665199f1dc5be2b3e3f7cb/core/chain_indexer_test.go#L226) [timeouts](https://github.com/ethereum/go-ethereum/blob/6ec15610443b28eabf665199f1dc5be2b3e3f7cb/core/chain_indexer_test.go#L188). I think the problem is that as Peter pointed out `t.Fatal` is being called from a goroutine which is not the test's main routine. So I tried to stop `ChainIndexer.updateLoop` gracefully.

core: fix potential race in chainIndexerTest

---

cmd/devp2p/internal/ethtest/chain_test.go
cmd/devp2p/internal/ethtest/eth66_suite.go
cmd/devp2p/internal/ethtest/eth66_suiteHelpers.go
cmd/devp2p/internal/ethtest/suite.go
cmd/devp2p/internal/ethtest/types.go
cmd/devp2p/rlpxcmd.go

This PR fixes an issue where the eth test suite would also run eth66 protocol version tests against the node even if the node does not support eth66.

cmd/devp2p: only run eth66 tests against supporting node

---

cmd/devp2p/dns_route53.go
cmd/devp2p/dnscmd.go

AWS SDK v2 requires setting the region explicity.

cmd/devp2p: add flag for AWS region

---

cmd/devp2p/dns_route53.go

This PR fixes a regression introduced in https://github.com/ethereum/go-ethereum/pull/22360, when we updated to the `v2` of the AWS sdk, which causes current crawler to just get the same first `100` results over and over, and get stuck in a loop.

cmd/devp2p: fix error in updating the cursor when collecting route53 records

---

cmd/devp2p/internal/ethtest/eth66_suite.go
cmd/devp2p/internal/ethtest/suite.go

Add old block announcement test to eth test suite, checks to make sure old block announcement isn't propagated

cmd/devp2p: add old block announcement test to eth test suite

---

accounts/usbwallet/ledger.go
accounts/usbwallet/trezor.go
accounts/usbwallet/wallet.go

Adds a new method `SignTypedMessage` to the `accounts.Wallet` type which enables [EIP-712](https://eips.ethereum.org/EIPS/eip-712) signing with ledgers. For other wallet types it simply falls back to signHash.
Support for 712 style signatures was introduced in v1.5.0 of the ledger firmware, and is specified at https://github.com/LedgerHQ/app-ethereum/blob/master/doc/ethapp.asc#sign-eth-eip-712.
This PR does not expose the `SignTypedMessage` to clef or anywhere else, I mainly wanted it in [ethsign](https://github.com/dapphub/dapptools/tree/master/src/ethsign) which is really just a cli wrapper around these parts of the geth code.
I don't really know golang so bare with me here... At least I'm able to successfully perform EIP-712 signatures with a ledger with this PR.

accounts: eip-712 signing for ledger

---

cmd/geth/chaincmd.go
cmd/geth/dao_test.go
cmd/geth/dbcmd.go
cmd/geth/snapshot.go
cmd/utils/flags.go
core/bench_test.go
core/blockchain_repair_test.go
core/blockchain_sethead_test.go
core/blockchain_snapshot_test.go
core/blockchain_test.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/rawdb/database.go
core/rawdb/freezer.go
core/state/pruner/pruner.go
core/state/snapshot/disklayer_test.go
eth/backend.go
eth/filters/bench_test.go
eth/filters/filter_test.go
eth/protocols/eth/protocol_test.go
ethdb/leveldb/leveldb.go
les/client.go
les/server.go
node/node.go
node/node_test.go
trie/trie_test.go

This PR introduces the "Read-Only" database and fixes a few issues in the db commands.
Test cases
MakeChainDatabase
MakeChain

all: add read-only option to database

---

core/state/snapshot/snapshot.go

When building a snapshot on top of a parent, the parent may occasionally be missing (if there are many blocks imported whilst simultaneously mining a new block). In that case, the current code panics because the path that checks for missing parent already makes an interface conversion before `nil` check.
```
panic: interface conversion: interface is nil, not snapshot.snapshot
goroutine 92 [running]:
github.com/ethereum/go-ethereum/core/state/snapshot.(*Tree).Update(0xc02b51d100, 0x1881189dfd6131c7, 0x65806745df63f116, 0xeeb17030c8ccf09f, 0x8be3502ada3d5705, 0xf3286cf6afe5e4da, 0xebc572ab54e816af, 0x6e0e89ca9372a1c2, 0xaa34de51b47e9b97, 0xc087c97ce0, ...)
github.com/ethereum/go-ethereum/core/state/snapshot/snapshot.go:286 +0xff
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit(0x …
```

core/state/snapshot: fix panic on missing parent

---

eth/downloader/downloader.go
eth/handler.go
eth/protocols/snap/sync.go
eth/protocols/snap/sync_test.go

This PR removes the use of a bloom filter during snap sync. Bloom filters are nice, but for snap they don't really help _that_ much. We only ever want to do a bit of light healing on top of mostly correct state. 
In practice, however, if the user restarts the node, it will kick of an entire trie-iteration to filll the bloom filter, which is a bit counterproductive for a feature that was meant to accelerate things by keeping the disk IO down.

eth/protocols/snap, eth/downloader: don't use bloom filter in snap sync

---

internal/web3ext/web3ext.go
node/api.go
node/api_test.go

Corresponding CLI flags --rpc have been moved to --http.
This moves the admin module HTTP RPC start/stop
methods to an equivalent namespace.
This notes `admin.StartRPC` and `admin.StopRPC` as deprecated (and logs a `WARN` if called) but does not remove them.
Rel https://github.com/ethereum/go-ethereum/pull/22263
Date: 2021-03-08 08:00:11-06:00

internal/web3ext,node: migrate node admin API (Start|Stop)RPC->HTTP

---

p2p/server.go

Fix a minor typo and delete a useless `fd` parameter

p2p: fix minor typo

---

p2p/dnsdisc/client.go

This makes the resolver rate limit apply regardless of whether the record is already
cached. It helps avoid hot-spinning in pathological cases like:
it, _ := client.NewIterator(...)
it = enode.Filter(it, func(*enode.Node) bool { return false })
for it.Next() {}
Fixes #22509

p2p/dnsdisc: rate limit resolving before checking cache

---

core/vm/eips.go
core/vm/evm.go
core/vm/instructions.go
core/vm/instructions_test.go
core/vm/interpreter.go
core/vm/jump_table.go
core/vm/logger.go
core/vm/logger_json.go
core/vm/logger_test.go
core/vm/runtime/runtime_test.go
eth/tracers/tracer.go
eth/tracers/tracer_test.go

This is an alternative to https://github.com/ethereum/go-ethereum/pull/22276
- Fixes the `CaptureStart` api to include the `EVM`, thus being able to set the statedb early on. 
- While at it, I also exposed the struct we used internally in the interpreter to encapsulate the contract, mem, stack, rstack, so we pass it as a single struct to the tracers.

core, eth/tracer: initialize tracer statedb in CaptureStart

---

cmd/devp2p/dns_route53.go
cmd/devp2p/dns_route53_test.go

The AWS API returns quoted DNS strings, so we must encode the new value
before comparing it against the existing record content. This also changes the
logging a bit to be more helpful.
Replaces #22536.

cmd/devp2p: fix comparison of TXT record value

---

core/headerchain.go

Found by @samczsun, the header verification check is not randomized in certain conditions.

core: fix condition on header verification

---

eth/protocols/eth/handler.go
eth/protocols/snap/handler.go
metrics/histogram.go
p2p/metrics.go

Currently we have no insight into how much time serving specific network requests take. This is a problem because we can't correlate performance issues with network traffic. This PR adds a measurement to all `eth` and `snap` packet handlers to track the latency of handling each packet type in a histogram. Hopefully this will shed some light onto how much time we actually take to serve certain requests and what might influence it.
TL;DR: PR makes colored pixels

eth/protocols, metrics, p2p: add handler performance metrics

---

eth/protocols/eth/handler.go
eth/protocols/snap/handler.go
metrics/resetting_sample.go

This PR "fixes" the previous histograms by resetting them upon each pull/push.
The same way as with timers, the metrics library assumes that there's a constant stream of events we monitor. If a metric gets updated very rarely (e.g. eth/64 header request), the chart will be skewed because the metric will report the same value over and over and over ad infinitum (decaying ever so slowly to 0).
This PR uses @nonsense's resetting idea, just for histograms to reset them on retrieval.
The diff is visible on the screenshot below. The code was updated to this PR in the middle on the displayed run.

eth/protocols, metrics: use resetting histograms for rare packets

---

metrics/influxdb/influxdb.go

Our InfluxDB reporter always pushed the content of a histogram, even if it was empty. This is problematic, because no measurements results in a reported value of 0 for all percentiles. This PR stops reporting 0 values if no measurements are made.

metrics/influxdb: don't push empty histograms, no measurement != 0

---

eth/protocols/snap/sync.go

In case of a `snap` request timeout, there's no context printed, so we have no idea what exactly timed out. This PR adds the peer's ID and the request ID as contextual infos to the timeout logs.

eth/protocols/snap: add peer id and req id to the timeout logs

---

core/state/pruner/pruner.go

The main idea behind it is: the range compaction is very expensive
which can take a few hours to finish. During this long procedure,
a lot of exceptions can occur, e.g.
- Geth is killed manually
- Geth is killed because of machine crash
- etc
In order to minimize the effect of the exceptions, the compaction
is moved out of the pruning. So that even the compaction is not
finished, the pruning is regarded as done.

core/state/pruner: move the compaction out of the pruning procedure

---

core/chain_makers.go

This PR adds a `GetBalance()` method to `BlockGen` to allow for more complex transaction generation during chain creation. For example, we will be using the `GetBalance()` method in the [`hivechain` tool](https://github.com/ethereum/hive/tree/master/cmd/hivechain) in order to generate chains with more than 1 transaction per block.

core: add GetBalance method to block generation

---

cmd/puppeth/module_dashboard.go

So basically with nodejs 15, if no WORKDIR is specified, NPM is executed in the root of the container
closes https://github.com/ethereum/go-ethereum/issues/22439
see also https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for

cmd/puppeth: specify working directory for nodejs 15

---

eth/protocols/snap/handler.go
eth/protocols/snap/sync.go

This PR increases the static timeout on snap messages from `10` to `15` seconds, and also adds an internal timeout for serving trie nodes, whereby it will abort after `5` seconds and return the results to the remote side.

eth/protocols/snap: try to prevent requests timing out

---

cmd/geth/dbcmd.go

The `db getslots <storage_root>` can help investigate issues regarding data corruption

cmd/geth: add db dumptrie command

---

core/state/snapshot/snapshot.go
ethdb/leveldb/leveldb.go
ethdb/memorydb/memorydb.go

We've seen some high memory usage on Ropsten around block 6M when snapshots are enabled. Our hunch is that there might be some huge contract self-destruct that takes it's toll on the memory usage. This PR is a benchmark test to see if that's indeed the case or not.

core/state/snapshot, ethdb: track deletions more accurately

---

rpc/client_test.go
rpc/handler.go
rpc/subscription.go
rpc/websocket_test.go

This fixes a rare issue where the client subscription forwarding loop
would attempt send on the subscription's channel after Unsubscribe has
returned, leading to a panic if the subscription channel was already
closed by the user. Example:
sub, _ := client.Subscribe(..., channel, ...)
sub.Unsubscribe()
close(channel)
The race occurred because Unsubscribe called quitWithServer to tell the
forwarding loop to stop sending on sub.channel, but did not wait for the
loop to actually come down. This is fixed by adding an additional channel
to track the shutdown, on which Unsubscribe now waits.
Fixes #22322

rpc: tighter shutdown synchronization in client subscription

---

consensus/ethash/api.go
consensus/ethash/ethash_test.go
eth/api.go
ethstats/ethstats.go
internal/web3ext/web3ext.go
miner/miner.go

`SubmitHashrate` (little R) is an RPC API method. We can't capitalize `Rate` in it. Fixes https://github.com/ethereum/go-ethereum/issues/22602.

all: fix miner hashRate -> hashrate on API calls

---

core/state/snapshot/difflayer.go

I encountered this race condition and it happens at difflayer.go:223 wrt `dl.origin = origin` but .Storage uses `dl.origin` at `		return dl.origin.Storage(accountHash, storageHash)` in difflayer.go.

[core] Race condition on diffLayer

---

docs/_interface/Private-Network.md

The `--etherbase` parameter seems to be named `--miner.etherbase` now.

[DOCS] fix --miner.etherbase flag

---

graphql/graphql.go
graphql/graphql_test.go
graphql/schema.go

fixes #22487  this PR adds the ability to query the type and AccessTuple from graphql endpoint

graphql: add support for tx types and tx access lists

---

internal/debug/flags.go

This PR moves the flags `--debug`, `--backtrace` to the `log` namespace (i.e. `--log.backtrace`, etc.). It keeps the previous ones but marks them as deprecated. In case both the current and deprecated flags are passed, the deprecated has lower precedence.
I noticed that the `--memprofilerate` and `--blockprofilerate` are right now ineffective (they're always overridden even if `--pprof.memprofilerate` is not set). This is also fixed.

internal/debug: rename flags in log namespace, fix some pprof flags

---

cmd/geth/main.go
cmd/utils/flags.go

Move the cache sanity check to the SetEthConfig function to allow the config file to load
Fixes #21090

cmd/geth: move cache sanity check to SetEthConfig

---

consensus/ethash/algorithm.go

We should not use the magic number. Change `4` to `cacheRounds+1`

Change the progress log

---

eth/api.go
eth/api_backend.go
eth/protocols/eth/protocol_test.go
eth/state_accessor.go
eth/tracers/api.go
eth/tracers/api_test.go
les/api_backend.go
les/state_accessor.go

eth, les: fix tracer

---

eth/state_accessor.go

When tracing based on a clean database (chain tracing), we removed the short-circuit that created a statedb on top of the starting block. That fix was needed to not process blocks on top of the live pruner.
However, we still do need to check if we can make a statedb on top of the starting block using only the disk database. Otherwise a chain tracer starting from the genesis would fail as it would try to reconstruct the genesis state from it's "parent" from the get to.

eth: fix tracing state retrieval if requesting the non-dirty genesis

---

eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/downloader/peer.go
eth/handler.go
eth/handler_eth_test.go
eth/protocols/eth/handler.go
eth/protocols/eth/handler_test.go
eth/protocols/eth/handshake_test.go
eth/protocols/eth/protocol.go
eth/sync_test.go
les/client_handler.go
les/server_handler.go

This PR drops support for `eth/64`. Unfortunately, there's not much more we can do now to clean up our codebase until we also start dropping `eth/65`. That said, after Berlin it's probably safe to still serve but not sync from below `eth/66`, which would simplify certain things.
The PR also enabled `eth/66` tests at various locations that didn't have them run and fixes them to complete successfully.

eth, les: drop support for eth/64

---

accounts/accounts.go

* replaces `an chance` with `a chance`
* replaces `SignHashWithPassphrase` with `SignTextWithPassphrase` as there was no SignHashWithPasspharse function in the file

accounts: documentation fixes

---

cmd/geth/dbcmd.go
core/rawdb/freezer.go
core/rawdb/freezer_table.go
core/rawdb/freezer_table_test.go
core/rawdb/schema.go

This PR makes it easier to inspect the freezer index, which could be useful to investigate things like #22111
```
geth --yolov3 db freezer-index diffs  214043 214056
INFO [04-08|13:52:42.921] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-08|13:52:42.921] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [04-08|13:52:42.922] Set global gas cap                       cap=25000000
INFO [04-08|13:52:42.922] Opening freezer                          location=/home/user/.ethereum/yolo-v3/geth/chaindata/ancient name=diffs
| number | fileno | offset |
|--------|--------|--------|
|  214043   |  000   |  823212   | 
|  214044   |  000   |  823216   | 
|  214045   |  000   |  823220   | 
|  214046   |  000   |  823224 …
```

cmd/geth: add db-command to inspect freezer index (ref #22111)

---

cmd/faucet/faucet.go

Adds `--goerli` and `--rinkeby` flags to the faucet that can be used in place of the `--genesis` flag. Not the most beautiful code but with the target audience size of 1-2 users, it might be ok :).
Sort off fixes https://github.com/ethereum/go-ethereum/issues/22531

cmd/faucet: Support testnet flags in the faucet

---

eth/fetcher/block_fetcher.go

eth/fetcher: avoid spurious timer events at startup

---

cmd/geth/snapshot.go
core/state/snapshot/conversion.go
core/state/snapshot/generate.go
core/state/snapshot/generate_test.go
core/state/snapshot/snapshot.go
core/state/snapshot/wipe.go
core/state/statedb.go
core/state/sync.go
core/state/sync_test.go
eth/downloader/statesync.go
eth/protocols/snap/sync.go
trie/committer.go
trie/sync.go
trie/trie.go
trie/trie_test.go

This PR improves snapshot generation (post-snap-sync) by orders of magnitude. 
When doing a snap sync, we download 'slices' of the trie, individually verified, and use these slices to fill our trie. 
The slices of accounts/storage themselves are forgotten. 
After this is done, we iterate the entire account trie, and every storage trie, to reconstruct the snapshot database. 
This process takes hundreds of hours, and the disk IO is extreme during this process. 
This PR implements the basic idea described here: https://gist.github.com/rjl493456442/85832a0c760f2bafe2a69e33efe68c60 . 
For starters, it stores the snapshots into the database. The account (and storage) data do not actually match up to whatever
root we'll eventually wind up on, but that's for later. 
After the snap sync is done, …

core/state/snapshot: faster snapshot generation

---

core/types/block.go

Drop some relics from the time of `eth/62`

core/types: drop some relice data types

---

core/genesis_test.go
params/config.go

Add a simple unit test checking if hardcoded
genesis hash values (in params) match with
the default genesis values.
Resolves https://github.com/ethereum/go-ethereum/issues/22560

core: test genesis:genesisHash values (and fix YoloV3)

---

eth/protocols/snap/sync.go

Snap sync has a run loop. All events are passed though this, which ensures race free consistency. This run loop can be stopped and later restarted if for example the pivot block moves.
Unfortunately, the run loop used persistent channels across sync cycles. Whilst this seemed like a good and clean idea, this means extra care needs to be taken to not leak "events" from one cycle into the next. The dirty-snapshot PR surfaced an interesting data race where a very quick stop/restart cycle ended up delivering stale events to the new sync. Since events assume certain invariants, such stale deliveries crashed.
This PR replaces the persistent channels with ephemeral ones, new for every sync cycle. This way even if a great deal of events are piled up, nobody will consume them upon a sync restart …

eth/protocols/snap: use ephemeral channels to avoid cross-sync delveries

---

les/vflux/server/balance.go
les/vflux/server/balance_test.go
les/vflux/server/clientpool.go
les/vflux/server/clientpool_test.go

This PR fixes a cornercase that caused two nodes kicking each other out of the priority pool in an infinite loop when the connection bias was very low. There was an earlier attempted fix for this case that tried to ensure that `estimatePriority` always returns a smaller priority than `priority` for the same node at the same moment. This was ensured by subtracting 1 from `estimatePriority` result. However, the negative balance `ExpiredValue` can change its exponent and lose some precision when adding the bias and in some rare cases this could create a situation when the future priority estimate still wasn't smaller than the current priority. Now the same condition is enforced directly.
A second commit simplifies a `ClientPool` condition when `InactiveAllowance` is zero. With the current …

les/vflux/server: fix priority cornercase causing fuzzer timeout

---

trie/stacktrie.go
trie/stacktrie_test.go

The stacktrie is a bit un-untuitive, API-wise: it mutates input values. 
This is dangerous, and easy to get wrong if the calling code 'forgets' this quirk, so this PR fixes that behaviour. The first commit provides a testcase, and the second commit provides a fix. Naturally, the fix has an overhead. 
With this PR:
```
name                       old time/op    new time/op    delta
DeriveSha200/std_trie-6       715µs ±13%     722µs ± 7%     ~     (p=0.841 n=5+5)
DeriveSha200/stack_trie-6     453µs ±13%     449µs ± 2%     ~     (p=0.690 n=5+5)
name                       old alloc/op   new alloc/op   delta
DeriveSha200/std_trie-6       273kB ± 0%     273kB ± 0%     ~     (p=0.548 n=5+5)
DeriveSha200/stack_trie-6    52.5kB ± 0%    58.5kB ± 0%  +11.24%  (p=0.016 n=4+5)
name …
```

trie: make stacktrie not mutate input values

---

core/state/snapshot/generate.go
trie/trie_test.go

Follow-up to https://github.com/ethereum/go-ethereum/pull/22673 , this PR avoid some copying for things going into the Stacktrie

core/state/snapshot: avoid copybytes for stacktrie

---

cmd/devp2p/README.md
cmd/devp2p/nodeset.go
cmd/devp2p/nodesetcmd.go

The new -limit option makes the filter operate on top N nodes by score.

cmd/devp2p: add support for -limit option in nodeset filter command

---

cmd/devp2p/dns_route53.go
cmd/devp2p/dnscmd.go

This adds a tool to delete all TXT records of a name on Route53.

cmd/devp2p: add dns nuke-route53 command

---

core/blockchain.go
core/blockchain_snapshot_test.go
core/state/snapshot/journal.go
core/state/snapshot/snapshot.go

The legacy snapshot format(more specific, the legacy snapshot journal) is already not supported. The upgrade logic has been kept for several months.
After the berlin hard fork this PR can be merged because we expect all the users won't run the legacy Geth version anymore.

core: nuke legacy snapshot supporting

---

consensus/ethash/consensus.go

Block rewards are disabled in catalyst, as the reward are provided by the eth2 consensus layer.

ethash: no block reward in catalyst mode

---

trie/stacktrie.go
trie/stacktrie_test.go

This PR makes `trie.StackTrie` support the interfaces `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler`.

trie: make stacktrie support binary marshal/unmarshal

---

tests/block_test.go

Before berlin, I enabled general state tests to run as blockchain tests aswell. I think we can disable that now, and hopefully get green on the arm64-build which currently times out most of the time

tests: disable blockchain tests based on general state tests

---

eth/tracers/api.go
eth/tracers/api_test.go
internal/ethapi/api.go

eth/tracer: extend call tracer

---

eth/tracers/api_test.go
internal/ethapi/api.go

eth/tracers, internal/ethapi: fix typos causing lint issue

---

les/server.go
les/test_helper.go

The tests fail a lot, e..g on appveyor. Example: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/38784182/job/5so0ap0l4d3al810 
It appears that a _lot_ of goroutines are leaked. Just by running `TestReceiptsAccessLes3`, I got the dump below after doing the teardown. 
THe changes in this PR might be doable more nicely, but I'm not really that well versed about how les works under the hood, so I just made the simplest changes I could find which "fixed" it. 
```
GOROOT=/usr/local/go #gosetup
GOPATH=/home/user/go #gosetup
/usr/local/go/bin/go test -c -o /tmp/___TestReceiptsAccessLes3_in_github_com_ethereum_go_ethereum_les github.com/ethereum/go-ethereum/les #gosetup
/usr/local/go/bin/go tool test2json -t /tmp/___TestReceiptsAccessLes3_in_github_com_ethereum_go_ethereum_les -test.v …
```

les: clean up resources during test

---

docs/_getting-started/index.md

GETH_LOCATION is confusing and "data dir" is usesd to describe the same in other parts of the documentation

docs: GETH_LOCATION -> GETH_DATA_DIR - closes #22417

---

trie/iterator.go
trie/iterator_test.go

This PR improves the efficiency of the nodeIterator `seek` operation. 
Previously, the `seek` operation used the `nextChild` to iterate across the fullnode chldren, resolving each as it traversed towards the seek position. 
Example: 
```
marker: 01ee4cbd12051867841e785a715f770a635da089ff75b19eff5e6f719963e83f
trie.resolveHash resolve path 
INFO [03-09|14:20:27.177] Resuming state snapshot generation       root="349972…b86d77" at="01ee4c…63e83f" accounts=7 slots=0 storage=278.00B elapsed=1.875ms eta=263ms
trie.resolveHash resolve path 00
trie.resolveHash resolve path 0000
trie.resolveHash resolve path 0001
trie.resolveHash resolve path 000104
trie.resolveHash resolve path 000108
trie.resolveHash resolve path 00010e
trie.resolveHash resolve path 0002
trie.resolveHash resolve path 000206 …
```

trie: improve the node iterator seek operation

---

accounts/external/backend.go
signer/core/api.go
signer/core/cliui.go
signer/core/types.go

This PR adds support to use clef as a backend for signing 2930 type transcations. 
```
-----------------------
WARN [03-26|14:47:56.832] Served account_signTransaction           reqid=4 t=1.856328178s             err="request denied"
--------- Transaction request-------------
to:    0x8A8eAFb1cf62BfBeb1741769DAE1a9dd47996192
from:     0x8A8eAFb1cf62BfBeb1741769DAE1a9dd47996192 [chksum ok]
value:    1 wei
gas:      0x84d0 (34000)
gasprice: 500 wei
nonce:    0x5 (5)
chainid:  0x796f6c6f763378
Accesslist
0. 0x8A8eAFb1cf62BfBeb1741769DAE1a9dd47996192
0. 0x79e6c92a69cc29f3faafb3d3cfe5b6ffaea50d4cecde1c0b03442a56f16f337a
1. 0x8A8eAFb1cf62BfBeb1741769DAE1a9dd47996192
0. 0x79e6c92a69cc29f3faafb3d3cfe5b6ffaea50d4cecde1c0b03442a56f16f337a
Request context:
NA -> NA -> NA
Additional HTTP header data, …
```

accounts/external, signer/core: clef support for 2930-type txs

---

rpc/errors.go
rpc/http.go
rpc/http_test.go
rpc/types.go

New error type holds details of the specific error code and response
body.
Closes #22654

rpc: return new HTTPError type for HTTP error responses

---

eth/protocols/eth/handler.go
eth/protocols/eth/handlers.go
eth/protocols/eth/peer.go
eth/protocols/eth/tracker.go
eth/protocols/snap/handler.go
eth/protocols/snap/peer.go
eth/protocols/snap/tracker.go
p2p/metrics.go
p2p/tracker/tracker.go

This PR is a counterpart to https://github.com/ethereum/go-ethereum/pull/22581, adding metrics to the request/reply RTTs too. 
Given that we (currently) do not have a centralized dispatcher which matches requests with replies, this PR introduces a global request tracker (per protocol). The tracker can be notified of outbound requests and inbound replies, and it will match them up and update the relevant metrics.
Since the request/reply pattern is stateful, there are a few caveats in the tracker:
- The tracker maintains a list of all currently pending requests. The only way to remove an item from this list is to either deliver a response; or for the request to time out. The timeout however is not the same as the `downloader` might use, rather a global number per protocol (5 min for `eth`, …

eth/protocols, prp/tracker: add support for req/rep rtt tracking

---

core/state/snapshot/generate.go
trie/iterator.go

This PR is a successor to https://github.com/rjl493456442/go-ethereum/pull/6 (some charts can be found there). 
This PR attempts to minimize the number of disk reads when doing the snapshot generation. 
When we have a slice of snapshot values which do not match the trie data, we currently iterate the disk to retrieve the canonical data.
What this PR does, is commit the (incorrect) snapshot data to a trie, which will be 99% correct. When iterating the trie, we then use the snapshot-trie-database for resolving hashes. By doing so, we can read 99% of the leaves the from the memory db instead of resolving from disk.
It can also be implemented differently (this was my third variation). Other variants which also "work"
- Use a differenceIterator, to walk only the nodes which are on disk and not …

core/state/snapshot: reuse memory data instead of hitting disk when generating

---

cmd/devp2p/internal/ethtest/chain.go
cmd/devp2p/internal/ethtest/eth66_suite.go
cmd/devp2p/internal/ethtest/eth66_suiteHelpers.go
cmd/devp2p/internal/ethtest/suite.go
cmd/devp2p/internal/ethtest/transaction.go
cmd/devp2p/internal/ethtest/types.go

This PR adds a large transaction request test to the eth test suite as well as a new pooled tx hashes announcement test. 
It depends on #22698.

cmd/devp2p/internal/ethtest: add more tx propagation tests

---

p2p/discover/v5_udp.go
p2p/discover/v5_udp_test.go

In the event a local node is binded to both an IPV4 and IPV6 interface, it will treat any inbound packets from an IPV4 address as a v4 in v6 mapped address. This leads to any source IPs being denominated in that fashion. The PR carries out a check so that v4 in v6 mapped addresses are reduced to their initial form which would be a simple IPv4 address. This also reduces the number of bytes in the `ToIP` field from 16 bytes to 4 bytes in a `Pong` packet.

p2p/discover: handle IPv4 mapped in IPv6 addresses

---

core/rawdb/freezer_table.go
core/rawdb/freezer_table_test.go

This PR fixes https://github.com/ethereum/go-ethereum/issues/22714 . 
The Append / truncate operations were racy. When a datafile reaches `2Gb`, a new file is needed. For this operation, we require a writelock, which is not needed in the 99.99% of all cases where the data does fit in the current head-file. 
This transition from readlock to writelock was incorrect, and as the readlock was released, a `truncate` operation could slip in between, and truncate the data. This would have been fine, however, the `Append` operation continued writing as if no truncation had occurred, e.g writing item `5` where item `0` should reside. 
This PR changes the behaviour, so that if when we run into the situation that a new file is needed, it aborts, and retries, this time with a writelock. 
The outcome …

core/rawdb: fix datarace in freezer

---

les/metrics.go
les/peer.go
les/server_handler.go
les/vflux/server/prioritypool.go

This PR polishes the les internal a bit. Nothing important changed.

les: polish code

---

consensus/ethash/consensus.go

This PR contains a small optimization picked from https://github.com/ethereum/go-ethereum/pull/19456 
When verifying a block PoW, we need to check an ancestor's uncles. However, most blocks don't have uncles, and in those cases we can avoid loading the full block, and just make do with the header.

consensus/ethash: less lookups of block data

---

cmd/puppeth/ssh.go

cmd/puppeth: support authentication via ssh agent

---

core/vm/operations_acl.go
core/vm/runtime/runtime_test.go

Supersedes #22680 
Original description below:
---
Possible way to close #22649.
Previously, the `makeCallVariantGasCallEIP2929` charged the cold account access cost directly, leading to an incorrect gas cost passed to the tracer from the main execution loop.
This change still temporarily charges the cost (to allow for an accurate calculation of the available gas for the call), but then afterwards refunds it and instead returns the correct total gas cost to be then properly charged in the main loop.
This is the best fix I could come up with that keeps the general wrapper structure intact. Alternatives would be deeper changes to the way EIP-2929 gas cost calculation is conducted.

core/vm: make gas cost reporting to tracers correct

---

core/rawdb/database_test.go
core/rawdb/table.go
eth/protocols/snap/handler.go
eth/protocols/snap/range.go
eth/protocols/snap/range_test.go
eth/protocols/snap/sync.go
eth/protocols/snap/sync_test.go
ethdb/batch.go
ethdb/leveldb/leveldb.go
ethdb/memorydb/memorydb.go
tests/fuzzers/stacktrie/trie_fuzzer.go
trie/trie_test.go

This PR implements an idea from @holiman, where instead of assembling subtries for each storage chunk received from the network, we drop all of them to disk first and then assemble the entire storage trie from the final disk content. The final trie might have faults in it if the pivot moves or sync is interrupted and resumed, but that will be fixed during the healing phase. The goal of this PR is to get rid of all the missing trie nodes on the request/reply chunk boundaries.
PR:
```
20:26) State sync start
[...]
00:55) State sync done  accounts=129,183,697@26.49GiB slots=422,048,701@67.87GiB codes=374,498@1.83GiB state=96.20GiB
[...]
01:27) State heal done  accounts=130,501@6.32MiB      slots=145,732@10.97MiB     codes=26@250.45KiB       nodes=969,287@257.60MiB pending=0
```
Master:
``` …
```

eth/protocols/snap: generate storage trie from full dirty snap data

---

cmd/devp2p/internal/ethtest/eth66_suite.go
cmd/devp2p/internal/ethtest/large.go
cmd/devp2p/internal/ethtest/suite_test.go
eth/protocols/eth/handlers.go

This PR fixes a flaky test:
```
not ok 1 TestNewPooledTxs_66
```
Which I think is due to spurious block broadcasts, you never quite know when a node might decide to send you one. 
Also, it moves the announcement sanity check earlier, and configure the blockchain a bit making the log output smaller (to stop the node from having to do gc after every block import)

cmd/devp2p, eth/protocols: earlier sanity check + fix flakey test

---

cmd/devp2p/internal/ethtest/eth66_suite.go
cmd/devp2p/internal/ethtest/eth66_suiteHelpers.go

This PR fixes an issue with the `SameRequestID` test in the eth test suite that caused it to be flakey both in the CI and when run on hive.

cmd/devp2p: fix flakey SameRequestID test

---

eth/protocols/snap/sync.go

Originally `snap` sync used fairly large packet sizes to minimize the healing phase due to chunking. With the optimization that fed contiguous snapshot chunks to generate trie nodes merged, the healing phase is mostly independent of how large packets are, so we can reduce them to something a bit more reasonable.
Ideally we want dynamic sizes, but that's for the next release.

eth/protocols/snap: lower the packet size to avoid overloading link

---

core/state/snapshot/generate.go
eth/protocols/snap/sync.go
tests/fuzzers/rangeproof/rangeproof-fuzzer.go
trie/notary.go
trie/proof.go
trie/proof_test.go

Since we changed how generation works, and how the snap sync works, we stopped using some of the functionality provided by the prover. 
Notably, we no longer make use of the returned `Trie`, nor the `Notary`. This PR removes them as return arguments. It also makes use of the `Stacktrie` for the cases where we don't have any proofs, and the provided key/value pairs are expected to produce a correct state root. 
The first commit adds a new benchmark for this case, which exhibit quite a boost by the use of `Stacktrie` instead of the regular one: 
```
name                      old time/op    new time/op    delta
Prove-6                      733µs ±21%     698µs ±27%     ~     (p=0.690 n=5+5)
VerifyProof-6               14.5µs ±16%    15.7µs ±15%     ~     (p=0.421 n=5+5)
VerifyRangeProof10-6 …
```

trie: remove redundant returns + use stacktrie where applicable

---

docs/_dapp/tracing.md

Sorry, didn't see this when I saw [this other typo](https://github.com/ethereum/go-ethereum/pull/22744).

docs: fix typo in EVM tracing

---

eth/catalyst/api.go

This adds a simple nil check on the retrieved parent block during the assembleBlock RPC call in catalyst (merge prototype).
Crash (thanks to potuz on discord for finding this):
```
INFO [04-29|08:56:36.015] Producing block                          parentHash=7d555b..bafbe4
ERROR[04-29|08:56:36.015] RPC method consensus_assembleBlock crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 823 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1(0xc00012a5b8, 0x17, 0xc0005ebd58)
/home/heluani/Documents/code/rayonism/mergenet-tutorial/clients/catalyst/rpc/service.go:200 +0xbd
panic(0x11c7600, 0x1c1b520)
/usr/lib/go/src/runtime/panic.go:965 +0x1b9
github.com/ethereum/go-ethereum/core/types.(*Block).Time(...) …
```

catalyst: check if block exists in assemble-block call with unknown parent-hash

---

core/rawdb/accessors_chain.go

This PR fixes a comment on ReadHeadBlock.
The function above `ReadHeadHeader` also appears to be unused throughout the rest of the repo. Is there any reason for keeping it? If not, I can add removing it to this PR.

Fix comment on read head block

---

core/types/transaction_marshalling.go

This PR adds a missing license header to `core/types/transaction_marshalling.go`. The header was copied directly from another file and the year replaced with 2021.

core/types: add license header

---

core/vm/operations_acl.go

This PR removes an unnecessary `"` character in a comment that seems to have been added or left in by mistake.

core/vm: fix typo in comment

---

core/vm/instructions_test.go

This PR replaces a string with 34 repeated occurrences with a variable in `core/vm/instructions_test.go`.
If this would be better if x/y/etc variables were skipped when `alphabetSoup` is assigned directly to them, I can easily make that change as well. They seem to make the tests more clear IMHO though.

core/vm: replace repeated string with predefined variable

---

core/blockchain.go

This PR fixes a small typo in `core/blockchain.go`

core: fix typo in comment

---

core/state/state_test.go
core/state/statedb_test.go

This PR removes toAddr with common.BytesToAddress for consistency.

core/state: remove toAddr helper in tests

---

core/blockchain.go
core/rawdb/accessors_snapshot.go
core/rawdb/database.go
core/rawdb/schema.go
core/state/snapshot/generate.go
core/state/snapshot/journal.go
core/state/snapshot/snapshot.go
eth/downloader/downloader.go
eth/downloader/downloader_test.go
eth/protocols/snap/sync.go

The new snap sync algo reuses the snapshot namespace instead of wiping and regenerating at the end. This means we need to disable snapshots from being used during sync. This disabling needs to survive restarts too.
A previous attempt tried to just nuke the journal, but that didn't really do anything as the existing snapshot was already live and used and a restart just considered everything missing and started a regeneration cycle from scratch, deleting the valuable partial data.
This PR solves it by adding a new marker to the database to track disabled snapshots, and on top it also aborts any active generation on demand and marks all existing layers stale so any accidental live use gets gracefully stopped too.

core, eth: abort snapshot generation on snap sync and resume later

---

eth/protocols/snap/sync.go

When large contract sync was interrupted and resumed, recreating the task set the account batch into the storage trie stack tries, causing those to never be flushed, rather just pushed into until the contract completed.

eth/protocols/snap: use storage batch, not account batch in st task

---

cmd/devp2p/internal/ethtest/eth66_suite.go
cmd/devp2p/internal/ethtest/eth66_suiteHelpers.go
cmd/devp2p/internal/ethtest/suite.go
cmd/devp2p/internal/ethtest/suite_test.go
cmd/devp2p/internal/ethtest/types.go

This PR fixes a couple of issues in the eth test suite that caused flakiness when run in the CI. 
It depends on #22754 getting merged.

cmd/devp2p: fix flakey tests in CI

---

core/vm/evm.go

Do not keep separate flag for "max code size exceeded" case, but instead
assign appropriate error for it sooner.

core/vm: clean up contract creation error handling

---

params/config.go

Package params should not depend on package crypto because building
crypto requires cgo.
Since build/ci.go needs package params to get the go-ethereum version
number, C code must be compiled in order to run the build tool, which is
annoying for certain cross-compilation setups.

params: remove dependency on crypto

---

cmd/utils/flags.go

closes https://github.com/ethereum/go-ethereum/issues/22720
Problem is that if the datadir is opened read only and does not exist, the `leveldb.New` command will fail.
Previous behavior was to create the datadir if non-existent.
This PR restores previous behavior

cmd/utils: don't crash on nonexistent datadir

---

core/blockchain.go

This PR removes a loop which we had in place to handle the case where people were upgrading from 1.8 to 1.9 during a fast-sync.
In 1.9, we started shoving old block data immediately into the freezer, whereas previously we wrote it to leveldb first.

core: remove old conversion to shuffle leveldb blocks into ancients

---

eth/backend.go

Micro nitpick: it's annoying to see a db upgrade warning when starting a fresh node.

eth: don't print db upgrade warning on db init

---

cmd/utils/flags.go
eth/backend.go
eth/discovery.go
eth/protocols/snap/handler.go
go.mod
go.sum
p2p/dnsdisc/client.go

This removes auto-configuration of the `snap.*.ethdisco.net` DNS discovery tree.
Since measurements have shown that > 75% of nodes in `all.*.ethdisco.net` support
snap, we have decided to retire the dedicated index for snap and just use the eth
tree instead.
The dial iterators of eth and snap now use the same DNS tree in the default configuration,
so both iterators should use the same DNS discovery client instance. This ensures that
the record cache and rate limit are shared. Records will not be requested multiple times.
While testing the change, I noticed that duplicate DNS requests do happen even
when the client instance is shared. This is because the two iterators request the tree
root, link tree root, and first levels of the tree in lockstep. To avoid this problem, the
change also …

cmd/utils: use eth DNS tree for snap discovery

---

Makefile
build/ci.go
internal/build/env.go
internal/build/gotool.go
internal/build/util.go

This PR cleans up the CI build system and fixes a couple of issues.
- The go tool launcher code has been moved to internal/build. With the new
toolchain functions, the environment of the host Go (i.e. the one that built
ci.go) and the target Go (i.e. the toolchain downloaded by -dlgo) are isolated
more strictly. This is important to make cross compilation and -dlgo work
correctly in more cases.
- The -dlgo option now skips the download and uses the host Go if the running Go
version matches dlgoVersion exactly.
- The 'test' command now supports -dlgo, -cc and -arch. Running unit tests with
foreign GOARCH is occasionally useful. For example, it can be used to run
32-bit tests on Windows. It can also be used to run darwin/amd64 tests on
darwin/arm64 using Rosetta 2.
- The 'aar', 'xcode' and …

build: improve cross compilation setup

---

appveyor.yml

This upgrades the Windows build environment to a newer image, which has a
more recent Go version installed by default. Since the included Go is recent
enough to run build/ci.go directly, it is no longer necessary to download it using
the appveyor tool. The new build image also includes GCC version 10.

appveyor.yml: upgrade to VisualStudio 2019 image

---

build/nsis.envvarupdate.nsh

With the update to a newer AppVeyor build image, creating the Windows
installer no longer worked because of a string quoting error in
EnvVarUpdate.nsh. This applies the fix recommended
in https://stackoverflow.com/questions/62081765.
I have tested this, and the resulting installer/uninstaller works.

build: fix windows installer build for NSIS v3.05

---

docs/_interface/JavaScript-Console.md

Linked docs doesn't match with the bundled web.js, this warning is needed.

docs: web3.js is outdated (#22521)

---

cmd/devp2p/internal/ethtest/eth66_suite.go

This PR changes the `SimultaneousRequests` tests in the eth test suite to send the requests from the same connection as it doesn't really make sense to test whether a node can respond to two requests with different request IDs from separate connections.

cmd/devp2p: `TestSimultaneousRequests` sends both requests from the same connection

---

core/vm/logger_json.go

While trying FuzzyVM on the recent `go-ethereum` master (`37b5595456e7049e3ed487c41564281de52e00ab`) I got an incorrect output.
Got:
```
./evm --json --nomemory statetest ~/github.com/MariusVanDerWijden/FuzzyVM/interesting_inputs/BenchTest-16.json
{"pc":0,"op":127,"gas":"0xb6c2b8","gasCost":"0x3","memory":"0x","memSize":0,"stack":[],"returnStack":null,"returnData":"0x","depth":1,"refund":0,"opName":"PUSH32","error":""}
{"pc":33,"op":99,"gas":"0xb6c2b5","gasCost":"0x3","memory":"0x","memSize":0,"stack":["0x564b34a33ecd1af05fe6923d6de71870997d38ef60155c325957214c4259d74b"],"returnStack":null,"returnData":"0x","depth":1,"refund":0,"opName":"PUSH4","error":""}
{"pc":38,"op":82,"gas":"0xb6c2b2","gasCost":"0x4268fec1b10","memory":"0x","memSize":0,"stack":["0x564b34a33ecd1af05fe6923d6de71870997d3 …
```

core: single end logging in json logger

---

core/vm/errors.go
core/vm/evm.go

Alternative to #22768. This implements EIP-3541 as part of London. 
London tracker: https://github.com/ethereum/go-ethereum/issues/22736

core: implement EIP-3541

---

core/blockchain_test.go
core/state_transition.go
core/vm/eips.go
core/vm/interpreter.go
core/vm/jump_table.go
core/vm/operations_acl.go
params/protocol_params.go

This PR implements [EIP 3529](https://github.com/ethereum/EIPs/pull/3529)
| Constant | Value |
| - | - |
| `FORK_BLOCK` | TBD |
| `NEW_MAX_REFUND_QUOTIENT` | 5 |
For blocks where `block.number >= FORK_BLOCK`, the following changes apply.
1. Remove the `SELFDESTRUCT` refund.
2. Replace `SSTORE_CLEARS_SCHEDULE` with `SSTORE_RESET_GAS + ACCESS_LIST_STORAGE_KEY_COST` (4,800 gas as of [EIP-2929](./eip-2929.md) + [EIP-2930](./eip-2930.md))
3. Reduce the max gas refunded after a transaction to `gas_used // NEW_MAX_REFUND_QUOTIENT`

core, params: implement EIP-3529

---

consensus/clique/clique.go

This PR adds some checks from ethash header verification that were missing on clique.

consensus/clique: add some missing checks

---

cmd/geth/consolecmd.go

'geth monitor' subcommand no longer supported

cmd/geth: remove reference to monitor command

---

consensus/ethash/difficulty.go
core/vm/instructions_test.go
core/vm/logger_test.go
go.mod
go.sum

`1.2.0` mainly contains some conversions, and also API-changes to make it more closely resemble a `big.Int`, and fixes an error in `SubUint64` (which is unused in our code) .

deps: update uint256 to 1.2.0

---

eth/protocols/eth/protocol.go
les/protocol.go

Getting the raw value is not necessary to decode this type, and
decoding it directly from the stream is faster.

eth/protocols/eth, les: avoid Raw() when decoding HashOrNumber

---

core/types/log.go
core/types/receipt.go
core/types/receipt_test.go

This removes the database upgrade path for receipts and logs stored before April 2019.

core/types: remove support for legacy receipt/log storage encoding

---

consensus/ethash/consensus.go

This implements (draft) EIP https://github.com/ethereum/EIPs/blob/909863b2938b5f8ae38d42c8b6442e599d7605a4/EIPS/eip-3554.md , the next bomb delay for London

consensus/ethash: implement EIP-3554 (bomb delay)

---

cmd/evm/internal/t8ntool/transition.go
cmd/evm/runner.go
cmd/evm/staterunner.go
cmd/geth/chaincmd.go
cmd/geth/snapshot.go
cmd/utils/flags.go
core/state/dump.go
core/state/state_test.go
eth/api.go
eth/api_test.go

Supersedes https://github.com/ethereum/go-ethereum/pull/22787
This PR adds support for doing dumps from the snapshot. This is useful for two purposes: 
- For general chain investigations, it's faster to dump data using the snapshot than iterating the trie. 
- For checking the trie against the snapshot, it's possible to dump out parts of the state from either, and compare the two. 
There are a few differences, however. 
- For snapshot dump, I haven't added the conversion from hashed form to preimages. Mostly because since we don't (by default) store preimages any longer, I don't think it makes sense to do an extra db lookup for every hash. However, I didn't remove the address lookup from the trie dump, to not destroy something.
- For snapshot dump, it only ever does iterative (`jsonlines`, …

cmd/geth, eth, core: snapshot dump + unify with trie dump

---

cmd/evm/internal/t8ntool/execution.go
cmd/evm/internal/t8ntool/transition.go

I think the error should be checked when unmarshalling from `stdin`, otherwise it may attempt read something on an uninitialized object.

cmd/evm: return json error if unmarshalling from stdin fails

---

consensus/ethash/consensus.go

To merge when https://github.com/ethereum/EIPs/pull/3563 is merged

consensus/ethash: change eip3554 from 9.5M to 9.7M

---

core/rawdb/database.go
core/rawdb/freezer.go

I revisited  #20986, which contains some fixes regarding the shutdown of the background freezer. That PR is now stale, and some of the changes are already applied. 
One remaining feature from that PR is to use a waitgroup to ensure that the shutdown takes effect, before proceeding to close the tables and eventually the database. If this is not performed, it may happen that the database is closed, which makes the freezer hit a `log.Crit`, causing an ungraceful termination. 
This PR adds a waitgroup to the `freezer` to fix that behaviour. 
Supersedes  #20986

core/rawdb: wait for background freezing to exit when closing freezer

---

p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v4wire/v4wire.go
p2p/discover/v4wire/v4wire_test.go

This changes the definitions of Ping and Pong, adding an optional field
for the sequence number. This field was previously encoded/decoded using
the "tail" struct tag, but using "optional" is much nicer.

p2p/discover/v4wire: use optional RLP field for EIP-868 seq

---

rlp/decode.go

This PR contains various cleanup changes for rlp.Stream.
The changes improve the performance of decoding large amounts of
types.Block by 1.8%, so it's not really worth applying for performance
reasons. But I think it improves the readability of the code quite a bit.

rlp: improve decoder stream implementation

---

cmd/utils/flags.go

closes #22889, replaces #22895

cmd/utils: expand tilde in --jspath

---

core/bench_test.go
core/block_validator.go
core/block_validator_test.go
core/chain_makers.go
core/state_processor_test.go
core/types/transaction.go
core/types/transaction_test.go
eth/catalyst/api.go
miner/worker.go
miner/worker_test.go

This PR contains the changes for the miner, taken from https://github.com/ethereum/go-ethereum/pull/22833 , and lightly squashed. 
This PR is based on `master`, and does not require the txpool changes to be merged first. 
Supersedes  https://github.com/ethereum/go-ethereum/pull/22833

EIP-1559: miner changes

---

core/rawdb/table.go

This function may forget to handle the prefix when the `start` and `limit` are not `nil`

core/rawdb: table compaction doesn't handle the prefix

---

rlp/decode.go
rlp/encode.go
rlp/encode_test.go
rlp/typecache.go

All encoding/decoding operations read the type cache to find the
writer/decoder function responsible for a type. When analyzing CPU
profiles of geth during sync, I found that the use of sync.RWMutex in
cache lookups appears in the profiles. It seems we are running into
CPU cache contention problems when package rlp is heavily used
on all CPU cores during sync.
This change makes it use atomic.Value + a writer lock instead of
sync.RWMutex. In the common case where the typeinfo entry is present in
the cache, we simply fetch the map and lookup the type.
Unfortunately, it is very hard to prove whether this is an improvement
because single-threaded benchmarks won't hit the slowdown.

rlp: use atomic.Value for type cache

---

rlp/decode.go
rlp/decode_test.go
rlp/encode.go
rlp/encode_test.go
rlp/safe.go
rlp/unsafe.go

This change improves the performance of encoding/decoding `[N]byte`.
```
name                     old time/op    new time/op    delta
DecodeByteArrayStruct-8     336ns ± 0%     246ns ± 0%  -26.98%  (p=0.000 n=9+10)
EncodeByteArrayStruct-8     225ns ± 1%     148ns ± 1%  -34.12%  (p=0.000 n=10+10)
name                     old alloc/op   new alloc/op   delta
DecodeByteArrayStruct-8      120B ± 0%       48B ± 0%  -60.00%  (p=0.000 n=10+10)
EncodeByteArrayStruct-8     0.00B          0.00B          ~     (all equal)
```

rlp: optimize byte array handling

---

eth/handler.go
eth/handler_eth_test.go
p2p/peer.go

This fixes the error log message:
ERROR[05-19|15:21:29.382] Ethereum peer removal failed             peer=b43a87c5 err="peer not registered"
The error happened because `removePeer` was called multiple times: once to disconnect the peer, and another time when the handler exited.
With this change, `removePeer` now has the sole purpose of disconnecting the peer. Unregistering happens exactly once, when the handler exits.

eth: unregister peer only when handler exits

---

eth/tracers/api.go
eth/tracers/api_test.go
graphql/graphql.go
internal/ethapi/api.go
internal/ethapi/transaction_args.go

There are two transaction parameter structures defined in the codebase, although for different purposes.
But most of the parameters are shared. So it's nice to reduce the code duplication by merging them together.

internal/ethapi: merge CallArgs and SendTxArgs

---

p2p/nat/natupnp_test.go

Addressing the issue from https://github.com/ethereum/go-ethereum/issues/21476.
This issue is pretty annoying for me; I don't want to accept failure as the normal development test status. 
This proposed patch causes the offending test to `Skip` if it would otherwise fail _and_ the environment has an empty `CI` env var value (suggesting the environment is _not_ CI). As far as I know, all CI environments set this value, eg:
- https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables (`CI=true`)
- https://docs.travis-ci.com/user/environment-variables/#default-environment-variables (`CI=true`)

p2p/nat: skip TestUPNP in non-CI envs if discover fails

---

tests/block_test.go
tests/difficulty_test.go
tests/init_test.go
tests/rlp_test.go
tests/state_test.go
tests/transaction_test.go
tests/vm_test.go

There were 2 TODOs about that fix after Golang 1.8 release. It's here for 3 years already, so now should be the right time.

tests: get test name from testing.T

---

graphql/graphql.go
internal/ethapi/api.go

This PR removes the unused vm.Config param currently passed in to DoCall. Replaces #22784

internal/ethapi: remove unused vm.Config parameter of DoCall

---

core/state/snapshot/generate_test.go

This PR fixes some flaky tests due to short wait time.
```
/var/folders/11/1thmg8jd64jc4v8x9qp8pvpr0000gn/T/go-stress-20210526T144842-803955729
--- FAIL: TestGenerateWithManyExtraAccounts (0.29s)
generate_test.go:641: root: 34b118351a8a35bdf2632fe90ec25160fad17f4cac4401dd110e4d7001a88e0c
generate_test.go:650: Snapshot generation failed
generate_test.go:652: invalid subroot(path 29184934297fb4f590f1e3937ee6d183d064bd994c805fe0aef390ff95881040), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have ddefcd9376dd029653ef384bd2f0a126bb755fe84fdcc9e7cf421ba454f2bc67
FAIL
```

core/state/snapshot: fix flaky tests

---

cmd/geth/genesis_test.go
cmd/utils/flags.go

Whenever I do `geth --dev` the graphics flicker a bit, indicating that something just consumed a lot of memory (some quirk in qubes, I guess). Turns out that doing `geth --dev` allocates 1.3 Gb. This PR fixes that, which should make it better on the CI runs too, where we sometimes instantiate geth. 
Before (`1304M`)
```
(pprof) top
Showing nodes accounting for 1280MB, 98.11% of 1304.59MB total
Dropped 215 nodes (cum <= 6.52MB)
Showing top 10 nodes out of 31
flat  flat%   sum%        cum   cum%
768MB 58.87% 58.87%      768MB 58.87%  golang.org/x/crypto/scrypt.Key
512MB 39.25% 98.11%      512MB 39.25%  github.com/holiman/bloomfilter/v2.newBits
0     0% 98.11%      512MB 39.25%  github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).NewAccount
0     0% 98.11%      256MB 19.62% …
```

cmd/utils: avoid 1Gb alloc in --dev mode

---

p2p/rlpx/buffer.go
p2p/rlpx/buffer_test.go
p2p/rlpx/rlpx.go
p2p/rlpx/rlpx_test.go
p2p/transport.go
rlp/raw.go
rlp/raw_test.go

This change significantly improves the performance of RLPx message reads
and writes. In the previous implementation, reading and writing of
message frames performed multiple reads and writes on the underlying
network connection, and allocated a new []byte buffer for every read.
In the new implementation, reads and writes re-use buffers, and perform
much fewer system calls on the underlying connection. This doubles the
theoretically achievable throughput on a single connection, as shown by
the benchmark result:
name             old speed      new speed       delta
Throughput-8     70.3MB/s ± 0%  155.4MB/s ± 0%  +121.11%  (p=0.000 n=9+8)
The change also removes support for the legacy, pre-EIP-8 handshake encoding.
As of May 2021, no actively maintained client sends this format.

p2p/rlpx: reduce allocation and syscalls

---

cmd/devp2p/internal/ethtest/helpers.go
cmd/devp2p/internal/ethtest/suite.go

This PR adds a block hash announcement test to the eth test suite for both eth protocol version 66 and 65 and below. The test sends a block hash announcement to the node, waits for the node to request the header, and from a separate connection, waits for either the block hash announcement or new block propagation from the node.

cmd/devp2p: add block hash announcement test to eth test suite

---

eth/downloader/peer.go
eth/protocols/snap/sync.go
p2p/msgrate/msgrate.go
p2p/msgrate/msgrate_test.go

Trying to fix the windows build failure.

p2p/msgrate: return capacity as integer

---

core/tx_list.go
core/tx_pool.go
core/tx_pool_test.go
core/types/transaction.go
eth/gasprice/gasprice.go

This pull request implements EIP-1559 compatible transaction pool with dual heap eviction ordering.
It is based on https://github.com/ethereum/go-ethereum/pull/22791
The eviction ordering scheme and the reasoning behind it is described here: https://gist.github.com/zsfelfoldi/9607ad248707a925b701f49787904fd6

EIP-1559 tx pool support

---

core/error.go
core/state_processor_test.go
core/state_transition.go
core/tx_pool.go
core/tx_pool_test.go

This PR adds the new consensus constraints of EIP-1559 transactions as specified here:
https://github.com/ethereum/EIPs/pull/3594
Note: the same sanity checks are performed first during tx pool validation even though the previously existing filters would filter out the same transactions. This way the same error types can be returned by the pool and by consensus.

core: add new eip-1559 tx constraints

---

cmd/faucet/faucet_test.go

This disables the facebook-test, which fails very often on CI. See https://github.com/ethereum/go-ethereum/pull/22985

cmd/faucet: disable flaky facebook test

---

eth/catalyst/api.go

This is the fix from @mkalinin and port it to the master branch.

eth/catalyst: runs every transaction in a snapshot in assembleBlock handler

---

core/tx_pool.go
core/tx_pool_test.go
core/types/transaction.go
eth/api_backend.go
eth/catalyst/api.go
eth/handler.go
eth/handler_test.go
eth/sync.go
miner/worker.go

Pre-1559, the transaction pool of a miner only tracked transactions that paid above the configured threshold. Post-1559 however, when the basefee rises, the tip can go below the expected threshold. This PR adds a filtering mechanism when retrieving the txs that can enforce the effective tip.
The PR solved the issue in the txpool because this way "local" tracking and price filtering remains scoped in the pool as previously. The downside is that the filtering needs to check all txs returned every time which is O(n). A more optimal solution would be to return the pending txs as before and check the effective tip in the miner before accepting the next best tx, but that would require leaking the locals and the configured threshold into the miner package.

core, eth, miner: enforce configured mining reward post 1559 too

---

docs/_rpc/ns-debug.md

Removes double occurence of the word "included".

Remove typo in debug docs

---

trie/database.go

Since it has to be written, there is no need to do this check.

trie/database.go remove the duplicate write for 'preimage'

---

cmd/evm/internal/t8ntool/execution.go
core/gen_genesis.go
core/gen_genesis_account.go
core/genesis.go
tests/block_test.go
tests/block_test_util.go
tests/gen_btheader.go
tests/gen_stenv.go
tests/gen_sttransaction.go
tests/state_test_util.go

This is a bit work in progress

tests: update for London 

---

core/rawdb/database.go

Avoid the error message of Database contains `unaccounted data`

core/rawdb: db inspect move 'config' and 'shutdown' into 'meta data'

---

accounts/external/backend.go
cmd/clef/main.go
cmd/clef/testdata/sign_1559_missing_field_exp_fail.json
cmd/clef/testdata/sign_1559_missing_maxfeepergas_exp_fail.json
cmd/clef/testdata/sign_1559_tx.json
cmd/clef/testdata/sign_bad_checksum_exp_fail.json
cmd/clef/testdata/sign_normal_exp_ok.json
internal/ethapi/transaction_args.go
signer/core/api.go
signer/core/api_test.go
signer/core/cliui.go
signer/core/gnosis_safe.go
signer/core/types.go
signer/fourbyte/validation.go
signer/fourbyte/validation_test.go
signer/rules/rules_test.go

This goes on top of the RPC-changes, integrates 1559 transactions into clef.

cmd/clef, signer: support 1559 type transactions in clef

---

eth/ethconfig/config.go

Make sure we don't limit the gas estimation to below the actual block size.

eth/ethconfig: bump the RPC gas cap to 50M, since 1559 exceeds 25

---

common/debug.go

This function is not used in the code base, so probably safe to do rename, or remove in its entirety, but I'm assuming the logic from the original creator still applies so rename probably better.

Rename unused function with typo

---

core/gen_genesis.go
core/genesis.go

This is needed to parse genesis basefee with hex encoding which is used for consensus-tests in hive

core: make genesis parse baseFee correctly

---

accounts/abi/bind/backends/simulated.go
accounts/abi/bind/backends/simulated_test.go

Adds a Reorg function to the `SimulatedBackend` to enable the simulation of chain reorganizations.  
This brings the possibility to test protocol implementations for the reorg case which only rarely occurs on-chain.
Example:
Assume we have two dependent transactions `A` and `B`. `B` can only be mined after `A` was mined.  
Each transaction is mined in its own block.  
The following code reorders `B` before `A` (with depth=2, length=3), therefore rendering `B` invalid. `A` remains valid.
```go
// Send A and B
// Confirm A (ok)
// Confirm B (ok)
sim.Reorg(ctx, 2, 3, func(txs []types.Transactions) []types.Transactions {
return []types.Transactions{txs[1] /*B*/, txs[0] /*A*/, nil}
})
// Confirm A (ok)
// Confirm B (error)
```
Regarding testing: I added a small test to check that the newly …

accounts/abi/bind/backends: add simulated reorgs

---

docs/_dapp/tracing.md

People get confused, because the docs mention the deprecated evmlab. This removes it.

docs: remove mention of old python evmlab

---

core/forkid/forkid_test.go
params/config.go

This adds the fork blocks as per [specs](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)

params: add london testnet blocks

---

params/config.go

Can't find a light server for Ropsten, so it's not bumped :shrug:

params: bump CHTs for Geth v1.10.4

---

core/vm/runtime/env.go
core/vm/runtime/runtime.go

Without this PR: 
```
[user@work evm]$ ./evm --json --code 0x48 run
{"pc":0,"op":72,"gas":"0x2540be400","gasCost":"0x2","memory":"0x","memSize":0,"stack":[],"returnStack":null,"returnData":"0x","depth":1,"refund":0,"opName":"BASEFEE","error":""}
{"output":"","gasUsed":"0x0","time":277726}
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x608dcb]
goroutine 1 [running]:
math/big.(*Int).Bits(...)
/usr/local/go/src/math/big/int.go:87
github.com/holiman/uint256.(*Int).SetFromBig(0xc00018b670, 0x0, 0x0)
/home/user/go/pkg/mod/github.com/holiman/uint256@v1.2.0/conversion.go:102 +0x4b
github.com/holiman/uint256.FromBig(...)
/home/user/go/pkg/mod/github.com/holiman/uint256@v1.2.0/conversion.go:50 …
```

core/vm: evm fix panic

---

.travis.yml
build/ci.go

Docker stops supporting automated builds on the 18th of June, 2021. This PR replaces that infrastructure with our own local builder via Travis + push to hub directly. This also allows us to do ARM64 builds.
**Note, this PR pushes to my private docker repo for now. We can switch over when we see things are working correctly.**

travis, build: own docker builder and hub pusher

---

core/types/transaction.go

Per the title, update the inline Go documentation to mention that `DynamicFeeTx` implements the `TxData` interface.
@fjl via a Discord chat

core/types: add DynamicFeeTx to TxData implementation list in docs

---

internal/ethapi/api.go

Looks like "fee" was omitted in the comment.

internal/ethapi: fix typo in comment

---

tests/state_test.go

This fixes a nil pointer exception if test.Run throws an unexpected error

tests: fix nil pointer panic on failure

---

tests/state_test_util.go

During normal execution, this is checked by `Sender()` in `tx.AsMessage` as the sender recovery will reject a transaction that was signed for a eip-1559 network as `transaction type not supported`

tests: fixed eip1559 tx on non-eip1559 network

---

.travis.yml
build/ci.go

This PR enabled building individual architecture specific docker images, pushing them to Docker hub and then linking them together in a later build step.

travis, build: add support for multi-arch docker images

---

core/genesis.go

`DeveloperGenesisBlock` is currently not thread safe, since it creates a shallow copy of the `CliqueConfig` and modifies the `Period` value of it.  
This MR:  
Adds a `Copy()` function to `CliqueConfig` and uses it in DeveloperGenesisBlock to avoid overwriting `params.AllCliqueProtocolChanges.Clique.Period`.
This change makes `DeveloperGenesisBlock` thread safe.

core, params: make DeveloperGenesisBlock thread safe

---

trie/trie.go

when `nn` is not `nil`, there is no need to check the number of non-nil entries.
Since n must've contained at least two children before deletion, there must be another child node other than `nn`.

trie: small optimization of delete in fullNode case

---

.travis.yml
Dockerfile
Dockerfile.alltools
build/ci.go

This PR merges docker push and multi-arch publish. Each individual builder will try to own the publishing, but only the last should succeed. This is achieved by pushing the travis build number into the final docker images and using those to match up published images with the builder runs form different architectures / travis jobs.

travis, Dockerfile, build: docker build and multi-arch publish combo

---

README.md

The `README.md` links the Gitter channel for discussions, but the
official docs and even the Gitter channel itself recommend using the
official Discord Server for such discussions.
This PR simply changes the Gitter link and provides Discord invite link.

docs: Discord server instead of gitter for communication with devs

---

accounts/abi/bind/base.go

`ensureContext` was called for every other context in the `transact` method.
Without it, `net/http` fails with an error `net/http: nil Context` if the user does not provide a context.

accounts/abi/bind: call ensureContext on every context

---

accounts/abi/bind/base.go

While reviewing #23062 we found that call to `context.TODO`. Replace it with `context.Background`.

aaccounts/abi/bind: replace context.TODO with context.Background

---

graphql/graphql.go

This PR fixes the GraphQL transaction API. Previously it will only look up the transaction index in the database so it doesn't work for light client.

graphql: fix transaction API

---

core/tx_journal.go

https://github.com/ethereum/go-ethereum/issues/23084

[23084] transactions.rlp should not be executable

---

crypto/secp256k1/panic_cb.go
crypto/secp256k1/scalar_mult_cgo.go
crypto/secp256k1/secp256.go

The fuzzer build is failing: https://oss-fuzz-build-logs.storage.googleapis.com/log-c9d947df-e83c-4880-bf8b-6d4e24222421.txt 
```
Step #4: Building fuzzVmRuntime
Step #4: + corpusfile=/root/go/src/github.com/ethereum/go-ethereum/tests/fuzzers/bn256/testdata/fuzzBn256Pair_seed_corpus.zip
Step #4: + '[' -f /root/go/src/github.com/ethereum/go-ethereum/tests/fuzzers/bn256/testdata/fuzzBn256Pair_seed_corpus.zip ']'
Step #4: + compile_fuzzer tests/fuzzers/runtime Fuzz fuzzVmRuntime
Step #4: + path=/root/go/src/github.com/ethereum/go-ethereum/tests/fuzzers/runtime
Step #4: + func=Fuzz
Step #4: + fuzzer=fuzzVmRuntime
Step #4: + echo 'Building fuzzVmRuntime'
Step #4: + [[ address = *coverage* ]]
Step #4: + cd /root/go/src/github.com/ethereum/go-ethereum/tests/fuzzers/runtime
Step #4: + go-fuzz …
```

crypto: fix build directives

---

eth/tracers/tracer.go

The tracer context now has `int` and `Hash` types. They need to be converted before they're pushed on the js stack.

Convert int/hash values from context into js object

---

docs/_rpc/pubsub.md

removed `includeTransactions` option from doc.
see #15804

[DOCS] remove includeTransactions parameter in newHeads example

---

core/headerchain.go
eth/downloader/queue.go

This PR increases the cache size from `64` to `256` Mb for block bodies. Benchmarks have shown this to be one bottleneck when trying to achieve higher download speeds. 
Plus some minor changes to reduce lookups.

eth/downloader: increase downloader block body allowance

---

p2p/enode/node.go

This is an obvious spelling error

fix spelling error

---

eth/tracers/tracer.go
eth/tracers/tracer_test.go

When reading through the `call_tracer` I noticed the tracer hardcodes the istanbul precompiles to respond to `isPrecompiled` requests as the test case shows.
Because the tracer object is created early on once and not for every block we won't have the correct list of precompiles before `CaptureStart`.
This thing I did with `tracer.isPrecompile` is a bit awkward. I can also maintain a list of precompiles in the tracer and update that on `CaptureStart`.

core,eth: fix precompile addresses for tracers

---

accounts/abi/bind/base.go

I believe this PR fix a bug that prevents gas price suggestion with go-ethereum 1.10.4 and a pre EIP-1559 client (e.g. geth < v1.10.4). Thanks!

accounts/abi/bind: fix gas price suggestion with pre EIP-1559 clients

---

p2p/server.go

Rename a method in comment that does not match the name in code.

p2p/server: rename method in comment

---

cmd/geth/config.go

This came up as part of #23111 where we want to remove some noop flags. However, removing their respective config fields causes all existing toml config files to break.
It introduces a way to gracefully deprecate config fields. The map `deprecatedConfig` should be populated by keys like `ethconfig.Config.EVMInterpreter`.

cmd/geth: don't fail on deprecated toml config fields

---

cmd/evm/internal/t8ntool/execution.go
core/chain_makers.go
core/state/statedb.go
core/state/statedb_test.go
core/state_prefetcher.go
core/state_processor.go
eth/catalyst/api.go
eth/state_accessor.go
eth/tracers/api.go
les/state_accessor.go
miner/worker.go

Statedb rem blockhash followup

---

eth/fetcher/block_fetcher.go
eth/fetcher/block_fetcher_test.go
trie/sync_bloom.go

Some tests take quite some time during exit, which I think causes some appveyor fails like this: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/39511210/job/xhom84eg2e4uulq3 
One of the things that seem to take time during exit is waiting for (up to 100ms) for the syncbloom to close. This PR changes it to use a channel,  instead of looping with a 100ms wait. 
On master: 
```
[user@work eth]$ go test . -run TestTransactionPropagation66 --count 5
ok      github.com/ethereum/go-ethereum/eth     7.414s
[user@work eth]$ go test . -run TestTransactionPropagation66 --count 5
ok      github.com/ethereum/go-ethereum/eth     8.026s
[user@work eth]$ go test . -run TestTransactionPropagation66 --count 5
ok      github.com/ethereum/go-ethereum/eth     7.763s
```
On this PR: 
``` …
```

trie: minimize wait-time when exiting syncbloom

---

crypto/signature_cgo.go
crypto/signature_nocgo.go

Witth these changes, I can build the evm with various flag combos: 
```
[user@work evm]$ go build -tags gofuzz . 
[user@work evm]$ go build -tags nocgo . 
[user@work evm]$ go build -tags gofuzz,nocgo . 
```
And also the runtime fuzzer again: 
```
[user@work runtime]$ go-fuzz-build .
```
Follow-up after https://github.com/ethereum/go-ethereum/pull/23089 which didn't fully fix all problems

crypto: gofuzz build directives

---

core/vm/gen_structlog.go
core/vm/logger.go
core/vm/logger_json.go
eth/tracers/tracers_test.go
internal/ethapi/api.go

This PR first adds a benchmark of the "opcode tracer", i.e, the barebones tracer which stores data in memory before sending it out over RPC. The benchmark is a very simple loop which just runs through `1M` gas. 
The second commit adds some optimizations which improves the performance quite a lot: 
```
name                old time/op    new time/op    delta
TransactionTrace-6     100ms ±12%      28ms ±13%  -72.03%  (p=0.000 n=10+9)
name                old alloc/op   new alloc/op   delta
TransactionTrace-6    40.1MB ± 4%     9.0MB ±12%  -77.58%  (p=0.000 n=10+10)
name                old allocs/op  new allocs/op  delta
TransactionTrace-6      571k ± 0%      163k ± 0%  -71.42%  (p=0.000 n=10+8)
```

eth/tracers: improve tracing performance

---

ethstats/ethstats.go

When we merged 1559, we changed the "internal" `SuggestPrice` API method to `SuggestGasTipCap`. Well, turned out `ethstats` did a runtime cast to check if that old method existed, and since it did not, it fell back to light client mode. As such, stats reported by Geth nodes mostly lack almost all block data. Oops.

ethstats: fix full node interface post 1559

---

Dockerfile
Dockerfile.alltools

Docker hub started choking on `env` with `Operation not permitted` on the new 1.14 Alpine guest images. Well, might as well try to get rid of make from our Dockerfiles, see if that fixes anything.

dockerfile: get rid of make and env, see if that fixes builds

---

oss-fuzz.sh

Fixes a typo which prevents oss-fuzz from building/running.

fuzzing: fix typo in fuzzer definitions

---

eth/api.go
internal/web3ext/web3ext.go
miner/miner.go
miner/worker.go

This PR makes it so people don't have to shut down their nodes to update the gaslimit when the london fork happens.

eth, miner: add RPC method to modify miner gaslimit

---

core/types/block.go

EIP 1559 added a new unbounded type to the headers (base fee). This PR adds a meaningful can on top of it to prevent anyone from finding an ingenious way to do an amplification attack with junk basefees (with valid PoW).

core/types: sanity check the basefee length inside a header

---

cmd/evm/main.go
cmd/evm/runner.go
cmd/geth/config.go
cmd/geth/main.go
cmd/geth/usage.go
cmd/utils/flags.go
consensus/misc/eip1559_test.go
core/vm/evm.go
core/vm/instructions_test.go
core/vm/interpreter.go
eth/backend.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go
eth/tracers/tracer_test.go
params/config.go
tests/init_test.go
tests/state_test.go

These PRs https://github.com/ethereum/go-ethereum/pull/17687, https://github.com/ethereum/go-ethereum/pull/18457, https://github.com/ethereum/go-ethereum/pull/18084 introduced the configuration for alternative interpreters (e.g. wasm or external evm-c based). They're no-op as of now and the feature PRs that use these config flags, namely https://github.com/ethereum/go-ethereum/pull/17954 and https://github.com/ethereum/go-ethereum/pull/16957 have been on hold for a long time and are not being actively pursued AFAIK.
If needed these flags can be re-introduced along with the actual logic at a later point.
I plan to look into whether the `Interpreter` interface implemented here https://github.com/ethereum/go-ethereum/pull/17093/files is useful without these external VMs and remove it …

all: remove noop vm config flags

---

core/types/log.go
core/types/receipt.go

Martin noticed that the encoding of `Log` and `LogForStorage` is exactly the same now. After tracking it down it seems like #17106 changed the storage schema of logs to be simply the encoding of `[Address, Topics, Data]`, which is equivalent to the encoding of `Log` (or `rlpLog`). Support for the legacy format was dropped in #22852 and if I'm not wrong there's no reason anymore to have these two equivalent types.
Switching to this branch on a running node didn't seem to create a problem, but I'm not sure what to look for.
Note: this change includes an API change in `core/types`

core/types: remove LogForStorage type

---

core/forkid/forkid_test.go
params/config.go

This PR adds mainnet `london` fork block at `12965000`.

core, params: define london block at 12965000

---

eth/gasprice/feehistory.go
eth/gasprice/feehistory_test.go
internal/ethapi/api.go
miner/worker.go

This PR contains a few fixes to the feeHistory code, which was merged a bit prematurely:
- The snapshotReceipts in the miner are copied to avoid a data race.
- The API return fields are lower cased and the rewards omitted if not requested.
- Error returns are modified a bit to be consistent with Go styles and some contextual infos are added.
- Naked returns are removed since they made the code very hard to follow.
- Other nits and bits.

eth/gasprice, internal/ethapi, miner: minor feehistory fixes

---

core/state/trie_prefetcher.go

Might reduce memory consumption a bit.
We don't need to declare a new variable here, casting to string twice might be a bit slower but less memory intensive
```
OUTINE ======================== github.com/ethereum/go-ethereum/core/state.(*subfetcher).loop in github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go
823.72MB    63.55GB (flat, cum) 13.25% of Total
.          .    277:func (sf *subfetcher) loop() {
[...]
.   638.60MB    282:    trie, err := sf.db.OpenTrie(sf.root)
.          .    283:    if err != nil {
.          .    284:        log.Warn("Trie prefetcher failed opening trie", "root", 
[...]
.          .    289:    // Trie opened successfully, keep prefetching items
.          .    290:    for {
10MB       10MB    291:        select {
.          .    292:        case …
```

core/state: trie-prefetcher nitpick

---

internal/ethapi/api.go
internal/ethapi/transaction_args.go

This PR fixes the stale checks in some transaction APIs. Previously the `gasPrice` field is required for signing transaction. After the london the `gasPrice` can be replaced with the `MaxFeePerGas` and `MaxPriorityFeePerGas` combo. So the check
should be changed accordingly.

internal/ethapi: fix transaction APIs

---

core/tx_pool.go
eth/api_backend.go
internal/ethapi/api.go
internal/ethapi/backend.go
internal/web3ext/web3ext.go
les/api_backend.go
light/txpool.go

We can call Content() to get `all` pending and queued transactions, but the response is really large... 
This pull request implements an API to filter the pending/queued transactions by an address.

internal: get pending and queued transaction by address
