ethereum/go-ethereum

consensus/clique/api.go, internal/web3ext/web3ext.go
Prints the signer for a certain block
=> consensus/clique: implement getSignerForBlock

les/api_backend.go
This PR fixes the `eth_sendTransaction` API in the light mode. More detail in #23214
=> eth, les: fix sendTransaction API in the light mode

cmd/evm/testdata/12/alloc.json, cmd/evm/testdata/12/env.json, cmd/evm/testdata/12/readme.md, cmd/evm/testdata/12/txs.json, core/state_processor_test.go, core/state_transition.go, eth/tracers/api_test.go
We need to account for the value transacted in the buyGas() stage, since it would otherwise mean our check would be
`assert balance >= tx.value + effective_gas_price * gas`
instead of 
`assert balance >= tx.value + maxFeePerGas * gas`
=> core: check that account has enough balance for value + gas * gasFeeCap

core/types/gen_log_json.go, core/types/log.go, core/types/receipt.go, core/types/receipt_test.go
This PR reverts three PRs for removing legacy scheme support. 
- https://github.com/ethereum/go-ethereum/pull/22852
- https://github.com/ethereum/go-ethereum/pull/23173
- https://github.com/ethereum/go-ethereum/pull/23177
This PR also fixes #23245
=> core/types: revert receipts changes

eth/api_backend.go, eth/gasprice/feehistory.go, eth/gasprice/feehistory_test.go, internal/ethapi/api.go, internal/ethapi/backend.go, les/api_backend.go
The current spec uses an `Integer` type for the `blockCount` parameter. The [schema](https://github.com/ethereum/eth1.0-specs/blob/bdabd69d0943e518d9bdadf1ef253ae3f72368ce/json-rpc/spec.json#L1788-L1793) for this type defines it to be a hex string.
(h/t @ryanschneider for finding)
=> Use `hexutil.Uint` for `blockCount` parameter in `feeHistory` method

docs/_vulnerabilities/vulnerabilities.json, docs/_vulnerabilities/vulnerabilities.json.minisig
This updates the vulnerability info to report 10.0.1 (first Berlin release) up until v1.10.5 to be not London-ready. 
Test:
```
geth version-check --check.url file:///home/user/QubesIncoming/vault/vulnerabilities.json --check.version Geth/v1.10.1-unstable-3
INFO [07-22|21:43:25.256] Checking vulnerabilities                 version=Geth/v1.10.1-unstable-3 url=file:///home/user/QubesIncoming/vault/vulnerabilities.json
Severity: High
Summary : The client is not ready for the 'London' technical upgrade, and will deviate from the canonical chain when the London upgrade occurs (at block '12965000' around August 4, 2021.
Fixed in: v1.10.6
References:
- https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/london.md
- …
```
=> [DOCS] update vulnerabilities

cmd/geth/testdata/vcheck/vulnerabilities.json
This is not terribly important, just keeps our test-version of the vulnerability sample in line with the prod version.
=> cmd/geth: update vulnerability testdata

accounts/abi/bind/base.go, accounts/abi/bind/template.go
This moves the initialization of the parsedABI object from the Deploy()
function into a var that gets executed on startup. This means deploying
the same contract multiple times becomes faster, as the ABI doesn't have
to be parsed every time. It does increase the memory usage by requiring
everyone to hold the ABI object in memory even if the contract is not
going to be deployed.
closes https://github.com/ethereum/go-ethereum/issues/22269
example: (updated)
```golang
// ReverterMetaData contains all meta data concerning the Reverter contract.
var ReverterMetaData = &bind.MetaData{
ABI: "[{\"constant\":false,\"inputs\":[],\"name\":\"revert\",\"outputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"}]",
Sigs: map[string]string{
"7da3c3ab": "revert()",
},
Bin: …
```
=> accounts/abi/bind: parse ABI once

accounts/abi/bind/auth.go
Sets a default context in the TransactOpts objects.
This (in combination with another, already fixed flaw) created some nil pointer exceptions for abigen users
=> accounts/abi/bind: set Context in TransactOpts

core/vm/access_list_tracer.go, ethclient/gethclient/gethclient_test.go, internal/ethapi/api.go
closes https://github.com/ethereum/go-ethereum/issues/23223
=> internal/ethapi: fix panic in accesslist creation

cmd/puppeth/module_ethstats.go, cmd/puppeth/wizard_ethstats.go, consensus/ethash/consensus.go, core/blockchain.go, core/blockchain_test.go, core/error.go, core/headerchain.go, light/lightchain_test.go
split of #23283 containing only the changes for the blacklist terms
=> inclusive terms: change blacklist terms

accounts/external/backend.go, internal/ethapi/transaction_args.go
Ticket https://github.com/ethereum/go-ethereum/issues/23273 found a flaw where we were unable to sign legacy-transactions using the external signer, even if we're still on non-london network. That's fixed in this PR. 
Additionally, I found that even when supplying all parameters, it was impossible to sign a london-transaction on an unsynched node. It's a pretty common usecase that someone wants to sign a transaction using an unsynced 'vanilla' node, providing all necessary data. Our `setDefaults`, however, insisted on checking the current block against the config. This PR therefore adds a case, so that if both `MaxPriorityFeePerGas` and `MaxFeePerGas ` are provided, we accept them as given. 
**OBS** This PR fixes a regression -- on current master, we are _unable_ to sign a …
=> accounts/external, internal/ethapi: make ext signer sign legacy 

p2p/simulations/mocker.go
When the `nodeCount` is less than `10`, it will panic with the out of bound error. 
How about we just skip this round, when `rand1` and `rand2` are equal?
=> p2p/simulations: fix unlikely crash in probabilistic connect

accounts/external/backend.go, cmd/abidump/main.go, cmd/clef/main.go, internal/ethapi/transaction_args.go, signer/core/api.go, signer/core/api_test.go, signer/core/apitypes/types.go, signer/core/auditlog.go, signer/core/gnosis_safe.go, signer/core/signed_data.go, signer/fourbyte/validation.go, signer/fourbyte/validation_test.go, signer/rules/rules_test.go
Follow-up to https://github.com/ethereum/go-ethereum/pull/23274 . This PR moves (some) account types into a standalone package, to make the `external` package not depend on the full signer core package. 
This is in reference to #23046
=> signer: move types to separate package

build/ci.go, core/tx_pool.go, rpc/websocket.go
split of #23290
easy to review, it is only comments and log
=> all: remove term "whitelist" in comments and log messages

p2p/dial.go, p2p/discover/common.go, p2p/discover/v4_udp.go, p2p/server.go
split of #23290
only p2p package, including the review of @fjl
=> p2p: remove term "whitelist"

tests/init_test.go
split of #23290
including the review of @fjl
=> tests: remove whitelist feature

docs/_rpc/ns-clique.md
clique_getSnapshot in RPC changed from `{"method": "clique_getSnapsnot", "params": [blockNumber]}` to `{"method": "clique_getSnapshot", "params": [blockNumber]}`
=> Update clique_getSnapshot in RPC (ns-clique.md)

core/state/statedb.go
This PR fixes an outdated comment that states `statedb.Prepare` sets the blockHash of the statedb, when this is no longer the case.
=> Fix outdated statedb Prepare comment

cmd/devp2p/internal/v4test/discv4tests.go
Nethermind fails tests spuriously on Hive. They fail basic ping test, because they send a PING not a PONG back. This is most likely a data race. When they get a PING, they're supposed to send both a PONG and a PING. However, the test framework assumes that the PONG will be the first response packet to arrive. 
This PR modifies the post-PING-send expectations to both be laxer and stricter: it doesn't care what order the packets arrive, but also verifies that exactly one PING and one PONG is returned. 
Tested against my local node: 
```
$ ./devp2p discv4 test --run Ping --remote "enode://cc44695159f742595bf2fd9a9da13535733836c71cd5ca1179d76c11b95565f37c8014db177e90c9d7907b3a17439b3f51949c2144adbe4fef0e615d11900ca8@127.0.0.1:30303?discport=0"
-- OK Ping/Basic (1ms)
-- OK Ping/WrongTo (700µs) …
```
=> cmd/devp2p: fix ping/pong race in discv4 tests

core/blockchain.go
When looking at #23277 I noticed that `GetTransactionReceipt` fetches the same block body twice and its header once from storage. This PR targets one of those, i.e. getting the header of a block when that block is already cached in `Blockchain`.
Alternatively I could warm the headerchain's cache when a block is cached.
This only saves one lookup for each block that's cached (when the header is not)..
=> core: use blockchain's block cache for headers

internal/ethapi/api.go
=> internal/ethapi: fix trace log marshalling

core/rawdb/accessors_indexes.go
Currently, `go-ethereum` prints out the address of the block number variable (`*uint64`) instead of the block number (`uint64`) itself:
```
ERROR[08-03|21:41:58.520] Transaction not found                    number=0xc005b9d158 hash=9d0943..3b7192 txhash=e3e774..d85e2e
```
This PR dereferences the block number pointer after it has been checked to be `non-nil` before logging.
=> core/rawdb: Dereference Block Number Before Logging

core/error.go, core/state_processor_test.go, core/state_transition.go, eth/tracers/api_test.go, tests/init_test.go, tests/state_test.go
This is a rebased version of #23002. Some commits are dropped, and I didn't want to squash-delete those until I'm sure they're not needed, hence the new PR.
=> core: check if sender is EOA

core/rawdb/accessors_chain_test.go
In core/rawdb/accessors_chain_test.go:435
```go
func TestAncientStorage(t *testing.T) {
}
```
db never close so goroutine created at core/rawdb/database.go:199 never return:
```go
...
if !frdb.readonly {
frdb.wg.Add(1)
go func() {
frdb.freeze(db)    <==== not return until Close been call
frdb.wg.Done()
}()
}
...
```
=> core/rawdb: close database in test to avoid goroutine leak

core/state_transition.go
There is no need to call ’IsLondon‘ twice, which may affect TPS
=> There is no need to call ’IsLondon‘ twice

internal/ethapi/api.go, rpc/types.go
This PR allows both hex and decimal formats for the blockCount input parameter eth_feeHistory API.
=> internal/ethapi: accept both hex and decimal for blockCount

core/state/pruner/bloom.go
After writing the bloom filter for the offline pruner, we opened the file read-only and synced it to disk. This ensures that the OS flushes all it's internal buffers before we start deleting data.
Whilst on Linux calling `fsync` on a read-only file works, it does not on Windows. This PR opens the file in read-write mode to work around this quirk.
Fixes https://github.com/ethereum/go-ethereum/issues/23364.
=> core/state/pruner: fix state bloom sync permission in Windows

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, cmd/utils/flags_legacy.go, core/block_validator.go, core/block_validator_test.go, core/chain_makers.go, eth/ethconfig/config.go, miner/stress/1559/main.go, miner/stress/clique/main.go, miner/stress/ethash/main.go, miner/worker.go, miner/worker_test.go
Fixes #23170
This PR simplifies the gas adjustment mechanism a bit and also drop the `miner.gastarget` flag support.
Note the CLI flag(--miner.gastarget) and the config field(miner.gasFloor) are still kept for backward compatibility.
=> cmd, core, eth, miner: deprecate miner.gastarget flag

core/state/snapshot/snapshot.go
=> core/state/snapshot: fix typo in comments

core/state/snapshot/snapshot.go
Small fix to clarify what is deleted.
Fixes: #23298
=> core/state/snapshot: clarify comment

internal/ethapi/api.go
Currently geth returns ~~`0`~~ `null`(console converts to `0`) for `gasPrice` for pending transactions:
```
> params = { from: me, to: me, maxFeePerGas: "0x1000000000", maxTipPerGas: "0x0", gas: "0x5208" }
{
from: "0xc0ffee61108b46c8b84c63df14e3a607ac981e93",
gas: "0x5208",
maxFeePerGas: "0x1000000000",
maxTipPerGas: "0x0",
to: "0xc0ffee61108b46c8b84c63df14e3a607ac981e93"
}
> personal.sendTransaction(params)
"0xd7291f16ce57eb4e6aaae4b3d81f3f16ed947763cbed230eef3d9d1cb395fa5d"
> eth.getTransaction("0xd7291f16ce57eb4e6aaae4b3d81f3f16ed947763cbed230eef3d9d1cb395fa5d")
{
accessList: [],
blockHash: null,
blockNumber: null,
chainId: "0x5",
from: "0xc0ffee61108b46c8b84c63df14e3a607ac981e93",
gas: 21000,
gasPrice: 0,
hash: "0xd7291f16ce57eb4e6aaae4b3d81f3f16ed947763cbed230eef3d9d1cb395fa5d", …
```
=> internal/ethapi/api: return maxFeePerGas for gasPrice for EIP-1559 txs

accounts/abi/bind/backends/simulated.go, accounts/abi/bind/backends/simulated_test.go, internal/ethapi/api.go
Currently, you can call `eth_estimateGas` with EIP-1559 fee parameters and it won't cap the gas limits it tries based on the account balance. This can cause an `ErrInsufficientFunds` to be propagated back to the users if they can't afford the initial `hi * maxFeeCapPerGas + value`.
Before:
```console
$ curl http://localhost:8645 -H 'Content-Type: application/json' -d '{"method":"eth_estimateGas","id":1,"jsonrpc":"2.0", "params":[{"type":"0x2","maxFeePerGas":"0xb2d05e00","maxPriorityFeePerGas":"0xb2d05e00","value":"0x2386f26fc10000","from":"0xe77162b7d2ceb3625a4993bab557403a7b706f18","to":"0xe77162b7d2ceb3625a4993bab557403a7b706f18","data":"0x"}]}' | jq .
{
"id": 1,
"error": {
"code": -32000,
"message": "err: insufficient funds for gas * price + value: address …
```
=> internal/ethapi/api, accounts/abi/bind: Cap highest gas limit by account balance for 1559 fee parameters

.travis.yml
Docker revoked our automated build capabilities on the ~29th of June. Since we don't want to upgrade the entire Ethereum org to a team plan, this PR makes the switch to manually building containers on Travis and pushing them to Docker Hub. On the upside, this also enables us to build multi-arch images with both amd64 and arm64 architectures.
This functionality has been working and pushing into [karalabe/geth-docker-test](https://hub.docker.com/repository/docker/karalabe/geth-docker-test) for the past 2 months.
=> travis: transition from docker auto builds to manual pushes

internal/ethapi/transaction_args.go
In https://github.com/ethereum/go-ethereum/pull/23274/files#diff-4a9c1433c7c79c50cb72fd743c896f7bf5a976f46ccbb5fae83f5c46b2465db9R103, a check got lost. When the user/caller supplies both maxFee and maxPriorityFee, we still should verify that they are valid.
=> internal/ethapi: add back missing check for maxfee < maxPriorityFee

core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/freezer_table.go, core/rawdb/freezer_table_test.go, core/rawdb/table.go, ethdb/database.go
This PR is a bit of a successor to https://github.com/ethereum/go-ethereum/pull/20308, which implemented sequential access to freezer data via an iterator interface. 
This PR instead returns a slice of data. It does not defer reads until `Next()`, so instead does all the reads while holding the readlock. 
It also switches the implementation of `Retrieve` to be a just a short-cut for doing a sequential read with max items set to `1`. This PR doesn't really add any uses of the new method (except the `Retrieve`), but does actually improve one thing as-is: previously, two syscalls were performed to read two index items from the index-file. This PR instead reads all (both) index items using only one syscall. 
Later on, this can be used to serve `eth64` data such as headers directly from …
=> core/rawdb: implement sequential reads in freezer_table

cmd/devp2p/internal/ethtest/suite_test.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/peer.go, eth/handler.go, eth/handler_eth_test.go, eth/protocols/eth/handler.go, eth/protocols/eth/handler_test.go, eth/protocols/eth/handlers.go, eth/protocols/eth/handshake_test.go, eth/protocols/eth/peer.go, eth/protocols/eth/protocol.go, eth/sync.go, eth/sync_test.go, les/client_handler.go
This PR finally drops support for `eth/65` as announced last year. It should only be merged after mainnet forks into London to maximize the life span for lagging clients. Also, this PR only drops serving the old `eth` protocol, but followup PRs (or commits) are needed to clean up leftover assumptions in the fetcher/downloader and replace them with enforced request ids.
=> eth: drop eth/65, the last non-reqid protocol version

cmd/utils/flags.go, cmd/utils/flags_legacy.go
This adds ``--nousb`` as a deprecated flag when someone runs the ``geth show-deprecated-flags`` command.
=> cmd/utils: add --nousb to the list of deprecated flags

core/rawdb/freezer.go, eth/downloader/downloader.go
=> eth/downloader: fix typo in comment

cmd/devp2p/internal/ethtest/suite_test.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/peer.go, eth/handler.go, eth/handler_eth_test.go, eth/protocols/eth/handler.go, eth/protocols/eth/handler_test.go, eth/protocols/eth/handlers.go, eth/protocols/eth/handshake_test.go, eth/protocols/eth/peer.go, eth/protocols/eth/protocol.go, eth/sync.go, eth/sync_test.go, les/client_handler.go
Reverts ethereum/go-ethereum#23120 temporarilly for the hotfix release.
=> Revert "eth: drop eth/65, the last non-reqid protocol version"

accounts/abi/bind/backends/simulated.go, core/state_transition.go, core/types/transaction.go, internal/ethapi/transaction_args.go, les/odr_test.go, light/odr_test.go, tests/state_test_util.go
replaces https://github.com/ethereum/go-ethereum/pull/23420
=> core: only check sendernoeoa in non fake mode

go.mod, go.sum
https://golang.org/doc/go1.17
As announced in the Go 1.16 release notes, Go 1.17 requires macOS 10.13 High Sierra or later; support for previous versions has been discontinued.
Go 1.17 adds support of 64-bit ARM architecture on Windows (the windows/arm64 port). This port supports cgo.
The 64-bit MIPS architecture on OpenBSD (the openbsd/mips64 port) now supports cgo.
Go programs now maintain stack frame pointers on the 64-bit ARM architecture on all operating systems. Previously it maintained stack frame pointers only on Linux, macOS, and iOS.
The main Go compiler does not yet support the LoongArch architecture, but we've reserved the GOARCH value "loong64". This means that Go files named *_loong64.go will now be ignored by Go tools except when that GOARCH value is being used.
=> go.mod: upgrade golang.org/x/sys for go1.17 support

eth/ethconfig/config.go, eth/gasprice/feehistory.go, eth/gasprice/feehistory_test.go, eth/gasprice/gasprice.go, eth/gasprice/gasprice_test.go
This PR changes the block count limitation rules in light client mode so that only the length of the queried section is limited per request but querying older sections of the chain is not limited. The feeHistory spec only mandates providing access to the most recent section because some clients might not be able to serve older data but the Geth light client is capable of doing so and therefore the limitations can be eased, allowing fee estimators to examine/sample a longer history if necessary.
The processed results are also cached per block now which greatly improves the performance of the calibration process of the [Economical Fee Oracle](https://github.com/zsfelfoldi/feehistory/blob/main/js/feeOracle.js).
=> eth/gasprice: feeHistory improvements

core/vm/analysis.go, core/vm/analysis_test.go, core/vm/instructions.go, core/vm/interpreter.go
This makes the analysis for code/data faster, and more evenly spread. Previously, the worst-performing case was PUSH7.
`PUSH1` started at ~40ns, and going upwards towards `50ms` at `PUSH7`. 
This PR doesn't improve the PUSH1 situation, but does markedly improve the (previous) worst-case quite a lot, and also the normal-case (for code which is not push). 
```
name                           old time/op  new time/op  delta
JumpdestOpAnalysis/PUSH1-6     39.7ns ± 3%  40.2ns ± 0%     ~     (p=0.151 n=5+5)
JumpdestOpAnalysis/PUSH2-6     39.4ns ± 0%  38.6ns ± 3%     ~     (p=0.190 n=4+5)
JumpdestOpAnalysis/PUSH3-6     41.4ns ± 1%  31.5ns ± 3%  -23.83%  (p=0.008 n=5+5)
JumpdestOpAnalysis/PUSH4-6     44.5ns ± 6%  23.7ns ± 5%  -46.72%  (p=0.008 n=5+5)
JumpdestOpAnalysis/PUSH5-6     47.7ns ± 5% …
```
=> core/vm: faster code analysis

docs/_vulnerabilities/vulnerabilities.json, docs/_vulnerabilities/vulnerabilities.json.minisig
This PR updates the version-check to include info about the latest patch. 
```
[user@work go-ethereum]$ geth version-check --check.url file:///tmp/vulnerabilities.json
INFO [08-24|09:34:03.423] Checking vulnerabilities                 version=Geth/v1.10.7-unstable-e3e0ce00-20210818/linux-amd64/go1.16.4 url=file:///tmp/vulnerabilities.json
Severity: High
Summary : A vulnerability in the Geth EVM could cause a node to no longer being able to process the chain. Further details about the vulnerability will be disclosed at a later date.
Fixed in: v1.10.8
CVE: CVE-2021-39137
References:
- https://github.com/ethereum/go-ethereum/security/advisories/GHSA-9856-9gg9-qcmq
- https://github.com/ethereum/go-ethereum/releases/tag/v1.10.8
```
=> vulnerabilities: update for CVE-2021-39137

p2p/dial.go, p2p/enode/iter_test.go
This PR fixes three data races found by the go race condition tester:
```
go test ./... --race
Write at 0x00c00036f048 by goroutine 57:
sync/atomic.CompareAndSwapInt32()
/home/matematik/sdk/go1.14.7/src/runtime/race_amd64.s:293 +0xb
github.com/ethereum/go-ethereum/p2p.(*conn).set()
/home/matematik/go/src/github.com/ethereum/go-ethereum/p2p/server.go:288 +0x68
github.com/ethereum/go-ethereum/p2p.(*Server).run()
/home/matematik/go/src/github.com/ethereum/go-ethereum/p2p/server.go:725 +0x20d0
Previous read at 0x00c00036f048 by goroutine 32:
github.com/ethereum/go-ethereum/p2p.(*dialScheduler).loop()
/home/matematik/go/src/github.com/ethereum/go-ethereum/p2p/dial.go:262 +0x1971
Goroutine 57 (running) created at: …
```
=> p2p: fixed data races

core/bloombits/matcher.go
When using `atomic.Value` it will panic if the error is a struct implementing the error interface and an error as been registered.
From https://pkg.go.dev/sync/atomic#Value.Store, `Store sets the value of the Value to x. All calls to Store for a given Value must use values of the same concrete type. Store of an inconsistent type panics, as does Store(nil).`
Check this example. https://play.golang.org/p/N5Zp15o_AoE
We recently found this error at https://github.com/ava-labs/ when a custom error was returned from `rawdb.ReadBloomBits`.
Kudos to https://github.com/StephenButtolph for writing the code.
=> core/bloombits: avoid crash when storing errors of different type

.gitmodules
As @MariusVanDerWijden mentioned the tests submodule is quite heavy added the shallow setting for it - does not help that much as most weight is in the actual data - not the history - but it helps a bit - hence the PR.
Before:
`316M	.git/modules/tests/`
After:
`171M	.git/modules/tests/`
so 145M saved - not much - but also not nothing.
=> tests/testdata: make submodule shallow

core/types/types_test.go
This PR just adds a benchmark of how performant the RLP encoding/decoding of core types is. 
```
BenchmarkEncodeRLP/legacy-header-6         	 2306220	       530.7 ns/op	1023.20 MB/s	       0 B/op	       0 allocs/op
BenchmarkEncodeRLP/london-header-6         	 2219181	       545.7 ns/op	1006.04 MB/s	       0 B/op	       0 allocs/op
BenchmarkEncodeRLP/receipt-for-storage-6   	 3012508	       404.4 ns/op	  22.25 MB/s	      64 B/op	       1 allocs/op
BenchmarkEncodeRLP/receipt-full-6          	 2059255	       668.5 ns/op	 403.88 MB/s	     320 B/op	       1 allocs/op
BenchmarkEncodeRLP/legacy-transaction-6    	 2062718	       624.7 ns/op	 163.27 MB/s	       0 B/op	       0 allocs/op
BenchmarkEncodeRLP/access-transaction-6    	 1271258	      1004 ns/op	 105.60 MB/s	      24 B/op	       1 …
```
=> core/types: add benchmark for rlp encoding/decoding

tests/fuzzers/trie/trie-fuzzer.go
go vet show a signature warning
```
go vet ./...
cmd/devp2p/internal/ethtest/chain.go:42:17: method WriteTo(writer io.Writer) error should have signature WriteTo(io.Writer) (int64, error)
```
I propose to fix that by making the function private.
=> tests/fuzzers: fix go vet warning about signature of ReadByte

core/tx_pool.go, core/tx_pool_test.go
This PR adds a change-counter, to prevent too much from happening inside the pool before the pool has had a chance to run a reorg, which 'balances' the queued and pending transactions.
=> core: add change counter

metrics/cpu_disabled.go, metrics/cpu_enabled.go, metrics/cputime_nop.go, metrics/cputime_unix.go, metrics/runtime_cgo.go, metrics/runtime_no_cgo.go
This change is required to allow compilation of accounts/abi/bind to WebAssembly.
=> metrics: fix compilation for GOOS=js

core/state/database.go, core/state/metrics.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/state_object.go, core/state/statedb.go, light/postprocess.go, light/trie.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/committer.go, trie/iterator_test.go, trie/secure_trie.go, trie/trie.go, trie/trie_test.go
This PR exposes a few state relevant metrics.
=> core, light, tests, trie: add state metrics

go.mod, go.sum
Reduce memory allocation of buffer_pool and db
https://github.com/syndtr/goleveldb/pull/367
snappy-4.0.0  upgrade
https://github.com/syndtr/goleveldb/pull/365
=> go.mod : goleveldb Reduce memory allocation

tests/state_test.go
Without this PR:
```
[user@work go-ethereum]$ go test ./tests --run TestState --count 1
ok      github.com/ethereum/go-ethereum/tests    111.655s
```
With this PR:
```
[user@work go-ethereum]$ go test ./tests --run TestState --count 1
ok      github.com/ethereum/go-ethereum/tests    54.563s
```
Let's see if it makes any difference on travis/appveyor
=> tests: avoid performance tests

crypto/bn256/cloudflare/bn256_test.go, crypto/bn256/cloudflare/curve.go, crypto/bn256/cloudflare/gfp.go, crypto/bn256/cloudflare/twist.go
Fixes #23346 
There were two upstream fixes required: one is for in-place addition and the second one was for in-place [unmarshalling](https://github.com/cloudflare/bn256/commit/d078d2bbd8e91bc6fc4eb466a2b74fcf785a938e)
=> crypto/cloudflare/bn256: fix in-place addition and unmarshalling

core/vm/analysis_test.go
For BenchmarkJumpdestOpAnalysis use fixed code size of ~1.2MB and classic benchmark loop.
```
> go test -bench Jumpdest ./core/vm
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/vm
cpu: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
BenchmarkJumpdestAnalysis_1200k-8           2296            520734 ns/op        2359.75 MB/s
BenchmarkJumpdestHashing_1200k-8             374           3144320 ns/op         390.80 MB/s
BenchmarkJumpdestOpAnalysis/PUSH1-8         1222            979226 ns/op        1254.87 MB/s
BenchmarkJumpdestOpAnalysis/PUSH2-8         1269            949313 ns/op        1294.41 MB/s
BenchmarkJumpdestOpAnalysis/PUSH3-8         1747            693702 ns/op        1771.37 MB/s
BenchmarkJumpdestOpAnalysis/PUSH4-8         2064            580610 ns/op        2116.40 …
```
=> core/vm: rework jumpdest analysis benchmarks

core/state/snapshot/iterator.go
=> core: fix typo in iterator.go

trie/stacktrie_test.go
This PR adds the standard copyright header to `trie/stacktrie_test.go` which was previously missing this header.
=> Add missing copyright header

docs/_vulnerabilities/vulnerabilities.json, docs/_vulnerabilities/vulnerabilities.json.minisig
This adds more info about the consensus vulnerability we had. It's a draft -- once we're OK with the wording, we also need to commit the updated signature, and add link to post-mortem . 
So, please review so I know when to do the final step(s)
=> docs: add vuln info

internal/debug/flags.go
The deprecated flags are removed in the main portion of geth, this PR removes it internally too.
=> internal/debug: remove deprecated flags

core/blockchain.go, core/blockchain_test.go, core/error.go, core/rawdb/accessors_chain.go, core/rawdb/accessors_chain_test.go, core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/freezer_batch.go, core/rawdb/freezer_table.go, core/rawdb/freezer_table_test.go, core/rawdb/freezer_test.go, core/rawdb/table.go, ethdb/database.go
This is the rebased and squashed version of https://github.com/ethereum/go-ethereum/pull/22932. Due to the new batched reader, it became pretty difficult to rebase and retain all commits, so I squashed it, which made the whole thing a lot easier. 
@fjl you're welcome to do do a more thorough rebase if you want to keep the commit history, or you can rebase and reown it, I don't really care personally.
=> core/rawdb: freezer batch write

p2p/discover/v5wire/encoding_test.go, p2p/enode/localnode.go, p2p/enode/localnode_test.go, p2p/enode/nodedb.go
This PR ensures that wiping all data associated with a node (apart from its key) will not generate already used sequence number for the ENRs, since all remote nodes would reject them until they out-number the previously published largest one.
=> p2p/enode: use unix timestamp as base ENR sequence number

core/tx_list.go
This fixes crashes on 32bit builds.
The crash: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/40672672/job/199i4y12cn9ybg71#L1076
=> core: make txPricedList.stales the first field for 64bit alignment

core/tx_pool_test.go
This fixes crashes in txpool tests on 32bit platforms.
The crash: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/40675788/job/6f6aygb3s12xxljw#L837
=> core: 64bit alignment of testBlockChain.gasLimit

cmd/evm/disasm.go, cmd/evm/internal/t8ntool/flags.go, cmd/evm/internal/t8ntool/transition.go, cmd/evm/main.go, cmd/evm/runner.go, cmd/evm/staterunner.go, core/vm/logger.go, core/vm/logger_json.go, eth/tracers/tracers_test.go, tests/state_test.go
Both `ReturnData` and `Memory` are pretty big and should not be part of traces by default. 
This inverts the behavior of DisableMemory and DisableReturnData.
=> core: cmd: invert disableMemory

cmd/devp2p/internal/ethtest/helpers.go
Fixes an issue where we send 65 style messages over a 66 connection
=> cmd/devp2p/internal/ethtest: only use eth66 if eth66 is negotiated

eth/tracers/tracer.go
This PR tries to fix https://github.com/ethereum/go-ethereum/issues/23397. Geth goes OOM after
heavy transaction tracing.
The tracer has a `Stop` method, which sets a flag. This flag causes the tracer to stop doing work, as in no longer invoking
the javascript engine for each opcode. However, it does not actually stop the evm execution.
I tested with a little `traceCall` where we just run in a loop, burning 10M gas:
```
> a=eth.accounts[0];for(i=0;i<10; i++){try{debug.traceCall({from:a, input: "0x5b600056", gas:"0x989680"}, "latest", {"tracer": "callTracer", "timeout": "1ms"})  }catch(e){}}
```
If I run this on `master`, with some added printout when the trace ends:
```
WARN [09-15|10:17:23.124] Served debug_traceCall                   reqid=63 t=62.092057ms err="execution timeout"
INFO …
```
=> eth/tracers: abort evm execution when trace is aborted

accounts/keystore/account_cache_test.go, ethclient/gethclient/gethclient_test.go
This PR fixes a flaky test, `ethclient/gethclient`: `TestGethClient`. The reason it was flaky was that the table-driven test was actually a map-driven test, and the key order when iterating over the map is undefined. Some of the tests (particularly the setHead test) modifies the backend chain, which is problematic for the access list test, which fails if the basefee is too high. 
So this PR changes it to use a list instead. 
Example failure: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/40814331/job/oh9s50w4lgcxge8d#L821
=> ethclient, accounts/keystore: fix flaky tests

go.mod, go.sum, internal/debug/api.go, internal/web3ext/web3ext.go
Whenever Geth hangs, we use the `debug.stacks` API endpoint to try and find what might be off. This is fine-ish, but it generates a huge dump of goroutines and it's quite a pain to find a needle in the haystack and see if there's something wrong or not.
The initial idea was to add a filter parameter where we can specify packages to filter for, potentially multiple - comma separated - but even that produces too much noise. Adding both inclusion filters and exclusion filters would be necessary, but that would get both nasty as well as probably still not flexible enough.
The solution is to use a single filter that can contain both inclusion and exclusion clauses, as well as the possibility to combine these arbitrarily. Without hinting further, the only way to solve it is to have the filter …
=> internal: support optional filter expression for debug.stacks

cmd/geth/consolecmd_test.go, console/console.go
- On systems like Windows, the command terminal or Git Bash terminal won't respond to Ctrl-D but the console can be closed with "exit", so we add a extra note to advise users of alternative.
=> console: add note about typing exit to exit

consensus/clique/clique.go, core/genesis.go, core/genesis_test.go, miner/worker_test.go
closes https://github.com/ethereum/go-ethereum/issues/23522
=> consensus/clique: prevent 0 len extradata from panicing

docs/_interface/Managing-your-accounts.md
- fix typo in keystore file format
- fix typo for word `timestamp`
=> [DOCS] Fix typos

rpc/client.go, rpc/server.go
Fixes #23593
Clef is reading out the request scheme from key "scheme" of the context. Scheme is being set for http requests in https://github.com/ethereum/go-ethereum/blob/b61ef24ccef9b4d14f4f3c97298fa6d4c1b6b47d/rpc/http.go#L244 but its not set for websocket or ipc connections.
=> rpc: set scheme for ws and ipc conns to the server

rpc/websocket.go, rpc/websocket_test.go
The first commit adds a (failing) test `TestClientWebsocketSevered`, which demonstrates a hanging subscription after severing the client's websocket connection, as in #23528. The test times out after 3 ping intervals.
The second commit fixes the test by adding a 30 second read timeout after each ping. This detects and discards severed connections after timing out, and subscriptions receive an error right away.
Fixes #23528
=> rpc: set pong read deadline - Fixes #23528

eth/tracers/api.go, internal/web3ext/web3ext.go
This PR implements a new debug method, which I've talked briefly about to some other client developers. It allows the caller to obtain the intermediate state roots for a block (which might be either a canon block or a 'bad' block). 
This is meant to be a useful tool when investigating a chain split, to quickly narrow down what transaction causes the problem. Previous/alternative schemes to do this often rely on either comparing the `gasUsed`, or checking the receipts. However, more intricate bugs such as "wrong value stored in a storage slot" are not necessarily captured in gas differences -- but the stateroot will always capture any state diff (by definition). 
Tested with `--dev`; since it's PoA, it was pretty convenient to check that it becomes correct -- the last intermediate …
=> eth/tracers: implement debug.intermediateRoots

accounts/abi/bind/base.go, accounts/abi/bind/base_test.go
I open this PR for [issue#23153](https://github.com/ethereum/go-ethereum/issues/23153)
I make UnpackLog and UnpackLogIntoMap check event signature first.
It will return error if event signature mismatch.
closes https://github.com/ethereum/go-ethereum/issues/23153
=> accounts/abi/bind: check event signature before parsing

eth/state_accessor.go, eth/tracers/api.go
This might fix https://github.com/ethereum/go-ethereum/issues/23559. 
The current code has several goroutine groups, for different purposes. 
1. Executors which trace chains. Even if those are disabled (replaced with a random timout), the error(s) still happen. So they're not the problem.
2. One state-maker loop, which readies the state for the executors to trace on. This one also references/dereferences state. 
3. One result-catcher loop. This one spews data to the caller, and also dereferences nodes. 
I think the root cause is the fact that a `statedb.Commit`, which is done on `2` inside the `StateAt` call writes to the trie.Database. While doing the actual insert, it does hold the trie mutex, but I suspect that the locking is too granular: if we are in the middle of a large commit when …
=> eth/tracers: avoid unsyncronized mutations on trie database

eth/protocols/eth/peer.go, eth/protocols/eth/peer_test.go
This PR adds a new ```set``` object that abstract the cache for known blocks and transactions.
=> eth/protocols/eth: simplify peer known block/txs caches

graphql/graphql.go, graphql/schema.go
I'm not really certain _why_ it didn't work previously, but for some reason, this fixes it. 
```
$ cat query.json 
{"query":"query getAccessList($blockNumber: Long = 5000628) { block(number: $blockNumber) {  transactionAt(index: 71) { accessList { address storageKeys } }  }}","variables":null,"operationName":"getAccessList"}
```
Without this PR: 
```
curl -X POST 'http://localhost:8545/graphql' -H 'Content-Type: application/json'  --data @query.json | jq . 
{
"data": {
"block": {
"transactionAt": {
"accessList": [
{
"address": "0x57b96462b8d236cfec75dc9c0e0dcee20a22a7dd",
"storageKeys": []
},
{
"address": "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
"storageKeys": []
},
{
"address": "0x4774be14b1e81eb9f78f5d58b061f796fb2c744f",
"storageKeys": []
}
]
}
}
}
}
```
With this PR: 
```
$ curl …
```
=> graphql: add storage slots to access list

eth/protocols/snap/handler.go, trie/trie.go
This PR fixes some error handling to be more early/precise
=> eth/protocols/snap, trie: better error-handling

internal/ethapi/api.go, internal/web3ext/web3ext.go
We have a method to retrieve a block in RLP form (`debug.GetBlockRlp`), but sometimes we only need the header. Retrieving and managing the entire block RLP in that case can be unwieldy on mainnet tx counts. This PR introduces a `GetHeaderRlp` counterpart that only retrieves and serializes the header for use cases where that's enough.
=> internal/ethapi: support retrieving header RLPs too

internal/ethapi/api.go
Use `hextuils` to return `debug_getHeaderRlp` or `debug_getBlockRlp` (it's annoying to feed the result into other API calls because I always need to manually much with the hex string).
=> internal/ethapi: make header/block rlp retrieval canonical

eth/filters/filter_system_test.go
* Fix test finishing before goroutines complete and passing even though it should fail
* Update test to match that FromBlock and ToBlock are no longer ignored
* New test cases
=> eth/filters: fix TestPendingLogsSubscription

eth/protocols/eth/broadcast.go
This PR removes an unnecessary array of hashes that was used to count the number of items. It is replaced by a simple counter.
=> eth/broadcast: Remove unused hashes array in txn broadcaster

eth/api.go, internal/web3ext/web3ext.go
From time to time, it's useful to know what roots are "accessible", meaning they can be used for tracing, or can be used when doing a `setHead` to hit a good target block. This PR adds a method to the `debug` namespace, to iterate over the blocks and check where we have the roots on disk. 
This is also pretty interesting from a diagnostic perspective, as it reveals a bit about what the actual periods between flushes are.  
IN the example below, I use the pivot block as 'from', and `latest` as 'end'. 
```
~/go/src/github.com/ethereum/go-ethereum$ ./build/bin/geth --maxpeers 0 --nodiscover console
...
INFO [09-26|23:56:58.391] Loaded most recent local header          number=13,303,855 hash=d8199b..65e2fe td=31,341,758,120,762,708,097,878 age=25m23s
INFO [09-26|23:56:58.391] Loaded most …
```
=> eth/api: add rpc method to obtain which states are accessible

go.mod, go.sum
This update includes fixes for the *BSD build and go module vendoring.
=> go.mod: upgrade github.com/karalabe/usb

eth/fetcher/block_fetcher.go
if notification.number is invalid, we chould break this select, the old logic will also continue.
=> eth/fetcher: discard block `0` notifications

accounts/abi/bind/backends/simulated.go, accounts/abi/bind/backends/simulated_test.go
EIP-1559 changes the min amount of gas price we can execute a transaction with (current basefee).
The simulated backend always returned 1 on suggestGasPrice. With 1559 we need to return at least the basefee, otherwise transactions will never be mined.
=> accounts/abi/bin/backends: return basefee in suggestGasPrice's

miner/worker.go
The comment above this loop says it deep copies receipts, but it both didn't copy logs and set fields before the copy. In particular setting the original log's BlockHash was triggering Go's race detector for us.
=> miner: fix receipt deep copy in worker

consensus/clique/api.go, rpc/types.go
With an empty database, before this PR: 
```
> clique.getSigner("latest")
ERROR[10-29|13:43:56.110] RPC method clique_getSigner crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 153 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
github.com/ethereum/go-ethereum/rpc/service.go:200 +0x89
panic({0x103e200, 0x1b263a0})
runtime/panic.go:1038 +0x215
github.com/ethereum/go-ethereum/consensus/clique.ecrecover(0x0, 0x2)
github.com/ethereum/go-ethereum/consensus/clique/clique.go:153 +0x170
github.com/ethereum/go-ethereum/consensus/clique.(*Clique).Author(...)
github.com/ethereum/go-ethereum/consensus/clique/clique.go:213
github.com/ethereum/go-ethereum/consensus/clique.(*API).GetSigner(0xc003f7e3f0, 0x18) …
```
=> rpc: avoid crashing on clique getSigner during sync

core/blockchain.go, core/blockchain_insert.go, core/blockchain_repair_test.go
Fix snapshot missing when recovery from crash(like OOM or power failure). It is because write known block only check block and state without snapshot when recovering, which will lead to gap between newest snapshot and newest block state, and snapshot would not be used in following block executions.
Related logs:
> ERROR[08-29|03:30:33.524] Failed to journal state snapshot         err="snapshot [0xa85858f689482c30a06655a011698caeeedcbe76d2f4293a0b642b4f70027c93] missing"
I found the log above when geth shutdown gracefully, before that I just restart geth from crash
=> core: fix snapshot missing when recovery from crash

core/vm/evm.go, eth/tracers/tracers_test.go
This PR fixes (at least partially?), https://github.com/ethereum/go-ethereum/issues/23811 . 
The current scope-tracer did not invoke enter()/exit() on 0-value `CALL` to non-existing accounts.
=> eth/tracers: invoke enter/exit on 0-value calls to inex accounts

consensus/ethash/ethash.go, consensus/ethash/mmap_help_linux.go, consensus/ethash/mmap_help_other.go
This PR avoids a pretty rare crash. 
Some more info here: https://github.com/edsrzf/mmap-go/issues/12#issuecomment-949649350 . 
When we map a file for generating the DAG, we do a simple truncate to e.g. `1Gb`. This is fine, even if we have nowhere near `1Gb` disk available, as the actual file doesn't take up the full `1Gb`, merely a few bytes. When we start generating into it, however, it eventually crashes with a `unexpected fault address `. 
Examples: 
- https://github.com/ethereum/go-ethereum/issues/21928 
- https://github.com/ethereum/go-ethereum/issues/23453
There are two ways we can fix this, the simplest being to use the `fallocate` linux system call. 
The second way is to convert the internals of ethash; instead of generating into a `[]byte`, we generate into an interface which …
=> consensus/ethash: avoid runtime errors due to OOD on mmap writes

cmd/puppeth/wizard_intro.go
This PR makes the ssh connection sequential. This is important in the case where user feedback is needed, e.g. when the ssh key is password protected. 
With this PR: 
```
INFO [01-08|11:24:53.385] Administering Ethereum network           name=rinkeby
INFO [01-08|11:24:53.387] Dialing previously configured server     server=karalabe:id_rsa_2017@boot.rinkeby.io
What's the decryption password for /home/user/.ssh/id_rsa_2017? (won't be echoed)
>
INFO [01-08|11:25:00.430] Dialing previously configured server     server=karalabe:id_rsa_2017@web.rinkeby.io
What's the decryption password for /home/user/.ssh/id_rsa_2017? (won't be echoed)
>
INFO [01-08|11:25:06.580] Starting remote server health-check      server=karalabe:id_rsa_2017@web.rinkeby.io
INFO [01-08|11:25:06.580] Starting remote server …
```
=> cmd/puppeth: make it possible to have pw-protected keyfiles

core/tx_noncer.go, core/tx_pool.go, core/tx_pool_test.go
This PR supersedes https://github.com/ethereum/go-ethereum/pull/21164  by @WeiLoy . The original PR was based off a fork of geth but on `master` , and I was not able to push the rebased + fixed version onto a `master` branch. 
I believe that the original implementation by @WeiLoy was correct, but it had been a bit bitrotted, the PR is quite old. 
Here are the benchmarks compared to current master: 
```
benchstat before.txt after3.txt 
name                           old time/op  new time/op  delta
PoolMultiAccountBatchInsert-6   993µs ±11%   281µs ± 7%  -71.72%  (p=0.008 n=5+5)
```
=> core: more efficient nonce-update in txpool

rpc/client.go
This avoids quadratic time complexity in the lookup of the batch element
corresponding to an RPC response. Unfortunately, the new approach
requires additional allocation for the map.
Fixes #22805
=> rpc: linear time batch response matching

eth/api_backend.go, eth/state_accessor.go, eth/tracers/api.go, eth/tracers/api_test.go, eth/tracers/tracer.go, les/api_backend.go
This PR changes long-running chain tracing, so that it at some points releases the memory trie db, and switch over to a fresh disk-backed trie.
=> eth: make traceChain avoid OOM on long-running tracing

consensus/clique/clique.go, miner/worker.go
When a clique network is not progressing, we see a memory leak: 
This is pretty bad, because whenever one signer falls off, then the rest of them eventually will crash too -- so one failing sealer will wreak havoc, causing other sealers to crash and making it very difficult to get the network live again. 
Every `3` seconds (`miner.recommit` interval) we shove a new task to be handed, where we e.g. deep-copy the receipts and other stuff and send it over a channel `w.taskCh <- &task{receipts: receipts, state: s, block: block, createdAt: time.Now()}:`
That get's shoved into a map
```
w.pendingTasks[sealHash] = task
```
So every 3 seconds (miner recommit), we leak a block into memory, basically. 
The routine that would have cleaned that up : 
```
clearPending := func(number uint64) { …
```
=> miner, consensus/clique: avoid memory leak during block stasis

les/vflux/client/serverpool_test.go, les/vflux/client/valuetracker.go, les/vflux/server/balance_tracker.go
This PR fixes a faulty condition in the les/vflux/server package that caused BalanceOperation to panic in some rare cases. The data races reported in https://github.com/ethereum/go-ethereum/issues/23848 are also fixed in les/vflux/client.
=> les/vflux: fixed panic and data races

core/tx_pool.go
The price limit is supposed to exclude transactions with too low fee
amount. Before EIP-1559, it was sufficient to check the limit against
the gas price of the transaction. After 1559, it is more complicated
because the concept of 'transaction gas price' does not really exist.
When mining, the price limit is used to exclude transactions below a
certain effective fee amount. This change makes it apply the same check
earlier, in tx validation. Transactions below the specified fee amount
cannot enter the pool.
Fixes #23837
=> core: check effective tip in txpool pricelimit validation

cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/suite.go
Debugging recent geth-failures in hive, it took a while to realize that it's because geth doesn't support ETH65 any longer. This PR makes such failures a bit more easy to figure out.
=> cmd/devp2p/internal: clarify protocol version in tests + more explicit error

cmd/evm/internal/t8ntool/transaction.go, core/error.go, core/state_processor_test.go, core/state_transition.go, core/vm/errors.go, core/vm/evm.go
This retroactively implements requirements or [EIP-2681](https://eips.ethereum.org/EIPS/eip-2681) for the account nonce upper limit.
Consensus tests (covering only CREATE/CREATE2 case): https://github.com/ethereum/tests/pull/934
Opening PR as requested in https://github.com/ethereum/tests/pull/934#issuecomment-959815137
=> core/vm: implement EIP-2681: Limit account nonce to 2^64-1

core/rawdb/accessors_chain.go, core/rawdb/accessors_chain_test.go, eth/api_backend.go
=> core/rawdb: add slow path for getting legacy logs

cmd/devp2p/dns_cloudflare.go, cmd/devp2p/dnscmd.go
This was apparently recently changed by Cloudflare, and
began returning an error: `TTL must be between 60 and 86400 seconds, or 1 for Automatic`
A failing run with an example error: https://github.com/etclabscore/discv4-dns-lists/actions/runs/1429049560
A fixed run with no error: https://github.com/etclabscore/discv4-dns-lists/actions/runs/1429650853
I created a new variable because `treeNodeTTL` is also used by the Route53 implementation.
=> cmd/devp2p: update TTL max for Cloudflare

accounts/abi/bind/backends/simulated.go
Now that `SimulatedBackend.SuggestGasPrice` inspects member values, a lock needs to be added to prevent a race condition.
=> accounts/abi/bind/backends: fix race condition in simulated backend

core/rawdb/freezer_batch.go, core/rawdb/freezer_test.go
This PR provides a better error message in case there's a mismatch between what's in ancients and what we try to put there. Right now, we can't really tell if we're missing something or if we have too much data there already.
=> core/rawdb: better error message in freezer

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, console/console_test.go, core/genesis.go, miner/miner_test.go
I was trying to tinker with some large gas limits to speed up some contract tests and while `--miner.gaslimit` does work, it takes a long time to reach if the initial gas limit is much lower.
=> cmd/geth: add flag --dev.gaslimit for dev mode

ethclient/ethclient.go, ethclient/ethclient_test.go, ethclient/signer.go
`types.Sender` caches signers' recovered addresses for transactions. `senderFromServer` takes advantage of that with two different invocations:
- It can be used with both `blockhash` and `addr` specified to populate the cache. `senderFromServer` will return the already known address, which `types.Sender` will remember and attach to the transaction.
- It can be used with only `blockhash` specified to query the cache. `senderFromServer`'s `Equal` implementation only checks the `blockhash`, so if the address was previously cached for this block hash, `types.Sender` will remember that and return it. However, if the cache misses, `senderFromServer` _should_ return an error, as it doesn't know the address. That's what this PR fixes. Previously, the check for a cache miss was if `blockhash` was …
=> ethclient: fix tx sender cache miss detection

cmd/evm/internal/t8ntool/transaction.go, cmd/evm/testdata/15/exp2.json, cmd/evm/testdata/16/exp.json, cmd/evm/testdata/17/exp.json
current output
```
{
"error": "gasPrice exceeds 256 bits",
"address": "0x54b0dfad82e7660aa185dbd371c359757fc3e656",
"hash": "0x63cc78c654a6cc5f8ab4f17d03caef02d49ef43275282b12d432880f1192b987",
"intrinsicGas": 21000
}
```
new output:
```
{
"error": "gasPrice exceeds 256 bits",
"address": "0x54b0dfad82e7660aa185dbd371c359757fc3e656",
"hash": "0x63cc78c654a6cc5f8ab4f17d03caef02d49ef43275282b12d432880f1192b987",
"intrinsicGas": "0x5208"
}
```
=> cmd/evm: make t9n intrinsicGas output hex, fixes #23883

core/vm/opcodes.go
This cleans up a pet peeve I've had for years. 
`iota` is useful when we don't really care what number something winds up with, we just want an enum-like thing which has a certain ordering between elements. 
Opcodes, however, are externally defined. It's IMO wrong to assign them by using `iota`, as if we don't really care what number `CALL` maps to internally. 
Aside from that, having it directly defined as in this PR makes it easier to check a particular opcode-to-byte with eyes alone, without relying on IDE magic to infer the actual number for you.
=> core/vm: don't use iota for opcode definitions

core/rawdb/chain_iterator.go
When we restore from ancients, we go through them and write the `hash->number` mapping into leveldb. As of a while back, we now have a methods to read ancients sequentially a lot faster. 
This PR can most easily be tested by doing a `geth --goerli removedb`, and leave ancients intact. Then a `geth --goerli --nodiscover --maxpeers 0`. 
~~The PR (in draft) contains a little self-validator, which should `CRIT` if the contents is not correct.~~
=> core/rawdb: use AncientRange when initializing leveldb from freezer

p2p/enode/localnode.go, p2p/simulations/adapters/types.go
Fix integer conversions discovered by CodeQL
=> p2p/enode: store local port number as uint16

trie/proof.go, trie/proof_test.go
Reject trie range proofs if they contain deletions, otherwise these would be noop entries that just bloat the response and may potentially cause trouble down the line since a semi-invalid proof passes verification.
=> trie: reject deletions when verifying range proofs

cmd/evm/internal/t8ntool/flags.go, cmd/evm/internal/t8ntool/transition.go, cmd/evm/main.go
Apologizes for another PR - my new commits weren't coming through in #23933.
Okay I misunderstood the meaning of the args `tracer.nomemory` and `tracer.noreturndata`. I understand now that it is preferred that memory and return data are *not* printed by default. Given this, I think the flag name are confusing. I didn't realize until looking deeply into this that `--tracer.nomemory=false` is a valid argument. I would've assumed the flag did not take a value and was a simple on/off switch, and therefore assumed the correct default behavior for these values should be *on*. [Others](https://discord.com/channels/717003406484701255/717010234669006899/910916940426530886) have also encountered this.
For these reasons, I propose renaming them to `tracer.memory` and `tracer.returndata` to avoid the …
=> cmd/evm: rename t8n args to improve clarity when tracing

cmd/devp2p/internal/v4test/discv4tests.go
This PR fixes two problems in devp2p tests (and through them, hive). 
1. Make the output more detailed about what is returned (always print packet kind). 
2. Allow Ping response to unsolicited findnode. 
Without this PR, nethermind fails a hive protocol tests, and I misinterpreted the result (https://github.com/NethermindEth/nethermind/issues/3617). Ergo, the output was not fool-proof.
=> cmd/devp2p: fix false-positive hive-test

consensus/clique/api.go
Doing `clique.getSigner('00ff')` (hex string without `0x`) in the console caused a crash
=> clique: fix block number unmarshal

cmd/devp2p/internal/v4test/discv4tests.go
This PR fixes two problems in devp2p tests (and through them, hive). 
1. Make the output more detailed about what is returned (always print packet kind). 
2. Allow Ping response to unsolicited findnode. 
Without this PR, nethermind fails a hive protocol tests, and I misinterpreted the result (https://github.com/NethermindEth/nethermind/issues/3617). Ergo, the output was not fool-proof. 
----
second attempt
=> cmd/devp2p/internal/v4test: fix false-positive hive test

core/state/snapshot/wipe.go, core/state/snapshot/wipe_test.go, core/vm/opcodes.go
This PR removes the 'wiper', which was used in an early version of snap sync to clean out snap data. It was deprecated since we figured out how to use the mostly-correct-but-partially-corrupt snapshot data without wiping it fully. 
This PR also removes some "unofficial opcodes used for parsing", which, actually, aren't used for parsing.
=> core/vm, core/state/snapshot: remove unused code

core/vm/contract.go
Small cleanup to remove unneed extra helper + use `STOP` literal instead of `0`.
=> core/vm: Simplify Contract.GetByte function

trie/stacktrie.go
Trim the search key from head as it's being pushed deeper into the trie.
Previously the search key was never modified but each node kept
information how to slice and compare it in `keyOffset`. Now the `keyOffset`
is not needed as this information is included in the slice of the
search key. This way the `keyOffset` can be removed and key manipulation
simplified.
BTW, I ported this Trie implementation (without hashing implementation) to C++. This helped me a lot, thanks.
=> trie: simplify StackTrie implementation

core/vm/errors.go, core/vm/instructions.go, core/vm/interpreter.go, core/vm/jump_table.go
This simplifies interpreter loop exit condition to just `err != nil`. This catches:
- reverting instructions (i.e. just `REVERT`),
- halting instructions (by them returning `errStopToken`).
Also `operation.jumps` check is removed by setting `pc - 1` inside the jump instruction and doing `pc++` in the loop unconditionally.
Finally, instructions manipulating return data are handling this themselves. This eliminates another `operation.returns` check.
=> core/vm: Simplify error handling in interpreter loop

core/vm/evm.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/instructions_test.go, core/vm/jump_table.go, core/vm/memory_table.go, core/vm/opcodes.go, params/protocol_params.go
Also rename helper functions.
This was [proposed in 2016](https://github.com/ethereum/EIPs/issues/59), [Solidity uses this since 2017](https://github.com/ethereum/solidity/blob/develop/Changelog.md#0412-2017-07-03), and evmone and other VMs use the `keccak256` name. This brings geth in line with those.
The only concern could be if there is some kind of intput/output geth produces where this makes a difference.
There is also a field which is serialised as `sha3Uncles` -- not sure what relies on it, but of course haven't touched that here.
=> core/vm: Rename SHA3 instruction to KECCAK256

eth/protocols/snap/handler.go, eth/protocols/snap/peer.go, oss-fuzz.sh, tests/fuzzers/snap/debug/main.go, tests/fuzzers/snap/fuzz_handler.go
This is the fuzzer that found the second vulnerability in the snap handler (https://github.com/ethereum/go-ethereum/security/advisories/GHSA-59hh-656j-3p7v).
=> tests/fuzzers: add snap protocol handling fuzzer

core/vm/instructions.go, core/vm/interpreter.go, core/vm/jump_table.go, eth/tracers/logger/logger_json.go
Fixes #23968.
I had trouble running tests locally, but `go test -v ./tests` passed (and displayed a lot of state tests lines). `make test` runs into various failures regarding "too many files open" or networking issues. In short: this change may be broken as I couldn't 100% verify with tests.
=> core/vm: Move interpreter.ReadOnly check into the opcode implementations

core/vm/instructions.go, core/vm/jump_table.go
The opcode was renamed in the codebase in 2017, but the functions were kept unchanged.
There are many other places where `suicide` is used as a term, including a lot in `core/state` (such as `StateDB.Suicide`) and the `Suicide`/`HasSuicided` interface in `core/vm`.  The nitpicker in me would try to rename all those, but that may be too much for little benefit. 
Let me know if this change here is not very useful and I'll avoid doing anything similar later.
=> core/vm: Rename opSuicide to opSelfdestruct

p2p/enr/enr.go
`sig` and `seq`
reduce a memory allocation
=> p2p/enr: reduce allocation in Record.encode

eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/fetchers.go, eth/downloader/fetchers_concurrent_bodies.go, eth/downloader/fetchers_concurrent_headers.go, eth/downloader/fetchers_concurrent_receipts.go, eth/downloader/queue.go, eth/downloader/queue_test.go, eth/protocols/eth/dispatcher.go, eth/protocols/eth/handlers.go
Curiously, the downloader is partially limited by CPU, because data deliveries are processed whilst the queue's lock is held. This means that no matter how good we are at downloading stuff, the data will end up being integrated into the queue sequentially. As long as the integration is faster than deliveries, this is fine.
However, the current downloader also does the data hashing (headers, txs, uncles, receipts) on the integration thread. This, it turns out, is slower than the rate at which we can pull data from the network, leading to hasher operations limiting th ebandwidth usage.
This PR introduces a pre-processing step after a reply is delivered but before it's given to the downloader to iterate over the delivered data, hash it and inject the hashes into the response. This was the …
=> eth: pre-process downloader responses on the peer reader thread

core/vm/instructions.go, core/vm/interpreter.go, core/vm/jump_table.go
Instead of checking if a slot in the jump table is `nil`, fill all unassigned slots with `opUndefined()` returning expected error `ErrInvalidOpCode`.
=> core/vm: fill gaps in jump table with opUndefined

core/vm/instructions.go, core/vm/interpreter.go, core/vm/interpreter_test.go
Fixes https://github.com/ethereum/go-ethereum/issues/23969
=> core/vm: Move interprepreter intrerruption check to jump instructions

README.md
Previous link leads to incorrect (more recent) version of web3.js docs.
go-ethereum uses v0.20.1. The docs for 0.2x.x have been archived at this Github link.
This was previously discussed in #23703
=> readme: use correct link for web3 docs

core/blockchain.go, core/rawdb/chain_iterator.go
This PR fixes a special corner case in transaction indexing.
When the chain is rewound by `SetHead` to a historical point which is even lower than the transaction indexes tail, then system will report `Failed to decode block body` error all the time, because the relevant blocks are already deleted.
In order to avoid this "non-critical-but-annoying" issue, we can recap the indexing target to `head+1`(to is excluded, so it means indexing transactions from 0 to head).
=> core, core/rawdb: fix transaction indexing

core/vm/evm.go, core/vm/interpreter.go
This PR removes the `NoRecursion` option from the `vm.Config`. The option was never set anywhere, so this just removes some unused code.
=> core/vm: remove no-recursion option from config

p2p/simulations/README.md
- Fix pronoun (which -> that)
- Fix hard to understand network description
=> p2p/simulations: improve README language

miner/worker.go
Whenever The Merge happens, the pow mining will be meaningless and be disabled by default in miner package. However miner package is still responsible for creating/maintaining the pending block/state for API usage.
This PR re-enables this functionality.
=> miner: update pending block even after the PoS transition

core/vm/opcodes.go
This function does not seem to be used at all. If it is needed somehow, I'd suggest to rename it to `IsUnconditionalJump`.
=> core/vm: Remove dead code (IsStaticJump)

core/vm/interpreter.go, core/vm/jump_table.go
This PR moves the dynamic memory check function to only be checked if the op has a dynamic gas function. This is strictly not a guarantee, just how things are, and it allows us to skip two conditionals on the cheap ops. 
One minor semantic change is that `cost` is set earlier, making errors more correct than previously (if erroring on e.g. shallow stack)
=> core/vm: avoid memory expansion check for trivial ops

les/vflux/client/serverpool_test.go, p2p/nodestate/nodestate.go
This PR fixes some data races in the server pool tests and also one in the NodeStateMachine.
Fixes https://github.com/ethereum/go-ethereum/issues/23848
=> les/vflux/client, p2p/nodestate: fix data races

rpc/handler.go
There's `t` parameter overwriting for messages in `rpc` package when Geth node uses `--log.json` flag. Here's an example of such overwriting:
```JSON
{"err":"sealing paused while waiting for transactions","lvl":"warn","msg":"Block sealing failed","t":"2021-12-15T14:16:48.131233613+03:00"}
{"lvl":"dbug","msg":"Served rpc_modules","reqid":"1","t":"33.633µs"}
{"lvl":"trce","msg":"Handled RPC response","reqid":"1","t":"334ns"}
{"lvl":"dbug","msg":"Served web3_clientVersion","reqid":"2","t":"27.963µs"}
```
In this PR I've tried to fix this by renaming `t` parameter.
=> rpc: fix time key collision for logger with json output

core/rawdb/accessors_metadata.go, eth/backend.go, internal/node/shutdown_marker.go, internal/shutdowncheck/shutdown_tracker.go, les/client.go
Successor to https://github.com/ethereum/go-ethereum/pull/22974, fixes https://github.com/ethereum/go-ethereum/issues/22580
=> core,eth,les: update unclean shutdown markers regularly

tests/solidity/contracts/OpCodes.sol
=> tests/solidity/contracts: fix typo in OpCodes.sol

core/forkid/forkid_test.go, eth/catalyst/api.go, eth/catalyst/api_test.go, eth/catalyst/api_types.go, eth/catalyst/gen_blockparams.go, eth/catalyst/gen_ed.go, params/config.go, rpc/errors.go
This PR implements kintsugi-spec v3 (with engine api version  v1.0.0-alpha.5)
A rundown of all changes can be found here: https://hackmd.io/@n0ble/kintsugi-spec
It includes a new fork block `MergeForkBlock` which should be updated before TTD is reached. 
This `MergeForkBlock` is only used for the forkID calculation, nothing else.
This is a block that should happen *before* the merge to fork non-merge ready nodes off the network.
=> eth/catalyst: implement kintsugi-spec v3

core/tx_pool.go
fix #24079
`pool.gasPrice` is config by `pricelimit`. 
https://github.com/ethereum/go-ethereum/blob/cc87cbd70af18241f79908eec10bb3c51a9fbda4/core/tx_pool.go#L300
`baseFee` will always changed by tx pool . so if you do that, users will not able to send tx below baseFee rather than `pricelimit`. highly recommended revert this pr  #23855.
https://github.com/ethereum/go-ethereum/blob/cc87cbd70af18241f79908eec10bb3c51a9fbda4/core/tx_list.go#L424
#23855
#23837
=> core: ignore basefee when comparing with pool gasprice in txpool

accounts/abi/unpack.go
Instead of recomputing the `outputLen` reuse existing var that has the length.
=> Reuse var for getting outputLen

core/types/dynamic_fee_tx.go
While researching something about EIP-1559, I noticed that these fields are not documented. While I still think the Go names are better than the JSON-RPC ones, it can't hurt to document what they correspond to.
=> core/types: document JSON field name equivalents of DynamicFeeTx

cmd/geth/main.go
Before:
```console
➜  go-ethereum git:(master) ./build/bin/geth --sepolia 2>&1 | grep -i -E 'sepolia|mainnet'
INFO [12-22|10:13:57.694] Starting Geth on Ethereum mainnet... 
INFO [12-22|10:13:57.694] Bumping default cache on mainnet         provided=1024 updated=4096
```
After:
```console
➜  go-ethereum git:(fix/missing-sepolia-mentions) ./build/bin/geth --sepolia 2>&1 | grep -i -E 'sepolia|mainnet'
INFO [12-22|10:13:29.484] Starting Geth on Sepolia testnet... 
```
=> cmd/geth: add missing sepolia testnet flag checks

core/rawdb/accessors_chain.go
Doing `ReadCanonicalHash` inside `ReadAncients` is a no-no, causing a double-locking. This PR fixes it.
=> core/rawdb: fix double-lock causing hang. fixes #24159

graphql/graphql.go
Fixes #24167
New behaviour is that the endpoint returns results only for available blocks without returning an error when it doesn't find a block. Note we skip any block after a non-existent block.
This adds a header fetch for every block in range (even if header is not needed). Alternatively we can do the check in every field's resolver method to avoid this overhead.
=> graphql: check for existence first when querying list of blocks

ethclient/ethclient.go, interfaces.go
SyncProgress was modified in PR #23576 to add the fields reported for
snap sync. The PR also changed ethclient to use the SyncProgress struct
directly instead of wrapping it for hex-decoding. This broke the
SyncProgress method.
Fix it by putting back the custom wrapper. While here, also put back the
fast sync related fields because SyncProgress is stable API and thus
removing fields is not allowed.
Fixes #24180
=> ethclient: fix unmarshaling of ethereum.SyncProgress

graphql/graphql.go
=> graphql: fix pre-byzantium receipt status

graphql/graphql.go
Fixes #24161
The issue is in the condition `b.numberOrHash == nil && b.header == nil`. The linked issue is coincidentally also fixed by #24190 because then `b.header` is always present, but this PR is a more correct fix for this particular bug.
=> graphql: fix block resolving for parent field

les/server_handler.go
This PR fixes a crash that happened on one of the sealers, after a `setHead` was performed on it: 
```
Jan 04 10:10:20 rinkeby-aws-eu-north-1-001 geth panic: runtime error: invalid memory address or nil pointer dereference
Jan 04 10:10:20 rinkeby-aws-eu-north-1-001 geth [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc69da5]
Jan 04 10:10:20 rinkeby-aws-eu-north-1-001 geth goroutine 155 [running]:
Jan 04 10:10:20 rinkeby-aws-eu-north-1-001 geth github.com/ethereum/go-ethereum/les.(*serverHandler).broadcastLoop(0xc007bf98c0)
Jan 04 10:10:20 rinkeby-aws-eu-north-1-001 geth github.com/ethereum/go-ethereum/les/server_handler.go:424 +0x3a5
Jan 04 10:10:20 rinkeby-aws-eu-north-1-001 geth created by github.com/ethereum/go-ethereum/les.(*serverHandler).start
Jan 04 10:10:20 …
```
=> les: fix crash happening after setHead

cmd/geth/snapshot.go, core/rawdb/accessors_state.go, eth/protocols/snap/sync.go, trie/sync.go
When doing some syncs, I noticed that in the heal phase, the db reads is going through the roof. This PR aims to bring that down a little bit, or at least reduce some allocation when that happens, by using `db.Has` wherever possible. 
I'll do a benchmark later, also to verify that it doesn't break anything.
=> trie, core, eth: use db.has over db.get where possible

eth/handler.go
The whitelist mechanism got broken in https://github.com/ethereum/go-ethereum/pull/23576, afaict, making it so that if the whitelist check succeeds, the code stalls. The peer is left somehow neither accepted nor rejected, in a state where it's marked as shutting down but not actually kicked out. 
This is the cause behind https://github.com/ethereum/go-ethereum/issues/24202 . 
Also, aside from not being able to sync, it also (on my test) causes failure to shut down. 
With this fix, I was able to start syncing with peers after the check completes.
=> eth: continue after whitelist check

cmd/ethkey/utils.go
This PR fixes a small typo `calulcated -> calculated`
=> Fix comment typo

core/blockchain.go
It turns out memory allocation is really inefficient in goleveldb batch. Constructing a large batch will take a few seconds and most of the time is spent on memory allocation. 
During the chain sync we noticed transaction indexing is expensive, one big cost is constructing a large batch for indexes. Therefore in this PR the single huge batch is divided into several small one according to the ideal batch size.
=> core: periodically flush the transaction indexes

cmd/geth/version_check_test.go
TestGethPubKeysParseable is inspired by the comment
in cmd/geth/version_check.go:141: "our pubkeys should be parseable".
TestKeyID checks the minisign public key of each gethPubKeys.
=> cmd/geth: add tests for version_check

trie/iterator.go
Since `resolver` only uses methods from `ethdb.KeyValueReader`, this smaller interface can be used instead.
=> trie: readonly interface for trie iterator's resolver

crypto/ecies/ecies_test.go, crypto/ecies/params.go
There is an error, which says "ecies: shared key params are too big", if we use P384 for encrypt. As it is said in readme.md, curve P384 should use AES192 not AES256.
=> crypto/ecies: use AES-192 for curve P384

cmd/geth/dbcmd.go, cmd/utils/flags.go, core/rawdb/freezer.go, core/rawdb/freezer_batch.go, core/rawdb/freezer_table.go, core/rawdb/freezer_table_test.go, core/rawdb/freezer_test.go
When opening the freezer in readonly mode (e.g. `db inspect` command) we still perform repair, possibly modifying the underlying files. This PR changes that and only raises an error instead when freezer is in an invalid state.
=> core/rawdb: Enforce readonly in freezer instantiation

cmd/geth/dbcmd.go, core/state/snapshot/journal.go
```
[user@work go-ethereum]$ ./build/bin/geth --sepolia db metadata
INFO [11-12|14:02:05.331] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-12|14:02:05.331] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [11-12|14:02:05.332] Set global gas cap                       cap=50,000,000
INFO [11-12|14:02:05.332] Allocated cache and file handles         database=/home/user/.ethereum/sepolia/geth/chaindata cache=512.00MiB handles=262,144 readonly=true
INFO [11-12|14:02:05.536] Opened ancient database                  database=/home/user/.ethereum/sepolia/geth/chaindata/ancient readonly=true
+------------------------+--------------------------------------------------------------------+
|         FIELD          | …
```
=> cmd/geth: add db cmd to show metadata

signer/core/gnosis_safe.go, signer/core/signed_data_test.go
After [EIP-1344 - ChainID opcode](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1344.md) was introduced, starting from 1.3.0 Gnosis Safe contracts added `chainId` to the EIP-712 domain for transactions - [changelog](https://github.com/gnosis/safe-contracts/blob/main/CHANGELOG.md#add-chainid-to-transaction-hash)
The `GnosisSafeTx` struct didn't support the `chainId` property and couldn't be used with newer versions of the Safe contracts.
This PR adds support for `chainId` in `GnosisSafeTx`, making it possible to use to transact with Safe Contracts version 1.3.0
Thanks to @rmeissner for the help with the PR
=> signer/core: support chainId in GnosisSafeTx

internal/ethapi/transaction_args.go
Using same receiver name will be greater than using different name.
=> Chore: use same receiver names

rpc/client.go, rpc/http.go, rpc/http_test.go, rpc/json.go, rpc/server.go, rpc/server_test.go, rpc/testservice_test.go, rpc/types.go, rpc/websocket.go, rpc/websocket_test.go, signer/core/api.go
This replaces the sketchy and undocumented string context keys for HTTP requests with a defined interface. Using string keys with context is discouraged because the keys may clash with keys created by other packages.
We added these keys to make connection metadata available in the signer, so this change also updates the signer to use the new PeerInfo API.
=> rpc: add PeerInfo

core/blockchain.go, core/blockchain_repair_test.go, eth/fetcher/block_fetcher_test.go, graphql/graphql_test.go, internal/jsre/jsre_test.go, miner/miner_test.go, miner/worker_test.go, node/node_test.go, rpc/client_test.go, signer/core/api_test.go
This PR fixes following issues:
1.
testRepair goroutine leak
```
goroutine 73 [select]:
github.com/ethereum/go-ethereum/core.(*BlockChain).update(0xc00025b300)
/repos/go-ethereum/core/blockchain.go:2443 +0x513
created by github.com/ethereum/go-ethereum/core.NewBlockChain
/repos/go-ethereum/core/blockchain.go:378 +0xcb9
```
2.
TestRegisterHandler_Successful goroutine leak
```
goroutine 49 [select]:
github.com/ethereum/go-ethereum/accounts.(*Manager).update(0xc000198000)
/repos/go-ethereum/accounts/manager.go:223 +0x15b4
created by github.com/ethereum/go-ethereum/accounts.NewManager
/repos/go-ethereum/accounts/manager.go:80 +0x585
...omit others
```
3.
TestStartStopMiner
```
goroutine 69 [select]:
github.com/ethereum/go-ethereum/core.(*BlockChain).update(0xc000258600) …
```
=> core, miner, rpc, eth: fix goroutine leaks in tests

trie/proof_test.go
This is probably a case where I am setting up something incorrectly, though the test fails when I remove the 1st elements of `keys` and `vals` (but passes otherwise). I was hoping you could take a look, since I couldn't exactly figure it out. 
I'm assuming it's because there's a shared prefix on the keys, though not sure.
This is the stack trace I am getting:
```
panic: trie.hashNode: invalid node: <a94e2bd8ee1e6b49b14831e8bd8a7fa01f4582bd1c22e514468c62ee05ca144e>
goroutine 19 [running]:
testing.tRunner.func1.2({0x43a35a0, 0xc000212620})
/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1212 +0x3b6
panic({0x43a35a0, 0xc000212620}) …
```
=> trie: test for edgecase in VerifyRangeProof

internal/ethapi/api.go
Because there is no `fullTx` parameter at function signatures and
uncle apis does not return txs also, those lines are un-necessary.
=> Chore: remove un-necessary comment describing un-used parameter `fullTx`

accounts/errors.go
Fix typo in `accounts/errors.go`, `secodn` => `second`.
=> account: fix typo in errors.go

eth/backend.go, eth/catalyst/api.go, eth/catalyst/api_types.go, miner/miner.go, miner/miner_test.go, miner/stress/beacon/main.go, miner/worker.go, miner/worker_test.go
This PR removes the duplicated code in the catalyst package, reuse the miner package code instead.
Highlight the critical changes in this PR:
- Offer one more API in the miner package called `GetSealingBlock` which will assemble and return the sealing block based on the given parameters.
- Sealing environment is abstracted out, all the functions will receive the sealing environment for further operations
- Uncle blocks management is changed for sake of simplification
=> eth, miner: remove duplicated code

accounts/abi/argument.go
Since `len(nonIndexedArgs)` is definitely `0` in this context, the code can be simplified.
=> accounts/abi: simplify Arguments.Unpack

core/rawdb/accessors_state.go
This changes the lookup of code, so that we check prefixed code before we checked legacy.
=> core/rawdb: do prefixed lookup first

eth/tracers/api.go
This is an alternative to #24283, and also closes  #23205.
This PR fixes the root cause, which are data-races in the blockhash cache. Although crisp new evm's were used, they all fell back to the same blockhash lookup closure. 
This PR produces identical results each time: 
```
-rw-rw-r-- 1 martin martin 1738663 jan 24 21:32 foo.1643056374.json
-rw-rw-r-- 1 martin martin 1738663 jan 24 21:32 foo.1643056376.json
-rw-rw-r-- 1 martin martin 1738663 jan 24 21:32 foo.1643056377.json
-rw-rw-r-- 1 martin martin 1738663 jan 24 21:32 foo.1643056378.json
-rw-rw-r-- 1 martin martin 1738663 jan 24 21:32 foo.1643056379.json
-rw-rw-r-- 1 martin martin 1738663 jan 24 21:33 foo.1643056383.json
-rw-rw-r-- 1 martin martin 1738663 jan 24 21:33 foo.1643056384.json
-rw-rw-r-- 1 martin martin 1738663 jan 24 …
```
=> eth/tracers: avoid using blockCtx concurrently

cmd/utils/flags.go
The PR https://github.com/ethereum/go-ethereum/pull/24119 introduced a regression where if the specified datadir for dev mode didn't exist geth wouldn't start. https://github.com/ethereum/go-ethereum/pull/24281 fixed that regression.
In this PR we add an extra check to see if the datadir exists. If so, then the db is opened in read-only. Otherwise it's opened in write-mode so leveldb can create the relevant files. Note that this is not the live db that dev mode uses for its operations. It's only opened temporarily to check for existence of a genesis block and closed immediately and hence doesn't need write access.
=> cmd/utils: open db in readonly when dev datadir exists

docs/_getting-started/index.md
Fast sync mode has [been removed](https://github.com/ethereum/go-ethereum/commit/c10a0a62c3537fbcf899358e3c3d6be9507fa18c#diff-23ce58cf1d66350fa0080c4020e681646f05e1d033d97930aaea0911643da47a) (#23576) from the Geth client, and this PR removes it from the Getting Started page of the docs too.
=> [DOCS]: Remove fast sync from "Getting Started"

rpc/http.go
When talking to an HTTP2 server, there are situations where it needs to "rewind" the Request.Body.
To allow this, we have to set up the `Request.GetBody` function to return a brand new instance of the body.
If not set, we can end up with the following error:
```
http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error
```
Commit :
https://sourcegraph.com/github.com/golang/net/-/commit/cffdcf672aee934982473246bc7e9a8ba446aa9b?visible=2
Close #24291
=> rpc: set Request.GetBody for client requests

.gitmodules, tests/init_test.go, tests/state_test.go
I converted evmone's benchmarks to StateTest format and they are available at https://github.com/ipsilon/evm-benchmarks. Here added as a git submodule. We are still discussing how exactly extract and maintain the benchmark suite outside of the evmone project.
Then I copied a lot of code from `TestState()` to create `BenchmarkState()` with the goal to use the lowest EVM execute function possible. I stopped at `EVM.Call()` but I believe even `Interpreter.Run()` is possible.
If some refactoring is done, some code can be shared between `TestState()` and `BenchmarkState()`. But the test runner is quite convoluted with `reflect` being used at some level...
```
go test -run - -bench='.*' ./tests/...
```
=> tests: external evm benchmarks

cmd/geth/accountcmd_test.go
before this change this test was failing reproducibly with:
```
--- FAIL: TestAccountImport (0.00s)
--- FAIL: TestAccountImport/correct_account (5.08s)
test_cmd.go:262: (stderr:4) INFO [01-30|04:50:50.619] Maximum peer count                       ETH=50 LES=0 total=50
test_cmd.go:262: (stderr:4) INFO [01-30|04:50:50.619] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
test_cmd.go:262: (stderr:4) WARN [01-30|04:50:50.622] Lowering memory allowance on 32bit arch  available=3838 addressable=2048
test_cmd.go:262: (stderr:4) WARN [01-30|04:50:50.622] Sanitizing cache to Go's GC limits       provided=1024 updated=682
test_cmd.go:262: (stderr:4) INFO [01-30|04:50:50.623] Set global gas cap                       cap=50,000,000
test_cmd.go:242: …
```
=> cmd/geth: make test pass on a pi4 by using lightkdf

accounts/accounts.go
I believe the sentence is attempting to explain that the URL is "[used] by upper layers to define a sorting order over all wallets from multiple backends."
=> accounts: correct spelling mistakes

cmd/geth/config.go, cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go
Integrate the catalyst API namespace registration with the TTD definition. No need to explicitly require opening the namespace if we know we need it.
=> cmd: auto-enable beacon APIs if TTD is defined

cmd/devp2p/internal/ethtest/chain.go, cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/snap.go, cmd/devp2p/internal/ethtest/snapTypes.go, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/suite_test.go, cmd/devp2p/internal/ethtest/types.go, cmd/devp2p/rlpxcmd.go, eth/protocols/snap/handler.go
This is a WIP
This PR adds support in the `devp2p` binary to perform testing of the snap protocol. 
Later on, the idea is to use this functionality for Hive-testing. 
In case other client implementors want to try out the testcases, here are two scripts that can be used for running it.  
A script to set up the Node Under Test (customize this for your node): 
```
$ cat setup.sh 
geth=~/go/src/github.com/ethereum/go-ethereum/build/bin/geth
ddir=./foo
genesis=~/go/src/github.com/ethereum/go-ethereum/cmd/devp2p/internal/ethtest/testdata/genesis.json
chain=~/go/src/github.com/ethereum/go-ethereum/cmd/devp2p/internal/ethtest/testdata/halfchain.rlp
set -e
rm -rf $ddir
$geth --datadir $ddir --nodiscover --nat=none --networkid 19763 --verbosity 5 init $genesis
$geth --datadir $ddir --nodiscover …
```
=> cmd/devp2p: implement snap protocol testing

miner/worker.go
This PR fixes the #24299. It's an alternative fix of #24301
=> miner: avoid data race in miner

go.mod, go.sum
This upgrade resolves a build issue on Android 7+ and removes a build warning on macOS >= 12.0.
=> go.mod: upgrade to github.com/karalabe/usb v0.0.2

core/state/state_object.go, core/state/statedb.go
I noticed that our meters are still not quite 100%. 
I think the fault lies on the `s.SnapshotAccountReads` handling. The `SnapshotStorageReads/StorageReads` were seemingly correct, because they did this litlte dance with pointers, to ensure that the final defer-method would update the correct counter, which the `SnapshotAccountReads/AccountReads` was missing. 
When looking into it a bit, I found that it could be simplified. This _slightly_ changes the semantics of the timer -- the timer measurement in this PR covers only the pure lookup from snapshot/trie, not the time for rlp decoding and other paths -- the time for that will wind up on the `execution` timer. I don't think either approach is more correct than the other, but it does simplify the code to do it like this. The alternative …
=> core/state: fix read-meters + simplify code

p2p/server.go
`dialPubkey` isn't used anywhere else after `dialDest.Load`, so it should be safe to restrict its scope to the `if clause`.
=> p2p: reduce the scope of dialPubkey

internal/ethapi/api.go
Signed-off-by: 0x6f736f646f <blackd0t@protonmail.com>
Resolves #24368
=> internal/ethapi: fix incorrect type on empty slice

ethclient/ethclient.go, ethclient/ethclient_test.go
I found this method is required when trying to seamlessly and incrementally synchronize contract state to local database.
=> ethclient: add CallContractAtHash 

core/rawdb/table.go, ethdb/batch.go, ethdb/leveldb/leveldb.go, ethdb/memorydb/memorydb.go, tests/fuzzers/bn256/bn256_fuzz.go, tests/fuzzers/stacktrie/trie_fuzzer.go, trie/iterator_test.go, trie/trie_test.go
This PR adds an addtional API called `NewBatchWithSize` for db
batcher. It turns out that leveldb batch memory allocation is
super inefficient. The main reason is the allocation step of
leveldb Batch is too small when the batch size is large. It can
take a few second to build a leveldb batch with 100MB size.
Luckily, leveldb also offers another API called MakeBatch which can
pre-allocate the memory area. So if the approximate size of batch is
known in advance, this API can be used in this case.
It's needed in new state scheme PR which needs to commit a batch of
trie nodes in a single batch. Implement the feature in a seperate PR.
=> core, ethdb, tests, trie: implement NewBatchWithSize API for batcher

trie/iterator.go, trie/iterator_test.go, trie/trie.go
This functionality is needed in new path-based storage scheme, but
can be implemented in a seperate PR though.
When an account is deleted, then all the storage slots should be
nuked out from the disk as well. In hash-based storage scheme they
are still left in the disk but in new scheme, they will be iterated
and marked as deleted.
But why the NodeBlob API is needed in this scenario? Because when
the node is marked deleted, the previous value is also required to
be recorded to construct the reverse diff.
=> trie: implement NodeBlob API for trie iterator

build/ci.go
From our launchpad build-uploader: 
```
Rejected:
hirsute is obsolete and will not accept new uploads.
ethereum (1.10.16+build27677+hirsute) hirsute; urgency=low
* git build of 20356e57b119b4e70ce47665a71964434e15200d
```
=> build: disable hirsuite builds

graphql/graphql.go
=> graphql: fix nonce for pending accounts

rlp/encbuffer.go
```
w.WriteString undefined (type rlp.EncoderBuffer has no field or method WriteString)
```
=> rlp: add WriteString method

appveyor.yml
The legacy tests are now in a sub-module within the tests repository. Hence, the CI tools need to fetch the sub-modules recursively before running the checks. This PR changes `appveyor.yml` to that end.
Fixes [#24312](https://github.com/ethereum/go-ethereum/issues/24312)
=> Fetch sub-modules recursively

les/vflux/client/fillset_test.go
This PR fixes a goroutine leak in testIter (used by TestFillSet).
This is an alternative solution to https://github.com/ethereum/go-ethereum/pull/24379
Fixes https://github.com/ethereum/go-ethereum/issues/24213
=> les/vflux/client: fix goroutine leak in testIter

downloads.html
For #20855. Reduces the size of batches to fetch, and increases the timeout.
I'm not sure if setting the timeout in jQuery will work, because it might be timing out on the server end. But it's worth a try.
The new batch size of 250 is pretty low, but I figure it's better to ensure the page works for everyone, than to worry about optimising it for people who have healthy networks.
That change is also on line 250, so it might be ... fate? :smile:
=> Tweak downloads page to work better on slow networks

README.md
Added hardware requirements mentioned in website/docs: Write missing doc pages #20260- https://github.com/ethereum/go-ethereum/issues/20260
=> README.md: add hardware requirements

docs/_rpc/pubsub.md
Running this command results in the response:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"too many arguments, want at most 1"}}
```
Also there are other newHeads subscription examples in this page, which don't have the {} param.
=> newHeads subscription doesn't take a second param

accounts/abi/selector_parser.go, accounts/abi/selector_parser_test.go, signer/fourbyte/abi.go
The selector parsing logic in fourbytes has been improved to work with tuples.
This requires changing the current regexp-based approach to a small hand-written parser.
Among potentially other things, this allows to call functions that have tuples in their signatures from `clef`, which would previously fail with the following error: `ValueError: validation failed: Transaction contains data, but the ABI signature could not be found: signature 40b1eb10 not found`
=> signer/fourbyte: add support for nested types in selectors

cmd/clef/main.go, cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, eth/catalyst/api.go, go.mod, go.sum, graphql/service.go, les/catalyst/api.go, node/api.go, node/config.go, node/defaults.go, node/endpoints.go, node/jwt_handler.go, node/node.go, node/node_test.go, node/rpcstack.go, node/rpcstack_test.go, rpc/server.go, rpc/types.go, rpc/websocket_test.go
This PR implements support for JWT. An `rpc.API` can now be `Authenticated`, meaning that it will only be exposed over an authenticated API point, meaning: 
- ipc, 
- or http endpoint with jwt support, 
- or ws endpoint with jwt support. 
The `jwt-secret` can be given via CLI param, loaded like the `nodeKey` (i.e: loaded or generated+stored). 
While the node is setting up the RPC endpoints, if it detects that there are `Authenticated` services, a new servre will be created. For now, using the port `8551` for both `http` and `ws`.
I _think_ this PR does not break existing functionality in `master`, but will cause breakage in `--catalyst` mode. The idea is to be able to merge this into master, and then make the TheMerge branches make use of it.
This PR does not implement client-side suport, …
=> cmd/geth, node, rpc: implement jwt tokens

cmd/geth/snapshot.go, core/rawdb/accessors_state.go, core/state/pruner/pruner.go
This PR does following:
1- Adds `HasCode` and replace it with `ReadCode` wherever possible.
2- Changes `ReadTrieNode` functions with `HasTrieNode`, in main and pruner packages. 
The reference commit:
https://github.com/ethereum/go-ethereum/commit/893502e561a03dd8d080a6b373d1174a322df00f
=> core/rawdb: add HasCode, HashTrieNode and use them where possible

mobile/geth.go
The function removed in this PR was first deprecated around a year and a half ago, in #21105.
This PR removes support for the deprecated Stop() function.
=> mobile: remove deprecated Stop function

cmd/evm/testdata/15/exp3.json, core/types/receipt.go, core/types/receipt_test.go, core/types/transaction.go, core/types/transaction_test.go
Because the switch statement checks for EIP-2718 (String and Bytes) *and* legacy (List) transactions, the default should throw an error expecting the newer String and Bytes rather than the List. Changed `return rlp.ErrExpectedList` to `return rlp.ErrExpectedString` in the default cases.
closes #24227
=> core/types: change default for DecodeRLP in transaction and recipt

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, node/config.go, node/defaults.go, node/node.go
The default listening address "localhost" is not sufficient when running geth in Docker.
I discovered this while trying to run the Hive engine API tests: https://github.com/ethereum/hive/pull/507#issuecomment-1062809913
=> cmd/geth: make authrpc listening address settable from command line

core/rawdb/table.go, ethdb/database.go, ethdb/dbtest/testsuite.go, ethdb/leveldb/leveldb.go, ethdb/memorydb/memorydb.go, ethdb/snapshot.go, tests/fuzzers/stacktrie/trie_fuzzer.go, trie/iterator_test.go, trie/trie_test.go
This PR introduce a new API for ethdb, the database snapshot.
It can happen that we want to get the specified version of the data from the database, 
to be more specific, retrieve the data from the specified disk snapshot. 
Right now this feature is unneeded since basically all data in disk have a unique identifier.
However, when we switch to path-based state scheme, this feature is required, for example:
- we want to trace block at height N, the disk state is at N + 100
- we need to rewind the disk state to height N-1 by applying the reverse diffs
- In the same time, the disk state is mutated by chain by pushing the new version state
- the trace state has these requirements: 
- state reverts should not affect the live state
- the live state changes should not affect the trace state
In …
=> core, ethdb, tests, trie: introduce database snapshot

core/blockchain.go, core/rawdb/accessors_chain.go, core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/freezer_batch.go, core/rawdb/freezer_meta.go, core/rawdb/freezer_meta_test.go, core/rawdb/freezer_table.go, core/rawdb/freezer_table_test.go, core/rawdb/freezer_test.go, core/rawdb/freezer_utils.go, core/rawdb/freezer_utils_test.go, core/rawdb/table.go, ethdb/database.go
This PR introduces the tail deletion of freezer.
The tail deletion is at file level by design. It means whenever data items at tail are deleted, they will not be **removed** from the file immediately. Instead they will be **hidden** until items in the tail data file are all deleted then the entire data file will be dropped.
**Performance**
The reason for designing this *lazy deletion* mechanism is mainly for saving cost of updating index file. The lookup in freezer is using item id to calculate the relative position in index file, read the data position info from the index file and finally read the data from data file. 
However in order to delete the tail items from the data file, all the remaining items in this data file must be shifted forward and all of them need to be re-indexed by …
=> core/rawdb, cmd, ethdb, eth: implement freezer tail deletion

eth/gasprice/feehistory.go, graphql/graphql.go, graphql/schema.go
This PR adds the `NextBaseFeePerGas` to `Block` and `EffectiveTip` to `Transaction` to make it easier for clients to compute fee history themselves. Note I made the tx reward sorting logic in our fee history algorithm stable so clients can compute consistent results.
Example client script: https://gist.github.com/s1na/851ad57e8fca7c74b2464207b2e99021
Result of a run on a few Goerli blocks:
```sh
❯ node index.js 4 6415924 "50, 75"
{
oldestBlock: '0x61e631',
reward: [
[ '0x9502f900', '0x165a0bbf9' ],
[ '0x59682f00', '0x59682f00' ],
[ '0x3b9aca00', '0x9502f900' ],
[ '0x9502f900', '0x9502f900' ]
],
baseFeePerGas: [ '0x7', '0x7', '0x7', '0x7', '0x7' ],
gasUsedRatio: [
0.10796890077097406,
0.0061631333333333335,
0.008546466666666667,
0.13900370378341118
]
}
{
oldestBlock: '0x61e631', …
```
=> graphql: fee history fields

core/rawdb/accessors_snapshot.go, core/rawdb/key_length_iterator.go, core/rawdb/key_length_iterator_test.go, core/state/snapshot/snapshot.go
This PR adds a db iterator wrapper that only returns key-value pairs with a specified key length.
=> Add specified key length iterator

trie/iterator.go, trie/iterator_test.go
This PR fixes two issues in iterator:
- Fix the memory leak in iterator. 
In trie iterator each resolved trie node will be wrapped with a struct and the corresponding pointer will be saved in the stack based slice. Whenever the node is visited, the struct is poped from stack. However this struct point should be explicitly set to nil in order to garbage collect the underlying struct.
- Fix the empty trie iterator
The empty trie shouldn't be iterated out any values.
=> trie: fixes two issues in trie iterator

eth/tracers/api.go
`debug_traceBlock` wasn't usable over RPC because the RLP block JSON input isn't being Unmarshalled.
See the bug using the geth console: 
```
> var rlp = debug.getBlockRlp(<ANY BLOCK NUMBER>)
> debug.traceBlock(rlp)
Error: could not decode block: rlp: expected input list for types.Header, decoding into (types.Block)(types.extblock).Header
at web3.js:6365:37(47)
at send (web3.js:5099:62(35))
at <eval>:1:17(4)
```
With the fix, the above commands work.
=> eth/tracers: use hex encoding for debug_traceBlock argument

internal/flags/helpers.go
context #24145
maybe we should also add it for other commands - so far I only enabled it for `geth`
=> cmd/geth: set EnableBashCompletion = true

eth/downloader/skeleton_test.go
I miscalculated which header is the one being retrieved that needs to be delayed to trigger the data race. It caused no delay thus 50% success 50% fail for the test.
=> eth/downloader: fix off-by-one error in test causing 50% fails

docs/_install-and-build/Backup--restore.md
After looking into the newest geth version and installed geth on my windows os, i found the location of data directory is on :
%LOCALAPPDATA%\Ethereum
not
%APPDATA%\Ethereum
=> docs: fix data directory location

eth/downloader/beaconsync.go, eth/downloader/downloader.go, eth/downloader/skeleton.go
Up until now the beacon sync ran until we downloaded all the header up to genesis and we started using that as the driver for the backfiller. Whilst this is simple and elegant, it does pose a problem during mainnet transition: a peer will stall on the first sethead until it redownloads all the headers it already has locally.
This PR adds a database check for every beacon header acceptance to check if the associated (parent) block body and receipt is present already in the local chain or not. If both are present (the header is surely present in that case), we can stop downloading headers and just call it a day.
Some additional checks needed to be added to ensure that we ignore the part of the beacon headers that have not been downloaded.
=> eth/downloader: terminate beacon sync early when linked to local chain

core/rawdb/freezer_table.go
This PR adds a hack to freezer, the newly introduced meta data file will always be opened in the read/write mode.
The reason for adding this hack is: the meta data files are missing for legacy nodes which means most of the db commands will fail when the db is opened in the read-only mode. 
Since tail deletion is not used right now, the only mutation can be made is initialization which is acceptable instead of breaking existent commands.
=> core/rawdb: fix db commands

core/blockchain.go, core/genesis.go, core/genesis_test.go, core/rawdb/accessors_metadata.go, core/rawdb/database.go, core/rawdb/schema.go
This PR is an alternative of #24450.
It will store the genesis allocation information into the disk, 
and whenever we want to rewind the state to genesis, the
genesis allocation can be loaded and generate the genesis
states.
=> core: store genesis allocation and recommit them if necessary

core/blockchain.go, eth/downloader/downloader.go, light/lightchain.go
This PR fixes a panic by importing zero size header batch. It can happen when the imported headers are crossing the ttd border and all the synced headers are post-merge.
=> eth/downloader: ignore zero size header batch for importing

cmd/geth/config.go, cmd/geth/dbcmd.go, core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/freezer_test.go, core/rawdb/table.go, core/types/legacy.go, ethdb/database.go
This is a slower but simpler version of https://github.com/ethereum/go-ethereum/pull/23454. I still plan to add in batch reading.
=> core/rawdb: simple legacy receipt converter

eth/downloader/skeleton_test.go
The `TestSkeletonSyncRetrievals` keeps failing on appveyor, because there's an assumption that `250ms` will be sufficient. This PR replaces that built-in timeout with a retrying mechanism, which starts at `20ms` and backs off, waiting at most around a second for the expected result to appear.
=> eth/downloader: fix flakey test

cmd/utils/flags.go, node/node.go
Removes the ability to pass a JWT secret in plaintext via CLI
This should help users not reveal their secret e.g. in bug reports
=> node: allow JWT pass by file only

internal/build/util.go
The travis sftp upload to ppa dies after 10m of inactivity. Hard to say what happens (we do get a notification about a successful upload from ppa), but directing the process stdout to stdout seems like thing that might tell us more.
=> internal/build: show ppa upload process stdout on stdout

internal/build/util.go
Trying to solve travis timeout issues. They recommend https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received : 
```
If you have a command that doesn’t produce output for more than 10 minutes, you can prefix it with travis_wait, a function that’s exported by our build environment. For example:
>    install: travis_wait mvn install
spawns a process running mvn install. travis_wait then writes a short line to the build log every minute for 20 minutes, extending the amount of time your command has to finish.
If you expect the command to take more than 20 minutes, prefix the command with travis_wait n where n is the number of minutes by which the waiting time is extended.
```
Seems a bit overkill ot install another dependency just to spit out …
=> internal/build: prevent travis timeout during ppa upload

internal/build/util.go
Now travis doesn't tear down the connection any longer, however, https://app.travis-ci.com/github/ethereum/go-ethereum/jobs/564712253 , neither do we. It appears the sftp upload kind of depended on travis eventually killing it. So this PR adds an `exit ` after all the sftp `put`s are done.
=> internal/build: exit sftp upload

internal/build/util.go
Some issue with the ppa sftp server makes it not close the connection when the client tries to terminate. 
```
[user@work sftp]$ sftp -i ./ppakey geth-ci@ppa.launchpad.net
Connected to ppa.launchpad.net.
sftp> ls
sftp> exit
Interrupt  
Interrupt  
Interrupt  
```
More details
```
sftp> quit
debug2: channel 0: read<=0 rfd 4 len 0
debug2: channel 0: read failed
debug2: chan_shutdown_read: channel 0: (i0 o0 sock -1 wfd 4 efd 6 [write])
debug2: channel 0: input open -> drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug3: send packet: type 96
debug2: channel 0: input drain -> closed
Interrupt  
```
Also seen here: https://github.com/kolban-google/sftp-gcs/issues/23#issue-1095191812 
Pending fix here: https://github.com/mscdex/ssh2/pull/1111 
This PR fixes it, so that when we …
=> build: close sftp connection when done

cmd/geth/config.go
=> cmd/geth: change to non-fatal error message when legacy receipt storage is not implemented

cmd/geth/dbcmd.go, eth/catalyst/api.go
Check if the state for the parent block is available, otherwise we might incur bad block errors
=> eth/catalyst: only apply block if we actually have the state

rlp/doc.go
=> rlp: fix spelling mistake in rlp doc

core/state/snapshot/generate.go
This PR cleans up the snapshot generation logic a bit by moving out the nested functions.
The main intention is to improve the code read-ability, the main logic shouldn't be changed.
=> core/state/snapshot: cleanup generation logic

internal/ethapi/api.go
Refund is helpful for tracing. So will it make sense to add it into `StructLogRes`?
(Background info: we are implementing zkevm, proving every opcode step using zk-proof, so very detailed information needed for every step, for example, refund is needed to sstore op. If refund is included in StructLogRes, we don't need to recalculate it outside)
=> internal/ethapi: add refund to StructLogRes

eth/tracers/logger/gen_structlog.go, eth/tracers/logger/logger.go, eth/tracers/logger/logger_test.go
This PR replaces #24491. I pushed some fixes on top, but do not have permissions to push to the submitter's repo. Also rebased on master. 
Closes #24487
=> eth/tracers/logger: use omitempty to reduce log bloat 

common/compiler/solidity.go
When trying to compile solidity files that import locally installed `openzeppelin-solidity`, it's very convenient to allow adding extra include path.
This PR adds a `ExtraAllowedPath` field to `Solidity` and exposes two APIs: `CompileSource` and `CompileFiles`, which were hidden inside `CompileSolidityString` and `CompileSolidity` before.
=> common/compiler: refactor compiler.Solidity

eth/handler.go
Hello!
I run a few geth nodes, and monitor the log output to check on their health (via an ELK stack).
The only `ERROR` level line I regularly get from `geth` looks like the one below:
```
Feb 27 12:39:19 xyz geth[324494]: ERROR[02-27|12:39:19.016] Snapshot extension registration failed   peer=664adfac err="peer connected on snap without compatible eth support"
```
I get over 100 of these `ERROR` messages an hour. They come from peer connections, and as it states, "Snapshot extension registration" has failed.  geth continues without any side-effects.
However, there's no action I can take here -- these are external clients, out of my control.  I'd really prefer `ERROR` level messages be kept to things I should address.  Then I can monitor the rate of `ERROR`s and alert.
As a result, I …
=> eth: change snapshot extension registration failure to warning instead of error

core/types/hashing_test.go, les/server_handler.go, tests/fuzzers/rangeproof/rangeproof-fuzzer.go, trie/committer.go, trie/iterator_test.go, trie/proof.go, trie/proof_test.go, trie/secure_trie.go, trie/secure_trie_test.go, trie/trie.go, trie/trie_test.go, trie/util_test.go, trie/utils.go
Trie tracer is an auxiliary tool to capture all deleted nodes
which can't be captured by trie.Committer. The deleted nodes
can be removed from the disk later.
TODO
=> trie, les, tests, core: implement trie tracer

eth/downloader/beaconsync.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go
This PR fixes a panic in beacon sync.
**Panic logs**
```
WARN [03-29|23:55:59.938] Local chain is post-merge, waiting for beacon client sync switch-over...
WARN [03-29|23:56:11.942] Ignoring payload with missing parent     number=55128   hash=be29d4..273c2e parent=0d8429..6eba9e
WARN [03-29|23:56:12.044] Ignoring payload with missing parent     number=55129   hash=e6b72a..fe7dc8 parent=be29d4..273c2e
INFO [03-29|23:56:12.176] Left PoW stage
INFO [03-29|23:56:12.176] Forkchoice requested sync to new head    number=55129   hash=e6b72a..fe7dc8
INFO [03-29|23:56:12.322] Looking for peers                        peercount=2 tried=79  static=0
INFO [03-29|23:56:12.366] Forkchoice requested sync to new head    number=55129   hash=e6b72a..fe7dc8
WARN [03-29|23:56:12.366] Beacon chain reorged …
```
=> eth/downloader: retrieve pivot header from local chain if necessary

README.md
A 500GB drive is no longer sufficient to sync mainnet with default settings. ~~A _freshly_ synced node will consume about 490GB, but then rapidly balloon beyond 500GB due to no online pruning. It's not reasonable to expect users to turn off (or severely degrade) their node every few weeks to prune, especially with The Merge on the horizon where an offline node means no staking.~~ A _freshly_ synced node will consume about 600GB (updating the PR description as my node actually syncs, until this is merged or I get lazy).
=> Update free space required

eth/fetcher/block_fetcher.go
Fixes https://github.com/ethereum/go-ethereum/issues/24623#issuecomment-1089125358, though it shouldn't impact the original issue of having sync problems.
=> eth/fetcher: if peers never respond, drop them

core/state/snapshot/difflayer.go
This line is not necessary, it reassigned an entry to a map, but that entry originated from the same map. I think this "noop" line originated from a previous code where the entry was a slice. However, if the entry being retrieved and reassigned is a map, that is a pointer internally in Go, so modifying it does not change the outer structure, thus no need for the reassignment.
=> core/state/snapshot: remove noop map item assignment

cmd/geth/snapshot.go
While investigating a failure during post-merge goerli shadowfork, I found that there was 'dangling' snap storage data. 
Our `verify-state` iterates the snapshot data by iterating the snapshot accounts, and regenerating the trie. This method was unable to discover the flaw, since the account did not exist (only the storage data did), thus reported that the verification passed. 
This PR adds an additional checker. It iterates the `o<32byte account key><32 byte storage key>` items in the db, and verifies that for each storage, there is a corresponding account. 
Example of running it 
```
$ geth --datadir ./eth1data/geth snapshot check-dangling-storage
INFO [04-05|09:28:55.764] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-05|09:28:55.765] Smartcard socket not …
```
=> cmd/geth: inspect snapshot dangling storage

accounts/abi/selector_parser.go, accounts/abi/selector_parser_test.go
Since https://github.com/ethereum/go-ethereum/pull/24407 the abi parser support nested types but was laking support for array of nested types (https://github.com/ethereum/go-ethereum/issues/24571)
=> accounts/abi: handle tuple arrays in ParseSelector

les/fetcher.go, les/fetcher_test.go, les/ulc_test.go
The panic can happen in ultra light client mode when original local chain has no common ancestor with newly synced chain. It's because the newly synced chain can be located after the checkpoint while the original local headers are before the checkpoint.
This fix recaps the common ancestor to genesis in case it's not found.
Fixes #24611
=> les: fix panic in ultra light client sync

log/handler.go
This PR modifies the order of `Lock()` `defer Unlock()` to follow the more typically used pattern.
=> log: modify lock defer unlock order in sync handler

build/deb/ethereum/deb.control
GitHub recently updated Git protocol security, and the usage of the unencrypted git protocol has been retired permanently on March 15th. But, the Debian control file `deb.control` still used git protocol for Vcs-Git.  Hence, may lead to bunch of unauthenticated git protocol errors.
Use https protocol in place of unencrypted git protocol
`git://github.com/ethereum/go-ethereum.git` should be changed to
`https://github.com/ethereum/go-ethereum.git`
https://github.blog/2021-09-01-improving-git-protocol-security-github/
Fixes #24675
=> Update Debian control file to remove unencrypted git protocol

core/bench_test.go
This PR fixes a few panics in the chain marker benchmarks. The root
cause for panic is in chain marker the genesis header/block is not
accessible, while it's expected to be obtained in tests. So this PR
avoids touching genesis header at all to avoid panic.
Fixes #24654
=> core: fix benchmark panic

eth/tracers/native/4byte.go, eth/tracers/native/call.go, eth/tracers/native/noop.go, eth/tracers/native/prestate.go, eth/tracers/native/tracer.go
=> eth/tracers: make txhash blockhash accessible to native tracers

eth/downloader/beaconsync.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go
This PR fixes a panic found by @marioevz.
The scenario is: 
- Geth starts beacon sync with remote head as 7 and local head as 5
- At the same time, Geth inserts a new block 6 via `NewPayload` API. The corresponding `ForkchoiceUpdate` event is not received yet, so it's still non-canonical.
- Beacon skeleton links with local chain at header 6, because the body and receipts of block 6 is present in disk 
- Geth then spins up the downloader for sync, the origin is recapped to 0 because in snap sync, the safety distance is 64 while our remote head is only 7
- Geth tries to deliver the header in range [1, 7] in `fetchBeaconHeaders`, for headers [1, 6] they are not present in skeleton space, so try to resolve them locally
- Header 6 is non-canonical, previously we only search the canonical …
=> eth/downloader: resolve local header by hash for beacon sync

go.mod, go.sum
See #24554 and https://github.com/btcsuite/btcd/issues/1839
=> go.mod: upgrade btcec and add 'chainhash' module requirement

trie/committer.go
Minor PR to remove `makeHashNode` which seems unused and simplify the `committer` struct.
=> trie: remove unused makeHashNode

core/vm/interpreter.go
Was just browsing the code and found this.
=> core/vm: fix typo

eth/downloader/downloader.go
synchornization -> synchronization
=> eth/downloader: fix typo in downloader.go

eth/tracers/logger/access_list_tracer.go
This change removes extraneous/unnecessary checks for equality
when comparing 2 accessList values A and B. Given that we validate that
their lengths of A and B are equal, if so and if every element in A is
in B, reflexively every element in B is already in A. If that weren't
the case and an element g existed in A but not in B, that would mean
that there is an extra element and hence a Mathematical contradiction.
While here, added benchmarks to exhibit the performance gains as below:
```shell
name                    old time/op    new time/op    delta
AccessListEqual10-8       14.8µs ± 5%     7.2µs ± 5%  -51.16%  (p=0.000 n=19+20)
AccessListEqual100-8       151µs ± 5%      74µs ± 5%  -50.89%  (p=0.000 n=19+19)
AccessListEqual1000-8     1.50ms ± 3%    0.74ms ± 2%  -50.67%  (p=0.000 n=19+17) …
```
=> eth/tracers/logger: remove unnecessary comparisons in accessList.equal

README.md
I was not able to build the project locally with Go v1.15 because Azure SDK was throwing errors:
```bash
$ make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
package command-line-arguments
imports github.com/ethereum/go-ethereum/internal/build
imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
imports github.com/Azure/azure-sdk-for-go/sdk/azcore: build constraints exclude all Go files in ~/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.21.1
package command-line-arguments
imports github.com/ethereum/go-ethereum/internal/build
imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
imports github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime
imports github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared: build constraints exclude all Go …
```
=> README.md: update Go min required version to 1.16

docs/_rpc/server.md
The rpc docs list "eth" and "shh" as the default namespaces, whereas the actual default namespaces are "eth", "web3" and "net".  Also want to explicitly mention the http.api flag will overwrite the default namespaces.
https://github.com/ethereum/go-ethereum/blob/ca298a28210622ddb18f2ec12b3ab7bf0f8d733c/cmd/geth/config.go#L114
https://github.com/ethereum/go-ethereum/blob/ca298a28210622ddb18f2ec12b3ab7bf0f8d733c/node/defaults.go#L56
=> Docs update- rpc server

mobile/types.go
Currently, there's an issue with `Receipt` to JSON conversion: method returns binary data instead of JSON string.
This change fixes described behavior.
=> eth/mobile: fix receipt encoding to json

p2p/peer_error.go
`DiscSubprotocolError` was incorrectly typed as `int`; this change correctly types it as `DiscReason`.
=> p2p: type DiscSubprotocolError as DiscReason

cmd/geth/snapshot.go, core/state/snapshot/journal.go
This PR fixes the flaw that @rjl493456442 found in https://github.com/ethereum/go-ethereum/pull/#issuecomment-1093817551 , namely, that the snapshot iterator uses the combined (disk + difflayers) 'view', wheres the raw iterator uses only the disk 'view'. 
This PR instead splits up the work: one phase is iterating the disk layer data, another phase is loading the journalled difflayers and performing the same check there. 
Regarding the second check, I'm not totally sure I've done it right; maybe it should take into account `nilness` of the account, and also perhaps the destructset. Right now, it naively assumes that if storage data exists, then some sort of entry (nil or not)  should also exist, and ignores the destructset fully.
=> cmd/geth, core/state/snapshot: fix flaw from #24643 + inspect difflayers

core/types/transaction_test.go
Fix unhandled errors in `TestTransactionCoding`. The comparison results of `assertEqual` are not used and we can compare two transactions by their hashes directly.
=> core/types: fix unhandled errors in TestTransactionCoding

cmd/utils/flags.go, consensus/misc/eip1559.go
This PR will, sooner or later, close #24601
Running with this PR, instead of 'invalid difficulty', I get
```
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, Berlin: 0, London: 0, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: 0, Engine: ethash}
Number: 1
Hash: 0x8ce374ca14f5c8f25f1a5731cf10e44f8f05ab6968a764fa9d13752e04796c94
Error: invalid baseFee: have 1000, want 1142, parentBaseFee 1142, parentGasUsed 0
##############################
```
=> cmd/utils: utilize beacon wrapper in makechain

ethclient/gethclient/gethclient.go, ethclient/gethclient/gethclient_test.go
Storage proofs were being unsmarshalled from the RPC form to the
go struct, but were not being included in the final returned struct.
This also adds a regression test for this case.
Note: I have not found or opened an issue for this.
=> ethclient: Return storage proofs in GetProof

cmd/devp2p/internal/ethtest/snap.go, cmd/geth/chaincmd.go, cmd/geth/config.go, cmd/geth/consolecmd.go, cmd/geth/dbcmd.go, cmd/geth/main.go, cmd/geth/snapshot.go, cmd/geth/usage.go, cmd/utils/flags.go
This PR groups all built-in network flags together and list them in the command as a whole.
It's so annoying that in some database relevant commands network flags are necessary for
resolving data directory, they are listed everywhere.
And all database path flags(datadir, ancient) are also grouped, since usually these two are
used together.
=> cmd: group network and db path flags together

Dockerfile, Dockerfile.alltools
Docker image build will use cached layers, since`go.mod` and `go.sum` won't changed very often, so we can add `RUN go mod download` early in `Dockerfile`.
https://cloud.google.com/architecture/best-practices-for-building-containers#optimize-for-the-docker-build-cache
=> dockerfile: better reuse of cached docker layers

cmd/geth/consolecmd_test.go, cmd/utils/cmd.go
Our monitor for free disk space works pretty well, but the limits are a bit too low -- particularly if we only check once per minute, as geth can eat up space pretty quickly. 
Example from a goerli sync: 
```
WARN [04-28|03:03:52.002] Disk space is running low. Geth will shutdown if disk space runs below critical level. available=439.25MiB critical_level=256.00MiB
...
INFO [04-28|03:04:40.226] Imported new chain segment               blocks=1       txs=8          mgas=0.976   elapsed=13.695ms    mgasps=71.296  number=6,791,790 hash=b67fb8..fd998f dirty=32.31MiB
INFO [04-28|03:04:45.911] Generating state snapshot                root=3f18e4..9a32e2 in=41c151..6351f9 at=6dc5b3..21e749 accounts=2,592,389            slots=27,928,843           storage=2.20GiB    elapsed=29m56.158s …
```
=> cmd/utils: double limit on free-disk monitor

graphql/graphql.go, graphql/schema.go
Alternative to https://github.com/ethereum/go-ethereum/pull/24726, also see https://github.com/ethereum/go-ethereum/issues/24720
=> graphql: add tx rawReceipt field

build/ci.go
This might enable builds for Jammy. 
Context info about ubuntu releases: https://wiki.ubuntu.com/Releases
=> build: ppa build for jammy (ubuntu 22.04)

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, eth/handler.go
Fixes https://github.com/ethereum/go-ethereum/issues/24797.
The issue is https://github.com/ethereum/go-ethereum/commit/dbfd3972624c1d82db21f5dfceab8fde7a1eee0a#diff-186ee0cda89676d60ba8ad8144c34a499010076a7720fa3d30259ac04b1a083eL427, where the `hash` was dropped from the iteration, causing the internals to fall back to some outer scope variable.
The PR also cleans up the offending original PR, it was all over the place.
=> cmd, eth: fix required blocks regression

core/blockchain.go
`WriteBlockAndSetHead` documentation comment labels it as `WriteBlockWithState` and does not describe its full functionality.
=> core: fix WriteBlockAndSetHead documentation

core/blockchain.go, core/blockchain_test.go, core/headerchain.go, eth/catalyst/api.go, les/catalyst/api.go, les/catalyst/api_test.go, light/lightchain.go
This PR improves the `SetChainHead`, with the additional guarantee that after head reset the head state is always available.
=> core: recover the state in SetChainHead if the head state is missing

eth/filters/filter.go
In filter.go:
https://github.com/ethereum/go-ethereum/blob/f94e23ca66eef8fdac2473ce99ca6ad57324aaa2/eth/filters/filter.go#L300-L305
If `len(topics)` greater than len(log.Topics), `continue Logs` will make `filterLogs()` got an infinite loop.
So, It should be `continue`, not `continue Logs`.
=> eth/filters: remove explicit continue label in filterLogs

p2p/simulations/network_test.go
=> p2p/simulations: fix typo in network_test.go

eth/catalyst/api.go, eth/catalyst/api_test.go, miner/worker.go
Head-interrupted blocks should not be `commit`-ed, since that introduces unnecessary delay, and possibly causes miner to mine on the previous head.
This could result in higher uncle rate (which seems to be up by some 0.5% since 3rd of March).
I kept the boolean semantics consitent with `commitTransactions`, but I'd be happy to refactor.
Intuitively, `w.current` should also not be set, since it could actually be a worse block than what was built previously (and we don't want to apply uncles on that block anyway).
This should never happen in `generateWork` (no interrupt passed in), but I added an error for completeness, since this could change.
=> miner: discard interrupted blocks

eth/fetcher/tx_fetcher_test.go, eth/filters/filter_system_test.go
Issue #23331 contains some very interesting cases of hard-to-find subtle bugs. This PR contains (so far) partial fixes for them. I'm not sure how to best verify the fixes though. 
This PR fixes (?) the following ones:
https://github.com/ethereum/go-ethereum/blob/56e9001a1a8ddecc478943170b00207ef46109b9/eth/downloader/downloader_test.go#L1517
=> eth/fetcher: fix test to avoid hanging. Partial fix for #23331

accounts/abi/argument.go, accounts/abi/unpack_test.go
This PR fixes abi checks in the edge case where all arguments are indexed
=> abi: fix checks when all fields are indexed

core/state/snapshot/difflayer.go, eth/protocols/snap/sync.go
This PR fixes two race conditions:
- a data race between `difflayer.Cap()` and `difflayer.Parent()` where `Parent` reads the parent field without requiring a read lock
- a data race between `(*Syncer).loadSyncStatus()` and `(*Syncer).OnByteCodes` where the `loadSyncStatus` writes the `snapped` field without a lock.
```
Write at 0x00c028443728 by goroutine 1404:
github.com/ethereum/go-ethereum/core/state/snapshot.(*Tree).cap()
github.com/ethereum/go-ethereum/core/state/snapshot/snapshot.go:484 +0x2b7
github.com/ethereum/go-ethereum/core/state/snapshot.(*Tree).Cap()
github.com/ethereum/go-ethereum/core/state/snapshot/snapshot.go:401 +0x1ca
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit() …
```
=> core/state/snapshot: fix race condition

internal/ethapi/api.go, internal/web3ext/web3ext.go
This method was added as part of https://github.com/ethereum/go-ethereum/pull/19003 temporarily to aid with testing. It doesn't seem to be needed [anymore](https://github.com/ethereum/go-ethereum/issues/24808#issuecomment-1119684407)
=> internal: drop TestSignCliqueBlock

eth/protocols/snap/sort_test.go, eth/protocols/snap/sync.go, trie/sync.go
It was pointed out @dceleda that we do not merge storage trie heal requests which are on the same path. The spec allows for doing so, which saves some bandwidth, but it was left as a todo. 
This PR attempts to fix it. Testing it now, will remove some extraneous printouts when I've checked whether it works.
=> eth/protocols/snap: sort trienode heal requests by path

cmd/geth/main.go
fixes #18243
> You are running Geth in --dev mode. Please note the following:
>      1.  This mode is only intended for fast, iterative development
without assumptions on security or persistence.
>     2.  The database is created in memory unless specified otherwise. Therefore, shutting down your computer or losing power will wipe your entire block data and chain state for your dev environment.
>     3.  A random, pre-allocated developer account will be available and
unlocked as eth.coinbase, which can be used for testing. The
random dev account is temporary, stored on a ramdisk, and will
be lost if your machine is restarted.
>      4.  Mining is enabled by default. However, the client will only seal blocks if transactions are pending in the mempool. The miner's minimum accepted gas price …
=> cmd/geth: add banner for devmode on console

graphql/graphql.go
=> graphql: fix long literal passed in a variable

internal/ethapi/api.go, internal/web3ext/web3ext.go
@holiman this is a follow-on to https://github.com/ethereum/go-ethereum/pull/24741 (but stand-alone) that implements the two debug methods I mentioned here https://github.com/ethereum/go-ethereum/issues/24720#issuecomment-1106868099
I ended up going with an array of receipts rather than the original map idea, since in practice the map felt a little clunky.
```
> r = debug.getRawReceipts("0x59d58395078eb687813eeade09f4ccd3a40084e607c3b0e0b987794c12be48cc")
["0x02f901850182aebbb9010000800000000000000000000000000000000000000000100000020000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000001000000000000000000 …
```
=> internal/ethapi: add debug_getRawReceipts RPC method

cmd/utils/flags.go
TL;DR:
```
$ geth --rinkeby --syncmode=light console]
INFO [05-16|08:28:09.050] Starting Geth on Rinkeby testnet... 
INFO [05-16|08:28:09.050] Dropping default light client cache      provided=1024 updated=128
INFO [05-16|08:28:09.052] Maximum peer count                       ETH=0 LES=10 total=50
INFO [05-16|08:28:09.053] Set global gas cap                       cap=50,000,000
WARN [05-16|08:28:09.053]  
WARN [05-16|08:28:09.053] -------------------------------------------------------------------------------- 
WARN [05-16|08:28:09.053] Please note, Rinkeby has been deprecated. It will still work for the time being, 
WARN [05-16|08:28:09.053] but there will be no further hard-forks shipped for it. Eventually the network 
WARN [05-16|08:28:09.053] will be permanently halted after the other …
```
=> cmd/utils: add deprecation warning for Rinkeby

core/asm/asm.go, core/asm/compiler.go, core/asm/lexer.go
1. fix docstring comment
2. optimize string concat
=> core/asm: use strings.Builder and fix godoc issues

core/vm/instructions_test.go
The op benchmark result will be like:
master 
```
BenchmarkOpAdd64-8   	33818551	        35.51 ns/op	      24 B/op	       1 allocs/op
```
this PR
```
BenchmarkOpAdd64-8   	85392249	        13.81 ns/op	       0 B/op	       0 allocs/op
```
=> core/vm: reduce overhead in instructions-benchmark

eth/catalyst/api_test.go, eth/protocols/snap/handler.go, eth/protocols/snap/sync_test.go
This PR fixes a few flaky tests in `eth/protocol/snap` and `eth/catalyst` packages.
=> eth: fix flaky test

graphql/graphql.go, graphql/schema.go
Adds:
- Transaction.raw
- Block.rawHeader
- Block.raw
=> graphql: add raw fields to block and tx

core/beacon/errors.go, core/blockchain.go, eth/catalyst/api.go, eth/catalyst/api_test.go
According to the spec, we should always return the `headblockhash` passed by the CL, even if our chain is different and we just ignore the fcu (because it tries to update us to an old block).
=> eth/catalyst: set the correct LatestValidHash

cmd/geth/dbcmd.go
This PR adds `db` tooling to verify the integrity of trie nodes. It iterates through the 32-byte key space in the database, which is expected to contain RLP-encoded trie nodes, addressed by hash. 
It checks that the `hash(content)` corresponds to the key. 
Example when running this on a corrupt kiln-node database: 
```
INFO [05-10|08:43:32.845] Opened ancient database                  database=/home/user/tmp/kiln-investigation/geth/chaindata/ancient readonly=true
Error at 0x143ec96ddd6e1d624a5f3ad2cb8bc641f6adbda0817d8172c365a62fa0edfcd2
Hash:  0x3004210bd6bc108fc06e951595ecd4599ec2391ed5ea4523b268535cfb1ee310
Data:  0xf8719f2099a79d8d238177a65a424e9d5fb92c28e3021a49ea28e2cd766d0750f330b84ff84d808906f4cc3821aa200000a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460 …
```
=> cmd/geth: tooling to verify integrity of trie nodes

console/prompt/prompter.go, core/asm/compiler.go, node/rpcstack.go, node/rpcstack_test.go
It's [more efficient](https://stackoverflow.com/questions/34383705/how-do-i-compare-strings-in-golang) to use `strings.EqualFold()` for [string comparison](https://github.com/dgryski/go-perfbook/blob/master/performance.md#common-gotchas-with-the-standard-library) than the normal operator. Especially when you have to lower or upper case one of the strings first.
=> all: use strings.EqualFold for string comparison

accounts/abi/bind/bind_test.go, accounts/keystore/file_cache.go, cmd/geth/accountcmd_test.go, cmd/geth/version_check_test.go, core/rawdb/freezer.go, eth/tracers/internal/tracetest/calltrace_test.go, internal/build/util.go, rpc/server_test.go, signer/core/signed_data_test.go
Continuation of https://github.com/ethereum/go-ethereum/pull/24869
`ioutil` was deprecated in [Go 1.16](https://go.dev/doc/go1.16#ioutil)
=> all: replace non-trivial uses of ioutil with os

cmd/utils/flags.go, ethdb/remotedb/remotedb.go, internal/ethapi/api.go, internal/ethapi/dbapi.go, internal/web3ext/web3ext.go
I'm not sure if this PR belongs in geth -- it's one of those PRs which doesn't _have_ to be in mainline geth, since it's not useful for the bulk of users. 
This is useful for investigating remote nodes. In many cases when something odd happens, we have to ask people to do various tasks, looking up db values or checking things over rpc. 
Alternatively, we make a special branch with some investigative tools and ask them to compile + redeploy. 
Since a while back, we added `debug_dbGet` to the rpc namespace, which allows us to just wrap the remote rpc endpoint as a database (it'll be readonly, since we decided not to include deletion/modification). 
Examples
Attaching to a local rpc node and getting the metadata: 
```
$ ./build/bin/geth --remotedb …
```
=> ethdb/remotedb, cmd: add support for remote (readonly) databases

core/blockchain.go, core/blockchain_reader.go, core/rawdb/accessors_chain.go, core/rawdb/database.go, core/rawdb/schema.go, eth/api.go, eth/api_backend.go, eth/catalyst/api.go, eth/catalyst/api_test.go, internal/jsre/deps/web3.js, rpc/types.go
This PR implements the notion of `FinalizedBlock` which is set post merge and all RPC calls with blocknumbers can now be called with `finalized` too
=> eth: core: implement final block

console/console_test.go, core/vm/runtime/runtime_test.go, eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/js/goja.go, eth/tracers/js/internal/tracers/tracers.go, eth/tracers/js/tracer.go, eth/tracers/js/tracer_test.go, go.mod, go.sum
Latest bench:
```
name                                old time/op    new time/op    delta
Tracers/create-8                      9.34ms ± 3%    5.16ms ± 1%    -44.82%  (p=0.008 n=5+5)
Tracers/deepCalls-8                   63.1ms ± 1%    38.9ms ± 0%    -38.39%  (p=0.008 n=5+5)
Tracers/delegatecall-8                13.4ms ± 1%     7.7ms ± 1%    -42.80%  (p=0.008 n=5+5)
Tracers/innerCreateOogOuterThrow-8    11.8ms ± 0%     6.2ms ± 1%    -47.04%  (p=0.016 n=5+4)
Tracers/innerInstafail-8              9.35ms ± 8%    5.92ms ± 1%    -36.66%  (p=0.008 n=5+5)
Tracers/innerThrowOuterRevert-8       13.5ms ± 1%     7.2ms ± 2%    -47.16%  (p=0.008 n=5+5)
Tracers/oog-8                         10.4ms ± 1%     5.4ms ± 1%    -48.27%  (p=0.008 n=5+5)
Tracers/revert-8                      8.19ms ± 2% …
```
=> eth/tracers/js: goja tracer

ethdb/remotedb/remotedb.go
The initial commit contained some flaws, as pointed out here:https://github.com/ethereum/go-ethereum/pull/24836#issuecomment-1130181689  by @hsyodyssey
This PR fixes it
=> ethdb/remotedb: fix flawed check in Has/HasAncient

tests/state_test.go, tests/state_test_util.go
Updates the tests to the most recent tip.
=> tests: update reference tests

eth/tracers/js/goja.go, eth/tracers/js/tracer.go, eth/tracers/js/tracer_test.go
Currently there's no way to get the memory length in the js tracer.  I've added the method following the pattern of the `length` method from the stack property:
https://github.com/ethereum/go-ethereum/blob/af806168b62b6a0e772b73ce25d31d8e61d26043/eth/tracers/js/tracer.go#L210-L211
=> eth/tracers/js: add memory.length method

core/beacon/errors.go, eth/catalyst/api.go, eth/catalyst/api_test.go, les/catalyst/api.go
This PR fixes an issue with our implementation where we deviated from the current spec which made us fail some tests on hive wrt. the `LatestValidHash`.
We expect
(1) The LVH to point to the current inserted payload if it was valid.
(2) The LVH to point to the valid parent on an invalid payload (if the parent is available).
(3) If the parent is unavailable, the LVH should not be set.
Before this PR our implementation only pointed to the latest hash set by FCU on an invalid payload.
See also https://github.com/ethereum/hive/pull/526#issuecomment-1113596741
This PR does another sneaky change in adding an error if the payload attributes are invalid, as specified here: https://github.com/ethereum/execution-apis/pull/211#issuecomment-1114164783
=> eth/catalyst: update implementation to spec

core/beacon/errors.go, eth/catalyst/api.go, les/catalyst/api.go, rpc/errors.go
According to https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#errors, we can return custom data error fields too when responding to failures. Do that where Geth has additional context.
=> core, eth, les, rpc: polish catalyst errors, add context

cmd/geth/dbcmd.go, cmd/geth/snapshot.go
This PR adds node checking into traverseRawState command, so corrupted trie node can also be detected.
=> cmd/geth: extend traverseRawState command

eth/catalyst/api.go, eth/catalyst/api_test.go
Fixes an Issue where we would accept a `NewPayload` where the grandparent is already post ttd, and the parent still has a `Difficulty`. This was found by @marioevz with hive in test `Transition to a Chain with Invalid Terminal Block, Higher Configured Total Difficulty (go-ethereum)`
=> eth/catalyst: fix edge case in NewPayload

contracts/checkpointoracle/oracle.go
This PR fixes our go-generate directives relying on solc compiler integration. 
This PR does not contain an updated version of the oracle, though. While testing this, I noticed that the oracle does not compile with the most recent version of `solc`. 
An older `0.6.10` version does compile (with warnings). I didn't think it made any sense to recompile with `0.6.10`, so just left it as it was instead. 
At some point maybe we could make it work on a more recent solc instead, and recompile it properly.
=> contracs/checkpointoracle: fix directives

eth/filters/filter_system_test.go
In func `TestPendingLogsSubscription`,
Goroutine may leak because sending to chan `testCases[i].err` is blocked forever on [L628](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/eth/filters/filter_system_test.go#L628), [L634](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/eth/filters/filter_system_test.go#L634), [L638](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/eth/filters/filter_system_test.go#L638), or [L642](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/eth/filters/filter_system_test.go#L642) when receiving from chan on [L652](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/eth/filters/filter …
=> eth/filters: use buffered channel to avoid goroutine leak

docs/_interface/JavaScript-Console.md
=> docs: redraft JS console page

core/evm.go, eth/tracers/api.go, eth/tracers/api_test.go, internal/ethapi/api.go
Closes https://github.com/ethereum/go-ethereum/issues/24830
This PR adds support for block overrides when doing `debug_traceCall`. 
- Previously, `debug_traceCall` against `pending` erroneously used a `common.Hash{}` stateroot when looking up the state, meaning that a totally empty state was used -- so it always failed, 
- With this change, we reject executing `debug_traceCall` against `pending`. 
- And we add ability to override all evm-visible header fields. 
Example when running this
First mine a block, 
```
> eth.sendTransaction({from: eth.accounts[0], to: eth.accounts[0], value:"0x1"})
INFO [05-13|10:25:03.671] Successfully sealed new block            number=1 sealhash=368ccd..9fe8c5 hash=eec9da..95c7ac elapsed="394.816µs"
INFO [05-13|10:25:03.671] 🔨 mined potential block …
```
=> eth/tracers: add support for block overrides in debug_traceCall

go.mod, go.sum, tests/fuzzers/bls12381/bls12381_fuzz.go
This PR adds the BLST library for BLS-12381 to our fuzzing.
One thing needed is the Pairing for BLST, the API is a bit different, so I'm not sure how to implement it
=> tests/fuzzers/bls12381: Add BLST to fuzzing support

eth/catalyst/api.go, eth/catalyst/api_test.go
=> eth/catalyst: return 0x0 on Invalid block on top of pow block

consensus/misc/eip1559.go
This PR:
1. Reduces memory allocations of `big.Int` in `misc.CalcBaseFee` and makes code a little bit cleaner by using fewer variables.
2. Adds the base fee calculation formulas to comments to make the code easier to read.
=> consensus/misc: reduce allocations and improve comments in CalcBaseFee

go.mod
This is a minor change fixing an error i get on the first build of the project (with fresh go install)
Add module **github.com/Azure/azure-sdk-for-go/sdk/azcore** imported in github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
=> go.mod: set go version to 1.17

core/vm/analysis.go
I benchmarked each commit separately, each giving some positive results but with tiny regressions in some cases (two worst cases PUSH1 and PUSH2 were never negatively affected).
Total performance change:
```
name                           old time/op    new time/op    delta                                                                                                                                                                
JumpdestOpAnalysis/PUSH1-8        983µs ± 0%     843µs ± 0%  -14.22%  (p=0.000 n=9+9)                                                                                                                                             
JumpdestOpAnalysis/PUSH2-8        947µs ± 0%     843µs ± 0%  -11.05%  (p=0.000 n=8+9) …
```
=> core/vm: optimize jumpdest analysis

tests/fuzzers/bls12381/bls12381_fuzz.go
Fixes an issue where a short scalar would crash the deserialization of BLST
=> tests/fuzzers/bls12381: fix blst deserializing

cmd/geth/snapshot.go, core/state/snapshot/dangling.go, core/state/snapshot/generate_test.go, core/state/snapshot/journal.go, core/state/snapshot/utils.go
This PR does a couple of things. 
It changes the journal loading, to make use of an iterator. The same iterator approach is used for 
- loading difflayers
- `account-check`
- `check-dangling-storage`. 
OBS: The dangerous part is the changes to _loading_ difflayers,  which, as opposed to the other changes, could actually _break_ geth if it's erroneously implemented.
This feature makes it possible to inspect the layer-content for a given account (address). 
It starts at the disk layer, and prints out the data (account + storage). Then goes through the journalled difflayers, and shows the data in those too. 
The example run below is from one of the problematic goerli shadowfork nodes. It can be seen that the disk layer has a lot of dangling storage data, and a much more recent difflayer …
=> cmd/geth, core/state/snapshot: rework journal loading, implement account-check

docs/_getting-started/dev-mode.md
the [Getting Started] page url without tailing slash (/docs/getting-started).
=> fix typo url in  dev-mode.md

trie/committer.go, trie/database.go
This PR moves grabbing and releasing the lock on inserting a node into the trie DB into the trie DB `insert` function, since currently the lock is grabbed externally to the function and then released immediately after the function is called everywhere that it gets called.
=> trie: move locking into trieDB insert method

accounts/abi/bind/backends/simulated.go, eth/filters/filter.go, eth/filters/filter_system_test.go, internal/ethapi/backend.go
=> eth/filters: fix pending for getLogs

p2p/discover/v4_udp_test.go
This PR fixes a bug which was hit on appveyor. First we find an error, then the test itself panics. 
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/43778141/job/bwxn7g0m3gqkb1b9
```
--- FAIL: TestUDPv4_findnode (4.04s)
v4_udp.go:554: TRACE[06-07|06:42:24.039] << FINDNODE/v4                           id=86b26dcca98de10d addr=10.0.1.99:30303 err=nil
v4_udp.go:509: TRACE[06-07|06:42:24.040] >> PING/v4                               id=64edc8796c90ce3c addr=10.13.0.8:2000  err=nil
v4_udp.go:509: TRACE[06-07|06:42:24.041] >> NEIGHBORS/v4                          id=86b26dcca98de10d addr=10.0.1.99:30303 err=nil
v4_udp.go:509: TRACE[06-07|06:42:24.041] >> NEIGHBORS/v4                          id=86b26dcca98de10d addr=10.0.1.99:30303 err=nil
v4_udp_test.go:284: sent packet type …
```
=> p2p/discover: fix panicky test

core/forkid/forkid_test.go, eth/backend.go, les/client.go, params/config.go, tests/init.go
Previously on Geth startup we just logged the chain config is a semi-json-y format. Whilst that worked while we had a handful of hard-forks defined, currently it's kind of unwieldy:
```
INFO [05-18|16:52:33.240] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: 4230000 Petersburg: 4939394 Istanbul: 6485846, Muir Glacier: 7117117, Berlin: 9812189, London: 10499401, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: 43531756765713534, Engine: ethash}"
```
This PR converts that original data dump and converts it into a user friendly - alas multiline - log output.
```
INFO [05-18|19:01:25.889] ---------------------------------------------------------------------------------- …
```
=> eth, les, params: log chain config a bit saner

eth/catalyst/api.go
Removes `engine` from any unauthenticated RPC service. I need to test it a bit
```
geth --ropsten --datadir /tmp/foo --nodiscover --maxpeers 0 console  --http --http.api=eth,debug,net,engine,web3
...
Welcome to the Geth JavaScript console!
instance: Geth/v1.10.19-unstable-107e28ac-20220531/linux-amd64/go1.18.1
at block: 0 (Thu Jan 01 1970 01:00:00 GMT+0100 (CET))
datadir: /tmp/foo
modules: admin:1.0 debug:1.0 engine:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
```
And connecting to it from remote:
```
> [user@work go-ethereum]$ geth attach http://127.0.0.1:8545
Welcome to the Geth JavaScript console!
instance: Geth/v1.10.19-unstable-107e28ac-20220531/linux-amd64/go1.18.1
at block: 0 (Thu Jan 01 1970 01:00:00 GMT+0100 (CET))
modules: debug:1.0 eth:1.0 …
```
=> eth/catalyst: remove unauthenticated 'engine' api

cmd/utils/flags.go
Just changed to `Ropsten network: pre-configured proof-of-stake test network`
=> cmd/utils: update --ropsten description

README.md, eth/filters/api.go
`eth.wiki` is considered deprecated, so we should be pushing people to more up-to-date resources.
=> readme,eth: remove references to eth.wiki

cmd/ethkey/message.go, cmd/ethkey/utils.go, signer/core/signed_data.go
1. use accounts.TextHash in cmd/ethkey
2. clean up comment
=> cmd/ethkey: use accounts.TextHash

common/format.go
Improves the speed of the prettyDuration regular expression by making it more specific
```
Master:
BenchmarkFormat-8   	 2040429	       659.9 ns/op	      53 B/op	       3 allocs/op
This PR:
BenchmarkFormat2-8   	 3560108	       334.8 ns/op	      30 B/op	       1 allocs/op
```
Benchmark code:
```go
func BenchmarkFormat(b *testing.B) {
s := ""
start := time.Now()
for i := 0; i < b.N; i++ {
dur := PrettyDuration(time.Since(start))
s = dur.String()
}
_ = s
}
```
=> common: improve pretty duration regex

eth/api.go, eth/downloader/api.go
Adds a few periods at the end of function-level documentation.
=> Add missing periods on end of comments

eth/downloader/downloader_test.go, eth/protocols/eth/handler.go, eth/protocols/eth/protocol.go, eth/sync_test.go, les/downloader/peer.go
In this PR, a new eth protocol `eth67` is introduced. The main change in this protocol version is `GetNodeDataMsg` and `NodeDataMsg` protocol messages are not supported anymore.
The rationale behind this change is: 
(1) fast sync is dropped by Geth, all other ethereum implementations should also jump to snap sync, a better sync algorithm. These two protocol messages are not needed.
(2) Geth will adopt path based state storage scheme very soon which can't support hash based state serving
(3) `OpenEthereum` and `Erigon` stopped serving fast sync data already even at the expense of a protocol violation, `eth67` is just catching up with the general direction
In order to have a smooth transition between the hash-based-state-storage and path-based-state-storage, `eth67` needs to be rolled out …
=> eth: introduce eth67 protocol

node/node.go
Adds an INFO line about successfully reading the JWT secret
=> node: add JWT secret log line

internal/ethapi/api.go
- Added a comment explaining that it dares to return nil instead of err.
=> internal/ethapi: add comment explaining return of nil instead of error

tests/fuzzers/rlp/rlp_fuzzer.go
The oss-fuzz engine crashes due to stack overflow decoding a large nested structure into a `interface{}`. This PR limits the size of the input data, so should avoid such crashes.
=> tests/fuzzers/rlp: avoid very large input

node/rpcstack_test.go
https://github.com/ethereum/go-ethereum/pull/25016 made the jwt tests a bit less prone to fail on appveyor, however it still happens from time to time that the tests fail. 
This is due to the amount of time that passes between the creation of the token and the request is made. This PR modifies the tests to not use `[]string`, but instead methods which are evaluated right before the request is made.
=> node: make jwt tests less time-dependent

trie/database.go
This PR fixes an instance where the dirtiesSize of the trie DB is decreased in place of the childrenSize value.
Thanks to @patrick-ogrady for finding a related issue in coreth.
=> trie: fix size accounting in cleaner

cmd/geth/accountcmd_test.go, cmd/geth/consolecmd.go, cmd/geth/main.go, cmd/utils/flags.go, console/console.go, console/console_test.go, console/testdata/exec.js
Drops support for `geth js file.js`. It is easily replaceable by `geth --exec "loadScript('file.js')" console`.
Also refactors ipc path determination for `attach`.
=> cmd/geth: drop geth js command

docs/_interface/merge.md
As per #25018 (included in v1.10.19), the new Ropsten TTD is hardcoded, and users no longer have to use the --override.terminaltotaldifficulty flag.
=> [DOCS]: add note about hardcoded ropsten ttd

eth/catalyst/api.go, miner/miner.go, miner/worker.go
This PR drops the necessity of recovering state for mining block.
In PoW, the state of head block is always used as base for preparing a mining block. It's unnecessary to recover state at all.
In PoS, the mining block is always generated with a `ForkchoiceUpdatedV1` request from consensus client with the head block specified. It means the base state should always be prepared for new mining block.
All in all, it's unnecessary to have this complicated mechanism for recovering a state for new mining block.
=> miner: retrieve mining state from live database

eth/tracers/js/goja.go
It seems like going directly from a byte array to `Uint8Array` incurs more copying than going through an `ArrayBuffer` which typed arrays use as the underlying buffer.
Testing this on block 14996244. Before:
```console
Duktape prestateTracerLegacy for block 14996244: 8785ms
Goja prestateTracerLegacy for block 14996244: 17213ms
```
After:
```console
Duktape prestateTracerLegacy for block 14996244: 8913ms
Goja prestateTracerLegacy for block 14996244: 8743ms
```
Fixes #25125
=> eth/tracers: optimize goja buffer conversion

internal/ethapi/api.go
I think it would be good to actually note this behavior, because it does not conform to EIP-695 as @fjl pointed out here: https://github.com/ethereum/go-ethereum/pull/21686#issuecomment-740523125
--
quote:
> In [EIP-695](https://eips.ethereum.org/EIPS/eip-695), it says
> >  The chain ID returned should always correspond to the information in the current known head block. This ensures that caller of this RPC method can always use the retrieved information to sign transactions built on top of the head.
> > If the current known head block does not specify a chain ID, the client should treat any calls to eth_chainId as though the method were not supported, and return a suitable error.
> So, the current geth behavior and this PR are not correct. eth_chainId should return an error when the …
=> internal/ethapi: add note about eth_chainId compatibility with EIP-695

cmd/clef/main.go, consensus/clique/clique.go, consensus/ethash/ethash.go, eth/backend.go, eth/catalyst/api.go, eth/tracers/api.go, internal/ethapi/backend.go, les/catalyst/api.go, les/client.go, les/server.go, node/api.go, node/rpcstack.go, node/utils_test.go, rpc/types.go
Depends on #25053.
This PR removes `public` from `rpc.API`.
=> all: remove `public` field from `rpc.API`

params/config.go
This PR sets the TTD for the sepolia testnet to 17_000_000_000_000_000 which is ~ 2x the current TD of 9,646,065,446,818,603 (according to otterscan)
=> params: set TTD for sepolia testnet

cmd/geth/main.go, cmd/utils/flags.go, p2p/server.go
Implements a geth cli flag to modify the P2P discovery server's UDP listening address. Solves issue #22040. 
See the issue for an overview of my proposed changes.
=> p2p: custom discovery UDP port

core/state/snapshot/disklayer_test.go
This PR simplifies the setup for TestDiskSeek by replacing constructing a leveldb instance with a memorydb instance as is used in the other unit tests.
=> core/rawdb: simplify TestDiskSeek to use memorydb

internal/ethapi/api.go
Partially fixes #25141.
```console
$ geth --dev console
> eth.sendTransaction({"from": personal.listAccounts[0], "to": personal.listAccounts[0]})
"0x3ca1cc849ce362a83369aa6925287b616632e195c9f5c5fb10f8923d56298cfa"
> eth.getTransaction("0x3ca1cc849ce362a83369aa6925287b616632e195c9f5c5fb10f8923d56298cfa")
{
accessList: [],
blockHash: "0xe706635bf933e3b9d4ae3d6f245af30e5c15f3f8278501a4e59d5b40c61c0fdd",
blockNumber: 1,
chainId: "0x539",
from: "0x579d7d50c7c69203dde8c46efb3b383ae948d0a9",
gas: 21000,
gasPrice: 875000001,
hash: "0x3ca1cc849ce362a83369aa6925287b616632e195c9f5c5fb10f8923d56298cfa",
input: "0x",
maxFeePerGas: 2000000001,
maxPriorityFeePerGas: 1,
nonce: 0,
r: "0xac23f21e665937e1777448d96f47a088b1423a7006322bf8d021f4a1f1e921a",
s: …
```
=> internal/ethapi: explicitly return chain id for EIP-155 legacy txs

consensus/beacon/consensus.go, consensus/beacon/consensus_test.go, consensus/errors.go, core/block_validator_test.go
Before this PR the following chain would be deemed valid during sync:
p1 <- p2 <- p3 <- p4 <- b1 <- b2 (each pX block with difficulty of 1)
and TTD = 3 
even though the chain has two blocks that passed the ttd requirement
This PR fixes an issue surfaced by the hive tests cc @marioevz @mkalinin 
The following hive tests *should* be fixed by this:
- Transition to a Chain with Invalid Terminal Block, Higher Configured Total Difficulty
- Transition to a Chain with Invalid Terminal Block, Higher Configured Total Difficulty (Transition Payload)
=> consensus/beacon: check that only the latest pow block is valid ttd block

build/deb/ethereum/completions/bash_autocomplete, build/deb/ethereum/completions/zsh_autocomplete, build/deb/ethereum/deb.install
The auto-completion scripts [urfave/cli](https://cli.urfave.org/v2/#enabling)from were added in https://github.com/ethereum/go-ethereum/pull/24751 but it also needs to reference `geth` and be added to the deb packaging.
I'll follow-up with a PR to update the gh-pages documentation.
NOTE: Zsh doesn't have a defined place to add completion files, like Bash. It's up to the user to fetch and reference the file.
I can confirm once the files (for Bash and Zsh completions) are sourced, the auto-completion works out of the box perfectly. Follow some screenshots:
=> build: fix auto-completion scripts and include them in .deb package

eth/catalyst/api.go, eth/catalyst/api_test.go, eth/handler.go
**Tests should be expanded to cover both full and snap sync behavioral requirements**
There is a very subtle bug in the catalysts API. Specifically, `newPayload` will always import a block if the parent's state is available, independent of what sync mode we're in. This does not match the behavior of pre-merge sync, where propagates blocks during snap sync are discarded.
The subtlety is important however. The snap sync code - everywhere - assumes that is has full control over the database and nobody else will poke at it. There are various optimizations (like the direct freezer inserter, rollback points, pivot markers, beacon sync link points) that all rely on the invariant that only snap modifies the db initially.
Allowing newPayload to always import a block if the state is available is a …
=> eth/catalyst: disallow importing blocks via newPayload during snap sync

accounts/abi/argument.go
Replace unnecessary fmt.Errorf with errors.New in accounts/abi/argument.go
=> Replace fmt.Errorf with errors.New in abi argument

accounts/scwallet/securechannel.go, accounts/scwallet/wallet.go, cmd/devp2p/internal/ethtest/snap.go, cmd/evm/runner.go, cmd/geth/dbcmd.go, cmd/rlpdump/main.go, cmd/rlpdump/rlpdump_test.go, consensus/misc/forks.go, core/asm/asm.go, core/blockchain.go, core/types/hashing_test.go, core/vm/jump_table.go, core/vm/opcodes.go, core/vm/runtime/runtime_test.go, eth/api.go, eth/api_test.go, eth/filters/api_test.go, eth/tracers/logger/logger.go, internal/ethapi/api.go, mobile/types.go, signer/core/apitypes/types.go, signer/core/signed_data.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/trie_test.go
The commit for a consistent format.
Some places use `0x%x`, some use `%#x`.
=> all: change format `0x%x` to `%#x`

consensus/beacon/consensus.go
Fixes an issue where during the sync we modified the td of the blocks, which resulted in marking blocks as `invalid-termina-blocks`
=> consensus/beacon: copy td value so we can modify it

core/blockchain.go, core/blockchain_reader.go
This small change allows us to create an invalid blockchain for hive tests
=> core: allow external code to set the validator

core/genesis.go
This PR fixes #25133. The issue is that if the datadir is uninitialized (or we're missing the state for the genesis block) we don't apply the overrideTTD flag correctly.
=> core: apply ttd override to uninitialized db

signer/core/apitypes/types.go
I have a EIP712 typehash using uint96, but it's currently not supported
by go-ethereum. This change fixes it.
=> apitypes: support primitive types int96/uint96

cmd/devp2p/discv4cmd.go, cmd/geth/chaincmd.go, cmd/geth/consolecmd.go, internal/flags/helpers.go
This resolves a few regressions from the cli/v2 migration.
Closes #25224 
Closes #25209
=> cmd/geth, cmd/devp2p: fix some cli parsing issues

core/blockchain.go
This extends the new `SetValidator` method so that we can also set a processor. This allows us to set invalid blocks with invalid transactions in hive
=> core: allow external processor

consensus/beacon/consensus.go
This PR fixes a hive tests where a chain with overlapping timestamp is imported during sync
=> consensus/beacon: verify timestamp is greater than parent timestamp

go.mod
This fixes an issue for tests ran with go-1.17
```
--- FAIL: TestGolangBindings (0.24s)
bind_test.go:2072: failed to tidy Go module file: exit status 1
bindtest imports
github.com/ethereum/go-ethereum/core/types tested by
github.com/ethereum/go-ethereum/core/types.test imports
github.com/ethereum/go-ethereum/core/rawdb imports
github.com/prometheus/tsdb/fileutil tested by
github.com/prometheus/tsdb/fileutil.test imports
github.com/prometheus/tsdb/testutil imports
github.com/go-kit/kit/log imports
github.com/go-logfmt/logfmt loaded from github.com/go-logfmt/logfmt@v0.3.0,
but go 1.16 would select v0.4.0
To upgrade to the versions selected by go 1.16:
go mod tidy -go=1.16 && go mod tidy -go=1.17
If reproducibility with go 1.16 is not needed:
go mod tidy -compat=1.17
For other options, see: …
```
=> go.mod: updated logfmt dependency

core/types/hashing.go
Changed `deriveBufferPool` to `encodeBufferPool`, in comment for encodeBufferPool.
=> core/types: fix typo in comment

node/rpcstack.go
This is a proposed fix for #25257.
I triggered a pprof and got the goroutine snapshot during the time geth hangs. It shows that the program has caught the SIGINT signal and has entered the `shutdown()` sub-func in `StartNode()`, so it spawns the `go stack.Close()`(https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/cmd.go#L92) but this goroutine then hangs at the `net/http.Shutdown()` so the terminating procedure cannot proceed.
```
goroutine 19333821 [select]:
net/http.(*Server).Shutdown(0xc014d0c620, {0x17deb68, 0xc000138000})
net/http/server.go:2775 +0x269
github.com/ethereum/go-ethereum/node.(*httpServer).doStop(0xc0002a3040)
github.com/ethereum/go-ethereum/node/rpcstack.go:264 +0x152
github.com/ethereum/go-ethereum/node.(*httpServer).stop(0x1357081a9754b950?) …
```
=> rpc: add graceful shutdown timeout for HTTP server

p2p/discover/ntp.go, p2p/discover/table_util_test.go, p2p/discover/v4_udp.go, p2p/discover/v4_udp_test.go, p2p/discover/v4wire/v4wire.go, p2p/discover/v5_udp.go, p2p/discover/v5wire/encoding.go
=> p2p/discover: fix typos in comments

eth/tracers/native/returnmsg.go, eth/tracers/native/revertreason.go
The idea of this pr was came up when I worked on a fusion (evm-compatible) block explorer.
Every failed transaction may have a error message return, either a system error (ErrExecutionReverted) or a custom error (message from abi Error(string))
The traditional way to fetch the message is to re-execute the transaction (eth_call) again on the specific block height, however this is not accurate, because other transactions in the same block may affect the transaction result (especially for the Dex Swap), so using debug trace will be the best solution to solve the case.
I have implemented this feature on fusion blockchain for months and the result is good, you can refer https://fsnscan.com
=> eth/tracers: add initial revertReasonTracer tracer

internal/build/archive.go
When creating the release archive tarballs, we place the files into a nested folder (e.g. `geth-linux-amd64-1.10.20-8f2416a8`). When creating this folder inside the tarball, the modification time is not set and defaults to the `0 unix timestamp`, which certain tools warn about. This PR fixes it by actually setting a timestamp on the directory header inside the tarball.
Fixes https://github.com/ethereum/go-ethereum/issues/25263.
=> internal/build: add a timestamp to the tar archive folder

cmd/clef/main.go, consensus/clique/clique.go, consensus/ethash/ethash.go, eth/backend.go, eth/catalyst/api.go, eth/tracers/api.go, internal/ethapi/backend.go, les/catalyst/api.go, les/client.go, les/server.go, node/api.go, node/utils_test.go, p2p/simulations/adapters/exec.go, rpc/types.go
Follow on to #25059
Remove the use of `rpc.API.Version` since it is not subsequently used anywhere. It could be neat to eventually use this method to define methods like `eth_callV2` or something, but that feels like far enough in the future (and uncertain enough) to deprecate the field for now.
=> all: remove version field

internal/ethapi/transaction_args.go
Partially closes #25141.
```console
$ geth --dev console
> eth.sendTransaction({"from": personal.listAccounts[0], "to": personal.listAccounts[0], "chainId": "0x123"})
Error: chain id does not match local (got=291, want=1337)
at web3.js:6365:9(45)
at send (web3.js:5099:62(34))
at <eval>:1:20(16)
> eth.sendTransaction({"from": personal.listAccounts[0], "to": personal.listAccounts[0], "chainId": "0x539"})
"0x2ae33c38f61d2b15f11b8af4298c9b12e53d0ac55b17209487d2f4f5d5a56ac6"
```
=> internal/ethapi: error if tx args includes chain id that doesn't match local

core/blockchain.go
Since ExportN is read-only, it shouldn't need the lock. (?)
=> Remove locking in (*BlockChain).ExportN

core/state/statedb.go, core/state/sync.go, core/state/sync_test.go, eth/downloader/skeleton_test.go, eth/protocols/snap/sort_test.go, eth/protocols/snap/sync.go, les/downloader/statesync.go, trie/committer.go, trie/sync.go, trie/sync_test.go, trie/trie.go, trie/trie_test.go
It's a PR based on the #24750 which ports some changes in snap sync from the PBSS PR.
=> core, les, eth: port snap sync changes

tests/state_test_util.go
Otherwise some rules might be enabled even if others are disabled (e.g. berlin gas calculation on istanbul chain config)
=> tests: only activate merge on london rules

trie/sync.go
Fixes a build regression introduced in https://github.com/ethereum/go-ethereum/pull/24898
=> trie: fix 'gosimple' lint issue

docs/_interface/Private-Network.md
I updated the example genesis.json so that it matches mainnet's HF from block 0. 
The reason I think this is a positive change is that users get confused by tools not behaving like their private network by default: https://github.com/NomicFoundation/hardhat/issues/2946
=> docs: Update private network config

docs/_rpc/server.md
Expanded page to better explain differences between RPC transport protocols.
=> docs: update RPC server page to describe transport protocols

params/config.go
Following @fjl's request to break the verkle PR down into smaller pieces, here comes the first PR that adds fork blocks for Shangai and Cancun.
Shangai is the first fork coming after the merge, and is necessary to introduce the removal of `SELFDESTRUCT`, necessary for verkle trees.
Cancun is the next major fork, that introduces verkle trees.
=> params: Add Shanghai and Cancun blocks

signer/core/apitypes/types.go, signer/core/signed_data.go
This PR adds methods for canonical `TypedData` (EIP 712) hashing: `TypedDataHash` and `TypedDataAndHash`.
These are meant to be similar to `PersonalMessage` (EIP 191) hashing methods `TextHash` and `TextAndHash`.
Since geth is the Ethereum reference library, it'd be useful to have the canonical method inside of geth itself.
=> signer/core: add canonical TypedData hashing methods

core/forkid/forkid_test.go, params/config.go
This PR sets the merge netsplit block for sepolia as defined in https://github.com/ethereum/execution-specs/pull/564/files
=> params: set sepolia mergeNetsplitBlock to 1735371

cmd/geth/consolecmd_test.go, cmd/geth/genesis_test.go, cmd/geth/les_test.go, cmd/utils/flags.go, eth/catalyst/api.go, les/catalyst/api.go
This PR enables the authrpc endpoint by default.
It has a caveat. If the CL calls any function other than `engine_exchangeTransitionConfiguration` the rpc call with panic and return an error (the node itself will still work fine).
=> cmd/geth: eth/catalyst: enable authrpc by default

eth/catalyst/api.go
Make the warning a bit easier to understand
=> eth/catalyst: better warning for ttd not configured

cmd/geth/chaincmd.go, cmd/geth/config.go, cmd/geth/consolecmd.go, cmd/geth/dbcmd.go, cmd/geth/main.go, cmd/geth/snapshot.go, cmd/utils/flags.go
This PR switches all `utils.GroupFlags` to `flags.Merge`. These two methods are identical and doesn't make sense to keep both.
It should be a very-easy-to-merge PR.
=> cmd: use flags.Merge for grouping flags

light/trie_test.go
fix `differTries()` error message
=> light/trie_test.go: fix differTries err message

core/beacon/types.go, eth/catalyst/api.go, eth/catalyst/api_test.go, eth/downloader/beaconsync.go, eth/downloader/downloader.go
Can't test it because hive is broken. /shrug
=> eth: support bubbling up bad blocks from sync to the engine API

core/blockchain.go, core/blockchain_reader.go, eth/api.go, eth/api_backend.go, eth/catalyst/api.go, internal/jsre/deps/web3.js, rpc/types.go
This PR implements the `safe` block tag for all block related RPC calls.
Contrary to the `finalized` block, the safe block is not stored in the database. It is initialized to the finalized block on startup.
```
> eth.getBlock("safe")
{
baseFeePerGas: 7,
difficulty: 0,
extraData: "0x",
gasLimit: 30000000,
gasUsed: 46083,
hash: "0x676383cc22620f878a1ee56ef74fd35201a6bcf95f30424958e74684000867b1",
logsBloom: "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> core: eth: rpc: implement safe rpc block

go.mod, go.sum
This PR downgrades the leveldb to a stable version.
Recently Geth pulled the changes made in go-leveldb, while it includes a buggy [change](https://github.com/syndtr/goleveldb/commit/afa53115c7698fb6dba75ccaeba1adafd1a9a4b1)
TL;DR With this change, some obsolete sstables will be referenced forever and can only be deleted in next restart. 
And even worse, for archive node, leveldb will create MANIFESTs(>64MB) for each leveldb compaction which will
bloat the entire database extremely fast.
Therefore, this PR downgrades the leveldb to a stable version which we have used for a year. And once the issue in
leveldb is resolved and regarded as stable again, we can pull the changes.
=> go.mod: downgrade leveldb

docs/_rpc/ns-debug.md
Looking at the JavaScript-based tracing specification of debug_traceTransaction the specification of `log.stack` seems incorrect because there is a `log.stack` Object with a couple of methods defined (peek and lengh) but the list of fields of `log` does not mention this `stack` Object.
Please let me know what is the most correct/recent specification for this endpoint.
=> Update debug_traceTransaction specification

cmd/evm/internal/t8ntool/execution.go, core/state/state_test.go, eth/api_test.go, trie/database.go, trie/preimages.go, trie/secure_trie.go
This PR separates the preimage logic to a standalone struct called `preimageStore`. It should simplify the code a bit.
Also another big change in this PR is: the preimage recording is disabled by default now.
=> core, trie, eth, cmd: rework preimage store

eth/catalyst/api.go
Fixes https://github.com/ethereum/go-ethereum/issues/25427, which is a false alarm due to a bad log message.
=> eth/catalyst: fix NewPayload warn log when dropping due to snap sync

node/jwt_handler.go, node/rpcstack_test.go
The default JWT timeout recently changed: https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md#jwt-claims
=> node: set JWT expiry to 60 seconds

eth/catalyst/api.go, eth/catalyst/api_test.go
> ACCEPTED is only allowed when "ancestors of a payload are known and comprise a well-formed chain."
At this point we don't know that, so we need to return syncing
=> eth/catalyst: return syncing not accepted

eth/catalyst/api.go
Weird requirement of the engine api
> {payloadStatus: {status: INVALID, latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000, validationError: errorMessage | null}, payloadId: null} obtained either from the [Payload validation](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#payload-validation) process or as a result of validating a terminal PoW block referenced by forkchoiceState.headBlockHash
Fixes two hive tests
=> eth/catalyst: return 0x0 if latestvalid is pow block

ethclient/ethclient.go, ethclient/ethclient_test.go, interfaces.go, internal/ethapi/api.go
Since fee history [is in](https://github.com/ethereum/execution-apis/blob/b4051c2f97cbd83f29c4f2cf3bdc2737600e5cc8/src/eth/fee_market.yaml#L9-L66) the JSON-RPC specification, I think it makes sense to support in `ethclient`. It's not trivial to decode the response into nice types when making the raw call.
=> ethclient: add `FeeHistory` support

common/mclock/simclock.go, common/prque/lazyqueue.go, les/distributor.go, les/flowcontrol/control.go, les/utils/timeutils_test.go, les/vflux/server/balance.go
This is just a syntactic change. It's same operation internally.
=> all: use AbsTime.Add instead of conversion

eth/api.go
Fixed grammatical error in comment. 
Added a period at the end of the comment on line 160 of 'eth/api.go' to make the comment style consistent with both [gofmt](https://github.com/golang/go/blob/master/src/cmd/gofmt/gofmt.go) comment conventions and the rest of the file.
Co-Authored-By: Rithwik Babu <54031798+rithwikbabu@users.noreply.github.com>
Co-Authored-By: JAIN0103 <85311310+jain0103@users.noreply.github.com>
=> eth: fix typo in comment

docs/_getting-started/dev-mode.md, docs/_getting-started/geth_with_clef.md, docs/_getting-started/index.md
splits beginner tutorial into two pages, one using Geth's built in account management tool and one using Clef.
Linked to issue #25347
=> split beginner tutorial -> clef/non-clef versions

eth/gasprice/feehistory.go, eth/gasprice/feehistory_test.go, eth/gasprice/gasprice_test.go
fixes #25420
I reworked `resolveBlockRange` a little bit, because I was having a little trouble following the previous flow.
=> eth/gasprice/feehistory: support finalized block

consensus/ethash/ethash.go
=> consensus/ethash: remove temp files created during DAG generation

cmd/devp2p/internal/ethtest/chain.go, cmd/devp2p/internal/ethtest/chain_test.go, cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/snapTypes.go, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/suite_test.go, cmd/devp2p/internal/ethtest/transaction.go, cmd/devp2p/internal/ethtest/types.go, cmd/devp2p/rlpxcmd.go
This change removes eth/65 tests and allows the remaining tests to run with either eth/66 or eth/67.
The amount of unique test scenarios does not decrease with this change, but overall test count is half of what it was before.
=> cmd/devp2p/internal/ethtest: update tests for eth/67

node/endpoints.go, node/rpcstack.go, rpc/http.go
This change makes http.Server.ReadHeaderTimeout configurable separately
from ReadTimeout for RPC servers. The default is set to the same as
ReadTimeout, in order to cause no change in existing deployments.
This is recommended by the following blog post in order to allow
mitigation of SLOWLORIS attacks:
https://simon-frey.com/blog/go-as-in-golang-standard-net-http-config-will-break-your-production/
=> node, rpc: add ReadHeaderTimeout config option

core/bloom_indexer.go
I guess, it possible that get the need memory size to Batch for BloomIndexer.Commit() in advance.
So it seems better to use NewBatchWithSize() than NewBatch().
```
// b.size will be set types.BloomBitsBlocks
batch := b.db.NewBatchWithSize((int(b.size) / 8) * types.BloomBitLength)
```
<br>
Here is my test codes and result about this.
```go
package test
import (
"testing"
)
const BloomBitsBlocks = 4096
const BloomBitLength = 2048
type Batch struct {
data []byte
}
func generateBloom() [BloomBitLength][]byte {
var bloom [BloomBitLength][]byte
for i := 0; i < BloomBitLength; i++ {
bloom[i] = make([]byte, BloomBitsBlocks/8)
}
return bloom
}
func BenchmarkOrigin(b *testing.B) {
bloom := generateBloom()
b.ResetTimer()
for i := 0; i < b.N; i++ {
tBatch := Batch{}
for j := 0; j < BloomBitLength; …
```
=> core: preallocate batch size in bloomIndexer

internal/ethapi/api.go
Alternative approach to #25328, based on comments from @fjl, @holiman.
Because the goal of `eth_createAccessList` is to provide the caller with an accurate access list, it's generally not important what gas limit the tracer is run under. As long as the call does not branch based on the gas limit, the access list returned will be accurate.
Before:
```console
> a = personal.listAccounts[0]
"0x9ca58ca9c146b4910075875c23c006ba0b3fe5ad"
> eth.sendTransaction({"from": a, "data": "0x6009600c60003960096000f3585854585854585854"})
"0x67F8AB20E1a548F447b1b3c3D61f18793E42f6dD"
> eth.createAccessList({"to": "0x67F8AB20E1a548F447b1b3c3D61f18793E42f6dD", "from": a}, "latest")
WARN [07-18|13:39:25.020] Served eth_createAccessList              reqid=13 duration=7.551625ms err="failed to apply transaction: …
```
=> internal/ethapi: don't estimate gas if no limit provided in eth_createAccessList

docs/_rpc/ns-debug.md
The spec for JavaScript-based tracing in `debug_traceTransaction` is missing some functions that are implemented in goja.js"
Log.Memory.length()
Context.gasPrice
Context.intrinsicGas
=> Update tracing spec in `debug_traceTransaction`

eth/api.go
This PR changes an `fmt.Errorf(...)` to `errors.New(...)` since there are no formatted arguments in the error.
=> Formatted error nit

cmd/devp2p/internal/ethtest/chain.go, cmd/evm/runner.go, cmd/faucet/faucet.go, consensus/clique/snapshot_test.go, core/blockchain_test.go, core/genesis.go, core/genesis_test.go, core/rawdb/accessors_metadata.go, core/rawdb/schema.go, eth/catalyst/api_test.go, eth/downloader/downloader_test.go, eth/downloader/queue_test.go, eth/downloader/testchain_test.go, eth/fetcher/block_fetcher_test.go, eth/filters/filter_test.go, eth/gasprice/gasprice_test.go, ethclient/ethclient_test.go, ethclient/gethclient/gethclient_test.go, les/catalyst/api_test.go, les/downloader/queue_test.go, les/downloader/testchain_test.go, les/fetcher/block_fetcher_test.go, les/peer_test.go, miner/stress/beacon/main.go, tests/state_test.go, tests/state_test_util.go
Currently there are a few APIs for initializing genesis state:
- ToBlock(db)
- Commit(db)
- MustCommit(db)
- GenesisBlockForTesting(db)
Basically all of them can be used to flush genesis state into the provided database.
In this PR, I removed the `GenesisBlockForTesting` which can be replaced by other APIs. And also the semantic of `ToBlock` is changed, It can only be used for obtaining the genesis block, but not for flushing genesis states.
Why do we need this change? We need to support both hash-based and path-based state scheme for some times. Therefore, an additional scheme flag will be passed to these APIs for flushing genesis states with correct scheme. Would be nice to cleanup these APIs first.
=> all: cleanup the APIs for initializing genesis

signer/rules/rules.go
The bidirectional channel was not working properly when a ruleset UI was used, which is fixed by this PR. 
Fixes #25298
=> signer/rules: register clef api properly when rules are used

core/state_processor.go
`bc ChainContext` is not used by `applyTransaction` at all, so there is no need to pass it.
The context is restarted by `applyTransaction` to the `txContext`:
https://github.com/ethereum/go-ethereum/blob/master/core/state_processor.go#L98
=> core: remove unused bc ChainContext in applyTransaction

Dockerfile, Dockerfile.alltools, build/ci.go, internal/build/env.go, internal/build/util.go
improve from PR #17247
This adds a new flag to the ci.go install script, `-static` which produces static linked binary.
Note: this is **only** working in **Alpine Linux musl library**
No dynamic library dependencies
=> build: add static linking support

accounts/abi/abi.go
This PR replaces an `errors.New` with a slightly more informative `fmt.Errorf` including the name of the method/event that could not be found.
=> accounts/abi: add name to method/event not found err

internal/ethapi/transaction_args.go, internal/ethapi/transaction_args_test.go
The PR #25193 found that there is a bug in `setDefaults` where the `IsLondon` check is always false. I don't think that change really addresses the underlying issue and I feel like the feel logic has gotten complicated enough to pull out of `setDefault` into its own function and test independently. So I've taken a stab at it here.
=> internal/ethapi: rework `setDefaults` for tx args so fee logic is separate

params/config.go
This PR sets the mainnet total terminal difficulty as defined inhttps://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
This enables the merge on mainnet. 
```
INFO [08-15|17:25:47.999]  
INFO [08-15|17:25:47.999] --------------------------------------------------------------------------------------------------------------------------------------------------------- 
INFO [08-15|17:25:47.999] Chain ID:  1 (mainnet) 
INFO [08-15|17:25:47.999] Consensus: Beacon (proof-of-stake), merged from Ethash (proof-of-work) 
INFO [08-15|17:25:47.999]  
INFO [08-15|17:25:48.000] Pre-Merge hard forks: 
INFO [08-15|17:25:48.000]  - Homestead:                   1150000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homes …
```
=> params: set mainnet terminal total difficulty for the merge

core/blockchain.go, trie/database.go
While working on verkle, I noticed that preimages were not properly saved. This PR adds a `Close` method on the trie database, so that preimages are saved.
Co-authored-by: rjl493456442 <garyrong0905@gmail.com>
=> core, trie: flush preimages to db on database close

core/state/database.go, core/state/statedb.go, light/trie.go, trie/secure_trie.go
Account deletion also needs to be abstracted, since verkle trees have to overwrite more than one leaf when deleting an account.
=> core/state, trie, light: Add a DeleteAccount method

core/tx_journal.go
This part can use os.Open() once to check the `file does not exist`.
=> core: reduce system call about `os`

core/genesis.go
The recent refactors to the preimage code have deactivated the saving of preimages during the generation of the genesis state. This PR re-enables it.
=> cmd. core: save preimages on genesis creation

docs/_dapp/builtin-tracers.md, docs/_dapp/custom-tracer.md, docs/_rpc/ns-debug.md
Documentation for:
- #25430 (merged)
- #25508 (NOT merged)
=> doc: add info about tracer config, rm revertReasonTracer

rlp/rlpgen/main.go
`typ` will be `nil` if `lookupStructType` returns an error. I think `cfg.Type` should be used instead.
=> rlp/rlpgen: fix error handling when target type not found

trie/database.go, trie/node.go, trie/node_test.go
This PR improves node(mostly full node) rlp decoding efficiency by avoiding byte copy.
Currently, bytes will be deep copied from the given byte stream to node struct when decoding. If we can hold the assumption that the provided byte stream is immutable, then we can avoid this deep copy.
It turns out this optimization can decrease the time from 1000ns to 670ns on my laptop for decoding a full node, 33% speedup.
=> trie: improve node rlp-decoding

eth/downloader/peer.go, les/downloader/peer.go
Noticed these two missing unlocks. The mutex is unlocked in the error check right above, but not in this error check. I suspect that this check was added later and the author forgot to add the unlock.
=> eth, les: unlock peerSet if there's an error

cmd/geth/chaincmd.go
It's cleaner/safer to parse this number with `ParseUint` than `Atoi`.
This was identified with Semgrep & the `string-to-int-signedness-cast` rule.
References:
* https://semgrep.dev/
* https://semgrep.dev/r?q=trailofbits.go.string-to-int-signedness-cast.string-to-int-signedness-cast
* https://github.com/trailofbits/semgrep-rules/blob/main/go/string-to-int-signedness-cast.yml
=> cmd/geth: parse uint64 value with ParseUint instead of Atoi

consensus/beacon/consensus.go
Fixes the last failing hive test. Basically we need to check that the TTD is reached even if we only get a batch of post merge headers
=> consensus/beacon: check ttd reached on pos blocks

accounts/abi/bind/backends/simulated.go, cmd/geth/config.go, cmd/geth/main.go, cmd/utils/flags.go, core/blockchain.go, core/blockchain_reader.go, eth/api_backend.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, eth/filters/api.go, eth/filters/bench_test.go, eth/filters/filter.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go, eth/filters/filter_test.go, ethclient/gethclient/gethclient_test.go, graphql/graphql.go, graphql/graphql_test.go, graphql/service.go, internal/ethapi/backend.go, les/api_backend.go, les/client.go
This adds a cache for block logs which is shared by all filters. In order to share the cache reference, filters now need to be created through a 'filter system' object. Cache size is user-configurable via `--cache.blocklogs`.
This PR is an alternative to https://github.com/ethereum/go-ethereum/pull/25425.
cc @ryanschneider 
Fixes https://github.com/ethereum/go-ethereum/issues/25421 
Includes #25468, which should be merged first.
=> eth/filters: add global block logs cache

accounts/abi/reflect.go, accounts/abi/unpack_test.go
Without this patch, [this test](https://github.com/zhiqiangxu/multicall/blob/master/multicall_test.go#L96) will report `abi: cannot unmarshal string in to string`:
After this patch, the above test will pass.
After all, there's no point to call `set` on `dst.Elem()` if `dst.Elem()` can not be set (`CanSet` returns `false`)
=> accounts/abi: fix set function

internal/ethapi/transaction_args_test.go
This fixes a regression which resulted from combining #25459 and #25197.
=> internal/ethapi: fix build regression

cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/transaction.go, eth/fetcher/tx_fetcher.go
This PR makes it so we'll sleep a bit when processing transactions, to avoid consuming too much resources
=> eth/fetcher: don't spend too much time on transaction inclusion

cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/transaction.go, eth/fetcher/tx_fetcher.go
Seems there's some flakyness in the behavior in this PR, postponing it till the next release.
=> Revert "eth/fetcher: don't spend too much time on transaction inclusion"

core/blockchain_reader.go, eth/downloader/skeleton.go
Currently the snap sync header insertion runs concurrently with the body/receipt insertion. In case of a failure, the header inserter spins down and rolls back the head of the chain. However, the body inserter might be running ocncurrently, ending up in a few unexpected items in the database. This should be fixed separately.
However, the presence of a spurious block body/receipt in the database can cause the old legacy sync to very rarely crash in the ancestor lookup, and can cause the new beacon sync to almost always hang and loop on an error. This PR adds an additional check that in both scenarios, a block is only considered present if all header, body and receipt is available. Whislt this is a tiny extra database read, it ensures that the two entity types (headerchain, blockchain) can …
=> core, eth/downloader: handle spurious junk bodies from racey rollbacks

core/state/statedb_test.go, trie/database.go
The trie commit rework PR made an unfortunate assumption (https://github.com/ethereum/go-ethereum/pull/25320/files#diff-8348a172e9fd3d3eb93c445d4ca58b8753b0f6d626c7af7db3b30b820d0788daR772) that the flush order doens't matter across storage tries and the account trie.
Unfortunately, this is false, because even though we do reference counting internally, the trie dirty cache drips trie nodes to disk when it's full, and the drip order is the insertion order. If the insertion order doesn't adhere to a strict child -> parent relationship, then we can end up with dangling storage trie nodes in the dirty cache, and missing subtries on disk.
As long as Geth keeps running, ll is fine because the dirty cache won't just flat out drop the data, and will eventually leak it to disk. But on shutdown it …
=> core/state, trie: fix trie flush order for proper pruning

consensus/beacon/consensus.go
This PR surfaces errors in two places where we previously ignored it.
=> consensus/beacon: don't ignore errors

internal/ethapi/api.go, internal/web3ext/web3ext.go
~~(waiting for spec to be merged: https://github.com/ethereum/execution-apis/pull/247)~~
Some small fixes to get the existing debug methods to conform to the spec. Mainly dropping the encoding information from the method name as it should be deduced from the debug context and allowing the method to be invoked by either block number or block hash. It also adds the method `debug_getTransaction` which returns the raw tx bytes by tx hash. This is pretty much equivalent to the `eth_getRawTransactionByHash` method.
=> internal/ethapi: rename debug getters to match spec

docs/_interface/consensus-clients.md
A proposed link update that gets users one click closer to the steps they need to take to configure Prysm with Geth :)
=> Update Prysm's link -> point to the Quickstart that includes Geth config instructions

cmd/devp2p/nodesetcmd.go, core/error.go, core/state/snapshot/difflayer.go, core/tx_noncer.go, p2p/discover/v4wire/v4wire.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
=> chore: remove duplicate word in comments

docs/_interface/peer-to-peer.md
Replaces outdated information about defining static and trusted nodes. 
Relates to issue #25593
=> docs: update info on static/trusted nodes in p2p docs

cmd/geth/config.go, cmd/geth/dbcmd.go
The legacy receipt detector produced a false positive when there were no non-empty receipts in the db.
Fixes #25498
=> cmd/geth: fix legacy receipt detection for empty db

build/ci.go, build/update-license.go
This PR surfaces two ignored errors.
=> build: fix ignored errors

ethclient/ethclient.go, ethclient/gethclient/gethclient.go
This PR adds support for using the strings `"finalized"` and `"safe"` in `ethclient`.
`"latest"` and `"pending"` have long been supported, but there's a small gap given these two new concepts.
=> ethclient: add 'finalized' and 'safe' block numbers

node/jwt_handler.go
`http.StatusUnauthorized` seems more suitable.
Explained in RFC-9110, Forbidden is... 
If authentication credentials were provided in the request, the server considers them insufficient to grant access.
But jwt_handler failure cases are failed in authorization process.
what i referenced)
RFC-9110 [401 Unauthorized](https://www.rfc-editor.org/rfc/rfc9110.html#name-401-unauthorized), [403 Forbidden](https://www.rfc-editor.org/rfc/rfc9110.html#name-403-forbidden)
=> node: change JWT error status to 401 Unauthorized

eth/catalyst/api.go
This PR changes the way we estimate time for the merge. There's a subtle error in the current algorithm
Consider the case where `2` headers are used for the estimation, rather than `64`. In that case, the difficulties for both blocks will be added, and the time between the two blocks. So the estimate will be based on `2 block difficulties / 1 block period`. 
So the current algo is based on `64 difficulties / 63 block periods`, over-estimating the difficulty per second.
Aside from that, I made it use `types.Header`s instead of blocks (easier on the db), got rid of some indentation, and made it never print out an estimate of `0` (which would happen in `PrettyAge` when time is below `1 second`.)
=> eth/catalyst: adjust eta for themerge

mobile/geth.go
Successfully created node `rawStack` should be closed before failing with other error, otherwise consecutive retry attempts to call `NewNode()` will fail with `datadir already used by another process`
=> mobile: close node on error

graphql/graphql.go
As part of #25459 I made a change so that graphql's tx log query goes through the usual filter system so it benefits from the newly added cache. However the filter system only handles logs on the block level, not tx level and I didn't select logs based on txindex which caused a regression.
Fixes #25583
=> graphql: return correct logs for tx

trie/secure_trie.go
It's a trivial PR to hidden the error log when the trie node is not found in the database. The idea for this change is for all `TryXXX` functions, the error is already returned and we don't need to fire a log explicitly. 
Recently there are a few tickets #25613 #25589 reporting that the trie nodes are missing because of `debug.SetHead`. The root cause is after resetting, the chain rewinds to a historical point and re-imports the blocks on top.
Since the node is already synced and started to accept transactions previously, these transactions are still kept in the txpool and verified by txpool with a *live state*. This live state is constructed based on the live trie database, which is changed fast by node referencing and de-referencing. 
Unfortunately, when we construct a live state(like …
=> trie: cleanup stateTrie

core/state/trie_prefetcher.go
This PR avoids a panic for copying nil trie.
=> core/state: filter out nil trie for copy

eth/protocols/snap/sync.go
This is the (hopefully) final atttempt to fix the problems that we are seeing on the azure bootnodes: nodes with a large amount of peers, but somewhat slow IO, which never finish the trie healing phase. 
Initially, I thought the error was that the internal queueing made the _already delivered_ responses time out, in our in-box, so to say. However, close inspection showed that that was not the case -- we cancel the timeout-function before we try to send on the channel which blocks further execution. 
But even though the code said one thing, the charts were kind of insistent that "No, actually, that's precisely what is happening". 
Luckily, I borrowed @karalabe's brain for a bit, which got the problem figured out. Yes, we do cancel the timeout, but we **also set the peer to idle**. Thus, …
=> eth/protocols/snap: fix problems due to idle-but-busy peers

docs/_interface/pruning.md
Adds a page with brief instructions for pruning a geth node.
Also intended for use on new site.
=> docs: add page on pruning a geth node

mobile/geth.go
This PR fixes a regression introduced by [#25459](https://github.com/ethereum/go-ethereum/pull/25459)
Removal of the following three lines makes `eth_subscribe("newHeads")` etc. no longer available on mobile platforms: https://github.com/ethereum/go-ethereum/pull/25459/files#diff-9443f03e7c706b082dc81e74820140747d7ca8afa3ff894930fd4f56495ad7c9L301-L303
=> mobile: register filter APIs

cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/transaction.go, eth/fetcher/tx_fetcher.go
This PR undoes the revertal by https://github.com/ethereum/go-ethereum/pull/25567, and restores https://github.com/ethereum/go-ethereum/pull/25524
=> eth/fetcher: throttle peers which deliver many invalid transactions

rpc/json.go, rpc/subscription_test.go, rpc/testdata/invalid-badversion.js
According to https://www.jsonrpc.org/specification,
`jsonrpc` in JSON-RPC 2.0 Request object  must be exactly "2.0".
In now, 
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1.11}' http://localhost:8545
<-- {"jsonrpc":"2.0","id":1.11,"result":"2757"}
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"geth","method":"net_version","params":[],"id":1.11}' http://localhost:8545
<-- {"jsonrpc":"2.0","id":1.11,"result":"2757"}
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2411.0","method":"net_version","params":[],"id":1.11}' http://localhost:8545
<-- {"jsonrpc":"2.0","id":1.11,"result":"2757"}
curl -X POST -H "Content-Type: application/json" --data …
```
=> rpc: check that "version" is "2.0" in request objects

eth/tracers/js/goja.go
All fields related to gas must be represented as uint64. Depth is
internally tracked as int, so it makes sense to also store it as int.
=> eth/tracers/js: fix integer types in log object

core/state/database.go, core/state/iterator_test.go, core/state/snapshot/generate_test.go, core/state/statedb.go, core/state/sync_test.go, light/trie.go, trie/database.go
This PR drops `DiskDB` function of the `trie.Database` for cleanup.
=> core, light, trie: remove DiskDB function from trie database

core/vm/evm.go, core/vm/jump_table.go, core/vm/opcodes.go
See: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4399.md
> This EIP supplants the semantics of the return value of existing DIFFICULTY (0x44) opcode and renames the opcode to PREVRANDAO (0x44).
=> core/vm: rename RANDOM to PREVRANDAO

trie/committer.go, trie/database.go, trie/secure_trie.go, trie/trie.go
This PR includes minor updates to comments in trie/committer that reference insertion to the db, and adds an `err != nil` check for the return value of `preimages.commit`.
Thanks for having a look.
=> trie: update comments + err check for preimages

eth/protocols/snap/sync.go
During initial snap sync, after we finish retrieving the snapshot chunks (across multiple pivot points), we need to go back and heal any faults that may have occurred (at the boundaries of snapshot chunks from different pivots; or state updates made to already downloaded state segments). This is the healing phase of snap sync, and it's essentially the old "fast sync", where we keep expanding the root state hash (via network downloads) until we hit existing nodes on all paths.
This trie expansion is primarily driven depth first to minimize the amount of memory needed during the phase. However, the downloader also does aggressive concurrency, where all peers are assigned tasks. These two notions unfortunately conflict a bit. Since expansion starts from the root, aggressive concurrency will …
=> eth/protocols/snap: throttle trie heal requests when peers DoS us

p2p/msgrate/msgrate.go
The `p2p` msgrate tracker is a thing which tries to estimate some mean round-trip times. However, it did so in a very curious way: if a node had 200 peers, it would sort their 200 respective `rtt` estimates, and then it would pick item number `2` as the `mean`. So effectively taking `third fastest` and calling it mean. This probably works "ok" when the number of peers are low (there are other factors too, such as `ttlScaling` which takes some of the edge off this) -- however when the number of peers is high, it becomes very skewed. 
Also, note: the peers that fail to deliver within the allotted time are _not discarded_ (at least if we're talking snap protocol). When they finally deliver, their response will be discarded, and they will be given a new task -- presumably failing again, thus …
=> p2p/msgrate: be more lenient when calculating 'mean'

docs/_rpc/server.md
Adds short paragraph about the Engine API to rpc/server.
Will also be included in new site.
@MariusVanDerWijden
=> docs: add engine-api section to rpc/server.md

core/tx_pool.go
Small changes to reduce the number of map resizing.
=> core: preallocate map in tx_pool

cmd/geth/main.go, cmd/geth/verkle.go, cmd/utils/flags.go, go.mod, go.sum
Verkle tree implementations are picking up pace, with Erigon working on a conversion tool. While verkle tree conversion is not yet ready to be merged in geth, the verification utilities are, and can be used to verify a conversion produced by Erigon.
This implements two commands:
* `geth verkle verify <root commitment>` that takes the root commitment of a post-conversion (verkle) tree, and recursively loads all the children of a tree node from the root, in order to ensure that all the nodes in the tree were saved in the database. This is analoguous to traversing an entire patricia trie. 
* `geth verkle dump`, a debugging tool that, given a set of keys, will create a representation of the verkle tree with these keys expanded.
=> cmd/geth: add a verkle subcommand

node/rpcstack.go
The HTTP server was always force closing with `HTTP server graceful shutdown timed out` because we didn't check that the error was not `nil`
=> node: fix HTTP server always force closing

les/catalyst/api.go
This method is missing in light client mode and breaks consensus clients that require a valid response.
=> les/catalyst/api: add support for ExchangeTransitionConfigurationV1

params/config.go
We passed the terminal total difficulty on block 
```
> eth.getBlock(15537394).hash
"0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7a38d72842b762076a664"
```
=> params: set TerminalTotalDifficultyPassed to true

crypto/bls12381/g1.go
Documentation of g1.Affine function was incorrect and appeared to be accidentally copied from the g1.Add function.
=> crypto/bls12381: docfix of g1 Affine

internal/ethapi/api.go
Fixes #25747.
The `key` parameter in `eth_getStorageAt` and `eth_getProof` currently uses `common.HexToHash` to convert the input string to `common.Hash`. This method disregards any errors and simply returns the decoded bytes up until the error. This can cause the RPC to return a different key than the user requested without error.
This PR changes the decoding method to use `hexutil.Decode`. This allows us to fail the request if the hex encoding is invalid. Since it only decodes to a `[]byte`, there is also a bound check to ensure the hex string is less than 32 bytes.
I have included a few tests in the `execution-apis` repo which will be pulled into `hive2`: https://github.com/ethereum/execution-apis/pull/305/files
Before:
```
>> …
```
=> internal/ethapi: return error when requesting invalid trie key

core/badblock.go, core/blockchain.go, les/client.go, params/config.go
This is more of an aesthetic preference, but I noticed that @s1na [also mentioned](https://github.com/ethereum/go-ethereum/pull/24904#issuecomment-1157614159) this issue so I thought I would propose it.
Before:
```console
########## BAD BLOCK #########
Chain config: Chain ID:  1 (mainnet)
Consensus: Ethash (proof-of-work)
Pre-Merge hard forks:
- Homestead:                   0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/ma
innet-upgrades/homestead.md)
- Tangerine Whistle (EIP 150): 0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/ma
innet-upgrades/tangerine-whistle.md)
- Spurious Dragon/1 (EIP 155): 0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/ma
innet-upgrades/spurious-dragon.md)
- …
```
=> core: add more compact summary of chain config for bad blocks

core/blockchain.go, internal/version/vcs_fallback.go, internal/version/vcs_go1.18.go, internal/version/version.go
This fixes the build with Go 1.17, which does not have BuildInfo.Settings yet.
=> core: move build version reading to its own package

core/rawdb/chain_iterator.go
Currently if a user has a finite tx lookup limit, they will see an "unindexing" info level log each time a block is imported. This information might help a user understand that they are removing the index each block and some txs may not be retrievable by hash, but overall it is generally more of a nuisance than a benefit. This PR downgrades the log to a debug log.
=> core/blockchain: downgrade tx indexing and unindexing logs 

eth/tracers/api.go
Currently, trace configs (introduced in [#25430](https://github.com/ethereum/go-ethereum/pull/25430)) don't work for the function `TraceCall`. This PR fixes it.
=> eth: fix trace config for `TraceCall`

eth/catalyst/api.go, eth/catalyst/api_test.go
Sometimes we get stuck on db compaction, and the CL re-issues the "same" command to us multiple times. Each request get stuck on the same place, in the middle of the handler. 
Eventually, we handle the requests in order. And it seems that we actually do reprocess each block, looking at the elapsed metric.
This means that if we're already under heavy pressure/load, and do a lot of compaction, then we're also doing extra work by chugging through the upcoming blocks over and over again.
This PR fixes it by making the entire `NewPayloadV1` mutex:ed.
=> eth/catalyst: add locking around newpayload

eth/catalyst/api_test.go
This PR makes the catalyst api tests run in ~1.5s instead of 8s.
=> eth/catalyst: make tests run faster

cmd/utils/flags.go
Currently, geth command line can't expand the argument such as `--authrpc.jwtsecret=~/.geth/jwt.secret`, use `flags.DirectoryFlag` instead
=> cmd/utils: make --authrpc.jwtsecret a DirectoryFlag

eth/protocols/snap/sync.go
A lot of users on our discord have been under the impression that their node is synced, and wondering why it is emitting "State healing" messages. In general, not understanding wether it is sync**ing*** or sync**ed**.
This PR tries to clarify that. 
cc @fjl
=> eth/protocols/snap: make log messages more clear that sync is ongoing

p2p/discover/v4_udp_test.go, p2p/dnsdisc/client_test.go, p2p/simulations/examples/ping-pong.go, p2p/simulations/http_test.go
There are four potential goroutine leaks in p2p tests.
1. In func `TestUDPv4_findnodeMultiReply` in `p2p/discover/v4_udp_test.go`, sending to chan `errc` is blocked forever on [L320](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/p2p/discover/v4_udp_test.go#L320) when `select` selects `result` on [L350](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/p2p/discover/v4_udp_test.go#L350) or `time.After` on [L357](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/p2p/discover/v4_udp_test.go#L357) and sending to `resultc` is blocked forever on [L322](https://github.com/ethereum/go-ethereum/blob/2b0d0ce8b0a02634b90b02bc038523eacd2b220a/p2p/discover/v4_udp_test.go#L322) when `select` …
=> p2p: add channel buffers to avoid goroutine leaks in tests

build/ci.go, cmd/abigen/main.go, cmd/checkpoint-admin/main.go, cmd/clef/main.go, cmd/devp2p/main.go, cmd/ethkey/main.go, cmd/evm/main.go, cmd/faucet/faucet.go, cmd/geth/config.go, cmd/geth/main.go, cmd/geth/misccmd.go, cmd/p2psim/main.go, internal/flags/helpers.go, internal/version/vcs_fallback.go, internal/version/vcs_go1.18.go, internal/version/version.go
This changes the CI build to store the git commit and date into package internal/version instead of package main. Doing this essentially merges our two ways of tracking the go-ethereum version into a single place, achieving two objectives:
- Bad block reports, which use version.Info(), will now have the git commit information even when geth is built in an environment such as launchpad.net, where git is unavailable.
- For geth builds created by `go build ./cmd/geth` (i.e. not using `go run build/ci.go install`), the git information stored by the go tool is now used in the p2p node name as well as in `geth version` and `geth version-check`.
=> internal/version: use gitCommit/gitDate injection in version handling code

cmd/abigen/main.go, cmd/abigen/namefilter.go, cmd/abigen/namefilter_test.go
When using combined-json input, the contract names generated by
`compiler.ParseCombinedJSON` are the fully qualified contract names,
that is, are of the form `<solFilePath>:<type>`. So when checking for
excluded types, the type name has to be split from the f.q. name.
If the contract name is of the short version `<type>`, then the behavior
is as before.
=> cmd/abigen: change --exc to exclude by type name

cmd/geth/snapshot.go, cmd/utils/flags.go, core/blockchain.go, core/state/pruner/pruner.go, core/state/snapshot/journal.go, core/state/snapshot/snapshot.go, tests/state_test_util.go
This PR cleans up the configurations for pruner and snapshotter by passing a config struct.
And also, this PR disables the snapshot background generation if the chain is opened in "read-only" mode. The read-only mode is necessary in some cases. For example, we have a list of commands to open the etheruem node in "read-only" mode, like `export-chain`. In these cases, the snapshot background generation is non expected and should be banned explicitly.
=> all: clean up the configs for pruner and snapshotter

cmd/geth/main.go, cmd/puppeth/module_node.go, cmd/puppeth/wizard_node.go, cmd/utils/flags.go, cmd/utils/flags_legacy.go
This PR fully removes the ``--miner.gastarget`` flag, as previously it was only hidden from the ``geth --help`` command, but could still be used.
=> cmd/puppeth, cmd/utils: finalize removal of gasTarget flag

cmd/faucet/README.md
=> cmd/faucet: fix readme typos

core/tx_pool.go
Fixes both https://github.com/ethereum/go-ethereum/issues/25869 and https://github.com/ethereum/go-ethereum/issues/25870 actually
=> core: fix datarace in txpool, fixes #25870 and #25869 

docs/_interface/Managing-your-accounts.md
refreshes the "Account Management" page under "Using Geth".
In particular:
- reorganizes the material into a more logical sequence (IMO) 
- adds important information about when and why account unlocking is forbidden (i.e. -http flag)
- includes account creation, importing from private keys, unlocking from both command line and javascript console. 
- adds new information about the difference in unlocking scope between `eth.sendTransaction` and `personal.unlockTransaction`
=> update account management page

eth/downloader/queue.go, les/downloader/queue.go
When `stale` is true, `res` will be nil, in that case `reconstruct` will report nil pointer error.
=> eth/downloader, les/downloader: fix subtle flaw in queue delivery

core/vm/interpreter.go
current code logic of `for...range...`check to delete elements in slice is not correct, would skip checking the element next to the element be deleted of which error was detected.
```
for i, v := range slice{
// check slice[i]
slice = append(slice[:i], slice[i+1:]...)
}
```
backwards the index when delete element from a slice
```
for i:=0; i<len(slice); i++{
// check slice[i]
slice = append(slice[:i], slice[i+1:]...)
i--
}
```
`core/vm/interpreter.go : NewEVMInterpreter(...)`
=> core/vm: correct logic for eip check of NewEVMInterpreter

cmd/geth/chaincmd.go, cmd/utils/flags.go, core/genesis.go
`geth dumpgenesis` current does not respect the content of the data directory. Instead, it outputs the genesis block created by command-line flags. This PR fixes it to read the genesis from the database, if the database already exists.
=> cmd/geth: make dumpgenesis command load genesis from the datadir if it exists

docs/_interface/peer-to-peer.md
Updates the "connecting to network page" to clarify that Geth alone (i.e. without consensus client) will not work on Goerli, Sepolia and Mainnet .
=> docs: update networks page for post-merge

eth/api_backend.go, internal/ethapi/api.go
Currently the 2nd return value of `EthAPIBackend.GetEVM` does nothing, this PR aligns it with `LesApiBackend.GetEVM` to do something a bit more useful and fixed the handling of a calling site.
=> eth: return state error via GetEVM

eth/downloader/skeleton_test.go
This PR tries to fix these which fail on CI from time to time: 
```
ok  	github.com/ethereum/go-ethereum/crypto/signify	0.079s	coverage: 83.8% of statements
ok  	github.com/ethereum/go-ethereum/eth	12.955s	coverage: 28.4% of statements
ok  	github.com/ethereum/go-ethereum/eth/catalyst	2.262s	coverage: 63.4% of statements
--- FAIL: TestSkeletonSyncRetrievals (1.84s)
skeleton_test.go:830: test 6, mid state: dropped peers mismatch: have 0, want 1
FAIL
coverage: 76.2% of statements
FAIL	github.com/ethereum/go-ethereum/eth/downloader	160.461s
?   	github.com/ethereum/go-ethereum/eth/ethconfig	[no test files]
```
I think the err above simply happens because the CH machines are too slow, we need to give them some more time to reach the desired state. This PR bumps a timeout from one to two …
=> eth/downloader: make flakey test less flakey

ethclient/gethclient/gethclient.go, ethclient/gethclient/gethclient_test.go
If the `code` property is not present in the state overrides, it should be skipped or set to `null` on marshal. Because of the type of the property `hexutil.Bytes` the empty slice marshals to "0x" and the request fails.
fixes #25615
=> ethclient/gethclient: fix bugs in override object encoding

eth/protocols/snap/sync.go, trie/sync.go
This PR tries to prevent making tiny writes, by only performing the batch-write if the accumulated data is large enough to be meaningful.
The current code, at worst case, would make a tiny batch-write on each trienode response.
=> trie, eth/protocols/snap: less tiny db-writes during trie-healing

tests/state_test.go
I think it's good to have `mgas/s` metric in EVM benchmarks, so anyone could compare geth's implementation with e.g. [evmone](https://github.com/ethereum/evmone)'s which has [the same reporting format](https://github.com/ethereum/evmone/blob/4ab4b4b928ed85fa6eea58cc135f31ab1f1ba8fa/test/bench/helpers.hpp#L145).
Ideally, we would be able to have all EVM implementations benchmarked against one metric that's comparable regardless of implementation language.
=> tests: report mgas/s metric in evm benchmarks

eth/tracers/native/prestate.go
Signed-off-by: Delweng <delweng@gmail.com>
=> eth/tracers: fix the issue of stateobject modified

internal/ethapi/api.go
This PR is for fixing bug.
This problem is causing problems everywhere using the decodeHash() function.
In some cases, the length of the string s, that is, the length of the hash, is odd like (0x6). 
In this case, the request fails with the following message.
"unable to decode storage key: hex string invalid"
In the case I experienced, it always failed to print out the above message when calling a function in a forked network through a hardhat.
=> internal/ethapi: handle odd length hex in decodeHash

core/blockchain.go, core/blockchain_test.go, core/rawdb/accessors_chain.go, core/rawdb/chain_iterator.go
This PR reworks tx indexer a bit.
Compare with the original version, one scenario is not handled any more: Users upgrade nodes from legacy geth without indexer support. It's not true anymore, tx indexer is introduced in 2020 and there are a few hardforks introduced since that, we can assume all Geth nodes have tx indexer supported right now.
Therefore we can simplify the tx indexer logic a bit:
- If the tail flag is not present, it means node is just initialized may or may not with an ancient store attached. In this case all blocks are regarded as unindexed
- If the tail flag is present, it means blocks below tail are unindexed, blocks above tail are indexed
This change can also address some weird cornercase that after crash indexer may not work.
=> core: rework tx indexer

accounts/abi/argument.go, accounts/abi/unpack.go
Returns the non-nil error before calculating next virtualArgs
=> accounts/abi: return toGoType error immediately

accounts/abi/bind/template.go
This PR should close the issue originally described in #22269, where useless JSON parsing happened on every contract bind call. The solution of this issue merged in #22583 was not complete and only fixed issue for deploy, but not in bind. 
I also faced with this useless JSON parsing during contract calls and overhead becomes noticeable when need to call contract for different addresses.
=> accounts/abi/bind: parse ABI once on bind

internal/flags/helpers.go
This PR fixes an issue related to how subcommands are hoisted into the global scope. 
Here's an example app: https://gist.github.com/holiman/5ed50fc9dcf44fd661abdb91a59137fe#file-main-go . This has a stringslice argument, and shows the corruption that happens when that stringslice is migrated across scopes: 
```
[user@work cmdtest]$ ./cmdtest  --header aa --header bb --url foo connect
invoked via subcommand
ctx.IsSet(HttpHeaderFlag.Name): true
0: [aa bb]
ctx.IsSet(UrlFlag.Name): true
foo
```
The value is migrated as the literal string `[aa bb]`, which is the string-equivalent of the stringslice. Unfortunately, the backing type, `StringSlice` cannot convert this back to a proper stringslice -- it expects input to be on the form `aa,bb`. 
This PR fixes it by detecting whether a given type …
=> internal/flags: fix issue with stringslice migration

index.html, static/styles/custom/common.css
Mascot on homepage was rendering too wide because image height and width were both hardcoded. This removes the hardcoded values which should enable the image to dynamically size.
=> docs: fix mascot sizing on homepage

cmd/geth/attach_test.go, cmd/geth/consolecmd.go, cmd/utils/flags.go, ethdb/remotedb/remotedb.go
This PR makes it possible to set custom headers. Example: 
```
$ source setheaders && go run . attach -H "CF-Access-Client-Id: $CFID" -H "CF-Access-Client-Secret: $CFSEC"  https://rpc.mainnet.ethpandaops.io
Welcome to the Geth JavaScript console!
instance: erigon/2022.09.1/linux-amd64/go1.18.5
```
Error handlng: 
```
go run . attach -H "a bad header"  https://rpc.mainnet.ethpandaops.io
Fatal: invalid http header directive: "a bad header"
```
=> cmd/geth, cmd/utils: geth attach with custom headers

cmd/devp2p/internal/ethtest/snap.go, eth/protocols/snap/handler.go
This PR makes it so that the snap server responds to trie heal requests when possible, even if the snapshot does not exist. The idea being that it might prolong the lifetime of a state root, so we don't have to pivot quite as often.
=> eth/protocols/snap: serve snap requests when possible

cmd/geth/main.go, cmd/utils/flags.go, eth/catalyst/api.go, eth/catalyst/api_test.go, eth/ethconfig/config.go, miner/miner.go, miner/worker.go, miner/worker_test.go
This PR adds a timeout mechanism for building sealing block. 
Once The Merge is conducted, block has to be prepared in the period of a slot. If we encounter some transactions that perform particularly expensive, instead of spending a lot of time filling the block, we would rather return a block that is not full, but it can be created at the specified time.
The timeout value should be chosen aligned with consensus spec.
TODO
=> eth, miner: add timeout for building sealing block

core/state_transition.go
I think https://github.com/ethereum/go-ethereum/pull/25924 accidentally broke master, for some reason the linter complains that the state_transition is not goimport:ed. This seems to solve it. 
I'm just a monkey pushing buttons here, no idea how or why
=> core: fix linter complaint

eth/tracers/api.go, eth/tracers/tracker.go, eth/tracers/tracker_test.go
This PR introduces a new mechanism in chain tracer for preventing creating too many trace states.
The workflow of chain tracer can be divided into several parts:
- state creator generates trace state in a thread
- state tracer retrieves the trace state and applies the tracing on top in another thread
- state collector gathers all result from state tracer and stream to users
It's basically a producer-consumer model here, while if we imagine that the state producer generates states too fast, then it will lead to accumulate lots of unused states in memory. Even worse, in path-based state scheme it will only keep the latest 128 states in memory, and the newly generated state will invalidate the oldest one by marking it as stale.
The solution for fixing it is to limit the speed of state …
=> eth/traces: add state limit

core/bloombits/scheduler_test.go
This PR brings down the time on Windows from ~70 seconds down to 2-3 seconds. The windows sleep duration cannot go below ~15ms, it seems.
=> core/bloombits: speed up windows-test

cmd/geth/consolecmd_test.go, core/tx_pool.go
=> cmd/geth, core: fix typo in comment

eth/protocols/eth/handlers.go
Technically "decode" could be read as "read", "decipher" or "understand", too, but calling it "encode" clearly specifies which operation failed.
=> eth/protocols/eth: Typo in log message

cmd/geth/chaincmd.go, cmd/geth/exportcmd_test.go, cmd/utils/flags.go, core/genesis.go, core/rawdb/accessors_metadata.go
A hive-test started failing:
Git bisect showed that it started failing at this [PR](https://github.com/ethereum/go-ethereum/pull/22396). 
This PR fixes the problem. 
These are the hive-logs on the geth-instance during the test run
- An instance where it does [not work](https://github.com/ethereum/go-ethereum/files/9791984/non-working.log)
- An instance with this PR, where the test [works again](https://github.com/ethereum/go-ethereum/files/9791983/working_again.log).
When it works, the logs emit these messages as the blockchain is shutting down: 
```
DEBUG[10-15|11:53:54.838] Inserted new block                       number=999 hash=0e70e0..67a424 uncles=0 txs=0   gas=0       elapsed="275.541µs>
DEBUG[10-15|11:53:54.839] Journalled generator progress            progress=done …
```
=> cmd/utils: enable snapshot generation in import-mode

consensus/clique/snapshot.go, core/rawdb/database.go, core/rawdb/schema.go, les/handler_test.go, les/server_handler.go, light/postprocess.go
put the db key prefix into one file
=> core/rawdb: refactor db key prefix

core/rawdb/freezer_table.go
Previously if a freezer table is opened in read-only mode, the corresponding meta file of this table will still be opened in read-write mode. It's mostly for backward-compatibility for legacy node.
However the meta file has been shipped for a few months and all nodes must have initialized the meta files because of the merge. Now we can ensure that if the table is existent, the corresponding meta file must be existent as well and we can drop this ugly hack.
=> core/rawdb: open meta file in read only mode

docs/_interface/sync-modes.md
adds a bit more detail to help users understand how their node will behave during state healing
=> docs: add detail to sync modes page

docs/_interface/JavaScript-Console.md, docs/_interface/Private-Network.md
`geth attach --datadir . data/geth.ipc --exec admin.nodeInfo.enr` results to
```
Fatal: invalid command-line: too many arguments
```
Putting `--exec` param before the ipc socket could fix the problem.
=> docs: fix attach --exec

docs/_interface/consensus-clients.md, docs/_interface/sync-modes.md
adds some information about checkpoint sync to the consensus client and sync-modes pages
=> docs: add info on checkpoint sync

docs/_developers/dns-discovery-setup.md, docs/_interface/Command-Line-Options.md, docs/_interface/Private-Network.md, docs/_interface/consensus-clients.md, docs/_rpc/ns-eth.md
Removes references to deprecated testnets across site, persists goerli/sepolia.
=> docs: purge references to rinkeby and ropsten

core/blockchain.go, core/txpool/txpool.go, core/types/block.go, core/types/block_test.go, core/types/transaction.go, core/types/transaction_marshalling.go, core/types/transaction_test.go, eth/downloader/queue.go, eth/protocols/eth/broadcast.go, les/downloader/queue.go
The `eth/68` protocol intends to pass the tx sizes along with transaction announces. For that however, we need the value to be accurate. This PR fixes an off by one size error for typed transactions. It also changes the returned type from `common.StorageSize`, which is a `float64` wrapped with nice formatting methods into an accurate `uint64`. Although at the expected sizes it's not relevant whether it's float or int, the latter seems more accurate.
The PR also does the same size type change for blocks, mostly because that number is also accurate, so might as well signal it being such via the function declaration. The Size method for headers and receipts however remain unchanged (`common.StorageSize`) since those are approximations only.
=> core, eth: for types with accurate size calcs, return uint64, not float

build/ci.go
Before:
```
$ make ios
env GO111MODULE=on go run build/ci.go xcode --local
\>>> /opt/local/lib/go/bin/go install -mod=readonly golang.org/x/mobile/cmd/gomobile golang.org/x/mobile/cmd/gobind
\>>> /Users/Jakub/Projects/DEVELOPMENT/MAC/TheChain/go-ethereum_official/build/bin/gomobile bind -ldflags "-s -w" --target ios -v github.com/ethereum/go-ethereum/mobile
go: unsupported GOOS/GOARCH pair darwin/arm
/Users/Jakub/Projects/DEVELOPMENT/MAC/TheChain/go-ethereum_official/build/bin/gomobile: darwin-arm: go build -tags ios -v -ldflags -s -w -buildmode=c-archive -o /var/folders/2l/srt5z_nx559gqfgwf_0c__8r0000gp/T/gomobile-work-3436797179/geth-arm.a gobind failed: exit status 2
util.go:48: exit status 1
exit status 1
make: *** [ios] Error 1
$
```
After:
```
$ make ios
env GO111MODULE=on go run …
```
=> build: make ios work again

core/vm/contracts.go
This PR changes the precompile to use a more optimized version of big.Int
=> core/vm: use optimized bigint

eth/filters/filter.go
This PR changes the `block` field in the filter to be a pointer, to disambiguate between empty hash and no hash
=> eth/filters: change filter block to be by-ref

core/blockchain.go, core/blockchain_test.go, core/rawdb/ancient_scheme.go, core/rawdb/ancient_utils.go, core/rawdb/database.go, core/state/snapshot/snapshot.go, core/state/state_object.go, core/state/statedb.go, trie/nodeset.go
This PR ports a few changes from PBSS
- ~The storage trie nodes of destructed contract will be marked as deleted~
- Fix the snapshot generator waiter in case the generation is not even initialized
- Refactor db inspector for ancient store
After the refactor, now inspector looks like 
```
+-----------------------+---------------------+------------+--------+
|       DATABASE        |      CATEGORY       |    SIZE    | ITEMS  |
+-----------------------+---------------------+------------+--------+
| Key-Value store       | Headers             | 576.00 B   |      1 |
| Key-Value store       | Bodies              | 44.00 B    |      1 |
| Key-Value store       | Receipt lists       | 42.00 B    |      1 |
| Key-Value store       | Difficulties        | 212.00 B   |      3 |
| Key-Value store …
```
=> core/rawdb: refactor db inspector for extending multiple ancient store

cmd/geth/main.go, cmd/utils/flags.go, eth/catalyst/tester.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go
This PR adds a parameter to startup, `--synctarget`. The `synctarget` flag is a developer-flag, that can be useful in some scenarios as a replacement for a CL node. It defines a fixed block sync target:
```
geth --syncmode=full --synctarget=./block_15816882.hex_rlp 
```
The `--synctarget` is only made available during `syncmode=full`. If we enable it for `syncmode=snap`, it would make geth capable of downloading block data, but geth would become stalled during state-sync due to the failure to move the pivot.
=> cmd, eth: implement full-sync tester

accounts/abi/type.go, accounts/abi/type_test.go
This is a follow-up PR for this one:https://github.com/ethereum/go-ethereum/pull/26043
=> accounts/abi: fixed bytes with size larger than 32 bytes is not allowed

docs/_interface/JavaScript-Console-Contracts.md, docs/_interface/JavaScript-Console.md
Adds a page on how to use the JS console to deploy and interact with a contract, Also removes examples from the original JS Console page that rely on `personal` namespace.
=> docs: add JS console contracts page

docs/postmortems/2021-08-22-split-postmortem.md
Removed parentheses in line 71 because line 80 doesn't have them either.
=> Fixed language inconsistency in docs

miner/worker_test.go
If NewBlockChain fails here, you would previously get a confusing panic later on in worker_test whose origin is non-trivial to diagnose. For example I encountered the output below when working on an eip-4844 related change:
> --- FAIL: TestGenerateBlockWithBlobsAndImportEthash (0.00s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x809cb4]
>
> goroutine 75 [running]:
> testing.tRunner.func1.2({0x8e19e0, 0xebe080})
> 	/usr/local/go/src/testing/testing.go:1389 +0x24e
> testing.tRunner.func1()
> 	/usr/local/go/src/testing/testing.go:1392 +0x39f
> panic({0x8e19e0, 0xebe080})
> 	/usr/local/go/src/runtime/panic.go:838 …
=> miner: fail early if core.NewBlockChain fails

rlp/decode_test.go, rlp/encode_test.go
This prevents producing an encoding of some struct that will fail to decode, as referenced in https://github.com/ethereum/go-ethereum/issues/26069
=> rlp: add more tests for nil pointer / optional field encoding

cmd/clef/main.go
Account listing is not currently available in Clef's CLI - it is only available using a Clef UI or by calling `eth.accounts` or `personal.listAccounts` which is being deprecated. 
This PR adds `clef listaccounts` as a Clef subcommand. 
The benefits of this are:
a) UX is better than having to implement a UI that can access the internal API, 
b) it is secure because the request requires explicit approval in Clef; 
c) it does not rely on a running Geth instance to handle calls to `eth.accoutns` - enables listing when Clef is used as standalone signer. 
Example:
```
>> ./clef listaccounts
...
INFO [10-31|15:47:12.847] Starting clef                            keystore=/home/user/.ethereum/keystore light-kdf=false
DEBUG[10-31|15:47:12.848] FS scan times …
```
=> cmd/clef add `listAccounts` to CLI

consensus/misc/eip1559.go, core/chain_makers.go, miner/worker.go, params/config.go, params/protocol_params.go
This PR changes geth to read the eip1559 params from the chain config instead of the globals.
This way the parameters may be changed by forking the chain config code, without creating a large diff throughout the past and future usages of the parameters.
Like with hardforks and testnets, geth can support different options at the same time, because the parameters are not hardcoded. This PR does not make the parameters configurable with new individual fields however, to follow the pattern where parameters are determined by hardfork/consensus-type. This PR does not introduce any new format or new branching logic.
See #25822 for context.
=>  params: make eip1559 params non-global

docs/_developers/devguide.md
Adds to the information on stack traces at `docs/developers/devguide.md`.
Addresses issue #20198
=> docs: update stacktrace info

accounts/abi/bind/base.go
if GasFeeCap and GasTipCap are specified no need to retrieve head
=> accounts/abi.bind: don't fetch head in transact unless required

docs/_interface/logs.md
Attempting to create a page that helps users interpret common console logs. In particular addresses:
1) how to configure logs - i.e. verbosity and redirecting to file
2) startup logs (for default config)
3) syncing logs (for default snap sync)
4) transaction logs (for simple eth transfer)
5) explaining commonly-queried logs 
Raising as a draft PR for now to see if Geth team have suggestions for messages that are commonly asked about by users or other important log messages I've overlooked.
=> docs: add page on log messages

docs/_interface/Managing-your-accounts.md
Updates account management page to:
1) Remove calls to methods in `personal` namespace
2) Prioritize Clef methods over `geth account <>` where possible
This is a first step to updating docs for `personal` namespace deprecation.
=> docs: update account management page to favour clef

cmd/clef/consolecmd_test.go, cmd/clef/main.go, cmd/clef/run_test.go
This adds `importraw` as a subcommand to clef. 
Walking the happy-path:
```
[user@work clef]$ go run . --suppress-bootwarn importraw ./hexkey
INFO [10-28|14:03:08.718] Starting clef                            keystore=/home/user/.ethereum/keystore light-kdf=false
DEBUG[10-28|14:03:08.719] FS scan times                            list="61.22µs" set="72.06µs" diff="6.886µs"
Please enter a password for the imported account
> 
-----------------------
Please repeat the password you just entered
> 
-----------------------
DEBUG[10-28|14:03:15.040] FS scan times                            list="78.702µs" set="74.598µs" diff="6.765µs"
Key imported:
Address 0x9160DC9105f7De5dC5E7f3d97ef11DA47269BdA6
Keystore file: /home/user/.ethereum/keystore/UTC--2022-10-28T12-03-13.976383602Z--9160dc9105f7de5dc5 …
```
=> cmd/clef: add importraw feature to clef

accounts/abi/abi.go
Printing some bytes as `string(...)` can create some non UTF-8 characters, which can mess up some log parsers (eg. Loki/Promtail/Grafana combo). I think a hex-string should be sufficient, which can easily be converted to `string` by the end user if needed.
=> accounts/abi: properly quote untrusted data in error message

p2p/discover/v5_udp.go, p2p/discover/v5_udp_test.go, p2p/enr/enr.go, p2p/enr/enr_test.go, rlp/raw.go, rlp/raw_test.go
Instead of using a limit of 3 nodes per message, we can pack more nodes into each message based on size. In my testing, this halves the number of sent NODES messages, because ENR size is usually < 300 bytes.
=> p2p/discover: improve discv5 NODES response packing

cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/transaction.go, cmd/devp2p/internal/ethtest/types.go
Adds the eth/68 protocol version to the devp2p test suite
=> cmd/devp2p/internal/ethtest: add support for eth/68

cmd/devp2p/internal/v4test/discv4tests.go
Nethermind is sometimes failing hive test `BondThenPingWithWrongFrom` because of sending `FindNode` instead of expected `Pong`. Sometimes `Pong` is our first response and then we are passing this test. As we were bonded before receiving `Ping`, we consider sending `FindNode` as acceptable. This PR is changing test `BondThenPingWithWrongFrom` to ignore received `FindNode` while waiting for `Pong` response.
I tested it and after changes from this PR we are always passing `BondThenPingWithWrongFrom`.
=> cmd/devp2p/internal/v4test: ignore FINDNODE in BondThenPingWithWrongFrom

eth/tracers/api.go, eth/tracers/logger/logger.go, eth/tracers/native/4byte.go, eth/tracers/native/call.go, eth/tracers/native/mux.go
Sometimes users might need the result of multiple tracers for a given tx. This PR introduces the `muxTracer` which allows you to do this. It takes in a list of tracers and their configs and returns each one's corresponding result with one run through the tx:
```console
> debug.traceTransaction('0xf8fd7bea3dc42ee81922584884d3f741e8e475ecccb75b0e4f2dad042061c723', { tracer: 'muxTracer', tracerConfig: { prestateTracer: { diffMode: true}, callTracer: null }})
{
callTracer: {
from: "0x2806a6d83218acc8b223063bd058957d38966a09",
gas: "0x0",
gasUsed: "0x5208",
input: "0x",
to: "0x2806a6d83218acc8b223063bd058957d38966a09",
type: "CALL",
value: "0x1"
},
prestateTracer: {
post: {
0x2806a6d83218acc8b223063bd058957d38966a09: {
balance: "0xffffffffffffffffffffffffffffffffffffffffffffffffffffef49bca6f9f7 …
```
=> eth/tracers: add multiplexing tracer

common/types.go
Many of the other types have a function to convert the type to a `big.Int` but the `Address` is missing this function. It is useful to be able to turn an `Address` into a `big.Int` when doing EVM-like computations natively in Go. Sometimes a Solidity `address` type is casted to a `uint256` and having a `Big` method on the `Address` type makes this easy.
Can follow up with tests if desired
=> common/types: add `Address.Big`

cmd/devp2p/keycmd.go
This adds two new commands which turn a node key file into a signed ENR or simply print the node ID.
Example: 
```
$ ./devp2p key to-id node1.key
b6eb0af089fc125d0f48746c938231c15e4737a72327194a7e351e42f60a54fc
$ ./devp2p key to-enr -ip 1.2.3.4 -udp 30304 node1.key 
enr:-Iu4QAUG3OoCOHQQ3Qe5XA8tuEPgyRg7xTTsLtG5SIThHgeXPa0ktpnrTE-gFXNYgOOUuUkWVpTqW-oqvzduUwGAwyCAgmlkgnY0gmlwhAECAwSJc2VjcDI1NmsxoQOWEd6Hlr9gtrdtEGeiSm5jXhFUyief-z5eG1FYgp4yAYN0Y3CCdl-DdWRwgnZg
$ ./devp2p enrdump enr:-Iu4QAUG3OoCOHQQ3Qe5XA8tuEPgyRg7xTTsLtG5SIThHgeXPa0ktpnrTE-gFXNYgOOUuUkWVpTqW-oqvzduUwGAwyCAgmlkgnY0gmlwhAECAwSJc2VjcDI1NmsxoQOWEd6Hlr9gtrdtEGeiSm5jXhFUyief-z5eG1FYgp4yAYN0Y3CCdl-DdWRwgnZg
Node ID: b6eb0af089fc125d0f48746c938231c15e4737a72327194a7e351e42f60a54fc
URLv4: …
```
=> cmd/devp2p: add more nodekey commands

graphql/service.go
https://github.com/ethereum/go-ethereum/issues/26026 as its proposed in this issue, I added the timeout
=> graphql: add query timeout to prevent dos attack

signer/core/cliui.go
PR #26082 added account listing to `OnSignerStartup` but did not consider the case where a user has a large number of accounts which would be annoying to display.
This PR updates `showAccounts()` so that if there are more than 20 accounts available the user sees the first 20 displayed in the console followed by: `First 20 accounts listed (N more available).` 
For example for a keystore with > 20 accounts the startup info looks as follows:
```
------- Signer info -------
* extapi_ipc : /home/user/.clef/clef.ipc
* intapi_version : 7.0.1
* extapi_version : 6.1.0
* extapi_http : n/a
------- Available accounts -------
0. 0xE70CAD05D0D54Ae3C9Fe5442f901E0433f9bd14B at keystore:///home/user/Code/go-ethereum/testdata/keystore/UTC--2022-10-31T15-45-59.185124924Z--e70cad05d0d54ae3c9fe5442f901e0433f9b …
```
=> cmd/clef: only print first N accounts on startup

core/vm/interpreter.go, core/vm/jump_table.go, core/vm/jump_table_test.go
=> core/vm: deep copy jumptable when enabling extra eips

common/lru/blob_lru.go, common/lru/blob_lru_test.go, core/state/database.go
Initial poc, one way to replace `fastcache` with a pretty simple LRU which does not require explicit closing. 
This is an alternative to https://github.com/ethereum/go-ethereum/pull/26071
=> core/state: replace fastcache code cache with gc-friendly structure

cmd/evm/internal/t8ntool/execution.go
This PR fixes a subtle bug in `t8n`. After this PR, `t8n` behaves like our state-test runner in this particular scenario: 
- After an empty block, 
- And the config is that there is a zero block reward, 
- And the coinbase did not previously exist, 
- And we're before EIP-158, 
- Then the coinbase should be touched, a.k.a brought into existence. 
Our state test runner handles that here: https://github.com/ethereum/go-ethereum/blob/master/tests/state_test_util.go#L266 
The t8n was meant to handle that exactly identical, but failed to do so. That's what's being fixed by this PR. 
Also related, the `miningReward` comes from this flag:
```golang
RewardFlag = &cli.Int64Flag{
Name:  "state.reward",
Usage: "Mining reward. Set to -1 to disable",
Value: 0,
}
```
cc @winsvega
=> cmd/evm: slight change in how t8n handles coinbase pre eip-158

eth/filters/filter_test.go
This PR fixes a benchmark-test which was made br0kken by  this commit: https://github.com/ethereum/go-ethereum/pull/25641/files#diff-dcfcc1778e0f2ab8820d4b00af81d5ce5209067a3a9b40af012d9d07b641a8e1R59  . 
Without this PR: 
```
[user@work go-ethereum]$ go test -run - -bench BenchmarkFilters  ./eth/filters
INFO [11-09|08:44:00.421] Allocated cache and file handles         database=/tmp/BenchmarkFilters672625565/001 cache=16.00MiB handles=16
INFO [11-09|08:44:00.423] Persisted trie from memory database      nodes=1 size=142.00B time="5.708µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
--- FAIL: BenchmarkFilters
filter_test.go:94: expected 4 logs, got 0
FAIL
exit status 1
FAIL    github.com/ethereum/go-ethereum/eth/filters     5.455s
FAIL
```
With this PR: 
```
[user@work …
```
=> eth/filters: fix failing benchmark-test

internal/debug/flags.go
This adds an option to direct log output to a file. This feature has been requested a lot. It's sometimes useful to have this available when running geth in an environment that doesn't easily allow redirecting the output.
=> internal/debug: add --log.file option

README.md, go.mod
This will allow use of generics and other new standard library APIs such as package `net/netip`.
=> go.mod: minimum Go version 1.18

eth/catalyst/api_test.go, eth/handler_eth_test.go
This is another PR to fix flaky tests, mostly due to built-in synchronicity requirements which do not work very well on the low-resource appveyor machines. 
Fix 1: 
```
--- FAIL: TestNewPayloadOnInvalidChain (0.14s)
api_test.go:604: payload should not be empty
```
Fix 2: 
```
--- FAIL: TestTransactionPropagation67 (1.76s)
handler_eth_test.go:455: sink 0: transaction propagation timed out: have 0, want 1024
INFO [11-10|03:48:40.490] Writing custom genesis block 
```
=> eth, catalyst: fix flaky tests

common/lru/blob_lru.go
This fixes a problem in the `SizeConstrainedLRU`. The SCLRU uses an underlying simple lru which is _not_ thread safe. 
During the `Get` operation, the recentness of the accessed item is updated, so it is _not_ a pure read-operation. Therefore, the mutex we need is a full mutex, not RLock. 
This PR changes the mutex to be a regular `Mutex`, instead of `RWMutex`, so a reviewer can at a glance see that all affected locations are fixed. 
Fixes: https://github.com/ethereum/go-ethereum/issues/26163
=> common/lru: fix race in lru

accounts/abi/bind/backends/simulated.go, eth/filters/api.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go, internal/ethapi/api.go, internal/ethapi/backend.go
This PR is an alternative to https://github.com/ethereum/go-ethereum/pull/26034. This PR keeps the internal objects as `*types.Transaction`, and mutates it into rpc.Transaction right before it's sent on the wire. 
At least I think it does, I haven't fully verified it (yet).
=> eth/filters: send rpctransactions in pending-subscription

rpc/server.go
When upgrading to mapset/v2 with generics, the set element type used in rpc.Server had to be changed to *ServerCodec because ServerCodec is not 'comparable'. While the distinction is technically correct, we know all possible ServerCodec types, and all of them are comparable. So just use a map instead.
=> rpc: fix connection tracking set in Server

ethclient/ethclient.go
=> ethclient: docs, fix misleading comment

cmd/evm/internal/t8ntool/execution.go, core/blockchain_test.go, core/chain_makers.go, core/state/journal.go, core/state/state_object.go, core/state/statedb.go, core/state/statedb_test.go, core/state/transient_storage.go, core/state_prefetcher.go, core/state_processor.go, core/state_transition.go, core/vm/eips.go, core/vm/instructions.go, core/vm/instructions_test.go, core/vm/interface.go, core/vm/opcodes.go, core/vm/runtime/runtime.go, eth/state_accessor.go, eth/tracers/api.go, les/state_accessor.go, miner/worker.go, tests/state_test.go
Implements `TSTORE` and `TLOAD` as specified by the following EIP:
https://eips.ethereum.org/EIPS/eip-1153
https://ethereum-magicians.org/t/eip-1153-transient-storage-opcodes/553
This PR includes test coverage of these opcodes.
We are interested in having this included as part of Shanghai, as talked about at the EIP panel at Devcon. There is general community support by application layer developers, see the Ethereum Magicians thread. There are 4 implementations so far, see the links below.
Includes an extensive test suite for `ethereum/tests` here https://github.com/snreynolds/tests/pull/1
Link to Shanghai planning issue https://github.com/ethereum/go-ethereum/issues/25820
Replaces https://github.com/ethereum/go-ethereum/pull/24463
For additional information, see https://www.eip1153.com/ …
=> all: implement EIP-1153 transient storage

eth/tracers/native/4byte.go, eth/tracers/native/call.go, eth/tracers/native/prestate.go
Use `noopTracer` as a base for other native tracers to avoid extra boilerplate for unimplemented hooks.
=> eth/tracers: small refactor for native tracers

internal/guide/guide_test.go, rpc/websocket_test.go
This should remove about ~~two minutes~~ `75s` on CI. 
The `internal/guide` test was news to me, but apparently it executes the commands on the page here: https://geth.ethereum.org/docs/dapp/native-accounts . Well, doing full scrypt on CI is very slow, so maybe we don't have to do it all the time.  
On ` Image: Visual Studio 2019; Environment: GETH_ARCH=386, GETH_MINGW=C:\msys64\mingw32 `, without this PR 
```
ok  	github.com/ethereum/go-ethereum/internal/guide	18.755s	coverage: [no statements]
...
ok  	github.com/ethereum/go-ethereum/rpc	107.314s	coverage: 84.1% of statements
```
With this PR
```
ok  	github.com/ethereum/go-ethereum/internal/guide	1.751s	coverage: [no statements]
...
ok  	github.com/ethereum/go-ethereum/rpc	49.667s	coverage: 83.7% of statements
```
=> rpc, internal/guide: speed up tests a bit

ethstats/ethstats.go
This PR sets a read limit on the ethstats connection to the ethstats-server, which is  a DoS prevention in case the user connects to a malicious ethstats server. 
This PR changes it to use the same limit as websocket rpc: https://github.com/ethereum/go-ethereum/blob/master/rpc/websocket.go#L285
Issue reported by Jorropo via bounty email.
=> ethstats: set readlimit on ethstats server connection

eth/catalyst/api_test.go
This makes a couple of sometimes-failing tests (https://ci.appveyor.com/project/ethereum/go-ethereum/builds/45400713/job/9w748su5x4fv5vj4#L1116) less brittle. 
It also removes a seemingly (?) signing/transaction-adding step in one test. @MariusVanDerWijden PTAL if that was needed, as far as I could tell it wasn't. If it indeed _is_ needed, then the test should have some sort of expectation built in on the number of txs in the payloads/blocks.
=> eth/catalyst: make tests less time-sensitive

cmd/utils/cmd.go
geth may be configured to use various paths across various mounted locations with different disk space availability.
This change additionally logs the path checked when encountering low disk space.
=> cmd/utils: log path used when checking disk space

core/blockchain_test.go, core/state/statedb.go, core/state_transition.go, core/vm/interface.go, core/vm/runtime/runtime.go, tests/state_test.go
Implements https://eips.ethereum.org/EIPS/eip-3651 for Shanghai.
=> core: implement EIP-3651, warm coinbase

core/rawdb/freezer_table.go
While investigating #22374, I noticed that the `Sync` operation of the freezer does not take the table lock.
It also doesn't call sync for all files if there is an error with one of them.
I doubt this will fix anything, but didn't want to drop the fix on the floor either.
=> core/rawdb: improve freezerTable.Sync

cmd/utils/flags.go
=> cmd/utils: print warning when --metrics.port set without --metrics.addr

signer/core/apitypes/signed_data_internal_test.go, signer/core/apitypes/types.go
Hey, @holiman 
Golang version: v1.19
go-ethereum version: v1.10.25
I have a problem doing EIP712 signature with parameter type `uint256[]`
It's like this issue: 
https://github.com/ethereum/go-ethereum/issues/23335#issue-961626333
When the input type is a slice of the internal required type, for example: 
`[]string`,`[]*math.HexOrDecimal256`...
The following line of code will not pass the type when performing type assertion, unless the user encapsulates it in `[]interface{}` before calling
```go
arrayValue, ok:=encValue.([]interface{})
```
Reference documentation: https://github.com/golang/go/wiki/InterfaceSlice
So I processed this code, using reflection to assert whether the value is a slice, process and return the required slice
=> signer/core/apitypes: deep convert types in slice

signer/core/signed_data.go, signer/core/signed_data_test.go
This PR replaces #23308, which had grown bitrotted. I rebased it and rewrote parts of it. The original branch (which was master-branch of @nasdf ) seems to be different since this PR was made, so I couldn't just push the fixes there. 
I tried to maintain authorship in the commit.
=> signer: enable typed data signing from signer rpc

p2p/nat/natpmp.go
```go
// IsPrivate reports whether ip is a private address, according to
// RFC 1918 (IPv4 addresses) and RFC 4193 (IPv6 addresses).
func (ip IP) IsPrivate() bool {
if ip4 := ip.To4(); ip4 != nil {
// Following RFC 1918, Section 3. Private Address Space which says:
//   The Internet Assigned Numbers Authority (IANA) has reserved the
//   following three blocks of the IP address space for private internets:
//     10.0.0.0        -   10.255.255.255  (10/8 prefix)
//     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
//     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)
return ip4[0] == 10 ||
(ip4[0] == 172 && ip4[1]&0xf0 == 16) ||
(ip4[0] == 192 && ip4[1] == 168)
}
// Following RFC 4193, Section 8. IANA Considerations which says:
//   The IANA has assigned the FC00::/7 …
```
=> p2p/nat: use `IP.IsPrivate`

internal/web3ext/web3ext.go
web3.js's eth_call which we were defaulting to doesn't have the `stateOverrides` parameter, so this param wasn't working in the console.
This came up when looking into https://github.com/ethereum/go-ethereum/issues/26088.
=> internal/web3ext: fix eth_call stateOverrides in console

core/forkchoice.go
=> core: forkchoice.go more readable code

internal/web3ext/web3ext.go
Fixes a regression in https://github.com/ethereum/go-ethereum/pull/26265.
Basically it only worked if all 3 parameters were provided.
=> internal/web3ext: fix eth.call regression in console

console/console.go
This change was already proposed in https://github.com/ethereum/go-ethereum/pull/25148, but that PR got closed for some reason. I recently needed this functionality myself, so here we go again.
=> console: use default APIs when server doesn't have rpc_modules

docs/_rpc/ns-personal-deprecation.md, docs/_rpc/ns-personal.md
adds deprecation warning note to the `ns_personal` api docs and adds a new page showing Clef's alternatives for each method in `ns_personal`.
=> docs: add info on `ns personal` deprecation

cmd/devp2p/internal/v5test/framework.go, p2p/discover/common.go, p2p/discover/v5_udp.go, p2p/discover/v5wire/encoding.go, p2p/discover/v5wire/encoding_test.go
With this PR, anyone using go-ethereum as a library should be able to span a discovery network isolated from the Ethereum Discovery v5 network by specifying a custom protocol id in the config passed to `ListenV5`
=> p2p/discover: add config option for discv5 protocol ID

miner/worker_test.go
There is a potential goroutine leak in the `TestStreamUncleBlock` test.
If the receives on `taskCh` time out before the worker starts sending, the worker will be blocked indefinitely.
This in turn blocks the main goroutine when it waits for the worker to close.
This is reproducible by inserting an appropriate `time.Sleep` before the send on `taskCh`.
The proposed fix allows the worker to proceed from sending on `taskCh` even when the reads have timed out.
=> miner: fix potential goroutine leak in TestStreamUncleBlock

core/txpool/list.go, core/types/transaction.go, p2p/util.go
Set the deleted item to its zero val so it can be garbage collected.
=> all: assign zero after resize in implementations of heap.Interface

core/vm/evm.go, core/vm/logger.go, eth/tracers/js/goja.go, eth/tracers/js/internal/tracers/call_tracer_legacy.js, eth/tracers/js/tracer_test.go, eth/tracers/logger/access_list_tracer.go, eth/tracers/logger/logger.go, eth/tracers/logger/logger_json.go, eth/tracers/native/call.go, eth/tracers/native/mux.go, eth/tracers/native/noop.go, eth/tracers/native/prestate.go
When working with evm traces, in tools like goevmlab, it's a bit annoying when traces are not deterministic. 
Example: 
```
{"pc":2619,"op":80,"gas":"0x13a8","gasCost":"0x2","memSize":2240,"stack":["0x7dce2faf43218578e3fcf2ad22df9918a89e2fba"],"depth":1,"refund":0,"opName":"POP"}
{"pc":2620,"op":0,"gas":"0x13a6","gasCost":"0x0","memSize":2240,"stack":[],"depth":1,"refund":0,"opName":"STOP"}
{"output":"","gasUsed":"0xb2e6d","time":4638993}
{"stateRoot": "ad1024c87b5548e77c937aa50f72b6cb620d278f4dd79bae7f78f71ff75af458"}
```
The `time` is what makes the output change, and does not really bring a whole lot of added value. This PR removes the `time` element on the `output` line. 
cc @s1na didn't you also gripe about this at some point?
=> eth/tracers/logger: do not include elapsed time in evm output

cmd/evm/staterunner.go
When doing differential fuzzing, it's convenient to use the `evm statetest` command to and parse the stateroot. Currently, this is done by parsing one of the output fields:. 
```
$ go run . statetest ./foo2.json 
[
{
"name": "foo-test-2",
"pass": false,
"fork": "London",
"error": "post state root mismatch: got bce00dc1f67e91e7f2b7461f3ecaf29d913704291639b89fcc6a9682b02c5671, want 0000000000000000000000000000000000000000000000000000000000000000"
}
]
```
This "works" -- https://github.com/holiman/goevmlab/blob/master/evms/geth.go#L61:L67 -- I can parse the text between `got ` and `, want`. 
However, it fails in certain scenarios, like when the test errors: 
```
$ go run . statetest ./foo.json 
[
{
"name": "foo-test",
"pass": false,
"fork": "London",
"error": "unexpected error: intrinsic gas …
```
=> cmd/evm: output stateroot in statetest result

p2p/nat/natpmp.go
For NAT-PMP, returns success with an available port if the requested port is already preempted. If this situation occurs, the current implementation considers it a success and performs the remaining tasks, but in practice, communication with external network nodes is impossible, and it is difficult to track down this issue.
This PR adds check logic for preempted ports and define this situation as an error.
ref: rfc6886 [p.12](https://www.rfc-editor.org/rfc/rfc6886.html#page-12), [p.29](https://www.rfc-editor.org/rfc/rfc6886.html#page-29)
=> p2p/nat: handle responses with alternative port in NAT-PMP

p2p/discover/table.go, p2p/discover/table_test.go
Spotted this days ago, today I was writing something similar and I decide to create a PR for this.
It just doesn't feel right to check `ix == len(h.entries)` after possibly appending an additional entry to `h.entries`.
@fjl correct me if there's something missed out:)
=> p2p/discover: improve nodesByDistance.push

cmd/geth/config.go, cmd/utils/flags.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go
`--syncTarget` is a feature for development purpose in post-merge world. Previously 
it's added into eth.Config. But it turns out it's a stupid idea.
- syncTarget is a block object, which is hard to be put in config file(large)
- syncTarget is just a dev feature, doesn't make too much sense to add it in config file
So I remove it from the eth config object. And it also fixes the #26328
=> eth, cmd: remove syncTarget from eth config

core/blockchain.go, eth/api.go, internal/web3ext/web3ext.go
=> core,eth: add rpc method to trie flush frequency

core/blockchain.go
While investigating another issue, I found that all callers of `collectLogs` have the complete block available. 
There is no need to read it back from the database.
=> core: pass block into collectLogs

event/feedof.go, event/feedof_test.go
This PR adds a new type `event.FeedOf[T]`, which is like `event.Feed` but parameterized over the channel element type. Performance is unchanged, and it still uses reflect. But unlike `Feed`, the generic version doesn't need to type-check `interface{}` arguments. All panic cases are gone from the API.
Closes #24549
=> event: add FeedOf[T]

eth/tracers/api.go, eth/tracers/api_test.go
Currently calling `debug_TraceTransaction` with a transacation hash that doesn't exist returns a confusing error: `{code=-32000, message=genesis is not traceable}`. This is because the `GetTransaction` returns `blockNumber=0` when the transaction doesn't exist.
This PR checks if the tx is `nil` and returns `nil` if so. This will match the behavior of `eth_getTransactionByHash` and `eth_getTransactionReceipt` for transactions that don't exist or aren't yet included in a block.
Fixes #22846.
Example RPC response:
```
> curl -d '{"id":0,"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x0000000000000000000000000000000000000000000000000000000000000000"]}' -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","id":0,"result":null}
```
=> eth/tracers: return proper error from debug_TraceTransaction when tx not found

core/state_transition.go
the comment suggests that contract creation happens if the recipient of a call is `0x00..00` ("zero address") but in fact the sender must be `nil`. the zero address is a regular valid address that is commonly used as a "burn" address
the comment should be updated in the event someone reads this text and gets confused
=> core: fix comment about recipient for contract creation

eth/tracers/native/prestate.go
Someone reported a crash, https://github.com/ethereum/go-ethereum/issues/26347 , in prestate tracer. The prestate tracer has `account`s, and they have a (possibly nil) balance. The existing code does not properly nil-check before dereferencing it, which this PR fixes.
=> eth/tracers/native: fix possible crash in prestate tracer

signer/core/api.go, signer/core/signed_data_test.go
This PR adds a check that the safetxhash that we sign corresponds to the one that is expected by the input. This PR also adds a case which is currently failing.
The current code calculates the `safeTxHash` for a certain json message differently than what is expected by the online safe tx machinery. 
cc @rmeissner could you please help me figure out the difference here? 
json: 
```json
{
"safe": "0x899FcB1437DE65DC6315f5a69C017dd3F2837557",
"to": "0x899FcB1437DE65DC6315f5a69C017dd3F2837557",
"value": "0",
"data": "0x0d582f13000000000000000000000000d3ed2b8756b942c98c851722f3bd507a17b4745f0000000000000000000000000000000000000000000000000000000000000005",
"operation": 0,
"gasToken": "0x0000000000000000000000000000000000000000",
"safeTxGas": 0,
"baseGas": 0,
"gasPrice": "0",
"refundReceiver": …
```
=> signer/core: handle gnosis safe problem with missing chain id

core/blockchain_snapshot_test.go
=> core: fix typo in blockchain_snapshot_test.go

eth/api.go, eth/api_backend.go, eth/filters/filter.go, eth/state_accessor.go, eth/tracers/api.go
This ensures that RPC method handlers will react to a timeout or cancelled request soon after the event occurs.
=> eth/filters, eth/tracers: add request cancellation checks

trie/committer.go, trie/trie.go, trie/util_test.go, trie/utils.go
This PR fixes an error in trie commit.
If the trie.root is nil, it can be two possible scenarios:
- The trie was empty, and no change happens
- The trie was non-empty and all nodes are dropped
For the latter one, we should collect the deletions and
apply them into database(e.g. in PBSS).
=> trie: wrap deletion in case trie.root is nil

core/rawdb/freezer_resettable.go, core/rawdb/freezer_resettable_test.go
This PR implements resettable freezer by adding a `ResettableFreezer` wrapper.
Freezer can truncate data from head or tail via truncation methods. Once items 
are deleted from tail, a flag `virtualTail` will be updated in the corresponding
metadata file to indicate these items are not available anymore.
However, tail truncation is irreversible. In other words, these positions corresponding 
to tail truncated can no longer store new data. The only way is to reset the entire
freezer.
In PBSS, freezer is used to restore trie history(reverse diff). These history items
will be truncated from tail. But it's possible that blockchain will be required to
rollback to genesis, which needs to reset the entire trie history(drop all of them).
So this function is needed in this case.
Implementation …
=> core/rawdb: implement resettable freezer

core/state/dump.go, core/state/state_object.go, core/state/statedb.go, eth/api.go, eth/api_test.go, internal/ethapi/api.go
This PR surfaces an error in case storage tries can't be constructed(e.g. database is corrupted).
Previously, if a storage trie is not found in database, we create an empty trie as the alternative.
This approach assumes the trie is always non-empty and finally the db error will be detected.
This PR surfaces the dbErr directly instead of creating an empty trie, since in some scenarios
creating empty trie can also fail.
=> core/state: return error when storage trie can't be opened

core/state/journal.go, core/state/state_object.go, core/state/statedb.go
Originally the destructed flag in stateDB is only maintained when snapshot
is enabled and alive. But it turns out that this flag is also required in PBSS.
For example: 
The object was destructed then re-created. StateDB needs the signal
to cleanup the original storage which is unknown without this flag
This PR maintains this flag by default. The logic should not be changed.
=> core/state: maintain destruction flag by default

core/blockchain.go, ethclient/gethclient/gethclient_test.go
This PR sends a HeadChainEvent on SetHead. The txpool will reset the txnoncer on receiving this head chain event.
probably closes https://github.com/ethereum/go-ethereum/issues/26154 & https://github.com/ethereum/go-ethereum/issues/20078
(The change to the test is because the setHeadTest now modifies the txpool, so the gas cost for creating the accesslist is too low)
=> core: reset txpool on sethead

common/mclock/alarm.go, common/mclock/alarm_test.go, p2p/dial.go
Alarm is a timer utility that simplifies code where a timer needs to be rescheduled over
and over. Doing this can be tricky with time.Timer or time.AfterFunc because the channel
may need to be drained in some cases.
Alarm is optimized for use cases where items are tracked in a heap according to their expiry
time, and a goroutine with a for/select loop wants to be woken up whenever the next item expires.
In this application, the timer needs to be rescheduled when an item is added or removed
from the heap. Using a timer naively, these updates will always require synchronization
with the global runtime timer datastructure to update the timer using `Reset`. Alarm avoids
this by tracking the next expiry time and only modifies the timer if it would need to fire earlier
than already scheduled. …
=> common/mclock: add Alarm

cmd/devp2p/internal/v5test/discv5tests.go, cmd/devp2p/internal/v5test/framework.go, p2p/discover/v5_udp.go, p2p/discover/v5_udp_test.go, p2p/discover/v5wire/encoding_test.go, p2p/discover/v5wire/msg.go
This adds more fields to discv5 packet logs. These can be useful when
debugging multi-packet interactions.
The FINDNODE message also an additional field, OpID, also for
debugging purposes. This field is not encoded onto the wire. The
OpID can be used to attribute requests to a specific lookup process.
I'm also removing topic system related message types in this change.
These will come back in the future, where support for them will be
guarded by a config flag.
=> p2p/discover: add more packet information in logs

core/state/database.go, core/state/statedb.go, core/state/trie_prefetcher.go, eth/protocols/snap/handler.go, eth/protocols/snap/sync.go, light/trie.go, trie/secure_trie.go
This PR cleans up/improves some trie interfaces:
- `TryGetAccount`, `TryUpdateAccount`, `TryDeleteAccount` accepts `common.Address` as the parameters, which is more intuitive to callers
=> core, eth, trie, light: clean up trie interface

.env.local.example, docs/getting-started/consensus-clients.md, netlify.toml, package.json, src/constants.ts, src/pages/_app.tsx, yarn.lock
A follow-up migration PR from the existing `ethereum/geth-website` repo. Includes a few changes that were added after the initial code freeze and site migration to the `ethereum/go-ethereum:website` branch. 
- [feat: Add Matomo analytics geth-website#199](https://github.com/ethereum/geth-website/pull/199)
- [Fix broken rpc link geth-website#203](https://github.com/ethereum/geth-website/pull/203)
=> [website] geth-website migration

eth/downloader/skeleton.go, eth/downloader/skeleton_test.go
Fixes #26300
This PR fixes a scenario in which Geth will delete referenced skeleton header by mistake.
In the example listed in #26300 
- Local skeleton header `325@0946fa`
- New beacon header `327@e97873 `
These two headers are in different chain, reorg happens. Geth syncs up the missing skeleton
headers which links up with local chain. The link point is lower than `325`.
Then there is a special logic in beacon sync that 
```
// If there are only 2 subchains - the current one and an older
// one - and the old one consists of a single block, then it's
// the expected new sync cycle after some propagated blocks.
```
And if the associated header of leftover subchain is in range of 
new subchain(just like the example), we delete the skeleton header
referenced by new subchain by mistake …
=> eth/downloader: fix unexpected skeleton header deletion

tests/init.go
Adds support for `Shanghai` as `--state.fork` parameter in evm t8n.
=> cmd/evm: support shanghai in evm t8n

crypto/bls12381/g1_test.go, crypto/bls12381/g2_test.go
Afaict, the only potential use-case for this code is to serve as a reference implementation for EIP-2537 `G1Mul` and `G2Mul` precompiles.  It makes sense to keep consistency with the  benchmarks in `core/vm/contracts_test.go` which benchmark worst-case inputs.
=> crypto/bls12381: use worst case scalar for input to G1/G2 mul benchmarks

core/state/state_object.go, core/state/statedb.go, eth/tracers/api_test.go, internal/ethapi/api.go
This PR fixes https://github.com/ethereum/go-ethereum/issues/24456 . 
This PR removes the notion of `fakeStorage` from the state objects, and instead, for any state modifications that are needed, it simply makes the changes and commits it. 
I'm not fully certain if there are any tangible negative side-effects of doing a `Commit` (such as, does it have potential to flush stuff to disk? I _think_ not). 
One other change is that this change makes it not possible to replace the entire storage in one go, rather we can only update slots explicitly. I don't know how much of a biggie that is.
=> core/state: remove notion of fake storage

eth/downloader/beaconsync.go
Fixes https://github.com/ethereum/go-ethereum/issues/26429.
In legacy (pre-merge) sync mode, headers were contiguously downloaded from the network and when no more headers were available, we checked every few seconds whether there are 64 new blocks to move the pivot.
In beacon (post-merge) sync mode, we don't need to check for new skeleton headers non stop, since those re delivered one by one by the engine API. The missing code snippet from the header fetcher was to actually look at the latest head and move the pivot if it was more than 2*64-8 away. This PR adds the missing movement logic.
The convoluted logic of pulling headers from disk if they don't exist in the skeleton chain shouldn't really be needed, but I've added it as a sanity check in case I'm missing some reasoning now. It …
=> eth/downloader: move the pivot in beacon sync mode too

core/vm/jump_table.go
[EIP-3855](https://eips.ethereum.org/EIPS/eip-3855): PUSH0 instruction is part of [Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md).
=> core/vm: enable EIP-3855 (PUSH0) in Shanghai

rpc/http.go
It looks like in #24911 the `httpClient` value in the config should have been set to the provided client, but it was accidentally omitted.
=> rpc: fix setting client in DialHTTPWithClient

ethclient/gethclient/gethclient.go
The spec and other clients do not accept a parameter value of null for this array.
=> ethclient/gethclient: ensure getProof keys parameter is not null

core/rawdb/chain_freezer.go, core/rawdb/freezer_table.go, core/rawdb/freezer_test.go
This PR fixes an issue which might result in data lost in freezer.
Whenever mutation happens in freezer, all data will be written into head data file
and it will be rotated with a new one in case the size of file reaches the threshold.
Theoretically, the rotated old data file should be fsync'd to prevent data loss.
In `freezer.Sync` function, we only fsync: (1) index file (2) meta file and (3) **head**
data file. So this PR forcibly fsync the head data file if mutation happens in the
boundary of data file.
**Attention**, we need to measure to performance impact brought by this change.
=> core/rawdb: fsync head data file before closing it

docs/interacting-with-geth/rpc/pubsub.md
A typo fix.
Follow-up to https://github.com/ethereum/go-ethereum/pull/26468 😄
=> [website] fix typo

internal/flags/flags.go, internal/flags/flags_test.go
closes https://github.com/ethereum/go-ethereum/issues/22367
NOT TESTED UNDER WINDOWS
=> Use filepath.clean instead of path.clean

cmd/geth/dbcmd.go, core/rawdb/chain_freezer.go, core/rawdb/freezer_table.go, core/rawdb/freezer_test.go
This PR does a few things. First of all, it makes the printout more detailed, e.g. 
```
WARN [01-11|10:56:59.140] Truncating dangling indexes              database=/media/seassd/ancient              table=bodies indexed=596.10MiB stored=596.05MiB
```
by showing the exact number instead of approximate `MB`. 
Secondly, it adds a testcase showing a cornercase that can occur during shutdown, if `freezer` is `Close()`d, and only afterwards the chain freezer calls `Sync`. Currently, this would lead to a exit with `CRIT`. 
The chain_freezer does writes here: https://github.com/ethereum/go-ethereum/blob/master/core/rawdb/chain_freezer.go#L162 
followed by `Sync` here: https://github.com/ethereum/go-ethereum/blob/master/core/rawdb/chain_freezer.go#L170
Between these operation, the underlying `f` …
=> core/rawdb: fix cornercase shutdown behaviour in freezer

cmd/evm/README.md
=> cmd/evm: fix typo in README.md

docs/getting-started/installing-geth.md
updates install instructions because `go get` no longer downloads and builds packages (see [here](https://go.dev/doc/go-get-install-deprecation))
Fixes #26344
=> [website]: update go installation instructions

core/txpool/txpool.go
This PR makes sure that only transactions that do not exceed the initcode size make it into the txpool 
> I just found a pretty nasty edge case wrt. 3860 (Max init code size).
I send a bunch of handcrafted interesting transactions to my node, and the 
transactions got stuck all the time. After the 20th time (I know) I decided to investigate.
The issue was that transactions with initdata > MaxInitCodeSize were not rejected by 
the transaction pool. They would be rejected by nodes executing them, but not by the txpool.
This could've been used to flood a txpool with unexecutable transactions.
Since they are valid looking, they would be propagated to peers and stay in the mempool.
So it would be great if all EL teams could check that their txpool rejects transactions
where the transaction is …
=> core/txpool: check if initcode size is exceeded

console/console.go, internal/jsre/completion.go
Fixes #26505. I also noticed while fixing this issue that autocomplete wasn't working for objects/fields with numbers in them (most importantly `web3.<tab><tab>`) which is also now fixed.
The issue is we dropped support for `protocolVersion` but the method still exists in the web3.js library. So console assumes it exists and crashes on the error it gets from server. For the fix we recover and ignore the error.
=> console, internal/jsre: fix autocomplete issues

core/forkid/forkid_test.go, params/config.go
This PR defines Cancun and Osaka forks as timestamp based forks which will happen
after Shanghai.
Apart from that, this PR changes three chain configs to `keyed fields` structure. Since
there are lots of forks/configs in a chain and will be more in the future, it's really unfriendly
for eyes to check which forks are activated and unintuitive to add more future forks.
=> params: define cancun and prague as timestamp based forks

signer/core/apitypes/types.go, signer/core/signed_data_test.go
From @CarlBeek
> The query I have is about enforcing reference types to be upper case. (Geth does it here: https://github.com/ethereum/go-ethereum/blob/master/signer/core/apitypes/types.go#L227-L234). As far as I can see, this is not something that is REQUIRED or even mentioned in the EIP spec. Do you know the reason for this check in geth?
> 
> This has come up as we are using EIP712 messages in the KZG ceremony and geth/clef refuses to sign these messages as one of the fields has type contributionPubkey.
This PR fixes our implementation so we no longer require reference types to start with a capital letter
=> signer/core: don't require capital lettered reference types

cmd/utils/flags.go
This fixes a regression where the flag did not accept values without the 0x prefix anymore. What's worse, if an invalid value was passed, the client would just log an INFO level message and continue.
=> cmd/utils: improve parsing of --miner.etherbase address

cmd/utils/flags.go
This fixes a regression in #26541 where we turned the miner address being missing into a startup error. The address was not configured in --dev mode, and geth failed to start.
=> cmd/utils: fix error at geth startup in --dev mode

eth/catalyst/api.go, eth/catalyst/api_test.go
According to the spec, we need to return an error if withdrawals are set before shanghai and if they are set to nil after shanghai
=> eth/catalyst: error on nil withdrawals post-shanghai

eth/catalyst/api.go
Implements the new `engine_exchangeCapabilities` method which returns all available method names.
Spec: https://github.com/ethereum/execution-apis/pull/364
=> eth/catalyst: implement exchangeCapabilities

params/config.go
Fixes a regression introduced in #25878
=> params: fix timestamp display in fork banner

cmd/evm/blockrunner.go, cmd/evm/main.go
Adds `blocktest` subcommand to the `evm` command, which is very similar to `statetest`, but instead of loading a StateTest static test it loads a BlockchainTest from a json file and runs it.
I use this a lot to double check tests are filled correctly on https://github.com/ethereum/execution-spec-tests/, and normally when testing a change I cherry-pick this commit on top of whatever I'm testing, but it might be useful to have it in master.
=> cmd/evm: add blocktest subcommand to evm

cmd/devp2p/README.md
=> cmd/devp2p: fix broken link to DNS discovery tutorial (docs)

log/format.go, log/format_test.go
This PR makes the log sanitation even stricter
=> log: better sanitation

ethclient/gethclient/gethclient_test.go
fix grammar typo in `ethclient/gethclient/gethclient_test.go`
=> ethclient/gethclient: fix typo

eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/native/call.go, eth/tracers/native/gen_callframe_json.go
This PR renames `Revertal ` to `RevertReason` which I believe is a typo.
=> eth/tracer: rename to revertReason

internal/ethapi/api.go
The `execution-apis` specification says that the full list of withdrawals should _always_ be returned when requesting a block over RPC:
https://github.com/ethereum/execution-apis/blob/378c4304f75b5af2c9b5263c9c76b511e33e8984/src/schemas/block.yaml#L90-L94
This PR adopts the expected behavior.
=> internal/ethapi: always add block withdrawal objects if present
