ethereum/go-ethereum

core/beacon/errors.go, eth/catalyst/api.go
We must return `-32602` when withdrawals are specified before shanghai, or not defined afterwards
closes https://github.com/ethereum/go-ethereum/issues/26584
=> eth/catalyst: return invalid params instead of invalid payload params

core/vm/evm.go, core/vm/instructions.go, core/vm/instructions_test.go, core/vm/interpreter.go
This PR improves the reusability of the EVM struct. Two methods are added:
* `SetBlockContext(...)` 
* `SetTracer(...)`
Other attributes like the TransactionContext and the StateDB can already be updated. BlockContext and Tracer are partially not updateable right now. This PR fixes that and opens the potential to reuse an EVM struct in more ways.
=> core/vm: improve EVM reusability

README.md, src/components/UI/docs/Note.tsx, src/components/UI/downloads/BuildsDeprecationNote.tsx, src/components/UI/downloads/DownloadsTable.tsx, src/components/UI/downloads/index.ts
This PR adds a deprecation note for mobile builds on downloads tables.
**Preview:** https://deploy-preview-26605--geth-website.netlify.app/downloads
Fixes #26601
=> Add note mobile builds

core/block_validator.go, core/state_processor_test.go, tests/block_test_util.go, tests/gen_btheader.go, tests/init.go, tests/state_test.go
This PR updates the tests, which presumably contains some shanghai tests.
=> tests: update to latest

src/constants.ts, src/utils/getLastModifiedDate.ts
Previously we were accidentally still pulling GitHub commit info from their REST API by pointing to the old dev form of the site on `ethereum/geth-website`.
#26619 Updated this, but the link did not properly reference the `website` branch of this repo, which required setting a new search param in the URL for `?sha=website`
This PR fixes the format for the call to the GitHub REST API to target the proper branch. I refactored the call to use the `new URL()` js object format which helps to construct these URLS with improved readability
=> [website] Fix document commit date fetch

accounts/abi/error_handling.go, accounts/abi/unpack.go, accounts/abi/unpack_test.go
In solidity, `abi.decode(abi.encode(256), (uint8))` will revert, which is currently not the case with `Unpack` in go.
This PR fixes this issue so that the behavior is consistent.
=> accounts/abi: fix ReadInteger

internal/ethapi/api.go, rpc/types.go
It's the same as math.HexOrDecimal64, which has more uses across the codebase.
=> rpc: remove DecimalOrHex type

log/format.go
This fixes a regression where panic reports from package rpc were quoted because they contain tab characters.
=> log: allow tabs in log messages

cmd/geth/snapshot.go, core/blockchain.go, core/blockchain_repair_test.go, core/blockchain_sethead_test.go, core/blockchain_snapshot_test.go, core/chain_makers.go, core/dao_test.go, core/genesis.go, core/state/iterator_test.go, core/state/pruner/pruner.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/statedb_test.go, core/state/sync_test.go, eth/protocols/eth/handler_test.go, light/postprocess.go, tests/fuzzers/stacktrie/trie_fuzzer.go, trie/database.go, trie/encoding_test.go, trie/iterator.go, trie/iterator_test.go, trie/stacktrie_test.go, trie/trie_test.go
This PR ports some changes from the main PBSS PR, mainly includes:
- get rid of callback function in trie.Database.Commit which is not required anymore
- rework the nodeResolver in trie.Iterator to make it compatible with multiple state scheme
- some other non-interesting changes in tests and typo
=> all: port changes from pbss PR

src/theme/foundations/textStyles.ts
This PR updates the `docs-nav-dropdown` & `docs-nav-links` text styles
**Preview:** https://deploy-preview-26635--geth-website.netlify.app/docs
Fixes #26477
=> [website] chore: update textStyles in DocsNav

common/prque/lazyqueue.go, common/prque/prque.go, common/prque/prque_test.go, common/prque/sstack.go, common/prque/sstack_test.go, core/blockchain.go, core/rawdb/chain_iterator.go, core/txpool/txpool.go, eth/downloader/fetchers_concurrent.go, eth/downloader/queue.go, eth/fetcher/block_fetcher.go, go.mod, go.sum, les/downloader/queue.go, les/fetcher/block_fetcher.go, les/flowcontrol/manager.go, les/flowcontrol/manager_test.go, les/servingqueue.go, les/vflux/server/prioritypool.go, trie/sync.go
This is an extended version of https://github.com/ethereum/go-ethereum/pull/26286 where even the priority is generic. Note, this meant getting rid of some "wrap around" quirk introduced and used by LES. The PR *did not fix* LES, just reverted it to the plain prque version. No test fails, but my assumption is that it breaks LES in an unknown way. Please @zsfelfoldi take a look.
Notably referring to this past discussion thread: https://github.com/ethereum/go-ethereum/pull/22495/files#r603754243
=> common/prque: generic priority queue 9000

common/prque/sstack.go, eth/downloader/fetchers_concurrent.go
There was a funky event ordering issue in the downloader, which was papered over with some `-1` indexing hack in the prque (emit -1 for a deleted item and ignore removing -1 index from the queue).
The issue was that the index updater set a new value for `ordering` when timeouts were shuffled in the priority queue, but in the code this PR fixes, the `ordering` was first deleted and only then the matching timeout popped. However, popping an item entails internal reorgs, so it actually resurrected the `ordering` item.
The original `-1` hack fixed this by resurrecting a value of `-1` in the end, which eventually got silently ignored by the `prque.Remove`. By changing the removal order to first pop the timeout (causing index changes) and only afterwards delete the `ordering`, there are no more …
=> common/prque, eth/downloader: fix timeout resurrection panic

core/state/database.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/state_object.go, core/state/statedb.go, eth/protocols/snap/sync_test.go, light/postprocess.go, light/trie.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/committer.go, trie/iterator_test.go, trie/secure_trie.go, trie/secure_trie_test.go, trie/sync_test.go, trie/trie.go, trie/trie_test.go, trie/util_test.go
I started investigating, due to https://github.com/ethereum/go-ethereum/pull/26637#discussion_r1099761367 ,  how/why a `Commit` operation could return an error, and found the answer to be: "Apparently it can't". 
This PR removes the error-return. Testing it out
=> core/state, trie: remove unused error-return from trie Commit operation

ethdb/dbtest/testsuite.go, ethdb/leveldb/leveldb_test.go, ethdb/pebble/pebble.go, ethdb/pebble/pebble_test.go
This PR adds a benchmark suite for different database engine; and the result ran by my laptop is also attached
```
goos: darwin
goarch: amd64
pkg: github.com/ethereum/go-ethereum/ethdb/leveldb
cpu: VirtualApple @ 2.50GHz
BenchmarkLevelDB
BenchmarkLevelDB/Write
BenchmarkLevelDB/Write/WriteSorted
BenchmarkLevelDB/Write/WriteSorted-8         	1000000000	         0.8535 ns/op	       0 B/op	       0 allocs/op
BenchmarkLevelDB/Write/WriteRandom
BenchmarkLevelDB/Write/WriteRandom-8         	       1	1251543292 ns/op	862467760 B/op	 3156705 allocs/op
BenchmarkLevelDB/Read
BenchmarkLevelDB/Read/ReadSorted
BenchmarkLevelDB/Read/ReadSorted-8           	       1	1620685500 ns/op	779155496 B/op	13155965 allocs/op
BenchmarkLevelDB/Read/ReadRandom
BenchmarkLevelDB/Read/ReadRandom-8           	       1 …
```
=> ethdb: add benchmark test suite

core/forkid/forkid_test.go, params/config.go, params/config_test.go
Announcement: https://github.com/ethereum/execution-specs/pull/716
=> params: schedule shanghai fork on sepolia

src/components/UI/docs/DocsLinks.tsx
[PR migrated from now deprecated `geth-website` repo](https://github.com/ethereum/geth-website/pull/192)
Add highlighting to active doc section
=> [website] Highlight active docs section

tests/fuzzers/bls12381/bls12381_fuzz.go
I _think_ this fixes https://github.com/ethereum/go-ethereum/issues/26669 . There may be other issues too, related to `blst`, but we can tackle that later in that case.
=> tests/fuzzers: supply gnark multiexp config, fixes #26669

cmd/devp2p/crawl.go
Our discovery crawler spits out a huge amount of logs, most of which is pretty non-interesting. This PR moves the very verbose output to `Debug`, and adds a 8-second status log message giving the general idea about what's going on.
=> cmd/devp2p: less output in node crawler

src/components/UI/docs/DocsLinks.tsx
The active doc link is a bit hard to read currently
=> [website]: Update background color of active doc link

p2p/dnsdisc/client_test.go, p2p/dnsdisc/tree_test.go
This fixes an issue where unit tests of package p2p/dnsdisc stopped working with Go 1.20. The failure was caused by a change in package crypto/ecdsa, which now explicitly prevents generating deterministic keys using `GenerateKey`. Our tests heavily relied on the output being deterministic.
=> p2p/dnsdisc: fix tests with Go 1.20

ethdb/pebble/pebble.go
`MemTableStopWritesThreshold` was set to the max size of all memtables before blocking writing but should be set to the max number of memtables. This is documented [here](https://github.com/cockroachdb/pebble/blob/master/options.go#L738-L742) and used in the code [here](https://github.com/cockroachdb/pebble/blob/master/db.go#L1892-L1903).
Nice work adding Pebble support! ❤️
=> ethdb/pebble: Fix `MemTableStopWritesThreshold`

docs/interacting-with-geth/rpc/ns-personal-deprecation.md, docs/interacting-with-geth/rpc/ns-personal.md
small updates to notes now that `personal` namespace is deprecated.
=> update personal namespace notes

core/genesis.go, core/types/block.go, eth/downloader/queue.go, eth/protocols/eth/handler_test.go
This PR relaxes the encoding rules a bit which allows nodes to encode empty withdrawals as [] or nil.
=> core/types: manually set withdrawals if withdrawalHash is emptyRootHash

core/genesis.go
This PR fixes a regression.
Previously it's a special trick to fast-bootstrap geth that people can nuke out leveldb but retain the ancient store. Once the node is restarted, it will sync up the missing state data from network but avoid re-downloading the chain segment.
Unfortunately it's broken in 1.11, we determine whether chain needs to be initialized with genesis block by the presence of genesis state, which is expected to be "NO" in the scenario described. However, in 1.11, we determine the state presence by opening it with trie database, which will also read the state from cache file. The chain initialization will be skipped if there is a leftover cache file and genesis root node is contained.
This PR fixes it by a quick hack: load the genesis root node directly from disk.
=> core: check genesis state presence by disk read

eth/downloader/queue.go
Follow-up to #26704, one remaining fix
=> eth/downloader: fix empty-body case in queue fetchresult

accounts/keystore/account_cache_test.go, common/lru/basiclru_test.go, common/prque/lazyqueue_test.go, consensus/ethash/consensus_test.go, core/bloombits/generator_test.go, core/rawdb/freezer_table_test.go, core/state/snapshot/difflayer_test.go, core/state/snapshot/iterator_test.go, core/state/snapshot/snapshot_test.go, core/txpool/txpool_test.go, crypto/signify/signify_test.go, ethdb/dbtest/testsuite.go, event/event_test.go, les/api_test.go, les/benchmark.go, les/utils/limiter_test.go, les/vflux/client/fillset_test.go, les/vflux/server/clientpool_test.go, metrics/sample.go, metrics/sample_test.go, miner/stress/1559/main.go, miner/worker_test.go, p2p/discover/v4_udp_test.go, p2p/enode/localnode_test.go, p2p/netutil/iptrack_test.go, trie/encoding_test.go, trie/proof_test.go, trie/trie_test.go
This PR is a (superior) alternative to https://github.com/ethereum/go-ethereum/pull/26708, it handles deprecation, primarily two specific cases. 
`rand.Seed` is typically used in two ways
- `rand.Seed(time.Now().UnixNano())` -- we seed it, just to be sure to get some random, and not always get the same thing on every run. This is not needed, with global seeding, so those are just removed. 
- `rand.Seed(1)` this is typically done to ensure we have a stable test. If we rely on this, we need to fix up the tests to use a deterministic prng-source. I expect that tests requiring this should start failing. This PR removes such calls (hint to reviewers: might want to check those) 
`rand.Read` has been replaced by `crypto/rand`.`Read` in this PR.
=> all: remove deprecated uses of math.rand

beacon/engine/errors.go, eth/catalyst/api.go, eth/catalyst/api_test.go
From @mkalinin on discord:
> I would not change V1 in the spec but implementations can remove it from V1, as even in the context of V1 INVALID and INVALID_BLOCK_HASH are semantically equal (there were not initially but then there was a change to INVALID which made them equal). One potential issue are hive tests that expect INVALID_BLOCK_HASH to be returned to newPayloadV1 call with payload having invalid blockHash.
This change will break one hive test, but pass another and it will be the better way going forward
=> eth/catalyst: send INVALID instead of INVALID_BLOCK_HASH

beacon/engine/errors.go, eth/catalyst/api.go, eth/catalyst/api_test.go
https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#specification-4
```
The call MUST return -38004: Too large request error if the requested range is too large.
```
=> eth/catalyst: request too large error

rpc/client.go, rpc/client_test.go, rpc/server_test.go, rpc/testservice_test.go
This is a re-submit of PR #26701, which I cannot push to. 
The change fixes unmarshaling of JSON `null` results into `json.RawMessage`.
=> rpc: fix unmarshaling of null result in CallContext

core/state/metrics.go, core/state/statedb.go, trie/committer.go, trie/database.go, trie/nodeset.go, trie/trie.go, trie/trie_test.go, trie/util_test.go, trie/utils.go
This reverts commit 7c749c947a9d5181f5f2c1b3fdb5ea6b0e401e8e.
=> Revert "core/trie: remove trie tracer (#26665)"

cmd/geth/config.go
This patch documentizes the 'saving into a file' option. 
As suggested in #16383, piping dumpconfig's stdout is imcompatible to the Windows powershell due to the UTF16LE encoding.
To fix this, #18327 (428eabe) added an option to save dumpconfig in a file. However, users cannot be informed of this feature (saving into a file) without searching the relevant github issue or seeing source code.
Thus, this patch fixes the aforementioned inconvenience by improving the description of the dumpconfig's help text.
fixes: 428eabe, #26658
=> geth/dumpconfig: fix undocumented helptext

core/blockchain.go, core/headerchain.go, core/rawdb/accessors_chain.go, core/rawdb/ancient_scheme.go, core/rawdb/chain_freezer.go, core/rawdb/chain_iterator.go, core/rawdb/database.go, eth/downloader/downloader.go, eth/downloader/queue.go
**This PR is not yet ready, I need to check snap vs full sync. Post-merge vs no-merge networks, etc. to make sure there's no weird cornercase that would end up with some nil panic.**
Snap sync introduced a simplified progress logging where instead of logging every import, we just logged a summary every 8 seconds. This made those logs more readable + there's little point in seeing all the details of every import call.
This PR does the same thing for the downloader's chain sync, replacing the individual "Imported headers" and "Imported receipts" lines with aggregated summaries every 8 second-ish. This should allow the user to see what percentage of the chain is synced and what's the ETA. The ETA will be off since the chain is getting heavier and heavier as it progresses, so we always …
=> core, eth: merge snap-sync chain download progress logs

core/genesis.go, core/rawdb/accessors_metadata.go
Closes https://github.com/ethereum/go-ethereum/issues/26746  
Closes #21881
```
$ geth --datadir=/tmp/foobar4  init ~/gen.json 
INFO [02-21|11:07:19.353] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-21|11:07:19.380] Set global gas cap                       cap=50,000,000
INFO [02-21|11:07:19.382] Using leveldb as the backing database 
INFO [02-21|11:07:19.382] Allocated cache and file handles         database=/tmp/foobar4/geth/chaindata cache=16.00MiB handles=16
INFO [02-21|11:07:19.383] Using LevelDB as the backing database 
INFO [02-21|11:07:19.384] Opened ancient database                  database=/tmp/foobar4/geth/chaindata/ancient/chain readonly=false
INFO [02-21|11:07:19.384] Writing custom genesis block 
INFO [02-21|11:07:19.385] Persisted trie from …
```
=> core: fix accessor mismatch for genesis state

core/rawdb/chain_freezer.go, core/rawdb/database.go, core/rawdb/freezer.go
Although the `NewFreezer` method was public until now, it was really impossible to initiate a chain freezer out of it because two parameters: the table size limit and the configuration which tables to snappy encode and which to leave in cleartext were private. Although we could have made the configs public, it's a bit of too much internal detail. Instead, this PR makes a public helped method `NewChainFreezer` that just sets these internal configs automatically.
CC @lightclient
=> core/rawdb: expose chain freezer constructor without internals

eth/filters/api.go, eth/filters/filter_system_test.go
1. fix a breaking change introduced by #25186
- eth_newPendingTransactionFilter & eth_getFilterChanges return hashes by default
2. send `RPCTransactions` in filter changes
=> eth/filters: fix a breaking change and return rpctransaction

common/math/big.go, common/math/integer.go
Fixes https://github.com/ethereum/go-ethereum/issues/26751
Before PR:
```
> eth.feeHistory(12, "latest")
Error: invalid argument 0: json: cannot unmarshal number into Go value of type *math.HexOrDecimal64
at web3.js:6365:9(39)
at send (web3.js:5099:62(29))
at <eval>:1:15(4)
```
After PR:
```
> eth.feeHistory(12, "latest")
{
baseFeePerGas: ["0x0", "0x0"],
gasUsedRatio: [0],
oldestBlock: "0x0"
}
> eth.feeHistory("12", "latest")
{
baseFeePerGas: ["0x0", "0x0"],
gasUsedRatio: [0],
oldestBlock: "0x0"
}
> eth.feeHistory("0xc", "latest")
{
baseFeePerGas: ["0x0", "0x0"],
gasUsedRatio: [0],
oldestBlock: "0x0"
}
```
=> common/math: allow HexOrDecimal to accept unquoted decimals too

log/logger.go, log/root.go
A super small change to improve development ergonomics. Whenever I use the logger, I end up needing to reference the godoc to remember the exact syntax, as it is not evident from the function signature. By making these changes, the IDE tooltip now looks like the below. The comments are added onto each individual method so that all of them now have the helpful IDE tooltips.
I will make a similar PR to log15 itself.
=> log: improve documentation

core/rawdb/freezer.go, go.mod, go.sum, node/node.go
This PR uses https://github.com/gofrs/flock instead of github.com/prometheus/tsdb/fileutil, as the latter is archived.
=> core/rawdb, node: use standalone flock dependency

eth/catalyst/api.go, eth/catalyst/queue.go, eth/catalyst/tester.go, eth/downloader/beaconsync.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/skeleton.go, eth/downloader/skeleton_test.go
Currently we use the hard coded LES CHT as the ancient limit for snap sync. That's unfortunate because a) it introduces a dependency on LES and b) it cannot be updated retrospectively for old clients and c) it needs manual update every release.
This PR adds an additional ancient limit selection logic to the downloader so that if we're in a post-merge network with finalized blocks being announced, then it will use the last finality point as the ancient limit during sync. This mechanism is superior as it will follow the chain dynamically and does not require any manual hardcoded thing.
Note: this PR does not add the same change for normal chain management, as in after initial sync, the ancient limit will revert to 90K and pebble will slowly get filled with ancients. That is a separate …
=> eth: use the last announced finalized block as the sync ancient limit

.travis.yml, appveyor.yml
This PR is the XOR of https://github.com/ethereum/go-ethereum/pull/26672 
I want to see if this makes the tests run any faster. 
Also, got this error on a windows-build on appveyor: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/46263355/job/0pm78r8hddm84kv5?fullLog=true#L807 
> consolecmd_test.go:60: have "password requirements not met: password too short (<10 characters)\nerror: coverage meta-data emit failed: writing C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\go-build826161592\\b564\\gocoverdir\\covmeta.c6c1f95b00265a2816b75dfdd6bd5f2e: rename from C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\go-build826161592\\b564\\gocoverdir\\tmp.covmeta.c6c1f95b00265a2816b75dfdd6bd5f2e1676638211275736200 failed: rename C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\go-build826161592\ …
=> ci: disable coverage reporting in appveyor and travis

cmd/devp2p/crawl.go, cmd/devp2p/discv4cmd.go, cmd/devp2p/discv5cmd.go, cmd/devp2p/dns_cloudflare.go, cmd/devp2p/dns_route53.go
This PR does a couple of things to the `devp2p` tool. First of all, it makes the crawler faster. The op can now set the parallelism arbitrary, here's an example where I set it to `200`: 
```
$ go run . discv4 crawl -timeout 2s -parallel 200 ../../all.json 
INFO [02-14|21:27:53.135] New local node record                    seq=1,676,406,473,135 id=4607be3ac694a60a ip=127.0.0.1 udp=60182 tcp=0
INFO [02-14|21:27:53.215] New local node record                    seq=1,676,406,473,136 id=4607be3ac694a60a ip=212.85.71.121 udp=60182 tcp=0
INFO [02-14|21:28:01.184] Crawling in progress                     added=8 updated=1711 removed=44 ignored(recent)=44 ignored(incompatible)=30
INFO [02-14|21:28:09.185] Crawling in progress                     added=9 updated=3140 removed=86 ignored(recent)=86 …
```
=> cmd/devp2p: faster crawling + less verbose dns updates

core/chain_makers.go, core/chain_makers_test.go
Previously, during chain generation, `AddWithdrawal` would look at parent blocks to determine what the proper withdrawal index is when adding a withdrawal. This was flawed because if there were no withdrawals in parent blocks, and one block added multiple withdrawals, those withdrawals would be given the same index.
The `AddWithdrawal` method is changed, setting the index based on the withdrawal with the highest index in the current block, if there are any other withdrawals.
A test is added, derived from the [withdrawals branch of rpctestgen](https://github.com/lightclient/rpctestgen/tree/withdrawals), making sure same-block withdrawals have increasing indexes.
=> core: ensure increasing BlockGen withdrawal index

ethdb/pebble/pebble.go
=> ethdb/pebble: fix range compaction

ethdb/pebble/pebble.go
=> ethdb/pebble: fix max memorytable size

ethclient/ethclient.go
This PR adds the Withdrawals array to the block body for blocks requested via the ethclient module.
=> ethclient: include withdrawals in ethclient block responses

core/rawdb/databases_64bit.go, core/rawdb/databases_non64bit.go, ethdb/pebble/pebble.go, ethdb/pebble/pebble_test.go
Fixes https://github.com/ethereum/go-ethereum/issues/26800, background at https://github.com/cockroachdb/pebble/issues/2341
=> core/rawdb, ethdb/pebble: disable pebble on openbsd

core/forkid/forkid_test.go, params/config.go
Schedules the goerli shanghai hardfork on timestamp 1678832736.
See also: https://github.com/ethereum/execution-specs/pull/724#pullrequestreview-1322472524
=> core: params: schedule Shanghai on goerli

eth/peer.go
Post-merge there is no more block broadcasts and announcements. As such, we cannot maintain the head infos for our peers. This PR unexposes those infos on the `admin.peers` API to avoid confusion thinking all our peers are unsynced.
Fixes https://github.com/ethereum/go-ethereum/issues/26733
=> eth: remove admin.peers[i].eth.head and difficulty

core/blockchain.go, core/rawdb/accessors_chain.go, core/types/gen_receipt_json.go, core/types/receipt.go, core/types/receipt_test.go, core/types/transaction.go, core/types/tx_access_list.go, core/types/tx_dynamic_fee.go, core/types/tx_legacy.go, internal/ethapi/api.go, light/odr_util.go
Submitting this to take over PR #26250, which I cannot push to for some reason.
This change adds a struct field `EffectiveGasPrice` in `types.Receipt`. The field is present
in RPC responses, but not in the Go struct, and thus can't easily be accessed via ethclient.
=> core/types: add EffectiveGasPrice in Receipt

core/types/block.go, eth/catalyst/api_test.go, graphql/graphql.go
This PR fixes multiple race conditions and tests:
- Fixes  `TestGenerateWithdrawalChain` a test recently broken
- Fixes a race in `TestNewPayloadOnInvalidTerminalBlock` where setting the TTD raced with the miner. Solution: set the TTD on the blockchain config not the genesis config
- Fixes a race in `CopyHeader` which resulted in races all over the place
- Fixes a race in `graphql.Logs` where querying multiple transactions of one block would race on setting the blockhash. This one is not really fixed imo, fixing it would introduce a mutex on t.block.numberOrHash which I can do, wanted to know some more opinions on it though.
=> core, eth/catalyst: fix race conditions in tests

metrics/cpu.go, metrics/cpu_enabled.go, metrics/cputime_nop.go, metrics/cputime_unix.go, metrics/metrics.go
This PR changes metrics collection to actually measure the time interval between collections, rather than assume 3 seconds.  I did some ad hoc profiling, and on slower hardware (eg, my Raspberry Pi 4) I routinely saw intervals between 3.3 - 3.5 seconds, with some being as high as 4.5 seconds.  This will generally cause the CPU gauge readings to be too high, and in some cases can cause impossibly large values for the CPU load metrics (eg. greater than 400 for a 4 core CPU)
=> metrics: improve accuracy of CPU gauges

cmd/evm/internal/t8ntool/execution.go, core/gaspool.go, miner/worker.go
=> core, miner: revert block gas counter in case of invalid transaction

beacon/engine/types.go, eth/catalyst/api.go, eth/catalyst/api_test.go
Fixes an issue where we would omit [] withdrawals.
Adds withdrawals to the ExecutionPayloadBodies tests.
=> beacon/engine: don't omit empty withdrawals in ExecutionPayloadBodies

signer/core/apitypes/types.go, signer/core/apitypes/types_test.go
Include all primitive types in Solidity for EIP-712 from 0 to 256 in multiples of 8
Currently, Uniswap Permit2 generates EIP-712 signatures with uint160 which will throw "unknown reference type" in validate(). Rather than just add uint160, I figured adding all multiples of 8 should be done since they are all valid primitive types. Primitive types cannot be capitalized/camel-cased, so this should cover all cases.
=> signer/core: accept all solidity primitive types for EIP-712 signing 

core/forkid/forkid_test.go
This changes the test to match the comment description. Using timestampedConfig in this test case is incorrect, the comment says 'local is at Gray Glacier' and isn't aware of more forks.
=> core/forkid: fix issue in validation test

core/vm/jump_table.go
it should be constantinople rather than contantinople
=> the fork change info error

core/blockchain.go
=> core: refactor code

eth/api_backend.go
fixes #26830
--
It feels like the right thing to do for pre-merge / non-PoS networks is to simply return error when `safe` or `finalized` is used. These tags have pretty specific meanings for PoS and it isn't clear what they should mean for PoW or PoS networks. `safe` *could* be repurposed for PoW to mean k-deep, but given the fact we're hoping to completely remove `ethash` at some point, it seems moot.
=> eth/api_backend: return error if pos tag used pre-merge

src/theme/search.css
Adjusts the `max-width` down by one pixel on the `search.css` search box styling. The remainder of the Chakra-UI breakpoint tokens function as `min-width`, so at this viewport width (`768px`) the layout is trying to be tablet/desktop, but the search was switching to mobile styling.
This also forces the contents of this search box (placeholder and keys) to properly display at this viewport width.
- Fixes #26420
=> [website]: Layout patch [Fixes 26420]

p2p/discover/v5_udp.go, p2p/discover/v5wire/encoding.go
From https://github.com/ethereum/go-ethereum/pull/25798#issuecomment-1430279369: 
> Either way, to get this in, we'd need to submit the p2p/discover fixes for Unhandled handling to master.
This PR contains the code-changes that are needed in order to overlay a different protocol on discv5: (1) passing the packets via the `unhandled` channel, and (2) not corrupting the data during decryption-attempt. 
It incurs a _slight_ performance penalty since it does an extra copy of the packet contents -- but there's no allocation involved, so it should indeed by very slight. 
Feel free to rebase/reown the commit, this was authored by @fjl as far as I know
=> p2p/discover: pass invalid discv5 packets to Unhandled channel

.github/CONTRIBUTING.md, README.md, cmd/checkpoint-admin/README.md, cmd/geth/consolecmd.go
Updated broken links that are giving 404 errors to https://geth.ethereum.org/docs
Issue: 26881
=> all: update links in documentation

rpc/websocket.go
This PR increases frame size, so it'll be possible to use more complicated RPC requests(like `eth_getBlockByNumber`, `trace_` (erigon)), via websocket
from: https://github.com/ledgerwatch/erigon/pull/2739
example block failure: https://etherscan.io/tx/0x1317d973a55cedf9b0f2df6ea48e8077dd176f5444a3423368a46d6e4db89982#internal
=> Increase websocket frame size (from erigon rpc client)

cmd/devp2p/main.go, cmd/geth/main.go
Not sure why this was removed, it's pretty useful to see the version also in --help.
=> cmd/devp2p, cmd/geth: add version in --help output

core/block_validator.go, core/state/state_object.go, core/state/statedb.go, core/vm/interface.go
It's an alternative approach to bubble up database failure when block processor gets a state mismatch error.
Supersedes #26671
=> core: print db failure in case of mismatched hash root

docs/interacting-with-geth/rpc/ns-debug.md, src/components/layouts/Layout.tsx, src/data/documentation-links.yaml, src/theme/search.css
This PR adds a `flex` container to layout elements, with a `min-height` and top margin to keep footer at the bottom.
Fixes #26425
=> fix: keep footer element at the bottom of the page

consensus/beacon/consensus.go, consensus/clique/clique.go, consensus/consensus.go, consensus/ethash/consensus.go, core/block_validator.go, core/blockchain.go
This PR improves the Finalize and FinalizedAndAssemble definition, clearly stats that:
- In Finalize function, a serial of state operations will be applied according to consensus rules, state root computation is not required. 
This function should be used in block processing(receive a block from network and apply it locally) but not block generation.
- In FinalizeAndAssemble function, except applying post-transaction state mutations, the block needs to be assembled with the latest state root computed.
This function should be used in block generation only.
=> consensus: improve consensus engine definition

eth/catalyst/api.go
This PR increases the time between consensus updates that we give the CL before we start warning the user. During sync it can happen that the CL will only give us updates every now and then and users are getting scared
> basically, recent nimbus versions give the EL one update every 8k blocks while syncing the finalized portion of the chain (ie during initial full sync or when catching up after being offline) - this doesn't seem to be enough to satisfy geth however in terms of the warning - per our earlier discussions, there's no point giving the EL too many FCU's or blocks that are not close to the head anyway
=> eth/catalyst: increase update consensus timeout

internal/ethapi/api.go
This PR marginally improves readability since the cast from int -> uint64 is lossless whereas the cast of uint64(index) -> int(index) is lossy and may overflow for very large values of index.
This is not a problem in practice since the number of txs in a block is much lower than an overflow to be possible here.
=> internal/ethapi: nit: int->uint64 in GetTxReceipt

accounts/abi/abi.go, trie/stacktrie.go
This PR adds err != nil checks for the return values of some calls in stacktrie.go and abi.go
These calls cannot actually return error, however it seems better form to check errors when they are specified in the return value.
=> trie, accounts/abi: nits: adds err checks

eth/api.go
This PR modifies the default file creation permissions from 0777 to 0700 for files created by ExportChain so they are not globally writable.
=> eth: fix output file permissions in admin_exportChain

trie/proof_test.go, trie/sync_test.go, trie/trie_test.go
Using a secure RNG to seed a PRNG, improves test time.
Decreases test time from 12s to 1.4 seconds on my machine.
Decreases overall time needed for testing the trie package from 29.687s to 20.901s
=> trie: reduce unit test time

core/txpool/list.go, core/txpool/txpool.go, core/txpool/txpool2_test.go, core/txpool/txpool_test.go
split the pr in https://github.com/ethereum/go-ethereum/pull/26820
=> core/txpool: use atomic int added in go1.19

core/forkid/forkid_test.go, params/config.go
Schedules the shanghai hardfork on timestamp `1681338455` as discussed on ACDE 157 https://github.com/ethereum/execution-specs/pull/727
=> params: schedule shanghai fork on mainnet

core/vm/jump_table_export.go, params/config.go
This PR adds three methods to the public interface
```golang
func LookupInstructionSet(fork string) func() JumpTable
func (op *operation) Stack() (int, int)
func (op *operation) HasCost() bool
```
Often, when interacting with geth as a library to e.g. produce state tests, it is desirable to obtain the consensus-correct jumptable definition for a given fork. This is useful in e.g. goevmlab or fuzzyvm.
=> core/vm: expose jumptable constructors

core/rawdb/freezer_table.go
Seems the ancient reading meter is always 0, not updated
=> core/rawdb: update freezertable read meter

cmd/evm/runner.go, tests/state_test_util.go
fixes #26945 
now:
```
$ go run ./cmd/evm --dump --code 600060006000f0600060006009f06c63ffffffff6000526004601cf3600052600d60006000f0 --sender 0x71660c4005ba85c37ccec55d0c4493e66fe775d3 --receiver 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 --value 0 run
{
"root": "a7330b1fbb702ae9b10d3e6d37a39255c9351a19841bd54be4f04bc549330b93",
"accounts": {
"0x14d8508446f0786f5154b75b746fe3fe04962bb4": {
"balance": "0",
"nonce": 1,
"root": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
"codeHash": "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
"key": "0xc36daef8aefc43de60e819ebec2f14dcd549ec19b53c98e594d7b909e80eac84"
},
"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48": {
"balance": "0",
"nonce": 2,
"root": …
```
=> cmd/evm, tests: record preimages if dump is expected

docs/fundamentals/les.md, docs/interacting-with-geth/rpc/index.md
Note about non-functional light client appeared twice on `les` page - this PR removes one of the notes.
Also fixed typo "acceptds" --> "accepts"
=> [website]: rm duplicated note, fix typo

eth/api_backend.go, eth/gasprice/feehistory.go, eth/gasprice/feehistory_test.go, eth/gasprice/gasprice.go, internal/ethapi/api.go, internal/ethapi/backend.go, internal/ethapi/transaction_args_test.go, les/api_backend.go
This PR changes the input type to the backend/gas price oracle function for `FeeHistory` to `uint64`
The parameter is currently supplied via the API as `uint64`. Since the internal function casts it back to `uint64` in some places, this change is intended to move the cast into the function where it is actually used, so it's more obvious how it is handled.
=> eth/gasprice: change feehistory input type from int to uint64

ethclient/ethclient.go
`Client.SubscribeNewHead` returns **interface** wrapping concrete type `*ClientSubscription` returned from `Client.EthSubscribe`. On error-path `*ClientSubscription` is `nil` but interface-wrapping results in non-nil **interface** returned from `Client.SubscribeNewHead` (so it can't be relied upon to have `nil` value when `error` returned is not `nil`).
In practice, this leads to unpleasant bugs for people who don't strictly follow popular golang convention: _when func returns non-`nil` `error` - other arguments in return list should be treated as "undefined" (can't be relied upon to have specific values)_, for example https://github.com/decred/dcrdex/pull/2252.
This PR tries to address that.
=> ethclient: harden against returned interface misuse

core/state/database.go, core/state/state_object.go, core/state/statedb.go, core/state/trie_prefetcher.go, eth/protocols/snap/handler.go, light/trie.go, trie/secure_trie.go, trie/sync_test.go
Follow-up PR as discussed with @fjl during the review of #26934 : remove the `Try` prefix in `Try` accessors.
I haven't removed it in tries that don't implement `Trie` because it creates a big diff to replace the old semantics of e.g. `Get` with those of `TryGet`, especially in tests. I can do that if consistency is deemed to prime over review ease.
=> core/state, trie, ligth: remove Try prefix in Trie accessors

core/vm/evm.go, core/vm/instructions.go
split the pr in https://github.com/ethereum/go-ethereum/pull/26820
=> core/vm: use atomic.Bool

eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/js/goja.go, eth/tracers/js/tracer_test.go, eth/tracers/native/call.go, eth/tracers/native/prestate.go, eth/tracers/tracers.go, eth/tracers/tracers_test.go
Prevents tracer from crashing when logs are enabled and a LOG opcode would underflow the stack or access memory that hasn't been expanded yet.
Please let me know if this is the right approach.  If so, I will apply it across all tracers and write unit tests.
fixes https://github.com/ethereum/go-ethereum/issues/26845
=> core/vm,eth/tracers/native: prevent panic for LOG edge-cases

internal/debug/flags.go
Adds a `--log.logfmt` CLI option to configure logging to use the `logfmt` style. `logfmt` support is already built into the logging framework, but previously the setup code would only allow selecting between JSON format or terminal format.
The `--log.json` flag takes priority if both `--log.json` and `log.logfmt` is specified and the default log format is unchanged (terminal).
=> internal/debug: Add log.logfmt flag to set logging to use logfmt

.github/CODEOWNERS
I haven't touched this part of the codebase in years, never really used GraphQL in the meantime and @s1na is now the GraphQL man.
=> remove @gballet as a GraphQL codeowner

graphql/graphql.go
Ironic that https://github.com/ethereum/go-ethereum/pull/26965 introduced a data race. Problem is it caches the `stateObject` for each account. However stateObject is not thread-safe, even when used in read-only mode. The race specifically happens when multiple storage slots are queried. They will both will try to write to the stateObject's `originStorage` cache.
I temporarily reverted the change. But I'd still like the ability to cache a state object. It doesn't make sense IMO to hit the db/snapshot multiple times for the same account during one query. But not sure how to achieve that yet.
TODO: add test case.
=> graphql: revert storage access regression

internal/debug/flags.go
Removes the new log.logfmt and hides log.json, replacing both with log.format=(json|logfmt|terminal). The hidden log.json option is still respected if log.format is not specified for backwards compatibility.
=> cmd/geth: Add `--log.format` cli param

accounts/abi/bind/base.go, accounts/abi/bind/base_test.go
This PR adds error handling for the case that `UnpackLog` or `UnpackLogIntoMap` is called with a log that has zero topics.
Also moves errors from `fmt.Errorf(...)` with no formatted arguments to use `errors.New` and declare the errors at the top of the file.
=> accounts/abi/bind: handle UnpackLog with zero topics

cmd/evm/internal/t8ntool/transition.go
Currently the t8n tool uses the same block number for the current block and its parent while calculating the base fee. This causes incorrect base fee calculation for the London fork block.
This commit sets the parent block number to be one less than the current block number
=> cmd/evm: use correct parent number for t8n base fee calculation

common/path.go, p2p/server.go
Although the comment in `p2p` says it uses `common.MakeName` to create the p2p name of the node, the function is actually not used anywhere in the codebase. Instead, the name is set in `node/node.go`: https://github.com/ethereum/go-ethereum/blob/00a73fbcce3250b87fc4160f3deddc44390848f4/node/node.go#L134
where `NodeName()`is this function: https://github.com/ethereum/go-ethereum/blob/00a73fbcce3250b87fc4160f3deddc44390848f4/node/config.go#L290-L306
=> common: delete MakeName

.gitignore, go.mod, go.sum, internal/debug/flags.go
executing geth:
```
>> go-ethereum git:(lumberjack)
➜ ./build/bin/geth --mainnet --log.debug --syncmode snap --datadir data/ --log.folder "/var/folders/w0/bf3y1c7d6ys15tq97ffk5qhw0000gn/T/tmp.QRUj0o0w/"
INFO [03-09|17:57:12.531|geth/main.go:305] Starting Geth on Ethereum mainnet...
INFO [03-09|17:57:12.532|geth/main.go:315] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [03-09|17:57:12.533|cmd/utils/flags.go:1421] Maximum peer count                       ETH=50 LES=0 total=50
INFO [03-09|17:57:12.537|cmd/utils/flags.go:1840] Set global gas cap                       cap=50,000,000
INFO [03-09|17:57:12.543|eth/backend.go:127]      Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [03-09|17:57:12.543|core/rawdb/database.go:380] Using …
```
=> cmd/geth: enable log rotation

cmd/geth/accountcmd.go, cmd/geth/main.go, miner/stress/beacon/main.go, signer/core/uiapi.go
Fixes #27022
Note, it's just a quick fix to not crash geth, but the entire account management should 
be refactored. It's weird that there can be multiple backends with the same type, like
multiple local keystores.
=> cmd, miner, signer: avoid panic if keystore is not available

core/txpool/txpool.go, core/txpool/txpool_test.go
This PR is for discussion, I'm fine with not merging it if we choose to. 
Currently, we do most of transaction validation while holding the txpool mutex: one exception being an early-on signature check. This PR changes that, so that we do all non-stateful checks before we enter the mutex arena. This means they can be performed in parallel, and to enable that, certain fields have been made `atomic` bools and uint64. 
Right now, the PR does not remove those checks from the in-mutex-arena. This is because of some edge-cases that may happen around hardforks, and particularly when transactions are re-added due to a reorg, in which a transaction from a dropped block becomes invalid due to a change in the rules. I think maybe we don't need to cater for that particular edgecase, but I left it in …
=> core/txpool: move some validation to outside of mutex

core/vm/analysis.go
The reason for the modification is that the original comment mentioned "push zeroes onto the bitvector," which is not accurate. In this scenario, the algorithm sets bits (with a value of 1) on the bitvector, not pushing zeroes. This ensures that the algorithm can correctly mark the following 32 bytes as data.
=> core/vm: clarify comment

consensus/misc/eip4844.go, consensus/misc/eip4844_test.go, params/protocol_params.go
This is a tiny PR to merge in 4844 in small chunks. Since the blobpool will require a bunch of remotely related changes, I'm trying to get those in separately. This PR is the change needed to convert from a 4844 header's excess data gas field (which is a random consensus number) into a blob fee value (which is needed by the blob pool for validation).
The PR also contains a commit "faked" to be by @roberto-bayardo, since I copy pasted his test cases for the fake exponential calculation.
=> consensus/misc, params: add EIP-4844 blobfee conversions

cmd/evm/internal/t8ntool/execution.go, cmd/evm/internal/t8ntool/transition.go, cmd/evm/runner.go, cmd/evm/staterunner.go, core/blockchain.go, core/blockchain_test.go, core/state_transition.go, core/vm/evm.go, core/vm/instructions.go, core/vm/interpreter.go, core/vm/runtime/runtime_test.go, eth/tracers/api.go, eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/internal/tracetest/flat_calltrace_test.go, eth/tracers/internal/tracetest/prestate_test.go, eth/tracers/js/tracer_test.go, eth/tracers/logger/logger_test.go, eth/tracers/tracers_test.go, internal/ethapi/api.go, tests/state_test.go
Alternative to #27002 
This PR removes the `Debug` field from vmconfig, making it so that if a tracer is set, `debug=true` is implied.
=> all: remove debug-field from vm config

metrics/counter_float64.go, metrics/counter_float_64_test.go, metrics/gauge_float64.go, metrics/gauge_float64_test.go
This PR changes the gauge and counter of type f64 to use atomic instead of mutex.
BenchmarkCounterFloat64Pararel-32       186.0 ns/op
BenchmarkCounterFloat64Pararel-32       169.3 ns/op
BenchmarkGaugeFloat64Pararel-32         180.7 ns/op
BenchmarkGaugeFloat64Pararel-32         170.2 ns/op
=> metrics: make gauge_float64 and counter_float64 lock free

core/txpool/list.go, core/txpool/txpool.go, core/txpool/txpool2_test.go
This PR fixes two issues:
- Local transactions should not be subject to the `future shouldn't churn pending txs` rule
- Transactions are added to the queue first, and on the next reorg procedure promoted 
There's still an issue with this, as the rule can be gamed if the queue contains a real future transaction with nonce -1.
=> core/txpool: disallow future churn by remote txs

core/state_transition.go, miner/worker.go
This PR cleans up the commitTransaction function in miner/worker. 
Whenever the error occurs after running transaction, this transaction should be regarded 
as invalid and all following transactions from the same sender won't be executable because
of the nonce restriction.  The only exception is the `nonceTooLow` error.
This PR unifies the error handling in miner.
=> core, miner: drop transactions from the same sender when error occurs

params/bootnodes.go
Sepolia has had some peering troubles in the past, seems like running `./devp2p rlpx ping enode` against the existing sepolia bootnodes doesn't return a response (thanks @lightclient for bring that up and introducing me to the tool!). It seems like the old bootnodes weren't created properly or not added to the IaC stack we usually have our configs in, so I went ahead and setup new bootnodes on DigitalOcean. These have more liberal bandwidth limits and cost far lesser to run, they should be able to help with peering and sync performance on Sepolia. 
The bootnode configs have been commited to the private devops repo along with a reserved IP and the nodekey has been backed up. The bootnode has additionally been added to the DevOps monitoring and updating stack. We should be able to maintain …
=> params: new sepolia bootnodes

cmd/devp2p/crawl.go
When logging the info about the nodes, `added=... updated=... removed=... ignored(recent)=... ignored(incompatible)=...`
it was printing the same amount for the removed and the ignored(recent) nodes because the wrong variable was used
Just fixed that by logging the right variable
=> cmd/devp2p: crawler : fix log of ignored recent nodes counter

core/blockchain.go, core/state/snapshot/snapshot_test.go
Fix comment to reflect function name. 
Currently, geth uses `stop` instead of `stopWithoutSaving` in the comment description, which is incorrect.
Also pluralized the subject of the sentence in another comment to match the correct one. 
Correct: https://github.com/ethereum/go-ethereum/blob/master/core/state/snapshot/snapshot_test.go#L229
Incorrect: https://github.com/ethereum/go-ethereum/blob/master/core/state/snapshot/snapshot_test.go#L121
=> core: fix comment to reflect function name

docs/fundamentals/databases.md
I think there's a typo in the fundamentals docs [databases](https://geth.ethereum.org/docs/fundamentals/databases) page.
> Any deleted or **overwritte** items in that key range are removed and the surviving data is reorganized for efficiency.
=> [website]: fix databases "overwritten" typo

p2p/server.go
In this file, for the internal anonymous Config structure calls within the Server struct, some calls were made using 'srv.Config.xx', while others were made using 'srv.xx'. In order to unify the coding style, I have removed the calls to 'srv.Config.xx'.
=> p2p: access embedded fields directly

internal/debug/flags.go
Backwards compatibility for --vmodule is preserved if --log.vmodule isn't specified with a warning logged.
Follows up on a suggestion in #26970 so log related CLI args all start with `--log.`
=> cmd/geth: Rename --vmodule to --log.vmodule

core/rawdb/accessors_indexes_test.go, core/state/snapshot/conversion.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/sync_test.go, core/types/block_test.go, core/types/hashing.go, core/types/hashing_test.go, eth/protocols/snap/sync_test.go, les/server_handler.go, light/postprocess.go, light/trie.go, tests/fuzzers/les/les-fuzzer.go, tests/fuzzers/rangeproof/rangeproof-fuzzer.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/errors.go, trie/iterator_test.go, trie/proof.go, trie/proof_test.go, trie/secure_trie.go, trie/secure_trie_test.go, trie/stacktrie.go, trie/stacktrie_test.go, trie/sync_test.go, trie/tracer_test.go, trie/trie.go, trie/trie_test.go
In this PR, all TryXXX(e.g. TryGet) APIs of trie are renamed to XXX(e.g. Get) with an error returned.
The original XXX(e.g. Get) APIs are renamed to MustXXX(e.g. MustGet) which will panic in case any error occurs.
=> all: refactor trie API

trie/committer.go, trie/database.go, trie/iterator.go, trie/node.go, trie/node_enc.go, trie/nodeset.go, trie/proof.go, trie/stacktrie.go, trie/trie.go, trie/trie_reader.go
This PR reworks the trie database a bit to simplify things and make it be usable by verkle tree.
Trie database uses reference counter mechanism to prune stale nodes in memory. It relies on the references
between parent node and child nodes to determine if the node is already outdated.
However, the trie database is very MPT specific. For example, it maintains the MPT nodes directly and iterate
children of nodes with MPT rules. It will bring some performance speed up by avoiding node encoding/decoding.
But it's not abstract enough, and very unfriendly for new trie types, e.g. verkle tree.
In this PR, trie database will only maintain encoded node blobs with additional metadata(e.g the children hashes
node). In this way, trie database could be abstract enough to be used by different trie …
=> core, trie: rework trie database

p2p/discover/metrics.go, p2p/discover/v4_udp.go, p2p/discover/v5_udp.go
This PR adds similar to p2p/metrics metered connection for discovery module. The aim is to have more detailed information about network usage which currently isn't tracked for discV4 and discV5.
=> p2p/discover: add traffic metrics

graphql/graphql.go, graphql/graphql_test.go, graphql/schema.go
**Breaking-change** All number fields (Big, or Long) will be hex-formatted for consistency.
We had inconsistent formatting for outputs of `Long` fields. Some returned decimal numbers while others returned hex-encoded string. They were initially all hex-encoded and later some but not all were converted to Long: https://github.com/ethereum/go-ethereum/pull/21883. This prompted #26118.
I think we should move back to hex-encoding when returning longs and have created a PR to disambiguate formatting of Long fields in the spec: https://github.com/ethereum/execution-apis/pull/389. Inputs are now more flexible and will take decimal or string. String can be hex or decimal encoded. This will succeed https://github.com/ethereum/go-ethereum/pull/26730.
=> graphql: encode Long values as hex

eth/api_backend.go
=> eth: fix crash on querying finalized block

trie/committer.go, trie/database.go, trie/nodeset.go, trie/tracer.go, trie/trie.go, trie/trie_test.go, trie/trienode/node.go, trie/types/node.go
In trie/types package, a few node wrappers are defined, which will be used
in both trie package, trie/snap package, etc. Therefore, a standalone common
package is created to place these stuffs.
=> trie: add node type common package

cmd/evm/t8n_test.go, cmd/evm/testdata/1/exp.json, cmd/evm/testdata/13/exp2.json, cmd/evm/testdata/23/exp.json, cmd/evm/testdata/24/exp.json, cmd/evm/testdata/25/exp.json, cmd/evm/testdata/3/exp.json, core/types/gen_receipt_json.go, core/types/receipt.go, core/types/receipt_test.go
the execution api [spec](https://github.com/ethereum/execution-apis/blob/af82a989bead35e2325ecc49a9023df39c548756/src/schemas/receipt.yaml#L49) suggests receipt.EffectiveGasPrice should be required, but it's currently not tagged as required in its receipt.go schema. Further, the field is tagged as 'omitempty' in the generated code even though it's not tagged as such in the schema.
This PR leaves the field as untagged in the receipt.go schema for backwards compatibility, adds a comment clarifying it's still technically required, removes the omitempty discrepancy in the generated code, and adds/updates test cases to codify the untagged behavior of the field. 
Alternatives considered:
- tag as required in schema + generated code. Dismissed due to backwards compatilbity concerns as it could …
=> core/types: fix discrepancy in receipt.EffectiveGasPrice json encoding tags

light/lightchain.go
use atomic.Bool for switches in light.LightChain
=> light: use atomic type

p2p/discover/table_util_test.go, p2p/discover/v5_talk.go, p2p/discover/v5_udp.go, p2p/discover/v5_udp_test.go, p2p/discover/v5wire/msg.go
This changes TALKREQ message processing to run the handler on separate goroutine,
instead of running on the main discv5 dispatcher goroutine. It's better this way because
it allows the handler to perform blocking actions.
I'm also adding a new method `TalkRequestToID` here. This is needed for my work on
data transfers over discv5 in the [discv5-streams repo](https://github.com/fjl/discv5-streams).
The new method allows implementing a request flow where one node `A` sends TALKREQ to
another node `B`, and node `B` later sends a TALKREQ back. With `TalkRequestToID`, node `B`
does not need the ENR of `A` to send its request.
=> p2p/discover: concurrent TALKREQ handling

eth/api_backend.go, eth/tracers/api.go, ethclient/gethclient/gethclient.go, ethclient/gethclient/gethclient_test.go, graphql/graphql.go, internal/ethapi/api.go, internal/ethapi/api_test.go, internal/ethapi/backend.go, internal/ethapi/transaction_args_test.go, internal/web3ext/web3ext.go, les/api_backend.go
Adds an optional config parameter to `eth_call` which allows users to override block context fields (same functionality that was added to `traceCall` in https://github.com/ethereum/go-ethereum/pull/24871)
Also I've integrated some of the changes from https://github.com/ethereum/go-ethereum/pull/25743, specially some test cases and modification to `GetEVM`.
Fixes #24025.
=> internal/ethapi: add block overrides to eth_call

eth/downloader/downloader.go
This PR fixes an incorrect error aggregation in downloader.
Downloader has a few components used to sync up chain. Whenever an error occurs in any of
these components, the sync procedure needs to be aborted and the error is expected to be 
bubbled up. This error is an important marker, one use case is as an indicator if transactions
from network should be accepted or not.
However this error aggregation is wrong. Previously the aggregated error is always overwritten
by the returned value from components, but the fact is some components(e.g. processFullSyncContent)
won't return error in some cases.
This PR fixes this error, and I believe it can prevent accepting transactions when syncing.
=> eth/downloader: fix error aggregator

eth/tracers/api.go, eth/tracers/api_test.go
This PR modifies the interface for the results of debug_traceBlock and debug_traceCall by adding the txHash, allowing users to identify which transaction's trace result corresponds to. This was previously discussed in issue #20629, but there has been no further discussion since then.
=> eth/tracers: add `txHash` field on txTraceResult

cmd/utils/cmd.go
When the block import fails, the error displays the number of the first block past the import batch, not the number of the failing block. This PR fixes this problem by identifying which blocks fails and reporting its number.
=> cmd/utils: report the correct invalid block number in block import

core/state/iterator.go, core/state/iterator_test.go, core/state/sync_test.go
This is a prerequisite for #27209 : changing the interface in `OpenStorageTrie` to accept an address instead of an address hash. This interface change is needed for verkle trees, as the hashing algorithm used to find storage is not keccak.
The problem this PR addresses, is that the node iterator would require preimage usage to conform to this new interface. Luckily, the node iterator is only used in tests, so this preimage requirement can easily be enforced. For this to happen, though, the node iterator interface should be unexported, lest someone else starts using it in the meantime.
=> core/state: unexport NodeIterator

cmd/evm/internal/t8ntool/execution.go, cmd/evm/runner.go, core/genesis.go, core/state/snapshot/generate_test.go, core/state/state_test.go, core/state/statedb_test.go, core/state/sync_test.go, core/state/trie_prefetcher_test.go, core/txpool/txpool2_test.go, core/txpool/txpool_test.go, core/vm/gas_table_test.go, core/vm/instructions_test.go, core/vm/interpreter_test.go, core/vm/runtime/runtime.go, core/vm/runtime/runtime_test.go, eth/api_test.go, eth/fetcher/block_fetcher_test.go, eth/protocols/snap/sync_test.go, les/fetcher/block_fetcher_test.go, light/postprocess.go, miner/miner_test.go, tests/state_test_util.go, trie/iterator_test.go, trie/secure_trie_test.go, trie/sync_test.go
This PR fixes the empty trie initialization by using `types.EmptyRootHash`. But the `common.Hash` is still accepted in case we still use it somewhere else.
=> all: new empty trie with types.EmptyRootHash instead of null

core/types/gen_access_tuple.go, core/types/transaction.go, core/types/transaction_marshalling.go, core/types/tx_access_list.go, core/types/tx_blob.go
This PR removes the SSZ notions from the blob txs, fixes an RLP encoding issue in it (To not marked as nil-able). The PR also adds the code to marshal between JSON - blobtx and sorts that code a bit to follow a more logical layout of the fields.
=> core/types: un-ssz blob txs, add json marshalling and tweaks

crypto/kzg4844/kzg4844.go, crypto/kzg4844/kzg4844_ckzg_cgo.go, go.mod, go.sum
Updates c-kzg-4844 to the new release:
* https://github.com/ethereum/c-kzg-4844/releases/tag/v0.2.0
This new version requires G1 points be in Lagrange form.
=> crypto/kzg4844: upgrade c-kzg-4844 to v0.2.0

rpc/websocket.go
rpc: the default dialer for websocket should respect the proxy environment variables like "HTTP_PROXY"
By default `gorilla/websocket` did respect the `http_proxy` setting, but the `newClientTransportWS` function explicitly provide a `websocket.Dialer` without a Proxy which overwrites the default one.
- https://github.com/gorilla/websocket/blob/76ecc29eff79f0cedf70c530605e486fc32131d1/client.go#L140-L144
- https://github.com/ethereum/go-ethereum/blob/9ca84e6b0b8302a0834534f262d4d2dd232640c5/rpc/websocket.go#L221-L228
=> rpc: websocket should respect the "HTTP_PROXY" by default

tests/fuzzers/bn256/bn256_fuzz.go
This PR removes Gnark from the Pair fuzzer. Because gnark uses a different pairing algorithm, it might produce a different result than the other implementations. However this is not an issue, since the bilinearity of a pairing means both results are correct. 
In order to preserve some fuzzing of the gnark pairing, I added a fuzzer that fuzzes the pairingCheck function, which does a pairing and verifies that the result is not equal to one. This is the function we use in ethereum, the pairing algorithm is not under consensus, only the pairing check algorithm.
=> tests/fuzzers/bn256: add PairingCheck fuzzer

docs/developers/evm-tracing/basic-traces.md, docs/interacting-with-geth/rpc/ns-personal.md, docs/interacting-with-geth/rpc/pubsub.md
If `jsonrpc` is not given, JSONRPC will raise the error as below:
```bash
> {"id": 1, "method": "eth_subscribe", "params": ["newHeads"]}
< {"jsonrpc":"2.0","id":1,"error":{"code":-32600,"message":"invalid request"}}
```
=> website: add 'jsonrpc:2.0' in jsonrpc request

common/types.go, common/types_test.go, internal/ethapi/api.go, internal/ethapi/api_test.go
This PR implements the suggestion of #24406 to return the address as EIP-55 encoded when creating a new account.
=> internal/ethapi: make NewAccount return EIP-55 format

rpc/service.go
The first argument of a Pub/Sub function should not be a pointer to context.Context, otherwise it will be registered as a subscription and its corresponding callback.hasCtx==false. This results in the parameter not having the correct value when called.
The problem description of the old code is as follows:
1. Suppose we define a subscription method, the first parameter is *context.Context.
2. When executing serviceRegistry.registerName for service registration, the isContextType method returns true, and isPubSub returns true, making callback.isSubscribe==true.
3. In the makeArgTypes method, because the first parameter Type!=contextType, the previously created callback.hasCtx==false.
4. In the callback.Call method, because callback.hasCtx==false, the correct context.Context cannot be …
=> rpc: more accurate checking of callback/subpub method signatures

beacon/types/config.go, go.mod, go.sum
pr #27292 imports a wrong yaml package, we should use `gopkg.in/yaml.v3`
https://github.com/go-yaml/yaml#example
it also fixes a lint error for line 124
=> go.mod: use`gopkg.in/yaml.v3` instead of `github.com/go-yaml/yaml`

cmd/evm/internal/t8ntool/transaction.go, cmd/evm/internal/t8ntool/transition.go, consensus/beacon/consensus.go, consensus/clique/clique.go, consensus/ethash/consensus.go, core/genesis.go, core/state_processor.go, core/state_processor_test.go, core/txpool/txpool.go, core/types/transaction_signing.go, eth/catalyst/api.go, light/txpool.go, params/config.go, params/config_test.go
Certain parts of the code can get weird if some later forks are enabled (Shanghai) before earlier ones (Berlin). This can happen if the chain is full syncing but not yet done, yet we request a pending block.
This PR ties all timestamp based forks to London so that you can only ever enter Shanghai and later if London already passed. This should ensure that we cannot end up in a strange future fork whilst still processing historical blocks.
=> all: tie timestamp based forks to the passage of London

cmd/utils/cmd.go
data dir is empty when using dev mode.
```console
$ ./build/bin/geth --dev
WARN [05-16|21:41:40.685] Failed to get free disk space            path= err="failed to call Statfs: no such file or directory"
```
=> cmd/utils: don't check free disk space in dev mode

cmd/geth/consolecmd_test.go, internal/cmdtest/test_cmd.go, rpc/client.go
I'm running the tests in my dev machine(m1 mac air), and some test case failed
I ran the test cases on my local machine (macOS M1 Air) and found that some test cases could not be passed. 
> run with command:
```bash
go test ./cmd/geth/... -v 
```
> test case 1
```bash
test_cmd.go:241: killing the child process (timeout)
test_cmd.go:115: not enough output, got until ◊:
---------------- (stdout text)
---------------- (expected text)
◊undefined
--- FAIL: TestUnlockFlagPasswordFile (5.03s)
=== RUN   TestUnlockFlagPasswordFileWrongPassword
```
> test case 2
```basg
=== NAME  TestAttachWithHeaders
test_cmd.go:261: (stderr:42) Fatal: Failed to start the JavaScript console: Post "http://localhost:58843": context deadline exceeded
--- PASS: TestRemoteDbWithHeaders (10.14s)
=== NAME …
```
=> rpc,internal/cmdtest: increase timeout in tests

accounts/abi/abi.go, accounts/abi/abi_test.go, accounts/abi/error.go
- Modify ID type from `common.Hash` to `[]byte` in Error struct
- Add ErrorById
=> accounts/abi: add ErrorById

cmd/evm/internal/t8ntool/transition.go, core/state/dump.go, core/state/state_test.go
This PR fixes bug which null address is ignored while doing iterative dump.
Null address is excluded in the `jsonl` result, which makes preimage(null address) not included in the final output.
This PR also adds test for testing iterative dump functionality.
Iterative dump without the fix:
```
{"root":"0xd5710ea8166b7b04bc2bfb129d7db12931cee82f75ca8e2d075b4884322bf3de"}
{"balance":"22","nonce":0,"root":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","address":"0x0000000000000000000000000000000000000001","key":"0x1468288056310c82aa4c01a7e12a10f8111a0560e72b700555479031b86c357d"}
{"balance":"1337","nonce":0,"root":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash": …
```
=> core/state: do not ignore null addr while iterative dump

cmd/evm/staterunner.go
This PR implements a feature that is already present in both nethermind and besu: the ability to run several state-tests in one instance. 
For state-tests that are reasonably small, this makes a _huge_ difference. Here's 1000 executions of a state-test which has a run-length of merely `28` steps. 
```
Doing 1000 execs old style
real	0m55.600s
user	0m41.665s
sys	0m17.886s
Doing 1000 execs new style
real	0m1.400s
user	0m1.443s
sys	0m0.116s
```
Nearly one minute versus `<2seconds`. When running it in a fuzzing-setting, the speedups is less marked, somewhere in the `1x-2x` region. 
If the kzg stuff now has a static overhead, as suggested in https://github.com/ethereum/go-ethereum/issues/27258, this PR would definitely help (the fuzzer). Perhaps something similar can be done for `evm t8n` too. …
=> cmd/evm: make batched state-test execution possible

cmd/clef/main.go, cmd/devp2p/discv4cmd.go, cmd/devp2p/discv5cmd.go, cmd/devp2p/dns_cloudflare.go, cmd/devp2p/dns_route53.go, cmd/devp2p/dnscmd.go, cmd/devp2p/enrcmd.go, cmd/devp2p/internal/ethtest/chain.go, cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/transaction.go, cmd/devp2p/internal/ethtest/types.go, cmd/devp2p/internal/v4test/discv4tests.go, cmd/devp2p/keycmd.go, cmd/devp2p/nodesetcmd.go, cmd/devp2p/rlpxcmd.go, cmd/evm/internal/t8ntool/block.go, cmd/faucet/faucet.go, cmd/geth/chaincmd.go, cmd/geth/verkle.go, cmd/utils/cmd.go
Seems `errors.New` is super fast then the empty `fmt.Errorf`, here is an benchmark test case from https://blog.imberkay.com/errorsnew-vs-fmterrorf
```go
package main
import (
"errors"
"fmt"
"time"
)
func testErrors() error {
return errors.New("test errors package")
}
func testFmt() error {
return fmt.Errorf("test fmt package")
}
func main() {
repeat := 100000000
start := time.Now()
for i := 0; i < repeat; i++ {
testErrors()
}
duration := time.Since(start)
fmt.Println("errors.New", duration)
start = time.Now()
for i := 0; i < repeat; i++ {
testFmt()
}
duration = time.Since(start)
fmt.Println("fmt.Errorf", duration)
}
```
In my macbook air m1, the result as below:
```bash
$ go version
go version go1.20.3 darwin/arm64
$ go run t.go
errors.New 63.858083ms
fmt.Errorf 5.240530083s
```
=> cmd: use errrors.New instead of empty fmt.Errorf

ethclient/ethclient.go, ethclient/ethclient_test.go, event/feed_test.go
=> ethclient,event: replace noarg fmt.Errorf with errors.New

crypto/crypto.go, crypto/ecies/ecies.go, crypto/ecies/ecies_test.go, crypto/ecies/params.go, crypto/signature_cgo.go, crypto/signature_nocgo.go
=> crypto: replace noarg fmt.Errorf with errors.New

les/benchmark.go, les/catalyst/api.go, les/client.go, les/retrieve.go, light/trie_test.go, signer/core/signed_data.go, signer/core/uiapi.go, signer/rules/rules.go
=> les, signer, light: replace noarg fmt.Errorf with errors.New

internal/build/archive.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go, internal/ethapi/transaction_args_test.go, tests/fuzzers/trie/trie-fuzzer.go, tests/init_test.go, tests/rlp_test_util.go, tests/state_test_util.go
=> internal,tests: replace noarg fmt.Errorf with errors.New

consensus/clique/clique.go, consensus/ethash/consensus.go, consensus/misc/eip1559.go, eth/api.go, eth/backend.go, eth/catalyst/api.go, eth/filters/api.go, eth/filters/filter_system.go, eth/tracers/js/goja.go, eth/tracers/logger/logger_test.go, eth/tracers/tracers.go
=> eth,consensus: replace noarg fmt.Errorf with errors.New

accounts/abi/bind/backends/simulated.go, accounts/abi/reflect.go, accounts/abi/selector_parser.go, accounts/abi/type.go, accounts/abi/unpack.go, accounts/external/backend.go, accounts/keystore/account_cache_test.go, accounts/scwallet/securechannel.go, accounts/scwallet/wallet.go
=> accounts: replace noarg fmt.Errorf with errors.New

eth/filters/filter.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go, eth/filters/filter_test.go
Try to implement https://github.com/ethereum/go-ethereum/issues/15063 and discussed with @s1na, 
In the first phase, we want to make the `filter.Logs()` function returns a channel instead of a large array
=> eth/filters: retrieve logs in async

docs/interacting-with-geth/rpc/ns-eth.md
These methods are not standardized and should be documented as a geth eth extension.
=> website: docs for eth_getHeaderBy* methods

core/types/block.go
The `random` field is no longer considered for inclusion in the block, remove the related comment.
=> core/types: remove TODO that will never be done

event/feed.go
It seems make sense to include `etype` initialization logic in the 'init'. 
What do you think?
=> event: include Feed type fixation logic in `f.init`

internal/ethapi/api.go
closes #27308
- deserializes hex keys early to shortcut on invalid input
- re-use the account `storageTrie` for each proof for each proof in the account, preventing repeated deep-copying of the trie
Code smell: 
I duplicated the `proofList` type rather than making it public. Making it public seemed like the wrong choice, as it would result in panics on misuse. There is probably a better way to do this but I'm not sufficiently familiar with the codebase
=> internal/ethapi: prevent unnecessary resource usage in eth_getProof implementation

consensus/beacon/consensus.go, consensus/clique/clique.go, consensus/ethash/consensus.go, consensus/misc/eip1559.go, consensus/misc/eip1559_test.go, consensus/misc/eip4844.go, consensus/misc/eip4844_test.go, core/block_validator.go, core/types/block.go, core/types/gen_header_json.go, core/types/gen_header_rlp.go, eth/downloader/queue.go, params/protocol_params.go
This PR implements validating the excessDataGa and dataGasUsed fields of Cancun headers according to the updated spec per https://github.com/ethereum/EIPs/pull/7062.
=> consensus, core, eth/downloader, params: 4844 chain validation

core/block_validator.go, eth/downloader/queue.go, params/protocol_params.go
This PR adds the blob hash validations for the blob transactions. An open question however is whether setting to `to` field to `nil` should be rejected (as in the spec and PR currently), or whether the data type itself should be changed to never be able to be `nil`. I vote for the latter, but that needs a spec change.
=> core, eth/downloader, params: validate blob tx bodies

core/block_validator.go, core/types/receipt_test.go, core/types/transaction_marshalling.go, core/types/tx_blob.go, eth/downloader/queue.go
The current 4844 spec states that the data format of blob txs allows the `To` field to be `null`, but such transactions are rejected as invalid during block processing. This is a weird take (probably an omission to be fixed) since this essentially means that the `To` fields *cannot* be `null`, but rejects the fact later in the processing pipeline.
This PR changes the `To` field from `*common.Address` to `common.Address`. This will ensure that `nil` will never enter Geth inside a blob transaction. Interestingly, this PR can be merged even now without a spec change, since both versions of this (reject at parse time vs reject at interpretation time) have the same effect.
Still, would be nice to confirm in the spec that nilness should be forbidden altogether.
=> core, eth/downloader: validate blobtx.To at serialization time

p2p/discover/common.go, p2p/discover/table.go, p2p/discover/table_test.go, p2p/discover/table_util_test.go, p2p/discover/v4_udp.go, p2p/discover/v5_udp.go
This adds config parameters for basic node table settings. These settings were previously
hard-coded, and it was not easily possible to change them for experimentation.
=> p2p/discover: add Table configuration and Nodes method

core/state/state_object.go, light/trie.go, trie/secure_trie.go
Continuing with a series of PRs to make the `Trie` interface more generic, this PR moves the RLP encoding of storage slots inside the `secure_trie` and `light.Trie` implementations, as other types of tries don't use this.
This PR is still in draft, as the snapshot still uses RLP. While I think the snapshot should also get rid of RLP, this would cause a bunch of issues:
* rlp encoding would have to be added to the snapsync code
* an upgrade path needs to be devised
Until a solution has been found, this means the RLP decoding happens twice for a snapshot-enabled MPT client.
=> core/state: move slot RLP encoding into the MPT implementation

core/state/journal.go, core/state/statedb.go
This PR aligns the dirty marker behavior in state journal. It's OK to not mark it as dirty in resetObject, but would be nice to align the behavior with other changes.
=> core/state: mark account as dirty when resetObject occurs

eth/downloader/skeleton.go
Fixes https://github.com/ethereum/go-ethereum/issues/27386.
When a reorg happens, the beacon/skeleton syncer needs to stop, swap out it's internal state to the new head and restart. If the downloader is busy importing blocks in the mean time, it will prevent the beacon syncer from completing it's restart loop until all queued blocks are consumed.
During this "hang", any newly arriving newPayload or forckchoiceUpdate messages will get blocked as they cannot feed their respective new data to the beacon syncer. If the "hang" lasts 15 minutes, these update messages will keep piling and piling, consuming RAM and goroutines.
The PR "fixes" this issue by dropping update messages on the floor while in this limbo state. This should unblock engine API events and prevent bloat.
That said, it does …
=> eth/downloader: drop beacon head updates if the syncer is restarting

core/state/journal.go, core/state/statedb.go, core/state/statedb_test.go
It's a following PR based on https://github.com/ethereum/go-ethereum/pull/27339
Before byzantium fork, state root will be computed for each transaction. Specifically,
`IntermediateRoot` will be called at the end of transaction processing. Inside of it,
account/storage data will be cached if snapshot is available.
However, whenever account reset occurs, these cached state data should be cleared
out, otherwise we have no way to distinguish whether these data belongs to the
original one or the new one.
This PR fixes it by handling destruction at `CreateAccount` function.
=> core/state: clear out cached state data when reset occurs

cmd/evm/blockrunner.go, tests/block_test.go, tests/block_test_util.go
This PR fixes https://github.com/ethereum/go-ethereum/issues/27363, and spits out logs while the evm is executing
=> cmd/evm: make evm blocktest output logs if so instructed

core/txpool/txpool.go
This fix a minor implementation issue with the newly introduced isGapped function
and it is described in this ticket: https://github.com/ethereum/go-ethereum/issues/27401
=> core/txpool: fix isGapped implementation

graphql/graphql.go, graphql/graphql_test.go, graphql/schema.go
Currently waiting for spec PR to be merged.
=> graphql: implement withdrawals (EIP-4895)

eth/api_debug.go, internal/ethapi/api.go, internal/ethapi/api_test.go
It seems that there is no error return when marshal block to rpc type. Can we remove it?
=> internal/ethapi: remove error return value of RPCMarshalBlock

core/types/transaction_marshalling.go, core/types/transaction_test.go
When marshalling a legacy type transaction to JSON, the chain ID field is always omitted, despite the fact that it can be derived using the signature values after [EIP-155](https://eips.ethereum.org/EIPS/eip-155). 
This change adds the chain ID to a legacy transaction's JSON encoding when it can be derived. 
If the transaction is not signed or is pre EIP-155, the chain ID will be omitted.
=> core/types: add derived chain ID to LegacyTx JSON encoding

ethclient/ethclient.go, rpc/client.go, rpc/errors.go, rpc/handler.go, rpc/subscription.go
`ethclient.Client` has methods which're only valid when `isHTTP` is false(e.g.:`Subscribe`), thus it's convenient to expose a `IsHTTP` method so that users can do different things based on whether the underlying connection is http or not.
=> rpc: add method to test for subscriptions

cmd/faucet/faucet.go, cmd/geth/consolecmd.go, cmd/geth/main.go, console/console_test.go, ethclient/ethclient_test.go, ethclient/gethclient/gethclient_test.go, node/node.go, p2p/simulations/adapters/inproc.go
Delete the unused error from return parameters, because `Attach()` function no longer returns an error.
=> node: remove unused error return from Attach

core/blockchain.go
This PR removes an unnecessary copy from `bc.collectLogs`
=> core: remove unnecessary log copy

core/types/receipt.go
This PR fixes an issue which can happen on blob-tx-testnets, where we try to encode the receipt of a blob-transaction, but ends up writing nothing: which is "deletion" as far as the stacktrie is concerned, causing panic. 
This PR does two things: 
- Always write type first, thereby making sure that even unsupported things cause a write of at least one byte, 
- Add support for blob receipts. 
As for the second bullet, a different way of doing it would be to do what the transactions already does 
```golang
if tx.Type() == LegacyTxType {
rlp.Encode(w, tx.inner)
} else {
tx.encodeTyped(w)
}
}
func (tx *Transaction) encodeTyped(w *bytes.Buffer) error {
w.WriteByte(tx.Type())
return rlp.Encode(w, tx.inner)
}
```
Simply write `type ... rlp(data)` for typed data. That way we wouldn't have to …
=> core/types: ensure receipts EncodeIndex writes + support blobtx-receipts

rlp/encode.go, rlp/encode_test.go
=> rlp: fix typos

build/update-license.go
=> build: use slices package for sorting

core/txpool/legacypool/legacypool.go
Description
issue: https://github.com/ethereum/go-ethereum/issues/23690
Rationale
Because there is a memory leak on txpool priced urgent list, so force calls Reheap periodically on the txpool to evict old transactions from the priced list when London fork is not enabled.
=> core/txpool/legacypool: reheap the priced list if london fork not enabled

core/txpool/legacypool/legacypool.go
Fixes https://github.com/ethereum/go-ethereum/issues/27301
=> core/txpool/legacypool: handle missing head in reset

accounts/keystore/account_cache.go, accounts/keystore/account_cache_test.go, accounts/keystore/keystore_test.go
=> accounts/keystore: use slices package for sorting

common/types.go, consensus/clique/snapshot.go, consensus/clique/snapshot_test.go, console/console.go
=> consensus/clique: use slices package for sorting

core/state/database.go, core/state/snapshot/generate.go, core/state/statedb.go, eth/protocols/snap/handler.go, eth/protocols/snap/sync_test.go, internal/ethapi/api.go, les/handler_test.go, les/server_requests.go, light/odr_test.go, light/trie.go, tests/fuzzers/rangeproof/rangeproof-fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/proof.go, trie/proof_test.go, trie/tracer_test.go, trie/trie_test.go
This PR removes the "unused" feature in trie prover by specifying the start level for collecting nodes as proof.
The main motivation for this PR is
- this feature is not used, even in LES
- this notion is a bit weird in mpt/verkle, we always expect the complete proof(please correct me if I am wrong, @gballet )
=> trie: remove prover parameter 'fromLevel'

common/types.go, eth/api_debug_test.go, eth/fetcher/tx_fetcher.go, eth/gasprice/feehistory.go, eth/gasprice/gasprice.go, eth/protocols/snap/sync_test.go, eth/tracers/api_test.go
Also adds Hash.Less method.
See #27474
=> eth: use slices package for sorting

internal/build/util.go
In macOS, there may exist hidden [`.DS_Store`](https://en.wikipedia.org/wiki/.DS_Store) files inside some directories. These are filesystem metadata files created by Finder.
If one of these `.DS_Store` files is inside the [./cmd](./cmd) directory, then running `make test` will fail with an error:
```bash 
$ make test
env GO111MODULE=on go run build/ci.go install  
util.go:202: fdopendir cmd/.DS_Store: not a directory  
exit status 1
make: *** [all] Error 1
```
This happens because the Go build tools try to process all files in the [./cmd](./cmd) directory, including the `.DS_Store` file, resulting in an error.
To fix this, we can ignore any files when parsing the package directory.
=> internal/build: ignore some files in FindMainPackages

core/txpool/txpool.go
This function was added in Go 1.20, but our compatibility target is Go 1.19.
=> core/txpool: remove use of errors.Join function

ethdb/pebble/pebble.go
This is likely the culprit behind several data corruption issues, e.g. where data has been written to the freezer, but the deletion from leveldb does not go through due to process crash. 
Pebble has pretty strange sync options:
- `sync=true`: writes to the WAL are flushed to OS, and fsync:ed to disk. 
- `sync=false`: writes to the WAL are in-mem, and flushed to OS at some future time. 
Out of durability guarantees, 
1. Even if the OS crashes, written batches are written
2. Even if process crashes, written batches are written
3. Batches are written sometime, at latest on controlled shutdown. 
With leveldb, we could choose to land on `2`: survive process crash, but potentially corrupt data on os crash. With pebble, it's either option `1` or `3`. Current master uses `3`.
This PR uses option …
=> ethdb/pebble: sync pebble writes

p2p/discover/v4_udp.go
This PR swaps the order of ping verification. 
In all other UDPv4 methods, the deadline is checked first. It seems weird to me that ping is an exception. Deadline comparison is also less resource intensive.
=> p2p/discover: swap verification order in discv4 ping handler

core/state/database.go, core/state/statedb.go, light/trie.go, trie/secure_trie.go
Rationale: verkle trees store the code inside the trie. This PR changes the interface to pass the code, as well as the `dirty` flag to tell the trie package if the code is dirty and needs to be updated. This is a no-op for the MPT and the odr trie.
=> core/state, light, trie: add UpdateContractCode to the Trie interface

crypto/secp256k1/secp256.go
NDEBUG can be defined in some architechtures, by checking it with ifndef we avoid compiler warning problems, such as:
```
Error: ../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/crypto/secp256k1/secp256.go:28:9: warning: 'NDEBUG' macro redefined [-Wmacro-redefined]
```
=> crypto/secp256k1: define NDEBUG only if not defined

core/vm/opcodes.go
See also https://eips.ethereum.org/EIPS/eip-1153
b3 -> 5c 
b4 -> 5d
=> core/vm: move TSTORE,TLOAD to correct opcode nums

common/lru/basiclru_test.go
We don't have test that Peek() function doesn't affect to recent-ness.
Reference: https://github.com/hashicorp/golang-lru/blob/master/simplelru/lru_test.go#L154
=> common/lru: Add BasicLRU.Peek testcase

core/blockchain.go
This PR adds an error log in a case where the error was previously unchecked. This error should never happen and the error message is copied from https://github.com/ethereum/go-ethereum/blob/v1.12.0/core/rawdb/accessors_chain.go#L647
=> core: log message if DeriveFields returns error

core/state/database.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/state_object.go, core/state/statedb.go, eth/protocols/snap/sync_test.go, light/postprocess.go, light/trie.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/iterator_test.go, trie/secure_trie.go, trie/secure_trie_test.go, trie/sync_test.go, trie/tracer_test.go, trie/trie.go, trie/trie_test.go
This has been discussed with @rjl493456442 : the `error` result was removed from `(*state.Trie).Commit` as no error could occur in the MPT's `Commit` function. In verkle, however, errors can happen and should be reported.
=> trie, core/state: revert error removal in (*state.Trie).Commit

core/blockchain_reader.go, core/state/database.go, core/state/iterator.go, core/state/state_object.go, core/state/sync_test.go, core/state/trie_prefetcher.go, les/benchmark.go, les/handler_test.go, les/odr_requests.go, les/request_test.go, les/server_handler.go, les/server_requests.go, light/odr.go, light/odr_test.go, light/trie.go, tests/fuzzers/les/les-fuzzer.go, trie/database_wrap.go
Like the previous changes to the `state.Trie` interface, in which functions were modified to use the un-hashed account address instead of its hashed version, the same thing needs to be applied to `ContractCode` since it takes the hash of the account's address as a parameter.
The only major problem is with LES: I have changed the request object to contain the un-hashed address instead of its hash.
Alternatively, it seems to me that this parameter is only used in LES. If we remove LES, then we can remove this parameter entirely.
=> core/state, light, les: make signature of ContractCode hash-independent

cmd/clef/main.go, cmd/utils/flags.go, internal/debug/flags.go, node/config.go, node/rpcstack.go
now we use `net.JoinHostPort` combines host and port into a network address of the form "host:port". If host contains a colon, as found in literal IPv6 addresses, then JoinHostPort returns "[host]:port".
=> node: allow listening on IPv6 address (#27628)

cmd/devp2p/internal/ethtest/suite_test.go, cmd/geth/config.go, cmd/geth/snapshot.go, cmd/utils/flags.go, cmd/utils/flags_legacy.go, core/blockchain.go, core/state/pruner/pruner.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, graphql/graphql_test.go, tests/fuzzers/snap/fuzz_handler.go, trie/database.go
The clean trie cache is persisted periodically, therefore Geth can 
quickly warmup the cache in next restart.
However it will reduce the robustness of system. The assumption is
held in Geth that if the parent trie node is present, then the entire 
sub-trie associated with the parent are all present.
Imagine the scenario that Geth rewinds itself to a past block and 
restart, but Geth finds the root node of "future state" in clean 
cache then regard this state is present in disk, while is not in fact.
Another example is offline pruning tool. Whenever an offline pruning
is performed, the clean cache file has to be removed to avoid hitting
the root node of "deleted states" in clean cache.
All in all, compare with the minor performance gain, system robustness
is something we care more.
=> cmd, core, eth, graphql, trie: no persisted clean trie cache file

ethdb/leveldb/leveldb.go
This PR implements feature described in #27497 
Additionally, it includes a small refactor of the meter method to be more future-proof.
=> ethdb/leveldb: update leveldb metrics collection

core/blockchain_test.go
Adds calls for chain.Stop() to tests that call NewBlockChain
=> core: stop chain when tests are finished

signer/core/api.go, signer/fourbyte/fourbyte.go
When developers first encounter Clef, they might fall into confusion due to failure, possibly because they didn't carefully read the documentation. Therefore, it would be beneficial to supplement information directly in the 'message.Warn'.
like https://github.com/ethereum/go-ethereum/issues/27528
=> signer/core: Extended logInfo for clef

eth/handler.go, eth/protocols/eth/handshake.go, eth/protocols/eth/metrics.go, eth/protocols/snap/metrics.go, p2p/dial.go, p2p/discover/metrics.go, p2p/discover/table.go, p2p/discover/v4_udp.go, p2p/discover/v4_udp_test.go, p2p/discover/v5_udp.go, p2p/metrics.go, p2p/server.go, p2p/server_test.go
This PR adds metrics for the p2p dialer, which gives us visibility into the quality of the dial candidates given to us by our discovery methods. This isn't quite a full picture though, because often once the dial completes, the subprotocols will then perform their handshakes. These frequently fail for a multitude of reasons: wrong chain, too many peers, etc. That isn't shown with these metrics. ~This is the reason the "success" rate seems very high for a rather low peer count. Using discv4, around 28% we can connect to on RLPx, but many of them immediately disconnect during `eth` handshaking~ (fixed by tracking errors during handshake). With DNS discovery, the number is much lower because (presumably) they're already maxed out on peers due to the constant barrage of ingress connection …
=> p2p, p2p/discover: add dial metrics

core/block_validator_test.go, core/txpool/legacypool/legacypool_test.go
Example failure on CI: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/47472592/job/sef9xwbf62hggx6t#L792 
Back before this commit: https://github.com/ethereum/go-ethereum/pull/27178/files#diff-0f667480e9ac227fc480354104860f0b690105077fde5d35e0903b6e4ba88857L137  , we spun up a number of ethash verifiers to verify headers. So we also had tests to ensure that we were indeed able to abort verification even if we had multiple workers running. 
With PR #27178, we removed the parallelism in verification, and these tests are now failing, since we now just sequentially fire away the results as fast as possible on one routine.
This PR removes the (sometimes failing) tests
=> core: remove outdated tests

public/docs/vulnerabilities/vulnerabilities.json
The vulnerability-info had been touched by two prettyfying-operations, which made it not checkable: 
```
$ geth version-check
INFO [07-07|09:48:06.746] Checking vulnerabilities                 version=Geth/v1.12.1-unstable-b45fa869-20230706/linux-amd64/go1.20.1 url=https://geth.ethereum.org/docs/vulnerabilities/vulnerabilities.json
INFO [07-07|09:48:07.317] Verification failed error                keyid=FB1D084D39BAEC24 error="Invalid signature"
```
This PR reverts the changes made in https://github.com/ethereum/go-ethereum/commit/27769604a3afc0332376039b6a71f4fc434b718f and https://github.com/ethereum/go-ethereum/commit/6a05a9dbecdcdcaae8e3d247504451597078fd4b 
After reverting it: 
```
geth version-check --check.url=file:///home/user/go/src/github.com/ethereum/go-ethereum/public/docs/vuln …
```
=> fix vulnerability-file

docs/fundamentals/command-line-options.md, docs/fundamentals/mining.md, docs/interacting-with-geth/rpc/ns-miner.md
Removes threads arg from `miner.start()` and removes ethash cli flags from the `command line arguments` page.
Seems like there might be some more info that needs to change resulting from https://github.com/ethereum/go-ethereum/pull/27178 ? @lightclient
=> [website]: remove some ethash info from docs

core/vm/jump_table.go, core/vm/jump_table_export.go, tests/init.go
This PR enables 1153, TSTORE/TLOAD for Cancun, and also "defines" `Cancun` for tests. 
With this PR, this test for 1153 works fine: https://github.com/ethereum/tests/blob/f0f23929eac50c2eb898b2949efc48b253ed84a7/EIPTests/StateTests/stEIP1153-transientStorage/03_tloadAfterStoreIs0.json . 
Nothing special about that test, just a random one I picked as a sanity-check.
=> core/vm: define cancun + enable 1153 (tstore/tload) in cancun

eth/handler.go, eth/handler_eth.go, eth/sync.go
fixes #27509
Wasn't able to reproduce the original race condition, but this does remove the `WaitGroup`, so it should suffice.
The idea here is to use two unbuffered channels to track active protocol handlers. `handlerStartCh` is called when a new protocol handler is started up, as long as we aren't actively quitting. When the handler closes, it writes to `handlerDoneCh`.
A separate goroutine watches theses channels and converts the writes into an integer tracking the total number of active routines. When quit is initiated, it waits until the active count goes down to zero before exiting, thus releasing the overarching `handler.wg`.
=> eth: better active protocol handler tracking

core/state/dump.go, core/state/journal.go, core/state/metrics.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/state_object.go, core/state/state_test.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, core/state/statedb_test.go, core/types/state_account.go, eth/protocols/snap/sync_test.go, light/postprocess.go, light/trie.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/database.go, trie/iterator_test.go, trie/secure_trie_test.go, trie/sync_test.go, trie/tracer_test.go, trie/trie_test.go, trie/trienode/node.go, trie/triestate/state.go
This PR tracks the state changes in statedb. 
The change set can be used to build the state history in path-based storage scheme
for state rollback and archive state serving.
=> all: track state changes in state db

console/console_test.go
In #27152 , I found that some goroutines that are not expected to be leaked (instead of cache-related global routines mentioned in #27247) existing blocking here:
```
[Goroutine 27 in state select, with github.com/ethereum/go-ethereum/rpc.(*Client).dispatch on top of the stack:
goroutine 27 [select]:
github.com/ethereum/go-ethereum/rpc.(*Client).dispatch(0xc0015a0080, {0x185ade0?, 0xc00043e300})
/tool/go-ethereum/rpc/client.go:619 +0x2b7
created by github.com/ethereum/go-ethereum/rpc.initClient
/tool/go-ethereum/rpc/client.go:259 +0x311
```
This pr fix it by closing it in `t.Cleanup` to avoid leaks in any cases.
=> console: add cleanup to avoid leaks in newTester

core/rawdb/freezer.go, core/rawdb/freezer_table.go, core/rawdb/freezer_table_test.go, core/rawdb/freezer_utils.go, ethdb/database.go
This PR lets freezer to perform batch read without size limitation.
Nowadays, it's a bit painful if users want to batch-read from multiple freezer tables
without knowing the accurate size requirement for each table. It might happen that
the items read from different tables are different. In this case, truncation is required
to align the items returned from different tables as a whole.
This feature can be useful if users are aware that out-of-memory will not happen
(e.g. read only 1k elements)
TODO
=> core/rawdb: support freezer batch read with no size limit

p2p/discover/table.go
This prevents an issue where the node would attempt to contact the bootstrap nodes even if they weren't contained in the netrestrict list.
Fixes #27668
=> p2p/discover: filter bootnodes by netrestrict

graphql/graphql_test.go
Log of the race:
```console
Write at 0x00010267cf48 by goroutine 30:
github.com/ethereum/go-ethereum/graphql.newGQLService()
/Users/sina/dev/go/src/github.com/ethereum/go-ethereum/graphql/graphql_test.go:457 +0x31d
github.com/ethereum/go-ethereum/graphql.TestWithdrawals()
/Users/sina/dev/go/src/github.com/ethereum/go-ethereum/graphql/graphql_test.go:383 +0x4b1
testing.tRunner()
/usr/local/Cellar/go/1.19.3/libexec/src/testing/testing.go:1446 +0x216
testing.(*T).Run.func1()
/usr/local/Cellar/go/1.19.3/libexec/src/testing/testing.go:1493 +0x47
Previous read at 0x00010267cf48 by goroutine 44:
github.com/ethereum/go-ethereum/consensus/beacon.IsTTDReached()
/Users/sina/dev/go/src/github.com/ethereum/go-ethereum/consensus/beacon/consensus.go:457 +0x64 …
```
=> graphql: fix race in withdrawals test

internal/ethapi/api.go
In the eth backend, the `GetTransaction` will always return nil error, but the tx maybe is null, so we don't have to continue the following logic if tx notfound
https://github.com/ethereum/go-ethereum/blob/4b06e4f25e9a97880ddf834b571b05a59fa1290c/eth/api_backend.go#L316-L319
=> internal: fast exit if getTxReceipt notfound

eth/tracers/logger/logger.go
This PR fixes a bug, where the tracer was used through RPC return data of calls were being reported even if user configured `enableReturnData: true`. Return data will be formatted as a hex string.
=> eth/tracers: add ReturnData in the structLogger tracer's response

eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/native/call.go, eth/tracers/native/prestate.go
We've run into a panic mentioned in https://github.com/ethereum/go-ethereum/issues/26845 inside the prestate tracer, not that https://github.com/ethereum/go-ethereum/pull/26848 fixed the issue in `callTracer` but did not fixed the `prestateTracer` issue also mentioned in the original issue, this PR goes back and fixes that as well.
However, I'm not sure what I should do, if anything, with the returned error, since `CaptureState` doesn't return an error itself.  Looks like `tracers.GetMemoryCopyPadded` only really fails if the arguments are wrong or the copy is more than 1024KB, in which sae I personally think it's ok to `panic(err)` but wanted to discuss before doing so.
Also unsure if there should have been a unit test to cover this, FWIW this is the payload we hit on goerli to get a …
=> eth/tracers/native: panic on memory read in prestateTracer

cmd/geth/main.go, go.mod, go.sum
As discussed with @rjl493456442 offline, if Geth was running in a container with CPU quota(set with cgroup limiting), and `runtime.NumCPU` returns the host's CPU cores(maybe bigger than the docker's setting), which may result in more Golang runtime schedule and context switch. 
So I'm using the [uber/atomaxprocs](https://github.com/uber-go/automaxprocs) package to return the correct cpu quota.
=> cmd/geth: use automaxprocs to apply cpu quota correctly

accounts/abi/bind/backend.go, cmd/evm/internal/t8ntool/execution.go, core/state/journal.go, core/state/state_object.go, core/state/state_test.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, core/state/statedb_test.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/interface.go, core/vm/operations_acl.go, eth/tracers/native/call_flat.go, tests/state_test_util.go
also, it removes a check for `nil` `stateObject` return within `StateDB.SelfDestruct`: the address is that of the currently-executing contract so the corresponding `stateObject` is guaranteed to exist.
=> core:  replace instances of 'suicide' with 'selfdestruct' to improve code consistency.

cmd/evm/staterunner.go, core/block_validator.go, core/error.go, core/evm.go, core/gen_genesis.go, core/genesis.go, core/state_processor.go, core/state_processor_test.go, core/state_transition.go, core/vm/evm.go, tests/gen_sttransaction.go, tests/state_test.go, tests/state_test_util.go
This PR pulls the latest tests, and also the latest "eip tests" -- tests not for general consumption yet, but which are slated for a future fork. It also contains some necessary changes to statetests, state processing and errors, to handle fields related to 4844. 
It passes the `MCOPY` and `TSTORE/TLOAD` tests, but fails a couple of `BLOBHASH` tests. These tests seem to be erroneously generated, as the geth stateroot matches besu.   
```
--- FAIL: TestState (0.00s)
--- FAIL: TestState/opcodeBlobhashOutOfRange.json (0.01s)
--- FAIL: TestState/opcodeBlobhashOutOfRange.json/Cancun/0/trie (0.00s)
state_test.go:110: post state root mismatch: got 579ea25b3ac839988eb9aab1f65c92d93031b4635767db7add0d94b6481952ca, want 9deeea534f5391503ba1116a4970f4a9264d5c2038426eb8a5092eea4146fc9d …
```
=> tests: update for cancun

core/state/state_object.go, core/state/statedb.go, core/vm/eips.go, core/vm/instructions.go, core/vm/interface.go, core/vm/jump_table.go
[EIP-6780](https://eips.ethereum.org/EIPS/eip-6780): SELFDESTRUCT only in same transaction
> `SELFDESTRUCT` will recover all funds to the caller but not delete the account, except when called in the same transaction as creation
---
I'm taking a stab at this (probably broken atm.  needs to be verified with tests)
=> core/state, core/vm: implement EIP 6780

beacon/engine/gen_ed.go, beacon/engine/gen_epe.go, beacon/engine/types.go, eth/catalyst/api.go, eth/catalyst/api_test.go, eth/catalyst/simulated_beacon.go, miner/payload_building.go
This is a spin-out from the EIp-4844 development branch, containing just the Engine API modifications
and nothing else. The newPayloadV3 endpoint won't really work in this version, but we need the data structures
for testing so I'd like to get this in early.
=> beacon/engine, eth/catalyst: EIP-4844 updates for the engine API

cmd/evm/testdata/3/readme.md, cmd/evm/testdata/4/readme.md, cmd/evm/testdata/8/readme.md, cmd/evm/testdata/9/readme.md
Hey :wave:,
This PR will fix :
1 typo in `cmd/evm/testdata/3/readme.md`
1 typo in `cmd/evm/testdata/4/readme.md`
1 typo in `cmd/evm/testdata/8/readme.md`
1 typo in `cmd/evm/testdata/9/readme.md`
Best!
=> cmd/evm/testdata: fix typos in docs

cmd/evm/internal/t8ntool/execution.go, cmd/evm/runner.go, core/blockchain.go, core/blockchain_test.go, core/chain_makers.go, core/genesis.go, core/state/dump.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/state_object.go, core/state/state_test.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, core/state/statedb_test.go, core/state/sync_test.go, eth/api_debug_test.go, eth/protocols/snap/sync_test.go, eth/state_accessor.go, light/postprocess.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, tests/state_test_util.go, trie/database.go, trie/iterator_test.go, trie/secure_trie_test.go, trie/sync_test.go, trie/tracer_test.go, trie/trie_test.go
This PR exposes the associated block number of state transition to statedb,
and be stored in state history (in following PR). It's more like a prerequisite 
step for path-based storage PR.
=> all: expose block number information to statedb

crypto/kzg4844/kzg4844.go, crypto/kzg4844/kzg4844_ckzg_cgo.go, crypto/kzg4844/kzg4844_test.go
* Add `ckzgIniter.Do(ckzgInit)` call to all c-kzg functions.
* Add `b.ResetTimer()` in benchmarks for accuracy.
* Delete some unnecessary blank lines for consistency.
* Fix a minor typo in a comment.
=> crypto/kzg4844: do lazy init in all ckzg funcs

core/types/block.go
Hi. Seems the header deep copy should also deep copy the new 4844 fields.
=> core/types: deepcopy ExcessDataGas, DataGasUsed

consensus/beacon/consensus.go, consensus/misc/eip4844/eip4844.go, consensus/misc/eip4844/eip4844_test.go, core/blockchain.go, core/rawdb/accessors_chain.go, core/state_processor_test.go, core/state_transition.go, core/types/gen_receipt_json.go, core/types/receipt.go, core/types/receipt_test.go, light/odr_util.go
This pulls in receipt changes from the 4844-devnet-7 branch.
=> core/types: add data gas fields in Receipt

core/types/gen_receipt_json.go, core/types/receipt.go
Found error while updating hive simulator: `math/big: cannot unmarshal "\"0x1\"" into a *big.Int`
This change fixes the error.
=> core/types: fix receipt blob fields marshaling

eth/api_debug.go
fix by staticcheck
https://staticcheck.dev/docs/checks/#QF1003
=> eth: conver if-else-if chain to tagged switch

core/state_transition.go
We should check ExcessBlobGas before `buyGas`, or else an nil pointer error is occurred
=> core: check excessBlobGas in front

core/state/journal.go, core/state/state_object.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, trie/triestate/state.go
This PR tracks state change set with account address instead of addrHash.
The benefits of this changes are:
- address is shorter than address hash, can save 12 bytes for each account
- address is human-readable
Although it will cause inconsistency, because storage slots are still identified by
slothash. The reason of using hash for slot is: when the entire storage is nuked,
slots has to be iterated from trie, and only slot hash is available there(it's a pain).
=> core, trie: track state change set with account address

cmd/bootnode/main.go
To avoid the `port already listening` error when restarting a node, it's recommended to use a defer statement to close the UDP connection when the node goes into shutdown. This way, when the node is booted again, the error won't be encountered.
=> fix: missing close udp connection

build/ci.go, tests/state_test.go
Our windows `386` builds are timing out on appveyor, on the individual test exceeding 10 minutes
```
panic: test timed out after 10m0s
running tests:
TestState (10m0s)
TestState/stLogTests/log4_MaxTopic.json (0s)
TestState/stLogTests/log4_MaxTopic.json/London/0/trie (0s)
TestState/stMemoryTest/buffer.json (14s)
TestState/stMemoryTest/buffer.json/Merge/334/snap (0s)
```
This PR splits up the tests execution, might make it work again.
=> tests: make tests pass on windows/386

cmd/geth/main.go
Disable the annoying automaxproc logs
eg: 
```bash
$ ./build/bin/geth --version
2023/07/31 14:30:26 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
geth version 1.12.1-unstable-xyz
```
Ref https://github.com/uber-go/automaxprocs/issues/18
And we only set CPU limit in geth main process
=> cmd/geth: disable automaxprocs log

eth/protocols/snap/sync.go
Fixes https://github.com/ethereum/go-ethereum/issues/27813.
The closure caused all subtasks to reference the same one batch when writing, so instead of each subtask of a contract growing and flushing it's own batch, they all grew the last one's, but flushed their own.
Interestingly however, this should only be an issue if there's also a lack of peers, otherwise whenever a delivery into the last batch is made, it should have flushed out everyone else's data too.
Edit: Actually, it might happen that the last chunk finishes earlier than the rest, which will cause memory to keep piling there. This will result in the node growing in memory until the pivot moves and sync restarts. This was confirmed via a bench pair comparing master (yellow) with PR (green):
Additionally, this might also mean …
=> eth/protocols/snap: fix batch writer when resuming an aborted sync

docs/fundamentals/node-architecture.md
Since there is no specification specified at https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md , hence it is good to point to https://github.com/ethereum/execution-apis/blob/main/src/engine where user can view the documentation.
=> Update the Engine-API Specification

core/types/block.go
This change rearranges the accessor methods in block.go and fixes some minor issues with the copy-on-write logic of block data. As a refresher, the rules around block immutability are as follows:
- We copy all data when the block is constructed. This makes the references held inside the block independent of whatever value was passed in.
- We copy all header data on access. This is because any change to the header would mess up the cached hash and size values in the block. Calling code is expected to take advantage of this to avoid over-allocating!
- When new body data is attached to the block, we create a shallow copy of the block. This ensures block modifications are race-free.
- We do not copy body data on access because it does not affect the caches, and also because it would be too …
=> core/types: fix immutability guarantees in Block

accounts/abi/bind/template.go, accounts/abi/error.go, core/vm/runtime/runtime_test.go
This PR removes trailing wspace from `accounts/abi/bind/template.go` and `core/vm/runtime/runtime_test.go`,
also removes double wspace from a comment in `accounts/abi/error.go`
=> all: remove trailing whitespace

graphql/graphql.go, internal/ethapi/api.go
The gas price is the smallest out of the gasTipCap + base fee, and the overall gasFeeCap.
=> internal/ethapi, graphql: correct comments about gas price logic

graphql/graphql.go, internal/ethapi/api.go, internal/ethapi/api_test.go, internal/ethapi/transaction_args.go, internal/web3ext/web3ext.go
=> ethapi: add state override to estimateGas

docs/tools/clef/rules.md
Fixed the invalid if statement by removing the extra closing parenthesis of the if statement in the rules example of Clef. website/docs/tools/clef/rules.md
=> Website fixed Clef rules js example

graphql/graphql.go
The graphql code greedily allocated for the response. A query such as 
``` 
{ "query": " { blocks(from:-2147483647 to:2147483647) {number hash parent { number hash } }}" }
```
Would thus instantly allocate space for 4 Bn pointers, going out of memory. 
With this change, it will still go out of memory, but much slower. 
A more rigorous fix requires us to add limits, so that anything which returns `a list of things` is capped at some point. 
----
PSA: Graphql is not secure, it should not be exposed in untrusted environments, such as the internet.  This has been said before, and apparently cannot be said too often.
=> graphql: don't allocate greedily

core/state/statedb.go
Context: The `UpdateContractCode` method was introduced for the state storage commitment schemes that include the whole code for their commitment computation. It must therefore be called before the root hash is computed at the end of `IntermediateRoot`.
This should have no impact on the MPT since, in this context, the method is a no-op.
=> core/state: move UpdateContractCode before the trie hash is computed

accounts/abi/bind/backends/simulated.go, core/rawdb/accessors_chain.go, core/rawdb/accessors_chain_test.go, eth/api_backend.go, eth/filters/filter.go, eth/filters/filter_system_test.go
This PR removes a chainconfig parameter passed into `rawdb.ReadLogs`, which is not used nor needed. 
It also modifies the filter loop slightly, avoiding a labeled break and instead using a method. 
None of the changes in this PR  (intentionally) modify behaviour.
=> eth/filters, core/rawdb: remove unused param, refactor filtering-loop

graphql/graphql.go
Block takes a `number` and a `hash`. The spec is unclear on this. My interpretation is either of these should be provided and we should error in case both are passed in.
Fixes https://github.com/ethereum/go-ethereum/issues/25899
=> graphql: validate block params

core/txpool/blobpool/metrics.go
Created this PR per https://github.com/ethereum/go-ethereum/issues/27900. I am running telegraf as a prometheus server and unable to scrape metrics because the blobpool metrics does not conform to Prometheus metrics naming standards. Please refer to https://prometheus.io/docs/practices/naming/.
All I am doing is changing the - to a _. 
I tested and built this and my node was syncing and metrics names are still easily readable:
```# TYPE blobpool_shelf_3_slotused gauge
blobpool_shelf_3_slotused 0
blobpool_shelf_4_datagaps 0
```
Apologies if I missed something here. First time open a PR in this repo.
=> fixing blobpool metrics name from - to _ for prometheus

ethdb/leveldb/leveldb.go
fix https://github.com/ethereum/go-ethereum/issues/27902
=> ethdb/leveldb: support more than 7 levels in metrics

rpc/websocket.go
This could be a fix for the issue reported in #27726. With enough load, it might happen that the `SetPongHandler` callback gets invoked before the call to `SetReadDeadline` is made in `pingLoop`. When this occurs, the socket will end up with a 30s read deadline even though it got the pong, which will lead to a timeout.
The fix here is processing the pong on `pingLoop`, synchronizing with the code that sends the ping.
=> rpc: attempt to fix ping/pong logic race

build/ci.go, build/deb/ethereum/deb.rules, go.mod, go.sum, internal/build/env.go, internal/build/gotool.go
This upgrades to the latest release of ckzg, and also attempts to fix some blst-related
build errors that occur on launchpad.net.
=> go.mod, build: upgrade c-kzg-4844

cmd/utils/flags.go
We need to be backward compatible with the old `--txlookuplimit` parameter
=> cmd/utils: restore support for txlookuplimit flag

trie/stacktrie_test.go
Did you know, the "short nodes" feature in MPT is completely useless for Ethereum State representation except for withdrawals receipts added recently. The RLP-encoded withdrawals are exactly 31-byte long. :+1:
=> trie: add tests for "short" nodes in StackTrie

eth/tracers/js/goja.go
There is a bug in js tracer, `ctx.GasPrice.toString(16)` returns a number string in base 10.
=> eth/tracers/js: use t.toBig on ctx.GasPrice for js tracing

build/ci.go
Our uploads are failing, so no point keeping it around: 
```
Rejected:
kinetic is obsolete and will not accept new uploads.
ethereum-unstable (1.13.0+build28808+kinetic) kinetic; urgency=low
* git build of 509cd428e9e8405f922fcbf8f73eed6792224d90
```
=> build: remove ubuntu kinetic (deprecated)

node/defaults.go, node/node.go
Fixes https://github.com/ethereum/go-ethereum/issues/27923
This raises the JSON-RPC batch request limits significantly for the engine API endpoint.
The limits are now also hard-coded, so users won't get them wrong. I have chosen these limits:
- maximum batch items: 2000
- maximum batch response size: 250MB
While it would also be possible to disable batch limits completely for the engine API, I think having
the limits is a good safety net against misbehaving CLs.
=> node: increase batch limits for auth rpc API

core/types/transaction_marshalling.go
Looks like `ok` should actually be interpreted as `overflow`.
=> core/types: fix unmarshalling of BlobTx values

cmd/devp2p/internal/ethtest/chain.go, core/forkid/forkid.go, core/forkid/forkid_test.go, eth/handler.go, eth/protocols/eth/discovery.go, eth/protocols/eth/handshake_test.go, les/client_handler.go, les/peer_test.go, les/server_handler.go, les/test_helper.go
There is an issue with how we compute forkid values for networks where a time-based fork is activated in genesis. Currently, we have no in `forkid.NewID` to determine the genesis' timestamp and per EIP-6122:
> If a chain is configured to start with a non-Frontier ruleset already in its genesis, that is NOT considered a fork.
However, since the `NewID` function cannot know the timestamp of the genesis block, it is unable to differentiate the case where a time-base fork activation is equal to the time of genesis and correctly skip the block.
Here is an example `genesis.json`:
<details><summary>genesis.json</summary>
```json
{
"alloc": {
"0x0000000000000000000000000000000000000000": {
"balance": "1"
},
"0x0000000000000000000000000000000000000001": {
"balance": "1"
}, …
```
=> all: correctly compute forkid when timestamp fork is activated in genesis

docs/developers/evm-tracing/custom-tracer.md, docs/interacting-with-geth/rpc/ns-admin.md, docs/interacting-with-geth/rpc/ns-clique.md, docs/interacting-with-geth/rpc/ns-debug.md, docs/interacting-with-geth/rpc/ns-eth.md, docs/interacting-with-geth/rpc/ns-les.md, docs/interacting-with-geth/rpc/ns-personal.md, docs/interacting-with-geth/rpc/ns-txpool.md, docs/interacting-with-geth/rpc/pubsub.md
Currently, there are many `Example,Parameters` tags on the right side, so it's hard to switch between other useful rpc methods
=> docs/interacting-with-geth/rpc: don't set header for Example,Parameters

core/txpool/legacypool/list.go
The pr https://github.com/ethereum/go-ethereum/pull/27324 fixed an issue somewhat incidentally. This PR fixes the root issue a bit more robustly, by using mutexes when the cache is read or modified. 
Replaces #27324
=> core/txpool/legacypool: protect cache with mutex

eth/downloader/skeleton.go
fix https://github.com/ethereum/go-ethereum/issues/27931
=> eth/downloader: fix rare crash when parent header missing in db

internal/ethapi/api.go
Optimizations:
- Currently if a transaction is reverting, EstimateGas will exhibit worst-case behavior and binary search up to the max gas limit (~40 state-clone + tx executions).  This PR allows EstimateGas to return after only a single unconstrained execution in this scenario.
- Uses the gas used from the unconstrained execution to bias the remaining binary search towards the likely solution in a simple way that doesn't impact the worst case. For a typical contract-invoking transaction, this reduces the median number of state-clone+executions from 25 to 18 (28% reduction).
Cleanup:
- added & improved function + code comments
- correct the EstimateGas documentation to clarify the gas limit determination is at latest block, not pending, if the blockNr is unspecified.
The performance …
=> internal/ethapi: optimize & clean up EstimateGas

trie/encoding.go, trie/encoding_test.go, trie/stacktrie.go
Reduces allocations in recHash.
I noticed during profiling, that a lot of allocations (3.8% of total) is spent on hexToCompact. This uses the existing HexToCompactInPlace to reduce allocations. 
Since we reset the key anyway after this operation, it should be fine imo
```
ROUTINE ======================== github.com/ethereum/go-ethereum/trie.keybytesToHex in github.com/ethereum/go-ethereum/trie/encoding.go
150455888  150455888 (flat, cum)  3.22% of Total
.          .     97:func keybytesToHex(str []byte) []byte {
.          .     98:    l := len(str)*2 + 1
150455888  150455888     99:    var nibbles = make([]byte, l)
.          .    100:    for i, b := range str {
.          .    101:        nibbles[i*2] = b / 16
.          .    102:        nibbles[i*2+1] = b % 16
.          .    103:    } …
```
=> trie: reduce allocs in recHash

eth/api_admin.go
This PR ignores the genesis block when importing a previously exported chain. 
The genesis block can not be imported anyway which will lead to bad blocks due to `unknown ancestor`.
=> eth: ignore genesis block on importChain

eth/catalyst/simulated_beacon.go
In dev mode, the finalized block should be the block that was produced at the start of the current epoch (block number 0, 32, 64, ...)
=> eth/catalyst: set finalized block hash properly in dev mode

core/blockchain.go
Currently, we trigger the logic to (un)index transactions when the node receives a new block. However, in some cases the node may not receive new blocks (eg, when the Geth node is configured with `--nodiscovery`, or when it acts as an RPC node for historical only data). 
In these situations, the Geth node user may not have previously configured `txlookuplimit` (i.e. the default of around one year), but later he realizes they need to index all historical blocks. However, adding `txlookuplimit=0` and restarting geth has no effect.
So in this case, I think if we start a timer, there would at least be one opportunity to run the indexing process.
=> core: ensure txindex will be triggered at least once

cmd/evm/staterunner.go
The PR #26274 broke the `evm statetest` command a bit, in that it stopped spitting out the stateroot following a non-successful statetest-execution. Specifically https://github.com/ethereum/go-ethereum/commit/503f1f7ada6d44714c93647e89a7677b7b706305#diff-b65701f0424f8a0db413f64508b663f424cff1fd3b35095b09493edb0b39ca29
This PR changes it back, so the stateroot is unconditionally output on stderr, and makes it so fuzzing works again. 
I am not sure why the change was needed in the first place, cc @rjl493456442 PTAL and see if I am doing something wrong.
=> cmd/evm: add back stateroot to jsonl-output

go.mod, go.sum, rpc/ipc_windows.go
This PR replaces the old npipe implementation with official microsoft-code: https://github.com/microsoft/go-winio/
=> rpc: use winio for named pipes

core/blockchain.go, core/blockchain_insert.go, core/blockchain_test.go, core/state/snapshot/snapshot.go, eth/state_accessor.go, eth/tracers/api.go, trie/database.go, trie/triedb/hashdb/database.go, trie/triedb/pathdb/database.go
Tracking dirty RAM usage by the pathdb got a bit convoluted because the node buffer memory usage (configurable-ish, flushes when full) got merged with the diff layer memory usage (non-configurable, must-have-ram). This PR split the two apart, and also introduced the same split and exposure for the snapshot diff layers, since it would be nice to see the RAM usages of those too just for kicks.
Edit:
The PR fixes weirdnesses like this:
```
INFO [08-22|11:01:44.247] Imported new chain segment [...] dirty=473.58MiB
INFO [08-22|11:01:52.752] Imported new chain segment [...] dirty=235.08MiB
```
Where the dirty drops from some random number (470) to some other random number (235), where the configured limit is 256 (neither of the two). The PRd version will be:
```
INFO [08-22|11:02:45.285] …
```
=> core, eth, trie: expose more detailed dirty ram tracking for diff layers

eth/catalyst/api.go, eth/catalyst/simulated_beacon.go
This PR fixes an issue in engine API. GetPayload supports two mode: full or non-full.
- In full mode, GetPayload will block until a full block is generated
("full block" doesn't mean it must include transaction, but it will try to pack as many transactions
as possible into block).
- In non-full mode, GetPayload will return immediately with any available payload(can be empty)
The non-full mode is chosen as default mode in engine API. This is necessary in case the block is
generated very slow(e.g. some attack transactions fulfill the pool) and empty block will always
be returned in order to not miss the slot.
This default option is modified in https://github.com/ethereum/go-ethereum/pull/27736
=> eth/catalyst: disable full payload when not in dev mode

.travis.yml, Makefile
GO111MODULE defaults to `on` since Go 1.16
=> travis: get rid of old useless GO111MODULE directives

rlp/decode.go
This removes a small allocation per DecodeBytes call. Performance impact of this change is hard to assess, but it will certainly not be slower than before.
=> rlp: remove allocation of bytes.Reader in DecodeBytes

core/blockchain_repair_test.go, core/blockchain_sethead_test.go, core/blockchain_snapshot_test.go, core/rawdb/database.go, core/rawdb/databases_64bit.go, ethdb/pebble/pebble.go
Proof of concept alternative to https://github.com/ethereum/go-ethereum/pull/27768 . 
I don't have a mac, so can't check if it works or not.
=> core/rawdb, ethdb/pebble: avoid fsync db in tests

core/rawdb/schema.go
During profiling I noticed that a lot of allocations are spent trying to compute the keys for accessing the database: 
```
ROUTINE ======================== github.com/ethereum/go-ethereum/core/rawdb.storageSnapshotKey in github.com/ethereum/go-ethereum/core/rawdb/schema.go
288552922  288552922 (flat, cum)  2.96% of Total
.          .    197:func storageSnapshotKey(accountHash, storageHash common.Hash) []byte {
288552922  288552922    198:	return append(append(SnapshotStoragePrefix, accountHash.Bytes()...), storageHash.Bytes()...)
.          .    199:}
.          .    200:
.          .    201:// storageSnapshotsKey = SnapshotStoragePrefix + account hash + storage hash
.          .    202:func storageSnapshotsKey(accountHash common.Hash) []byte {
.          .    203:	return …
```
=> core/rawdb: allocate database keys with explicit size to avoid slice growth

core/state/statedb.go, core/state/statedb_test.go
Since we're doing a minor version update, I thought it would be an opportune time to slim down the statedb API. 
This PR removes the `statedb.ForEachStorage` method. I doubt there's any widespread use of that api-method (but I may be wrong)
=> core/state: remove public method ForEachStorage

beacon/engine/types.go, consensus/misc/eip4844/eip4844.go, core/txpool/blobpool/blobpool.go, core/txpool/validation.go, eth/catalyst/api_test.go, miner/payload_building.go, miner/worker.go, miner/worker_test.go, params/protocol_params.go
I'm ripping out the changes that allow the miner to build 4844 blocks from #27511.
=> core,miner: add ability to build block with blobs

miner/payload_building.go, miner/worker.go, miner/worker_test.go
=> miner: refactor getSealingBlock method

core/rawdb/accessors_chain.go, core/rawdb/accessors_sync.go, core/state/iterator.go, core/state/sync.go, core/types/transaction_test.go, eth/tracers/api.go, light/odr_util.go, p2p/discover/v4wire/v4wire.go, signer/core/api_test.go
Follow-up to #27987 where @holiman noticed we have quite a few uses of `rlp.Decode(bytes.NewReader(...))`.
=> all: use rlp.DecodeBytes instead of rlp.Decode where possible

eth/catalyst/api.go, eth/catalyst/simulated_beacon.go, eth/catalyst/tester.go
When running geth with `--dev` mode, there are a lot of disturbing warning messages as below:
```
> WARN [08-23|11:54:51.740] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
> WARN [08-23|11:59:51.786] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
```
This PR disabled the heartbeat to remove those messages.
=> eth/catalyst: disable heartbeat for simulated beacon node

core/vm/runtime/env.go, core/vm/runtime/runtime.go
Make the Random field configurable through the Runtime interface. The RANDOM opcode will otherwise crash due to a nil pointer if it is run via Runtime.
=> core/vm/runtime: Add Random field to config

core/state/snapshot/snapshot.go
This PR updates `diffToDisk(...)` within snapshot flattening to write the entire diff to disk in a single batch.
Writing the diff to disk across multiple batches leads to the possibility that the snapshot will be corrupted during an ungraceful shutdown and can cause degraded performance during snapshot re-generation on startup.
=> core/state/snapshot: replace diffToDisk ideal batch size with 64MB

eth/catalyst/simulated_beacon.go
fix https://github.com/ethereum/go-ethereum/issues/27990
=> eth/catalyst: reset to current header if chain is rewound (in dev mode)

core/state/statedb.go, core/state/statedb_fuzz_test.go, core/state/statedb_test.go
```
Deletion of 328239 slots 22.47 MiB statesize in time 812.148619ms
800ms vs 3.6 s
```
=> core/state: implement fast storage deletion

eth/api_backend.go
We're dealing with a bit of a problem over in [rpctestgen](https://github.com/lightclient/rpctestgen/pull/21#discussion_r1270725621) where we would like to generate some rpc test interactions using the `safe` and `finalized` block tags, but it is not currently possible without making some Engine API requests.
This is a relatively specialized use case, but the error returned is sort of incorrect here when a genesis has `terminalTotalDifficultyPassed` set in genesis: `'xxxxx' tag not supported on pre-merge network`. Now it will return `nil` if the network is pre-merge or the network is post-merge but we haven't determined which block is `safe` / `final` yet. This behavior seems more correct.
=> eth: remove check for tdd reached on pos api block tags

build/checksums.txt, build/ci.go, tests/block_test.go, tests/block_test_util.go, tests/gen_btheader.go, tests/init.go, tests/init_test.go
This PR adds the execution spec tests to our test suite.
Doesn't work under windows yet
=> build: tests: add execution spec tests

tests/gen_sttransaction.go, tests/state_test_util.go
A while back, statetests started coming with `sender` baked in, which at least `evmone` makes use of. Let's make use of that too, and save some cycles.
=> tests: use 'sender' on statetests

core/txpool/blobpool/blobpool.go
Noticed that this tx object should be referenced when used as decode target.
=> core/txpool/blobpool: fix missing reference

beacon/engine/gen_epe.go, beacon/engine/types.go
The `shouldOverrideBuilder` field was added to response of `NewPayload` with the intention that EL clients could give the CL client some indication of the health of the execution network in terms of censorship.
This PR is adds support for the field, but sets the value statically to zero so the CL will never override the builder. Marius has a more complete solution in #26829.
I've been using this proposed PR for testing the devents. We should make a decision on which approach to move forward with.
=> beacon/engine: add `shouldOverrideBuilder` to payload envelope

cmd/devp2p/nodesetcmd.go, core/forkid/forkid.go, core/forkid/forkid_test.go
I made a mistake in #27895, I didn't realize `newFilter` also generated the fork id hash. This caused geth to disconnect from peers during the handshake. I've resolved it by modifying `gatherForks` to simply skip forks that are non-zero and before the genesis timestamp.
=> core/forkid: skip genesis forks by time

consensus/misc/eip4844/eip4844.go, consensus/misc/eip4844/eip4844_test.go, core/txpool/blobpool/slotter_test.go, params/protocol_params.go
Back in ACD 163 we agreed to bump the target and max blob values from 2/4 to 3/6 for future devnets until we could decide on final mainnet number. I'm updating it here so that we can get master passing all the hive tests. The final decision is still to be made.
=> params: update 4844 parameters

common/types_test.go, log/format.go, log/handler_glog.go, log/logger.go, log/logger_test.go
We can avoid the somewhat expensive `stack.Caller` invocation by checking the atomic global. 
```
name            old time/op    new time/op    delta
TraceLogging-8    2.84µs ± 8%    0.97µs ± 4%  -65.87%  (p=0.008 n=5+5)
name            old alloc/op   new alloc/op   delta
TraceLogging-8      511B ± 0%      263B ± 0%  -48.53%  (p=0.008 n=5+5)
name            old allocs/op  new allocs/op  delta
TraceLogging-8      4.00 ± 0%      2.00 ± 0%  -50.00%  (p=0.008 n=5+5)
```
Closes https://github.com/ethereum/go-ethereum/issues/28064
=> log: avoid stack lookups when not needed/used

core/state/statedb.go, core/state/statedb_fuzz_test.go, trie/database.go, trie/database_test.go
This PR cleans up the trie database by removing some unused functions and non-interesting field.
=> core, trie: cleanup trie database

go.mod, go.sum
There was some bugfix that landed 1 day after we updated Pebble. Just pull that + some cosmetics afterwards: https://github.com/cockroachdb/pebble/commits/crl-release-23.1
=> go.mod: pull in a fix from pebble crl-release-23.1

ethclient/ethclient.go, ethclient/gethclient/gethclient.go
Closes https://github.com/ethereum/go-ethereum/issues/28077 
This makes ethclient / gethclient use `input` instead of `data` for passing input with a transaction. `input` is the preferred way. 
See https://github.com/ethereum/go-ethereum/issues/15628, and https://github.com/ethereum/go-ethereum/blob/master/signer/core/apitypes/types.go#L93
=> ethclient: use 'input', not 'data' as field for transaction input

core/state_processor.go
This fixes the derived value `BlobGasPrice` on the receipt of EIP-4844 transactions.
=> core: fix calculation of blob gasprice in tx receipt

cmd/geth/config.go
The eth_protocol seems wrong (it contains all protocols, the eth part originates from the "eth" service the protocols are from, but that's moot in the context of Geth). This PR drops the eth_ prefix.
=> cmd/geth: rename the protocols field in the metrics gague

eth/api_debug.go
The trie flush interval does not make sense in path scheme anyway. We could return a value for getAccessibleState later on when historical state is merged in, for now return error.
=> eth: abort on api operations not available in pbss-mode

cmd/geth/main.go, go.mod, go.sum, internal/flags/flags.go, internal/flags/helpers.go
This PR does three things:
- Updates the CLI dependency (because why not)
- Extends each CLI flag with an auto-generated env var that can be used for the same purpose. This should help initialize Geth in cloud and other container infrastructure which are more tuned to being inited via env vars vs flags or config files.
- Updates the --help screen to use colored flag and category names.
=> cmd/geth, internal/flags, go.mod: colorize cli help, support env vars

internal/flags/flags.go
Seems custom flags need to be explicitly told to load from env vars.
The added code is just a copy-pasta of how the CLI library does it internally. We might be able to "separate" out the iteration into a method and then just have the rest internally, but figured it's more of a complexity than worth for 3 types.
=> internal/flags: fix loading env vars for custom flags

metrics/metrics.go
This is another followup PR to fix corner cases in the env var support. The metrics subsystem completely ignores the CLI library and rather directly checks if `--metrics` or `--metrics.expensive` is specified in `os.Args`. It does this to ensure that my the time anything accesses `metrics.Enabled`, the field has been correctly initialized, even if it's accessed on package initializer methods.
This PR extends this part of the logic to also check for `GETH_METRICS` and `GETH_METRICS_EXPENSIVE` env vars in the same vein. A tad ugly for sure, but beats rethinking all the initialization logic.
=> metrics: add support for enabling metrics from env vars

core/state/statedb.go
Hi. It seems the intention was to check the error returned from `iter.Error()` and return it if non-nil.
Thanks.
=> core/state: check err for iter.Error in fastDeleteStorage

eth/downloader/downloader.go
Fix an extremely rare corner-case where snap sync might actually restart snap syncing after committing the pivot block, if a pivot move is detected in between processing the full blocks. This should realistically not happen, but still, better fix for that one in a million case.
=> eth/downloader: prevent pivot moves after state commit

eth/catalyst/api.go
=> eth/catalyst: fix engine API

internal/ethapi/api.go
The latest release doesn't calculate the effective gas price correctly. The behavior implemented is `price = min(gasTipCap + baseFee, gasTipCap)`, but it is supposed to be `price = min(gasTipCap + baseFee, gasFeeCap)`, according to the comment above `effectiveGasPrice()`.
As an example, this can be observed by calling `eth_getBlockByNumber`, and observing that the `gasPrice` and `maxPriorityFeePerGas` are equivalent for all reported transactions.
```
curl --location '<GETH_NODE_URL>' \
--header 'Content-Type: application/json' \
--data '{
"method": "eth_getBlockByNumber",
"params": [
"0x114D27E",
true
],
"id": "1"
}' 
snip
"blockHash": "0xa14e2a59a71b44ea305df73069e4c4229cc0ea357009c2970c170150825520f9",
"blockNumber": "0x114d27e",
"from": …
```
=> Correctly calculate effective gas price

core/blockchain.go, eth/downloader/downloader.go
Fixes #28120 
This pull request fixes two main flaws introduced by path-based scheme. 
##
a) In the blockchain repair stage, initiate the repair process to restore the missing genesis state if the head block is still the genesis block.
This is indeed a unique and exceptional scenario that can only occur in the path-based scheme. The root cause of this issue is the state syncer overwriting the persistent genesis state, leading to a situation where no complete and usable state is available. 
This pull requests fixes this issue by restoring the genesis state. It won't affect the correctness of following state sync, due to the fact that the written genesis state is **complete** and state healer will address and fix any inconsistencies between the genesis state and sync target.
It's an …
=> core, eth/downloader: fix genesis state missing due to state sync

cmd/devp2p/crawl.go, cmd/devp2p/discv4cmd.go, cmd/devp2p/discv5cmd.go
In This PR, we can use `--bootnodes` to start a `devp2p crawl`, the flag will take effect if the input/output.json file is missing or empty. Also in this PR, we cannot begin crawling if no input nodes are provided.
close https://github.com/ethereum/go-ethereum/issues/27942
=> cmd/devp2p: use bootnodes as crawl input

trie/database.go
Rebasing the verkle code on top of PBSS broke the overlay transition code in the following way:
* The overlay code used `rawdb.ReadPreimage` while enumerating the snapshot in order to re-hash the key for insertion in the verkle tree
* The preimages are no longer directly flushed to disk at the end of a block, but bulk-saved at specific times (e.g. when the blockchain stops or the cache gets above a certain threshold).
This means that the overlay conversion method will miss some preimages if they are in the cache and not yet on disk. In order to fix this issue, the conversion code needs to check both the disk and cache stores for preimages. This is done by adding a getter to `trie.Database`, so that it can call `(*preimageStore).preimage`.
=> trie: add getter for preimage store in trie.Database

docs/fundamentals/config-files.md
I'm new to Ethereum. When I read the documentation, I noticed that `Eth.Miner.Noverify` was used for PoW. So it doesn't work now and can be removed.
=> website- remove Noverify

accounts/keystore/watch.go
close https://github.com/ethereum/go-ethereum/issues/28132
As the keydir will be automatically created after an account is created, no error message if the watcher is failed.
=> cmd/clef: suppress fsnotify error if keydir not exists

docs/fundamentals/command-line-options.md, docs/fundamentals/private-network.md
This PR will update the docs with the latest cli flags used by the client. This includes docs on the ability to configure the node via ENV variables. Additionally, a note has been made to the custom network section on how to `init` the custom network when `path` based storage is meant to be used.
=> Update CLI args as well as custom network documentation

core/rawdb/freezer_table.go
If a file was opened in read-only mode, the `file.Truncate` will return the error: `truncate xxx: invalid argument`. Let's skip it.
=> core/rawdb: no need to run truncateFile for readonly mode

core/rawdb/accessors_trie.go, trie/sync.go, trie/sync_test.go
This pull requests fix the state healer in path-mode context, by removing the internal disk nodes within the path range occupied by a shortNode, ensuring the guarantee of state healing that each existing sub-trie in disk should be complete. 
Although the condition to trigger the issue is super hard, thus we never see the state corruption after snap sync in real.
=> trie: remove internal nodes between shortNode and child in path mode

cmd/geth/snapshot.go
When running state traversal, we only log progress for accounts. That's unfortunate when iterating a huge contract as it can take a very long time without output. This PR adds the logging for storage iteration too.
I.e. This is what I want to fix
```
INFO [09-22|07:37:48.021] Traversing state                         nodes=6,395,005 accounts=451,926 slots=2,271,664 codes=73378 elapsed=1m58.960s
INFO [09-22|07:42:05.237] Traversing state                         nodes=21,319,313 accounts=482,117 slots=8,634,942 codes=78166 elapsed=6m16.175s
```
Note the 5 minute gap in the logs.
=> cmd/geth: print progress logs when iterating large contracts too

core/genesis.go, params/config.go
Updates the Holesky genesis specs to the relaunched testnet.
=> core, params: update Holesky testnet to relaunched spec

core/forkid/forkid_test.go
Adds a forkid test, matching besu & nethermind
```
ForkId(0xc61a6098, 1696000704)
and then after Shanghai...
ForkId(0xfd4f016b, 0)
```
=> core/forkid: add forkid test for holesky

cmd/utils/flags.go
1.  BootstrapNodes is set in config.toml, no matter empty or not, like
```
[Node.P2P]
MaxPeers = 30
NoDiscovery = false
BootstrapNodes = []
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false
```
2. start `geth` with flag BootnodesFlag
bootnode in BootnodesFlag is ignored
reset the bootnode from BootnodesFlag
=> cmd/utils: fix parsing BootstrapNodes from BootnodesFlag

ethclient/ethclient.go
There is an issue. After marshaling rpc.BlockNumberOrHash we have e.g. {"jsonrpc":"2.0","id":3,"method":"eth_getBlockReceipts","params":[{"blockNumber":"0x2"}]} instead of {"jsonrpc":"2.0","id":3,"method":"eth_getBlockReceipts","params":["0x2"]} and invalid response.
=> ethclient: fix BlockReceipts parameter encoding

internal/ethapi/api.go, internal/ethapi/api_test.go
So apparently in the spec the base block parameter of eth_call is optional. I agree that `"latest"` is a sane default for this that most people would use.
=> internal/ethapi: eth_call block parameter is optional

accounts/abi/bind/backends/simulated.go, cmd/devp2p/internal/ethtest/suite_test.go, core/blockchain.go, core/rawdb/accessors_sync.go, core/rawdb/database.go, core/rawdb/schema.go, core/txpool/blobpool/blobpool.go, core/txpool/legacypool/legacypool.go, core/txpool/txpool.go, eth/api_backend.go, eth/backend.go, eth/downloader/downloader.go, eth/handler.go, eth/handler_eth.go, eth/handler_eth_test.go, eth/sync.go, miner/miner_test.go, trie/database.go, trie/triedb/pathdb/database.go, trie/triedb/pathdb/database_test.go, trie/triedb/pathdb/errors.go, trie/triedb/pathdb/journal.go
This pull request addresses scenarios where the associated head state is missing.
In the original design, the chain head would never be stateless because the genesis state was always considered present, and we could always rewind the chain back to the genesis block. However, in path mode, the genesis state may have already been overwritten by the state syncer, making recovery impossible.
As a result, it is important to ensure that even when the chain is in a stateless condition, everything continues to function smoothly until the state synchronization process is fully completed.
The lazy initialization is introduces to txpool if the chain is stateless, it's looks a bit ugly, but no idea how to make it elegant.
A few scenarios need to be tested:
=> core, accounts, eth, trie: handle genesis state missing

ethdb/leveldb/leveldb.go, ethdb/pebble/pebble.go, internal/ethapi/api.go
LevelDB has a method exposed via the API to expose all internal counters. This is rarely useful to debug things.
With the current Pebble issues, turns out Pebble also has a similar mechanism, but unfortunately we never exposed it. This PR exposes it.
=> ethdb, internal/ethapi: support exposing Pebble stats too, beside LevelDB

core/chain_makers.go, internal/ethapi/api_test.go
Same way that the gasUsed in header is updated when a tx is added we should update blob gas used instead of requiring caller to set it manually.
=> core: infer blobGasUsed in chain maker

core/state/trie_prefetcher.go
This PR adds a comment to the trie prefetcher `fetches` field to make it clear when it will be populated (I found this non-obvious when reading through the code) and updates `trieID` to allocate a slice up front and copy in rather than using `append`.
Just small nits I found while reviewing the code, hope it's helpful 🫡
=> core/state: small trie prefetcher nits

eth/catalyst/api.go
Small change which now returns the error message from `ExecutableDataToBlock(..)`.
=> eth/catalyst: add validation error in new paylaod hash mismatch

cmd/geth/config.go, cmd/utils/flags.go, eth/catalyst/tester.go, eth/downloader/beacondevsync.go, eth/downloader/downloader.go, eth/downloader/peer.go
This PR switched the `--synctarget` flag from requiring a block RLP in a file (which is annoyingly hard to obtain) to just using a hash and retrieving everything else from the network.
`geth --synctarget 0x91c90676cab257a59cd956d7cb0bceb9b1a71d79755c23c7277a0697ccfaf8c4`
=> cmd, eth: switch the dev synctarget to hash from block

cmd/evm/internal/t8ntool/execution.go, cmd/evm/runner.go, core/evm.go, core/state_processor.go, core/state_transition.go, core/vm/eips.go, core/vm/evm.go, core/vm/jump_table.go, core/vm/opcodes.go, core/vm/runtime/env.go, core/vm/runtime/runtime.go, internal/ethapi/api.go
Implements the https://eips.ethereum.org/EIPS/eip-7516 opcode for cancun
=> core: implement blobfee opcode

core/txpool/blobpool/blobpool.go, core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, core/txpool/txpool.go, eth/api_backend.go, eth/catalyst/simulated_beacon.go, eth/handler.go, eth/handler_eth.go, eth/handler_eth_test.go, eth/handler_test.go, eth/protocols/eth/handler.go, eth/protocols/eth/handlers.go, miner/ordering_test.go, miner/worker.go
This PR starts feeding blobpool transaction events into all other parts of Geth via the tx subscription mechanism. A few caveats:
- Blob transactions fed into the event system will always be **without** sidecars. Feeding the blobs through everything would be very expensive. If something needs the blobs themselves, those should request it explicitly.
- If Cancun is enabled, eth/67 is disabled since there's no way to tag the tx announcements with the blobs. Whilst this wouldn't necessarily be needed just now, it's IMO good practice.
- The subscriptions were extended to allow subscribing to new transaction that either include or not reorged resurrections. This is good because things that are pulled back up from disk should already be known to everybody, so there's no point in reannouncing …
=> core, eth, miner: start propagating and consuming blob txs

eth/handler.go, eth/peerset.go
We have a warning log if somebody connects on snap but doe snot have a valid eth to go along, since the two protocols need each other. This PR extends that log so we can see what exactly is the mismatch to see who the offenders are. It does not make the log less annoying, but that will be solved in a followup PR that does some ENR checks. Then we can see how frequent it remains and what to do about it.
Turns out doing the ENR check also requires exposing devp2p caps into the ENR records. That is going to have to be done on all clients, so it's going to take a while, so for now this PR lowers the warning down to debug. We can revisit when ENR caps are more prevalent.
=> eth: when snap is complaining for missing eth, be verbose about the details

cmd/evm/internal/t8ntool/block.go
Pretty straightforward bugfix, although tests pass before and after.
=> t8ntool: tiny bugfix for difficulty field

eth/fetcher/tx_fetcher.go, eth/fetcher/tx_fetcher_test.go, eth/handler.go, eth/handler_eth.go, tests/fuzzers/txfetcher/txfetcher_fuzzer.go
In `eth/68` we introduced the capability to announce transaction types and sizes along with their hashes. The goal was to allow fetching large transactions and blob transactions via a throttled mechanism to avoid saturating a connection. Whilst we did start announcing the extra data, we never started validating it. This PR adds that component, cross checking delivered transaction bodies with announced metadatas and dropping offending peers. This is a **necessary** DoS protection, otherwise peers could announce fake small blob txs and cause us to request many concurrently, overloading our bandwidth.
=> eth: enforce announcement metadatas and drop peers violating the protocol

.gitignore
Currently when running `make test` the `build/ci.go` will download the execution spec test, thanks to #26985. I don't think there is any reason it should be considered an untracked folder to git since we won't want to actually push that artifact up. For this reason, I've added it to our `.gitignore`.
=> git: ignore tests/spec-tests folder

accounts/abi/bind/backends/simulated.go
The simulated backend had two quirks that PR addresses:
- When doing a Call, we could specify the header to use as the call context. However, when the gas price was auto calculated for 1559, the target header was the chain HEAD, not the header we used as context. I don't expect people to specify gas prices for calls, but if they do, this is more accurate that the old code.
- If no gas limit is given for a Call (e.g. the abigen generated stuff does not -and cannot - specify a gas limit), the simulated backend defaults to a 50M gas cap. The PR suggests making this dynamic at 10X the block gas limit for the header being ran at. This is consistent with what [Infura for example runs their APIs with](https://docs.infura.io/networks/ethereum/json-rpc-methods/eth_call) and would allow going a bit …
=> accounts/abi/bind/backend: use requested header for gas prices and gas limits

ethdb/pebble/pebble.go
This pull requests exposes the file number of different levels in pebble to metrics.
Note, it's already existent in leveldb, but not in pebble.
=> ethdb/pebble: add level file metrics

eth/fetcher/tx_fetcher.go, eth/fetcher/tx_fetcher_test.go
The transaction fetcher until now was rate limited by number of transactions requested. With the addition of announced sizes (and soon arriving blob transactions), we can now also add a throttling on the bandwidth usage. This is needed to avoid requesting too many blob transactions and starving the peer connection due to the response hogging the channel.
=> eth/fetcher: throttle tx fetches to 128KB responses

cmd/clef/main.go, cmd/devp2p/internal/ethtest/snap.go, common/types.go, core/state_processor_test.go, eth/protocols/snap/handler.go, eth/protocols/snap/range.go, eth/protocols/snap/range_test.go, eth/protocols/snap/sync.go, eth/protocols/snap/sync_test.go, trie/proof_test.go
This pull request addresses an issue in snap sync, specifically when the entire sync process can be halted due to an encountered empty storage range.
Currently, on the snap sync client side, the response to an empty storage range is discarded. However, this response is valid when there are no available storage slots within that range.
For instance, consider a large contract where the entire key space is divided into 16 chunks, and there are no available slots in the last chunk [0xf] -> [end]. When the node receives a request for this particular range, the response includes:
- The proof with origin [0xf]
- A nil storage slot set
If we simply discard this response, the finalization of the last range will be skipped, halting the entire sync process indefinitely. The test case …
=> eth/protocols/snap: fix snap sync failure on empty storage range

go.mod, go.sum
No particular gain, but the dep was over 3 years old with tiny sub-dep-updates going in, so update ourselves to avoid referencing older sub-deps than needed.
=> go.mod: update fastcache to latest

cmd/devp2p/internal/ethtest/snap.go, core/state/snapshot/generate.go, eth/protocols/snap/sync.go, tests/fuzzers/rangeproof/rangeproof-fuzzer.go, trie/proof.go, trie/proof_test.go
During snap-sync, we request ranges of values: either a range of accounts or a range of storage values. For any large trie, e.g. the main account trie or a large storage trie, we cannot fetch everything at once. 
Short version; we split it up and request in multiple stages. To do so, we use an `origin` field, to say "Give me all storage key/values where key > `0x20000000000000000`". When the server fulfils this, the server provides the first key after `origin`, let's say `0x2e030000000000000` -- never providing the _exact_ origin. However, the client-side needs to be able to verify that the `0x2e03..` indeed is the first one after `0x2000..`, and therefore the attached proof concerns the `origin`, not the first key. 
So, short-short version: the left-hand side of the proof relates to the …
=> trie: make rhs-proof align with last key in range proofs

build/checksums.txt, build/ci.go, cmd/evm/blockrunner.go, tests/block_test.go
This updates the execution-spec-tests to latest version. Putting it up to see if it builds
=> tests: update execution-spec-tests to 1.0.5

eth/fetcher/tx_fetcher.go
Erigon is sending bad tx announces. We should drop them, but that would hurt the network. We were loud, but that hurts users. Let's lower the verbosity, get them to fix it and then raise it back up again.
=> eth/fetcher: only make noise big mismatches

ethclient/gethclient/gethclient_test.go, internal/ethapi/api.go
Fixes https://github.com/ethereum/go-ethereum/issues/28355 (I think), unconditionally looks up the codehash. Also refactors a bit.
=> internal/ethapi: fix codehash lookup in eth_getProof

eth/fetcher/tx_fetcher.go, eth/fetcher/tx_fetcher_test.go
This PR adds a test and fixes a corresponding bug in the tx fetcher
=> eth/fetcher: fix fetcher timeout

core/state/snapshot/conversion.go, core/state/statedb.go, eth/protocols/snap/sync.go, tests/fuzzers/stacktrie/trie_fuzzer.go, trie/stacktrie.go, trie/trie_test.go
This pull request enhances the stacktrie constructor by introducing option struct, besides it also simplify the `Hash` and `Commit` operation, getting rid of the special handling round root node.
=> core, trie, eth: refactor stacktrie constructor

core/chain_makers.go, core/chain_makers_test.go
Adds the ability to set the `ParentBeaconRoot` of a generated block.
=> core/chain_makers: add SetParentBeaconRoot(..) to chain makers

tests/fuzzers/les/les-fuzzer.go
This PR fixes a crash in the LES fuzzer. We included transactions that payed less gas than the block base fee
```
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO [10-17|09:42:05.569] Persisted trie from memory database      nodes=1 size=149.00B time="10.63µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=0 livesize=0.00B
panic: max fee per gas less than block base fee: address 0x71562b71999873DB5b286dF957af199Ec94617F7, maxFeePerGas: 0 baseFee: 875000000
goroutine 1 [running]:
github.com/ethereum/go-ethereum/core.(*BlockGen).addTx(0x10c0006ce240, 0xf71746c9?, {{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}}, 0x10c000700900)
github.com/ethereum/go-ethereum/core/chain_makers.go:105 +0x4ba
github.com/ethereum/go-ethereum/core.(*BlockGen).AddTx(...) …
```
=> tests/fuzzers/les: fix crasher

rpc/websocket_test.go
=> rpc: increase timeout in TestClientWebsocketPing

eth/filters/filter_system_test.go
I used a private field in the test which is ugly but the test isn't using a constant timeout which should be more reliable.
```terminal
--- FAIL: TestPendingTxFilterDeadlock (0.43s)
filter_system_test.go:945: Filter 0xb8eae786b9803d3d609b2c821eb1063b should have been uninstalled
filter_system_test.go:945: Filter 0x9c29340950cc32a5d529614bc7eebba6 should have been uninstalled
filter_system_test.go:945: Filter 0xee2adcbcb566863626d022fd9a7cf25d should have been uninstalled
filter_system_test.go:945: Filter 0x9787a8ad2029820e12ec76c42834669b should have been uninstalled
filter_system_test.go:945: Filter 0x4ed8bcb649c19fb643819d1a0a4c7d5 should have been uninstalled
filter_system_test.go:945: Filter 0x63649cc3a9ff47d4fae0f9c288b03e57 should have been uninstalled
filter_system_test.go:945: …
```
=> eth/filters: fix flaky test

crypto/blake2b/blake2b_f_fuzz_test.go, crypto/blake2b/blake2b_f_test.go
This PR tries to unbork master by only enabling the fuzzer if non-generic functions can be accessed (which is not the case on 32-bit platforms)
=> crypto/blake2b: only fuzz non-generic functions if enabled

appveyor.yml, build/ci.go, core/blockchain.go, core/state/snapshot/disklayer.go, core/state/snapshot/snapshot.go, tests/state_test_util.go
This change fixes a memory leak, when running either state-tests or blockchain-tests, we allocate a `1MB` fastcache during snapshot generation. `fastcache` is a bit special, and requires a `Reset()` (it has it's own memory allocator). 
The `1MB` was hidden [here](https://github.com/ethereum/go-ethereum/blob/master/tests/state_test_util.go#L333) and [here](https://github.com/ethereum/go-ethereum/blob/master/tests/block_test_util.go#L146) respectively.
=> core/state, tests: fix memory leak via fastcache

event/subscription.go, event/subscription_test.go
A goroutine oversees the lifetime of subscriptions handled by resubscriptions. This goroutine terminates when the subscription ends without any errors.  However, the resub goroutine needs to live long enough to read from the unsub channel. Otherwise, an Unsubscribe call deadlocks when writing to the unsub channel.
=> event: fix Resubscribe deadlock when unsubscribing after inner sub ends

core/rawdb/freezer_resettable.go, core/rawdb/freezer_table.go, trie/triedb/pathdb/history.go, trie/triedb/pathdb/history_test.go
This PR adds more error message for debugging purpose.
Here is a [bug report](https://github.com/ethereum/go-ethereum/issues/28105) which indicates that index file of freezer might be corrupted by having an invalid last index item {headFileID, offset=0}.
It should never occur and the added log is to determine it's the case.
=> trie/triedb/pathdb, core/rawdb: enhance error message in freezer

graphql/graphql.go
return error instead of nil if block from > to
=> graphql: return error if block from>to

eth/protocols/snap/metrics.go, eth/protocols/snap/sync.go, eth/protocols/snap/sync_test.go, trie/stacktrie.go, trie/stacktrie_test.go, trie/sync.go
This pull request implements two optional features for stacktrie:
- Filtering out the boundary nodes to avoid committing "incomplete" ones
- Detecting dangling nodes fall within the path covered by an extension node
These two features can be used to enhance the snap sync in the case of path mode.
---
**Why to filter out boundary nodes?**
In the snap sync, a large trie is separated into several chunks(usually 16) to sync concurrently. For single chunk, there is a corresponding stack trie to accept the states within this range and build the merkle trie nodes on top.
However, the lack of states ahead and behind, the generated merkle trie nodes on boundary are incomplete. They do not match the nodes in the full trie.
In this example above, the trie is divided into three ranges. The partial …
=> core, eth, trie: filter out boundary nodes and remove dangling nodes in stacktrie

core/txpool/legacypool/legacypool.go
deprecated ErrAlreadyKnown  in legacypool
=> txpool/legacypool: remove already known error in legacypool

core/state/snapshot/generate.go, trie/stacktrie.go, trie/stacktrie_test.go
Follow-up to https://github.com/ethereum/go-ethereum/pull/28350 . 
This PR removes `panic`s from stacktrie (mostly), and makes the `Update` return errors instead. While adding tests for this, I also found that one case of possible corruption was not caught. 
If we inserted into an existing node, we noticed and panic:ed. However, it was possible to insert into an "empty slot" further back, so inserting at `0xaa` followed by `0x10` did not panic. To handle that, I now added a `lastPath` to the stacktrie, to keep record of the path of the last inserted item. 
This can also be useful for keeping track of the right hand boundary.
=> trie: use explicit errors in stacktrie (instead of panic)

rpc/types.go, rpc/types_test.go
The String() version of BlockNumberOrHash uses decimal for all block numbers, including negative ones used to indicate labels. Switch to using BlockNumber.String() which encodes it correctly for use in the JSON-RPC API.
The incorrect encoding was introduced in https://github.com/ethereum/go-ethereum/pull/28087 when switching from the working but non-standard object encoding (e.g. `{"blockNumber":"0x7fffffffffffffff"}`) that comes from JSON serialising `BlockNumberOrHash` to using `String()` to return a single value.  With this implementation of `String()` it matches the execution-apis spec for block hash, block number and block labels.
=> ethclient: Fix eth_getBlockReceipts call when using block numbers or labels

graphql/graphql.go, graphql/graphql_test.go
Fix as issue of nil pointer panic
> query
```graphql
{blocks { number }}
```
> response
```json
{
"errors": [
{
"message": "panic occurred: runtime error: invalid memory address or nil pointer dereference",
"path": [
"blocks"
]
}
],
"data": null
}
```
and the stack:
```
> 2023/10/26 08:25:36 graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
goroutine 4252 [running]:
github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0x28?, {0x104254960?, 0x140014805a0}, {0x103fdb9a0, 0x104d31bf0})
github.com/graph-gophers/graphql-go@v1.3.0/log/log.go:21 +0x58
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1()
github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:187 +0x80
panic({0x103fdb9a0?, 0x104d31bf0?}) …
```
=> graphql: fix an issue of nil pointer panic

graphql/graphql_test.go, graphql/service.go
Fix an issue of wrong Content-Type
```
$ curl -XPOST 127.0.0.1:8545/graphql -d '{"query": "{block(number: 1  hash: \"0xc1d1224983a2b43f2ea1b847337eda55e316e94603386e346abe3f6e08121027\") {number hash }}"}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
* Connected to 127.0.0.1 (127.0.0.1) port 8545 (#0)
> POST /graphql HTTP/1.1
> Host: 127.0.0.1:8545
> User-Agent: curl/8.1.2
> Accept: */*
> Content-Length: 124
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 400 Bad Request
< Date: Thu, 26 Oct 2023 00:29:18 GMT
< Content-Length: 110
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 127.0.0.1 left intact
{"errors":[{"message":"only one of number or hash must be specified","path":["block"]}],"data":{"block":null}}
```
@s1na PTAL
=> graphql: set content-type as json

trie/triedb/pathdb/database_test.go, trie/triedb/pathdb/disklayer.go, trie/triedb/pathdb/history.go
This pull request fixes an edge case in state history management.
In the context of the path model, Geth maintains a list of state histories to facilitate the rollback of the persistent state when needed. To prevent uncontrolled expansion of state history, Geth also provides a mechanism to prune the oldest state histories.
Because Geth manages the state layer in a tree structure, whenever a new layer is piled on top, it will trigger the merging of bottom diff layer with disk layer. This merging operation also involves the construction of the corresponding state history of the bottom diff layer and the truncation of oldest state histories.
However, a potential issue can happen if an unclean shutdown occurs after persisting the state history but before flushing the cached states to disk. In …
=> trie/triedb/pathdb: improve dirty node flushing trigger

core/rawdb/accessors_chain.go, core/rawdb/freezer_resettable.go
This PR adds logging and fixes some comments around the `AncientRange` function. Addresses #27667.
=> core/rawdb: add logging and fix comments around AncientRange function.

core/bench_test.go, core/chain_makers.go, core/chain_makers_test.go, core/state_processor.go, core/state_processor_test.go, eth/filters/filter_test.go
This change improves GenerateChain to support internal chain history access (ChainReader) for the consensus engine and EVM.
GenerateChain takes a `parent` block and the number of blocks to create. With my changes, the consensus engine and EVM can now access blocks from `parent` up to the block currently being generated. This is required to make the BLOCKHASH instruction work, and also needed to create signed clique chains. Clique uses chain history to figure out if the current signer is in-turn, for example.
I've also added some more accessors to BlockGen. These are helpful when creating transactions:
- g.Signer returns a signer instance for the current block
- g.Difficulty returns the current block difficulty
- g.Gas returns the remaining gas amount
=> core: add basic chain history support in GenerateChain

cmd/evm/blockrunner.go
Adds `--single-test` option to `evm blocktest` to run a single test from a given json BlockchainTest file.
This allows [execution-spec-tests](https://github.com/ethereum/execution-spec-tests/) to verify each of the tests it produces individually, because at the moment we verify the entire json file and it's not simple to detect which one of the included tests was the one that failed.
=> cmd/evm: Add `--single-test` option to blocktest

ethdb/pebble/pebble.go
Fixes https://github.com/ethereum/go-ethereum/issues/28384
Wait the upstream [fix](https://github.com/cockroachdb/pebble/pull/3008/files) to revert this "temporary" fix.
=> ethdb/pebble: cap memory table size as maxMemTableSize-1

core/vm/opcodes.go
Small change that improves the performance of `OpCode.String()` by changing:
```diff
- var opCodeToString = map[OpCode]string{
+ var opCodeToString = [256]string{
```
> `// Since the opcodes aren't all in order we can't use a regular slice.`
Yes, but we can use an array and define opcodes using a key-value-pair as one would do in a map (so order still does not matter).
=> core/vm: performance tweak of `OpCode.String()`

eth/backend.go, eth/ethconfig/config.go, ethclient/ethclient_test.go
> This improves the user experience when creating a private network
because the --networkid flag doesn't need to be specified anymore.
Replaces https://github.com/ethereum/go-ethereum/pull/20271 as that has some nasty discussions and is quite stale
=> eth: set networkID to chainID by default

graphql/graphql.go, graphql/schema.go
Discussed in https://github.com/ethereum/execution-apis/pull/471
as `r`, `s`, `v` are bigints, so yParity should also be the same.
=> graphql: change the type of yParity from Long to BigInt

cmd/geth/logtestcmd_active.go, cmd/geth/testdata/logging/logtest-json.txt, cmd/geth/testdata/logging/logtest-logfmt.txt, cmd/geth/testdata/logging/logtest-terminal.txt
This adds more edgecases around logging, particularly around handling of different types of nil-values as concrete types and within interfaces.
Also adds tests with 'reserved' values which breaks json/logfmt formats. The json output is checked in, but not actively used by any testcase at the moment.
I also removed the timestamps from the output, to remove some of the 'false postives' when we make any changes to it. 
This PR is in preparation of #28187
=> cmd/geth: more testcases for logging

ethdb/pebble/pebble.go
https://github.com/cockroachdb/pebble/commit/422dce9100554605cb60f1b29e77287d70f540ae added `Errorf` to the Logger interface; add this to `panicLogger` to allow compilation with latest version.
=> ethdb/pebble: add `Errorf` function to panicLogger

eth/filters/api.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go
Currently, geth's will return `[]` for any `len(topics) > 4` log filter. If user request a large range of blocks, this will only make geth to do useless works. So maybe we can fast exit if the query topics is invalid at the beginning.
FYI, here is some responses for different client. 
> request
```json
{
"method": "eth_getLogs",
"id": 74,
"params": [
{
"address": "0x514910771af9ca656af840dff83e8264ecf986ca",
"toBlock": "0x11AC43D",
"fromBlock": "0x11AC43D",
"topics": [[], [], [], [], []]
}
]
}
```
> reth's response
```json
{
"error": {
"code": -32602,
"data": "exceeded maximum topics len at line 7 column 5",
"message": "Invalid params"
},
"id": 74,
"jsonrpc": "2.0"
}
```
> erigon's response
```json
{
"id": 74,
"result": []
}
```
> and here is the …
=> eth/filters: exit early if topics-filter has more than 4 topics

core/rawdb/ancient_utils.go, core/rawdb/freezer_batch.go, core/rawdb/freezer_table.go, core/rawdb/freezer_utils.go
This pull request tries to fix an issue in freezer, raised by #28105 
--- 
Let's briefly recap the issue: If a power failure occurs during the execution in path model, Geth may not be able to recover in the subsequent restart.
After investigating a bit further, I discovered that the underlying state freezer is corrupted. Specifically, the freezer has experienced corruption in its index files, which now contain indexes with the values {file_num = 0; offset = 0} at the end.
Upon accessing the freezer table, it will initiate a repair process by truncating the excess bytes in the data file. However, due to the "zero" index at the end, the freezer table truncates the entire data file while retaining the complete index file.
Therefore, freezer table enters a very weird status that items indexes …
=> core/rawdb: fsync the index file after each freezer write

cmd/evm/staterunner.go
This just makes it simpler for other `evm` implementations testing against `geth`.
=> cmd/evm: allow state dump regardless if test passes in statetest

ethclient/gethclient/gethclient_test.go
I apologize for the inappropriate fix for the issue https://github.com/ethereum/go-ethereum/issues/28441. Here, I have added two new test cases to differentiate between the scenarios:
1. the account/contract does not exists;
2. the account/contract exists but is empty.
=> ethclient: add empty/nonexist account testcase for eth_getProof RPC

build/checksums.txt
New security fix: https://groups.google.com/g/golang-announce/c/4tU8LZfBFkY
=> build: upgrade -dlgo version to Go 1.21.4

core/asm/asm_test.go, core/vm/opcodes.go
As reported by @LukaszRozmej:
```
{"op":{"isPush":false,"asString":"PUSH0","asNumber":95}
```
=> eth/tracers/js: fix isPush for push0

tests/block_test.go, tests/state_test.go
This change makes it so that we, when running on 32-bit windows (typically CI on appveyor), we skip half the blockchain-tests and state-tests. Executing the `tests/` currently takes roughly 1000seconds, bumping the total test exec time to above 1 hour, which times out on appveyor. 
I am hoping that this shaves off ~500 seconds, which should make the CI green again. We could even be more aggressive, say execute only 20% of the tests -- as long as every test is executed at least from time to time regularly.
=> tests: skip tests on windows 32bit CI

cmd/geth/logtestcmd_active.go, cmd/geth/testdata/logging/logtest-logfmt.txt, cmd/geth/testdata/logging/logtest-terminal.txt
Add more logging tests to handle a bug that was introduced in the slog PR: https://github.com/ethereum/go-ethereum/pull/28187#discussion_r1393210010
=> cmd/geth: add logging tests for errors and fmt.Stringer values that have quotes and spaces

miner/miner_test.go, miner/ordering_test.go, miner/payload_building_test.go, miner/worker_test.go
Running `golangci-lint run ./... -E paralleltest` reveals that a lot of tests might be able to run in parallel, to make them run faster. Here I add `t.Parallel()` to all tests in the miner package:
```
$ go test ./miner/... -race -count=1
// Before
ok  	github.com/ethereum/go-ethereum/miner	9.768s
// After
ok  	github.com/ethereum/go-ethereum/miner	6.491s
```
If you are interested I can also refactor the other packages to run tests in parallel? From an initial look at it this will create a lot of race conditions (sharing resources?), so it has to be done selectively (refactoring tests to not interfere with each other is not in scope for this work, but could be done later).
It's also possible to run sub tests in parallel more places.
=> miner: run tests in parallel

internal/jsre/deps/web3.js
fix `formatOutputUInt` function jsdoc 
return type from  `BigNumeber`  to `BigNumber `
=> internal/jsre/deps: fix typo in jsdoc

accounts/scwallet/wallet.go, cmd/p2psim/main.go, p2p/nat/nat.go, p2p/simulations/http.go, rpc/json.go, rpc/service.go
=> all: replace some strings.SplitN(arg, sep, 2) with strings.Cut(arg, sep)

ethdb/memorydb/memorydb.go, ethdb/memorydb/memorydb_test.go, trie/iterator.go, trie/iterator_test.go, trie/sync_test.go
The changes in https://github.com/ethereum/go-ethereum/pull/28461 regarding the `sync_test` showed that by adding a resolver, the node iterator sped up considerably. This is really kind of strange, since a memorydb is in essence a map of `string->[]byte`, exactly the same thing as the resolver used instead. 
While investigating, I found that one big reason for the test being slow is that a lot of time is spent on gc. And the upside of using a naive slice instead of memorydb is that memorydb copies on write, and copies again on read. This PR removes one unnecessary copy of the key though. 
```
name           old time/op    new time/op    delta
BatchAllocs-8     412µs ± 6%     382µs ± 2%   -7.18%  (p=0.016 n=5+4)
name           old alloc/op   new alloc/op   delta
BatchAllocs-8     480kB ± …
```
=> ethdb/memorydb, trie: reduced allocations

tests/block_test_util.go
This PR additionally verifies the accounts' storage as specified in a blockchain test's `postState` field (as described in the "Expect" section [here](https://ethereum-tests.readthedocs.io/en/latest/test_filler/blockchain_filler.html#expect)).
=> cmd/evm: validate blockchain tests poststate account storage

signer/core/api_test.go, signer/core/apitypes/signed_data_internal_test.go, signer/core/apitypes/types_test.go, signer/core/signed_data_test.go, signer/core/validation_test.go, signer/fourbyte/abi_test.go, signer/fourbyte/fourbyte_test.go, signer/fourbyte/validation_test.go, signer/rules/rules_test.go, signer/storage/aes_gcm_storage_test.go
Continuation of https://github.com/ethereum/go-ethereum/pull/28506
Run more tests in parallel.
```
go test ./signer/... -race -count=1
// Before
ok  	github.com/ethereum/go-ethereum/signer/core	16.925s
ok  	github.com/ethereum/go-ethereum/signer/core/apitypes	1.487s
ok  	github.com/ethereum/go-ethereum/signer/fourbyte	39.548s
ok  	github.com/ethereum/go-ethereum/signer/rules	3.115s
ok  	github.com/ethereum/go-ethereum/signer/storage	2.306s
// After
ok  	github.com/ethereum/go-ethereum/signer/core	9.835s
ok  	github.com/ethereum/go-ethereum/signer/core/apitypes	1.515s
ok  	github.com/ethereum/go-ethereum/signer/fourbyte	43.597s
ok  	github.com/ethereum/go-ethereum/signer/rules	3.537s
ok  	github.com/ethereum/go-ethereum/signer/storage	2.758s
```
=> signer: run tests in parallel

core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go
I've added a check for `pool.config.NoLocals` when setting up `txpool` validation. The goal is to reject transactions if they don't meet the `--txpool.pricelimit` setting.
=> core/txpool/legacypool: respect nolocals-setting

cmd/abigen/namefilter_test.go, cmd/clef/consolecmd_test.go, cmd/devp2p/dns_route53_test.go, cmd/devp2p/internal/ethtest/chain_test.go, cmd/devp2p/internal/ethtest/suite_test.go, cmd/ethkey/message_test.go, cmd/evm/t8n_test.go, cmd/faucet/faucet_test.go, cmd/geth/accountcmd_test.go, cmd/geth/consolecmd_test.go, cmd/geth/exportcmd_test.go, cmd/geth/les_test.go, cmd/geth/logging_test.go, cmd/geth/version_check_test.go, cmd/rlpdump/rlpdump_test.go, cmd/utils/export_test.go, cmd/utils/flags_test.go, cmd/utils/prompt_test.go
Continuation of https://github.com/ethereum/go-ethereum/pull/28506
=> cmd: run tests in parallel

cmd/evm/blockrunner.go, cmd/evm/compiler.go, cmd/evm/disasm.go, cmd/evm/main.go, cmd/evm/runner.go
When I used the “evm --help” command, the output displayed the content in the figure below. I noticed that the capitalization was inconsistent.
I standardized the capitalization to make it more consistent and readable.
=> cmd/evm: capitalize evm commands

accounts/abi/error.go
In my opinion, if we need to return different errors for different parameter check, we should split them, otherwise we should put them together 
```go
if len(data) < 4 || !bytes.Equal(data[:4], e.ID[:4]) {
return "", errors.New("invalid data for unpacking")
}
```
=> accounts/abi: distinguish 'Unpack' error

accounts/keystore/account_cache_test.go, core/forkid/forkid_test.go, core/state/statedb_test.go, rpc/client_test.go, trie/sync_test.go
This PR makes a few of our tests faster, the changes are in separate commits which makes it easier to review and shows their advantages. 
All in all these fixes take our whole pipeline (including ethereum/tests) from 96s to 88s on my machine.
=> core, trie, rpc: speed up tests

ethdb/pebble/pebble.go
Adds `released` flag to `pebbleIterator` to avoid double closing `cockroachdb/pebble.Iterator` as it is an invalid operation.
Fixes #28565
=> ethdb/pebble: don't double-close iterator inside pebbleIterator

core/types/transaction.go, core/types/transaction_marshalling.go, core/types/transaction_test.go
Removes a redundant check for `dec.V == nil` on transaction types that accept either `V` or `yParity`.
The check is performed by `yParityValue`, so the extra check at `UnmarshalJSON` resulted in the unmarshal failing when the `V` field was missing, but `yParity` was present.
Currently the redundant check was present only in `DynamicFeeTxType` and `BlobTxType`, and was caught during hive testing because besu was returning only `yParity` on `eth_getBlockByNumber` in its blob type transactions, and this is correct as specified by the [API](https://ethereum.github.io/execution-apis/api-documentation/).
Added unit test `TestYParityJSONUnmarshalling`.
=> core/types: make 'v' optional for DynamicFeeTx and BlobTx

cmd/utils/flags.go, core/genesis.go, eth/catalyst/simulated_beacon.go, params/config.go
Dev mode should expect TTD to be passed at genesis.  With these changes, it also asserts that pre-merge non-DAO, non-difficulty bomb delay HFs are activated at block 0 (not strictly necessary for all of them but why not 🤷‍♂️ )
This aims to help prevent users from foot-gunning themselves if they misconfigure a custom genesis.
=> cmd/utils:  if dev-mode is enabled and db is pre-existing, validate that genesis configuration is compatible

docs/developers/dapp-developer/dev-mode.md
Also remove redundant blurb.
Depends on https://github.com/ethereum/go-ethereum/pull/28463
=> website: add subsection about running in development mode with custom genesis configuration

les/vflux/client/fillset_test.go, les/vflux/client/queueiterator_test.go, les/vflux/client/requestbasket_test.go, les/vflux/client/serverpool_test.go, les/vflux/client/timestats_test.go, les/vflux/client/valuetracker_test.go, les/vflux/client/wrsiterator_test.go, les/vflux/server/balance_test.go, les/vflux/server/clientdb_test.go, les/vflux/server/clientpool_test.go, les/vflux/server/prioritypool_test.go
Continuation of https://github.com/ethereum/go-ethereum/pull/28506
Run more tests in parallel. I'm currently running on a 2019 intel Mac, so it's a bit slow...
There are more tests that can be parallelized in the `les` package, but I thought it would be nice to split it up into multiple PRs.
```
➜  go-ethereum git:(estensen/parallel-tests-les) ✗ go test ./les/vflux/client -race -count=1
➜  go-ethereum git:(estensen/parallel-tests-les) ✗ go test ./les/vflux/server -race -count=1
// Before
ok  	github.com/ethereum/go-ethereum/les/vflux/client	5.536s
ok  	github.com/ethereum/go-ethereum/les/vflux/server	132.992s
// After 
ok  	github.com/ethereum/go-ethereum/les/vflux/client	2.509s
ok  	github.com/ethereum/go-ethereum/les/vflux/server	32.019s
```
=> les/vflux: run tests in parallel

cmd/devp2p/internal/ethtest/snap.go
remove debug-hack flaw preventing tests from running
=> cmd/devp2p/internal/ethtest: fix debug-hack

trie/trie_test.go
This PR is a one-liner change to fix the minor bug in the `randTest.Generate` function.
When generating random tests for the Trie, the Generate function should terminate only when the size reaches 0. However, the current code does the opposite, effectively causing the random Trie tests to be redundant since there are no test cases at all.
=> trie: fix random test generator early terminate

eth/catalyst/api.go, eth/downloader/skeleton.go, eth/downloader/skeleton_test.go, trie/verkle_test.go
This pull request exposes more information from sync module internally.
=> eth/catalyst, eth/downloader: expose more sync information

eth/tracers/js/goja.go
As pointed out by @LukaszRozmej there are 2 type inconsistencies in the JS tracer:
- In most places we return byte arrays as a `Uint8Array` to the tracer. However it seems we missed doing the conversion for `ctx` fields which are passed to the tracer during `result`. They are passed as simple arrays. I think Uint8Arrays are more suitable and we should change this inconsistency. Note: this will be a breaking-change. But I believe the effect is small. If we look at our tracers we see that these fields (`ctx.from`, `ctx.to`, etc.) are used in 2 ways. Passed to `toHex` which takes both array or buffer. Or the length was measured which is the same for both types.
- The `slice` taking in `int, int` params versus `memory.slice` taking `int64, int64` params. I suggest changing `slice` types to …
=> eth/tracers/js: fix type inconsistencies

crypto/secp256k1/secp256_test.go
The 32-bit tests are broken because a test file builds regardless of the `CGO_ENABLED` context, when the functions it uses are only availanle when `CGO_ENABLED=1`. This PR makes the two file be both included (or not) depending on the value of `CGO_ENABLED`.
=> crypto/secp256k1: fix 32-bit tests when CGO_ENABLED=0

consensus/clique/clique.go, consensus/ethash/consensus.go
In Clique and Ethash, Shanghai- and Cancun-specific header fields should be nil (as is the BaseFee before the EIP-1559 fork).
=> clique, ethash: verify the non-existence of shanghai- and cancun-specific header fields

core/state_transition.go, eth/gasestimator/gasestimator.go, graphql/graphql_test.go, internal/ethapi/api.go, internal/ethapi/api_test.go
This PR adds three optimisations to gas estimation:
- A precise optimization is trying to return 21000 gas for plain transfers. It does it if there's no contract code at the receiver side and no input data. The call is still simulated before returning 21000 to catch any potential future unaccounted tx cost (like access lists currently). This results in a total iteration count of 1 for plain transfers.
- Introduces an error ratio (currently set to 1.5%) to allow short circuiting the binary search faster by returning a slight overestimate. This reduces the number of needed estimation calls from 18-20 to 7-8 at the cost of overshooting the perfect estimate by 1.5% gas max. Maybe this could be made configurable in the future, but I think it's useful to be more agressive by default than …
=> eth/gasestimator: allow slight estimation error in favor of less iterations

internal/testlog/testlog.go, log/format.go, log/format_test.go, log/handler.go, log/logger_test.go
Some previous discussion here: https://github.com/jwasinger/go-ethereum/pull/8 
----
These changes improves the performance of the non-coloured terminal formatting, _quite a lot_. 
```
name               old time/op    new time/op    delta
TerminalHandler-8    10.2µs ±15%     5.4µs ± 9%  -47.02%  (p=0.008 n=5+5)
name               old alloc/op   new alloc/op   delta
TerminalHandler-8    2.17kB ± 0%    0.40kB ± 0%  -81.46%  (p=0.008 n=5+5)
name               old allocs/op  new allocs/op  delta
TerminalHandler-8      33.0 ± 0%       5.0 ± 0%  -84.85%  (p=0.008 n=5+5)
```
I tried to _somewhat_ organize the commits, but the it might still be a bit chaotic. Some core insights: 
- The function `terminalHandler.Handl` uses a mutex, and writes all output immediately to 'upstream'. Thus, it can …
=> slog: faster and less memory-consumption

eth/tracers/api.go, eth/tracers/api_test.go
Currently, `debug_traceCall` only supports invoking the post-state based on a specific block. 
However, in some cases, we may want to simulate the transaction based on the state of a specific intermediate index within a block. For example, when analyzing a scenario involving a malicious transaction, we may want to simulate the execution of that malicious transaction based on the state before its execution to observe the impact it would have caused.
So I added the field `txIndex` in the `TraceCallConfig`
=> eth/tracers: support debug_traceCall on transaction

cmd/evm/README.md
Followed the evm/cmd documentation, found that the actual returned json field **currentDifficulty** are not consistent with the description of the documentation.
=> cmd/evm:fix Env struct json tag

common/hexutil/json.go, common/hexutil/json_test.go, eth/tracers/logger/gen_structlog.go, eth/tracers/logger/logger.go
The recent update to `uint256.Int` to make it default to same output-format as `big.Int` broke the fuzzer, since now it spits out stack items as `dec`. 
```
[user@work go-ethereum]$ go run ./cmd/evm/ --code 6040 --json run
{"pc":0,"op":96,"gas":"0x2540be400","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":2,"op":0,"gas":"0x2540be3fd","gasCost":"0x0","memSize":0,"stack":["64"],"depth":1,"refund":0,"opName":"STOP"}
```
This PR changes it back to `hex`: 
```
[user@work go-ethereum]$ go run ./cmd/evm/ --code 6040 --json run
{"pc":0,"op":96,"gas":"0x2540be400","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":2,"op":0,"gas":"0x2540be3fd","gasCost":"0x0","memSize":0,"stack":["0x40"],"depth":1,"refund":0,"opName":"STOP"} …
```
=> eth/tracers/logger: make structlog/json-log stack hex again

cmd/geth/logtestcmd_active.go, cmd/geth/testdata/logging/logtest-json.txt, cmd/geth/testdata/logging/logtest-logfmt.txt, cmd/geth/testdata/logging/logtest-terminal.txt, internal/debug/flags.go, internal/testlog/testlog.go, log/format.go, log/handler.go, log/logger.go, log/logger_test.go, p2p/discover/table.go, p2p/msgrate/msgrate.go
Follow-up to https://github.com/ethereum/go-ethereum/pull/28621 
- Removes interface `log.Format`, 
- Removes method `log.FormatFunc`, 
- unexports `TerminalHandler.TerminalFormat` formatting methods (renamed to `TerminalHandler.format`)
- ~~renames `JSONHandler` to `NewJSONHandler` (more go-idiomatic)~~
- ~~renames `LogfmtHandler` to `NewLogfmtHandler` (more go-idiomatic)~~
- removes the notion of `log.Lazy` values
The lazy handler was useful in the old log package, since it could defer the evaluation of costly attributes until later in the log pipeline: thus, if the logging was done at 'Trace', we could skip evaluation if logging only was set to 'Info'.
With the move to slog, this way of deferring evaluation is no longer needed, since slog introduced 'Enabled': the caller can thus do …
=> log: polishes to exported interface

.github/workflows/go.yml
This is a 2nd attempt in running 32-bit tests outside of appveryor's 32 bit windows. The previous attempt in #28523 ran into the same problem described in #28378.
As an intermediate approach, this PR will build a  i386, 32-bit linux binary and run it. This works because linux is still able to run i386 binaries without an emulation layer since intel/amd processors are still backwards-compatible.
=> .github: use github actions to run 32-bit linux tests

build/checksums.txt
New security fix: https://groups.google.com/g/golang-announce/c/iLGK3x6yuNo
=> build: upgrade -dlgo version to Go 1.21.5

cmd/evm/staterunner.go, core/state/dump.go
When investigating https://github.com/ethereum/evmone/issues/740, I noticed that the dump after state-test didn't seem to work. 
Can be tested by storing that statetest as `foo.json` and running: 
```
go run ./cmd/evm --json --dump  statetest   ./foo.json
```
With this PR , it works. The problem was an error, "Already committed", which was silently ignored. The state needs to be re-initialized for the dumping to work.
=> cmd/evm: fix dump after state-test exec

cmd/utils/flags.go, eth/handler.go
- Add a check to eth/handler to refuse to start in snap sync mode without snapshots
- Add a check to cmd/utils to fix invalid combos before reaching the startup fault in eth/handler
=> cmd/utils, eth: disallow invalid snap sync / snapshot flag combos

ethdb/dbtest/testsuite.go, trie/sync.go, trie/sync_test.go
This pull request fixes #28587 
--- 
**State sync recap**
In Geth state sync mechanism, there are two steps: (1) snap sync (2) state healing. In the first stage, Geth will request a batch of states(accounts and storage slots), verify the correctness via range proof and construct the internal merkle tree nodes locally. 
However due to the fact that the retrieved states may be incomplete, lacking either the head or the tail, the locally constructed merkle trie nodes may be inconsistent with the correct one. In order to avoid committing inconsistent trie nodes, the boundary trie nodes are filtered out and this logic is implemented in https://github.com/ethereum/go-ethereum/pull/28327.
After retrieving the states of the entire keyspace, the persistent states, along with their Merkle tree …
=> trie: remove inconsistent trie nodes during sync in path mode

cmd/utils/flags.go
Fixes https://github.com/ethereum/go-ethereum/issues/28668.
When users specify the `http.addr` and `ws.addr` command line flags, they will overwrite the `HTTPHost` and `WSHost` in the config file.
=> cmd/utils: fix HTTPHost, WSHost flag priority

eth/protocols/eth/dispatcher.go, eth/protocols/eth/peer.go, log/logger.go
minor typo fix
two comments, one returned message
=> eth/protocols/eth: fix typos in comments

eth/fetcher/tx_fetcher_test.go, eth/gasestimator/gasestimator.go
hey, few typos i found in comments, this is a minor change.
have a nice afternoon.
=> eth/fetcher, eth/gasestimator: fix typos in comments

accounts/abi/abi.go, accounts/abi/bind/auth.go, accounts/abi/bind/base.go, accounts/abi/bind/bind.go, accounts/abi/topics.go, cmd/clef/README.md
Hello,
I fixed several minor typos.
Hope it helps.
Br, Elias.
=> all: fix typos in comments

miner/worker.go
When there are plenty of chainHead events rushing into the `chainHeadCh` channel, it is possible to make the `resubmitAdjustCh` full, which would cause the `commitWork`  to get stuck,  and because of which the `newWorkLoop` will stuck here at the call of `commit(true, commitInterruptNewHead)`
Finally the `newWorkLoop` and `mainLoop` would fall into a dead loop.
so I use `select` statement to prevent the `commitWork`  from being blocked at 
`w.resubmitAdjustCh <- &intervalAdjust{inc: false}`.  If `resubmitAdjustCh` is full, just discard the message.
=> miner: eliminate the dead loop possibility for `newWorkLoop` and `mainLoop`

internal/flags/helpers.go
Flags like `--rpc.txfeecap` currently don't have an env var auto-generated for them. This PR adds three missing cli flag types to the auto env-var helper function to fix this.
This was probably missed in the original work that added auto env-vars: https://github.com/ethereum/go-ethereum/pull/28103
Would be great if we can still get this into [`1.13.6`](https://github.com/ethereum/go-ethereum/milestone/154) 🙏🏻
=> internal/flags: add missing flag types for auto-env-var generation

cmd/bootnode/main.go, cmd/clef/main.go, cmd/evm/internal/t8ntool/block.go, cmd/evm/internal/t8ntool/transaction.go, cmd/evm/internal/t8ntool/transition.go, cmd/evm/main.go
This change fixes a problem with our non-core binaries: `evm`, `clef`, `bootnode`. 
First of all, they failed to convert from legacy loglevels `1 to 5`, to the new slog loglevels `-4 to 4`. 
Secondly, the logging was actually setup in the init phase, and then overridden in the main. This is not needed for `evm`, since it used the same flag name as the main geth `verbosity`. Better to let the flags/internal handle the logging init.
=> cmd/evm, cmd/clef, cmd/bootnode: fix / unify logging

core/rawdb/freezer_table.go, core/rawdb/freezer_table_test.go
This is the fix to issue #27483. A new hiddenBytes() is introduced to calculate the byte size of hidden items in the freezer table. When reporting the size of the freezer table, size of the hidden items will be subtracted from the total size.
=> core/rawdb: implement size reporting for live items in freezer_table

.travis.yml
As documented on https://golangci-lint.run/usage/performance/ , a lower GOGC value causes less peak mem consumption when running the linter.
Exceeding 3Gb is a common cause for build failures, according to https://docs.travis-ci.com/user/common-build-problems/#my-build-script-is-killed-without-any-error
=> .travis: set lower GOGC value

internal/build/util.go
Fixes the crash below, which happens because the `done` channel was not initialized.
```
Waiting for command "build/cache/golangci-lint-1.51.1-linux-amd64/golangci-lint"
panic: close of nil channel
goroutine 1 [running]:
github.com/ethereum/go-ethereum/internal/build.MustRunCommandWithOutput({0xc0002d1500, 0x3a}, {0xc000296060, 0x4, 0x6})
/home/appveyor/projects/go-ethereum/internal/build/util.go:87 +0xac
main.doLint({0xc0000ae000, 0x0, 0x0})
/home/appveyor/projects/go-ethereum/build/ci.go:369 +0x237
main.main()
/home/appveyor/projects/go-ethereum/build/ci.go:167 +0x1b3
```
=> internal/build: fix crash in MustRunCommandWithOutput

.golangci.yml, build/checksums.txt, internal/build/gotool.go, internal/build/util.go
This is primarily to make lint work again on macOS 14. The older version of golangci-lint kept crashing. Also included is a fix for a goroutine leak in the recently-introduced function MustRunCommandWithOutput.
I had to disable the goconst linter because it started reporting issues all of sudden. These issues weren't new, but I think this linter is silly anyway and we're not going to start fixing the things it reports anytime soon. For example, it reported warnings like this one:
```text
node/node.go:681:9: string `http://` has 6 occurrences, make it a constant (goconst)
return "http://" + n.http.listenAddr()
```
=> build: upgrade to golangci-lint v1.55.2

cmd/geth/dbcmd.go, core/rawdb/ancient_scheme.go, core/rawdb/ancient_utils.go, core/rawdb/database.go, trie/triedb/pathdb/database.go
Alternative to #28715
-----------
Fix for https://github.com/ethereum/go-ethereum/issues/28713 
**Original problem** was caused by https://github.com/ethereum/go-ethereum/pull/28595 . In this PR, we made it so that as soon as we start to sync, we delete the root of the disk layer. That is not wrong per se, but, another part of the code uses the "presence of the root" as an init-check for the pathdb. And, since the init-check now failed, it tried to initialize it, which failed since a sync was already ongoing.
**Impact:** after a state-sync has begun, if the node is restarted, it will refuse to restart, with the error message: `Fatal: Failed to register the Ethereum service: waiting for sync`.
=> core, cmd, trie: fix the condition of pathdb initialization

core/rawdb/accessors_trie.go
This pull request improves the condition to check if path state scheme is ever used.
Originally root node presence is used as the indicator if path scheme is used or not. However due to fact that root node will be deleted during the initial snap sync, this condition is no longer useful.
Therefore, one more condition is added if the root node is not present => The presence of `PersistentStateID` is also checked, reasons:
- PersistentStateID is only available in path scheme
- PersistentStateID is only committed once we successfully update the persistent state, e.g. Initialize genesis state
- PersistentStateID entry won't be deleted ever.
If PersistentStateID is present, it can prove we did write state in path scheme before and it's a good indicator for path scheme.
=> core/rawdb: improve state scheme checking

core/state/statedb.go
Every other getter in statedb follows the pattern of:
```
if stateObject != nil {
return value
}
return defaultValue
```
I changed GetCodeHash to match this pattern
=> core/state: logic equivalence for GetCodeHash

tests/gen_stenv.go, tests/state_test_util.go
Adds `currentExcessBlobGas` to the state test parser, to be able to read tests generated by the following PR:
https://github.com/ethereum/execution-spec-tests/pull/356
The value is interpreted as the current context's ExcessBlobGas, as the value that would been read from the block's header, and assuming the value was correctly calculated by using the parent's ExcessBlobGas and BlobGasUsed.
=> tests: Add `currentExcessBlobGas` to state tests

build/ci.go
Seems we've missed to add the latest ubuntu
=> ci.go: add support for ubuntu 23.10: mantic minotaur

log/root.go
=> log: avoid setting default slog logger in init

cmd/evm/README.md
fix the relative path in  cmd/evm/README.md
before that:
=> chore(cmd/evm):fix link jump in cmd/evm/README.md

core/vm/operations_acl.go
Hi. Minor PR to update comments to match the related EIP
=> core/vm: update comments to match eip number

cmd/evm/internal/t8ntool/execution.go
Moves the block's blob-gas-used increment to the same place as the normal gas so that, in the case of failed transactions, neither gas type usage is incremented.
=> cmd/evm: Fix blob-gas-used on invalid transactions

cmd/geth/main.go, internal/flags/helpers.go
=> internal/flags: update copyright year to 2024

log/logger.go
closes https://github.com/ethereum/go-ethereum/pull/28774
=> log: emit error level string as "error".  not "eror"

eth/filters/api.go
FIx https://github.com/ethereum/go-ethereum/pull/28762 the logsub should not be unsubscribed earlier than the go func
=> eth/filters: fix early Unsubscribe of log events

core/forkid/forkid_test.go, params/config.go
This PR schedules the cancun fork for the goerli testnet as discussed on ACD.
Spec: https://github.com/ethereum/execution-specs/pull/860
We schedule:
goerli at 1705473120
=> params, core/forkid: schedule cancun fork on goerli

cmd/geth/dbcmd.go
Supersedes #28721
When managing geth over docker, sometimes it's desirable to do a partial wipe: delete state but retain freezer data. This can be a bit tricky: the ansible scripts to delete files individually are _slow_, a faster way to do it is to 
- move the freezer-data somewhere else, 
- delete the chaindata
- create the chaindata
- move back the freezer-data
This "works" but it's clumsy, and now that we have both block-data and state-data in freezer, it's a bit incomplete, the correct thing to do would be to save only the block-data, not the state-data. 
This PR implements an alternative way to achieve the same thing, by making it possible to run `geth removedb` non-interactive, using boolean options instead. 
------------
Explicitly removing chain (it asks about state, no question …
=> cmd/geth: make it possible to autopilot removedb

accounts/abi/topics.go, accounts/abi/topics_test.go
The bigInt encoding is wrong in contract topic if the bigInt is a negative number.
For example, the bigInt(-1) is encoded as `0000000000...000000000001`, while it should be `ffffffffff...ffff` instead.
=> accounts/abi: fix bigInt topic encoding

docs/interacting-with-geth/rpc/ns-debug.md
The `debug_stopGoTrace` API does not accept any parameters but is documented as accepting a file name.
https://github.com/ethereum/go-ethereum/blob/daa2e5d6a66833b9834b60a3a46835610bbde99a/internal/web3ext/web3ext.go#L340-L344
=> website: fix `debug.stopGoTrace()` param docs

eth/api_backend.go
we already have `func (b *EthAPIBackend) ChainConfig() *params.ChainConfig` and we can reuse it
=> eth: minor change of config-accessor

accounts/abi/bind/backends/simulated.go, accounts/abi/bind/util_test.go, ethclient/simulated/backend.go, ethclient/simulated/backend_test.go, ethclient/simulated/options.go, ethclient/simulated/options_test.go
This PR does a minor renaming of the simulated constructor and fixes some gas limit bugs introduced by the rework.
It also adds an initial batch of fine tuning options.
=> accounts, ethclient: minor tweaks on the new simulated backend

.github/workflows/go.yml, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/suite_test.go, internal/utesting/utesting.go
This test was failling consistently on the github 32-bit build probably due to slow IO. Skipping it for that green check.
=> cmd/devp2p/internal/ethtest: skip large tx test on github build

docs/fundamentals/private-network.md
This bug was already reported by [28450](https://github.com/ethereum/go-ethereum/issues/28450) on nov 1 and fixed in the same date by [28451](https://github.com/ethereum/go-ethereum/pull/28451,) but due to "Deploy Preview for geth-website failed" by netlify bot, was not deployed. 
On nov 7, the last comment of [28433](https://github.com/ethereum/go-ethereum/issues/28433#issuecomment-1800042790)  (the solution was pointed out in the same comment) reported the persistence of the bug, I tried by myself and found the bug still occurs:
This alternative PR fix this issue
=> docs: fix example to avoid  "gas required exceeds allowance"-error

p2p/dnsdisc/tree.go
in this case use `strings.Cut` is more clear && readable.
=> p2p/dnsdisc: use strings.Cut over strings.IndexByte

ethclient/gethclient/gethclient_test.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go
I found these two instances where we are estimating gas and computing the access list for a tx on top of the pending block. Given the discussions around deprecating pending (see #28623 or https://github.com/ethereum/execution-apis/issues/495), we can move away from it internally.
=> internal/ethapi: avoid using pending for defaults

cmd/rlpdump/main.go, cmd/rlpdump/rlpdump_test.go
```
go run ./cmd/rlpdump -pos cmd/devp2p/internal/ethtest/testdata/chain.rlp 
0: [
3:   [
6:     3d35e0b689cdd20720592d9a4d0d208de0612ebcb46e391141501e7d55d55b42,
39:     1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347,
72:     0000000000000000000000000000000000000000,
93:     e2eb6472cb1addc491bcf24dca5bc93e8a1feb5280793be6583e82fea2820772,
126:     8f3b22c4b001b4062f9430d885cf4dba33a3b086ada9e7768ecfe90b14df1ca1,
159:     b81239ff8b0e3bcb4b3b347b27f1236648dd4427e3e93c51e1144997d114ced2,
192:     0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> cmd/rlpdump: add -pos flag, displaying byte positions

ethclient/ethclient_test.go
This commit also asserts context.Cancel error upon canceling, and removes unnecessary newlines in logs messages.
=> ethclient: add tests for TransactionInBlock

tests/block_test_util.go
This prints some more info in case a block in a blockchain test fails decoding. 
```
$ go run ./cmd/evm/ blocktest ~/Downloads/invalid_blob_tx_contract_creation.json  2>&1 | tail -n 5
INFO [01-15|13:32:38.195] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [01-15|13:32:38.195] 
INFO [01-15|13:32:38.196] Loaded most recent local block           number=0 hash=93a8f6..9578db td=0 age=54y9mo3w
INFO [01-15|13:32:38.196] Block decoding failed                    index=0 err="rlp: input string too short for common.Address, decoding into (types.Block)(types.extblock).Txs[0](types.BlobTx).To"
INFO [01-15|13:32:38.196] Blockchain stopped
```
This was requested by testing-team (@danceratopz …
=> tests: more verbosity if block decoding fails

eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/internal/tracetest/flat_calltrace_test.go, eth/tracers/internal/tracetest/prestate_test.go, eth/tracers/internal/tracetest/testdata/prestate_tracer_with_diff_mode/create_failed.json, eth/tracers/tracers_test.go
While working on another issue, I found that in the tracing tests the base fee is generally set to `nil` (see https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/internal/tracetest/prestate_test.go#L120). Changing this to pass the proper base fee works for most tests, but `TestPrestateWithDiffModeTracer` runs into problems in the `create_failed.json` test case.
Here the base fee is 51088069741, and the transactions fee limit is set to 112855938170. The transactions tip cap is 1500000000. This leads to a gas price of 112855938170 when the base fee is not set, but 52588069741 when the base fee is set.
The difference between those two values is 60267868429, multiplied by the gas limit of the transaction (176545) this makes up a balance difference of 10639990831797805, which is …
=> tracer: use proper base fee in tests

eth/filters/filter_test.go
This PR resets `filter.begin` to 0 between benchmark iterations, otherwise the filter backend will update `begin` after the call to `Logs` and the 2nd call will return no logs.
Alternatively, can move:
```go
filter := sys.NewRangeFilter(0, -1, []common.Address{addr1, addr2, addr3, addr4}, nil)
``` 
to the loop if you prefer.
=> eth/filters: reset filter.begin in BenchmarkFilters

core/state_transition.go, core/txpool/blobpool/blobpool_test.go, core/txpool/validation.go, core/types/tx_blob.go, crypto/kzg4844/kzg4844.go, eth/downloader/queue.go, params/protocol_params.go
The code to compute a versioned hash was duplicated a couple times, and also had a small
issue: if we ever change params.BlobTxHashVersion, it will most likely also cause changes
to the actual hash computation. So it's a bit useless to have this constant in params.
=> crypto/kzg4844: add helpers for versioned blob hashes

core/forkid/forkid_test.go, params/config.go
This PR schedules the cancun fork for the goerli testnet as discussed on ACD.
Spec: https://github.com/ethereum/execution-specs/pull/860
We schedule:
sepolia at 1706655072
holesky at 1707305664
=> params, core/forkid: enables cancun on sepolia and holesky

README.md, cmd/geth/main.go
Geth is described as "the official golang" ethereum implementation, which is not proper. Geth does not have any more 'official' status than any other client. This PR removes the usage of this phrase.
=> docs: remove reference to being official

go.mod, go.sum
This is necessary for karalabe/usb#43 to buld on windows for arm64. It adds support for the arm64 target.
=> go.{mod,sum}: upgrade go-ole to support arm64

core/bench_test.go
Hi, currently the benchmarks `BenchmarkChainRead_header_10k` etc are failing with:
`error creating chain: database contains incompatible genesis (have c27db71b33e259aa7357e6d44f8f1c78adbae50d5ac59d61103ec0f1ad109a3f, new d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3`
I made this change to call `&core.Genesis{}.ToBlock().Header()` to set-up the genesis header, since the amount of setup in the test is not sufficient to pass through the checks in `SetupGenesisBlock`
Alternatively, we could set the loop to start at 1 [here](https://github.com/ethereum/go-ethereum/pull/28856/files#diff-d05251a221cde2fe44cf0b3a5f53f9d3a7317508308801a02568404e0779cf1eL248) for a less invasive change and similar effect, if you prefer.
=> core: fix genesis setup in benchReadChain

build/checksums.txt
New release: https://groups.google.com/g/golang-announce/c/F12eMaUITDs
=> build: upgrade -dlgo version to Go 1.21.6

core/state/pruner/bloom.go, core/state/snapshot/difflayer.go
This PR switches from using the Hasher interface to add/query the bloomfilter to implementing it as methods.
This significantly reduces the allocations for Search and Rebloom.
The allocations for the storageBloom alone was ~7% of all allocations (in a quite contrived scenario)
`  26666581   26666581    243:			dl.diffed.Add(storageBloomHasher{accountHash, storageHash})`
`  14812039   14812039    375:	hit := dl.diffed.Contains(storageBloomHasher{accountHash, storageHash})`
`14828423   14849723 (flat, cum)  2.50% of Total`
`26666581   26672121 (flat, cum)  4.49% of Total`
The added benefit of reduced allocations also surfaces in the benchmark:
```
Master:
BenchmarkSearchSlot-8   	 4042929	       341.6 ns/op	     160 B/op	       3 allocs/op
PR:
BenchmarkSearchSlot-8   	 6573976	       180.8 …
```
=> core/state/snapshot: use AddHash/ContainHash instead of Hasher interface

core/vm/jump_table.go
PR's title is pretty explanatory, the comment was probably referring to EIP-2930 instead of EIP-2929
=> core/vm: fix misleading comment

eth/catalyst/api.go, eth/catalyst/api_test.go, params/config.go, params/forks/forks.go
This PR introduces a few changes with respect to payload verification in fcu and new payload requests:
* First of all, it undoes the `verifyPayloadAttributes(..)` simplification I attempted in #27872. At the time I expected the pattern from `forkchoiceUpdatedV2` to continue where the previous version's payload attributes would be accepted by the method _if_ the timestamp allowed. It turns out this is only a special case in `forkchoiceUpdatedV2`. In `forkchoiceUpdatedV3` is _not_ possible to provide `PayloadAttributesV2`. Only `V3` is accepted. This sort of defeats the purpose of the shared method.
To see this in the spec, you may first view the parameters for [`forkchoiceUpdatedV2`](https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_forkchoiceupdatedv2) …
=> eth/catalyst: add timestamp checks to fcu and new payload and improve param checks

core/txpool/txpool.go, eth/catalyst/api.go, eth/catalyst/simulated_beacon.go
This PR fixes an issues in the new simulated backend. The root cause is the fact that the transaction pool has an internal reset operation that runs on a background thread.
When a new transaction is added to the pool via the RPC, the transaction is added to a non-executable queue and will be moved to its final location on a background thread. If the machine is overloaded (or simply due to timing issues), it can happen that the simulated backend will try to produce the next block, whilst the pool has not yet marked the newly added transaction executable. This will cause the block to not contain the transaction. This is an issue because we want determinism from the simulator: add a tx, mine a block. It should be in there.
The PR fixes it by adding a Sync function to the txpool, which waits …
=> core/txpool, eth/catalyst: fix racey simulator due to txpool background reset

beacon/engine/types.go, eth/catalyst/api.go, eth/catalyst/api_test.go, eth/catalyst/simulated_beacon.go, miner/payload_building.go
_this PR is built on top of #28230_
Technically, `GetPayloadVX` should only return payloads which match its version. `GetPayloadV2` is a special snowflake that supports v1 and v2 payloads. Originally I thought to either i) plumb the version through the entire building process so when the payload was retrieved in the API request, it would be possible to determine if the call was valid _or_ ii) to ascertain from the payload itself which version it would have been requested through.
@holiman had a much better idea, which is to prefix the payload id with the version number. This involved minimal plumbing and pretty straightforward integration in `GetPayloadVX`.
=> eth/catalyst: prefix payload id with version

ethclient/ethclient.go, ethclient/ethclient_test.go
Fix flaky test due to incomplete transaction indexing
```
--- FAIL: TestEthClient/StatusFunctions (0.00s)
ethclient_test.go:481: unexpected progress: &{0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0}
```
=> ethclient: fix flaky test

core/types/transaction.go, core/types/transaction_signing_test.go, core/types/tx_blob_test.go
Fix the `Transaction.WithSignature` method to handle when a signer implementation returns nil accidentally.
Return the `ErrInvalidSig` error if so.
The `Signer` has many custom implementations, some based on remote data or communication, and `nil` values were causing issues when using one of those custom signers.
Also add a comment, to clarify that the raw signature values can be nil/zero. Can they be nil? Or does `NewTx` enforce the copy, and thus the non-nilness? Probably worth a comment if that guarantee exists.
=> core/types: fix and test handling of faulty nil-returning signer

README.md
The hyperlink in the README file that directs to the Travis CI build was broken. This commit updates the link to point to the correct Travis CI build page for the Ethereum code repository.
=> README.md: fix travis badge

eth/catalyst/api.go
At some point, `ForkchoiceUpdatedV2` stopped working for `PayloadAttributesV1` while paris was active. This was causing a few failures in hive: https://hivetests2.ethdevops.io/suite.html?suiteid=1706266201-57f1c042be25eab3f1893cb5718fc756.json&suitename=engine-withdrawals
Additionally, I added a gate in `ForkchoiceUpdatedV1` to disallow `PayloadAttributesV3`.
Neither of these cases should really be encountered at this point, but I think it is good to correctly follow the spec while we have the code and especially if there are active hive tests failing.
=> eth/catalyst: allow payload attributes v1 in fcu v2

README.md, docs/postmortems/2021-08-22-split-postmortem.md
These changes aim to ensure that the links in the document are current, enhancing the quality of the documentation and the reader's experience.
=> fix:Update outdated links in 2021-08-22-split-postmortem.md document

core/blockchain.go
This pull request resets the txlookup cache if certain transactions are reorg'd out, preventing them from remaining reachable. It addresses failures in the hive tests.
=> core: reset tx lookup cache if necessary

eth/downloader/beaconsync.go, eth/downloader/downloader.go, eth/downloader/skeleton.go
This pull request fixes a corner case in skeleton header deletion.
The background is Geth uses a backward-sync mechanism to fetch and assemble the skeleton header chain locally (guided by consensus client) and then extend block chain by consuming the skeleton headers. The consumed skeleton headers will be deleted from database to avoid accumulating junks.
The assumption is always held that a complete skeleton header chain is linked with local blockchain, specifically `skeleton.tail.parent == blockchain.head`. However the originally deletion logic always sets the `blockchain.head` as the new tail and delete headers beforehand.
In this fix, the next header of filled block will be regarded as the new tail, to keep the guarantee skeleton chain is linked with blockchain, instead of overlapping …
=> eth/downloader: fix skeleton cleanup

core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go, core/txpool/blobpool/metrics.go
The database behind the blobpool is excessively simple, so much so, that a crash will result in old deleted items being resurrected. This is not a particularly thorny issue as the code will badly detect the duplicate nonce/tx as a nonce gap and drop everything after. Still, the logs reported will be out of whack quite a bit + a duplicate nonce should not drop non-duplicated items.
This PR explicitly handles the two possible new cases with resurrections: a transaction is fully duplicated or only an already used nonce is duplicated. In both scenarios, only the offending items will be dropped and the rest retained.
The PR also adds various metrics to track all the drop events (grouped by various causes) and the add events (grouped by rejection causes).
=> core/txpool/blobpool: post-crash cleanup and addition/removal metrics

core/txpool/subpool.go
When retrieving transactions for mining, we return lazy wrappers. The purpose is to delay loading blobs from disk until they are absolutely necessary and seem to really really really go into a next block.
The original wrapper however when "Resolved", pulled in the full transaction and stored it in the lazy wrapper. This seems like a good idea as it avoids loading the transaction a second time, but:
- We never ever want to load a transaction a second time. We load it when we want to insert into a block, and then we either push it into the block or discard it. We never need it again (until the next block when we remake the lazy list). Storing it is thus pointless.
- However, storing it means that our original light list starts to get heavy. And for every transaction that the miner resolves, …
=> core/txpool: don't inject lazy resolved transactions into the container

core/types/tx_blob.go
replace "sigining" to "signing"
=> core/types: fix typo

p2p/server_nat.go, p2p/server_nat_test.go
This pull request fixes the issue where the portMappingLoop function was prematurely terminated, causing the defer function to be called and trigger "Deleting port mapping" 2 minutes after the initial launch. The fix involves changing the return statement to a continue statement in order to continue the loop.
This issue has been initially reported at https://github.com/etclabscore/core-geth/issues/609 and fixed at https://github.com/etclabscore/core-geth/pull/611.
Background: this has been introduced with https://github.com/ethereum/go-ethereum/pull/26359.
=> p2p: fix accidental termination of portMappingLoop

internal/flags/flags.go
Seems the CLI package did some internal crap, which caused our default formatter for big.Int flags to stop working. I just copy pasted the default handling from the cli.Uint64 flag.
$ geth --help
master:
```
--miner.gasprice value              (default: 0)              ($GETH_MINER_GASPRICE)
Minimum gas price for mining a transaction
```
vs PR:
```
--miner.gasprice value              (default: 1000000000)              ($GETH_MINER_GASPRICE)
Minimum gas price for mining a transaction
```
=> internal/flags: fix --miner.gasprice default listing

core/txindexer.go, core/txindexer_test.go
This pull request tries to address issue #28907
From the ticket we can see the `txindexer.report` dominates the CPU usage. Inside of this function, only a single database read is involved. Therefore the first attempt to mitigate the situation is caching the `tail` data in memory instead of retrieving it from db.
**Note, with this change, the indexing progress reported will have a big delay as tail is only updated at the end**. It might have bad UX for reporting tx indexing progress, but should be fine.
=> core: cache transaction indexing tail in memory

accounts/abi/bind/util_test.go, eth/api_miner.go, ethclient/simulated/backend_test.go, ethclient/simulated/options.go, miner/miner.go, miner/ordering.go, miner/ordering_test.go, miner/worker.go
Geth originally enforced transaction gas prices and tips in the transaction pool. This seemed like an elegant way to avoid having to check the same thing in two different places. By default the pool (and hence miner) admitted 1 wei tip transactions, and when mining was started, that was increased to whatever the user set, or 1gwei by default.
Unfortunately, the merge kind of broke this mechanism. Since post-merge mining is not requested to be "turned on" in Geth, rather blocks are sometimes produced on demand via the beacon client, the mechanism that flipped the pool from non-mining-node mode to mining-node mode never got triggered. The effect is that all validating Geth nodes accept 1 wei tip transactions into the pool currently, and because the miner doens't do a follow-up enforcement, …
=> eth, miner: fix enforcing the minimum miner tip

cmd/era/main.go, cmd/geth/chaincmd.go, cmd/geth/main.go, cmd/utils/cmd.go, cmd/utils/history_test.go, core/blockchain_reader.go, go.mod, go.sum, internal/era/accumulator.go, internal/era/builder.go, internal/era/e2store/e2store.go, internal/era/e2store/e2store_test.go, internal/era/era.go, internal/era/era_test.go, internal/era/iterator.go
This PR is allows users to export their chain into an an archive format called Era1. It is formulated similarly to the Era[^1] format, which is optimized for reading and distribution CL data. The Era and Era1 format are stricter subsets of a simple [type-length-value](https://en.wikipedia.org/wiki/Type%E2%80%93length%E2%80%93value) scheme called e2store[^2], both developed by the Nimbus team.
The Era format was originally designed to distribute Beacon chain data, but it is clearly desirable to have the same functionality for the EL. A shareable and verifiable archive format is generally considered the first step towards implementing history pruning[^3].
For these reasons, a special flavor of the Era format was developed[^4]: Era1. It's goal is to service EL history *pre-merge*. The reason …
=> cmd,internal/era: implement `export-history` subcommand

core/genesis.go, params/config.go
@barnabasbusa was running into some issues when setting up a holesky shadow fork. When the default chain config was loaded from the already initialized chain, it would return the default which is `params.AllEthashProtocolChanges`.
This PR adds the case for Holesky genesis and derefs the actual timestamp values in the config error messages.
=> core,params: add holesky to default genesis func when config not available

cmd/devp2p/internal/ethtest/conn.go, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/transaction.go, eth/downloader/downloader_test.go, eth/downloader/skeleton_test.go, eth/handler_eth.go, eth/handler_eth_test.go, eth/protocols/eth/broadcast.go, eth/protocols/eth/handler.go, eth/protocols/eth/handler_test.go, eth/protocols/eth/handlers.go, eth/protocols/eth/handshake_test.go, eth/protocols/eth/peer.go, eth/protocols/eth/protocol.go, eth/sync_test.go
ETH67 does not have the necessary metadata for blob announcements. Our code is fine as is, the moment Cancun is enabled on a chain config Geth will stop advertising ETH67 support. That said, might as well nuke it out completely.
=> cmd/devp2p, eth: drop support for eth/67

core/forkid/forkid_test.go, params/config.go
This PR schedules the Cancun hardfork for mainnet.
Timestamp: `1710338135`
Fork id: `0x9f3d225`
Spec: TBD
=> params, core/forkid: add mainnet timestamp for Cancun

accounts/usbwallet/trezor/trezor.go
Hello, I've found outdated link to trezor docs, this PR fix the issue.
=> fix: update outdated link to trezor docs

internal/ethapi/transaction_args.go
Hello guys I am a [taiko](https://taiko.xyz/) employee, when I debug eip4844 tx found a bug about `blobhash not found` when calling `FillTransaction` for blob tx.
=> feat(api): Fix bug about doing estimateGas for blob contract call.

common/big.go, core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go, core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool2_test.go, core/txpool/legacypool/legacypool_test.go, core/txpool/legacypool/list.go, core/txpool/legacypool/list_test.go, core/txpool/subpool.go, core/txpool/txpool.go, eth/backend.go, eth/protocols/eth/handler_test.go, miner/miner_test.go, miner/worker_test.go
Related issue: #28577
This PR changes the use of `big.Int` to `uint256.Int` in the legacypool package. The changes are made primarily only on the internal functions of legacypool, without touching other dependencies and related interfaces.
=> core/txpool/legacypool: use uint256.Int instead of big.Int

internal/ethapi/api.go, signer/core/signed_data.go
This PR updates deprecated links to geth.ethereum.org. Makes the distinction between External API and personal namespace methods clearer.
=> internal/ethapi, signer/core: fix documentation-links

cmd/evm/staterunner.go, core/state/snapshot/snapshot.go, eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/internal/tracetest/flat_calltrace_test.go, eth/tracers/internal/tracetest/prestate_test.go, eth/tracers/tracers_test.go, tests/state_test.go, tests/state_test_util.go
This PR fixes two things, 
- A goroutine leak caused by snapshot generation, which, after being completed, wants to deliver the generator stats over a chanel. In some cases, we fail to read the channel, which causes thousands of threads getting blocked (example https://github.com/ethereum/go-ethereum/pull/28946#issuecomment-1935928557 ).
- ~A `t.Parallel`  early in the state test execution causes a _massive_ parallelization: basically _all_ statetest files are read, and initiated. Once all state-tests are initiated, they are all halted, or, put into a wait, so that testing can proceed at the specified paralellism. I suspect that the early forking of testcases does not improve the testing-speed on appveyor/travis, so I removed it here. Will check which run is fastest, with or without it.~
=> tests: fix goroutine leak related to state snapshot generation

ethclient/ethclient.go, interfaces.go
Add blob transaction fields in the eth client.
=> ethereum, ethclient: add blob transaction fields in CallMsg

core/txpool/blobpool/blobpool.go
use underscores so they are not confused for subtraction
=> core/txpool/blobpool: rename variables in comments

cmd/devp2p/internal/ethtest/suite.go
Finding a small inconsistency when playing with blob transactions (using this code snippet as a reference). Changing the module from 2 to 3 can make it consistent with the comments, and by the way, it can consume all blobs when calling makeBlobTxs in the tests (first tx with 2 blobs, second with 1 blob):
```
var (
t1 = s.makeBlobTxs(2, 3, 0x1)
t2 = s.makeBlobTxs(2, 3, 0x2)
)
```
Previously, the first tx only had 1 blob, and the second 1, strictly less than 3 blobs bandwidth provided.
=> cmd/devp2p: fix modulo in makeBlobTxs

beacon/engine/types.go, eth/catalyst/api.go, eth/catalyst/api_test.go
This implements the new method `engine_getClientVersionV1`. Still waiting it to be merged here: https://github.com/ethereum/execution-apis/pull/517
=> eth/catalyst,beacon/engine: implement GetClientVersionV1

build/checksums.txt, tests/block_test.go, tests/init_test.go, tests/state_test.go
This PR does two things:
- it brings up the execution spec tests to latest release, [2.1.0](https://github.com/ethereum/execution-spec-tests/releases/tag/v2.1.0)
- The execution spec tests previously were only blockchain tests, but now also contain statetests.
- These statetests are now also executed, in `TestExecutionSpecState`
- it moves legacy state tests into `TestLegacyState`
With this PR, about `25%` of `TestState` is instead shoved off into `TestLegacyState`:
```
[user@work go-ethereum]$ go test ./tests -run TestLegacyState
ok      github.com/ethereum/go-ethereum/tests   58.864s
[user@work go-ethereum]$ go test ./tests -run TestState
ok      github.com/ethereum/go-ethereum/tests   180.807s
```
This is good, because the test timeout is per individual test, afaik, so cutting off 30% …
=> tests: update execution spec tests + split statetest exec

cmd/evm/transition-test.sh
json tag keep consistency with  struct's field
=> cmd/evm: fix typo in test script

core/txpool/blobpool/blobpool.go, core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, core/txpool/txpool.go, eth/api_backend.go, eth/catalyst/simulated_beacon.go, eth/handler.go, eth/handler_test.go, eth/sync.go, miner/worker.go
This issue was found by @MariusVanDerWijden!
This PR fixes a number of performance bugs in the transaction pool pending retrieval:
- In the blob pool, we have done no pre-filtering whatsoever when the miner requested the transactions, rather just shipped everything over. The idea was that all the necessary information is already there for the miner to pick what it needs and throw everything else away. Unfortunately we haven't forwarded the blobFee, so the miner couldn't check if the blob transaction can actually be included without loading the entire thing from disk. This made the miner extremely suboptimal and also caused the memory blowup (fixed on master, but the root cause was unknown). This PR solves it by adding a pre-filtering step into the blob pool. Whilst we could have fixed it …
=> core/txpool, eth, miner: pre-filter dynamic fees during pending tx retrieval

ethstats/ethstats.go
This pull request fixes a flaw in ethstats. 
The panic happens when the local blockchain is reorging which causes the original head block not reachable(number->hash canonical mapping is deleted).  In order to prevent the panic, the block nilness will be checked in ethstats. 
```
INFO [02-19|01:42:43.476] Chain reorg detected                     number=19,258,596 hash=9d98f1..e6fc8a drop=1 dropfrom=9e5d7e..e9aea2 add=1 addfrom=5c3ee3..9b5f97
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x100bdfa]
goroutine 4464 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Header(...)
github.com/ethereum/go-ethereum/core/types/block.go:356
github.com/ethereum/go-ethereum/ethstats.(*Service).assembleBlock …
```
=> ethstats: prevent panic if head block is not available

core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go, core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, eth/handler_test.go, miner/ordering.go, miner/ordering_test.go, miner/worker.go
This PR adds a benchmark to the blobpool to measure the execution speed of pending transaction retrieval. Note, the benchmark uses an in-memory bill of 10GB and needs to pre-generate 80K private keys. It takes 5 minutes.
Based on the benchmark, the PR also contains some fixes to the pending retrieval:
- Preallocations of the pending map and individual slices shaved off 10-15%
- Replacing the time.Now loop invocation with an outer one resulted in an additional 10-15%
- Avoiding the uint256 to bigInt conversion shaved off an additional 50%
Due to the last one, the PR changes this all over the place. This does mean that the legacy pool starts to pay the price in exchange. That said, the legacy pool is capped to about 4K txs, whereas the blobpool currently 80K, so it's worth it. Also, ideally …
=> core/txpool, miner: speed up blob pool pending retrievals

core/vm/operations_acl.go, internal/ethapi/api_test.go, params/config.go
This PR fixes an overflow which can could happen if inconsistent blockchain rules were configured. Additionally, it tries to prevent such inconsistencies from occurring by making sure that merge cannot be enabled unless previous fork(s) are also enabled. 
Without this PR, it is possible to set the overrides on an `eth_call` over RPC and trigger a method-handler crash (not a full node crash). 
Hat-tip to @pleasew8t for reporting this via the bounty via a very well-written submission.
=> core/vm, params: ensure order of forks, prevent overflow

core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go, core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, core/txpool/txpool.go, eth/api_backend.go, eth/catalyst/simulated_beacon.go, eth/handler.go, eth/handler_test.go, eth/sync.go, miner/ordering.go, miner/worker.go
Whilst retrieving a single batch of transactions from the pools is elegant, the fact that inclusion is extremely asymmetric makes things less than ideal. This PR is a proposal to allow retrieving plain and blob transactions in separate batches so that the miner can discard the entire set when the blobs-space is full.
=> core/txpool, eth, miner: retrieve plain and blob txs separately

core/state_transition.go, core/txpool/blobpool/blobpool.go, core/txpool/legacypool/legacypool.go
Found some typos when reading the blob pool implementation, some are already fixed in: https://github.com/ethereum/go-ethereum/pull/29031, leaving some nitpicks.
=> core/txpool: fix typo

internal/ethapi/transaction_args.go, internal/ethapi/transaction_args_test.go
This PR comes with 2 fixes:
- We shouldn't fill blob proofs/commitments before cancun
- setDefaults has shortcuts to avoid doing extra work if gasPrice or EIP-1559 fee fields are already provided by the user. This shortcut caused us not to fill the maxBlobFee as well.
I have a refactor of setDefaults that I need for #27720 that I'd like to port to master which includes these fixes. Will post that as a separate PR to have fix and refactoring separate.
=> internal/ethapi: fix defaults for blob fields

eth/tracers/api.go, internal/ethapi/api.go
Previously, even if `baseFee` was overridden via `BlockOverrides` parameters, the sender of the call would be charged based on the original block's `baseFee`. This leads to incorrectly calculated `gasPrice` in `TransactionArgs#ToMessage` function for calls that provided `gasFeeCap`/`gasTipCap` parameters.
Solution is to use the `baseFee` from block context, which includes overridden values.
=> eth/tracers,internal/ethapi: use correct baseFee when BlockOverrides is provided in call/traceCall

internal/ethapi/api.go, internal/ethapi/transaction_args.go
This PR enhances `eth_createAccessList` RPC call to support scenarios where the node is launched with an unlimited gas cap (`--rpc.gascap 0`). The `eth_createAccessList` RPC call returns failure if the `ethereum.CallMsg` doesn't explicitly set a gas limit.
An error message example (the unexpected `err: intrinsic gas too low: have 0`):
```
failed to apply transaction: 0x7073334f34b8882d79023837f726926522cf796da1ea4354bbb132497feb0331 err: intrinsic gas too low: have 0, want 22624
```
=> internal/ethapi: support unlimited rpc gas cap in eth_createAccessList

eth/catalyst/api.go
Fix some error messages:
1. keep in the same format: `params.BlobGasUsed` vs `blobGasUsed`;
2. in NewPayloadV2 we check `IsCancun`, but the error message is `post-shangshi`, I think it should be `post-cancun`;
3. ~I think beaconRoot should be the parentBlock's beacon root, so the error message should `parentBlockBeaconRoot` more accurate~
=> eth/catalyst: fix wrong error message of payloadV2 after cancun

core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go, core/txpool/validation.go
I noticed you can send geth a blob transaction with a 0 BlobFeeCap and it will be accepted but then never get included in a block.  The spec states there is a min blob fee of 1 wei, so seems better to reject these during validation.
=> make blobpool reject blob txs with blob fee cap below the minimum

log/logger_test.go, p2p/server.go, p2p/transport.go, rpc/types.go
Parameterless errors should be using errors.New instead of fmt.Errorf
=> p2p,log,rpc: use errors.New to replace fmt.Errorf with no parameters

cmd/clef/README.md
Add space after links in cmd/clef/README.md so they are clickable in vscode.
Before:
| QtSigner| https://github.com/holiman/qtsigner/| Python3/QT-based| :+1:| :+1:| :+1:| :+1:| :+1:| :x: |  :+1: (partially)|
| GtkSigner| https://github.com/holiman/gtksigner| Python3/GTK-based| :+1:| :x:| :x:| :+1:| :+1:| :x: |  :x: |
| Frame | https://github.com/floating/frame/commits/go-signer| Electron-based| :x:| :x:| :x:| :x:| ?| :x: |  :x: |
| Clef UI| https://github.com/ethereum/clef-ui| Golang/QT-based| :+1:| :+1:| :x:| :+1:| :+1:| :x: |  :+1: (approve tx only)|
After:
| QtSigner| https://github.com/holiman/qtsigner/ | Python3/QT-based| :+1:| :+1:| :+1:| :+1:| :+1:| :x: |  :+1: (partially)|
| GtkSigner| https://github.com/holiman/gtksigner | Python3/GTK-based| :+1:| :x:| :x:| :+1:| :+1:| :x: |  :x: …
=> Fix formating in cmd/clef/README.md

core/txpool/legacypool/journal.go
A private node that I run locally has relatively few transactions. I noticed the following logs (every hour) and found that the rotate process can be skipped if there are no local transactions.
```bash
INFO [02-26|12:39:36.200] Regenerated local transaction journal    transactions=0 accounts=0
INFO [02-26|13:39:36.043] Regenerated local transaction journal    transactions=0 accounts=0
INFO [02-26|14:39:35.885] Regenerated local transaction journal    transactions=0 accounts=0
```
=> core/txpool: no need to run rotate if no local txs

eth/tracers/native/call.go
Fixed missing logs for `callTracer` calls having `withLog == true && onlyTopCall == true`:
```bash
curl --location 'http://0.0.0.0:8545' \
--header 'Content-Type: application/json' \
--data '{
"method": "debug_traceTransaction",
"params": [
"0x506d0ce623a33ef868780a99f051b5eba5c82fc5dd2826ee1bb0b666131a6fb8",
{
"tracer": "callTracer",
"tracerConfig": {
"withLog": true,
"onlyTopCall": true
}
}
],
"id": 1234
}'
```
So the expected response is:
```json
{
"id": 1234,
"result": {
"from": "0x82211934c340b29561381392348d48413e15adc8",
"gas": "0x742e",
"gasUsed": "0x72d1",
"to": "0x83e32b17b3a5fee7ea3294bca3840f54818edf92",
"input": "0xfc0a63300000000000000000000000009f333fc2a4b329addb8e0b5ac34653b53c79c264",
"logs": [
{
"address": …
```
=> eth/tracers/call: Fix call_tracer withLog == true && onlyTopCall == true

core/txpool/errors.go, core/txpool/txpool.go
We see this error when switching between blob and non-blob txs and must handle it specially (e.g. by submitting a cancel transaction to clear the old tx type). Thought this tweak might "elevate" its definition to better codify the error text we match against.
=> declare the 'already reserved' error in txpool's errors.go

core/vm/instructions.go
I am still reading the code in core/vm.
relate PR: https://github.com/ethereum/go-ethereum/pull/29022
=> core: using math.MaxUint64 instead of 0xffffffffffffffff

core/rawdb/schema.go, triedb/pathdb/nodebuffer.go
=> core, triedb/pathdb: calculate the size for batch pre-allocation

eth/catalyst/api.go
This fixes 5 of the `engine-cancun` tests on hive that are failing. After https://github.com/ethereum/execution-apis/pull/498 we had to modify the behavior to return `InvalidPayloadAttributes` instead of `InvalidParams`.
The remaining errors are due to i) the other `TODO` in fcuv3, which is to split up the `forkchoiceUpdated(..)` function into a) processing the fcu and b) validating / kicking off block production and ii) some race-y behavior with blobs / blob pool.
=> eth/catalyst: return invalid payload attributes instead of invalid parms for bad fcu payload

cmd/geth/chaincmd.go, cmd/geth/snapshot.go
This PR fixes the bug of `./geth dump` and `./geth snapshot dump` due to the early closing of the database.
`parseDumpConfig()` creates the database `db := utils.MakeChainDatabase(ctx, stack, true)` and then defers closing database `db.Close()`. When returning the db object, the database would be closed, making it impossible for other functions to read the database.
This PR would move the responsibility of opening and closing the database outside of `parseDumpConfig()`. Instead functions calling `parseDumpConfig()` should parse the db as a function argument.
=> cmd/geth: parseDumpConfig should not return closed db

cmd/era/main.go, cmd/geth/chaincmd.go, cmd/utils/cmd.go, core/txpool/validation.go, internal/era/accumulator.go, internal/era/builder.go, internal/era/e2store/e2store.go, internal/era/e2store/e2store_test.go, internal/era/era.go, internal/era/iterator.go, miner/worker.go, node/rpcstack.go, p2p/discover/v4_udp.go, p2p/discover/v5_udp.go, p2p/discover/v5wire/encoding.go, p2p/dnsdisc/client.go, p2p/dnsdisc/tree.go, p2p/enode/idscheme.go, p2p/nat/natpmp.go, p2p/simulations/adapters/exec.go, signer/core/apitypes/types.go, trie/trie_test.go, triedb/pathdb/history.go
Replace all fmt.Errorf() which has no param with errors.New().
=> era,utils,p2p,triedb: replace fmt.Errorf() with errors.New() if no param required

cmd/utils/flags.go, core/rawdb/accessors_trie.go, graphql/graphql_test.go, triedb/pathdb/database.go
This PR flips the default state-scheme from hash to path, though it also adds a fallback for archive mode which force sets hash mode.
=> cmd/utils, core/rawdb, triedb/pathdb: flip hash to path scheme

eth/backend.go, eth/handler.go
Geth currently propagates new transactions by sending them in full to `sqrt(peers)` and announcing their hashes to the rest of the peers. The exceptions are peers that already are known to have the transactions (neither is done for them) and large/blob transactions (which are always announced). For this PR's scope, we don't care about the special cases, only the normal new transactions.
The rationale behind the broadcast/announce split is that broadcasting to everyone in full would be very wasteful, as everyone would in essence receive the same transactions from all their peers. Announcing it to everyone on the other hand would minimize traffic, but would maximise distribution latency as everyone would need to explicitly ask for an announced transaction. Depending on whatever timeout …
=> eth: make transaction propagation paths in the network deterministic

p2p/server.go
```
c := &conn{fd: fd, flags: flags, cont: make(chan error)}
err := srv.setupConn(c, flags, dialDest)
```
function `setupConn` has not used param `flags`. And the first struct param `c` contains `flags`, we can use `c.flags` in setupConn if needed.
=> p2p: delete duplicate flags

accounts/abi/type.go
the `err` has be checked on line 173.
=> accounts/abi: delete duplicate error check

cmd/devp2p/internal/ethtest/snap.go, core/types/block_test.go
tests: use EmptyUncleHash, EmptyCodeHash instead of raw value
=> all: use EmptyUncleHash, EmptyCodeHash instead of raw value

cmd/devp2p/main.go
It got broken in some update of the cli library, and thus bootnodes weren't being configured automatically for some of the discovery commands.
Fixes #28897
=> cmd/devp2p: fix commandHasFlag

core/blockchain_repair_test.go, core/blockchain_sethead_test.go, core/rawdb/chain_freezer.go, core/rawdb/database.go
This pull request uses the finalized block tag as the indicator for chain freezing.
Originally, the latest 90K blocks will be retained in the key-value store by default, which are regarded as "non-finalized" in the context of Proof-of-work. However, in Proof-of-stake, we do have the concrete finalized block tag from the consensus client. Therefore, it makes more sense to directly rely on the `Finalized` for chain freezing.
=> core: use finalized block as the chain freeze indicator

.mailmap
This was an old work email of mine that hasn't been valid since 2015.  git history also confirms it has never been associated with any commits to this repo, no idea how it ended up in this file
=> .mailmap: remove invalid email address

core/state_transition.go
Current code is like below:
```golang
st.gasRemaining += st.msg.GasLimit
st.initialGas = st.msg.GasLimit
```
It makes readers think `gasRemaining` is accumulated across transactions in a block while `initialGas` is only for a single transaction.
But in fact both `gasRemaining` and `initialGas` are accounting for a single transaction **only**.
(each transaction will have its own `StateTransition` object.)
And this codestyle is copied downstream to [op](https://github.com/ethereum-optimism/op-geth/blob/optimism/core/state_transition.go#L292-L293).
I think it helps understanding to make the initializing style the same for `gasRemaining` and `initialGas`.
=> core: initialize `gasRemaining` with `=` instead of `+=`

core/state/metrics.go, core/state/statedb.go, core/state/statedb_test.go, trie/triestate/state.go, triedb/pathdb/database.go, triedb/pathdb/database_test.go, triedb/pathdb/disklayer.go, triedb/pathdb/history.go, triedb/pathdb/history_test.go, triedb/pathdb/journal.go
As SELF-DESTRUCT opcode is disabled in the cancun fork(unless the account is created within the same transaction, nothing to delete in this case). The account will only be deleted in the following cases:
- The account is created within the same transaction. In this case the original storage was empty.
- The account is empty(zero nonce, zero balance, zero code) and is touched within the transaction. Fortunately this kind of accounts are not-existent on ethereum-mainnet.
All in all, after cancun, we are pretty sure there is no large contract deletion and we don't need this mechanism for oom protection.
=> core/state, trie/triedb/pathdb: remove storage incomplete flag

accounts/usbwallet/hub.go, accounts/usbwallet/wallet.go, go.mod, go.sum
Replaces https://github.com/ethereum/go-ethereum/pull/28901
=> accounts/usbwallet: use updated hid (only) library

internal/jsre/deps/web3.js
In the geth's console, the output of `blob` related fields not formated:
=> internal/jsre: format blob fields from hexdecimal to int 

rlp/unsafe.go
SliceHeader is deprecated  in [go](https://github.com/golang/go/blob/e41fabd6886ec16db6026b30486e20732f89960a/src/reflect/value.go#L2842-L2847).
=> rlp: using unsafe.Slice instead of SliceHeader

core/state_transition.go
This PR makes the code style of [`buyGas`](https://github.com/ethereum/go-ethereum/blob/93c541ad563124e81d125c7ebe78938175229b2e/core/state_transition.go#L235) function more consistent.
=> core: remove useless assignments

node/node_test.go
fixes
```
--- FAIL: TestRegisterHandler_Unsuccessful (0.00s)
node_test.go:423: could not create new node: mkdir /home/matematik/.ethereum: file exists
FAIL
FAIL    github.com/ethereum/go-ethereum/node    2.549s
```
=> node: fix test if directory already exists

accounts/usbwallet/hub.go, accounts/usbwallet/wallet.go, go.mod, go.sum
This PR reverts #28945, switching back to use karalabe/usb. 
The reason is that it currently does not compile on docker (alpine). See https://github.com/karalabe/hid/pull/51 for more information. 
So, let's revert it, until https://github.com/karalabe/hid/pull/51 is resolved, so that it builds on both appveyor _and_ alpine (which currently seems mutually exclusive).
=> accounts/usbwallet: revert #28945

rpc/types_test.go
Hello everyone,
Would like to add missing test cases for `rpc/types.go` related to `finalized` and `safe` `BlockNumber`.
=> rpc: add more test cases for arg types

eth/tracers/internal/tracetest/prestate_test.go, eth/tracers/internal/tracetest/testdata/prestate_tracer/blob_tx.json, eth/tracers/native/prestate.go
Currently, the prestateTracer does not include the blob gas used for the sender's address. We should make sure to add it back and consider it in the calculations.
=> eth/tracers: prestate tracer add blob fee

accounts/accounts.go
This conversion is unnecessary, the bottom layer will do it, and it is omitted to save overhead.
For more information, please refer to go’s official modifications https://go-review.googlesource.com/c/go/+/520918/1/src/os/exec/lp_windows_test.go#b48
=> accounts: remove redundant string conversion

internal/testlog/testlog.go, log/logger.go
It is sometimes useful to access the underlying handler of a logger. The `slog.Logger` exposes its handler, so this PR simply adds the `Handler` getter to geth's `log.Logger` interface and forwards it in the `logger` implementations to the inner logger.
=> log: add Handler getter to Logger interface

p2p/simulations/adapters/inproc_test.go
Correct the assertion in the test.
=> p2p/simulations/adapters: fix error messages in TestTCPPipeBidirections

core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go
This matches behavior with the legacypool which will return ErrAlreadyKnown for duplicate transactions instead of ErrReplaceUnderpriced. The primary motivation for this is to help blob transaction submitters by providing more information in the error and standardizing the error returned in this case with non-blob transactions, though this also fixes go-ethereum's internal tx fetcher duplicate count metric.
=> core/txpool/blobpool: return ErrAlreadyKnown for duplicate txs

cmd/devp2p/internal/ethtest/chain.go, cmd/devp2p/internal/ethtest/engine.go, cmd/devp2p/internal/ethtest/suite_test.go, cmd/era/main.go, cmd/evm/internal/t8ntool/transition.go, cmd/utils/cmd.go, cmd/utils/history_test.go, core/blockchain_repair_test.go, core/blockchain_snapshot_test.go, core/rawdb/freezer_test.go
// Package filepath implements utility routines for manipulating filename paths
// in a way compatible with the target operating system-defined file paths.
//
// The filepath package uses either forward slashes or backslashes,
// depending on the operating system. To process paths such as URLs
// that always use forward slashes regardless of the operating
// system, see the path package.
// Package path implements utility routines for manipulating slash-separated
// paths.
//
// The path package should only be used for paths separated by forward
// slashes, such as the paths in URLs. This package does not deal with
// Windows paths with drive letters or backslashes; to manipulate
// operating system paths, use the path/filepath package.
Filepath is used to process file paths, path is used …
=> cmd: use package filepath over path for file system operations

common/math/big.go
Since the Exp function can not be removed https://github.com/ethereum/go-ethereum/pull/29206, let's keep the code consistent with the comment.
=> common/math: copy result in Exp

p2p/dial.go
Recreating PR #29203 because I can't push to it.
=> p2p: fix race in dialScheduler

eth/tracers/api.go
=> eth/tracers: fix concurrency issue for JS-tracing a block

cmd/devp2p/internal/ethtest/suite.go, core/txpool/blobpool/blobpool_test.go, core/txpool/validation.go, core/types/tx_blob_test.go, crypto/kzg4844/kzg4844.go, crypto/kzg4844/kzg4844_ckzg_cgo.go, crypto/kzg4844/kzg4844_ckzg_nocgo.go, crypto/kzg4844/kzg4844_gokzg.go, crypto/kzg4844/kzg4844_test.go, go.mod, go.sum, internal/ethapi/api_test.go, internal/ethapi/transaction_args.go
This PR makes use of the following underlying changes in order to avoid passing large things on the heap:
- c-kzg: https://github.com/ethereum/c-kzg-4844/pull/393 and
- go-kzg: https://github.com/crate-crypto/go-kzg-4844/pull/63
The huge allocs that showed during benchmarks were visible in a memprofile, as part of the setup, but not actually visible in the go bench output. But yeah, this thing is gone in this PR: 
```
155            .     6.82GB                   if err := kzg4844.VerifyBlobProof(sidecar.Blobs[i], sidecar.Commitments[i], sidecar.Proofs[i]); err != nil { 
```
=> crypto/kz4844: pass blobs by ref

core/blockchain.go
This pull request improves the chain rewinding mechanism a bit:
- use a more efficient approach for finding an available state in path scheme
- set a rewinding limit in hash scheme for preventing endless rewinding if the snapshot is above the head, fixed #29156
=> core: improve chain rewinding mechanism

appveyor.yml, tests/block_test.go, tests/state_test.go
…when flag `-short` is used
Also enable -short flag on all appveyor builds (previously was only appveyor/windows, now also ubuntu)
=> tests, appveyor: only execute one in four permutations on CI

eth/catalyst/api.go
Seems `delayPayloadImport` always returns `nil`, so no need to return an error to simplify it.
=> eth/catalyst: delayPayloadImport no need return error

cmd/devp2p/enrcmd.go
Fixed #29252
Command:
```
devp2p enrdump "enr:-Ku4QImhMc1z8yCiNJ1TyUxdcfNucje3BGwEHzodEZUan8PherEo4sF7pPHPSIB1NNuSg5fZy7qFsjmUKs2ea1Whi0EBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQOVphkDqal4QzPMksc5wnpuC3gvSC8AfbFOnZY_On34wIN1ZHCCIyg"
```
Output:
```
Node ID: 191bbf49632da5393590a33d54421e79e8e5c96ade72f0ba69e1803095de6b04
URLv4:   enode://95a61903a9a9784333cc92c739c27a6e0b782f482f007db14e9d963f3a7df8c01ad6a387e8021f13e684e576ca9e5d8759b3116df521b280a887a0bdc72e457f@18.223.219.100:0?discport=9000
Record has sequence number 1 and 6 key/value pairs.
"attnets"   0000000000000000
"eth2"      f5a5fd4200000000ffffffffffffffff
"id"        "v4"
"ip"        18.223.219.100
"secp256k1" 0395a61903a9a9784333cc92c739c27a6e0b782f482f007db14e9d963f3a7df8c0 …
```
=> cmd/devp2p: fix decode raw RLP value

core/chain_makers_test.go, core/state_processor.go, eth/catalyst/api_test.go, params/protocol_params.go
in https://eips.ethereum.org/EIPS/eip-4788 we use `BEACON_ROOTS_ADDRESS`, this should be better to use the same variable name to avoid confusion, so people will know if this is a contract address, not a contract storage key slot address
=> params: use the same variable name as EIP-4788

common/types.go, eth/catalyst/api.go
This PR is an alternative to https://github.com/ethereum/go-ethereum/pull/28942 
When we receive a bad NewPayload, we currently emit a _lot_ of data to the logging facilities. This PR makes it so we print less data. 
We might want to consider either storing the bad updates to db, or dump them to disk, but emitting it all on logs is not The Way, IMO. 
Example with this PR:
```
WARN [03-14|09:02:12.961] Invalid NewPayload params                params.Number=19,431,844 params.ParentHash=ba6b8c..bbca43 params.BlockHash=f87b00..c7af1a params.StateRoot=b6c4a2..9add76 params.FeeRecipient=0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990 params.LogsBloom="0x00eb1f...5a7d09 (256B)" params.Random=c97a4c..570c2f params.GasLimit=30,000,000 params.GasUsed=11,262,708 params.Timestamp=1,710,402,263 …
```
=> eth/catalyst: prettier output on bad new payloads

accounts/abi/bind/base.go
I'm guessing it's for historical reasons, but for now, it shouldn't be required
=> accounts/abi/bind: remove unused err set and check

go.mod, go.sum
Replaces https://github.com/ethereum/go-ethereum/pull/29253
Not important, but code-hygiene means we should avoid deps with known vulnerabilities (even if we're not affected)
=> go.mod: update protobuf

eth/protocols/snap/sync_test.go, internal/testrand/rand.go, trie/stacktrie_test.go, triedb/pathdb/database.go, triedb/pathdb/database_test.go, triedb/pathdb/difflayer_test.go, triedb/pathdb/history_test.go, triedb/pathdb/testutils.go
This pull request improves the existing unit tests in triedb package. Highlight the changes as follow:
- define `internal/testrand` package for generating random bytes, address, hash for testing purpose. The package can be used/shared in other places.
- change pathdb's maximum difflayer allowance to 4 to fasten unit tests
- fix a clean cache bug in test
---
Expand the third fix a bit. 
In PathDB, there is a clean cache for maintaining trie node caches of persistent state. The key of each cache item should be unique to prevent accidental content modification. For actual usage, the item key is derived by following this rule:
```
// cacheKey constructs the unique key of clean cache.
func cacheKey(owner common.Hash, path []byte) []byte {
if owner == (common.Hash{}) {
return path
}
return …
```
=> triedb/pathdb: improve tests

log/format.go
According to the comment, the tmp variable can be replaced with bytes.Buffer.AvailableBuffer() now since go version 1.21 is required to build geth.
=> log: replace tmp with bytes.Buffer.AvailableBuffer

core/asm/asm.go
https://github.com/ethereum/go-ethereum/blob/4c1b57856f0f5ebccb6edb83ab755ab114500078/core/vm/opcodes.go#L27-L29
when op = PUSH0
uint64(it.op) - uint64(vm.PUSH1) = uint64(-1) 
uint64(it.op) - uint64(vm.PUSH1)  + 1 == 0
Although it's not a problem, it's best to put add first
=> core/asm: minor code-clarification

metrics/json.go, metrics/registry.go, metrics/timer.go
Walkthrough go-ethereum code, tweak a bit timer's metric comment
=> metrics: fix docstrings

cmd/evm/staterunner.go
I mismatched the flags a bit in #29290. This PR fixes it
=> cmd/evm: fix flag-mismatch from #29290

core/blockchain.go
Geth has the mechanism to repair the chain if the associated state of head block is missing. The whole repair procedure can be divided into two steps:
(1) rewind the head block tag until the associated state is available in database
(2) truncate the extra chain segment, including headers, blocks, receipts, etc., if the new chain head is below the freezer head.
In step (2), deletion is sufficient as the head block is already considered stateful. Therefore, UpdateFn doesn't need to be invoked.
=> core: skip the check the statefulness of head block in repair

core/txpool/blobpool/priority.go
`log1.125(x) = log(x) / log(1.125) = log2(x) / log2(1.125)
`
In golang, math.Log is faster than math.Log2 about 35%, because math.log2 calls math.Log internally https://github.com/golang/go/blob/fba54f6345449586518039043ab38df337c25146/src/math/log10.go#L36
My benchmark code:
```
package main
import (
"testing"
"math"
"github.com/holiman/uint256"
)
var fee, _ = uint256.FromDecimal("12345678910")
var log2_1_125 = math.Log2(1.125)
var log1_125 = math.Log(1.125)
func BenchmarkLog2(b *testing.B) {
var result float64
for i := 0; i < b.N; i++ {
result = math.Log2(fee.Float64()) / log2_1_125
}
_ = result // Prevent compiler optimization
}
func BenchmarkLog(b *testing.B) {
var result float64
for i := 0; i < b.N; i++ {
result = math.Log(fee.Float64()) / log1_125
}
_ = result // Prevent compiler …
```
=> core/txpool/blobpool: calculate log1.125 faster

consensus/beacon/consensus.go, consensus/clique/clique.go, consensus/consensus.go, consensus/ethash/consensus.go, core/chain_makers.go, core/state_processor.go, core/types/block.go, miner/worker.go
This PR modifies the consensus interface to wrap the body fields.
Impact on block processing should be minimal (only one more alloc), but it makes changes to the block body way easier.
Inclusion Lists adds another field to the block body, so we need to modify it probably soon.
I think it just makes everything a bit cleaner
=> core: refactor consensus interface

eth/protocols/snap/sync_test.go, internal/testlog/testlog.go
This PR fixes two races from `go test --race ./...` : 
```
Write at 0x000001f2af90 by goroutine 39:
github.com/ethereum/go-ethereum/eth/protocols/snap.testSyncAccountPerformance.func1()
/home/user/go/src/github.com/ethereum/go-ethereum/eth/protocols/snap/sync_test.go:1885 +0x35
github.com/ethereum/go-ethereum/eth/protocols/snap.testSyncAccountPerformance.deferwrap1()
/home/user/go/src/github.com/ethereum/go-ethereum/eth/protocols/snap/sync_test.go:1885 +0x17
runtime.deferreturn()
/usr/local/go/src/runtime/panic.go:602 +0x5d
github.com/ethereum/go-ethereum/eth/protocols/snap.TestSyncAccountPerformance()
/home/user/go/src/github.com/ethereum/go-ethereum/eth/protocols/snap/sync_test.go:1878 +0x3c
testing.tRunner() …
```
=> eth/protocols/snap, internal/testlog: fix dataraces

accounts/keystore/keystore.go, core/vm/analysis_test.go, crypto/crypto.go, crypto/secp256k1/scalar_mult_cgo.go, eth/protocols/eth/peer.go, internal/era/era.go, metrics/sample_test.go, p2p/discover/common.go, p2p/discover/v5wire/crypto.go, rlp/decode.go
Embrace some of the stuff in `go 1.21`: https://go.dev/doc/go1.21
=> all: use min/max/clear from go1.21

triedb/hashdb/database.go
Hi. Setting `db.cleans` to nil on Close() can cause concurrent access (data race) with other functions accessing `db`.
This is not likely an issue, but also setting `db.cleans` to nil does not achieve much since the cache is reset, so it seems easier to let it be and let the cache be collected along with the owner of `db`.
=> triedb/hashdb: Avoid setting db.cleans on Close

cmd/geth/dbcmd.go, triedb/history.go, triedb/pathdb/database.go, triedb/pathdb/history_inspect.go
This pull request introduces a database tool for inspecting the state history. It can be used for either account history or storage slot history, within a specific block range.
The state output format can be chosen either with 
- the "rlp-encoded" values (those inserted into the merkle trie)
- the "rlp-decoded" value (the raw state value)
The latter one needs `--raw` flag.
---
Example usage:
`geth db inspect-history -start 4972612 -end 4974412 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 0x321690423bfa8088917640d62a3b42bb0acc95376d9366929f697905e89aead8`
```
Storage history:
address: 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
slot: 0x321690423bfa8088917640d62a3b42bb0acc95376d9366929f697905e89aead8
blockrange: [#4972612-#4974412]
#4972612 - #4972815: 88180a84df00995800
#4972815 - #4973208: …
```
=> cmd, triedb: implement history inspection

eth/downloader/queue_test.go, internal/debug/api.go, internal/debug/flags.go, internal/testlog/testlog.go, log/format.go, log/handler.go, log/handler_glog.go, log/logger.go, log/logger_test.go, log/root.go, p2p/simulations/adapters/exec.go, p2p/simulations/adapters/types.go, p2p/simulations/http_test.go, signer/core/auditlog.go, signer/storage/aes_gcm_storage_test.go
We're on go 1.21+ now, can use the "real" `slog`
=> log: use native log/slog instead of golang/exp

eth/backend.go, ethclient/simulated/backend.go
This PR makes the simulated backend keep track of the underlying Node (instead of the eth.Backend) and closes it when Close() is called. It also adds to the eth.New() function godoc to clarify the returned object's lifecycle gets managed by the Node, since I found this a bit surprising.
Context: Lingering resources were causing a bit of bloat during OP-stack end to end testing, some of which seemed to come from the simulated backends used throughout.
=> ethclient/simulated: clean up Node resources when simulated backend is closed

beacon/light/api/light_api.go
The `StartHeadListener` method will only be called once. So it can't just make one attempt to connect to the eventsource endpoint, it has to keep trying. Note that once the stream is established, the eventsource implementation itself will keep retrying.
=> beacon/light/api: improve handling of event stream setup failures

beacon/blsync/config.go
This PR fixes blsync command line parameter processing in case of a custom chain config.
=> beacon/blsync: fixed blsync command line params

internal/ethapi/api.go
Before, `ToMessage` was returning both the resulting `Message` and an error while no error is returned now.
Those error checks were probably leftover from the past.
=> Removes some leftover `err` check

eth/catalyst/simulated_beacon.go
The break only breaks out of the select statement, making maxCount useless.
It should return immediately instead.
=> eth/catalyst: fix flaw in withdrawal-gathering in simulated beacon

tests/state_test_util.go
Fixes a `panic` due to the TxStart not having been called, which results in the `env` in the json logger to be `nil`. 
```
]$ go run ./cmd/evm/ --json --noreturndata --nomemory statetest ./fuzz.json 
{"output":"","gasUsed":"0x79bff8"}
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xd05322]
goroutine 1 [running]:
github.com/ethereum/go-ethereum/eth/tracers/logger.(*jsonLogger).OnOpcode(0xc0000128d0, 0x0, 0x7f, 0x79bff8, 0x3, {0x1634008, 0xc0000138d8}, {0x0, 0x0, 0x0}, ...)
/home/user/go/src/github.com/ethereum/go-ethereum/eth/tracers/logger/logger_json.go:67 +0xa2
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc000040780, 0xc000000540, {0x20d8400, 0x0, 0x0}, 0x0) …
```
=> tests: fix panic via state test runner using json logger

core/blockchain.go, core/chain_makers.go, core/state/database.go, core/state/statedb.go, core/state_processor_test.go, triedb/database.go, triedb/pathdb/database.go, triedb/pathdb/database_test.go, triedb/pathdb/difflayer.go, triedb/pathdb/difflayer_test.go, triedb/pathdb/disklayer.go, triedb/pathdb/errors.go, triedb/pathdb/metrics.go, triedb/pathdb/nodebuffer.go, triedb/pathdb/reader.go
In order to reduce the merging complexity of verkle, this PR adds a test meant to serve as a sentinel for changes that break verkle execution. It is a subset of a test that is used extensively in the verkle branch.
This requires #29084 as the current code hashes the node, which isn't really practical to do in a verkle way (on top of using a different hashing algorithm).
Co-authored-by: Ignacio Hagopian <jsign.uy@gmail.com>
=> core: add an end-to-end verkle test

eth/protocols/snap/sync.go
This pull request fixes an error for checking storage root existence, introduced by https://github.com/ethereum/go-ethereum/pull/28327/files#diff-d26ea400bc58a59ffc652f18f3e402fe7e3279c1569c8374c216b5d702f2fe7cR2204
In snap sync, there is a special case that a storage is split into several chunks for retrieval, while all the slots are found in the first range in the end. In this case the root node produced by the stackTrie in first range matches with the full one and state healing can be skipped.
In the PR 28327, in order to enhance the condition, an additional check is added to ensure the root storage trie node is indeed present in the database before skipping state healing. **However, the check only reads node in path scheme, namely in hash based the mechanism is no longer working.** …
=> eth/protocols/snap: check storage root existence for hash too

beacon/engine/types.go
rename `clientName` to `name` in `ClientVersionV1 `
https://github.com/ethereum/execution-apis/blob/main/src/engine/identification.md#clientversionv1
=> beacon/engine: Fix json param name in GetClientVersionV1

accounts/keystore/keystore_test.go
The annotations for these two methods have been swapped, correct them
=> accounts/keystore: fix typos in comments

core/blockchain.go
This pull request removes an unused function from the blockchain. It was previously utilized by miner package but is no longer necessary.
=> core: remove unused code

src/components/UI/docs/MDComponents.tsx
- Removes bottom margin from _nested_ `ul` and `ol` elements on markdown pages
cc: @s1na @nloureiro
=> website: fix nested list margin

rpc/ipc_unix.go
Accidentally ran into a issue when start a private network node on my mac with a long datadir name. 
```
WARN [03-28|15:24:36.794] IPC opening failed                       url="/Users/mileschen/Library/Mobile Documents/com~apple~CloudDocs/Dev/labs/ethereum_blockchain/node1/geth.ipc" error="listen unix /Users/mileschen/Library/Mobile Documents/com~apple~CloudDocs/Dev/labs/ethereum_blockchain/node1/geth.ipc: bind: invalid argument"
Fatal: Error starting protocol stack: listen unix /Users/mileschen/Library/Mobile Documents/com~apple~CloudDocs/Dev/labs/ethereum_blockchain/node1/geth.ipc: bind: invalid argument
```
After reading the code, i realize it's the socket path too long, above ipc path's length is 105, But meanwhile i found geth assume Unix Socket Path limit is 108 bytes meanwhile it …
=> rpc: fix ipc max path size

p2p/metrics.go, p2p/server.go
This PR adds new inbound and outbound peer metrics as follows:
1. `p2p/peers/inbound`
2. `p2p/peers/outbound`
It's useful to get those data in the form of metrics, rather than getting them through `admin_peers` and then manually filtering them by the `inbound` field.
=> p2p: add inbound and outbound peers metric

internal/debug/api.go
Looks like this was never updated to convert the legacy log level we're used to sending over `debug_verbosity` to the new levels.
=> internal/debug: convert legacy log level value in `debug_verbosity`

core/types/block.go, core/types/transaction.go, core/types/transaction_signing.go, eth/catalyst/simulated_beacon_test.go
Migrated from `atomic.Value` to the newer (generic) pendants `atomic.Pointer[T]` and `atomic.Uint64` for better performance.
=> core/types: use new atomic types in caches

signer/core/apitypes/types.go, signer/core/apitypes/types_test.go
I br0ke master, this change unbreaks it again
=> signer/core/apitypes: fix apitypes breakage due to bitrotted PR

common/prque/prque.go, common/prque/sstack.go
=> common/prque: fix godoc comments

internal/debug/flags.go, log/handler.go, log/logger_test.go
We noticed the default JSON handler (unexpectedly to us) eats log lines of anything more than INFO level. I suspect this is not intentional, so this PR changes the behavior to log everything by default, and adds a "..WithLevel" method that allows you to configure it if desired. This makes it match the behavior of the Terminal logger.
=> log: default JSON log handler should log all verbosity levels

core/vm/errors.go, core/vm/gas_table.go, core/vm/gas_table_test.go, core/vm/interpreter.go, eth/tracers/internal/tracetest/testdata/call_tracer_flat/callcode_precompiled_throw.json, eth/tracers/internal/tracetest/testdata/call_tracer_flat/nested_create_action_gas.json
While investigating https://github.com/ethereum/execution-specs/issues/914, I noticed that geth hid the actual error, in some cases
- which was hidden as a `ErrOutOfGas`, 
- Behind that, there as an `ErrGasUintOverflow`, 
- But actually, the error we should have returned was `max initcode size exceeded`. 
This PR changes that to surface the actual error
Without this PR: 
```
{"pc":45,"op":106,"gas":"0x1acf1","gasCost":"0x3","memSize":192,"stack":["0x43","0x50","0xab","0x70","0xcc","0x6c","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x20000","0x0"],"depth":1,"refund":0,"opName":"PUSH11"}
{"pc":57,"op":245,"gas":"0x1acee","gasCost":"0x7d00","memSize":192,"stack":["0x43","0x50","0xab","0x70","0xcc","0x6c","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff …
```
=> core/vm: better error-info for vm errors

core/blockchain_sethead_test.go, core/rawdb/database.go, core/rawdb/freezer_test.go, internal/build/util.go, node/node_auth_test.go, signer/core/signed_data_test.go
path.Join will have a '/' file separator in the window environment
=> all: replace path.Join with filepath.Join

accounts/external/backend.go, cmd/devp2p/internal/ethtest/transaction.go, core/blockchain.go, internal/era/iterator.go, miner/worker.go
=> all: replace fmt.Errorf() with errors.New() if no param required

core/genesis.go
As dev mode starts in merge the difficulty of the first block should be zero. You can see a symptom of this problem when doing an eth_call on top of genesis that invokes a post-london opcode:
```terminal
> eth.call({ from: eth.accounts[0], to: '0xc000000000000000000000000000000000000000' }, 'latest', { '0xc000000000000000000000000000000000000000': { code: '0x6080604052348015600e575f80fd5b505f36606048604051602001602291906054565b6040516020818303038152906040529050915050805190602001f35b5f819050919050565b604e81603e565b82525050565b5f60208201905060655f8301846047565b9291505056fea2646970667358221220c0aef6db63bc9113c75225aa80911ead112cc205dcc1cd8b0771368b894dc4e964736f6c63430008190033' } })
WARN [04-05|18:19:22.534] Served eth_call                          reqid=12 duration=5.756917ms  err="invalid …
```
=> core: fix dev mode genesis difficulty

core/vm/evm.go, core/vm/interface.go, tests/block_test.go, tests/state_test.go
This pull request implements [EIP-7610](https://github.com/ethereum/EIPs/pull/8161), which rejects the contract deployment if the destination has non-empty storage.
=> core/vm: reject contract creation if the storage is non-empty

internal/build/util.go, internal/jsre/jsre_test.go, signer/core/signed_data_test.go
Following #29479, replace `path.Join` with `filepath.Join`.
=> internal, signer/core: replace path.Join with filepath.Join

rlp/decode.go, rlp/encode.go
`reflect.PtrTo` has been deprecated and superseded by `reflect.PointerTo`
See also https://pkg.go.dev/reflect#PtrTo
=> rlp: replace reflect.PtrTo with reflect.PointerTo

core/vm/contracts.go, tests/fuzzers/bls12381/precompile_fuzzer.go
https://eips.ethereum.org/EIPS/eip-2537
Name	Value	Comment
FORK_TIMESTAMP	TBD	Mainnet
BLS12_G1ADD	0x0b	precompile address
BLS12_G1MUL	0x0c	precompile address
BLS12_G1MULTIEXP	0x0d	precompile address
BLS12_G2ADD	0x0e	precompile address
BLS12_G2MUL	0x0f	precompile address
BLS12_G2MULTIEXP	0x10	precompile address
BLS12_PAIRING	0x11	precompile address
BLS12_MAP_FP_TO_G1	0x12	precompile address
BLS12_MAP_FP2_TO_G2	0x13	precompile address
=> core/vm: move bls precompiles to correct addresses

core/blockchain.go, core/blockchain_reader.go
=> core: add txlookup lock

core/bloombits/matcher.go, eth/downloader/beaconsync.go, eth/downloader/downloader.go, ethstats/ethstats.go, p2p/simulations/adapters/exec.go, p2p/simulations/mocker.go, p2p/simulations/network.go
```
// After waits for the duration to elapse and then sends the current time
// on the returned channel.
// It is equivalent to NewTimer(d).C.
// The underlying Timer is not recovered by the garbage collector
// until the timer fires. If efficiency is a concern, use NewTimer
// instead and call Timer.Stop if the timer is no longer needed.
```
use time.NewTimer should be used in loop uncertainties to avoid possible memory leaks
=> all: use timer instead of time.After in loops, to avoid memleaks

eth/protocols/snap/metrics.go, eth/protocols/snap/progress_test.go, eth/protocols/snap/sync.go
This pull request enhances the sync snap, preventing the duplicated storage retrieval tasks.
However, due to the fact that 
- storage retrieval tasks are selected randomly: https://github.com/ethereum/go-ethereum/blob/master/eth/protocols/snap/sync.go#L1274 
- a few waves of storage tasks could be sent out before receiving any responses (no subTask scheduled yet)
Consequently, it is entirely possible that there are some completed storages(could be small storage retrieved in a single request, or large contract be retrieved in multiple requests) while there remains an incomplete storage task preceding them.
If the snap sync is interrupted at that time, the fully-retrieved storages won't be considered as completed due to the incomplete storage task beforehand. …
=> eth/protocols/snap: skip retrieval for completed storages

cmd/clef/rules.md, cmd/ethkey/README.md
**Updated for readability and typos**
cmd/ethkey/README.md
cmd/clef/rules.md
=> Updated for readability and typos (.md)

core/rawdb/accessors_chain.go
This PR adds a sanity-check limit of 2MB for header-range queries
=> core/rawdb: add sanity-limit to header accessor

eth/filters/api.go
This PR adds a limit to the "inner" topics in a filter-criteria
=> eth/filters: enforce topic-limit early on filter criterias

core/state/snapshot/conversion.go, core/state/statedb.go, eth/protocols/snap/gentrie.go, eth/protocols/snap/gentrie_test.go, eth/protocols/snap/metrics.go, eth/protocols/snap/sync.go, trie/stacktrie.go, trie/stacktrie_fuzzer_test.go, trie/stacktrie_test.go, trie/trie_test.go
This pull request defines a `gentrie` for snap sync purpose.
The stackTrie is used to generate the merkle tree nodes upon receiving a state batch. Several additional logics have been added into stackTrie to handle incomplete states (either missing states before or after).
In this pull request, these logics have been relocated from stackTrie to genTrie, which serves as a wrapper for stackTrie specifically for snap sync purposes. 
--- 
What's more, the logic for incomplete states has been enhanced in this pull request. Originally, there are two additional logics exist:
- boundary node filtering 
- internal (covered by extension node) node clearing
(Implemented in this [pull request](https://github.com/ethereum/go-ethereum/pull/28327/))
By this pull request, this logic has been added: …
=> core, eth/protocols/snap, trie: implement gentrie

rpc/client.go, rpc/websocket.go
- PR to implement `Unwrap()` for wsHandshakeError
- Removes a tautological condition
=> rpc: implement Unwrap() for wsHandshakeError

rpc/client_test.go, rpc/websocket_test.go
Hi. This PR adds some `defer client.Close()` to rpc tests where it was missing and removes a duplicate call.
This helps reduce the number of goroutines left running after the tests execute.
Thanks for your review.
=> rpc: close Clients in tests

cmd/utils/flags.go
In order to be consistent with t8ntool [trace.jsonconfig](https://github.com/ethereum/go-ethereum/blob/master/cmd/evm/internal/t8ntool/flags.go#L38) we rename the to `vmtrace.jsonconfig`.
=> Rename vmtrace.config to vmtrace.jsonconfig

ethdb/pebble/pebble.go
This pull request introduces a mechanism that prints a warning log if database performance is heavily degraded. This feature has been enabled in LevelDB for a long time and is now being brought to Pebble as well.
=> ethdb/pebble: print warning log if db performance degrade

trie/utils/verkle.go
The type of `subIndexMod` is `*uint256.Int` (alias `[4]uint64`) and `DivMod` never returns a `nil`. So `len(subIndexMod)` is always `4` and this code can be simplified.
=> trie/utils: simplify codeChunkIndex

docs/developers/dapp-developer/native-bindings.md
According to the lastest design, the `bind.NewTransactor` function is [deprecated](https://github.com/ethereum/go-ethereum/blob/304879da20200f6912d241ccd471e140d3487093/accounts/abi/bind/auth.go#L44-L56)
=> docs: replace deprecated function NewTransactor in native-bindings page

beacon/blsync/block_sync.go
This PR fixes an issue that happens when the chain either cannot finalize or is new and does not have a finality proof yet. Now if a finality proof is not expected soon then blsync proceeds without a finalized block hash.
=> beacon/blsync: proceed with empty finalized hash if proof is not expected soon

core/vm/contracts.go, core/vm/evm.go, tests/init.go
This is a follow-up to https://github.com/ethereum/go-ethereum/pull/29441, it enables the bls-contracts for Prague, so that the testing-team can enable them.
=> core/vm: enable bls-precompiles for Prague

eth/catalyst/api.go
progress, try to extend it with the current payload request to relieve
=> eth/catalyst: fix typo

cmd/geth/config.go, cmd/geth/consolecmd.go, cmd/geth/main.go
=> all: fix unused parameter passing

cmd/utils/flags.go, eth/filters/api.go, eth/filters/filter.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go, eth/filters/filter_test.go, ethclient/gethclient/gethclient_test.go, ethclient/simulated/backend.go
"Pending logs" were always an odd feature, because it can never be fully reliable. When support for it was added many years ago, the intention was for this to be used by wallet apps to show the 'potential future token balance' of accounts, i.e. as a way of notifying the user of incoming transfers before they were mined. In order to generate the pending logs, the node must pick a subset of all public mempool transactions, execute them in the EVM, and then dispatch the resulting logs to API consumers.
Nowadays, block producers often do not use the top-paying transactions from the public mempool, and rely on MEV extraction processes instead, so it's kind of unlikely for the tx selection made by the node to actually match the next block.
And even for the small percentage of block builders …
=> eth/filters: remove support for pending logs

eth/api_backend.go, eth/gasprice/feehistory.go, eth/gasprice/feehistory_test.go, eth/gasprice/gasprice_test.go, internal/ethapi/api.go, internal/ethapi/api_test.go, internal/ethapi/backend.go, internal/ethapi/transaction_args_test.go, internal/jsre/deps/web3.js
Fixes #29139, this adds the new `eth_blobBaseFee` RPC and the new fields to `eth_feeHistory` from https://github.com/ethereum/execution-apis/pull/486.
~There's still one issue with the code: the `baseFeePerBlobGas` array is missing the "next" block so is one shorter than it should be, but I ran out of time and am not sure how much bandwidth I'll have to work on this again next week.~ Update: I believe this is working as expected now as of [cc1649a](https://github.com/ethereum/go-ethereum/pull/29140/commits/cc1649a364563651d5b18a8a3bf60ec0a17629a3).
Also, the unit test coverage could be a bit better, but I was having trouble getting the `newTestBackend` to actually raise the blob gas price even when blocks were full.  I had to add a fair amount of other logic to `newTestBackend` to support …
=> eth: Add eth_blobBaseFee RPC and blob fields to eth_feeHistory

beacon/blsync/block_sync_test.go, beacon/light/api/api_server.go, beacon/light/api/light_api.go, beacon/light/request/scheduler.go, beacon/light/request/scheduler_test.go, beacon/light/request/server.go, beacon/light/request/server_test.go, beacon/light/sync/head_sync_test.go, beacon/light/sync/test_helpers.go, beacon/light/sync/types.go, beacon/light/sync/update_sync.go
This PR adds an extra mechanism to the `CheckpointInit` sync module that tries to determine the reason and print a useful error log if checkpoint retrieval fails.
If the checkpoint is reported unavailable by a server, it tries to retrieve the belonging header and also its parent header if necessary, in order to determine whether the specified checkpoint block is canonical, finalized and on epoch boundary.
Since neither the canonical or finalized status or the non-existence of the checkpoint or header can be validated without a synced chain, the mechanism operates on a per-server basis and also the error messages are printed per server, based on their reported info.
This PR is based on top of https://github.com/ethereum/go-ethereum/pull/29449
=> beacon/light/sync: print error log if checkpoint retrieval fails

eth/catalyst/api_test.go, triedb/pathdb/database.go, triedb/pathdb/database_test.go
This PR tries to fix two tests that often fail on CI: `TestEth2AssembleBlock` and `TestEth2NewBlock` (edit: and `TestEth2PrepareAndGetPayload`). It changes the call to `Add` a tx to the pool by setting `sync=true`.  
I don't know if doing so somehow makes the test moot, but I don't see why that would be so (?)
=> eth/catalyst: (try to) fix flaky tests

miner/worker.go
fix a typo in `miner/worker.go`
=> fix(miner): fix typos

beacon/blsync/block_sync.go, beacon/blsync/block_sync_test.go, beacon/blsync/engineclient.go, beacon/light/api/api_server.go, beacon/light/api/light_api.go, beacon/light/head_tracker.go, beacon/light/sync/head_sync.go, beacon/light/sync/head_sync_test.go, beacon/light/sync/test_helpers.go, beacon/light/sync/types.go, beacon/light/sync/update_sync.go, beacon/light/sync/update_sync_test.go, beacon/types/exec_payload.go, beacon/types/light_sync.go
This PR adds an extra mechanism to `sync.HeadSync` that tries to retrieve the latest finality update from every server each time it sends an optimistic update in a new epoch (unless we already have a validated finality update attested in the same epoch). Note that this is not necessary and does not happen if the new finality update is delivered before the optimistic update. The spec only mandates `light_client_finality_update` events when a new epoch is finalized. If the chain does not finalize for a while then we might need an explicit request that returns a finality proof that proves the same finality epoch from the latest attested epoch.
Note: the devops nodes that don't send finality update events for some reason do fully work now with this PR, including finalized block info. This …
=> beacon/light: request finality update explicitly when necessary

core/vm/contracts.go
Found while writing tests for EIP-6110, the beacon deposit contract was failing because SHA256 precompile was not where it was supposed to be.
=> core/vm: Fix Prague contracts

core/blockchain.go, core/tracing/hooks.go
The `OnClose` trace hook is being triggered on blockchain Stop, so as tracers can release any resources.
=> core/tracing: Add OnClose Trace Hook

eth/state_accessor.go, eth/tracers/api.go
The beacon root when applied in `state_processor.go` is performed right before executing transaction. That means that contract reliying on this value would query the same value found in the block header.
In that spirit, it means that any tracing/operation relying on state data which touches transaction must have updated the beacon root before any transaction processing. This PR brings this where I spotted where it was important through `StateAtTransaction` and those using with `StateAtBlock` and transactions.
For now I've put the beacon root update outside of `StateAtBlock`. I was reluctant to include it in `StateAtBlock` because technically the state at block doesn't include any state happening "in the block". But everywhere that `StateAtBlock` was used, it felt setting the beacon root …
=> eth, eth/tracers: process beacon root before transactions

core/state/journal.go, core/state/state_object.go, core/state/state_test.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, core/state/statedb_test.go, core/vm/evm.go, core/vm/interface.go, tests/block_test.go
This PR is an alternative to https://github.com/ethereum/go-ethereum/pull/28666 . It is based on the same root, "remove account reset operation", but handles one of the edge-cases slightly differently. 
Whereas #28666 adds a `eip6780DeletableChange` event to the journal, this PR instead adds a `createContractChange`, which I personally find a bit cleaner, semantically. 
Where
- `createObjectChange` represents the event of something being created in the `trie`, a
- `createContractChange` represents the event of a contract being created: this happens slighly _before_ the initcode is executed (order matters, of course). Implementation-wise, it just sets the `created`-flag to true. 
Typically, the sequence of events for a contract deployment would be 
1. createObject
2. createContract
3. // …
=>  core/state: remove account reset operation v2

core/state/journal.go, core/state/state_object.go
Currently our state journal tracks each storage update to a contract, having the ability to revert those changes to the previously set value.
For the very first modification however, it behaves a bit wonky. Reverting the update doesn't actually remove the dirty-ness of the slot, rather leaves it as "change this slot to it's original value". This can cause issues down the line with for example write witnesses needing to gather an unneeded proof.
This PR modifies the `storageChange` journal entry to not only track the previous value of a slot, but also whether there was any previous value at all set in the current execution context. In essence, the PR **changes the semantic of `storageChange` so it *does not* simply track storage changes, rather it tracks *dirty storage changes*, an …
=> core/state: storage journal entry should revert dirtyness too

internal/ethapi/api.go
Fix incorrect comment "pears -> peers"
=> internal/ethapi: typo

core/state/access_list.go, core/state/state_object.go, core/state/statedb_test.go, core/state/transient_storage.go
This PR fixes some flaws with the existing tests, which I discovered while working on a different journalling system. 
The randomized testing (`TestSnapshotRandom`) executes a series of steps which modify the state and create journal-events. 
Later on, we compare the forward-going-states against the backwards-unrolling-journal-states, and check that they are identical. 
The "identical" check is performed using various accessors. It turned out that we failed to check some things: the accesslist contents and the transient storage contents. 
After we remove the account reset operation in https://github.com/ethereum/go-ethereum/pull/29520, we should also add accessors/checks for `newContract`
=> core/state: better randomized testing (postcheck) on journalling

build/checksums.txt, build/ci.go, build/deb/ethereum/deb.rules
=> build: build all the builders to build all the builders

core/state/state_object.go
There are two cases in state object updates that have unexpected leftovers:
- Single tx sets slot from A -> B -> A. In this case the current code will mark the slot marked as updated, but won't prefetch it (that part was smarter). Later the commit (`stateObject.updateTrie`) will try to fetch the trie from the prefetcher, failing, after which it makes a fresh one from the db, only to throw it out because the slot didn't really change.
- Tx1 sets slot from A -> B; after which tx2 sets the same slot from B -> A within the same block. The effect is similar, but the cause slightly different. Tx1 marks the slot updated, and tx2 leaves it as updated, even though it reverted to it's original.
The fix in this PR is fairly simple: whenever a slot is change back to it's original (during tx …
=> core/state: revert pending storage updates if they revert to original

core/blockchain.go, core/state/state_object.go, core/state/statedb.go
This PR is more of a prep thing and maaaaybe (?) a very light performance optimization.
Currently we're trying to measure things very accurately when it comes to state object updates, hashes and commits. The only problem is that there are *a lot* of these, and many will have insignificant runtimes (maybe update 1 slot?). The overhead of retriving system timers and updating metrics might be more than teh actual computation of 1 slot. Due to that, this PR moves the metering a bit to the outside. It does mean we lose the ability to differentiate between storage update and storage hash, but I doubt it's really relevant given that we can only change so many slots in a block.
On the other hand, moving these metrics out does a few useful cleanups: state objects don't start poking at statedb …
=> core/state: move metrics out of state objects

params/config.go
- Defines the `String()` methods on a value receiever so that nil is shown differently.
- Adds the parameters to the representation for `CliqueConfig`.
Currently these config objects will display the same whether they're nil or present. For example, this chain config:
```json
{
"chainId": 1212,
"homesteadBlock": 0,
"eip150Block": 0,
"eip155Block": 0,
"eip158Block": 0,
"byzantiumBlock": 0,
"constantinopleBlock": 0,
"petersburgBlock": 0,
"istanbulBlock": 0,
"berlinBlock": 0,
"londonBlock": 0,
"mergeNetsplitBlock": 0,
"terminalTotalDifficulty": 0,
"shanghaiTime": 0,
"cancunTime": 0
}
```
when printed with `%+v`, shows as (note `Ethash:ethash Clique:clique` at the end):
```
&{ChainID:+1212 HomesteadBlock:+0 DAOForkBlock:<nil> DAOForkSupport:false EIP150Block:+0 EIP155Block:+0 EIP158Block:+0 …
```
=> params: clarify consensus engine config `String`s

params/config.go, params/config_test.go
two errors in func ConfigCompatError as error info in the above picture
1. RewindToTime overflow
for dev testnet, often set timebased hardfork to `0`, so they will be enabled same with London Block at genesis
for example in genesis.json
`
"shanghaiTime": 0,
`
then we change it 
`
"shanghaiTime": 1712889032,
`
and run `geth --datadir ./ init ./genesis.json,  then RewindToTime will overflow to the max of uint64 type
2.  err.StoredTime and err.NewTime are pointers, print them is meaningless, their value are desired
=> params: print time value instead of pointer in ConfigCompatError

cmd/utils/flags.go
Related to #29469 as that doesn't seem resolved if the user sets their own genesis config. I also discovered TTD can be negative and I could trick the correct state by setting `TTD = -1` and `difficulty = 0` since 0 difficulty is what triggers the correct EVM rules. This PR also validates that negative values are not accepted.
---
If genesis config is set by the user, `difficulty` must be > TTD. However, if TTD is `0` and we are post-merge, setting `difficulty > 0` will use the wrong EVM fork rules and raise issues like:
```
WARN [04-18|09:34:02.022] Served eth_estimateGas                   reqid=3 duration="419.912µs" err="invalid opcode: PUSH0"
```
I'm not sure if this is the best way to resolve it but if the user can set both to `0` at genesis, that makes sense that we'd be in a state …
=> cmd/utils: require TTD and difficulty to be zero at genesis for dev mode

core/rawdb/ancient_scheme.go, core/rawdb/ancienttest/testsuite.go, core/rawdb/chain_freezer.go, core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/freezer_memory.go, core/rawdb/freezer_memory_test.go, core/rawdb/freezer_resettable.go, core/rawdb/freezer_resettable_test.go, core/rawdb/freezer_test.go, ethdb/database.go, node/node.go, triedb/pathdb/database.go, triedb/pathdb/history.go, triedb/pathdb/history_inspect.go, triedb/pathdb/history_test.go
This pull request introduces the in-memory freezer, which implements the ethdb.AncientStore interface.
The in-memory freezer can be used along with in-memory key-value store, acting as a full-functional ephemeral database.
=> core/rawdb: implement in-memory freezer

trie/trienode/node.go, trie/trienode/node_test.go
Shaves off a bit of alloc during nodes merge
```
name         old time/op    new time/op    delta
Merge/1K-8      600µs ± 7%     544µs ± 4%   -9.26%  (p=0.000 n=9+10)
Merge/10K-8    5.99ms ± 8%    5.48ms ± 7%   -8.64%  (p=0.000 n=10+10)
name         old alloc/op   new alloc/op   delta
Merge/1K-8      252kB ± 0%     244kB ± 0%   -3.17%  (p=0.000 n=8+10)
Merge/10K-8    2.02MB ± 0%    1.94MB ± 0%   -3.96%  (p=0.000 n=10+10)
name         old allocs/op  new allocs/op  delta
Merge/1K-8      2.08k ± 0%     0.08k ± 0%  -96.29%  (p=0.000 n=10+9)
Merge/10K-8     20.6k ± 0%      0.6k ± 1%  -97.31%  (p=0.000 n=10+10)
```
=> trie/trienode: minor speedup in nodeset merging
