- accounts/account_manager.go
- accounts/accounts_test.go
- crypto/crypto.go
- crypto/key.go
- crypto/key_store_passphrase.go
- crypto/key_store_plain.go
- crypto/key_store_test.go
* Add initial UserAccount and AccountManager structs
* Add NewAccount, Sign and Accounts functions
* Refactor key stores to use key address as main identifier
while keeping the UUID.
* Use key address as file/dir names instead of UUID
>  Add accounts package and refactor key stores

- cmd/ethereum/flags.go
- cmd/ethereum/main.go
- cmd/mist/flags.go
- cmd/mist/main.go
- cmd/mist/ui_lib.go
- cmd/utils/cmd.go
- eth/backend.go
To support functionality requested in https://github.com/ethereum/system-testing/issues/30
> Seednode CLI param updates

- .travis.yml
Better structured Travis config
> Updates for Travis

- cmd/ethereum/main.go
- eth/backend.go
- logger/types.go
Per https://github.com/ethereum/system-testing/wiki/Log-Events
> JSON log updates

- rpc/util.go
> topics fix

- rpc/args.go
- rpc/packages.go
0 is genesis block. Xeth recognises -1 as current
> Allow zero and negative block numbers

- accounts/account_manager.go
- accounts/accounts_test.go
- crypto/key_store_plain.go
Thanks to https://github.com/jaekwon for original fix!
> Fix key store address hex decoding and accounts test

- accounts/account_manager.go
- accounts/accounts_test.go
* Change account signing API to two sign functions;
* Sign without passphrase - works if account is unlocked
* Sign with passphrase - always works and unlocks the account
* Account stays unlocked for X ms and is then automatically locked
> Add automatic locking / unlocking of accounts

- rpc/api.go
- rpc/messages.go
> Stub defaultBlock RPC methods

- cmd/ethereum/flags.go
- cmd/ethereum/main.go
- cmd/mist/flags.go
- cmd/mist/main.go
- cmd/utils/cmd.go
- rpc/http/server.go
`-rpcaddr=""` will listen on all addresses
`-rpcaddr="127.0.0.1"` is the default
> Set RPC listening address via param

- cmd/blocktest/flags.go
- cmd/blocktest/main.go
- core/chain_manager.go
- core/error.go
* Add blocktest cmd and support for block tests files in
tests/BlockTests , the launched node does not connect to
network, resets state with a genesis block from the test file
and starts the RPC API
> Add initial implementation of block tests

- trie/iterator.go
Bug: If you set contract.storage[0] = whatever, you won't see it by iterating over storage using the Iterator.
This is the fix.
> Fixed iterator bug which skips the 0x000...000 key

- cmd/ethereum/main.go
- cmd/utils/cmd.go
plus a little mod for version output
> Poc9/cli (exportchain)

- cmd/ethereum/blocktest.go
- cmd/ethereum/main.go
- cmd/mist/main.go
- cmd/utils/flags.go
- core/types/block.go
- eth/backend.go
- tests/blocktest.go
This won't compile until ethereum/ethash#4 is merged.
Also needs to be updated for changes to develop.
> cmd/ethereum: add blocktest command

- README.md
> Fix link to build instructions in the readme

- blockpool/blockpool.go
- blockpool/peers.go
- blockpool/section.go
- blockpool/status.go
https://github.com/ethereum/go-ethereum/issues/511
> Frontier/blockpool 

- eth/backend.go
> eth: fix protocol version/network id copied from config to Ethereum field

- blockpool/blockpool.go
- blockpool/peers.go
- blockpool/peers_test.go
- reset bestIdleTimer when launching head section process
- log chain head events
- common.Hash key in activateChain map
> bugfix with idle too long triggered after peer switch

- rpc/responses.go
- rpc/responses_test.go
To coincide with recent type conversion
Tests don't test much other than running through the conversions, which is the main function of the response types.
> Update response types + tests

- vm/address.go
What's the proper way to run the tests for something like this?
> vm: explicit error checks in ecrecover #505

- eth/backend.go
> Update Go bootnode address

- rpc/api.go
- rpc/responses.go
- rpc/responses_test.go
> Issue #613

- jsre/pp_js.go
one more, I think the last one related with printing values.
> do not print Plain Object prototype fields in geth console

- common/bytes.go
- rpc/api.go
- rpc/args.go
- rpc/args_test.go
- rpc/responses.go
- xeth/xeth.go
Placeholder for ongoing RPC Test fixes
> RPC Tests updates

- rpc/api.go
> Fix RPC Call output when empty

- p2p/server.go
The dial timer was not reset properly when the peer count reached MaxPeers.
> p2p: fix the dial timer

- rpc/responses.go
This is my first attempt at submitting a pull request for actual go code.
I did run ./gocoverage.sh when I was done and did not get any errors but like I said, I am a newbie and may have made any number of mistakes.
Baby steps to the elevator Bob...
> Remove "minGasPrice" field from JSON responses. Closes. #754

- cmd/geth/block_go_test.go
- cmd/geth/blocktest.go
- eth/backend.go
- tests/block_test_util.go
- tests/blocktest.go
- tests/transaction_test_util.go
* Add fixes to parsing and converting of fields in tx tests
* Correct logic in tx tests; validation of fields and correct
logic for when RLP decoding works/fails and when this is
expected or not
* Rename files for consistency
* Add block tests wrapper to run block tests with go test
> Block test improvements

- rpc/args.go
> Treat hexnums as big.Int instead of int64. Closes #762

- rpc/api.go
> Rename eth_Version to eth_protocolVersion. Closes #737

- cmd/geth/main.go
█   █      █                       █           █  █           ███              █   █
█ █ █ ███  █  ███ ███ ███ ███     ███ ███     ███ ███ ███     █   ███ ███ ██  ███     ███ ███
█ █ █ ██   █  █   █ █ ███ ██       █  █ █      █  █ █ ██      ██  █   █ █ █ █  █   █  ██  █
█████ ███  ██ ███ ███ █ █ ███      ██ ███      ██ █ █ ███     █   █   ███ █ █  ██  ██ ███ █
> Changed "Welcome to the Frontier" to something more geeky

- README.md
- eth/backend.go
* Updated bootnode URI
* Cleanup duplicate README text
> Bootnodes update

- common/path.go
> Remove path separator literals

- cmd/geth/main.go
- core/chain_manager.go
- eth/backend.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/queue.go
- eth/downloader/queue_test.go
- eth/handler.go
- eth/sync.go
> eth, eth/downloader: error handlers and td checks

- cmd/utils/flags.go
- p2p/handshake.go
- p2p/handshake_test.go
- p2p/peer.go
- p2p/server.go
- p2p/server_test.go
These fixes mostly correct some errors from recent PRs.
I have bumped the default maxpeers to 25 as the result of a discussion with @subtly.
> p2p: more last-minute fixes

- common/size.go
- common/size_test.go
- core/events.go
- core/manager.go
- core/transaction_pool.go
- eth/backend.go
- miner/miner.go
- miner/worker.go
- rpc/jeth.go
* core: Added GasPriceChange event
* eth: When one of the DB flush methods error a fatal error log message
is given. Hopefully this will prevent corrupted databases from
occuring.
* miner: remove transactions with low gas price. Closes #906, #903
> core, eth, miner: improved tx removal & fatal error on db sync err

- cmd/geth/js_test.go
- jsre/ethereum_js.go
- rpc/api.go
- rpc/args.go
- rpc/jeth.go
- xeth/xeth.go
This is an API extension that is necessary for Dapps that create various receipts and make promises outside of the block chain. In particular, it is helpful for testing Swarm, but I propose this change because of its general usefulness.
> Signature on arbitrary data using the private keys of an account

- cmd/geth/admin.go
- miner/worker.go
Miner does not ignore low gas txs from accounts that are owned.
> miner, cmd/geth: miner will not ignored owned account transactions

- eth/backend.go
- ethdb/database.go
> eth, ethdb: lower the amount of open files & improve err messages for db

- xeth/xeth.go
> Check for error on DB fetch of tx

- rpc/api.go
> Format contract code as hexdata

- cmd/geth/admin.go
- core/chain_manager.go
- eth/backend.go
- miner/miner.go
> core, miner: fork resolving and restart miner after sync op

- miner/agent.go
Prevent double closing of quitCurrentOp channel #1002
> fixed race condition in miner

- cmd/geth/admin.go
- cmd/geth/main.go
- cmd/utils/cmd.go
Removes the state and blockchain databases
Closes #1010
> Add "removedb" command to Geth

- rpc/api.go
- xeth/xeth.go
Placeholder per #884 
Updates to `eth_getBlockByNumber` and `eth_getTransactionByHash` complete. Changes to filter logs blocked
> JSON RPC null field updates

- cmd/geth/admin.go
- cmd/geth/main.go
- cmd/utils/flags.go
- eth/backend.go
- backend: AutoDAGDir passed from cli, autoDAG loop started if non-empty
- backend: autoDAG loop start/stop, remove previous DAG
- cli: AutoDAG bool flag, off by default, but automatically ON if mining
- admin jsre: add startAutoDAG stopAutoDAG and makeDAG in miner section
closes #1015
> automatic DAG pregeneration for smooth epoch transitions

- eth/sync.go
> eth: expand acronym in log message from TD

- cmd/geth/admin.go
- cmd/geth/js.go
- jsre/jsre.go
- jsre/jsre_test.go
- rpc/jeth.go
This PR will fix #1070, #1082, #1083 and hopefully #1079 and will also clean up the timer handling.
> jsre: fixes for concurrent use, improved timer handling

- cmd/geth/js.go
This fix applies mostly to unsupported terminals that do not trigger the
special interrupt handling in liner. Supported terminals were covered
because liner.Prompt returns an error if Ctrl-C is pressed.
> cmd/geth: exit the console cleanly when interrupted

- cmd/mist/assets/examples/coin.html
- core/block_processor.go
- core/block_processor_test.go
- core/state/log.go
- core/types/receipt.go
Optimised logs and stored receipts for faster iterations
> core: log optimisations

- miner/worker.go
@see trace https://gist.github.com/eupraxic/87fdfefe702c51d5944d
> crash fix: skip deep log if self.chain is not caught up

- p2p/discover/node_test.go
- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/udp_test.go
This should fix the Travis build failures.
> p2p/discover: deflake TestUDP_successfulPing

- eth/sync.go
- If an explicitly fetched block won't fit our chain, don't spin up a new goroutine for the import
- Miners will probably originate a lot of hash announcements. Don't hammer them for pulling the blocks if some other neighbors also advertised that they have the block. Pick the fetch origin randomly.
- Fix a few bugs (premature state cleanups) that resulted in the same block pulled multiple times.
> eth: optimize the notification/explicit fetch mechanism

- core/chain_manager.go
- eth/backend.go
Added an additional channel which is used to interupt the chain manager
when it's processing blocks.
> eth, core: interrupt the chain processing on stop

- rpc/args_test.go
> unit test coverage for NewDataArgs

- eth/fetcher/fetcher.go
Fairly trivial PR containing two fine tuning:
* Only cache future blocks to a distance of 32 (opposed to 256 previously). The rationale behind future caching is to make transitioning from the downloader to propagation smooth: blocks appearing after the downloader started importing should be cached in order not to require a new download iteration. 256 accumulates too much junk and really beats the original purpose of the caching.
* When an announce times out and needs manual fetch, also fetch anything within 100ms expiration time too: this should prevent simultaneously announced blocks from trashing the scheduler and reiterating ms-s apart.
> eth/fetcher: lower max cache size, add timeout slack

- common/db.go
- core/chain_manager.go
- ethdb/database.go
- ethdb/memory_database.go
- trie/cache.go
- trie/trie_test.go
> core, ethdb, trie: validate database errors

- core/block_processor.go
- core/chain_makers.go
- core/state/state_object.go
- core/state_transition.go
- miner/worker.go
- tests/state_test_util.go
- xeth/xeth.go
* BuyGas => SubGas
* RefundGas => AddGas
* SetGasPool => SetGasLimit
> core, miner, xeth: renamed gas methods

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go
- Godeps/_workspace/src/github.com/ethereum/ethash/ethash_test.go
- Godeps/_workspace/src/github.com/ethereum/ethash/src/libethash/internal.c
- Godeps/_workspace/src/github.com/ethereum/ethash/src/libethash/internal.h
See changes here: https://github.com/ethereum/ethash/pull/65
> Update Ethash Godeps

- rpc/codec/codec.go
- rpc/codec/json.go
- rpc/comms/comms.go
- rpc/comms/ipc.go
- rpc/comms/ipc_unix.go
- rpc/comms/ipc_windows.go
> IPC interface improvements

- cmd/geth/monitorcmd.go
This PR fixes a few small issues with the monitor (prefilled dummy data, no rescale on unit change, panic on too little data).
> Monitor fixes

- .travis.yml
- README.md
- cmd/geth/monitorcmd.go
- eth/fetcher/fetcher.go
- p2p/peer.go
- p2p/peer_test.go
- p2p/protocol.go
Do not merge! Just opened to show which commits where lost in recent merges from HEAD this morning
> Debug develop

- core/canary.go
- core/chain_manager.go
- miner/worker.go
> miner: broadcast block before insertion/validation

- core/chain_manager.go
- core/chain_manager_test.go
- core/transaction_pool.go
* Add a checkpoint every X blocks
* Removed queued write
> core: added checkpoint for last block

- cmd/geth/main.go
- core/chain_manager.go
> core, cmd/geth: recover by number

- core/state_transition.go
- xeth/types.go
- xeth/xeth.go
> core, xeth: core.AddressFromMessage removed => crypto.CreateAddress

- cmd/utils/flags.go
- core/canary.go
- rpc/codec/json.go
- rpc/codec/json_test.go
- rpc/jeth.go
This PR:
- fixes #1350
- fixes #1336
- shows a brief error and stacktrace in the console
- add support for request pipelining
- solves a problem with missing requests
> Several bugfixes to IPC channel

- core/block_processor.go
- core/block_processor_test.go
- core/chain_manager.go
- core/transaction_util.go
- core/types/receipt.go
- eth/gasprice.go
- miner/worker.go
- xeth/xeth.go
* Added GetReceiptsFromBlock, GetReceipt, PutReceipts
* Added ContractAddress to receipt. See #1042
> core, eth, miner, xeth: receipt storage fix

- core/types/transaction.go
- core/types/transaction_test.go
- xeth/xeth.go
> core/types, xeth: separate tx hash and tx signature hash

- core/bad_block.go
- core/chain_manager.go
- miner/worker.go
- tests/init.go
Whenever bad blocks are encountered they are being reported to https://badblocks.ethdev.com
> core, miner, tests: added test, implemented bad block reporting

- core/block_processor.go
- core/transaction_util.go
- core/types/receipt.go
- eth/gasprice.go
- rpc/api/eth.go
- rpc/api/parsing.go
Added some additional backward compatibility code for old receipts
> core, eth, rpc: proper gas used. Closes #1422

- cmd/geth/main.go
- cmd/utils/flags.go
- eth/backend.go
- miner/miner.go
- miner/worker.go
- rpc/api/miner.go
- rpc/api/miner_args.go
- rpc/api/miner_js.go
- tests/block_test_util.go
- tests/state_test_util.go
- xeth/types.go
- xeth/xeth.go
Credit goes to @zelig but #1419 contains file changes that are incorrect.
> cmd,eth,rpc,tests: default coinbase

- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
This is a fairly simple PR, which only ensures that the eth/61 sync procedure drops fake TD attacks. If a remote peer advertised a higher TD than ours, but can't/won't deliver anything we don't have yet, then drop it immediately.
Other than that I tagged the tests with the protocol versions they are running against, merged a few ones to use the same code and test both proto versions, and of course added a test for the specific scenario we try to circumvent.
> eth/downloader: drop peer if advertised TD but won't delvier

- core/filter.go
- jsre/ethereum_js.go
- miner/worker.go
- xeth/xeth.go
> miner, xeth: fire log event during mining. Fix return raw tx

- cmd/geth/js_test.go
- cmd/geth/main.go
- cmd/utils/flags.go
- common/natspec/natspec_e2e_test.go
- core/bench_test.go
- core/block_processor_test.go
- core/chain_makers.go
- core/chain_makers_test.go
- core/chain_manager.go
- core/chain_manager_test.go
- core/chain_util.go
- core/genesis.go
- eth/backend.go
- eth/protocol_test.go
- tests/block_test_util.go
Implemented the `--genesis` flag thru which we can set a custom genesis
block, including the official Ethereum genesis block.
#1402
> core: genesis preparation

- miner/agent.go
- miner/remote_agent.go
- miner/worker.go
Work is now handled and carried over multiple sessions. Previously one
session only was assumed, potentially resulting in invalid (outdated)
work
> miner: smart mining

- cmd/geth/main.go
- cmd/utils/cmd.go
- cmd/utils/legalese.go
Note that fancy terminal support is disabled, as it was rendering inconsistently
> Legalese updates

- core/chain_makers_test.go
- core/fees.go
- tests/block_test.go
@CJentzsch @Gustav-Simonsson Block tests probably require an update due to this change
> core: 5 ether block reward

- crypto/ecies/asn1.go
- crypto/ecies/ecies_test.go
Reverts ethereum/go-ethereum#1551
> Revert "remove elliptic.P224 usage"

- accounts/accounts_test.go
This should fix the flakeyness.
> accounts: bump timeout in TestSignRace

- cmd/ethtest/main.go
> Update ethtest default path for BlockTests

- core/block_processor.go
- core/chain_makers.go
- core/chain_util.go
- core/chain_util_test.go
- miner/worker.go
- tests/files/BasicTests/difficulty.json
This PR changed from inflation to ice age. Difficulty will now increase rather than decrease
> core, miner: added difficulty bomb

- cmd/geth/main.go
- eth/backend.go
- miner/miner.go
- rpc/api/miner.go
Implemented canonical extra data according to
https://github.com/ethereum/wiki/wiki/Extra-Data
> cmd/geth, eth: added canonical extra data

- jsre/ethereum_js.go
> web3: updated

- p2p/rlpx.go
Validate recovered ephemeral pubkey against checksum in decodeAuthMsg
Initiator sends an `authMsg` containing a signature produced by the ephemeral private key, and a sha3 checksum of the ephemeral public key. However the receiver was not validating the recovered pubkey against the checksum.
The other change is to check the validity of a remote peer right away, so we don't first waste entropy/time on a nonce and private key.
> p2p: validate recovered ephemeral pubkey

- xeth/xeth.go
When doing a call use the `2**256` as a mix for `eth_call`. This should also give the correct estimate regardless of the current gas limit
> xeth: call fix when doing 'create'-like calls

- jsre/jsre.go
- jsre/pretty.go
This PR fixes a minor issue when printing arrays containing objects and adds a new JS function `inspect` that pretty-prints its arguments.
> jsre: pretty printer improvements

- rpc/xeth.go
At a certain point the RPC API package was updated to return separate success and error messages instead of one big `map[string]{interface}`. Since the monitor wasn't used lately, nobody checked that it uses its own custom `xeth over rpc` module (to directly be able and call methods from Go, not requiring javascript console stuff), which wasn't updated and hence broke down. This PR simply patches up that module to interpret the response of the RPC call and extract the read data from it.
> rpc: update the xeth over RPC API to use the success/failure messages

- core/block_processor.go
- core/state_transition.go
> core: improve block gas tracking

- cmd/geth/main.go
- cmd/utils/flags.go
- eth/backend.go
Dev mode enabled some debugging flags such as:
* VM debugging mode
* Simpler proof of work
* Whisper enabled by default
* Datadir to a tmp datadir
* Maxpeers set to 0
* Gas price of 0
* Random listen port
> cmd/geth, cmd/utils, eth: added dev mode flag

- cmd/geth/main.go
Allows setting extradata from the command line
> adds extradata flag

- cmd/geth/js.go
right. The long desired one-character change PR!
> fix console history, lines with leadning whitespace NOT included

- eth/peer.go
This PR fixes an issue where "Gav's Node" would be stuck in the peer list even when a private network id was configured.
> eth: time out status message exchange after 5s

- eth/gasprice.go
- xeth/xeth.go
XEth.gpo was being initialized as needed. WithState copies the XEth
struct including the gpo field. If gpo was nil at the time of the copy
and Call or Transact were invoked on it, an additional GPO listenLoop
would be spawned.
Move the lazy initialization to GasPriceOracle instead so the same GPO
instance is shared among all created XEths.
Fixes #1317
Might help with #1930
> eth, xeth: fix GasPriceOracle goroutine leak

- cmd/utils/flags.go
- common/natspec/natspec_e2e_test.go
- common/natspec/natspec_e2e_test.go.orig
- crypto/crypto.go
- crypto/key_store_passphrase.go
- crypto/key_store_test.go
- tests/block_test_util.go
Addresses
https://github.com/ethereum/go-ethereum/issues/1148
https://github.com/ethereum/go-ethereum/issues/1911
> cmd/utils, crypto: add --lightkdf flag for lighter KDF

- cmd/utils/flags.go
- eth/filters/filter_system.go
- miner/miner.go
- miner/remote_agent.go
- miner/worker.go
- rpc/comms/ipc.go
- rpc/comms/ipc_unix.go
- rpc/comms/ipc_windows.go
- xeth/xeth.go
This PR fixes an issue where every IPC connection would leak goroutines and memory when the connection was closed.
Fixes #1930. I ran the shell loop there for a few minutes and didn't see any changes in the memory profile.
> Fix for xeth OOM issue

- miner/remote_agent.go
This PR fixes an issue where the remote worker was stopped twice and not
properly handled. This adds a synchronised running check to the start
and stop methods preventing closing of a channel more than once.
> miner: synchronise start / stop

- eth/downloader/peer.go
- eth/downloader/queue.go
This PR fixes an ugly issue hidden by the usage of a generic set implementation, which failed to catch mismatching types being placed inside it.
In essence, we were using a generic `fatih.Set` to accumulate a list of hashes that a node didn't have in order to prevent re-requesting them multiple times. The original code to populate this set iterated over a `map[hash]Header` construct, placing all the selected hashes into said set. After rewriting this construct to simply `[]Header`, the for each construct (`for hash, _ := range headers`) remained valid, but [instead of  adding hashes, it added indexes](https://github.com/ethereum/go-ethereum/pull/1960/files#diff-bdc55f77f09f52de6a3820c6619900caL880), essentially rendering the ignore list dysfunctional. The end result is that the same peer …
> eth/downloader: fix dysfunctional ignore list hidden by generic set

- event/filter/filter_test.go
```
Read by goroutine 6:
github.com/ethereum/go-ethereum/event/filter.TestFilters()
/work/src/github.com/ethereum/go-ethereum/event/filter/filter_test.go:48 +0x829
testing.tRunner()
/opt/google/go/src/testing/testing.go:456 +0xdc
Previous write by goroutine 7:
github.com/ethereum/go-ethereum/event/filter.TestFilters.func1()
/work/src/github.com/ethereum/go-ethereum/event/filter/filter_test.go:33 +0x6a
github.com/ethereum/go-ethereum/event/filter.Generic.Trigger()
/work/src/github.com/ethereum/go-ethereum/event/filter/generic_filter.go:47 +0x3d
github.com/ethereum/go-ethereum/event/filter.(*Generic).Trigger()
<autogenerated>:4 +0xce
github.com/ethereum/go-ethereum/event/filter.(*Filters).loop() …
```
> event/filter: fix data race in the test

- cmd/geth/js.go
- jsre/ethereum_js.go
- xeth/xeth.go
Random fixes I made during some whisper sessions
> cmd, crypto: updated web3

- jsre/jsre.go
The JRSE code directly maps `setTimeout` and `setInterval` to Go function calls, however this prevents being able to properly throw a JavaScript exception in case of bad parameters (i.e. missing callback to invoke when the timer fires). This PR renames the internal implementations to an underscored naming convention (e.g. `_setTimeout`), and provides an outer wrapper that runs within the JavaScript VM and that will actually enforce the required callback parameter.
With the new code:
```js
> setTimeout()
TypeError: Failed to execute 'setTimeout': 1 argument required, but only 0 present.
at setTimeout (<anonymous>:-73:-13)
at <anonymous>:1:1
```
With the old code it was a hard panic.
What a browser would report:
```js
setTimeout()
Uncaught TypeError: Failed to execute 'setTimeout' on …
```
> jrse: fix #1082, fail if setTimeout/setInterval lack callback

- Makefile
@obscuren @fjl Any chance of a quick merge so I can progress on the build bot? Thanks :)
> Makefile: enable iOS experimental builds (fix prev omission)

- core/transaction_pool.go
- core/transaction_pool_test.go
*This PR contains 3 fixes to the transaction pool. Originally I wanted to open separate PRs for each of them, but as they would conflict with each other, it's simpler to add all three into one. However I'd like to keep the commits and motivations separately as they fix different issues.*
---
Currently if a transaction arrives over the network, the origin account of which doesn't have enough funds, we simply discard the transaction.
However, if the account did have enough funds upon transaction receipt (and spends all of it with the first one), we will queue them up and never again check, instead keeping the transactions around until the balance constraint is again satisfied. If the said out-of-fund transactions were placed in the future queue, this is a smaller problem, as it burdens only …
> core: transaction invalidation and reorganization fixes

- cmd/geth/main.go
- cmd/utils/flags.go
- rpc/api/bzz_js.go
- rpc/api/utils.go
- swarm/api/testapi.go
- swarm/cmd/swarm/gethup.sh
- swarm/cmd/swarm/netstatconf.sh
- swarm/cmd/swarm/swarm.sh
- swarm/cmd/swarm/test.sh
- swarm/network/forwarding.go
- swarm/network/hive.go
- swarm/network/messages.go
- swarm/network/protocol.go
- swarm/network/syncer.go
- swarm/storage/chunker.go
- swarm/storage/database.go
- swarm/swarm.go
- swarm/test/connections/00.sh
- swarm/test/syncing/00.sh
- swarm/test/syncing/01.sh
- swarm/test/syncing/02.sh
* migrate ethutil scripts under swarm/cmd/swarm
* add basic peer connection bootstrap test
* hive keepAlive launches with alarm in case no discover and no kaddb
* fix IP address formatting issue [::1] -> became ::1 which refused to dial, now use discover.NewNode#String
* database Print removed
* add another syncer test for aborted sync
* forwarding: only send if syncer is setup on the peer (not blocking)
* add control api for network (block read)
* syncing test for stalled/aborted connection
> scripted network/sync tests

- core/chain_makers.go
@fjl PTAL
@zsfelfoldi Please try this fix for the chain maker.
> core: fix invalid state reuse in chain maker based tests

- accounts/abi/abi.go
- accounts/abi/abi_test.go
- accounts/abi/event.go
- accounts/abi/event_test.go
- accounts/abi/type.go
Implementation of basic event parsing and its input types. This
separates methods and events and fixes an issue with go type parsing and
validation.
> account/abi: implements event parsing

- rpc/http.go
This PR simply makes the HTTP RPC server respond to GET requests too as it seems most client code was written like that.
**Note, although this does fix the issue, do we really want to support GET? What clients are using GET? Anything that's JavaScript will default to POST.**
> rpc: allow RPC requests on GET too

- accounts/abi/abi.go
- accounts/abi/abi_test.go
Added support for fixed size and arbitrary length byte arrays to be
marshallable in fixed size (typed) byte slices.
> accounts/abi: support for typed array

- crypto/ecies/ecies.go
- crypto/ecies/ecies_test.go
- p2p/discover/udp.go
- p2p/discover/udp_test.go
- p2p/message_test.go
- p2p/peer.go
- p2p/rlpx.go
- p2p/rlpx_test.go
- rlp/decode.go
- rlp/decode_tail_test.go
- rlp/decode_test.go
- rlp/encode.go
- rlp/encode_test.go
- rlp/typecache.go
Resubmit of #2091 because it got merged by accident.
> p2p, p2p/discover: EIP-8 changes

- eth/downloader/downloader.go
This is a step into the direction of fixing https://github.com/ethereum/go-ethereum/issues/2211. This PR is not really the cause of that issue, but the fixes contained within are safety nets that should help prevent strange failures.
The PR contains two related fixes:
* When doing fast sync and importing headers, if part of the batch import succeeded but part of it not, then the rollback didn't remove the part that actually succeeded (it only appended them to the list after importing the entire batch successfully), so even though the receipts were rolled back, the headers not. This should not really cause any issues because when we sync the next time, we do the ancestor lookup from out head receipts and not head headers. Nonetheless it's bad behavior so the PR fixes it by rolling back the …
> eth/downloader: fix partial rollback and ancestor lookup

- eth/api.go
When a block is queried for retrieval we should add a check whether the
block falls within the frontier rules. If we'd always use `From`
retrieving transaction might fail.
> eth: fixed homestead tx check

- params/protocol_params.go
This commit increases the artificial gas floor to 4712388
> params: settle the Pi vs Tau dispute

- rpc/inproc.go
> rpc: simplify inproc client

- cmd/utils/jeth.go
This PR will allow users to supply a password as argument when creating a new account with `personal.newAccount`. This is useful for scripts.
It also addresses a problem with single quotes in the password which where not escaped.
> console: allow optional password on the command line

- core/blockchain.go
- core/blockchain_test.go
Previously all blocks that were already in our chain were never re
announced as potential uncle block (e.g. ChainSideEvent). This is
problematic during mining where you want to gather as much possible
uncles as possible increasing the profit. This is now addressed in this
PR where during reorganisations of chains the old chain is regarded as
uncles.
Fixed #2298
> core: announce ChainSideEvent during reorg

- core/blockchain.go
Added a future lock which prevents the anything being added or removed
from or to the set when looping over the set of blocks. This fixes a nil
pointer in the range loop when trying to retrieve a block from the set
which was previously available but removed due to regular chain
processing.
Fixes #2305
> core: added future proc mutex lock

- core/block_validator.go
- core/blockchain_test.go
- core/chain_makers.go
- core/state/managed_state.go
- core/state/state_test.go
- core/state_processor.go
- core/tx_pool.go
- core/tx_pool_test.go
- core/types.go
- core/types/block.go
- core/types/transaction.go
- core/vm/asm.go
- core/vm/doc.go
- core/vm/environment.go
- core/vm/jit.go
- core/vm/jit_test.go
- core/vm/jit_util.go
- core/vm/runtime/runtime.go
- core/vm/vm.go
- core/vm/vm_jit.go
- core/vm_env.go
Went through all .go files in core/ using aspell in ccpp mode.
> core: various typos

- cmd/geth/main.go
- cmd/utils/flags.go
- common/chequebook/api.go
- common/chequebook/cheque.go
- common/chequebook/cheque_test.go
- rpc/javascript.go
- swarm/api/ethereum.go
- swarm/api/testapi.go
- swarm/cmd/swarm/gethup.sh
- swarm/cmd/swarm/netstatconf.sh
- swarm/cmd/swarm/swarm.sh
- swarm/cmd/swarm/test.sh
- swarm/network/depo.go
- swarm/network/forwarding.go
- swarm/network/hive.go
- swarm/network/messages.go
- swarm/network/protocol.go
- swarm/network/syncer.go
- swarm/services/swap/swap.go
- swarm/swarm.go
- swarm/test/swap/00.sh
- swarm/test/swap/01.sh
* add bzz.syncEnabled (hive.syncEnabled -> testapi/SyncEnabled | bzznosync param)) triggers nil sync State request to peer
* syncEnabled false then historical items are not delivered
* add swap initial scenarios, no funds, no retrieval; chequebook autodeployment; available funds -> retrieval
* remove -ipcexp option from swarm script
* tweaks to swarm/cmd files
* add Balance to chequebook api
* set chequebook balance from blockchain
* fix chequebook tests after balance check
* log balance when chequebook created
* fix state setting in ethereum backend
* add balanceAt to backend
> swap integration test

- cmd/utils/flags.go
- miner/worker.go
This PR introduces a 10% probability that you'll run the client with the
JIT enabled testing the new client and helps us potentially catch
errors when reported.
This feature is **disabled** for miners (disabling the JIT completely).
The JIT can however be force for miners if they enable both `--jitvm` and
`--forcejit`.
> cmd/utils, miner: A/B testing JIT VM. Disabled for miners

- accounts/abi/bind/bind.go
- accounts/abi/bind/bind_test.go
Previously we only supported slices for addresses. This PR fixes it up properly by supporting
* Slices for `address`, `bool` and `string`
* Slices for various sized byte arrays
* Unifies the `int` and `uint` handling code
* Supports both unbound slices and fixed sized arrays for all types
> accounts/abi/bind: support generating bindings for various arrays

- cmd/utils/flags.go
This PR addresses an issue with exporting and importing the chain to/from file. Geth tries to open the database multiple times which would lead to a crash.
Fixes #2428 
@obscuren, PTAL.
I'm not sure about the intentions of [this](https://github.com/ethereum/go-ethereum/blob/7e02105672cda92889a78db864a5701d78f45eb2/cmd/utils/flags.go#L826) line. If the olympic flag is set then the testnet genesis block is written? It was added later so there seems to be reason for it?
> cmd/utils: bugfix where database is opened multiple times

- eth/api.go
- internal/debug/api.go
- jsre/completion.go
- jsre/completion_test.go
- jsre/jsre.go
- jsre/pretty.go
- rpc/javascript.go
I wanted to look at leveldb properties and added the API, but then I got carried
away and fixed a few things in the console, too.
> eth: add chaindbProperty to debug API (+ console fixes)

- common/types.go
- common/types_test.go
Add test for Address#UnmarshalJSON and a minor code improvement
> Improve Address test coverage

- accounts/watch.go
- accounts/watch_fallback.go
Fixes #2488
@obscuren PTAL
@eramseth please try
> accounts: disable file system watch on linux/arm64

- README.md
Our README currently is in quite a dire state. This PR aims to clean it up a bit and expose some valuable information in a friendlier way. The PR is "constantly" ready, as it in can be merged whenever, but I'll keep pushing polishes in here so please only merge it before doing the next RC.
> Make the README suck less :P

- cmd/utils/fdlimit_freebsd.go
> cmd/utils: fix build on *BSD

- miner/worker.go
> miner: fixed pending state by not shutting down update loop

- index.html
I'm not sure on your policy for accepting PR's to `gh-pages` but I have corrected a few typographical and grammatical mistakes.
> Fix typos and grammar

- .github/CONTRIBUTING.md
Fixes a miscellaneous spelling mistake.
> misc: fix spelling mistake

- core/tx_pool.go
Fixes #2650 
Please review: @obscuren
> core: add missing lock in TxPool.GetTransaction

- cmd/geth/accountcmd.go
Fixes https://github.com/ethereum/go-ethereum/issues/2436.
> cmd/geth: fix the keystore path in the accounts help text

- cmd/geth/chaincmd.go
- cmd/utils/flags.go
- core/bench_test.go
- core/block_validator.go
- core/blockchain.go
- core/blockchain_test.go
- core/database_util.go
- core/database_util_test.go
- core/genesis.go
- core/headerchain.go
- core/vm_env.go
- eth/api.go
- eth/backend.go
- eth/backend_test.go
- eth/db_upgrade.go
- eth/filters/api.go
- eth/filters/filter.go
- eth/filters/filter_test.go
- eth/gasprice.go
- eth/handler.go
- eth/handler_test.go
- eth/sync.go
- miner/worker.go
- tests/block_test_util.go
This PR implements the "sequential keys" chain db improvement. Upgrade is automatical and runs in the background.
> core: improved chain db performance by using sequential keys

- cmd/utils/cmd.go
Copy of https://github.com/ethereum/go-ethereum/pull/2689 to fix the commit message.
> cmd/utils: add space between "to" and filename

- core/state_processor.go
Set the final block in stone, T-6 days.
> core: update the DAO soft fork proposal to the final block

- accounts/abi/bind/backends/simulated.go
- common/registrar/ethreg/api.go
- core/state_transition.go
- core/types/transaction.go
- eth/api.go
- internal/ethapi/api.go
- tests/util.go
fixes https://github.com/ethereum/go-ethereum/issues/2796
alternative solution to https://github.com/ethereum/go-ethereum/pull/2797
> core: added CheckNonce() to Message interface

- cmd/bootnode/main.go
Note this also changes the default behaviour of --genkey to run the bootnode after generating the key. If this is a problem, I can change it back to quitting by default.
> cmd/bootnode: Add support for outputting a node's ID on the command line

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/batch.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage/file_storage_nacl.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/hash.go
I need this change to compile with native client.
New commits: https://github.com/syndtr/goleveldb/compare/917f41c560270110ceb73c5b38be2a9127387071...master
> Godeps: bump github.com/syndtr/goleveldb/... to ab8b5dcf104

- containers/docker/develop-alpine/Dockerfile
- containers/docker/master-alpine/Dockerfile
Update alpine, this time using correct branch (develop).
> containers/docker: update to alpine 3.4

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/rjeczalik/notify/.travis.yml
- Godeps/_workspace/src/github.com/rjeczalik/notify/appveyor.yml
- Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents.go
> Godeps: update github.com/rjeczalik/notify to f627deca7a51

- rpc/client.go
- rpc/client_example_test.go
- rpc/client_test.go
- rpc/notification_test.go
I found these issues while working on ethclient.
> rpc: client bug fixes

- eth/downloader/downloader.go
*This is a followup PR to https://github.com/ethereum/go-ethereum/pull/2861, please merge that in first.*
Although we strive to maintain an accurate remote chain head metadata about all of our connected peers, for new connections we kind of have to take in on face value that the peer is truthful in the handshake (especially if it's in the future, there's no sure way to verify).
However there are some peers in the network which report high TDs in their handshakes, but low head numbers. This causes problems for the sync algo as the high TD will prompt a sync cycle, but the low reported head causes the ancestor lookup to estimate an older fork point, pulling and reimporting many duplicate blocks (wasted IO, wasted PoW check).
This PR modified the ancestor lookup so that instead of requesting …
> eth/downloader: fewer headers and futures too in ancestor lookup

- accounts/account_manager.go
- cmd/abigen/main.go
- cmd/geth/accountcmd.go
- cmd/geth/consolecmd.go
- cmd/geth/main.go
- cmd/gethrpctest/main.go
- cmd/utils/flags.go
- common/compiler/solidity.go
- common/compiler/solidity_test.go
- console/console_test.go
- core/types.go
- eth/backend.go
- eth/bind.go
- ethdb/database.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- internal/ethapi/solc.go
- miner/miner.go
- miner/worker.go
- node/config.go
- node/node.go
- node/service.go
This PR resolves some of the tech debt created by #2159.
Please see the commit descriptions for more detail about the individual changes.
Fixes #2760 
Fixes #2806, accidentally
> all: clean up tech debt left behind by the API split

- eth/fetcher/fetcher.go
Fixes https://github.com/ethereum/go-ethereum/issues/2807.
> eth/fetcher: fix a log message formatting issue

- eth/fetcher/fetcher.go
> Small typo fix (develop branch)

- README.md
Just filling a small gap in the documentation.
Please let me know if you like me to change anything.
Thanks!
> Small docker run example for main README

- p2p/nat/nat.go
> p2p/nat: fix external/internal port order in mapper

- README.md
Changed http:// to https:// on some links in README.md
> README: Changed http:// to https:// on some links

- swarm/storage/chunker.go
* Allow EOF at the end of the reader in the chunker.
* Continue reading if the chunk is not full.
> swarm: fix http API's last problems

- core/tx_pool.go
- core/tx_pool_test.go
This PR adds a few limits and allowance guarantees on the transaction pool's pending list:
* All unique accounts are guaranteed 16 slots in the pool. This should ensure that even if the pool is saturated and a ton of transactions are queued, normal users can still have a chance to include their transactions and not get pushed out by someone else.
* There's a global limit of 16K executable transactions on the pool. If the total number of transactions goes over this limit, big transacting accounts start to get equalized (i.e. drop transactions from the heavyweights until the total count is below the allowance).
* Local transactions are never evicted, ensuring that both that pools issuing thousands of txs in payouts don't lose them (i.e. they can still mine their own even in the face of tx …
> core: add global (soft) limits on the pending transactions

- cmd/geth/chaincmd.go
Extends the result text of a `geth import` operation by also printing the database compaction stats (also compacts the db after an import). This should help developing database optimizations.
```
Import done in 9m23.772190821s, compacting...
Compaction done in 56.726582346s.
Compactions
Level |   Tables   |    Size(MB)   |    Time(sec)  |    Read(MB)   |   Write(MB)
-------+------------+---------------+---------------+---------------+---------------
0   |          0 |       0.00000 |      33.75067 |       0.00000 |    2709.77516
1   |          0 |       0.00000 |     191.15939 |   14178.37611 |   14023.15792
2   |          0 |       0.00000 |     260.06293 |   18094.19571 |   18093.11371
3   |       1270 |    2553.27375 |     100.93812 |    6788.15036 |    6787.94915
```
> cmd/geth: compact and print database stats after an import

- core/blockchain.go
This PR adds some metric block processing time metric collection
> core: Add block processing time metric collection

- cmd/geth/chaincmd.go
- trie/trie.go
This PR adds a 64 bit cache miss counter to the `trie` so that we can track the number of times we load a node from the database. The counter is also printed after importing a batch of blocks from disk.
> cmd/geth, trie: track and report trie cache misses

- core/vm/opcodes.go
See #2553 
**Note: build failures are NOT due to this commit.**
> core/vm: fix GASPRICE string (resolves #2553)

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/batch.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/cache/cache.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/comparer.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_snapshot.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_transaction.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_util.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/errors.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/errors/errors.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/iterator/iter.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/journal/journal.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/key.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/opt/options.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/session.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/session_util.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage/mem_storage.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage/storage.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util.go
- Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/version.go
- internal/ethapi/api.go
- internal/web3ext/web3ext.go
This update should fix the issue where database performance degrades over time because compaction cannot keep up. See https://github.com/syndtr/goleveldb/commit/62a36c4ec8d8f7f8bbf13599cba7ca5c61b96660.
> Update goleveldb, add debug.chaindbCompact

- internal/debug/flags.go
- internal/ethapi/tracer.go
- rpc/http.go
- swarm/storage/chunker_test.go
Run `go fmt` on the source.
As a "test commit " for my 1st PR.
> internal/debug, internal/ethapi, rpc, swarm/storage: go fmt

- common/math/exp.go
- core/vm/instructions.go
> common/math, core/vm: implement fast EXP.

- accounts/abi/abi.go
- accounts/abi/abi_test.go
- accounts/abi/reflect.go
- accounts/abi/type.go
- node/node.go
solves #3119
Signed-off-by: VoR0220 rj@erisindustries.com
> accounts/abi: differentiate between static and dynamic arrays

- internal/build/pgp.go
> internal/build: call correct signer method

- cmd/geth/dao_test.go
(move https://github.com/ethereum/go-ethereum/pull/3213 to develop branch )
To setup a looped unit test function, to instead previous many functions.  With what developer can run specific function, to cover all cases in one mechanism.
Signed-off-by: xiekeyang <xiekeyang@huawei.com>
> a loop in unit test

- cmd/utils/flags.go
- core/blockchain_test.go
- core/state_processor.go
- core/types/transaction_signing.go
- core/types/transaction_signing_test.go
- params/util.go
Refactored explicit chain id checking in to the Sender deriviation method
> core, core/types: refactored tx chain id checking

- .travis.yml
- build/ci-notes.md
Note: I need to set up the key before this can be merged.
> travis.yml: upload to the real PPA

- build/env.sh
This should fix the 'make' build with Go 1.5.
> build: set GO15VENDOREXPERIMENT in env.sh

- README.md
Changed http:// to https:// on one link in README.md
> README: Changed http:// to https:// on one link

- whisper/shhapi/api.go
- whisper/shhapi/api_test.go
- whisper/whisperv5/benchmarks_test.go
- whisper/whisperv5/doc.go
- whisper/whisperv5/filter.go
- whisper/whisperv5/filter_test.go
- whisper/whisperv5/message_test.go
- whisper/whisperv5/peer_test.go
- whisper/whisperv5/topic_test.go
- whisper/whisperv5/whisper_test.go
- refactored the filtering
- fixed the filter behavior
- fixed the filter test
- added new message types for forward compatibility
> whisper: refactoring

- cmd/geth/consolecmd_test.go
- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- ethstats/ethstats.go
- les/backend.go
- mobile/geth.go
- params/version.go
`geth --ethstats "golang <3:secret@ethstats.net"`
> cmd, ethstats, les, mobile, params: native netstats

- core/blockchain_test.go
While the `tests` directory contains JSON tests for all the EIPs and transitions (which we pass), we currently don't have any go unit tests testing certain scenarios.
This PR aims to fix that by adding more EIP tests.
> core: eip unit tests

- light/state_object.go
- light/vm_env.go
fixes https://github.com/ethereum/go-ethereum/issues/3353
> light: implemented VMState.Empty()

- ethstats/ethstats.go
This PR fixes two stats annoyances:
* The previous code did a stats reporting optimization that if multiple head events are fired simultaneously, only one of them is forwarded to the stats server. Since the server does track forks, this meant that if the non-reported block became canonical, the stats server would display a big red line for us on that block since we never sent it. The new version will report all head blocks, even if multiple versions exist simultaneously.
* The second smaller annoyance was that pending transaction count was only updated when a new arrived, but not when a block was imported. This meant that if a block contained 10 txs, the pending counter didn't decrease by 10 until a new tx actually appeared.
> ethstats: don't drop concurrent head reports (mini forks)

- cmd/geth/chaincmd.go
- cmd/geth/main.go
- cmd/geth/misccmd.go
Superseeds https://github.com/ethereum/go-ethereum/pull/3251 which got very messy due to the various merge conflicts.
> cmd/geth: tidied up the source

- ethstats/ethstats.go
There is a race condition in the `ethstats.Service#loop` function. When the node is stopped the event mux is stopped which causes channels associated with subscriptions to be closed. This returns a nil value which isn't checked.
```
goroutine 122 [running]:
panic(0xc60460, 0xc43265ed90)
/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/ethstats.(*Service).loop(0xc42148ef00)
/home/bas/develop/golang/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:149 +0xb36
created by github.com/ethereum/go-ethereum/ethstats.(*Service).Start
/home/bas/develop/golang/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/ethstats/ethstats.go:87 +0x60
```
> ethstats: check if received event is valid

- cmd/utils/cmd.go
- eth/api.go
Open question: If this duplicated code should be refactored, where to? Inside Blockchain?
> cmd/utils, eth: Add gzip support for chain dump and restore

- core/tx_pool.go
The tx pool keeps track of local pending state for transaction validation. This pending state is lazy initialized by checking if the pending state is nil before use. It turns out that there is at least one case where this check was missing.
Since there appears no good reason for the lazy initialisation this PR inits the pending state when the tx pool is created and removes nil checks.
Fixes https://github.com/ethereum/go-ethereum/issues/3428
> core: init pending state in tx pool on creation

- eth/api.go
- miner/remote_agent.go
Fixes https://github.com/ethereum/go-ethereum/issues/2816
> eth, miner: verify PoW in the remote agent to notify submitter

- swarm/api/http/server.go
The swarm http server must call Size() before ServeContent().
This is needed because ServerContent uses seek-from-end and we cannot seek from end without knowing the size.
Size() determines the size of the data by reading it from the root chunk.
If the root chunk is not found the size is reported as zero and an error returned.
This PR introduces a check on the returned error. Previously we continued along as if we knew what the size was thus triggering the "seeker can't seek" error described here: https://github.com/ethereum/go-ethereum/issues/3307
This PR also changes the error message people see when calling http://localhost:8500
> swarm/http: check error returned by reader.Size

- accounts/account_manager.go
- accounts/accounts_test.go
- internal/ethapi/api.go
- mobile/accounts.go
- mobile/android_test.go
**This PR has as it's prerequisite https://github.com/ethereum/go-ethereum/pull/3455, please merge that before this one (this contains the same commits too).**
> Account management API polishes

- node/api.go
- fixes #3531
- issue proved to be trivial to fix, it was just simple missing of pointer dereference
> node: fixes pointer dereference issue in StartRPC()

- cmd/swarm/upload.go
swarm command line uploader used to build one monolithic manifest unlike the implementation in 
`swarm/api/filesystem` which instead creates a compacted trie. 
By using HTTP PUT (which calls this internal manifest builder), the command line uploader's behaviour is 
now identical.
> cmd/swarm: uploader uses HTTP PUT for directories

- core/database_util.go
`core#WriteMipmapBloom` first retrieves the existing bloom filter on a level, updates it with the new set of logs and adds it to a batch that is written when the bloom filters on all levels are updated. When called in parallel (`core.BlockChain#InsertReceiptChain`) this can cause a race condition because one of the batches can overwrite the other.
Fixes #3502 and #2370
> core: fix race condition in WriteMipmapBloom

- core/types/block.go
- eth/api.go
- miner/agent.go
- miner/remote_agent.go
> eth: accept leading zeros for nonce parameter of submitWork

- core/state_transition.go
Removal of dead code that appeard as if we had a consensus issue. This
however is not the case as the proper error catching happens in the vm
package instead.
> core: removal of dead-code

- internal/guide/guide.go
- internal/guide/guide_test.go
~~This PR depends on https://github.com/ethereum/go-ethereum/pull/3581. The test failure is caused by the missing changes.~~ merged
> internal/guide: initial test suite to ensure guide snippets run ok

- event/feed.go
This PR makes init handling a bit cleaner to reason about and also faster since a sync.Once internally uses atomics to fast track, and only resorts to mutex locking during it's first execution.
> event: use sync.Once for init for faster/cleaner locking

- swarm/storage/dbstore.go
- swarm/storage/dbstore_test.go
- swarm/storage/dpa.go
- swarm/storage/localstore.go
- swarm/storage/memstore.go
- swarm/storage/netstore.go
- swarm/storage/types.go
- swarm/swarm.go
> swarm/storage: release chunk storage after stop swarm

- .travis.yml
*This PR took me 24 builds rounds on Travis...*
Old:
New:
> travis: split Android off OSX, use native image

- cmd/wnode/main.go
- whisper/mailserver/mailserver.go
- whisper/mailserver/server_test.go
including small refactoring and bugfix
> Whisper Mailserver Tests 

- swarm/api/http/server_test.go
TL;DR; https://travis-ci.org/ethereum/go-ethereum/jobs/202558655#L337
> swarm/api/http: fix go vet issue on Go 1.8

- cmd/wnode/main.go
- whisper/whisperv5/api.go
- whisper/whisperv5/api_test.go
- whisper/whisperv5/benchmarks_test.go
- whisper/whisperv5/doc.go
- whisper/whisperv5/envelope.go
- whisper/whisperv5/filter.go
- whisper/whisperv5/filter_test.go
- whisper/whisperv5/peer_test.go
- whisper/whisperv5/whisper.go
- whisper/whisperv5/whisper_test.go
This PR prepares Whisper API for easy switch to v5.
> Whisper API fixed

- accounts/abi/bind/util.go
- accounts/keystore/account_cache.go
- accounts/keystore/watch.go
- accounts/usbwallet/ledger_wallet.go
- eth/downloader/downloader.go
- eth/downloader/modes.go
- eth/downloader/peer.go
- eth/downloader/queue.go
> eth/downloader: port over old logs from glog to log15

- accounts/url.go
- cmd/geth/chaincmd.go
- cmd/geth/main.go
- cmd/swarm/cleandb.go
- cmd/swarm/hash.go
- cmd/swarm/main.go
- cmd/swarm/manifest.go
- cmd/swarm/upload.go
- cmd/utils/cmd.go
- cmd/utils/flags.go
- eth/api.go
- eth/backend.go
- eth/bad_block.go
- eth/db_upgrade.go
- eth/downloader/downloader.go
- eth/downloader/peer.go
- eth/fetcher/fetcher.go
- eth/gasprice/gasprice.go
- eth/handler.go
- eth/peer.go
- eth/sync.go
- ethdb/database.go
Updated the remainder of logs from `cmd`, ported over `eth` and `ethdb`.
Commit 2 made some minor cleanups in ethdb.
> Logger updates 3

- swarm/network/kademlia/kademlia.go
Does this little change really already fix this issue? Or is there further scanning needed in order to close this issue? @homotopycolimit
> closes #3461

- ethstats/ethstats.go
Fixes https://github.com/ethereum/go-ethereum/issues/3797.
The current ethstats client defaulted to `wss://`, and required the user to explicitly specify `ws://` in the ethstats URL if non TLS connection was needed. This turns out to be messy with private networks and reverse proxies, where HTTPS forwarding can cause weird errors. This PR adds a fallback to the default so that if the user didn't explicitly specify `ws://` or `wss://`, the latter will be defaulted to, but the former fallen back to if the latter doesn't work. This should make ethstats configuration much more robust, especially for automatic deployment where it may not be obvious which to choose in advance.
The PR also fixes another ethstats annoyance on new private networks where prior to block 3000, ethstats seemingly …
> ethstats: try both ws:// and wss:// if none specified

- ethstats/ethstats.go
This PR fixes up the `ethstats` package a bit so it's closed in behavior to the "official" client. Namely it adds a few fields to the reported blocks that aren't used for anything, except some weird comparison within the stats page.
It also fixes the history requests/responses, by actually sending the **reverse** of what the stats server requested. Sending it in the actual order requested irreversibly blews the block history inside ethstats?!
A few other cleanups were also added, such as logging to see what's being sent to the server and received form there, as well as I dumped my custom JSON streams to the suggested methods from `websockets`. The end result is the same, just figured it's a bit cleaner.
> ethstats: cleanups, trace logs and "fix" history responses

- rpc/server.go
Fixes https://github.com/ethereum/go-ethereum/issues/3810
Currently when on an RPC channel we reached the end of the stream, we closed down the connection immediately, even if requests were actively being served. This is a problem if scripts interact with geth which send it a few requests and close the input stream, while waiting for replies on the output stream.
This PR ensures that in the case of reaching the end of the stream (EOF), all pending requests are honored first before tearing the connection down. The weird string `"EOF"` comparison is done because the underlying readers send some wrapped errors, not the standard `error`. I didn't want to refactor the entire RPC package to add this lowly fix.
Note, tearing down the connection (as we do currently) won't stop those requests from …
> rpc: honor pending requests before tearing conn down

- core/types/transaction.go
> core/types: ensure all EIP155 signer fields are set by deriveSigner

- build/ci.go
Fixes #3792 by stripping debug symbols.
> build: work around cgo linker issue on macOS 10.12.4

- cmd/wnode/main.go
- whisper/mailserver/mailserver.go
- whisper/mailserver/server_test.go
- whisper/whisperv5/api.go
- whisper/whisperv5/api_test.go
- whisper/whisperv5/doc.go
- whisper/whisperv5/envelope.go
- whisper/whisperv5/filter.go
- whisper/whisperv5/filter_test.go
- whisper/whisperv5/message.go
- whisper/whisperv5/peer.go
- whisper/whisperv5/peer_test.go
- whisper/whisperv5/whisper.go
- whisper/whisperv5/whisper_test.go
> whisper: big refactoring

- cmd/swarm/main.go
- `swarm` command accepts `--bzzacount` flag, but password must be provided interactively by typing
- `geth` command has the `--password` flag (where one can provide password file to be used to unlock account in a non-interactive mode)
- this PR adds `--password` flag to `swarm` command allowing users to start swarm node in completely non-interactive manner
**Note:** For consistency, code mimics the same in `cmd/geth` (it seems it already has been derived from there anyway).
> cmd/swarm: add feature to specify account password non-interactively

- build/ci.go
Fixes https://github.com/ethereum/go-ethereum/issues/14314
> build: support packaging for Ubuntu Zesty

- cmd/swarm/main.go
- swarm/api/api.go
- swarm/api/http/server_test.go
- swarm/swarm.go
> swarm: better name resolver handling 

- cmd/utils/flags.go
- cmd/wnode/main.go
- internal/web3ext/web3ext.go
- mobile/geth.go
- whisper/whisperv5/api.go
- whisper/whisperv5/api_test.go
This PR contains a minor refactoring and completes switching to v5.
> whisper: switch to v5 

- console/bridge.go
With Go 1.7, encoding/json marshals float64 using scientific
notation ("10e+6"), but Go's int and *big.Int decoders don't accept such
numbers. This change disables use of float64 to avoid the problem.
> console: avoid float64 when remarshaling parameters

- README.md
> README: add config to genesis.json

- core/blockchain.go
- core/blocks.go
- core/chain_makers.go
- core/database_util.go
- core/events.go
- core/fees.go
- core/genesis.go
- core/headerchain.go
- core/helper_test.go
- core/state_transition.go
- core/tx_pool.go
- core/vm/interpreter.go
This PR supersedes https://github.com/ethereum/go-ethereum/pull/14455 by having it based on current master and fixing the issues raised during review.
> core: fix various golint warnings and errors

- ethstats/ethstats.go
The main purpose is to ensure stats traffic is fixed and does not depend on block size.
> ethstats: don't report transaction content, only hash

- cmd/swarm/upload.go
The error returned by `client.Upload` was previously being ignored due to becoming out of scope outside the if statement.
This has been fixed by instead defining a function which returns the hash and error (rather than trying to set the hash in each branch of the if statement).
> cmd/swarm: Fix error handling in 'swarm up'

- consensus/clique/clique.go
- consensus/clique/snapshot.go
Choose a meaningful vote in clique Prepare()
> consensus/clique: choose valid votes

- core/tx_pool.go
- core/tx_pool_test.go
Fixes https://github.com/ethereum/go-ethereum/issues/14935.
This PR fixes three race issues:
* The transaction pool test suite used `pool.stats` instead of `pool.Stats` to check the internal counters. The former however did not lock the pool and thus clashed with the pool's background maintenance processes. Fixed by switching the test to `pool.Stats`, which obtains the lock first.
* Similarly the transaction tests used `pool.resetState` to occasionally force the pool to reorganize its transactions (simulating a new block arrival). This clashed the same way with the background processing. The fix is adding a `pool.lockedReset` method which first obtains the lock and only then calls reset. This method is private as outside entities should not be able to reset the pool.
* Lastly, the pool …
> core: fix txpool journal and test races

- eth/downloader/downloader_test.go
Straightforward fix for https://github.com/ethereum/go-ethereum/issues/14936 race.
Add the mutex and use getter/setter (`delay()/setDelay()`) for accessing delay field in downloadTesterPeer.
> eth/downloader: fix race in downloadTesterPeer

- README.md
> README: add missing full stop

- Dockerfile
This PR enables multi-stage builds for our docker images, which essentially means that we can use one base container to build Geth, and a final image to deploy it.
This is good because we can reuse build steps (i.e. install Go, gcc, etc) between builds, so building many times over locally should be a lot faster, whilst the final build image is kept as small as possible. This should be supported by docker hub (https://github.com/docker/hub-feedback/issues/1039), so distributing our bundles will get faster and better.
The second nice benefit is that we can use `golang:1.9-alpine` as our base builder container instead of plain `alpine`, which means we can finally bump dockerized Geth from Go 1.7.3 to 1.9.0.
> Dockerfile: multi-stage builds, Go 1.9

- core/asm/lexer.go
should use strings.ContainsRune(valid, l.next()) instead
> should use strings.ContainsRune(valid, l.next()) instead

- common/types.go
Fixes https://github.com/ethereum/go-ethereum/issues/15004
> common/types: Fix documentation, fix #15004

- internal/debug/api.go
- internal/web3ext/web3ext.go
I need this to debug memory usage issues.
> internal/debug: add debug_freeOSMemory

- eth/downloader/peer.go
- eth/downloader/statesync.go
Previously when the state sync was part of the downloader queue, peer drops resulted in successful cancellation of pending state sync tasks too. However with the state sync rewrite, the state download tasks were not cancelled on peer drop, rather relying on timeouts to detect such scenarios.
Apparently there are two issues with this approach:
* If a peer is dropped for not responding to an arbitrary non-state-download request (or simply disconnects remotely), the state task will not be rescheduled until it times out. This might be up to 2 minutes for slow connections. That can have a seriously adverse effect on performance.
* If the peer reconnects in between, it will be assigned a new download task, and the old one scheduled for discarding (emulating a timeout on it). This can quite …
> eth/downloader: track peer drops and deassign state sync tasks

- interfaces.go
interfaces: fixed some typos in interfaces.go
> interfaces: fixed some typos in interfaces.go

- accounts/abi/bind/backends/simulated.go
Added function in SimulatedBackend to allow testing functions which use block timestamps.
Current Action : each commit advances clock by 10 seconds
New Action : JumpTimeInSeconds(skip int64) adds `skip` seconds to the clock for next commit regardless of any Tx to commit or not.
> accounts/abi/backends: add AdjustTime

- miner/agent.go
We may start `CpuAgent` fail if we call stop() and start() quickly. The original go routine may not be stopped yet, so the following `start()` will be failed because `isMining` is still `1`. Refer to remote_agent.go, and update `isMining` to `0` in `Stop()`.
> miner: avoid starting agent fail

- eth/api.go
- eth/bind.go
- internal/ethapi/api.go
Fixed typo in comments from Etheruem to Ethereum
> eth, internal: Fix typo

- internal/ethapi/api.go
> internal: fix repeat code

- accounts/usbwallet/hub.go
The USB HID library on macOS does not support setting the interface number for different endpoints on the same device, returning `-1` for all instead. This is a problem on the Trezor as it exposes multiple endpoints, only one for the actual wallet. The current code wrongly assumed that the interface IDs work, and only ever connected numbed `0`. The result was that neither the Trezor nor the Ledger would connect on macOS.
Although macOS does handle the USB HID usage page IDs correctly for different endpoints, Linux does not, returning `0` for all instead. This is again a problem on the Trezor :P 
This PR fixes the issue by pattern matching on both the USB HID interface IDs (looking for number 0 for both the Ledger and the Trezor) and also the USB HID usage page IDs (looking for `0xff00` on …
> accounts/usbwallet: handle bad interface number on macOS

- vendor/github.com/peterh/liner/common.go
- vendor/github.com/peterh/liner/input.go
- vendor/github.com/peterh/liner/line.go
- vendor/vendor.json
Supersedes https://github.com/ethereum/go-ethereum/pull/15247 as the author of that PR constantly force pushed out my fixes to the file permissions.
> vendor: update liner to fix docker and mips bugs

- mobile/bind.go
Fix also confirmed to work by Cameron Voell @cameronvoell here: https://gitter.im/ethereum/light-client?at=59ceb3d3b59d55b82353b83c
> mobile: Fix Contract ABI Error - closes #14363

- eth/backend.go
> Fixed typo: s/singer/signer/

- core/vm/interpreter.go
Read-only enforcement depends on the stack being valid. Validate stack first, and only afterwards check for write violation.
> core/vm: check opcode stack before readonly enforcement

- build/ci.go
Fixes https://github.com/ethereum/go-ethereum/issues/15339
> build: start shipping Ubuntu Artful Aardvark binaries

- les/serverpool.go
> les: fix channels assignment data race

- internal/ethapi/api.go
Changed output to clarify gas calculation in txpool.inspect
#15491
> internal/ethapi: Changed output in txpool.inspect

- .github/CODEOWNERS
> .github: add CODEOWNERS

- whisper/whisperv6/envelope.go
This is a very, very simple PR that is in preparation for other PRs. In v6, there is no longer an `AESNonce` field in the envelope, so just rename `EnvNonce` to `Nonce`.
> whisper: rename EnvNonce to Nonce in the v6 Envelope

- params/bootnodes.go
Courtesy of @MihaiAlisie @kenshyx and https://github.com/AkashaProject.
> params: add Rinkeby bootnode from Akasha

- core/blockchain.go
- p2p/discv5/database.go
> core, p2p/discv5: fix leaked goroutines

- ethstats/ethstats.go
> ethstats: Fix ethstats reporting while syncing

- whisper/whisperv6/envelope.go
PoW parameter may contain zero as a legitimate value, which means that PoW is not required. Negative value indicates that target is not set, and Seal function should only use WorkTime param. In this case Seal just runs for a specified time and uses the best PoW it can find.
> whisper: Seal function fixed

- node/node.go
- rpc/http.go
> node, rpc: fix linter issues

- p2p/rlpx.go
- p2p/rlpx_test.go
This PR adds a commit from @zelig from https://github.com/ethersphere/go-ethereum/pull/119/commits/60d50fcc5b2636cd2d180302e9cbbcd51f15effd
It also fixes the rlpx_test.go tests, which until now were using `net.Pipe` to check for the DiscReason message. `net.Pipe` has been switched with `tcpPipe` so that we make sure that DiscReason is received in normal/production setting.
TODO:
> p2p: don't send DiscReason to disconnected peer when using net.Pipe

- whisper/whisperv6/peer.go
`go test -race` reveals a race condition when running the e2e tests in https://github.com/status-im/status-go/tree/feature/geth-1.8.0. It is caused by the indeterministic access to both `peer.fullNode` and `peer.bloomFilter`. This PR adds the required mutex to protect access to both fields.
```
Read at 0x00c4204dadc0 by goroutine 357:
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/whisper/whisperv6.bloomFilterMatch()
/home/pedro/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/whisper/whisperv6/whisper.go:1187 +0x72
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/whisper/whisperv6.(*Peer).bloomMatch()
/home/pedro/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go- …
```
> Fix race condition in whisperv6/peer.go

- swarm/metrics/flags.go
At the moment if a user enables metrics on swarm with the `--metrics` flag, swarm will automatically try to push metrics to the default configuration for the external metrics database (localhost:8086).
This PR introduces an `--metrics.influxdb.export` boolean flag, which by default is `false`, and one has to explicitly set in case they want to push their node's stats to an external metrics database.
> swarm/metrics: introduce metrics export flag

- cmd/wnode/main.go
all messages are saved if savedir param is given
> whisper: wnode refactored

- cmd/faucet/faucet.go
Currently the faucet updates its state whenever a new head event is fired. This unfortunately is very bad during a resync because it attempts to retrieve its balance/nonce/whatnot for every single header imported. Since old state is not available in the network, the issue gets even worse as there's a 5 second timeout before the retrieval fails. The end result is that the faucet can in theory import 1 header / 5 seconds. In practice sync just blows up with timeouts and whatnot.
This PR puts the state update (triggered by a new head) on a background thread so it doesn't block the event subsystem. Also it only ever runs a single state update, so if a state is being updates while a new header arrives, the new head event is simply skipped and we'll update on the next even instead.
> cmd/faucet: update state in background, skip when busy

- .github/CODEOWNERS
- light/postprocess.go
- add new CHTs for mainnet and ropsten
- add code owner for packages les, light
> light: new CHTs

- consensus/ethash/consensus.go
> consensus/ethash: fixed typo

- swarm/storage/chunker_test.go
> swarm/storage: disable TreeChunker test while it is flaky

- cmd/wnode/main.go
- whisper/whisperv6/envelope.go
- fixed error caused by the use of uninitialized variable shh
- fixed message saving (envelopes instead of messages)
- fixed filereader mode
- fixed user interface
> whisper: final refactoring

- eth/fetcher/fetcher.go
> eth: Fixed typo

- .github/CODEOWNERS
Add @gballet and @gluk256 to the CODEOWNER file
> whisper: Notify Vlad and Guillaume of whisper PRs

- core/evm.go
- core/headerchain.go
- core/vm/instructions.go
- core/vm/intpool.go
Minor EVM speed optimizations and memory allocation reductions. Bumps snail tracer benchmark performance by about 5%, mod/div ops by 10%.
> core: minor evm polishes and optimizations

- cmd/geth/chaincmd.go
- cmd/geth/main.go
- cmd/utils/cmd.go
- ethdb/database.go
In this pull request, implement two geth command to export/import preimage data in json format. 
More detail is in #16124.
@holiman PTAL
> cmd: implement preimage dump and import cmds

- whisper/whisperv6/api.go
- whisper/whisperv6/api_test.go
Fixes #16271. What was appeneded was a pointer to
an object that changes during the iteration.
> whisper: fix issue in topic list copy

- .travis.yml
This is supposed to fix the FTP upload issue according to travis-ci/travis-ci#9391.
> travis.yml: remove sudo requirement for PPA and Azure purge builders

- README.md
> Updated Readme.md with small change

- build/ci.go
> travis: Add -X and -e flags to get debug output for getting more information on #16433

- core/state/statedb.go
Fix the edgecase reported here: https://github.com/ethereum/go-ethereum/pull/16485#issuecomment-380438527 .
> core/state: fix ripemd-cornercase in Copy

- eth/downloader/downloader.go
Currently, we spawn 5 fetcher goroutines to fetch the blockchain data separately. But when we terminate the downloader(e.g. Ctrl+C), the downloader may terminates itself without waiting all in-flight fetcher goroutines to exit.
So we can find sometimes state nodes are failed to write into database because leveldb has already been closed.
In this pull request, i move the `sync.WaitGroup` variable from the `spawn` function to downloader internal to make sure all fetchers have exited when we call `Cancel`.
> eth/downloader: wait all fetcher goroutines to exit before terminating

- Dockerfile
- Dockerfile.alltools
Reverts https://github.com/ethereum/go-ethereum/pull/16052/files
> Dockerfile: revert the user change PR that broke all APIs

- whisper/shhclient/client.go
- whisper/whisperv5/api.go
- whisper/whisperv5/doc.go
- whisper/whisperv5/message.go
- whisper/whisperv5/peer.go
- whisper/whisperv5/peer_test.go
- whisper/whisperv5/topic.go
- whisper/whisperv5/whisper.go
Specifically naming conflicts and comment formatting for documentation
> whisper/*: Golint fixes in whisper packages

- mobile/types.go
Add the lost GetStatus method for Receipt
> mobile: Add GetStatus Method to Receipt

- .travis.yml
mainly want to check out if travis is happy with this - when it is let's merge it after we have working uploads to maven-central again
> mobile: Use ndk16b - closes #16549

- light/postprocess.go
new CHTs for mainnet and ropsten
> light: new CHTs for mainnet and ropsten

- metrics/metrics.go
Previously created a pull request, fixed line at the end
@karalabe 
@holiman
> metrics: removed repetitive calculations

- internal/ethapi/api.go
Fixes https://github.com/ethereum/go-ethereum/issues/16940.
When retrieving the pending accounts for our particular node, we did an account lookup for every single transaction. On mainnet that's `4K txs x num_accounts`. For exchanges, that means an insanely high number, which is completely pointless.
This PR first creates an account lookup table, and then uses that to see if a transaction is local or not. This reduces the runtime complexity of the `eth.pendingTransactions` method from `O(txs * accounts) to O(txs + accounts)`.
> internal/ethapi: reduce pendingTransactions to O(txs+accs) from O(txs*accs)

- core/asm/lexer.go
core/asm/lexer: correct comments typo
> core/asm/lexer: correct comments typo

- whisper/whisperv5/peer_test.go
- whisper/whisperv6/peer_test.go
Improves test portability for #15685 by resolving `127.0.0.1:0` to get a random free port instead of the hard coded one => now the test works if you have a running node on the same interface already.
>  #15685 made peer_test.go more portable by using random free port instead of hardcoded port 30303

- mobile/ethereum.go
**contact** log filtering -> **contract** log filtering
> mobile: correct comment typo in ethereum.go

- ethstats/ethstats.go
spell correction from `repors` to `reports`
> ethstats: ethstats.go comment minor correction

- downloads/index.html
Fixing an unexpected end of </tbody>
> downloads: update index.html

- p2p/peer.go
p2p/peer: correct comments typo
> p2p: correct comments typo

- consensus/clique/snapshot.go
Using golang sorting by function to sort the signers list in the clique PoA consensus engine
> consensus/clique: replace bubble sort by golang stable sort

- core/tx_pool.go
line133: fix "Minimum" to "Maximum".
> core: fixed typo

- core/vm/evm.go
> Update a comment word

- miner/agent.go
- miner/worker.go
> WIP miner: seperate state, receipts for different mining work

- p2p/server.go
This is a follow-up PR that fixes a minor concurrency issue from https://github.com/ethereum/go-ethereum/pull/16333 by making (c *conn) set really atomic.
> p2p: use safe atomic operations when changing connFlags

- swarm/api/http/server_test.go
Implements all unit tests described in https://github.com/ethersphere/go-ethereum/issues/779
> Swarm http unittests

- cmd/swarm/config.go
This PR addresses https://github.com/ethereum/go-ethereum/issues/16587
> cmd/swarm: remove shadow err

- cmd/puppeth/wizard_netstats.go
The puppeth network stats gathering code currently crashes if it cannot connect to a remote machine due to accessing a field before reconnection is attempted. This PR fixes the access so we only retrieve the IP address if we actually have a connection to retrieve it from.
The PR also modifies the stats reporting a bit so that stat gathering failures are also included into the table (seems to be a regression, we definitely had the errors listed before).
Old behavior:
```
ERROR[08-16|09:24:21.405] Previous server unreachable              server=example.com err="dial tcp 1.2.3.4:22: connect: no route to host"
INFO [08-16|09:24:22.850] Starting remote server health-check      server=example.com
[signal SIGSEGV: …
```
> cmd/puppeth: fix nil panic on disconnected stats gathering

- accounts/accounts.go
accounts: Line 109 had a typo of 'o' instead of 'to'
> fixed 'to' typo

- p2p/protocol.go
> p2p: fix typo

- swarm/storage/ldbstore.go
This PR is updating the `swarm db cleanup` cmd to remove chunks bigger than our `chunk.DefaultSize`, which is currently 4KB.
> swarm/storage: cleanup task - remove bigger chunks than DefaultSize

- console/console.go
- console/console_test.go
- console/prompter.go
- promt => prompt
- displaing => displaying
- parentesis => parenthesis
> console: fixed comment typo

- core/types/transaction.go
Fix docs in Protected function
> core/types: Fix Protected docs

- eth/api_tracer.go
A bug received via bug bounty, credits to Chen Nan.
> Ensure from < to when tracing chain

- swarm/network/simulation/simulation_test.go
> swarm/network/simulation: Fix typo

- consensus/clique/clique.go
- consensus/clique/snapshot_test.go
- consensus/consensus.go
- consensus/ethash/consensus.go
- consensus/ethash/ethash_test.go
- consensus/ethash/sealer.go
- consensus/ethash/sealer_test.go
- core/types/block.go
- miner/worker.go
- mobile/types.go
> miner: commit state which is relative with sealing result

- signer/storage/aes_gcm_storage.go
> signer/storage: fix typo

- cmd/faucet/faucet.go
delete '\n" from ioutil.ReadFile
> cmd/faucet: fixed #17557, delete tail "\n" from pass variable

- .github/no-response.yml
The template was not grammatical to me as it was. I have edited the language a tiny bit to make the close comment more clear and less abrasive.
> docs: Slight edits to No Response template

- core/state_processor.go
- core: fix typo in comment
Signed-off-by: Hyung-Kyu Choi <hyungkyu.choi@gmail.com>
> core: fix typo in comment

- cmd/evm/disasm.go
- common/bytes.go
- core/chain_indexer.go
- core/types/bloom9.go
- eth/tracers/tracer.go
- p2p/discover/table.go
- p2p/discv5/table.go
- swarm/api/http/server_test.go
- swarm/pss/pss.go
- swarm/storage/ldbstore.go
- swarm/storage/ldbstore_test.go
- swarm/storage/types.go
- whisper/whisperv5/filter_test.go
- whisper/whisperv6/filter_test.go
Found using https://go-critic.github.io/overview#unslice-ref
> all: simplify s[:] to s where s is a slice

- swarm/network/fetcher.go
Adjust the severity of fethcer log message.
> swarm/network: downgrade fetcher unable to request log message severity

- consensus/clique/clique.go
> consensus: hide no transaction error

- cmd/puppeth/wizard_dashboard.go
- eth/api_tracer.go
- swarm/network/simulation/simulation.go
- swarm/network/stream/peer.go
- swarm/pot/doc.go
- promt => prompt
- requestd => requested
- disctance => distance
- funcional => functional
- quiting => quitting
- cancelation => cancellation
> fixed comment typo

- les/retrieve.go
This PR fixes stateRequesting() behavior in the retriever state machine.
It is always assumed that tryRequest is called before entering stateRequesting and an rpSent event will occur. If ev.peer != nil then we stay in requesting state and assume that either a delivery or a soft timeout event will follow. The existing implementation did not handle rpDeliveredInvalid though in which case it stayed in stateRequesting while no further event was happening in relation to that request, resulting in a deadlock. This PR handles rpDeliveredInvalid by starting a new request if the previous one was the one resulting in the bad reply.
>  les: fix invalid delivery handling in retriever

- build/ci-notes.md
- build/deb/ethereum-swarm/deb.control
- build/deb/ethereum-swarm/deb.rules
- build/deb/ethereum/deb.control
- build/deb/ethereum/deb.rules
TL;DR https://twitter.com/mwhudson/status/1043047729054838784
CC @eosclassicteam
> build: revert launchpad PPAs to Go 1.10

- swarm/network/stream/messages.go
- swarm/network/stream/streamer_test.go
ethersphere/go-ethereum/issues/927
> swarm/network/stream: fix DoS invalid offered hashes length

- swarm/network/fetcher.go
- swarm/network/fetcher_test.go
- swarm/network/stream/delivery.go
- swarm/network/stream/stream.go
- swarm/storage/mru/testutil.go
- swarm/storage/netstore.go
- swarm/storage/netstore_test.go
Related PR and discussion: https://github.com/ethersphere/go-ethereum/pull/941
> swarm: prevent forever running retrieve request loops

- cmd/swarm/config.go
- cmd/swarm/upload.go
Closes https://github.com/ethersphere/go-ethereum/pull/948
> cmd/swarm: use expandPath for swarm cli path parameters

- cmd/swarm/access.go
- swarm/storage/mru/lookup/epoch_test.go
- swarm/storage/mru/lookup/lookup_test.go
- swarm/storage/mru/query.go
This PR addresses https://github.com/ethersphere/go-ethereum/issues/952
> cmd/swarm: trim new lines from files

- params/config.go
To-do: Enable constantinople on rinkeby testnet also 
cc @karalabe @holiman
> Enable constantinople on Ropsten testnet

- swarm/storage/localstore.go
This PR is fixing up the migration that should clean up invalid chunks.
> swarm/storage: correctly determine chunks to be cleaned

- rpc/subscription.go
- rpc/subscription_test.go
Notifier tracks whether subscription are 'active'. A subscription
becomes active when the subscription ID has been sent to the client. If
the client sends notifications in the request handler before the
subscription becomes active they are dropped. The tests tried to work
around this problem by always waiting 5s before sending the first
notification.
Fix it by buffering notifications until the subscription becomes active.
This speeds up all subscription tests.
Also fix TestSubscriptionMultipleNamespaces to wait for three messages
instead of six. The test now finishes just after all notifications have
been received and doesn't hit the 30s timeout anymore.
Part of #17854
> rpc: fix subscription corner case and speed up tests

- rpc/client.go
- rpc/client_test.go
- rpc/stdio.go
> rpc: fix client shutdown hang when Close races with Unsubscribe

- swarm/api/http/server.go
- swarm/network/protocol_test.go
- swarm/pot/address.go
- swarm/pss/client/client_test.go
- swarm/pss/pss_test.go
- swarm/pss/types.go
- swarm/storage/common_test.go
- swarm/storage/feed/handler_test.go
- swarm/storage/ldbstore.go
- swarm/storage/types.go
Those that were identified by code inspection tool.
> swarm: clean up unused private types and functions

- cmd/swarm/swarm-smoke/feed_upload_and_sync.go
Found two places that do not pass loop variables into the func block which could cause issues.
> cmd/swarm/swarm-smoke: fix issue that loop variable capture in func

- event/event_test.go
- event/filter/generic_filter.go
1.remove unnecessary local variable
2.remove unused function parameter
> event: some code refactor

- cmd/utils/cmd.go
- core/blockchain.go
- core/rawdb/accessors_metadata.go
- core/rawdb/schema.go
1. remove unused parameter for WritePreimages func
2. modify a spelling mistake
> rawdb: remove unused parameter for WritePreimages func

- .github/CODEOWNERS
replace tabs by spaces in the code owners file
> all: format code owners file

- rpc/client_example_test.go
> rpc: fix typo

- trie/iterator.go
- trie/proof.go
> trie: return hasher to pool

- swarm/api/http/middleware.go
This PR addresses a change in the HTTP package that will allow monitoring to assert time per HTTP request.
fixes https://github.com/ethersphere/go-ethereum/issues/996
> swarm/api/http: change request served msg log level

- vendor/github.com/syndtr/goleveldb/leveldb/cache/cache.go
- vendor/github.com/syndtr/goleveldb/leveldb/comparer/bytes_comparer.go
- vendor/github.com/syndtr/goleveldb/leveldb/comparer/comparer.go
- vendor/github.com/syndtr/goleveldb/leveldb/db.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go
- vendor/github.com/syndtr/goleveldb/leveldb/db_util.go
- vendor/github.com/syndtr/goleveldb/leveldb/iterator/iter.go
- vendor/github.com/syndtr/goleveldb/leveldb/opt/options.go
- vendor/github.com/syndtr/goleveldb/leveldb/session_util.go
- vendor/github.com/syndtr/goleveldb/leveldb/table.go
- vendor/vendor.json
This PR updates leveldb to use the most recent version. 
Ref https://github.com/ethereum/go-ethereum/issues/18181
> vendor: update leveldb

- README.md
Changed http:// to https:// on JSON-RPC link in README.md
> Changed http:// to https:// on JSON-RPC link

- whisper/whisperv6/api_test.go
- whisper/whisperv6/whisper.go
Remove duplicated code for whisperv6 package.
> whisperv6: remove duplicated code

- accounts/usbwallet/ledger.go
Check returned error in case there is some error happening when doing hex decoding
> usbwallet: check returned error when decoding hexstr

- core/tx_cacher.go
This is just a comment word misspelled
> core/tx_cacher: Small comment error

- .github/CODEOWNERS
I always miss changes to that dir, so I want to make sure that I'm notified.
> .github: add @gballet as code owner of accounts/abi

- core/tx_pool.go
- core/tx_pool_test.go
https://github.com/ethereum/go-ethereum/pull/17178#issuecomment-405289201
> core: sanitize more TxPoolConfig fields

- build/update-license.go
update-license.go file need license comment.
> build: add LGPL license at update-license.go

- vendor/github.com/mattn/go-isatty/isatty_linux_ppc64x.go
- vendor/github.com/mattn/go-isatty/isatty_others.go
fixed regression mistake by https://github.com/ethereum/go-ethereum/pull/17740
reported by @mksully22
> vendor: go-isatty - add missing files

- cmd/puppeth/genesis.go
This PR to fix small issue on #18343
> cmd/puppeth: fix panic error when export aleth genesis wo/ precompile-addresses

- swarm/storage/mock/test/test.go
This PR addresses one of testing issues in https://github.com/ethersphere/go-ethereum/issues/1055.
`swarm/storage/mock/test/test.go:199:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
`
> swarm: fix T.Fatal inside a goroutine in storage/mock/test

- cmd/swarm/swarm-snapshot/create_test.go
fixes https://github.com/ethereum/go-ethereum/issues/18473
> cmd/swarm/swarm-snapshot: disable tests on windows

- swarm/network/simulation/kademlia_test.go
- swarm/network/simulations/overlay_test.go
- swarm/network/stream/visualized_snapshot_sync_sim_test.go
closes https://github.com/ethersphere/go-ethereum/issues/994
> swarm/network: unskip tests previously skipped due to suggestPeer issues

- swarm/pss/pss.go
fixes https://github.com/ethersphere/go-ethereum/issues/1116
clone of https://github.com/ethersphere/go-ethereum/pull/1137
> swarm/pss: fixing race condition

- swarm/pss/notify/notify_test.go
TestStart failed when all tests were run with race detection.
Simplest way to reproduce:
`go test -race -count 1 -run TestStart ./swarm/pss/notify`
The handler passed to `ctrlClient.Subscribe` is run in a goroutine,
started in `p2p.(*Peer).startProtocols()`. There were 2 problems/races
cased by the handler closure:
1. `t.Fatalf` was called from a goroutine
2. `updateMsg` passed to the handler (reda) was later modified in the
main thread (write)
fixes ethersphere/go-ethereum#1158
> swarm/pss: fix data race in notify_test.go (TestStart)

- swarm/pss/pss.go
topicHandlerCaps had concurrent read and write access without any
synchronisation primitive.
Failing test was:
go test -race -count 1 -run TestProtocol ./swarm/pss
fixes ethersphere/go-ethereum#1157
> swarm/pss: fix data race on topicHandlerCaps map

- eth/fetcher/fetcher.go
> eth/fetcher: blockFilter is not used anymore

- interfaces.go
Please see https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
> all: fixed FilterQuery comment in accordance with the JSON-RPC document

- trie/database.go
> trie/database: add a missing unlock

- vendor/github.com/peterh/liner/fallbackinput.go
- vendor/github.com/peterh/liner/go.mod
- vendor/github.com/peterh/liner/go.sum
- vendor/github.com/peterh/liner/input.go
- vendor/github.com/peterh/liner/input_windows.go
- vendor/github.com/peterh/liner/line.go
- vendor/github.com/peterh/liner/output.go
- vendor/github.com/peterh/liner/output_windows.go
- vendor/github.com/peterh/liner/width.go
- vendor/vendor.json
> vendor: update github.com/peterh/liner

- console/console.go
- internal/jsre/jsre.go
- internal/web3ext/web3ext.go
> console, internal/*: enforce mixed caps variable names

- trie/encoding.go
- trie/trie_test.go
Fixes an error in trie decoding. 
The flaw was found by Lukasz Matczak
> trie: fix error in node decoding

- .travis.yml
Fix https://travis-ci.org/ethereum/go-ethereum/jobs/494736871#L599
> travis.yml: add launchpad SSH public key

- core/vm/evm.go
reference: https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L215
keep annotation style consistent
> core/vm: update annotation

- accounts/accounts.go
- accounts/keystore/wallet.go
Fix a couple typos that got created during the `SignData` merge
> Fix a couple typos that got created during #17789

- cmd/swarm/config.go
- cmd/swarm/config_test.go
- cmd/swarm/flags.go
- cmd/swarm/main.go
- cmd/swarm/upload.go
- swarm/api/act.go
- swarm/api/api.go
- swarm/fuse/swarmfs.go
- swarm/fuse/swarmfs_unix.go
- swarm/network/stream/peer.go
- swarm/storage/ldbstore_test.go
- swarm/swarm.go
> cmd, swarm: enforce mixed caps variable names

- swarm/storage/localstore/localstore_test.go
This PR sets a different `now` function in tests when running on windows to ensure that the order of uploaded or accessed chunks is the same as in database indexes. This is the smallest required change, any different solution would require changing the testing approach. 
Swarm PR: https://github.com/ethersphere/go-ethereum/pull/1262
fixes: https://github.com/ethersphere/go-ethereum/issues/1230
> swarm/storage/localstore: fix tests for windows os

- swarm/storage/localstore/gc_test.go
This PR addresses the data race discovered on Travis with TestDB_collectGarbageWorker test.
```
--- FAIL: TestDB_collectGarbageWorker (5.17s)
```
After the Close method timeout of 5s timeout, collect garbage worker goroutine may still be active resulting a data race on testHookCollectGarbage variable. This change prevents that data race by correctly ordering the database close and testHookCollectGarbage reset defers, as they are in other tests in this package.
I was not able to reproduce this data race locally unless with simulating a delay with deliberate sleeps in collect garbage worker goroutine.
```
=== RUN   TestDB_collectGarbageWorker
=== RUN   TestDB_collectGarbageWorker/pull_index_count
=== RUN   TestDB_collectGarbageWorker/gc_index_count
=== RUN …
```
> swarm/storage/localstore: fix testDB_collectGarbageWorker data race

- signer/core/api.go
> clef: fix erroneous api version

- cmd/swarm/swarm-smoke/upload_and_sync.go
- swarm/network/fetcher.go
- swarm/network/stream/delivery.go
- swarm/network/stream/peer.go
- swarm/storage/netstore.go
Addresses partly https://github.com/ethersphere/go-ethereum/issues/1292
> swarm: tracing improvements

- ethdb/leveldb/leveldb.go
- ethdb/memorydb/memorydb.go
- trie/proof_test.go
- trie/trie_test.go
Removing some package stutter after @fjl's previous request to split the key-value stores into multiple packages.
> ethdb: tiny API tidy-up from the database rework pr

- vendor/github.com/syndtr/goleveldb/leveldb/session.go
- vendor/github.com/syndtr/goleveldb/leveldb/session_compaction.go
- vendor/github.com/syndtr/goleveldb/leveldb/session_util.go
- vendor/github.com/syndtr/goleveldb/leveldb/table.go
- vendor/github.com/syndtr/goleveldb/leveldb/version.go
- vendor/vendor.json
This PR includes two leveldb optimizations which has been merged in the upstream:
* https://github.com/syndtr/goleveldb/pull/268
* https://github.com/syndtr/goleveldb/pull/270
> vendor: udpate leveldb upstream

- core/blockchain.go
This PR tries to fix up the trie metrics reporting once again. The problematic issue with collecting all the metrics and reporting everything at the end is that certain trie operations (hashing in particular) is split across multiple phases (processing state root pre-byzanium does hashing, validation post byzantium does hashing). This PR changes the reporting so all metrics are reported the moment they are "completed", to avoid having to declare many many partial metrics and report all at the end.
> core: 3rd try on splitting the trie metrics correctly

- .travis.yml
- appveyor.yml
https://golang.org/doc/devel/release.html#go1.12.minor
> appveyor.yml: Upgrade to go1.12.2

- appveyor.yml
https://golang.org/doc/devel/release.html#go1.12.minor
```
find -type f -exec sed -i 's/go1.12.2/go1.12.3/g' {} \;
```
> appveyor.yml: Upgraded to Go 1.12.3

- vendor/github.com/gballet/go-libpcsclite/README.md
- vendor/github.com/gballet/go-libpcsclite/doc.go
- vendor/github.com/gballet/go-libpcsclite/error.go
- vendor/github.com/gballet/go-libpcsclite/winscard.go
- vendor/vendor.json
some trave was left out in the vendored go-libpcsclite. Remove it.
> vendor: remove leftover trace

- accounts/scwallet/README.md
@ligi as promised, I checked that 2.2.1 worked and have updated the documentation accordingly. This closes #19418
> accounts/scwallet: Update README for v2.2.1 support

- cmd/clef/main.go
This PR updates the warning text that is printed when starting clef
> clef: update warning-text

- appveyor.yml
https://golang.org/doc/devel/release.html#go1.12.minor
```
find -type f -exec sed -i 's/go1.12.3/go1.12.4/g' {} \;
```
> appveyor.yml: Upgraded to Go 1.12.4

- docs/_whisper/Whisper-js-example.md
The example page wasn't helpful. Describe how the app is built.
> whisper: detail the internals of the JS example

- core/rawdb/accessors_chain.go
> typo fix: storea => store

- docs/_whisper/Whisper-Overview.md
Version was still incorrectly reported
> whisper: fix version number in overview

- core/rawdb/schema.go
> typo fix: know=>known

- docs/_interface/Management-APIs.md
From 10c4630101402a700d54f1614d8c8bd811ce36eb Mon Sep 17 00:00:00 2001
From: Jonas Felber <felber.jonas@gmail.com>
Date: Fri, 15 Mar 2019 10:49:38 +0100
Subject: [PATCH] Fixed traceTransacion with custom tracer example.
closes #19277
>  Fixed traceTransaction with custom tracer example

- appveyor.yml
https://golang.org/doc/devel/release.html#go1.12.minor
```
fd -Ht f -exec sed -i 's/1\.12\.4/1\.12\.5/g' {} \;
```
> appveyor.yml: Upgraded to Go 1.12.5

- eth/downloader/downloader.go
A while back we changed our downloader so that if we have old blocks, but not old state in the database, we don't start downloading from the oldest existing state, rather we only fetch new blocks and leave it up to the blockchain to detect that state is missing and fix it (i.e. replay old blocks). This scenario happens after crashes btw, where the state is not written to disk, but the blocks are.
We have another funky mechanism in the downloader that attempts to delay header deliveries while sync is ongoing: if we're waaay behind the chain, it's not the best idea to deliver the most recent header, since that might suffer a mini-reorg, so the subsequent header delivery might produce an invalid hash chain (old head became an uncle). Instead of stopping the downloader until the importer …
> eth/downloader: fix header delays during chain dedup

- core/blockchain.go
- core/blockchain_test.go
This PR fixes the known block insertion logic.
Geth node can import a batch of known blocks in such scenario:
* During the fast sync, the pivot point is already submitted but rollback
happens. 
* Then node resets the head full block to a lower height via `rollback`
and leaves a few known **full** blocks in the database.		
*  When node runs fast sync again, it can re-import a batch of known blocks via
`insertChain` while a part of them have higher total difficulty than current
head full block(new pivot point).
If the known blocks' total difficulty is lower than head full block, ignore them. But if the td is higher, commit them as the new head.
> core: import known blocks

- cmd/faucet/faucet.go
Fixes https://github.com/ethereum/go-ethereum/issues/19538.
>  cmd/faucet: embed git commit hash/date, disable Google+

- swarm/metrics/flags.go
I know we collect this on an infrastructure level, but it is also handy to have it alongside the app metrics.
> swarm/metrics: collect metrics on datadir disk usage

- swarm/version/version.go
To be merged after https://github.com/ethereum/go-ethereum/pull/19585
> swarm/version: v0.4.0 stable

- les/fetcher.go
This PR avoids a potential light fetcher deadlock caused by filling the capacity of requestChn. This could be caused by 100 simultaneous server announcements (possible attack vector).
> les: avoid fetcher deadlock on requestChn

- core/state/state_object.go
The function signature of the state object is self-split,
```go
func (c *stateObject) ...
func (s *stateObject) ...
func (self *stateObject) ...
```
Uniformly modified to
```
func (s *stateObject) ...
```
> chore(state_object.go): Unified function signature

- cmd/utils/flags.go
Fixes a regression from https://github.com/ethereum/go-ethereum/pull/19662
> cmd/utils: close quote

- accounts/usbwallet/hub.go
On my work machine (fedora 29 on Qubes), usb enumeration fails, and it would print out three error messages every second to tell me about it. 
This PR does not fix any underlying issue, but does abort USB enumeration after three failures (three per usb hub, so in total nine)
After this PR
```
INFO [06-05|10:54:43.822] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [06-05|10:54:43.822] Sanitizing cache to Go's GC limits       provided=4096 updated=2590
INFO [06-05|10:54:43.827] Maximum peer count                       ETH=0 LES=0 total=0
INFO [06-05|10:54:43.828] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
ERROR[06-05|10:54:43.829] Error enumerating USB                    code="failed to initialize libusb: …
```
> account/usbwallet: abort usb enumeration after failures

- vendor/github.com/karalabe/usb/Dockerfile.alpine
- vendor/github.com/karalabe/usb/Dockerfile.ubuntu
- vendor/github.com/karalabe/usb/libs.go
- vendor/vendor.json
Fixes a build failure on musl (Alpine Linux).
> vendor: pull in USB fix for docker (alpine/musl)

- dashboard/assets/yarn.lock
This PR contains a package update of the dashboard.
> dashboard: update yarn.lock

- appveyor.yml
- vendor/github.com/karalabe/usb/appveyor.yml
- vendor/vendor.json
Related: https://github.com/karalabe/usb/pull/3
> appveyor: bump to Go 1.12.6

- mobile/context.go
> mobile: fix comment typos

- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/config.go
- eth/gen_config.go
- les/backend.go
- params/config.go
- Drop `--override.constantinople`
- Rename `ConstantinopleFix` to `Petersburg`
> cmd, eth, les, param: drop --override.constantinople

- p2p/message.go
- p2p/peer.go
- p2p/server.go
This PR adds info about remote and local ip to peerevents, so that someone who wants to analyse traffic pattern can also know the origin/dest of each message. 
With this pr, using the following request
```json
{"id": 1, "method": "admin_subscribe", "params": ["peerEvents"]}
```
This is returned on the subscription
```
[user@work go-ethereum]$ cat request.json - | ncat -U /home/user/.ethereum/geth.ipc
{"jsonrpc":"2.0","id":1,"result":"0x925aac646d4de507f99c974a9be2ac7e"}
{"jsonrpc":"2.0","method":"admin_subscription","params":{"subscription":"0x925aac646d4de507f99c974a9be2ac7e","result":{"type":"add","peer":"74094ca6f4684039aa6eeb827dd2841eb8251ee63d44bdbe6ec34f5d1166940b","local":"10.137.0.15:37536","remote":"51.255.142.204:30305"}}} …
```
> p2p: add address info to peer event reporting

- cmd/utils/flags.go
- eth/config.go
- eth/gen_config.go
> cmd, eth: fix dump config issue.

- core/state/statedb_test.go
- p2p/discover/v4_udp_test.go
- trie/trie_test.go
- whisper/whisperv6/whisper_test.go
No need to convert these types.
> Avoid unnecessary conversions

- cmd/geth/main.go
Fixes https://github.com/ethereum/go-ethereum/issues/19874
> cmd/geth: skip 4GB memory bump for devnet

- signer/fourbyte/validation.go
Supersedes https://github.com/ethereum/go-ethereum/pull/19688 as that PR was abandoned.
> signer/fourbytes: fix up error messages
