core/vm/instructions.go

zero check has been added to `uint256.AddMod` since this commit https://github.com/holiman/uint256/commit/6785da6e3eea403260a5760029e722aa4ff1716d

core/vm: remove a redundant zero check in opAddmod

---

eth/tracers/native/call_flat.go
eth/tracers/native/call_flat_test.go

Fix for #29622:
Store `reason` when `Stop` is called in the `flatCallTracer`. This will be returned when `GetResult()` is called.

eth/tracers/native: fix flatCallTracer Stop() bug

---

core/vm/contracts.go

Adds the subgroup checks as required by the current spec: https://github.com/ethereum/EIPs/pull/8456/files

core/vm: add subgroup checks for mul/mulexp for G1/G2

---

internal/ethapi/api.go

If the context is cancelled while we're calculating an access list, we previously didn't check it which can cause excessive resource usage.

internal/ethapi: listen to ctx cancellation in access list

---

beacon/engine/types.go
beacon/types/exec_payload.go
cmd/evm/internal/t8ntool/block.go
consensus/beacon/consensus.go
consensus/clique/clique.go
consensus/ethash/consensus.go
core/genesis.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/rawdb/accessors_indexes_test.go
core/rawdb/chain_iterator_test.go
core/state_processor_test.go
core/txpool/legacypool/legacypool_test.go
core/types/block.go
core/types/block_test.go
eth/catalyst/api_test.go
eth/downloader/downloader.go
eth/downloader/queue.go
ethclient/ethclient.go
internal/era/era.go
internal/era/iterator.go
internal/ethapi/api_test.go
miner/miner_test.go

Something we've discussed a bit in the past; thought I would see if there is interest in it now before we look into merging PRs for 6110 and 7002 -- they both add new quantities to the body.

all: refactor so `NewBlock`, `WithBody` take `types.Body`

---

cmd/devp2p/internal/ethtest/snap.go
cmd/geth/dbcmd.go
core/genesis_test.go
core/rawdb/accessors_trie.go
core/rawdb/ancient_utils.go
eth/handler.go
eth/protocols/snap/gentrie.go
eth/protocols/snap/sync.go
eth/protocols/snap/sync_test.go
trie/hasher.go
trie/stacktrie_fuzzer_test.go
trie/sync.go
trie/trie_test.go
trie/trienode/node.go
trie/triestate/state.go
triedb/database.go
triedb/database/database.go
triedb/hashdb/database.go
triedb/pathdb/database.go
triedb/pathdb/database_test.go
triedb/pathdb/difflayer_test.go
triedb/pathdb/disklayer.go
triedb/pathdb/journal.go
triedb/pathdb/nodebuffer.go

This pull request does a few things:
- Remove `HasAccountTrieNode` and `HasStorageTrieNode` APIs: 
these APIs were used to determine if the node with provided path and hash is existent in the disk or not. If the database entry is existent but with a different hash, it will also return false
- Rename `ExistsAccountTrieNode` to `HasAccountTrieNode`
- Rename `ExistsStorageTrieNode` to `HasStorageTrieNode`
- Change `ReadAccountTrieNode` and `ReadStorageTrieNode` to only return the blob (no hashing)
- Replace `sha3.NewLegacyKeccak256().(crypto.KeccakState)` with `crypto.NewKeccakState()` as they are equivalent
The reason for this change is that the current code uses keccak256 as the default method to compute the node hash (alternatively referred to as the unique ID of the node). While this …

core/rawdb, trie: improve db APIs for accessing trie nodes

---

docs/interacting-with-geth/javascript-console.md

Running a `geth attach --exec` command as shown in the website will cause an error: `Fatal: invalid command-line: too many arguments`.
The fix is simple: write the `--exec` flag and the command before `attach`.

website: fix js console --exec commands

---

p2p/discover/v5wire/encoding_test.go

p2p/discover/v5wire: add tests for invalid handshake and auth data size

p2p/discover/v5wire: add tests for invalid handshake and auth data size

---

core/state_processor.go
core/tracing/CHANGELOG.md
core/tracing/hooks.go

Added a `start/end` system where tracer can be notified that processing of some Ethereum system calls is starting processing and also notifies it when the processing has completed.
Doing a `start/end` for system call will enable tracers to "route" incoming next tracing events to go to a separate bucket than other EVM calls. Those not interested by this fact can simply avoid registering the hooks.
The EVM call is going to be traced normally afterward between the signals provided by those 2 new hooks but outside of a transaction context `OnTxStart/End`. That something implementors of live tracers will need to be aware of (since only "trx tracers" are not concerned by `ProcessBeaconRoot`).
I've looked into providing some kind of unit tests for that but it prove harder than anticipated. Since …

core/tracing: add system call callback when performing `ProcessBeaconBlockRoot`

---

core/blockchain.go
core/blockchain_test.go
core/state/statedb.go

The 128 layers is currently hardcoded in `state`, whereas that depth is left as a constant in `core`.
Move this constant so that the verkle code that consumes it, and needs a deeper tree, has to only modify a single location.

core, core/state: move TriesInMemory to state package

---

ethdb/pebble/pebble.go

Pebble gauge metrics are stuck when opening a database for the second time (within the same metrics namespace, after closing first one). 
Gauge metrics are created with `metrics.NewRegisteredGauge` and it fails silently if metric name already exists. The Meter metrics work despite that `metrics.NewRegisteredMeter` is used, because it calls `metrics.GetOrRegisterMeter` internally.
This PR fixes the issue by using `metrics.GetOrRegister*` functions instead.

ethdb/pebble: fix pebble metrics registration

---

eth/gasprice/feehistory.go

Add query limit to defend DDoS attack. Max allow 100 different percentiles in rewardPercentiles.
this PR is ported from bsc [2423](https://github.com/bnb-chain/bsc/pull/2423)

eth/gasprice: add query limit for FeeHistory to defend DDOS attack

---

eth/gasestimator/gasestimator.go

Fix for the bug descripted on https://github.com/ethereum/go-ethereum/issues/29702 -- I no longer see the bug.
I am new to go-ethereum codebase, so I may have missed things, please tell me :-)
Also, would you like some test with it?

eth/gasestimator: include blobs in virtual balance computation

---

.travis.yml

This bumps the travis image for building six years forward, from 2018 to 2024. 
Doing this might not fix https://github.com/ethereum/go-ethereum/issues/28987#issuecomment-2095287914, but _not_ doing it certainly will block it.

travis: use ubuntu noble (24.04) instead of bionic (18.04)

---

core/state/journal.go
core/state/state_object.go
core/state/statedb_test.go

This pull request reworks the dirty storage logic a bit, by handling one more corner case for revoking dirtiness.
The dirty marker of a storage slot will be revoked in these following two cases:
- the initial mutation of the slot inside of the current transaction is reverted 
- the storage slot is set back to its original value
In these two cases, the storage slot shouldn't be regarded as dirty anymore.

core/state: remove slot dirtyness if it's set back to origin value

---

event/multisub.go

replace "of" with "or" in the code's comment so that its meaning can be more clearly understood.

event: fix typo

---

core/state/state_object.go

Originally `updateTrie` will try to finalize the dirty storages first before trie committing. This operation is removed in this pull request, reasons as below:
- Before the `updateTrie`, all the finalization has already been done in `IntermediateRoot`, the operation here is duplicated
- The prefetcher has been terminated at that time and if there are some leftover slots, they will be failed for prefetching

core/state: remove useless operation

---

core/chain_makers_test.go
core/genesis.go
params/protocol_params.go

Dev/Private chain setup now supports EIP-4788 at Genesis block.
Took `BeaconRootsCode` from [here](https://github.com/lightclient/4788asm?tab=readme-ov-file#building) and then added to `Alloc`.
Result on console:
`> eth.call({ from: eth.accounts[0], input: '0x5f6020818181720f3df6d732807ef1319fb7b8bb8522d0beac024282525afa1460275760205ff35b5f80fd' })
"0x0000000000000000000000000000000000000000000000000000000000000000"`
Fixes #29539

core: deploy EIP-4788 contract in dev mode genesis

---

.github/workflows/go.yml

Node16 is deprecated and Actions using it will stop being used 3rd of June
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
See example warning in https://github.com/ethereum/go-ethereum/actions/runs/9079334833
Currently `checkout@v2` uses `node16` since `node12` was deprecated last year

.github: upgrade to action versions with node20

---

core/state_transition.go

Currently `balanceCheck` only includes `msg.Value` when `msg.GasFeeCap!=nil`.
I think `balanceCheck` should always include `msg.Value` no matter whether `msg.GasPrice` or `msg.GasFeeCap` is chosen as the effective gas price.

core: `balanceCheck` should always include `msg.Value`

---

eth/protocols/snap/sync.go
trie/sync.go

This pull request adds one more check before committing the trie nodes from the `trie.Syncer`:
- for node deletion, the node blob must be zero-length
- for node update, the node blob must be non-zero-length
The check is cheap enough and shouldn't have any performance impact.
--- 
The node blob cached in the `trie.Syncer` is not deep-copied, rather than a reference of the [network packet](https://github.com/ethereum/go-ethereum/blob/master/eth/protocols/snap/sync.go#L2793).
Theoretically it should be safe the hold the network packet reference being originated from [here](https://github.com/ethereum/go-ethereum/blob/master/eth/protocols/snap/handler.go#L267), although i am not 100% confident about it. 
If it's possible to empties the referenced blob somehow, than it could be the root cause …

trie, eth/protocols/snap: sanitize the committed node data

---

eth/tracers/api.go
eth/tracers/api_test.go

This PR adds a testcase to trigger the flaw in #29800. 
@s1na feel free to pile a fix on top here :)

eth/tracers: fix and add testcase for #29800

---

internal/ethapi/api.go

Since the recent release notes said that you like nitpick PRs, here's one more!
Personally, I would also say "revert" instead of "revertal", but since it occurs five times in the code base, it doesn't seem to be an accident.

internal/ethapi: fix typos

---

eth/tracers/api.go
eth/tracers/logger/logger_json.go

`evm blocktest` goes through the main block processing code path, triggering the system calls. That caused a crash because we start opcode processing without doing `OnTxStart` (which sets the env).
This PR removes events from the system call. I'm open to keeping them if they are useful for testers, and instead fix the crash.

eth/tracers: fix json logger for evm blocktest

---

Makefile

- Added `fmt` command to **Makefile** for easier formatting.
- Formatted '.go' files with `make fmt`.
- Made `help` the default command and updated it.

Makefile: add fmt, update help

---

cmd/devp2p/discv4cmd.go
internal/testlog/testlog.go
node/api.go
p2p/discover/common.go
p2p/discover/lookup.go
p2p/discover/node.go
p2p/discover/table.go
p2p/discover/table_reval.go
p2p/discover/table_test.go
p2p/discover/table_util_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v5_udp.go
p2p/discover/v5_udp_test.go
p2p/server.go

Node discovery periodically *revalidates* the nodes in its table by sending PING, checking if they are still alive. I recently noticed some issues with the implementation of this process, which can cause strange results such as nodes dropping unexpectedly, certain nodes not getting revalidated often enough, and bad results being returned to incoming FINDNODE queries.
Let me first describe how the revalidation process worked previously:
- We set a randomized timer < 10s. When that timer expires, a random bucket is chosen, and within that bucket the last node will be validated.
- The idea of revalidating the *last node* was taken from the original Kademlia paper. Certain contacts, such as incoming PING, will move nodes to the first position of the bucket. Other events (i.e. adding nodes …

p2p/discover: improved node revalidation

---

metrics/sample_test.go

Refer [comments](https://github.com/ethereum/go-ethereum/pull/29826#issuecomment-2128364846) from @fjl 
Since we calculated the average by totalizing the `values`, there is no test case to ensure `SampleSnapshot.Sum()` is calculated correctly, I think we need this test case.
BTW, if we have guaranteed the result of `SampleSnapshot.Sum()` in a test, why should we do another redundant round of computation in other tests?

metrics: add test for `SampleSnapshot.Sum`

---

core/types/transaction.go

changed comments to mention set inclusion explicitly

core/types: clarify set inclusion in comments

---

core/genesis.go
eth/protocols/snap/progress_test.go
internal/ethapi/api_test.go

- Removed redundant use of `types.Account` and `common.Hash`.

core, eth/protocols/snap, internal/ethapi: Fix redundant types

---

miner/payload_building_test.go

Regarding #29830
Due to the large transaction churn,  adding tx to txpool may postpone fully integrating the tx to a later point to batch multiple ones together. 
If a block resolution occurs before a mock transaction is added to the transaction pool, the block won't contain any transactions. This sporadically causes TestBuildPayload to fail.
The solution is to set the sync flag to true, delaying block resolution until the addition is completed.

miner: fix TestBuildPayload sporadic failure

---

eth/downloader/skeleton_test.go

This pull request fixes the flay test `TestSkeletonSyncRetrievals`. In this test, we first trigger a sync cycle and wait for it to meet certain expectations. We then inject a new head and potentially also a new peer, then perform another final sync. The test now performs the `newPeer` addition before launching the final sync, and waits a bit for that peer to get registered. This fixes the logic race that made the test fail sometimes.
The potential test error could be:
```
--- FAIL: TestSkeletonSyncRetrievals (5.15s)
skeleton_test.go:948: test 0, end state: subchain 0 head mismatch: have 5001, want 5003
FAIL
--- FAIL: TestSkeletonSyncRetrievals (0.84s)
skeleton_test.go:908: test 5, mid state: dropped peers mismatch: have 0, want 1
FAIL
```

eth/downloader: fix flaky test

---

beacon/types/exec_payload.go
cmd/clef/consolecmd_test.go
cmd/clef/main.go
core/chain_indexer_test.go
core/types/transaction_test.go
eth/backend.go
eth/catalyst/api_test.go
log/logger_test.go

Fixed the error string format according to https://go.dev/wiki/CodeReviewComments#error-strings. PTAL

all: improve some error strings

---

core/vm/runtime/runtime.go
core/vm/runtime/runtime_test.go

This PR closes https://github.com/ethereum/go-ethereum/issues/29782 and https://github.com/ethereum/go-ethereum/issues/29722 . The `IsMerge` indicator used by core/vm/runtime checked if the prevrandao/random was set. This is actually a somewhat sane indicator, because if it is `nil`, it will trigger a nil deref later on if the `RANDOM` opcode is used. 
This PR fixes it by setting it in case we're past Shanghai. 
```
[user@work go-ethereum]$ go run ./cmd/evm --nomemory=false --json --code 5f44 run 
{"pc":0,"op":95,"gas":"0x2540be400","gasCost":"0x2","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH0"}
{"pc":1,"op":68,"gas":"0x2540be3fe","gasCost":"0x2","memSize":0,"stack":["0x0"],"depth":1,"refund":0,"opName":"DIFFICULTY"} …
```

core/vm/runtime: set random to enable merge-opcodes

---

core/rawdb/freezer_resettable.go
triedb/pathdb/database.go

This pull request fixes the read-only option for state freezer in pathdb.

core/rawdb, triedb/pathdb: fix freezer read-only option

---

p2p/discover/node.go
p2p/discover/table_reval.go
p2p/discover/table_reval_test.go
p2p/discover/table_util_test.go

p2p/discover: fix crash when revalidated node is removed

---

p2p/discover/table.go
p2p/discover/table_reval.go
p2p/discover/table_reval_test.go
p2p/discover/table_test.go

It seems the semantic differences between addFoundNode and addInboundNode were lost in
#29572. My understanding is addFoundNode is for a node you have not contacted directly
(and are unsure if is available) whereas addInboundNode is for adding nodes that have
contacted the local node and we can verify they are active.
handleAddNode seems to be the consolidation of those two methods, yet it bumps the node in
the bucket (updating it's IP addr) even if the node was not an inbound. This PR fixes
this. It wasn't originally caught in tests like TestTable_addSeenNode because the
manipulation of the node object actually modified the node value used by the test.
New logic is added to reject non-inbound updates unless the sequence number of the
(signed) ENR increases. Inbound updates, which are …

p2p/discover: fix update logic in handleAddNode

---

eth/downloader/api.go
eth/tracers/api_test.go

eth/downloader, eth/tracer: fix typos in comments

---

cmd/devp2p/internal/v4test/framework.go
p2p/discover/common.go
p2p/discover/lookup.go
p2p/discover/metrics.go
p2p/discover/node.go
p2p/discover/table.go
p2p/discover/table_reval.go
p2p/discover/table_reval_test.go
p2p/discover/table_test.go
p2p/discover/table_util_test.go
p2p/discover/v4_lookup_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v4wire/v4wire.go
p2p/discover/v5_talk.go
p2p/discover/v5_udp.go
p2p/discover/v5_udp_test.go
p2p/server.go

Here we clean up internal uses of type `discover.node`, converting most code to use `enode.Node` instead. The `discover.node` type used to be the canonical representation of network hosts before ENR was introduced. Most code worked with `*node` to avoid conversions when interacting with `Table` methods. Since `*node` also contains internal state of `Table` and is a mutable type, using `*node` outside of `Table` code is prone to data races. It's also cleaner not having to wrap/unwrap `*enode.Node` all the time.
`discover.node` has been renamed to `tableNode` to clarify its purpose.
While here, we also change most uses of `net.UDPAddr` into `netip.AddrPort`. While this is technically a separate refactoring from the `*node` -> `*enode.Node` change, it is more convenient because `*enode.Node` …

p2p/discover: refactor node and endpoint representation

---

eth/catalyst/simulated_beacon.go

This should fix an occasional test failure in ethclient/simulated.TestForkResendTx. Inspection of logs revealed the cause of the failure being that txpool was not done reorganizing by the time Fork is called.
```
~/d/e/go-ethereum >> go test -run TestForkResendTx -count 200 ./ethclient/simulated 
ok  	github.com/ethereum/go-ethereum/ethclient/simulated	3.645s
~/d/e/go-ethereum >> go test -run TestForkResendTx -count 200 -race ./ethclient/simulated 
ok  	github.com/ethereum/go-ethereum/ethclient/simulated	11.669s
```

eth/catalyst: ensure TxPool is synced in Fork

---

docs/fundamentals/private-network.md
docs/interacting-with-geth/rpc/ns-clique.md
docs/tools/clef/clique-signing.md

As mentioned in this [PR](https://github.com/ethereum/go-ethereum/pull/29292), clique has been deprecated since v1.14 of geth.
Adding a disclaimer on each clique mention to tell user this protocol is now deprecated.
Not the most beautiful way to do but the
```md
> [!Warning]
> My warning
```
snippet is not working as expected.
Decided to not remove completely the documentation as some people might need time to move away from clique.
fixes #29877

Add Disclaimer on clique being deprecated from v1.14

---

common/math/big_test.go
common/math/integer.go

It's odd to use the keyword `int` as variable name, I think it's better to use `in`

common/math: rename variable name `int` to `in`

---

miner/miner.go

This PR is the result of a long debate as to what the default minimum miner tip expectation of Geth should be. It's important to highlight here that this is *just* a CLI flag that miners can change, but still people felt strongly that the default should be more reasonable (https://github.com/ethereum/go-ethereum/issues/29771).
The 1 gwei was originally meant as an opportunity cost for doing more computation on the block + propagating a larger block, which could have someone beat the miner to producing a block. With PoS, there's no opportunity cost wrt someone producing a better block, so it makes sense to reduce the minimum needed price.
Whilst in theory we could also just completely remove it, I feel that miners should still be rewarded *something* for adding transactions to their …

miner: lower default min miner tip from 1 gwei to 0.001 gwei

---

core/genesis_test.go
core/state/state_object.go
core/state/statedb.go
core/state/statedb_fuzz_test.go
core/state/stateupdate.go

This pull request rewrites the statedb by introducing a state update struct. 
A state update struct will be constructed once the `statedb.Commit` is invoked. It contains all the state
changes caused by previous state transition, e.g. 
- original state root and post-execute state root
- deleted accounts along with their original value
- updated accounts along with their original value
- dirty contract codes
- dirty trie nodes (state hasher)
Instead of committing the state change into state snapshot and trie database blindly, the state update
will be returned and then can be consumed by different state database implementation in different 
ways. It gives more flexibilities to design database abstraction for different purposes.
What's more, the statedb has been simplified significantly, …

core/state: introduce stateupdate structure

---

core/state/statedb.go

Fix #29880 
Always prefetch the account trie while starting the prefetcher.

core/state: prefetch account trie while starting a prefetcher

---

core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go

`deriveLogFields` is a testing-only function and can be replaced with another one. This pull request deprecates this "unused" function for clean up.

core/rawdb: remove unused deriveLogFields

---

cmd/devp2p/internal/ethtest/conn.go
cmd/devp2p/internal/v4test/framework.go
cmd/devp2p/nodesetcmd.go
cmd/devp2p/rlpxcmd.go
p2p/dial.go
p2p/discover/table.go
p2p/discover/table_test.go
p2p/discover/table_util_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v5_udp.go
p2p/discover/v5wire/encoding_test.go
p2p/enode/localnode.go
p2p/enode/localnode_test.go
p2p/enode/nodedb.go
p2p/enode/nodedb_test.go
p2p/netutil/addrutil.go
p2p/netutil/iptrack.go
p2p/netutil/iptrack_test.go
p2p/netutil/net.go
p2p/netutil/net_test.go
p2p/server.go
p2p/server_nat_test.go

`enode.Node` was recently changed to store a cache of endpoint information. The IP address in the cache is a `netip.Addr`. I chose that type over `net.IP` because it is just better. `netip.Addr` is meant to be used as a value type. Copying it does not allocate, it can be compared with `==`, and can be used as a map key.
This PR changes most uses of `Node.IP()` into `Node.IPAddr()`, which returns the cached value directly without allocating.
While there are still some public APIs left where `net.IP` is used, I have converted all code used internally by p2p/discover to the new types. So this does change some public Go API, but hopefully not APIs any external code actually uses.
There weren't supposed to be any semantic differences resulting from this refactoring, however it does introduce …

p2p: use netip.Addr where possible

---

rlp/raw.go

don't need to repeatly called `len` method

rlp: no need to repeat called len method

---

cmd/evm/internal/t8ntool/transition.go
cmd/evm/internal/t8ntool/tx_iterator.go

Parameter `env` is unused on the method [loadTransactions](https://github.com/ethereum/go-ethereum/blob/125fb1ff5855134b040e295f380eeecff29af375/cmd/evm/internal/t8ntool/tx_iterator.go#L115).

cmd/evm/internal/t8ntool: remove unused parameter

---

cmd/clef/README.md
cmd/evm/README.md

Update README docs.
In `cmd/evm/README.md`, tab isn't applied because of an incorrect entry and in `cmd/clef/README.md`, the numbering is incorrect.

cmd/clef, cmd/evm: fix markdown issues in README

---

p2p/discover/table.go

According to the documentation of the method [`handleAddNode`](https://github.com/ethereum/go-ethereum/blob/1098d148a51c929fd9829328fe60ca1214f3c7b5/p2p/discover/table.go#L506),
> // The caller must hold tab.mutex.
This required call to `tab.mutex.Lock`, and `tab.mutex.Unlock` is missing on the method `loadSeedNodes`.

p2p/discover: add missing lock when calling tab.handleAddNode

---

p2p/server.go

Replacing bubble sort in `p2p/server.go` on `PeersInfo` method by standard library method [ `slices.SortFunc`](https://pkg.go.dev/slices#SortFunc).

p2p: use package slices to sort in PeersInfo

---

core/genesis.go

closes https://github.com/ethereum/go-ethereum/issues/29955

core: initialize developer genesis beacon root contract with 0 balance

---

core/state/snapshot/iterator_test.go
rlp/decode.go

remove duplicated words in comments to improve reading experience.

core, rlp: remove duplicated words

---

cmd/geth/main.go
cmd/utils/flags.go
core/blockchain.go
core/state/state_object.go
core/state/statedb.go
core/state/trie_prefetcher.go
core/state/trie_prefetcher_test.go
core/vm/interpreter.go
eth/backend.go
eth/ethconfig/config.go

Pulled out from https://github.com/ethereum/go-ethereum/pull/29719

core, cmd/utils: when configured via  flag, in block execution: prefetch all reads from account/storage tries

---

.github/workflows/go.yml

disable the dependency cache so that they are not uploaded to github's servers, which is just as slow as downloading all the dependencies in the first place.

.github/workflows: disable cache

---

.golangci.yml
beacon/light/sync/test_helpers.go
core/txpool/blobpool/blobpool_test.go
core/types/transaction_signing.go
internal/ethapi/api.go
log/handler.go
signer/core/apitypes/types.go
signer/core/uiapi.go

Mismatching receiver name are a common source of PRs on this repo. The new lint rule should prevent these from happening.

all: fix inconsistent receiver name and add lint rule for it

---

accounts/abi/type.go
accounts/scwallet/wallet.go

every time function **NewType** and **wallet.Open** execute, these regexp are initialized. which situation reduce the performance.

accounts/abi, accounts/scwallet: avoid duplicate regex compilation

---

core/state/database.go
core/state/snapshot/generate.go
core/state/snapshot/generate_test.go
core/state/state_object.go
core/state/statedb.go
eth/protocols/snap/sync_test.go
trie/iterator_test.go
trie/secure_trie.go
trie/secure_trie_test.go
trie/stacktrie_fuzzer_test.go
trie/sync_test.go
trie/tracer_test.go
trie/trie.go
trie/trie_test.go
trie/triestate/state.go
trie/verkle.go
triedb/pathdb/database_test.go
triedb/pathdb/testutils.go

The `Commit` operation performs the commitment computation, computing the changed node-set, internal intermediate roots, and new state root.  There's no reason that it should fail and return an error.

core/state, eth/protocols, trie, triedb/pathdb:  remove unused error from trie Commit

---

beacon/light/api/light_api.go
beacon/light/request/server.go
beacon/light/request/server_test.go

This PR fixes shutdown/server disconnection issues in the beacon light syncer:
- as described in https://github.com/ethereum/go-ethereum/issues/29915 the server event stream crashed during shutdown; this issue was simply caused by a double call to `stream.Close()`.
- the server implementation in `beacon/light/request` did not handle server disconnection properly. If an event callback arrived after unsubscribing from server events (shutdown occured while a request was pending) the server called the removed (nil) callback function. Also, the unsubscription from the parent was called while the server mutex was locked, which was both unnecessary and wrong because it broke the normal locking order (`Scheduler` -> `serverWithLimits` -> `serverWithTimeout` -> `ApiServer`) sometimes causing a …

beacon/light: fix shutdown issues

---

triedb/database.go
triedb/hashdb/database.go

Seems moving `Reader` to `triedb/database` allows it to be imported in the pathdb/hashdb and the explicit type switch in `Database.Reader` can be avoided by adding it to the `backend` interface.

trie/triedb: add Reader to backend interface

---

common/math/big.go
common/math/integer.go

Fixes a potential panic if `len(input) == 1`
```
input = input[1 : len(input)-1]
```

common/math: fix out of bounds access in json unmarshalling

---

core/state/snapshot/snapshot.go

Make sure that all operations are done with the snaptree if we call Release on it

core/state/snapshot: acquire the lock on Release

---

trie/trie.go

We will want the tracer access list available after calling `Commit` when building stateless witnesses.  There's no need to clear it as a trie should not be mutated again after calling `Commit`.

trie: don't reset tracer at the end of Commit

---

common/types.go
common/types_test.go

Since `Decimal` is defined as `type Decimal uint64`, we should use `strconv.ParseUint` instead of `strconv.ParseInt`

common: using `ParseUint` instead of `ParseInt`

---

core/txpool/blobpool/blobpool.go

Modified some of the locks in `blobpool` to readlocks where appropriate.

core/txpool/blobpool: change lock to read lock

---

core/state/snapshot/generate.go
core/state/snapshot/snapshot.go

This pull request improves and fixes some tiny issues:
---
Originally, the first account range after an interruption was limited to a single account. The rationale was that mutations might occur at the interruption point, making it more likely to detect inconsistencies. However, since mutations can occur anywhere, this special handling was unnecessary and overly complex. Therefore, it has been removed in this pull request.
---
Besides, this pull request also fixes a tiny issue, by releasing the clean cache if the whole snapshot is disabled, preventing memory leak.

core/state/snapshot: tiny fixes

---

p2p/discover/table_test.go

This pull request fixes a flaky test TestTable_revalidateSyncRecord in #29830
BTW, there is also an issue with the first `waitForRevalidationPing`
```shell
/tmp/go-stress-20240618T231835-3046585152
--- FAIL: TestTable_revalidateSyncRecord (2.00s)
table_test.go:426: Table did not send revalidation ping
FAIL
```
1. First `time.Sleep` ensures `fast revalidationList` can return non-nil fast node from `func (list *revalidationList) get(now mclock.AbsTime, rand randomSource, exclude map[enode.ID]struct{}) *tableNode`, so that we can send `ping request`
2. Second `time.Sleep` ensures `fast revalidationList` moves to `slow revalidationList`, and can return non-nil slow node from `func (list *revalidationList) get(now mclock.AbsTime, rand randomSource, exclude map[enode.ID]struct{}) *tableNode`, …

p2p/discover: fix flaky test TestTable_revalidateSyncRecord

---

cmd/blsync/main.go

*Replaces #30042*
As @fjl mentioned, the correct way to have `blsync` handle the log configuration is to reuse `debug.Setup`.

cmd/blsync: use debug.Setup for logging configuration

---

.github/CODEOWNERS

In an effort to lower the number of open PRs, I am proposing to add myself to a few packages that I have contributed to over the past few years that I feel comfortable with helping maintain.
Obviously open to reducing or increasing the scope of code ownership depending on how people feel. Just hoping this will decrease some of the busy work for those with merge rights.

.github: add lightclient as codeowner to relevant packages

---

core/txpool/blobpool/blobpool.go
core/txpool/blobpool/evictheap.go
core/txpool/blobpool/evictheap_test.go

Map types are reference types, we can use them as pointers.

core/txpool/blobpool: avoid use *map as parameter.

---

docs/fundamentals/kurtosis.md

Fix a typo in Kurtosis private network command to spin up the network, which makes it unrunnable.

website: fix kurtosis cmd

---

eth/tracers/live/supply.go
eth/tracers/native/call_flat.go
trie/verkle.go

eth/tracers,trie: remove unnecessary check

---

docs/developers/evm-tracing/built-in-tracers.md

This changes the diffMode description for the prestate tracer to be more clear on what is included and what excluded.
When I used the tracer I was surprised that some fields where included in `pre` even though they were not changed in the transaction. In particular, the "Any read-only access is omitted completely from the result." is not clear that this omission is on an account level, rather than on a field level.
Feel free to adjust it to make it more clear, that's the best I could come up for now.

website: clarify prestate tracer diffMode

---

triedb/pathdb/database.go
triedb/pathdb/database_test.go

Refer to #29830 [comment](https://github.com/ethereum/go-ethereum/issues/29830#issuecomment-2143240316)
Larger `maxDiffLayers` causes a higher probability of failing. If maxDiffLayers >= 7, it always fails.
I think it's due to the round times of init data in `newTester`.
After adjusting round times to 12 and stress test `TestNewTester` for 2 minutes, no failed again
```go
// TestNewTester is a temp test for quickly check
func TestNewTester(t *testing.T) {
// Redefine the diff layer depth allowance for faster testing.
maxDiffLayers = 4
defer func() {
maxDiffLayers = 128
}()
tester := newTester(t, 0)
defer tester.release()
if ok, err := tester.db.diskdb.Has(rawdb.TrieNodeAccountPrefix); !ok {
panic(fmt.Sprintf("missing key %v %v", ok, err))
}
}
```
```shell
stress ./pathdb.test …
```

triedb/pathdb: fix flaky test in pathdb

---

rpc/handler.go

Currently a user with the ability to use the `eth_call` RPC can cause the node to log a large amount of data (depending on the `RPCGasCap`).
This PR truncates rpc call message's returned error data after 1024 chars.

rpc: truncate call error data logs

---

core/state/access_events_test.go

Some of the values for comparison and in error message are inconsistent.
Correct me if I chose the wrong one.

core/state: fix inconsistent verkle test error messages

---

docs/fundamentals/kurtosis.md

The command ```kurtosis shell lucid-sky el-2-geth-lighthouse``` gives ```Error:  unknown command "shell" for "kurtosis```
Reason: The keyword **_service_** is missing from the command. 
Check official reference here: https://docs.kurtosis.com/service-shell
- I am using kurtosis cli version: 0.90.1  
- The command should be: ```kurtosis service shell $THE_ENCLAVE_IDENTIFIER $THE_SERVICE_IDENTIFIER```

[Website]: fix cmd to access kurtosis shell

---

crypto/crypto.go

The same hardcoded value is already [there](https://github.com/ethereum/go-ethereum/blob/2d9d42376436cd275c28056cffd0eb97cb8daed8/crypto/secp256k1/curve.go#L287), so no need to do it twice.

crypto: remove hardcoded value for secp256k1.N

---

eth/catalyst/api.go

If a fork choice fails because the final block isn't in the canonical chain, we should log the details of the update's `FinalizedBlockHash` not its `HeadBlockHash` in order to be useful for debugging.

eth/catalyst: fix params in failure log

---

core/txpool/blobpool/blobpool.go

This PR reverts https://github.com/ethereum/go-ethereum/pull/29989/files which introduced a race condition between subsequent calls to blobpool.Nonce. 
The issue is that statedb.GetNonce can write to a cache.
Closes https://github.com/ethereum/go-ethereum/issues/30139

core/txpool/blobpool: revert #29989, WLock on Nonce

---

core/state/statedb.go

This pull request fixes a flaw in verkle.
Inside of the statedb, there is a tool named "prefetcher". It will pull the necessary data for state hashing in the background to accelerate the state hashing performance. Unfortunately, it's broken in the verkle context.
The root cause is once verkle is activated, there is only a single trie used for state hashing(instead of two-layer tree structure in merkle). And storage trie commits are schedule before the account trie for performance consideration. If the verkle trie is resolved from the prefetcher *after committing the storage changes*, the changes caused by storage will be silently dropped.
This pull request disables the prefetching in verkle as a quick fix.

core/state: fix prefetcher for verkle

---

core/txpool/blobpool/blobpool.go

This does not change the behavior here as the nonce in the argument is tx.Nonce(). This commit helps to make the function easier to read and avoid capturing the tx in the function.

core/txpool/blobpool: use nonce from argument instead of tx.Nonce()

---

trie/verkle.go
trie/verkle_test.go

This is a helper PR to support the rolling back of verkle treees.
The request by @rjl493456442 was to have a `DeleteAccountCode` but this API would come with several issues:
* The `DeleteAccount` function does not rollback, it overwrites with 0s, which is the expected behavior of verkles trees.
* a `DeleteAccountCode` function would have to be called _before_ a `DeleteAccount`, so there is a high bug potential here.
Instead, this PR offers `RollBackAccount` which will delete the whole code + the account (and also the first 64 storage slots).
Note that this PR is far from optimized, as it needs support from go-verkle. I would like to first validate the API before I go ahead and modify the library function.
TODO for the final version:

trie: add RollBackAccount function to verkle trees

---

p2p/server_nat.go

`extip` is a `*mclock.Alarm`, so this log prints `ip="&{ch:0x1400797efc0 clock:{} timer:0x1400786c0a0 deadline:239748684632166}"`.
Fix to print changed ip address `ip=121.166.24.7`.

p2p: fix ip change log parameter

---

core/types/transaction_signing.go
core/types/transaction_test.go

For large chain IDs calling `ChainId()` on legacy transactions results in the v param of the signature being modified. This was introduced by removing the copy in this [PR](https://github.com/ethereum/go-ethereum/pull/29911/files#diff-58204a02692cd9ef1cf0767b18dbc4df99eb678126c8982350e5b727af075b5eR574-R576). 
This PR reintroduces the copy of the V param and adds a test.

core: don't modify signature param V when reading chainId

---

eth/catalyst/simulated_beacon.go
ethclient/simulated/backend_test.go

This PR fixes a conversion in `(*SimulatedBeacon).AdjustTime()` which was adding a raw _nanosecond_ duration to a unix timestamp value (_seconds_).  The corresponding test `TestAdjustTime` was making the same mistake.

eth/catalyst: fix (*SimulatedBeacon).AdjustTime() conversion

---

trie/committer.go
triedb/database.go
triedb/hashdb/database.go

This pull request removes the ChildrenResolver interface from the hashdb package.
Originally, this interface was introduced to eliminate the dependency of triedb on trie. However, it has become apparent that this dependency is essential, as triedb relies on trie for numerous functionalities. Consequently, the dependency has been added back in the master branch. Therefore, retaining the interface no longer makes sense.

trie, triedb: remove unnecessary child resolver interface

---

core/txpool/legacypool/legacypool.go

- `slice` and `map` are reference types, we can use themselves as pointers.
- Use `maps.Keys` and `maps.Copy` simplify code.

core/txpool/legacypool: use maps.Keys and maps.Copy

---

core/state/statedb.go

In verkle trees, accounts and storage slots all end up in a single tree. Also, computing the root is quite computationally-intensive, and it is more efficient to compute all hashes/commitments at the same time, than sequentially.
This PR skips root computation of the "storage" trie in verkle, since it would amount to recomputing the root sequentially, over and over again, for each account that has its storage updated.

core/state: don't compute verkle storage tree roots

---

cmd/geth/dbcmd.go
core/genesis_test.go
core/rawdb/accessors_trie.go
core/rawdb/ancient_scheme.go
core/rawdb/ancient_utils.go
core/rawdb/database.go
core/rawdb/schema.go
triedb/database.go
triedb/pathdb/database.go
triedb/pathdb/history_test.go

This pull request isolates Verkle data and Merkle data in the database by prefixing the Verkle data. 
This isolation is necessary in path mode to prevent trie node conflicts and ensure that the two data structures do not interfere with each other.

core/rawdb, triedb, cmd: create an isolated disk namespace for verkle

---

p2p/discover/node.go
p2p/discover/table_util_test.go
p2p/discover/v4_lookup_test.go
p2p/discover/v4_udp.go
p2p/discover/v4_udp_test.go
p2p/discover/v5_udp_test.go

The pubkey type was moved to package v4wire a long time ago. Remaining uses of encPubkey were probably left in due to laziness.

p2p/discover: remove type encPubkey

---

core/state/metrics.go
core/state/statedb.go

This pull request removes a few outdated metrics for simplification.
Originally, these metrics were added to track the largest storage wiping. 
Since account self-destruction was deprecated with the Cancun fork, 
these metrics have become meaningless.

core/state: remove useless metrics

---

rpc/server.go

The error detail may help the client debug the problem.
An example error detail is like the following:

rpc: show more error detail for `invalidMessageError`

---

core/txpool/validation.go

The address recover is executed and cached in ValidateTransaction already. It's expected that the cached one is returned in ValidateTransactionWithState. However, currently, we use the wrong function signer.Sender instead of types.Sender which will do all the address recover again.
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/txpool/legacypool
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
│    old.txt    │               new.txt                │
│    sec/op     │    sec/op     vs base                │
BatchInsert100-8     11.671m ± 29%   7.731m ± 34%  -33.76% (p=0.000 n=10)
BatchInsert1000-8    140.62m ± 17%   72.54m ±  5%  -48.42% (p=0.000 n=10)
BatchInsert10000-8   1384.3m ±  7%   709.5m ±  1%  -48.75% (p=0.000 n=10)
geomean               131.5m …
```

core/txpool: use the cached address in ValidateTransactionWithState

---

core/state/statedb.go

This pull request adds an additional error check after statedb.IntermediateRoot, ensuring that no errors occur during this call. This step is essential, as the call might encounter database errors.

core/state: check db error after intermediate call

---

cmd/utils/flags.go

Currently, we have 3 flags to configure blob pool. However, we don't read these flags and set the blob pool configuration in eth config accordingly. This commit adds a function to check if these flags are provided and set blob pool configuration based on them.

cmd/utils: allow configurating blob pool from flags

---

core/state/statedb.go
internal/ethapi/api_test.go

This pull request fixes the broken feature where the entire storage set is overridden.
Originally, the storage set override was achieved by marking the associated account as deleted, preventing access to the storage slot on disk. However, since [pull request 29520](https://github.com/ethereum/go-ethereum/pull/29520), this flag is also checked when accessing the account, rendering the account unreachable.
A fix has been applied in this pull request, which re-creates a new state object with all account metadata inherited.

core/state: fix SetStorage override behavior

---

triedb/pathdb/reader.go

This pull request explicitly prints out the full hash for debugging purpose.

triedb/pathdb: print out all trie owner and hash information

---

beacon/types/beacon_block.go
beacon/types/exec_header.go
cmd/devp2p/rlpxcmd.go
p2p/enr/entries.go

1. Replace `fmt.Errorf` with `errors.New` when there is no parameter
2. Use `%` format instead of `+` to concat error message

beacon/types, cmd/devp2p, p2p/enr: clean up uses of fmt.Errorf

---

internal/ethapi/api_test.go

Looks like #30094 became a bit stale after #30185 was merged and now we have a stale ref to a state override object causing CI to fail on master.

internal/ethapi: fix state override test

---

p2p/nat/nat.go

Return the actually requested external port instead of `0` for the `AddMapping` implementation for `--nat extip:<IP>`.
Returning `0` causes various trouble, as we now treat this as our externally reachable port. For example, a zero port is treated in some parts of the code as missing value, like when we send a discv4 ping: https://github.com/ethereum/go-ethereum/blob/f94baab238a64895e78034522092e935628c6c74/p2p/discover/v4_udp.go#L204-L211
As `node.UDPEndpoint` returns `ok == false` when our port is `0`, this causes us to generate an invalid ping packet.
This PR aims to fix this issue and possibly other related issues.

p2p/nat: return correct port for ExtIP NAT

---

p2p/server_nat_test.go

The test specifies `ListenAddr: ":0"`, which means a random ephemeral port will be chosen for the TCP listener by the OS. Additionally, since no `DiscAddr` was specified, the same port that is chosen automatically by the OS will also be used for the UDP listener in the discovery UDP setup. This sometimes leads to test failures if the TCP listener picks a free TCP port that is already taken for UDP. By specifying `DiscAddr: ":0"`, the UDP port will be chosen independently from the TCP port, fixing the random failure.
See issue #29830.
Verified using
```
cd p2p
go test -c -race
stress ./p2p.test -test.run=TestServerPortMapping
...
5m0s: 4556 runs so far, 0 failures
```
The issue described above can technically lead to sporadic failures on systems that specify a listen address via the …

p2p: fix flaky test TestServerPortMapping

---

p2p/discover/table_reval.go

If `nextTime` has passed, but all nodes are excluded, `get` would return `nil` and `run` would therefore not invoke `schedule`. Then, we schedule a timer for the past, as neither `nextTime` value has been updated. This creates a busy loop, as the timer immediately returns.
With this PR, revalidation will be also rescheduled when all nodes are excluded.

p2p/discover: schedule revalidation also when all nodes are excluded

---

miner/worker.go

Hi, it seems the prefetcher was intentionally removed from the miner (per this [comment](https://github.com/ethereum/go-ethereum/pull/28623/files#r1514228528)) so it is more clear if the comment does not reference it.

miner: remove outdated comment

---

eth/downloader/beaconsync.go

This pull request fixes an issue in the setMode function of the beaconBackfiller where the sync mode change log was not displaying the previous mode correctly. This issue was discovered while exploring [issue #29817](https://github.com/ethereum/go-ethereum/issues/29817).
After the change, the log message now correctly shows both the old and new sync modes.
Modified the setMode function to store the previous sync mode and display it in the log message.
___________________________________
Additionally, I have a question about the implementation of the **setMode** function. In the current code, the sync mode is updated before checking for errors. Shouldn't we check for errors first, and then update `b.syncMode = mode` if there are no issues?

  eth/downloader: correct sync mode logging to show old mode

---

.golangci.yml
Makefile
accounts/usbwallet/trezor.go
accounts/usbwallet/trezor/trezor.go
build/tools/tools.go
go.mod
go.sum

The package `github.com/golang/protobuf/proto` is deprecated in favor `google.golang.org/protobuf/proto`. 
We should update the codes to recommended package.

all: remove deprecated protobuf dependencies

---

accounts/abi/bind/base.go

Adding the correct accessList parameter when calling a contract can reduce gas consumption. However, the current version only allows adding the accessList manually when constructing the transaction. This PR can provide convenience for saving gas.

accounts/abi/bind: add accessList support to base bond contract

---

eth/downloader/beaconsync.go

Fixes a regression introduced in https://github.com/ethereum/go-ethereum/pull/30219

eth/downloader: gofmt

---

cmd/evm/runner.go

fixes #30254 
It seems like this line is [very old](https://github.com/ethereum/go-ethereum/blame/67b81371008d147aa2ccebd3fa9655fe042b0f14/cmd/evm/runner.go#L165) and is not needed anymore. After removing it, setting a sender that does not exist in the state doesn't seem to cause an issue.
This is the result of the command in the issue, you can see that `BALANCE` now returns the expected value:
```console
$ go run ./cmd/evm --debug --sender 0x1c7cd2d37ffd63856a5bd56a9af1643f2bcf545f --gas 0xffffff --nomemory=false --json --code 731c7cd2d37ffd63856a5bd56a9af1643f2bcf545f3160005260406000f3 --prestate ./genesis.json run
INFO [08-01|21:17:49.233] Persisted trie from memory database      nodes=1 size=142.00B time="2.208µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=0 livesize=0.00B …
```

cmd/evm: don't overwrite sender account

---

docs/interacting-with-geth/rpc/ns-admin.md

ref: https://github.com/ethereum/go-ethereum/issues/29863
Update `admin_nodeInfo` and `admin_peers` examples to match the current output. Specifically, the `id` field has been changed to a shorter form.

Website: update admin api examples

---

eth/catalyst/api.go

Seems it is checked with the wrong argument

eth/catalyst: get params.ExcessBlobGas but check with params.BlobGasUsed

---

core/vm/runtime/runtime_test.go

The struct-based tracing added in #29189 seems to have caused an issue with the benchmark `BenchmarkTracerStepVsCallFrame`. On master we see the following panic: 
```console
$ go test -v ./core/vm/runtime -bench=BenchmarkTracerStepVsCallFrame -run=^#
goos: darwin
goarch: arm64
pkg: github.com/ethereum/go-ethereum/core/vm/runtime
BenchmarkTracerStepVsCallFrame
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x1019782f0]
goroutine 37 [running]:
github.com/ethereum/go-ethereum/eth/tracers/js.(*jsTracer).OnOpcode(0x140004c4000, 0x0, 0x10?, 0x989680, 0x1, {0x101ea2298, 0x1400000e258}, {0x1400000e258?, 0x14000155928?, 0x10173020c?}, ...)
/Users/matt/dev/go-ethereum/eth/tracers/js/goja.go:328 +0x140 …
```

core/vm/runtime: ensure tracer benchmark calls `OnTxStart`

---

ethclient/ethclient.go

Some chains’ network IDs use hexadecimal such as Optimism ("0xa" instead of "10"), so when converting the string to big.Int, we cannot specify base 10; otherwise, it will encounter errors with hexadecimal network IDs.

ethclient: support networkID in hex format

---

signer/core/apitypes/types.go

This is a simple fix for the issue: https://github.com/ethereum/go-ethereum/issues/30274
TLDR: the problem is isPrimitiveTypeValid uses `fmt.Sprintf` within for-loop. That causes high cpu usage for isPrimitiveTypeValid
This PR simply pre-computes all valid primitive type into a map and use it later.

signer/core: improve performance of isPrimitiveTypeValid function (#30274)

---

core/vm/instructions.go
core/vm/memory.go

Consistently use `uint64` for indices in `Memory` and drop lots of type conversions from `uint64` to `int64`.

core/vm: use uint64 in Memory for indices everywhere

---

tests/transaction_test.go
tests/transaction_test_util.go

Due to https://github.com/ethereum/tests/releases/tag/v10.1, the format of the TransactionTest changed, but it was not properly addressed, causing the test to pass unexpectedly.
This PR follows the structural changes and corrects the TransactionTest to pass correctly.
For reference, a similar issue had occurred previously.
https://github.com/ethereum/go-ethereum/issues/19033

tests: fix TransactionTest to actually run

---

core/types/withdrawal.go
eth/downloader/queue.go

This PR addresses an issue where the size of the downloader queue was not accurately measured. Previously, the size of withdrawals was not included in the queue size calculation, leading to an accumulation of more items than originally intended. This simple fix ensures that withdrawals are now considered, providing an accurate measurement of the queue size.

eth/downloader, core/types: take withdrawals-size into account in downloader queue

---

cmd/evm/runner.go

This PR fixes #30279
We did not use the basefee from the genesis, and instead the defaults were used from `runtime.go/setDefaults`-function
```golang
if cfg.BaseFee == nil {
cfg.BaseFee = big.NewInt(params.InitialBaseFee)
}
```
That method will still be used if it's not provided in genesis. 
----------
With this PR
```
[user@work go-ethereum]$ go run ./cmd/evm  --debug --gas 0xffffff --nomemory=false --json --code 4860005260406000f3 --prestate ./genesis.json run
INFO [08-08|15:55:21.436] Persisted trie from memory database      nodes=1 size=142.00B time="6.577µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=0 livesize=0.00B
{"pc":0,"op":72,"gas":"0xffffff","gasCost":"0x2","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"BASEFEE"} …
```

cmd/evm: fix evm basefee

---

go.mod
go.sum

Release notes: https://github.com/holiman/uint256/releases/tag/v1.3.1

go.mod: update uint256 to 1.3.1

---

beacon/engine/types.go
eth/gasprice/feehistory.go
ethdb/pebble/pebble.go

Use params.MaximumExtraDataSize for extraData length check

beacon/engine, consensus/beacon: use params.MaximumExtraDataSize instead of hard-coded value

---

eth/protocols/snap/gentrie.go
eth/protocols/snap/gentrie_test.go
eth/protocols/snap/sync.go
trie/stacktrie.go

This pull request fixes the https://github.com/ethereum/go-ethereum/issues/30229.
During the snap sync, large storage will be split into several pieces and synchronized
concurrently. Unfortunately, the tradeoff is that the respective merkle trie of each 
storage chunk will be incomplete due to the incomplete boundaries. The trie nodes 
on these boundaries will be discarded, and any dangling nodes on disk will also be 
removed if they fall on these paths, ensuring the state healer won't be blocked.
However, the dangling account trie nodes on the path from the root to the associated
account are left untouched. This means the dangling account trie nodes could 
potentially stop the state healing and break the assumption that the entire subtrie 
should exist if the subtrie root exists. We …

eth/protocols/snap: cleanup dangling account trie nodes due to incomplete storage

---

go.mod
go.sum

missing `go mod tidy` in #30250

go.mod: remove `github.com/julienschmidt/httprouter`

---

core/txpool/blobpool/blobpool.go

the validation process only checks for 'less than', which is inconsistent with the error output

core/txpool/blobpool: fix error message

---

go.mod
go.sum

Includes a fix for MIPS32 support.
Pebble release: https://github.com/cockroachdb/pebble/releases/tag/v1.1.2
Key fix for mips32: https://github.com/cockroachdb/pebble/commit/9f3904a705d60b9832febb6c6494183d92c8f556 (also the only change from v1.1.1.

pebble: Update to v1.1.2

---

core/genesis.go

This PR refactors the genesis initialization a bit, s.th. we only compute the blockhash once instead of twice as before (during hashAlloc and flushAlloc)
This will significantly reduce the amount of memory allocated during genesis init

core: only compute state root once

---

eth/fetcher/tx_fetcher.go
eth/fetcher/tx_fetcher_test.go

This pull request drops the legacy transaction retrieval support before the eth68,
adding the restrictions that transaction metadata must be provided along with
the transaction announment.

eth/fetcher: always expect transaction metadata in announcement

---

eth/backend.go
eth/protocols/eth/discovery.go
eth/protocols/eth/handler.go
eth/protocols/snap/handler.go

Here I am adding a discv5 nodes source into the p2p dial iterator. It's an improved version of #29533.
Unlike discv4, the discv5 random nodes iterator will always provide full ENRs. This means we can apply filtering to the results and will only try dialing nodes which explictly opt into the eth protocol with a matching chain.
I have also removed the dial iterator from snap. We don't have an official DNS list for snap anymore, and I doubt anyone else is running one. While we could potentially filter for snap on discv5, there will be very few nodes announcing it, and the extra iterator would just stall the dialer.

eth: dial nodes from discv5

---

beacon/light/api/light_api.go

blsync was failing if the light endpoint it was provided ended with a `/`. This change should handle the joining more gracefully.

beacon/light: handle endpoint URL more gracefully

---

core/state_processor.go

I thought the withdrawal length check should be placed in `BlockValidator.ValidateBody`
https://github.com/ethereum/go-ethereum/blob/32a1e0643ca5012bda851d65194fb5eb3d83591b/core/block_validator.go#L73-L84
the BlockValidator has the chain config field, and should be feasible to move the check to the ValidateBody.
but there is only a withdrawal root hash check.
and the verifyHeader func in the consensus package ensures a block that before shanghai fork doesn't have a withdrawal hash.
https://github.com/ethereum/go-ethereum/blob/32a1e0643ca5012bda851d65194fb5eb3d83591b/consensus/beacon/consensus.go#L267-L273
so I think the check in the processor is not required and can be removed.

core: remove withdrawal length check for state processor

---

core/vm/evm.go

To allow all error paths in `vm.EVM.create()` to consume the necessary gas, there is currently a pattern of gating code on `if err == nil` instead of returning as soon as the error occurs. The same behaviour can be achieved by abstracting the gated code into a method that returns immediately on error, improving readability and thus making it easier to understand and maintain.
1. There is no new logic. Other than a single new method signature, all code is original.
2. All actions and checks that were previously gated by `if err == nil` are moved to a new `EVM.initNewContract()` method that removes the gating and instead returns immediately on error—this is functionally equivalent but more idiomatic and reduces cognitive load because the reader knows that it's a terminal statement.
An …

vm: simplify error handling in `vm.EVM.create()`

---

internal/build/env.go

When we are building in detached head, we cannot easily obtain the same information as we can if we're in non-detached head. 
However, one thing we _can_ obtain is the git-hash and git-date. Currently, we omit to include the git-date into the build-info, which causes problem for reproducable builds which are on a detached head. This PR should fix it. 
----
Can be tested locally by adding an early return in `ci.go` and then do `go run build/ci.go install` , check out a specific git commit and add some printouts to see the env. 
```
func doInstall(cmdline []string) {
var (
dlgo       = flag.Bool("dlgo", false, "Download Go and build with it")
arch       = flag.String("arch", "", "Architecture to cross build for")
cc         = flag.String("cc", "", "C compiler to cross build with") …
```

internal/build: include git-date on detached head

---

build/ci.go

Our ppa-uploads for mantic are rejected, so might aswell skip attempting it
```
Rejected:
mantic is obsolete and will not accept new uploads.
ethereum-unstable (1.14.9+build30173+mantic) mantic; urgency=low
* git build of 710c3f32ac8e4e5829a6a631dcfb1e0e13a49220
```

build: remove mantic from ppa builds

---

.gitignore

Closes https://github.com/ethereum/go-ethereum/issues/30324
Our `WriteArchive`, used by ci builder, creates files in the repo root, in order to upload.
https://github.com/ethereum/go-ethereum/blob/master/internal/build/archive.go#L80
After we've built the amd64-builds, we go on building remaining architectures. The repo is now flagged as dirty. 
There are more complicated ways to solve this, but the by far simplest is just to fix the gitignore.

gitignore: ignore upload-artefacts

---

eth/catalyst/api.go
eth/catalyst/simulated_beacon.go
eth/catalyst/simulated_beacon_api.go
eth/catalyst/simulated_beacon_test.go

closes #29475, replaces #29657, #30104 
The original problem noted in #29475 was a deadlock where `runReorg` was trying to write to `newTxs` subscription, but the reader was already waiting for `runReorg` to finish in a call to `txpool.Sync()`. This PR solves that issue by creating a worker thread in the simulated beacon API which allows the API's main event handler to never block. Instead, when a new tx or withdrawal event is received it notifies the worker thread to begin constructing a block. It uses a buffered channel to ensure that while the worker is building a block, additional requests to construct a block are not dropped nor blocked on.
Although this was also solved by spawning a new goroutine on each `newTxs` event #29657, an additional issue around handling txs [was …

eth/catalyst: ensure period zero mode leaves no pending txs in pool

---

accounts/abi/abi_test.go
accounts/abi/type.go

A PR to fix: #30266
The ABI pulled from Etherscan sometimes does not conform to the specifications, so before formally processing the ABI, we validate whether the input ABI meets the standards.

accounts/abi: handle ABIs with contract type parameter

---

core/rawdb/database.go
core/rawdb/freezer.go
core/rawdb/freezer_memory.go
core/rawdb/freezer_resettable.go
core/rawdb/freezer_test.go
core/rawdb/table.go
ethdb/database.go
ethdb/remotedb/remotedb.go

These are the leftovers from #24028.

core/rawdb: drop MigrateTable

---

build/ci.go

This PR implements the conclusions from https://github.com/ethereum/go-ethereum/issues/28987#issuecomment-2296075028, that is: 
Building with `--strip-all` as  a ld-flag to the cgo linker, to remove symbols. Without that, some spurious reference to a temporary file is included into the kzg-related library. 
Building with `--build-id=none`, to avoid putting a `build id` into the file. 
cc @vivi365

build: attempt at reproducible builds

---

rpc/client.go
rpc/client_test.go
rpc/subscription.go

fixes #30156
This adds a repro of the linked issue. I fixed it by adding a timeout when issuing the call to unsubscribe.

rpc: add timeout to Client.Unsubscribe

---

cmd/devp2p/dns_cloudflare.go

This PR adds the `dns:read` and `dns:edit` permissions to the required set of permissions checked before deploying an ENR tree to Cloudflare. These permissions are necessary for a successful publish.
**Background**:
The current logic for `devp2p dns to-cloudflare` checks for `zone:edit` and `zone:read` permissions. However, when running the command with only these two permissions, the following error occurs:
```
wrong permissions on zone REMOVED-ZONE: map[#zone:edit:false #zone:read:true]
```
Adding `zone:read` and `zone:edit` to the API token led to a different error:
```
INFO [08-19|14:06:16.782] Retrieving existing TXT records on pos-nodes.hardfork.dev
Authentication error (10000)
```
This suggested that additional permissions were required. I added `dns:read`, but encountered another …

cmd/devp2p: require dns:read, dns:edit permissions for cloudflare deploy 

---

cmd/utils/flags.go
p2p/discover/v4_udp.go

Now that #30302 is in, I think we enable discv5 by default.

cmd/utils,p2p: enable discv5 by default

---

eth/protocols/eth/handlers.go

Proper fix for handling `count=0` get header requests

eth/protocols/eth: handle Count Zero

---

eth/tracers/js/goja.go
eth/tracers/logger/logger.go
eth/tracers/native/call.go
tests/state_test_util.go

Make tracers more robust by handling `nil` as input. Closes https://github.com/ethereum/go-ethereum/issues/30117

eth/tracers: avoid panic if nil-receipt passed to OnTxEnd

---

build/ci.go

The previous clearing of buildid did fully work, turns out we need to set it in `ldflags` 
The go buildid is the only remaining hurdle for reproducible builds, see https://github.com/ethereum/go-ethereum/issues/28987#issuecomment-2306412590 
This PR changes the go build id application note to say literally `none` 
https://github.com/golang/go/issues/33772#issuecomment-528176001:
> This difference is due to the .note.go.buildid section added by the linker. It can be set to something static e.g. -ldflags=-buildid= (empty string) to gain reproducibility.

build: set buildid once more

---

trie/secure_trie.go

This pull request enhances the stateTrie a bit, by avoiding the unnecessary map copy
if the preimage recording is not enabled.

trie: only copy the preimages if necessary

---

beacon/blsync/block_sync_test.go

I managed to run into this error case and was unsure about the reason until I added this error handling. So I think it is worth it to spend the extra three lines to get a proper error message.

beacon/blsync: better error information in test

---

.gitignore

From https://app.travis-ci.com/github/ethereum/go-ethereum/jobs/625441424#L1332
```
$ git status --porcelain
?? geth-alltools-linux-amd64-1.14.9-unstable-0378dc83.tar.gz.asc
?? geth-alltools-linux-amd64-1.14.9-unstable-0378dc83.tar.gz.sig
?? geth-linux-amd64-1.14.9-unstable-0378dc83.tar.gz.asc
?? geth-linux-amd64-1.14.9-unstable-0378dc83.tar.gz.sig
```
These files are generated during signing of download-binaries, and the 'dirty' the vcs for subsequent builds.

gitignore: ignore build signatures

---

core/blockchain.go
core/state/metrics.go
core/state/state_object.go
core/state/statedb.go
triedb/pathdb/disklayer.go

This pull request adds a few more performance metrics, specifically:
- The average time cost of an account read
- The average time cost of a storage read
- The rate of account reads
- The rate of storage reads

core: add metrics for state access

---

core/state/statedb.go
core/state/trie_prefetcher.go
core/state/trie_prefetcher_test.go

This pull request fixes the panic issue in prefetcher once the verkle is activated.

core/state: fix trie prefetcher for verkle

---

p2p/discover/metrics.go

`WriteToUDP` was never called, since `meteredUdpConn` exposed directly all the methods from the underlying `UDPConn` interface.
This fixes the `discover/egress` metric never being updated.

p2p/discover: fix Write method in metered connection

---

accounts/abi/bind/util_test.go
ethclient/simulated/backend_test.go

In few tests the returned error from `SendTransaction` is not being checked. This PR checks the returned err in tests. 
Returning errors also revealed tx in `TestCommitReturnValue` is not actually being sent, and returns err ` only replay-protected (EIP-155) transactions allowed over RPC`. Fixed the transaction by using the `testTx`.

accounts/abi/bind, ethclient/simulated: check SendTransaction error in tests

---

core/state/journal.go
core/state/state_object.go
core/state/statedb.go
core/state/statedb_fuzz_test.go
core/state/statedb_test.go

This is a follow-up to #29520, and a preparatory PR to a more thorough change in the journalling system.
This PR hides the journal-implementation details away, so that the statedb invokes methods like `JournalCreate`, instead of explicitly appending journal-events in a list. This means that it's up to the journal whether to implement it as a sequence of events or aggregate/merge events. 
This PR also makes it so that management of valid snapshots is moved inside the journal, exposed via the methods `Snapshot() int` and `RevertToSnapshot(revid int, s *StateDB)`. 
JournalSetCode journals the setting of code: it is implicit that the previous values were "no code" and emptyCodeHash. Therefore, we can simplify the setCode journal.
The self-destruct journalling is a bit strange: we allow the …

core/state: semantic journalling (part 1)

---

signer/core/apitypes/signed_data_internal_test.go
signer/core/apitypes/types.go

`resolves`: https://github.com/ethereum/go-ethereum/issues/30183
When attempting to hash a typed data struct that includes a type reference with a fixed-size array, the validation process fails. According to EIP-712, arrays can be either fixed-size or dynamic, denoted by `Type[n]` or `Type[]` respectively, although it appears this currently isn't supported.
This PR introduces a change to the validation logic to accommodate types containing fixed-size arrays.

signer/core/apitypes: support fixed size arrays for EIP-712 typed data

---

beacon/engine/gen_ed.go
beacon/engine/types.go
consensus/beacon/consensus.go
core/chain_makers.go
core/state/statedb.go
core/state_processor.go
core/state_processor_test.go
core/types/block.go
core/types/gen_header_json.go
go.mod
go.sum
trie/verkle.go

This PR adds the bulk verkle witness+proof production at the end of block production. It reads all the data from the tree in one swoop.
For the PR to work, we still need:

consensus/beacon, core/types: add verkle witness builder

---

core/genesis_test.go
core/state/access_events.go
core/state/access_events_test.go
core/state/database.go
core/state/statedb.go
core/state_processor_test.go
core/state_transition.go
core/vm/operations_verkle.go
trie/secure_trie.go
trie/utils/verkle.go
trie/utils/verkle_test.go
trie/verkle.go
trie/verkle_test.go

This PR implements changes related to [EIP-6800](https://eips.ethereum.org/EIPS/eip-6800) and [EIP-4762](https://eips.ethereum.org/EIPS/eip-4762) spec updates.
A TL;DR of the changes is that `Version`, `Balance`, `Nonce` and `CodeSize` are encoded in a single leaf named `BasicData`. For more details, see the [_Header Values_ table in EIP-6800](https://eips.ethereum.org/EIPS/eip-6800#header-values).
The motivation for this was simplifying access event patterns, reducing code complexity, and, as a side effect, saving gas since fewer leaf nodes must be accessed.

trie, core/state: Nyota EIP-6800 & EIP-4762 spec updates

---

eth/tracers/internal/tracetest/makeTest.js

When creating prestate tracer tests in diff mode, the diff mode flag has to be included in the resulting test JSON. This change makes sure the flag is included in the JSON when it is passed to makeTest.

Include tracerConfig in created tracing test

---

core/state/state_object.go

This pull request fixes a flaw in prefetcher.
In verkle tree world, both accounts and storage slots are committed into a single tree instance
for state hashing. If the prefetcher is activated, we will try to pull the trie for the prefetcher for
performance speedup. 
However, we had a special logic to skip pulling storage trie if the storage root is empty. While
it's true for merkle as we have nothing to do with an empty storage trie, it's totally wrong for
verkle. The consequences for skipping pulling is the storage changes are committed into trie
A, while the account changes are committed into trie B (pulled from the prefetcher), boom.

core/state: pull the verkle trie from prefetcher for empty storage root

---

node/rpcstack_test.go

This PR fixes a flaky jwt-test. 
The test is a jwt "from one second in the future". The test passes; the reason for this is that the CI-system is slow, and by the time the jwt is actually evaluated, that second has passed, and it's no longer future.
Alternative to #30380

node: fix flaky jwt-test

---

build/ci.go

This increases the timeout for the go tests on ci, this should prevent travis from erroring.
see: https://app.travis-ci.com/github/ethereum/go-ethereum/jobs/625803693

build: increase go test timeout

---

core/state/journal.go

This pull request replaces the field pointer in journal entry with the field itself, especfically the address of mutated account.
While it will introduce the extra allocation cost, but it's easier for code reading. Let's measure the overhead overall to see if the change is acceptable or not.
**BENCHMARK REQUIRED**

core/state: get rid of field pointer in journal

---

cmd/devp2p/internal/ethtest/suite.go
eth/fetcher/tx_fetcher.go
eth/fetcher/tx_fetcher_test.go

This PR fixes an issue with blob transaction propagation due to the blob transation txpool rejecting transactions with gapped nonces. The specific changes are:
- fetch transactions from a peer in the order they were announced to minimize nonce-gaps (which cause blob txs to be rejected
- don't wait on fetching blob transactions after announcement is received, since they are not broadcast
Testing:
- unit tests updated to reflect that fetch order should always match tx announcement order
- unit test added to confirm blob transactions are scheduled immediately for fetching
- running the PR on an eth mainnet full node without incident so far

eth/fetcher: fix blob transaction propagation

---

core/state/snapshot/disklayer.go
core/state/snapshot/generate.go
core/state/snapshot/snapshot.go

#29995 has been reverted due to an unexpected flaw in the state snapshot process. 
Specifically, it attempts to stop the state snapshot generation, which could potentially
cause the system to halt if the generation is not currently running.
This pull request ports the changes made in #29995 and fixes the flaw.

core/state/snapshot: port changes from 29995

---

beacon/engine/types.go
eth/catalyst/api.go

h/t @MariusVanDerWijden for finding and fixing this on devnet 3.
I made the mistake of thinking `PayloadVersion` was correlated with the `GetPayloadVX` method, but it actually tracks which version of `PayloadAttributes` were passed to `forkchoiceUpdated`. So far, Prague does not necessitate a new version of fcu, so there is no need for `PayloadV4`.

beacon/engine/types: remove PayloadV4

---

core/vm/operations_acl.go

Remove redundant address presence check in `makeGasSStoreFunc`.
This PR simplifies the `makeGasSStoreFunc` function by removing the redundant check for address presence in the access list. The updated code now only checks for slot presence, streamlining the logic and eliminating unnecessary panic conditions.
This change removes the unnecessary address presence check, simplifying the code and improving maintainability without affecting functionality. The previous panic condition was intended as a canary during the testing phases (i.e. _YOLOv2_) and is no longer needed.

core/vm: remove panic when address is not present

---

eth/filters/filter_system_test.go

Hi, during a CI run I observed the following:
```
fatal error: concurrent map read and map write
goroutine 88 [running]:
github.com/ava-labs/subnet-evm/eth/filters.TestPendingTxFilterDeadlock(0xc0061ef860)
/home/runner/work/subnet-evm/subnet-evm/eth/filters/filter_system_test.go:[84]
```
seems this access in the test should be protected like the other accesses in `api.go`

eth/filters: prevent concurrent access in test

---

core/rawdb/freezer.go

Fixes https://github.com/ethereum/go-ethereum/issues/29793

core/rawdb: correct description of freezer

---

core/state/access_events.go
core/state/access_events_test.go
core/tracing/hooks.go
core/vm/evm.go

Implementation of [this EIP-4762 update](https://github.com/ethereum/EIPs/pull/8867).

core/{state, vm}: Nyota contract create init simplification

---

p2p/enode/localnode.go
p2p/enode/node.go
p2p/enode/node_test.go
p2p/enr/entries.go

Add `quic` entry to the ENR as proposed in https://github.com/ethereum/consensus-specs/pull/3644
Allowing to read [Lighthouse `quic` port](https://github.com/sigp/lighthouse/blob/d6ba8c397557f5c977b70f0d822a9228e98ca214/book/src/developers.md?plain=1#L20-L26) from ENR.

p2p/enode: add quic ENR entry

---

core/txpool/blobpool/blobpool.go

This situation(`len(txs) == 0`) rarely occurs, but if it does, it will panic.

core/txpool/blobpool: avoid possible zero index panic

---

internal/era/e2store/e2store_test.go
internal/era/era_test.go
internal/ethapi/api_test.go
internal/ethapi/transaction_args_test.go
internal/flags/flags_test.go
internal/guide/guide_test.go
internal/jsre/completion_test.go
internal/jsre/jsre_test.go
internal/utesting/utesting_test.go

Continuation of https://github.com/ethereum/go-ethereum/pull/28546

internal: run tests in parallel

---

core/types/transaction_signing.go

Having just a single return point in methods that build signers makes it easier for forks of go ethereum to add their own signers that delegate to the underlying signer chain, since they can intercept the signer chain at a single point.
At celo we are currently transitioning to be an L2 based on the optimism codebase and we have a number of additional transaction types that we have extended vanilla ethereum with, these transaction types require custom signing therefore requiring us to modify the signer creation functions.
In order to lessen the burden of being a fork of op-geth and consequently go-ethereum we are trying to ensure that our changes are minimally invasive to the codebase, we've partially achieved that for transaction signing by having an overlay signer that handles our added …

core/types: more easily extensible tx signing

---

core/stateless/witness.go
core/txpool/blobpool/blobpool.go
core/types/transaction.go
trie/trie.go

- preallocate capacity for map
- avoid `reinject` adding empty value
- use `maps.Copy`

core, trie: prealloc capacity for maps

---

core/tracing/CHANGELOG.md
core/tracing/hooks.go

Add changes from #30409 and #29338 to changelog.
Btw @gballet seems like `GasChangeWitnessContractCreation` is unused.

core/tracing: add verkle gas change reasons to changelog

---

core/genesis.go

Balance being null causes `getGenesisState` to fail as the balance field is required in json marshaling of an account.

genesis: fix dev mode alloc

---

core/blockchain_repair_test.go
core/blockchain_sethead_test.go
core/blockchain_snapshot_test.go
core/blockchain_test.go

After this PR, https://github.com/ethereum/go-ethereum/pull/28187, the way to set the default logger is different. This PR only updates the way to set logger in some test cases' comments that existed in the codebase (since this commit https://github.com/ethereum/go-ethereum/commit/b63e3c37a6). Although I am not sure if it a good way to leave the code in the comment, it truly makes me more efficiently to debug and fix the failing test cases.

core: minor fix for the log wrapper with debug purpose

---

ethdb/pebble/pebble.go

- Handle error in pebble module
- Use `common.CopyBytes`

ethdb/pebble: handle error in pebble module

---

.github/CODEOWNERS

In order to make the release process smoother, grant merge access to the `params/` directory to all team members who volunteered to do releases.

.github: add release maintainers to params/ CODEOWNERS

---

.travis.yml

This should fix https://github.com/ethereum/go-ethereum/issues/30471. See investigation in https://github.com/ethereum/go-ethereum/pull/30478 for more background.

build: fix macos builds by working around travis osx flaw

---

.travis.yml

This is a work-around for a strange issue with travis, specifically, `os=osx, go: 1.23.1`. When this is used, the actual go that ends up being used is `go1.19.4 darwin/amd64 `. 
Using `which go`, it told me that the `go` in the path was a softlink at `/Users/travis/gopath/bin/go1.23.1  `. However, this was not true: using `command -v go`, it told me that the actual `go` that was used is a softlink at  `/usr/local/bin/go`. 
This change rewrites the `/usr/local/bin/go` softlink to point to the binary at `/Users/travis/gopath/bin/go1.23.1`, so we get the right go-version.

travis: work around travis/osx/go1.23 setup bug

---

cmd/utils/flags.go

I think `setEtherbase` should continue to handle `MinerPendingFeeRecipientFlag` even if `MinerEtherbaseFlag` is specified.

cmd/utils: fix `setEtherbase`

---

core/state/statedb.go

This pull request skips the state snapshot update if the base layer is not existent, 
eliminating the numerous warning logs after an unclean shutdown.
Specifically, Geth will rewind its chain head to a historical block after unclean shutdown
and state snapshot will be remained as unchanged waiting for recovery. During this 
period of time, the snapshot is unusable and all state updates should be ignored/skipped
for state snapshot update. This pull request fixes this "flaw".
The warning logs:
```
^[[33mWARN ^[[0m[09-23|10:18:48.379] Failed to update snapshot tree           ^[[33mfrom^[[0m=6f23c3..2d5e28 ^[[33mto^[[0m=e07088..376d9e ^[[33merr^[[0m="parent [0x6f23c30f2a9a4ec370baace9d3c05f974009e1dae8d1a3af5f8644a2ad2d5e28] snapshot missing"
^[[33mWARN ^[[0m[09-23|10:18:48.379] Failed to cap …
```

core/state: commit snapshot only if the base layer exists

---

internal/ethapi/api.go

closes https://github.com/ethereum/go-ethereum/issues/30467 .  In #27720 , we introduced RPC global gas cap.  There seems to be precedent in the code that a gas cap of 0 means an unlimited gas cap.
This PR fixes that behavior for simulated calls.

internal/ethapi/api: for simulated calls, set gaspool to max value if global gas cap is 0

---

core/rawdb/accessors_trie.go

When first start `geth` with the flags:
export FLAGS="--state.scheme=path --syncmode=full"
geth
...
--authrpc.addr=0.0.0.0 \
--authrpc.jwtsecret=/geth/jwt.hex \
--allow-insecure-unlock \
--state.scheme=path \
"$FLAGS"
This is the illegal log message, and then `geth` can normally start:
`State scheme set by user                 scheme="path --syncmode=full"`
Finally, `geth` started with `snap` sync mode and `hash` state scheme, it's not what I want.

core/rawdb: make sure specified state scheme is valid

---

core/tracing/hooks.go
core/vm/interpreter.go

Extending the `OpContext` interface:
- adding `ContractCode` - returns the code of the contract being executed.
Previous implementation of tracing had access to the contract code in Scope, the current one does not. And it was important in the context of custom tracers(e.g., in my case 👀).
So in reference to the conversation on discord (#tracing channel), I add such functionality.
I tried to follow the current naming convention, lmk if i should fix/change something!

core/tracing, core/vm: add ContractCode to the OpContext

---

p2p/discover/v4_lookup_test.go
p2p/enode/nodedb.go

This PR fixes two tests, which had a tendency to sometimes write to the `*testing.T` `log` facility. This is considered a major breach of etiquette by `golang`.  This PR fixes it by using waitgroups to ensure that the handler/logwriter terminates before the test exits. 
closes #30505

p2p/discover: fix flaky test which wrote to test.log after completion

---

go.mod
go.sum

This update should only affect the fuzzers, as far as I know. But it seems like it might also fix some arm/macos compilation issue in https://github.com/ethereum/go-ethereum/issues/30494
Closes #30494 (I think)

deps: update supranational/blst

---

core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go

This PR reverts part of #30437. 
I failed to take note of this at the time, but now I am unsure if the "avoid reinject adding empty value" part was correct. 
Previously, `reinject` would contains an empty list for the address `addr`, and the blobpool Reset function would then call `p.recheck` on that `addr`
```golang
if reinject, inclusions := p.reorg(oldHead, newHead); reinject != nil {
var adds []*types.Transaction
for addr, txs := range reinject {
// Blindly push all the lost transactions back into the pool
for _, tx := range txs {
if err := p.reinject(addr, tx.Hash()); err == nil {
adds = append(adds, tx.WithoutBlobTxSidecar())
}
}
// Recheck the account's pooled transactions to drop included and
// invalidated ones
p.recheck(addr, inclusions)
}
if len(adds) > 0 { …
```

core/txpool/blobpool: return all reinject-addresses

---

core/txpool/blobpool/blobpool.go
core/txpool/legacypool/legacypool.go
core/txpool/subpool.go
core/txpool/txpool.go
eth/catalyst/simulated_beacon.go

Reverts ethereum/go-ethereum#30495
You are free to create a proper Clear method if that's the best way. But one that does a proper cleanup, not some hacky call to set gas which screws up logs, metrics and everything along the way. Also doesn't work for legacy pool local transactions.
The current code had a hack in the simulated code, now we have a hack in live txpooling code. No, that's not acceptable. I want the live code to be proper, meaningful API, meaningful comments, meaningful implementation.

Revert "core/txpool, eth/catalyst:  ensure gas tip retains current value upon rollback"

---

p2p/discover/common.go
p2p/discover/table.go
p2p/discover/v4_udp.go
p2p/discover/v5_udp.go

This is for fixing Prysm integration tests.

p2p/discover: add config option for disabling FINDNODE liveness check

---

core/txpool/blobpool/blobpool.go

Use types.Sender(signer, tx) to utilize the transaction's sender cache and avoid repeated address recover.

core/txpool/blobpool: use types.Sender instead of signer.Sender

---

.travis.yml
Dockerfile
Dockerfile.alltools
build/ci.go

This is a work in progress of a `buildx`-based docker image creator. Our current builder is very complicated: 
- Use multiple builders, on different platforms (arm vs amd). 
- They build and push their own native platform
- One of them (random which, decided by a race) generates a `manifest` image, which basically says "stable == stable-amd64 and/or stable/amd64". 
With docker [buildx](https://docs.docker.com/reference/cli/docker/buildx/), we can build all archs in one go.

 build: use buildx to build multi-platform docker images

---

eth/catalyst/simulated_beacon.go
ethclient/simulated/backend_test.go

Fixes https://github.com/ethereum/go-ethereum/issues/30448

eth/catalyst: use setcanonical instead of sethead in simulated fork

---

cmd/geth/chaincmd.go
cmd/utils/flags.go

This PR removes the dependencies on `lightchaindata` db as the light protocol has been deprecated and removed from the codebase.

cmd/geth: remove deprecated lightchaindata db

---

core/rawdb/freezer_batch.go
core/rawdb/freezer_table.go
core/rawdb/freezer_table_test.go
triedb/pathdb/disklayer.go
triedb/pathdb/nodebuffer.go

This pull request removes the `fsync` of index files in freezer.ModifyAncients function for 
performance gain.
Originally, fsync is added after each freezer write operation to ensure the written data is truly
transferred into disk. Unfortunately, it turns out `fsync` could be relatively slow, especially on
macOS. see https://github.com/ethereum/go-ethereum/issues/28754 for more information.
In this pull request, fsync for index file is removed as it turns out index file can be recovered
even after a unclean shutdown. But fsync for data file is still kept, as we have no meaningful
way to validate the data correctness after unclean shutdown.
---
**But why do we need the `fsync` in the first place?** 
As it's necessary for freezer to survive/recover after the machine crash (e.g. power …

core/rawdb: freezer index repair

---

beacon/light/head_tracker.go

`update.Validate()` can be called before grabbing the lock.

beacon/light: optimize lock usage in `HeadTracker`

---

eth/tracers/api.go

`debug_traceBlockByNumber` may return incorrect result on some blocks, with JS tracers.
This PR tries to fix it.
`traceBlockParallel` does not apply `ProcessBeaconBlockRoot` and `ProcessParentBlockHash`  before executing block's transactions, which may cause some transactions trace to report unexpected reverted errors.
request
```
{
"method": "debug_traceBlockByNumber",
"params": [
"0x128c38d",
{
"tracer": "callTracerLegacy"
}
],
"id": 1,
"jsonrpc": "2.0"
}
```
In response, tx [`0x8236b9e4749102df80e43130d7df505cb7e9b3036c2fa8759867b5fbbf837370`](https://etherscan.io/tx/0x8236b9e4749102df80e43130d7df505cb7e9b3036c2fa8759867b5fbbf837370) would show `"error": "execution reverted"`, that's wrong.
```
{
"txHash": "0x8236b9e4749102df80e43130d7df505cb7e9b3036c2fa8759867b5fbbf837370",
"result": …
```

eth/tracers: do system contract processing prior to parallel-tracing 

---

eth/downloader/downloader_test.go
eth/protocols/eth/handlers.go
eth/protocols/eth/protocol.go

Block no longer has Requests.
It wasn't removed in #30425

eth/protocols/eth: remove Requests in block body

---

core/tracing/hooks.go

The previous tracing implementation gave access to `TransientState`, in the current one is missing, so I extended the interface. I checked and no hooks collect it. 
This gives the ability to analyze the transient state for custom tracers (e.g. mine).

core/tracing: add GetTransientState method to StateDB interface for accessing transient state data

---

cmd/evm/internal/t8ntool/execution.go
core/blockchain_test.go
core/chain_makers.go
core/genesis.go
core/state_processor.go
core/types/block.go
eth/catalyst/simulated_beacon.go
eth/catalyst/simulated_beacon_test.go
eth/tracers/internal/tracetest/supply_test.go
internal/ethapi/testdata/eth_getBlockReceipts-block-with-blob-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-block-with-contract-create-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-block-with-dynamic-fee-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-contract-call-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-transfer-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-tag-latest.json
internal/ethapi/testdata/eth_getTransactionReceipt-blob-tx.json
internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-tx.json
internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-with-access-list.json
internal/ethapi/testdata/eth_getTransactionReceipt-dynamic-tx-with-logs.json
internal/ethapi/testdata/eth_getTransactionReceipt-normal-transfer-tx.json
internal/ethapi/testdata/eth_getTransactionReceipt-with-logs.json
miner/worker.go
params/config.go
params/protocol_params.go

This is a redo of #29052 based on newer specs. Here we implement EIPs scheduled for the Prague fork:
- EIP-7002: Execution layer triggerable withdrawals
- EIP-7251: Increase the MAX_EFFECTIVE_BALANCE
Co-authored-by: @lightclient

all: implement EIP-7002 & EIP-7251

---

beacon/blsync/engineclient.go
beacon/engine/types.go
eth/catalyst/api_test.go
miner/payload_building.go

This change brings geth into compliance with the current engine API specification for the Prague fork. I have moved the assignment of ExecutionPayloadEnvelope.Requests into BlockToExecutableData to ensure there is a single place where the type is removed.
While doing so, I noticed that handling of requests in the miner was not quite correct for the empty payload. It would return `nil` requests for the empty payload even for blocks after the Prague fork. To fix this, I have added the emptyRequests field in miner.Payload.

beacon/engine: strip type byte in requests

---

internal/ethapi/transaction_args.go

Beyond "they weren't being used so I deleted them", this is consistent because:
calculating a reasonable tx blob fee cap (`max_blob_fee_per_gas * total_blob_gas`) only depends on the excess blob gas of the parent header.  The parent header is assumed to be correct, so the method should not be able to fail and return an error.

internal/ethapi:  remove unused parameters, error return from `TxArgs.setCancunFeeDefaults`

---

beacon/engine/gen_epe.go
beacon/engine/types.go

Omit null `witness` field from payload envelope.
Currently, JSON encoded payload types always include `"witness": null`, which, I believe, is not intentional.

fix: omit null witness field from payload envelope

---

ethdb/pebble/pebble.go

Since forever we've been using 2MB database files, ever since the LevelDB era. We've sometimes attempted to change these to something different, but compaction-induced db writes always blew up disk IO tens fold.
A lot of time passed however, and nowadays we're using a completely different data scheme (path vs hash), which has much more localized writes. Out of curiosity I've ran a benchmark changing back the levels to exponentially increasing ones.
Naturally, the obvious effect is the number of files:
- `master` branch with 2MB files across all levels has about 160K data files in the datastore.
- `pr` branch has about 9.2K data files in the datastore.
These have been expected, but the more interesting question is how this affects performance (charts: green == master, yellow == PR)?
Full …

ethdb/pebble: switch to increasing level sizes

---

core/blockchain.go
core/blockchain_test.go

~~Opening this as a draft to have a discussion.~~ Pressed the wrong button
I had [a previous PR ](https://github.com/ethereum/go-ethereum/pull/24616)a long time ago which reduced the peak memory used during reorgs by not accumulating all transactions and logs.
This PR reduces the peak memory further by not storing the blocks in memory.
However this means we need to pull the blocks back up from storage multiple times during the reorg. 
I collected the following numbers on peak memory usage: 
// Master: 			BenchmarkReorg-8   	   10000	    899591 ns/op	  820154 B/op	    1440 allocs/op 	1549443072 bytes of heap used
// WithoutOldChain: BenchmarkReorg-8   	   10000	    1147281 ns/op	  943163 B/op	    1564 allocs/op 	1163870208 bytes of heap used
// WithoutNewChain: BenchmarkReorg-8   	   10000 …

core: reduce peak memory usage during reorg

---

cmd/evm/internal/t8ntool/execution.go
cmd/evm/internal/t8ntool/transition.go
cmd/utils/flags.go
core/tracing/hooks.go
core/vm/evm.go
core/vm/runtime/runtime_test.go
eth/backend.go
eth/tracers/api.go
eth/tracers/dir.go
eth/tracers/internal/tracetest/calltrace_test.go
eth/tracers/internal/tracetest/flat_calltrace_test.go
eth/tracers/internal/tracetest/prestate_test.go
eth/tracers/js/goja.go
eth/tracers/js/tracer_test.go
eth/tracers/live.go
eth/tracers/live/noop.go
eth/tracers/live/supply.go
eth/tracers/native/4byte.go
eth/tracers/native/call.go
eth/tracers/native/call_flat.go
eth/tracers/native/call_flat_test.go
eth/tracers/native/mux.go
eth/tracers/native/noop.go
eth/tracers/native/prestate.go

- The ChainConfig was exposed to tracers via VMContext passed in `OnTxStart`. This is unnecessary specially looking through the lens of live tracers as chain config remains the same throughout the lifetime of the program. It was there so that native API-invoked tracers could access it. So instead we moved it to the constructor of API tracers.
- Change the default config of the tracers to be `{}` instead of nil. This way an extra nil check can be avoided.
- Rename `supply` struct to `supplyTracer`.
- Un-export some hook definitions.

eth/tracers: various fixes

---

miner/payload_building.go

Fixes an issue missed in #30576 where we send empty requests for a full payload being resolved, causing hash mismatch later on when we get the payload back via `NewPayload`.

miner: send full request when resolving full payload

---

beacon/engine/types.go
core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go
core/txpool/blobpool/lookup.go
core/txpool/legacypool/legacypool.go
core/txpool/subpool.go
core/txpool/txpool.go
eth/catalyst/api.go

Implements [engine_getBlobsV1](https://github.com/ethereum/execution-apis/pull/559).
The getBlobs method requests blobs via their own hashes, not via the transaction hashes (supposedly the consensus client does not know the hash of the transactions, at least not yet when it wants to call this method). Due to that, a new index is needed in the blobpool that maps blob hashes to a set of transaction hashes (it can happen that the same blob is present in multiple transactions).
This PR does basically that, starts tracking the blob hash to tx hash mappings in the blob pool in addition to everything it does now. With that added, it becomes possible to look up transactions from blob hashes, and then to look up the billy storage items from those and then extract the actual blob data from disk.

beacon/engine, core/txpool, eth/catalyst: add engine_getBlobsV1 API

---

build/ci.go

This is kind of an experiment. Originally we used travis arm64 to build, and had to reduce build concurrency due to limited memory. Nowadays we don't cross build, only to docker, and on that we use amd64 builders. This PR is an attempt to speed up the docker image builders so it doesn't take 45 minutes.
Then again, it could happen that the CI env var isn't passed to docker at all. Oh well, I don't really see a reason to constrain ourselves. We can revert if something downstream borks.

build: reenable building arm64 concurrently

---

core/state/state_object.go
core/state/statedb.go
core/state/trie_prefetcher.go
core/state/trie_prefetcher_test.go

This is a trivial change, which seems large-sh, but it's a nobrainer copy-paste fix.
The state prefetched works on both accounts and addresses. The former is 20 bytes the latter 32. To avoid duplicating code, it was implemented by  `[]byte` type. Unfortunately, this turned out to be an issue: whereas previously addresses and hashes passed around in statedb were by value on the stack, all of a sudden the `addr[:]` conversion forces *all* of them onto the heap, increasing allocations immensely.
This PR "simply" splits the address and hash tracking inside the prefetcher so it can pass around stack values instead of heap items. Fixes the issue, allocation count for my burnt pix benchmarker:
Before:
```
EVM gas used:    5642735088
execution time:  12.939730959s
allocations:     5372681 …
```

core/state: fix runaway alloc caused by prefetcher heap escape

---

build/ci.go
internal/build/file.go

Our CI build script should not depend on Ethereum data types. There's still an indirect dependency through params.version, but I'll do that in a followup since there's are multiple possible approaches.

build: get rid of ci.go -> common direct dependency

---

consensus/clique/clique.go
miner/payload_building_test.go

Clique currently depends on the `accounts` package. This was a bit of a big cannon even in the past, just to pass a signer "account" to the Clique block producer. Either way, nowadays Geth does not support clique mining any more, so by removing that bit of functionality from our code, we can also break this dependency.
Clique should ideally be further torn out, but this at least gets us one step closer to cleanups.

consensus/clique, miner: remove clique -> accounts dependency

---

eth/tracers/internal/tracetest/util.go

I have a test locally, but the callTracer test always complains `invalid opcode: PUSH0`
if we want to test chain after the Merge, then the Random(aka prevRandao) should be not be nil
https://github.com/ethereum/go-ethereum/blob/a5fe7353cff959d6fcfcdd9593de19056edb9bdb/core/vm/evm.go#L128
https://github.com/ethereum/go-ethereum/blob/a5fe7353cff959d6fcfcdd9593de19056edb9bdb/params/config.go#L923-L925

eth/tracers/internal/tracertest: add missing Random to call context

---

core/state_processor.go

core: fix tracing of pre-block processors

---

beacon/blsync/config.go
cmd/blsync/main.go

This PR adds the beacon chain config for the holesky testnet. It also updates beacon checkpoints for Mainnet and Sepolia.

beacon/blsync: add holesky config and update checkpoints

---

cmd/geth/config.go

This is a super insignificant change, it just annoyed me. The datadir path is generated from the `clientIdentifier`, so it felt appropriate to also generate the IPC path from the same variable instead of hard coding it.

cmd/geth: avoid hard coding the IPC name

---

core/rawdb/accessors_indexes_test.go
core/rawdb/freezer.go
core/rawdb/freezer_memory.go
core/rawdb/freezer_resettable.go
ethdb/database.go

This clears up the ethdb.Database interface, making it more understandable that it is basically just the AncientStore and KeyValueStore combined. Also removes a few interfaces that are not needed anymore, and makes a few types implement the `AncientStater` interface

ethdb: refactor Database interface

---

appveyor.yml
build/ci.go
internal/build/file.go

This PR cleans up the go mod tidy and go generate checker, moving some code into internal files. In addition, it adds a new "bad dependency" checker where we can add some package deps that should be avoided, but tend to accidentally leak in (e.g. rawdb -> leveldb).

appveyor, build, internal: ci.go cleanups, add package dep checker

---

beacon/light/committee_chain.go

This field is a duplicate of [`UpdateScore.SignerCount`](https://github.com/ethereum/go-ethereum/blob/9326a118c7c074a6c719b381033845c47c1168f5/beacon/light/committee_chain.go#L108) and never referenced.

beacon/light: remove unused CommitteeChain.signerThreshold

---

docs/developers/evm-tracing/built-in-tracers.md

Follows #30648, add the document of `disableCode,disableStorage`, @s1na PTAL.

docs(tracer/prestate): add disableCode,disableStorage

---

core/state/statedb.go
core/vm/evm.go
core/vm/instructions.go

I think the core code should generally be agnostic about the witness and the statedb layer should determine what elements need to be included in the witness. Because code is accessed via `GetCode`, and `GetCodeLength`, the statedb will always know when it needs to add that code into the witness.
The edge case is block hashes, so we continue to add them manually in the implementation of `BLOCKHASH`.
It probably makes sense to refactor statedb so we have a wrapped implementation that accumulates the witness, but this is a simpler change that makes #30078 less aggressive.

core: add code to witness when state object is accessed

---

cmd/utils/flags.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go

This is a flag leftover from the swarm era. No need to deprecate it, it's been useless/dead forever now.

cmd/utils, eth/ethconfig: remove some ancient leftover flag

---

cmd/blsync/main.go
cmd/devp2p/discv4cmd.go
cmd/devp2p/discv5cmd.go
cmd/evm/main.go
cmd/evm/runner.go
cmd/geth/chaincmd.go
cmd/geth/config.go
cmd/geth/consolecmd.go
cmd/geth/dbcmd.go
cmd/geth/main.go
cmd/geth/snapshot.go
cmd/geth/verkle.go
internal/flags/helpers.go

This is a noop change to not have custom code for stdlib functionality.

internal/flags: remove Merge, it's identical to slices.Concat

---

cmd/utils/flags.go
internal/flags/flags.go
internal/flags/helpers.go

Currently we have a custom TextMarshalerFlag. It's a nice idea, allowing anything implementing text marshaller to be used as a flag. That said, we only ever used it in one place because it's not that obvious how to use and it needs some boilerplate on the type itself too, apart of the heavy boilerplate got the custom flag.
All in all there's no *need* to drop this feature just now, but while porting the cmds over to cli @v3, all other custom flags worker perfectly, whereas this one started crashing deep inside the cli package. The flag handling in v3 got rebuild on generics and there are a number of new methods needed; and my guess is that maybe one of them doesn't work like this flag currently is designed too.
We could definitely try and redesign this flag for cli v3... but all that …

internal/flags: remove low-use type TextMarshalerFlag

---

build/ci.go

Since functions from `slices` package are already used extensively, this makes it more consistent with other places in the project.

build: use slices.Clone for copying slice

---

tests/fuzzers/bls12381/bls12381_fuzz.go

This PR updates the fuzzing verbosity a bit, in case of mismatches

tests/fuzzers/bls12381: more verbose fuzzing-output

---

core/txpool/txpool.go
core/txpool/validation.go

I noticed that these two responses can make their way back to the transaction
submitter when submitting unsupported tx types.
Adding the extra context makes it easier for the submitter to understand what
went wrong. Particularly in the case of the invalid sender response, which is
returned when an unsupported transaction type is encountered.

core/txpool: Improve error responses

---

eth/catalyst/api_test.go

This test depends on a 100ms timer, which fails quite often, messing up our pipelines. Hook directly into the internal version of getPayload which has the capacity to wait for the full payload before returning. This might not be absolutely correct from a test perspective, but it beats failing ci. The alternative would be to expose the full build hook into the outside, but it might be a bit overkill for this scenario.

eth/catalyst: make engine api test time independent

---

core/vm/runtime/runtime.go

While updating goevmlab, I noticed that the way I invoked the executions, using the `core/vm/runtime` helpers, I didn't get any callbacks on the tx end. This PR fixes it by invoking them.

core/vm/runtime: invoke tx-end hook

---

core/bench_test.go
core/rawdb/accessors_chain_test.go
core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go
core/txpool/blobpool/evictheap_test.go
core/txpool/validation.go
eth/tracers/internal/tracetest/calltrace_test.go
eth/tracers/tracers_test.go
log/logger_test.go
metrics/sample_test.go
triedb/pathdb/difflayer_test.go

This PR fixes some issues with benchmarks

all: fix issues with benchmarks

---

cmd/utils/flags.go

closes https://github.com/ethereum/go-ethereum/issues/30304
We already use `DirectoryFlag` for `authrpc.jwtsecret` which expands the tilde, so this should work out of the box

cmd/utils: change blssync.JWTSecretFlag to DirectoryFlag

---

ethclient/ethclient.go
ethclient/ethclient_test.go
ethclient/example_test.go
ethclient/types_test.go

Here I'm adding a new helper function that extracts the revert reason of a contract call.
Unfortunately, this aspect of the API is underspecified. See these spec issues for more detail:
- https://github.com/ethereum/execution-apis/issues/232
- https://github.com/ethereum/execution-apis/issues/463
- https://github.com/ethereum/execution-apis/issues/523
The function added here only works with Geth-like servers that return error code `3`. We will not be able to support all possible servers. However, if there is a specific server implementation that makes it possible to extract the same info, we could add it in the same function as well.

ethclient: add RevertErrorData function and example

---

ethclient/gethclient/gethclient_test.go

Add Testcase for createAccessList when user requested gasPrice is less than baseFee
In test, the baseFee for first block is 875000000. So, I just input the gasPrice '1'.
This PR is derived from this issue( #30145 ), so more specific information plz check this issue.

ethclient/gethclient: testcase for createAccessList, make tabledriven

---

internal/ethapi/api.go
internal/ethapi/transaction_args.go
internal/ethapi/transaction_args_test.go

totally WIP, and I'm not sure this is correct.  I need to further validate this tomorrow.
Should close https://github.com/ethereum/go-ethereum/issues/30145 .  The problem is that for `AccessList`, we are filling transaction fields with `TransactionArgs.setDefaults` which afaict is meant to validate provided fields and give proper values to missing fields based on the state at the current chain tip.
`eth_call`-like methods seem to populate fields using `TransactionArgs.CallDefaults`, which also seems appropriate for `eth_accessList` as it is `eth_call`-like under the hood:  it can be executed against historical blocks.
The referenced issue reflects this:  if we calculate defaults for the transaction's dynamic fee fields based on the chain tip, but re-execute against a historical block, …

internal/ethapi:  Set basefee for `AccessList` based on given block, not chain tip

---

accounts/usbwallet/ledger.go

Fixes #30173 
- Add support for EIP 1559 Dynamic tx using ledger

accounts/usbwallet: support dynamic tx

---

signer/core/apitypes/signed_data_internal_test.go
signer/core/apitypes/testdata/typed-data.json
signer/core/apitypes/types.go
signer/core/apitypes/types_test.go

This PR patches the current implementation to resolve [this issue](https://github.com/ethereum/go-ethereum/issues/30619).
The test cases in [testdata/typed-data.json](https://github.com/ethereum/go-ethereum/compare/master...naveen-imtb:go-ethereum:feat/support-fixed-sized-array-encoding?expand=1#diff-e048d4ae7de4b342df8e7e9eb597f43670e7b2b2000d8e51ff06a71e2e5f7321) have been repurposed from the ethers.js [repository](https://github.com/ethers-io/ethers.js/blob/main/testcases/typed-data.json.gz).
The test cases have been updated to remove the ones that don't have a valid domain separator as EIP-712 messages without a domain separator are not supported by geth.
As an example, the below test case from ethersjs repository has been removed as it is considered invalid.
```
{
"name": …
```

signer/core: extended support for EIP-712 array types

---

cmd/evm/runner.go
cmd/evm/staterunner.go
tests/state_test_util.go

When `evm statetest --bench` is specified, benchmark the execution similarly to `evm run`.  It will explicitly error if there is more than one matched subtest to be executed (new `statetest` flags are added to filter which tests are ran).
Breaks the state test runner API.  But I figure that we are the only consumers of this API, so it's not a big problem?

cmd/evm:  benchmarking via `statetest` command + filter by name, index and fork

---

core/state/statedb_hooked.go

Implemented code change tracking for `selfdestruct` operations by adding `OnCodeChange` hooks in the `SelfDestruct` and `SelfDestruct6780` methods of the `hookedStateDB` structure. 
Motivation:
Now, we can track `OnCodeChange` when the contract is deployed. It would be nice also to be able to track changes (code, codeHash) when the contract is destroyed.
Let me know if this makes sense or if I need to improve/fix anything

core/state: invoke OnCodeChange-hook on selfdestruct

---

trie/utils/verkle.go

The default value of `fr.Element` is already zero, you can see the evidence in `go-verkle` here:
1. https://github.com/ethereum/go-verkle/blob/dffa7562dbe971a9776f43795d49177a18ecb5c8/tree.go#L273
2. https://github.com/ethereum/go-verkle/blob/dffa7562dbe971a9776f43795d49177a18ecb5c8/tree.go#L294
It doesn't call `SetZero` for those already zeroed `fr.Element`s.

trie/utils: remove useless `SetZero` for verkle

---

eth/protocols/eth/handler_test.go
oss-fuzz.sh

Adds a protocol handler fuzzer that will try to fuzz the protocol handlers.
Two points of discussion:
- currently input needs to be valid RLP which makes it harder to reach certain states
- currently all handlers are fuzzed at the same time which might confuse a mutator, I could pull it out into 12+ individual fuzzers, but that seems overkill to me
wdyt @holiman

eth/protocols/eth: add protocol handler fuzzers

---

tests/state_test_util.go

Fix test panic 
```
--- FAIL: TestState (5.11s)
init_test.go:200: missing test files
--- FAIL: TestState/stSpecialTest/eoaEmptyParis.json (0.01s)
--- FAIL: TestState/stSpecialTest/eoaEmptyParis.json/Shanghai/2/hash/trie (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100cc3210]
goroutine 24268777 [running]:
testing.tRunner.func1.2({0x100ec02e0, 0x1011a0c70})
/usr/local/go/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1634 +0x33c
panic({0x100ec02e0?, 0x1011a0c70?})
/usr/local/go/src/runtime/panic.go:770 +0x124 …
```

tests: fix test panic

---

docs/postmortems/2021-08-22-split-postmortem.md

"datcopy" — there's a missing "**a**" here; it should be "datacopy", matching the function name used elsewhere.

docs: fix typo

---

core/state/snapshot/iterator_binary.go
core/state/snapshot/iterator_test.go

Work in progress
cc @rjl493456442

core/state: tests on the binary iterator

---

go.mod
oss-fuzz.sh
tests/fuzzers/bls12381/bls12381_fuzz.go
tests/fuzzers/bls12381/bls12381_test.go

The [kilic](https://github.com/kilic/bls12-381) bls12381 implementation has been archived.  It shouldn't be necessary to include it as a fuzzing target any longer.
This also adds fuzzers for G1/G2 mul that use inputs that are guaranteed to be valid.  Previously, we just did random input fuzzing for these precompiles.

all: remove kilic dependency from bls12381 fuzzers

---

rpc/client_test.go
rpc/http_test.go
rpc/server_test.go
rpc/subscription_test.go
rpc/types_test.go
rpc/websocket_test.go

Continuation of https://github.com/ethereum/go-ethereum/pull/30381

rpc: run tests in parallel

---

core/vm/program/program.go
core/vm/program/program_test.go
core/vm/program/readme.md
core/vm/runtime/runtime_test.go

In many cases, we have a need to create somewhat nontrivial bytecode. A recent example is the verkle statetests, where we want a `CREATE2`- op to create a contract, which can then be invoked, and when invoked does a selfdestruct-to-self. 
It is overkill to go full solidity, but it is also a bit tricky do assemble this by concatenating bytes. This PR takes an approach that I've been using in goevmlab for several years. 
Using this utility, the case can be expressed as: 
```golang
// Some runtime code
runtime := program.New().Ops(vm.ADDRESS, vm.SELFDESTRUCT).Bytecode()
// A constructor returning the runtime code
initcode := program.New().ReturnData(runtime).Bytecode()
// A factory invoking the constructor
outer := program.New().Create2AndCall(initcode, nil).Bytecode()
```
We have a lot of …

core/vm/program: create evm programming utility

---

cmd/evm/internal/t8ntool/execution.go
core/chain_makers.go
core/state_prefetcher.go
core/state_processor.go
core/verkle_witness_test.go
core/vm/evm.go
core/vm/gas_table_test.go
core/vm/instructions_test.go
core/vm/interpreter_test.go
core/vm/runtime/env.go
eth/api_backend.go
eth/gasestimator/gasestimator.go
eth/state_accessor.go
eth/tracers/api.go
eth/tracers/api_test.go
eth/tracers/internal/tracetest/calltrace_test.go
eth/tracers/internal/tracetest/flat_calltrace_test.go
eth/tracers/internal/tracetest/prestate_test.go
eth/tracers/js/tracer_test.go
eth/tracers/logger/logger_test.go
eth/tracers/tracers_test.go
internal/ethapi/api.go
internal/ethapi/api_test.go
internal/ethapi/backend.go
internal/ethapi/simulate.go
internal/ethapi/transaction_args_test.go
miner/worker.go
tests/state_test.go
tests/state_test_util.go

This pull request refactors the EVM constructor by removing the TxContext parameter.
The EVM object is frequently overused. Ideally, only a single EVM instance should be created and reused throughout the entire state transition of a block, with the transaction context switched as needed by calling evm.SetTxContext.
Unfortunately, in some parts of the code, the EVM object is repeatedly created, resulting in unnecessary complexity. This pull request is the first step towards gradually improving and simplifying this setup.

core, eth, internal, cmd: rework EVM constructor

---

cmd/evm/internal/t8ntool/execution.go
core/chain_makers.go
core/state_processor.go
core/verkle_witness_test.go
eth/state_accessor.go
eth/tracers/api.go
internal/ethapi/simulate.go
miner/worker.go

It's a subsequent pull request after the #30745 , removing some unnecessary parameters.

core, eth, internal, miner: remove unnecessary parameters

---

internal/ethapi/api.go

`ActivePrecompiledContracts()` clones the precompiled contract map, thus its callsite does not need to clone it

internal/ethapi: remove double map-clone

---

build/ci.go
core/verkle_witness_test.go
core/vm/eof.go
trie/utils/verkle.go

Since err != nil has been judged before, nil is returned directly here, which is more obvious, readable and less error-prone.

all: typos in comments

---

trie/proof.go
trie/trie.go

in `trie`
- Replace custom logic with `bytes.HasPrefix`
- Remove unnecessary code in `GetNode`

trie: replace custom logic with bytes.HasPrefix

---

core/state/snapshot/conversion.go
core/state/snapshot/difflayer.go
core/state/snapshot/difflayer_test.go
core/state/snapshot/disklayer.go
core/state/snapshot/disklayer_test.go
core/state/snapshot/generate_test.go
core/state/snapshot/iterator.go
core/state/snapshot/iterator_binary.go
core/state/snapshot/iterator_fast.go
core/state/snapshot/iterator_test.go
core/state/snapshot/journal.go
core/state/snapshot/snapshot.go
core/state/snapshot/snapshot_test.go
core/state/snapshot/utils.go
core/state/statedb.go
core/state/statedb_fuzz_test.go
core/state/statedb_test.go
core/state/stateupdate.go
triedb/states.go

This pull request removes the destruct flag from the state snapshot to simplify the code.
Previously, this flag indicated that an account was removed during a state transition, making all associated storage slots inaccessible. Because storage deletion can involve a large number of slots, the actual deletion is deferred until the end of the process, where it is handled in batches.
With the deprecation of self-destruct in the Cancun fork, storage deletions are no longer expected. Historically, the largest storage deletion event in Ethereum was around 15 megabytes—manageable in memory.
In this pull request, the single destruct flag is replaced by a set of deletion markers for individual storage slots. Each deleted storage slot will now appear in the Storage set with a nil value.
This change …

core, triedb: remove destruct flag in state snapshot

---

internal/flags/flags.go

If we define an alias for any of DirectoryString and BigFlag, `geth` or `make test` will panic with message `flag redefined`. For example:
```go
AncientFlag = &flags.DirectoryFlag{
Name:     "datadir.ancient",
Aliases:  []string{"datadir-ancient"},
Usage:    "Root directory for ancient data (default = inside chaindata)",
Category: flags.EthCategory,
}
```
The geth will panic with the following message
```text
geth flag redefined: datadir.ancient
panic: geth flag redefined: datadir.ancient
```
Some of test cases will fail with the following message when we run `make test`:
```text
test_cmd.go:261: (stderr:1) geth-test flag redefined: datadir.ancient
test_cmd.go:261: (stderr:1) panic: geth-test flag redefined: datadir.ancient
```

internal/flags: fix "flag redefined" bug for alias on custom flags

---

eth/tracers/logger/logger_json.go

Fixes a flaw introduced in https://github.com/ethereum/go-ethereum/pull/29795 , discovered while reviewing https://github.com/ethereum/go-ethereum/pull/30633 . 
Merge this and rebase https://github.com/ethereum/go-ethereum/pull/30633 on top of it?

eth/tracers/logger: fix json-logger output missing

---

accounts/abi/topics.go
accounts/abi/topics_test.go
signer/core/apitypes/types.go

#28764 updated `func MakeTopics` to support negative `*big.Int`s. However, it also changed the behavior of the function from just _reading_ the input `*big.Int` via `Bytes()`, to leveraging `big.U256Bytes` which is documented as being _destructive_:
https://github.com/ethereum/go-ethereum/blob/a5fe7353cff959d6fcfcdd9593de19056edb9bdb/common/math/big.go#L175-L177
This was flagged by the race detector in our test suite, due to sharing some fixture variables for "constants" like `oneEth`. Looking around the codebase, other users of this function make defensive copies, like `packNum`:
https://github.com/ethereum/go-ethereum/blob/2814ee0547cb49dddf182bad802f19100608d5f8/accounts/abi/pack.go#L81
This PR updates `MakeTopics` to make a copy in the same way.

accounts/abi:  fix MakeTopics mutation of big.Int inputs

---

eth/ethconfig/config.go

This updates the message you get when trying to initialize Geth with genesis.json that doesn't have `terminalTotalDifficulty`. The previous message was a bit obscure, I had to check the code to find out what the problem was.

eth/ethconfig: improve error message if TTD missing

---

core/tracing/hooks.go

This PR extends tracing.StateDB by adding a GetCodeHash function.
Motivation
- Currently, tracing.StateDB supports 2 out of 3 basic account data getters (GetBalance and GetNonce). Adding GetCodeHash completes the set, making it 3/3.
- This addition significantly improves the performance of tracers that need to compute code hashes. Previously, the only available option was to use `crypto.Keccak256Hash(t.stateDB.GetCode(addr))`, which is less efficient.

core/tracing: add GetCodeHash to StateDB

---

core/state/snapshot/snapshot.go

This reverts commit 23800122b37695be50565f8221858a16ce1763db.
The original pull request introduces a bug and some flaky tests are detected because of this flaw.
```
--- FAIL: TestRecoverSnapshotFromWipingCrash (0.27s)
blockchain_snapshot_test.go:158: The disk layer is not integrated snapshot is not constructed
{"pc":0,"op":88,"gas":"0x7148","gasCost":"0x2","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PC"}
{"pc":1,"op":255,"gas":"0x7146","gasCost":"0x1db0","memSize":0,"stack":["0x0"],"depth":1,"refund":0,"opName":"SELFDESTRUCT"}
{"output":"","gasUsed":"0x0"}
{"output":"","gasUsed":"0x1db2"}
{"pc":0,"op":116,"gas":"0x13498","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH21"}
```
Before the original PR, the snapshot would block the function until the disk …

Revert "core/state/snapshot: simplify snapshot rebuild (#30772)"

---

cmd/evm/runner.go
cmd/evm/staterunner.go

Reusing state between benchmark iterations resulted in inconsistent results across runs, which surfaced in https://github.com/ethereum/go-ethereum/issues/30778 .
If these errors are triggered again, they should be printed to output.  To ensure that the code invoking `testing.Benchmark()` can catch and output these errors, and then exit:  I replace calls to `t.B.Fatalf` with setting an error which is consumed by the calling code.
The same consistency checks should probably be applied to the state test benchmarker.  I am figuring that out now.
closes https://github.com/ethereum/go-ethereum/issues/30778 .

cmd/evm: don't reuse state between iterations, show errors

---

core/blockchain_reader.go

~~According to the comments and code logic, the err here should be handled by the upper layer GetTransaction~~
Add a comment for error return of nil

core: add a comment for error return of nil

---

core/state/snapshot/journal.go
core/state/snapshot/snapshot.go

This workaround is meant to minimize the possibility for snapshot generation 
once the geth node upgrades to new version (specifically #30752 )
In #30752, the journal format in state snapshot is modified by removing the
destruct set. Therefore, the existing old format (version = 0) will be discarded
and all in-memory layers will be lost. Unfortunately, the lost in-memory layers 
can't be recovered by some other approaches, and the entire state snapshot 
will be regenerated (it will last about 2.5 hours).
This pull request introduces a workaround to adopt the legacy journal if the 
destruct set contained is empty. Since self-destruction has been deprecated 
following the cancun fork, the destruct set is expected to be nil for layers above
the fork block. However, an exception occurs during …

core/state/snapshot: handle legacy journal

---

trie/proof.go

Small optimization. It's guaranteed that `len(keys)` == `len(values)`, so we can combine the checks in a single loop rather than 2 separate loops.

trie: combine validation loops in VerifyRangeProof

---

beacon/engine/types.go
cmd/evm/internal/t8ntool/execution.go
core/chain_makers.go
core/genesis.go
core/state_processor.go
core/types/hashes.go
eth/tracers/internal/tracetest/supply_test.go
internal/ethapi/testdata/eth_getBlockReceipts-block-with-blob-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-block-with-contract-create-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-block-with-dynamic-fee-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-contract-call-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-transfer-tx.json
internal/ethapi/testdata/eth_getBlockReceipts-tag-latest.json
internal/ethapi/testdata/eth_getTransactionReceipt-blob-tx.json
internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-tx.json
internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-with-access-list.json
internal/ethapi/testdata/eth_getTransactionReceipt-dynamic-tx-with-logs.json
internal/ethapi/testdata/eth_getTransactionReceipt-normal-transfer-tx.json
internal/ethapi/testdata/eth_getTransactionReceipt-with-logs.json
miner/worker.go

Implements changes from these spec PRs:
- https://github.com/ethereum/EIPs/pull/8989
- https://github.com/ethereum/execution-apis/pull/599

all: exclude empty outputs in requests commitment

---

core/types/block.go

The existing implementation is correct when building and verifying blocks, since we will only collect non-empty requests into the block requests list.
But it isn't correct for cases where a requests list containing empty items is sent by the consensus layer on the engine API. We want to ensure that empty requests do not cause a difference in validation there, so the commitment computation should explicitly skip them.

core/types: add length check in CalcRequestsHash

---

triedb/database.go
triedb/hashdb/database.go
triedb/pathdb/buffer.go
triedb/pathdb/database.go
triedb/pathdb/database_test.go
triedb/pathdb/difflayer.go
triedb/pathdb/difflayer_test.go
triedb/pathdb/disklayer.go
triedb/pathdb/journal.go
triedb/pathdb/metrics.go
triedb/pathdb/nodes.go
triedb/pathdb/reader.go
triedb/pathdb/states.go
triedb/pathdb/states_test.go
triedb/states.go

This pull request ports some changes from the main state snapshot integration one, specifically introducing the flat state tracking in pathdb.
Note, the tracked flat state changes are only held in memory and won't be persisted in the disk. Meanwhile, the correspoding state retrieval in persistent state is also not supported yet. The states management in disk is more complicated and will be implemented in a separate pull request.
Part 1: https://github.com/ethereum/go-ethereum/pull/30752

triedb/pathdb: track flat state changes in pathdb (snapshot integration pt 2)

---

core/blockchain_reader.go
core/state/database.go
core/state/iterator.go
core/state/reader.go
core/state/state_object.go
core/state/statedb.go
core/state/sync_test.go
eth/protocols/snap/handler.go

It's an alternative of #30808 
This PR introduces a `ContractCodeReader` interface with functions defined:
```go
// ContractCodeReader defines the interface for accessing contract code.
type ContractCodeReader interface {
// Code retrieves a particular contract's code.
//
// - Returns nil code along with nil error if the requested contract code
//   doesn't exist
// - Returns an error only if an unexpected issue occurs
Code(addr common.Address, codeHash common.Hash) ([]byte, error)
// CodeSize retrieves a particular contracts code's size.
//
// - Returns zero code size along with nil error if the requested contract code
//   doesn't exist
// - Returns an error only if an unexpected issue occurs
CodeSize(addr common.Address, codeHash common.Hash) (int, error)
}
```
This interface can be …

core, state: introduce code reader interface

---

internal/debug/flags.go

This flag is very rarely needed, so it's OK for it to have a verbose name. The name --trace also conflicts with the concept of EVM tracing, which is much more heavily used.

internal/debug: rename --trace to --go-execution-trace

---

cmd/utils/flags.go
eth/backend.go
eth/catalyst/api.go
eth/catalyst/api_test.go
eth/catalyst/simulated_beacon_test.go
eth/catalyst/tester.go
eth/downloader/beaconsync.go
eth/downloader/downloader.go
eth/downloader/queue.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go
eth/ethconfig/syncmode.go
eth/handler.go
eth/handler_eth_test.go
eth/handler_test.go
eth/sync_test.go
ethclient/simulated/backend.go

Lots of packages depend on eth/downloader just for the SyncMode type. Since we have a dedicated package for eth protocol configuration, it makes more sense to define SyncMode there, turning eth/downloader into more of a leaf package.

eth/downloader: move SyncMode to package eth/ethconfig

---

cmd/evm/main.go
cmd/evm/runner.go
core/vm/runtime/runtime_test.go
eth/tracers/api_test.go
eth/tracers/logger/logger.go
eth/tracers/tracers_test.go

This PR refactors the structlog a bit, making it so that it can be used in a streaming mode. 
-------------
OBS: this PR makes a change in the input `config` config, the third input-parem field to `debug.traceCall`. Previously, seteting it to e.g. ` {"enableMemory": true, "limit": 1024}` would mean that the response was limited to `1024` items. Since an 'item' may include both memory and storage, the actual size of the response was undertermined. 
After this change, the response will be limited to `1024` __`bytes`__ (or thereabouts). 
-----------
The commandline usage of structlog now uses the streaming mode, leaving the non-streaming mode of operation for the eth_Call. 
There are two benefits of streaming mode 
1. Not have to maintain a long list of operations, 
2. Not have to duplicate …

cmd/evm, eth/tracers: refactor structlogger + make it streamable

---

core/state/database.go

It's a pull request based on https://github.com/ethereum/go-ethereum/pull/30643
In this pull request, the partial functional state reader is enabled if **legacy snapshot
is not enabled**. The tracked flat states in pathdb will be used to serve the state 
retrievals, as the second implementation to fasten the state access.
This pull request should be a noop change in normal cases.

core/state: enable partial-functional reader (snapshot integration pt 3)

---

p2p/peer.go
p2p/peer_error.go
p2p/peer_test.go
p2p/transport.go
p2p/transport_test.go

This PR reverts back the change to the `DiscReason` rlp decoding done in https://github.com/ethereum/go-ethereum/pull/24507
It also adds a test to check for correctness. The current code in `master` will fail the test since the rlp decoding of DiscReason will fail. However the error returned from `rlp.Decode` is not checked, so the client proceeds using the default value for DiscReason, which is `DiscRequested`.
This PR also prevents a possible nil pointer dereference when closing an rlpx connection.

p2p: fix DiscReason encoding/decoding

---

docs/fundamentals/config-files.md
docs/monitoring/metrics.md

As the `--metrics.expensive` flag was marked as depreated, 
`Expensive metrics are collected by default, please remove this flag` 
we should remove this flag also in the website document.

docs: rm the deprecated --metrics.expensive flag 

---

triedb/pathdb/database.go
triedb/pathdb/holdable_iterator.go
triedb/pathdb/holdable_iterator_test.go
triedb/pathdb/iterator.go
triedb/pathdb/iterator_binary.go
triedb/pathdb/iterator_fast.go
triedb/pathdb/iterator_test.go
triedb/pathdb/reader.go
triedb/pathdb/states.go
triedb/pathdb/states_test.go

**It's highly recommended to review the changes by comparing the files directly.**
In this pull request, the state iterator is implemented. It's mostly a copy-paste from 
the original state snapshot package, but still has some important changes to highlight
here:
**(a) The iterator for the disk layer consists of a diff iterator and a disk iterator**. 
Originally, the disk layer in the state snapshot was a wrapper around the disk, and 
its corresponding iterator was also a wrapper around the disk iterator. However, 
due to structural differences, the disk layer iterator is divided into two parts:
- The disk iterator, which traverses the content stored on disk.
- The diff iterator, which traverses the aggregated state buffer.
Checkout `BinaryIterator` and `FastIterator` for more details. …

trie/pathdb: state iterator (snapshot integration pt 4)

---

core/vm/memory.go
go.mod
go.sum

Updates geth to use the latest uint256, which has a neat optimization or two. 
No rush to merge, it can marinate for a few weeks

core/vm, go.mod: update uint256 and use faster method to write to memory

---

core/chain_makers.go

Adding some missing functionality I noticed while updating the hivechain tool for the Prague fork:
- we forgot to process the parent block hash
- added `ConsensusLayerRequests` to get the requests list of the block

core: fixes for Prague fork in GenerateChain

---

core/vm/opcodes.go

Noticed this omission while doing some work on goevmlab. We don't properly type some of the opcodes, but apparently implicit casting works in all the internal usecases.

core/vm: make all opcodes proper type

---

core/types/block.go
core/types/gen_authorization.go
core/types/gen_header_json.go
core/types/tx_setcode.go
internal/ethapi/api.go
internal/ethapi/transaction_args.go

Fixing some issues I found while regenerating RPC tests for Prague:
- Authorization signature values were not encoded as hex
- `requestsRoot` in block should be `requestsHash`
- `authorizationList` should work for `eth_call`

core/types, internal/ethapi: fixes for prague RPC encoding

---

cmd/evm/blockrunner.go
cmd/evm/main.go
cmd/evm/staterunner.go

This fixes a regression introduced recently. Without this fix, it's not possible to use statetests without `.json` suffix. 
This is problematic for goevmlab `minimizer`, which appends the suffix `.min` during processing.  
Without fix
```
[user@work go-ethereum]$ go run ./cmd/evm/ statetest --trace --trace.format=json ./00155493-mixed-6.json.min.min
null
```
With fix
```
[user@work go-ethereum]$ go run ./cmd/evm/ statetest --trace --trace.format=json ./00155493-mixed-6.json.min.min
{"pc":0,"op":127,"gas":"0x19e701","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH32"}
{"pc":33,"op":95,"gas":"0x19e6fe","gasCost":"0x2","memSize":0,"stack":["0xc159603ab9942405d1c9c45c46403949f0540852afe082105fc3a18449358973"],"depth":1,"refund":0,"opName":"PUSH0"}
```

cmd/evm: make evm statetest accept non-json files

---

core/blockchain_test.go
core/state_processor_test.go
core/state_transition.go
core/types/gen_authorization.go
core/types/transaction.go
core/types/transaction_marshalling.go
core/types/tx_setcode.go
internal/ethapi/api.go
internal/ethapi/transaction_args.go
tests/state_test_util.go

Here I am proposing two small changes to the exported API for EIP-7702:
(1) `Authorization` has a very generic name, but it is in fact only used for one niche use case: authorizing code in a `SetCodeTx`. So I propose calling it `SetCodeAuthorization` instead. The signing function is renamed to `SignSetCode` instead of `SignAuth`.
(2) The signing function for authorizations should take key as the first parameter, and the authorization second. The key will almost always be in a variable, while the authorization can be given as a literal. Compare these two invocations:
```go
a, err := types.SignSetCode(types.SetCodeAuthorization{
ChainID: getChainID(),
Nonce: getNonce(),
}, key)
```
with
```go
a, err := types.SignSetCode(key, types.SetCodeAuthorization{
ChainID: getChainID(),
Nonce: …
```

core/types: updates for EIP-7702 API functions

---

cmd/evm/internal/t8ntool/transaction.go
core/state_transition.go
core/txpool/validation.go
core/types/transaction.go
core/types/transaction_signing.go
eth/tracers/native/prestate.go
internal/ethapi/api.go
internal/ethapi/transaction_args.go
tests/state_test_util.go
tests/transaction_test_util.go

As a follow-up to #30933, I propose to also use the SetCode prefix in our internal APIs for the authorization list.

core, core/types: rename AuthList to SetCodeAuthorizations

---

crypto/bn256/cloudflare/gfp12.go
crypto/bn256/google/gfp12.go

The `a` parameter should be used in the `MulScalar` function. The upstream cloudflare and google repos have already merged fixes.
Reference:
* https://cs.opensource.google/go/x/crypto/+/8d7daa0c54b357f3071e11eaef7efc4e19a417e2
* https://github.com/cloudflare/bn256/pull/33

crypto/bn256: fix MulScalar

---

eth/tracers/logger/logger.go

The struct logger relies on the `OnTxStart` hook to store the execution context. In order to support tracing system calls, the logger also needs to listen to the `OnSystemCallStartV2` hook.

eth/tracers/logger: support tracing system calls

---

core/rawdb/freezer.go

Fixes an issue where the node panics when an LStat fails with something other than os.ErrNotExist
closes https://github.com/ethereum/go-ethereum/issues/30968

core/rawdb: fix panic in freezer

---

eth/protocols/eth/dispatcher.go
eth/sync_test.go

This PR attempts to fix a strange test-failure (timeout) observed on a windows-32 platform. 
https://ci.appveyor.com/project/ethereum/go-ethereum/builds/51174391/job/d8ascanwwltrlqd5
A goroutine is stuck trying to deliver a response:
```
goroutine 9632 [select, 29 minutes]:
github.com/ethereum/go-ethereum/eth/protocols/eth.(*Peer).dispatchResponse(0x314f100, 0x3e5f6d0, 0x3acbb84)
C:/projects/go-ethereum/eth/protocols/eth/dispatcher.go:172 +0x2a5
github.com/ethereum/go-ethereum/eth/protocols/eth.handleBlockHeaders({0x12abe68, 0x30021b8}, {0x12a815c, 0x40b41c0}, 0x314f100)
C:/projects/go-ethereum/eth/protocols/eth/handlers.go:301 +0x173
github.com/ethereum/go-ethereum/eth/protocols/eth.handleMessage({0x12abe68, 0x30021b8}, 0x314f100)
C:/projects/go-ethereum/eth/protocols/eth/handler.go:205 …
```

eth/protocols/eth: prevent hanging dispatch

---

cmd/clef/rules.md

**-The two main features that are required for this to work well are;
+The two main features that are required for this to work well are:**
> Explanation: Replaced semicolon with colon since it introduces a list of items.
**-var limit = big.NewInt("0xb1a2bc2ec50000")
+var limit = new BigNumber("0xb1a2bc2ec50000")**
> Explanation: The code was using an incorrect method big.NewInt() which doesn't exist in the BigNumber.js library. The correct way to create a BigNumber instance is using the new BigNumber() constructor. This is particularly important when dealing with large numbers in Ethereum transactions where precision is crucial. The value "0xb1a2bc2ec50000" represents a hexadecimal number that needs to be handled as a big number to avoid JavaScript's number precision limitations.
**-if …

cmd/clef: fix JS issues in documentation

---

triedb/pathdb/database_test.go

There is a "rare" bug in test generator: If the run is very unlucky it can use `modifyAccountOp` / `deleteAccountOp` without creating any account, leading to have a trie root same as the parent.
This pull request includes a change to the `generate` function in the `database_test.go` file to ensure that account creation 
always occurs first during the test iterations. 
Changes in test logic:
* [`triedb/pathdb/database_test.go`](diffhunk://#diff-aa0965b61dc78a72ef175bc83cacadd7e5f29613ea543f86242a459b7259ccb9L225-R230): Modified the `generate` function to start with account creation in the first iteration, ensuring consistent initial conditions for the test.

triedb/pathdb: fix tester generator

---

README.md

Removes some outdated info from our readme

README: remove private network section from readme

---

core/genesis.go
core/state/stateupdate.go
core/types/hashes.go
internal/ethapi/override/override_test.go
trie/trie_reader.go
triedb/pathdb/database.go
triedb/pathdb/database_test.go
triedb/pathdb/journal.go
triedb/pathdb/layertree.go

As the node hash scheme in verkle and merkle are totally different, the original default node hasher in pathdb is no longer suitable. Therefore, this pull request configures different node hasher respectively.

triedb/pathdb: configure different node hasher in pathdb

---

.golangci.yml
build/checksums.txt
core/txpool/blobpool/blobpool.go
core/txpool/legacypool/legacypool.go

This PR upgrades `golangci-lint` to v1.63.4 and fixes a warn message which is reported by v1.63.4:
```text
WARN [config_reader] The configuration option `run.skip-dirs-use-default` is deprecated, please use `issues.exclude-dirs-use-default`.
```
Also fixes 2 warnings which are reported by v1.63.4:
```text
core/txpool/blobpool/blobpool.go:1754:12: S1005: unnecessary assignment to the blank identifier (gosimple)
for acct, _ := range p.index {
^
core/txpool/legacypool/legacypool.go:1989:19: S1005: unnecessary assignment to the blank identifier (gosimple)
for localSender, _ := range pool.locals.accounts {
^
```

build: upgrade golangci-lint to v1.63.4

---

eth/tracers/logger/logger.go
eth/tracers/logger/logger_test.go

The logger tracer is dropping data from a revert.
Because of error wrapping the == comparison is not sufficient. errors.Is is needed.

eth/tracers/logger: return revert reason

---

core/txpool/legacypool/legacypool_test.go

- it was failing because the maximum data length (previously `dataSize`) was set to `txMaxSize - 213` but should had been `txMaxSize - 103` and the last call `dataSize+1+uint64(rand.Intn(10*txMaxSize)))` would sometimes fail depending on rand.Intn.
- Maximal transaction data size comment (invalid) replaced by code logic to find the maximum tx length without its data length
- comments and variable naming improved for clarity
- 3rd pool add test replaced to add just 1 above the maximum length, which is important to ensure the logic is correct

core/txpool/legacypool: fix flaky test TestAllowedTxSize

---

core/blockchain_test.go
core/state_transition.go

Cleans up two unused parameters.

core: remove unused function parameters

---

cmd/geth/chaincmd.go
cmd/utils/history_test.go
core/blockchain.go
core/genesis.go
core/genesis_test.go
core/verkle_witness_test.go
miner/miner_test.go
params/config.go
triedb/database.go
triedb/hashdb/database.go
triedb/pathdb/database.go

This pull request refactors the genesis setup function, the major changes are highlighted here:
**(a) Triedb is opened in verkle mode if `EnableVerkleAtGenesis` is configured in chainConfig
or the database has been initialized previously with `EnableVerkleAtGenesis` configured**.
A new config field `EnableVerkleAtGenesis` has been added in the chainConfig. This field must
be configured with True if Geth wants to initialize the genesis in Verkle mode.
In the verkle devnet-7, the verkle transition is activated at genesis. Therefore, the verkle rules
should be used since the genesis. In production networks (mainnet and public testnets), verkle 
activation always occurs after the genesis block. Therefore, this flag is only made for devnet
and should be deprecated later. Besides, verkle …

cmd, core, miner: rework genesis setup

---

accounts/accounts.go
cmd/devp2p/internal/ethtest/protocol.go
cmd/devp2p/internal/v4test/discv4tests.go
consensus/clique/snapshot_test.go
core/tracing/hooks.go
core/txpool/legacypool/legacypool2_test.go
core/types/deposit.go
core/vm/eof_validation.go
core/vm/program/program.go
crypto/blake2b/blake2b.go
crypto/bn256/gnark/pairing.go
crypto/ecies/ecies.go
eth/tracers/dir.go
eth/tracers/internal/util.go
internal/era/builder.go
internal/jsre/jsre.go
internal/reexec/reexec.go
metrics/exp/exp.go
metrics/gauge_info.go
metrics/log.go
metrics/metrics.go
metrics/resetting_timer.go
metrics/syslog.go
p2p/discover/v5wire/encoding_test.go
params/protocol_params.go
signer/core/api.go
signer/core/uiapi.go

This pull request includes several changes to improve code clarity and consistency across multiple files. The changes mainly involve adding detailed comments to functions and renaming variables and functions for better readability.
* [`accounts/accounts.go`](diffhunk://#diff-fa6086f3607f309a500ad2bc035978919674730a1e2cf5a33cac9214531164feL217-R219): Added detailed comments to `WalletDropped` to explain when the event is fired.
* [`cmd/devp2p/internal/v4test/discv4tests.go`](diffhunk://#diff-98d4d2702c510dfe2017793fd2957d2588b78ca05cab00d5a055745e2a811b67L197-R197): Updated comments for multiple functions to provide clear descriptions of their behavior, such as `PingExtraDataWrongFrom`, `PingPastExpiration`, `WrongPacketType`, and others. …

all: fix some typos in comments and names

---

core/blockchain_test.go
core/state_transition.go
core/types/gen_authorization.go
core/types/transaction_marshalling.go
core/types/transaction_signing.go
core/types/tx_blob.go
core/types/tx_dynamic_fee.go
core/types/tx_setcode.go
internal/ethapi/transaction_args.go
tests/gen_stauthorization.go
tests/state_test_util.go

We still need to decide how to handle non-specfic `chainId` in the JSON encoding of authorizations. With `chainId` being a uint64, the previous implementation just used value zero. However, it might actually be more correct to use the value `null` for this case.

core/types: change SetCodeTx.ChainID to uint256

---

beacon/engine/types.go
eth/catalyst/api.go

According to https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md#engine_newpayloadv4:
> Elements of the list MUST be ordered by request_type in ascending order. Elements with empty request_data MUST be excluded from the list.

beacon/engine: check for empty requests

---

core/blockchain.go
core/sender_cacher.go
core/txpool/legacypool/legacypool.go

This pull request focuses on refactoring the `SenderCacher` initialization and usage to ensure thread-safe lazy initialization. The changes include modifying the way `SenderCacher` is accessed and updating relevant function calls.
Key changes include:
* By not creating the `SenderCacher` instance globally on startup, created on-demand
* More thread Safety
* [`core/sender_cacher.go`](diffhunk://#diff-dd52cbf4eef8ac1b1a73b870d766707497a7ee4e69b90c4ee3e1b0e25e54b041R21-R42): Introduced a singleton pattern for `SenderCacher` using `sync.Once` to ensure thread-safe lazy initialization. Added the `GetSenderCacher` function to return the singleton instance.
* [`core/blockchain.go`](diffhunk://#diff-53d5f4b8a536ec2a8c8c92bf70b8268f1d77ad77e9f316e6f68a2bcae5303215L1619-R1619): Updated the …

core: use sync.Once for SenderCacher initialization

---

core/txpool/legacypool/legacypool.go
ethclient/simulated/backend_test.go
ethclient/simulated/rollback_test.go

closes https://github.com/ethereum/go-ethereum/issues/30842

core/txpool/legacypool: ensure pending nonces are reset by SubPool.Clear

---

ethdb/memorydb/memorydb.go

This PR replaces the iterator based DeleteRange implementation of memorydb with a simpler and much faster loop that directly deletes keys in the order of iteration instead of unnecessarily collecting keys in memory and sorting them.

ethdb/memorydb: faster DeleteRange

---

cmd/abigen/main.go

This PR addresses issue #30768 , which highlights that running cmd/abigen/abigen --pkg my_package example.json (erroneously omitting the --abi flag) generates an empty binding, when it should fail explicitly.
Changes
--abi flag is now mandatory when running abigen command and fail explicitly if it is missing
If theses changes are good, I’d be happy to continue familiarizing myself with the project and contributing to it!

cmd/abigen: make one of `--abi` or `--combined-json` be required

---

core/types/tx_setcode.go

TestStateProcessorErrors fails, the chainId should be initialized

core/types: initialize ChainID in SetCodeTx copy method

---

core/txpool/txpool.go

if the pool terminates before `resetDone` can be read, then the go-routine will hang.

core/txpool:  terminate subpool reset goroutine if pool was closed

---

eth/filters/api.go

Discovered from failing test introduced https://github.com/ethereum/go-ethereum/pull/31033 .  We should ensure `timeoutLoop` terminates if the filter event system is terminated.

eth/filters:  ensure filter api timeout loop terminates with filter event system termination

---

go.mod

We have our own system for downloading the toolchain, and really don't want Go's to get in the way of that. We may switch to Go's builtin toolchain support, but not now.

go.mod: remove toolchain line

---

cmd/evm/staterunner.go
cmd/evm/t8n_test.go
cmd/evm/testdata/evmrun/10.out.1.txt
cmd/evm/testdata/evmrun/9.out.2.txt

Refactoring of the `evm` command moved where some commands were valid.  One command, `--bench`, used to work in `evm statetest`.  The pluming is still in place.  This PR puts the `--bench` flag in the place the trace flags were moved, and adds tests to validate the bench flag operates in `run` and `statetest`

cmd/evm: restore --bench flag to evm statetest

---

triedb/pathdb/database_test.go
triedb/pathdb/disklayer.go
triedb/pathdb/history.go

State history v2 has been shipped and will take effect after the Cancun fork. 
However, the state revert function does not differentiate between v1 and v2, 
instead blindly using the storage map key for state reversion. 
This mismatch between the keys of the live state set and the state history 
can trigger a panic: `non-existent storage slot for reverting`.
This flaw has been fixed in this PR.

triedb/pathdb: fix state revert on v2 history

---

trie/bytepool.go
trie/encoding.go
trie/hasher.go
trie/node.go
trie/node_enc.go
trie/stacktrie.go
trie/stacktrie_test.go

This PR uses various tweaks and tricks to make the stacktrie near alloc-free. 
```
[user@work go-ethereum]$ benchstat stacktrie.1 stacktrie.7
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/trie
cpu: 12th Gen Intel(R) Core(TM) i7-1270P
│ stacktrie.1  │             stacktrie.7              │
│    sec/op    │    sec/op     vs base                │
Insert100K-8   106.97m ± 8%   88.21m ± 34%  -17.54% (p=0.000 n=10)
│   stacktrie.1    │             stacktrie.7              │
│       B/op       │     B/op      vs base                │
Insert100K-8   13199.608Ki ± 0%   3.424Ki ± 3%  -99.97% (p=0.000 n=10)
│  stacktrie.1   │             stacktrie.7             │
│   allocs/op    │ allocs/op   vs base                 │
Insert100K-8   553428.50 ± 0%   22.00 ± 5%  -100.00% (p=0.000 …
```

trie: reduce allocations in stacktrie

---

accounts/usbwallet/hub.go

The latest firmware for Ledger Nano S Plus now returns `0x5000` for it's product ID, which doesn't match any of the product IDs enumerated in `hub.go`.
This PR removes the assumption about the interfaces exposed, and simply checks the upper byte for a match.
Also adds support for the `0x0007` / `0x7000` product ID (Ledger Flex).

accounts/usbwallet: fix ledger access for latest firmware and add Ledger Flex

---

.github/workflows/go.yml

appveyor too slow
check_generate seems to take longer than others. Will check it in future.

.github: add lint step

---

build/ci.go

Travis often fails because the test times out.

build: bump test timeout

---

netlify.toml
redirects.js

Deletes a previous forced redirect of the objects page and updates the intended redirect to the correct one
Fixes #30214

website: Fix incorrect objects page redirect

---

.travis.yml
build/ci.go

This changes the `-upload` flag to just toggle the upload. The remote image name is now configured using the `-hub` flag.

build: provide a flag to disable publishing in dockerx build

---

core/vm/eips.go

Implements https://github.com/ethereum/EIPs/pull/9248

core/vm: EXTCODE* return delegation designator for 7702

---

eth/catalyst/api.go
eth/catalyst/api_test.go

I caught this error on Hive. It was introduced by https://github.com/ethereum/go-ethereum/pull/31071 because after adding the equality check the request type 0 will be rejected.

eth/catalyst: fix validation of type 0 request

---

core/vm/interpreter.go

Removes duplicate code in the interpreter loop.
The tradeoff is an additional conditional check in the hot loop of the interpreter, but this should not have a measurable performance impact.  I can run the benchmarks to verify this at a later time.

core/vm: simplify tracer hook invocation in interpreter loop

---

tests/fuzzers/bls12381/bls12381_fuzz.go

**Description:**  
I noticed a typo in the error message within the `fuzzCrossG2Add` function. The panic message incorrectly references "G1 point addition mismatch" when it should be "G2 point addition mismatch," as the function deals with G2 points.
This doesn't affect functionality but could cause confusion during debugging. I've updated the message to reflect the correct curve.  
Here's the fix:  
```go
panic("G2 point addition mismatch blst / geth ")
```  
Thanks!

tests/fuzzers/bls12381: fix error message in fuzzCrossG2Add

---

core/genesis.go
eth/downloader/testchain_test.go

This PR fixes the following data race:
The issue was that SetupGenesisWithOverride would overwrite the passed chain config
```
Write at 0x0000011fcea0 by goroutine 107204:
github.com/ethereum/go-ethereum/core.SetupGenesisBlockWithOverride()
/home/matematik/go/src/github.com/ethereum/go-ethereum/core/genesis.go:302 +0x244
github.com/ethereum/go-ethereum/core.NewBlockChain()
/home/matematik/go/src/github.com/ethereum/go-ethereum/core/blockchain.go:285 +0x668
github.com/ethereum/go-ethereum/eth/downloader.newTestBlockchain.func1()
/home/matematik/go/src/github.com/ethereum/go-ethereum/eth/downloader/testchain_test.go:220 +0x1cb
sync.(*Once).doSlow()
/home/matematik/sdk/go1.22.1/src/sync/once.go:74 +0xf0
sync.(*Once).Do()
/home/matematik/sdk/go1.22.1/src/sync/once.go:65 …
```

core: copy genesis before modifying

---

core/genesis.go
core/genesis_test.go

I hit this case while trying something with the simulated backend. The EVM only enables instruction set forks after the merge when 'Random' is set. In the simulated backend, the random value will be set via the engine API for all blocks after genesis. But for the genesis block itself, the random value will not be assigned in the vm.BlockContext because the genesis has a non-zero difficulty. For my case, this meant that estimateGas did not work for the first transaction sent on the simulated chain, since the contract contained a PUSH0 instruction.
This could also be fixed by explicitly configuring a zero difficulty in the simulated backend. However, I think that zero difficulty is a better default these days.

core: assign default difficulty to zero for chain without ethash

---

core/txpool/blobpool/blobpool_test.go

Fixes the lint on master which was broken by https://github.com/ethereum/go-ethereum/pull/30559

core/txpool/blobpool: fix incorrect arguments in test

---

cmd/evm/internal/t8ntool/execution.go
consensus/misc/eip4844/eip4844.go
consensus/misc/eip4844/eip4844_test.go
core/chain_makers.go
core/state_processor_test.go
eth/gasprice/feehistory.go
eth/tracers/internal/tracetest/util.go
internal/ethapi/simulate.go
miner/worker.go

~~*This PR is built on #31002.*~~
--
A clarification was made to EIP-7691 stating that at the fork boundary it is required to use the target blob count associated with the head block, rather than the parent as implemented here.
See for more: https://github.com/ethereum/EIPs/pull/9249

consensus/misc/eip4844: use head's target blobs, not parent

---

cmd/evm/internal/t8ntool/execution.go
consensus/misc/eip4844/eip4844.go
consensus/misc/eip4844/eip4844_test.go
core/chain_makers.go
core/state_processor_test.go
eth/gasprice/feehistory.go
eth/tracers/internal/tracetest/util.go
internal/ethapi/simulate.go
miner/worker.go

As noted in the review of #31101, it's a bit weird to pass two headers to `CalcExcessBlobGas`. We only use the second header to look up the fork timestamp, so I'm changing the function here to pass that timestamp. Most callers are not affected much, but it does make a difference in places like in tracetest which had to commit the genesis state and create a block just to get this header.
Also adding a small sanity check for the parent<->child relationship in `VerifyEIP4844Header`.

consensus/misc/eip4844: more changes for blob gas calculation

---

cmd/devp2p/internal/ethtest/conn.go

After recent changes in Geth (removing TD):
https://github.com/ethereum/go-ethereum/commit/39638c81c56db2b2dfe6f51999ffd3029ee212cb#diff-d70a44d4b7a0e84fe9dcca25d368f626ae6c9bc0b8fe9690074ba92d298bcc0d
Non-Geth clients are failing many devp2p tests with an error:
`peering failed: status exchange failed: wrong TD in status: have 1 want 0`
Right now only Geth is passing it - all other clients are affected by this change.
I think there should be no validation of TD when checking `Status` message in hive tests. Now Geth has 0 (and hive tests requires 0) and all other clients have actual TD. And on real networks there is no validation of TD when peering

cmd/devp2p/internal/ethtest: remove TD from status validation

---

core/forkid/forkid_test.go
params/config.go

Agreed to the following fork dates for Holesky and Sepolia on ([option 2 ACDC 150](https://github.com/ethereum/pm/issues/1265#issuecomment-2637778317)):
```
Holesky slot: 3710976	(Mon, Feb 24 at 21:55:12 UTC)
Sepolia slot: 7118848	(Wed, Mar 5 at 07:29:36 UTC)
```

params,core/forkid: enable prague on holesky and sepolia

---

consensus/beacon/consensus.go
eth/catalyst/api_test.go
eth/gasprice/gasprice_test.go
eth/protocols/eth/handler_test.go
eth/tracers/internal/tracetest/supply_test.go
graphql/graphql_test.go

This removes the method `TestingTTDBlock` introduced by #30744. It was added to make the beacon consensus engine aware of the merge block in tests without relying on the total difficulty. However, tracking the merge block this way is very annoying. We usually configure forks in the `ChainConfig`, but the method is on the consensus engine, which isn't always created in the same place. By sidestepping the `ChainConfig` we don't get the usual fork-order checking, so it's possible to enable the merge before the London fork, for example. This in turn can lead to very hard-to-debug outputs and validation errors.
So here I'm changing the consensus engine to check the `MergeNetsplitBlock` instead. Alternatively, we assume a network is merged if it has a `TerminalTotalDifficulty` of zero, which is …

consensus/beacon: remove TestingTTDBlock

---

p2p/discover/table_reval.go

we forget to remove the now argument related to this refactor PR  https://github.com/ethereum/go-ethereum/pull/30239

p2p/discover: remove unused parameter in revalidationList.get

---

p2p/discover/common.go
p2p/discover/v5_udp.go

This PR fix #31118 . It make discv5 response timeout configuable.

p2p/discover: make discv5 response timeout configurable

---

internal/ethapi/api.go

Fixes the panic raised in https://github.com/ethereum/go-ethereum/pull/31104. Alternative to https://github.com/ethereum/go-ethereum/pull/31116.

internal/ethapi: fix panic in debug methods

---

go.mod
go.sum

closes https://github.com/ethereum/go-ethereum/issues/31072
BLST released their newest version which includes a fix for go v.1.24: https://github.com/supranational/blst/releases/tag/v0.3.14
I went through all commits between 0.3.14 and 0.3.13 for a sanity check

go.mod: update blst

---

core/genesis.go
params/config.go

This is to prevent a crash on startup with a custom genesis configuration. With this change in place, upgrading a chain created by geth v1.14.x and below will now print an error instead of crashing:
```
Fatal: Failed to register the Ethereum service: invalid chain configuration: missing entry for fork "cancun" in blobSchedule
```
Arguably this is not great, and it should just auto-upgrade the config. We'll address this in a follow-up PR for geth v1.15.2

core: sanity-check fork configuration in genesis init

---

core/rawdb/freezer_table.go

This PR addresses a flaw in the freezer table upgrade path.
In v1.15.0, freezer table v2 was introduced, including an additional 
field (`flushOffset`) maintained in the metadata file. To ensure 
backward compatibility, an upgrade path was implemented for legacy
freezer tables by setting `flushOffset` to the size of the index file.
However, if the freezer table is opened in read-only mode, this file 
write operation is rejected, causing Geth to shut down entirely.
Given that invalid items in the freezer index file can be detected and 
truncated, all items in freezer v0 index files are guaranteed to be complete.
Therefore, when operating in read-only mode, it is safe to use the 
freezer data without performing an upgrade.

core/rawdb: skip setting flushOffset in read-only mode

---

cmd/evm/internal/t8ntool/execution.go
core/block_validator.go
core/rawdb/accessors_chain_test.go
core/state_processor.go
core/types/block.go
core/types/bloom9.go
core/types/bloom9_test.go
core/types/receipt.go
core/types/receipt_test.go
eth/filters/filter_test.go

Currently, when calculating block's bloom, we loop through all the receipt logs to calculate the hash value. However, normally, after going through applyTransaction, the receipt's bloom is already calculated based on the receipt log, so the block's bloom can be calculated by just ORing these receipt's blooms.
```
goos: darwin
goarch: arm64
pkg: github.com/ethereum/go-ethereum/core/types
cpu: Apple M1 Pro
BenchmarkCreateBloom
BenchmarkCreateBloom/small
BenchmarkCreateBloom/small-10             810922              1481 ns/op             104 B/op          5 allocs/op
BenchmarkCreateBloom/large
BenchmarkCreateBloom/large-10               8173            143764 ns/op            9614 B/op        401 allocs/op
BenchmarkCreateBloom/small-mergebloom
BenchmarkCreateBloom/small-mergebloom-10 …
```

core/types: create block's bloom by merging receipts' bloom

---

consensus/beacon/consensus.go

This fixes a regression introduced in #31153 where we didn't consider mainnet to be in PoS, causing #31190.
The problem is, `params.MainnetChainConfig` does not have a defined `MergeNetsplitBlock`, so it isn't considered to be in PoS in `CalcDifficulty`.

consensus/beacon: fix isPostMerge for mainnet

---

p2p/config.go

This fixes an issue where a nat.Interface unmarshaled from the TOML config file could not be re-marshaled to TOML correctly.
Fixes #31183

p2p: fix marshaling of NAT in TOML

---

eth/protocols/eth/handler.go

We somehow forgot to add this in #30302, so discv5 and DNS have actually been disabled since then.
Fixes #31168

eth/protocols/eth: add discovery iterator to protocol

---

trie/stacktrie_fuzzer_test.go
trie/trie_test.go

This PR removes the assumption of the stacktrie and trie to have the same ordering.
This was hit by the fuzzers on oss-fuzz

trie: do not expect ordering in stacktrie during fuzzing

---

cmd/utils/flags.go

My understanding is that this flag is only relevant for the path state scheme, but it's not clear from the description.
So this PR just clarifies that, similar to the `gcmode` flag.

utils: clarify description for history.state flag

---

ethclient/ethclient.go

When querying blocks using special tags, there is no direct method call. It requires delving into the code to find the corresponding number for the special tag and then retrieve the block, which is inconvenient. Therefore, a method was encapsulated to directly query blocks using special tags.

ethclient: enhance the description of using block number tags

---

core/state_processor.go
core/state_transition.go
core/vm/contract.go
core/vm/eips.go
core/vm/evm.go
core/vm/gas_table_test.go
core/vm/instructions.go
core/vm/instructions_test.go
core/vm/interface.go
core/vm/interpreter_test.go
core/vm/runtime/runtime.go
eth/tracers/js/tracer_test.go
eth/tracers/logger/logger_test.go
tests/state_test.go

This PR does a few things including:
- Remove `ContractRef` interface
- Remove `vm.AccountRef` which implements `ContractRef` interface
- Maintain the `jumpDests` struct in EVM for sharing between call frames
- Simplify the delegateCall context initialization

core/vm: clean up EVM environmental structure

---

eth/catalyst/simulated_beacon.go

I know there has been prior discussions on handling that. I think it would be fine to add the last extra miles so it's possible to better test the chain in various conditions, for me around tracing in particular.
It appears the code of the simulated beacon is now already architectured to enable easily support different forks with the `newPayload` function that determines how to construct the right payload based on the the parameters pass to it.
Seems that it's relatively easy to also select the right payload version based on the blockchain state.
I understand that could be seen as an extra maintenance burden though. If there is consensus on merging the PR, happy to check to also handle V1 is seen important.

eth/catalyst: support earlier forks in SimulatedBeacon

---

eth/tracers/internal/tracetest/calltrace_test.go
eth/tracers/internal/tracetest/flat_calltrace_test.go
eth/tracers/internal/tracetest/makeTest.js
eth/tracers/internal/tracetest/prestate_test.go
eth/tracers/internal/tracetest/testdata/call_tracer/blob_tx.json
eth/tracers/internal/tracetest/testdata/prestate_tracer/blob_tx.json
eth/tracers/internal/tracetest/testdata/prestate_tracer/create_create.json
eth/tracers/internal/tracetest/util.go

Made some simple adjustment for the trace testcase:
1. rm `withdrawals{Root}`, `genesis.baseFeePerGas` in `makeTest.js`;
2. add `tracerConfig` in `maketest.js` is not null;
3. reuse `tracerTestEnv` struct;

eth/tracers: refactor block context in test runner

---

oss-fuzz.sh

Fixes https://github.com/ethereum/go-ethereum/issues/31223
(sorry, I thought the fork fork would be created on my repo, not upstream, when I used the GH editor)

oss-fuzz: remove deprecated targets

---

p2p/nat/stun_test.go

The test occasionally fails when network connectivity is bad or if it hits the wrong server. We usually don't add tests with external network dependency so I'm removing them.
Fixes #31220

p2p/nat: remove test with default servers

---

core/types/transaction_marshalling.go

The code contained a TODO comment ("TODO: check hash here?") in the `UnmarshalJSON` function for transactions, indicating that the transaction hash from the JSON input was not being validated against the computed hash. This check is important to ensure the integrity of transaction data. Without it, there is a risk that an incorrect or tampered transaction could be accepted.
This PR adds a hash verification step in the `UnmarshalJSON` function. The solution works as follows:
- After the inner transaction is decoded and set via `tx.setDecoded(inner, 0)`, we check if a non-zero hash value was provided in the JSON (i.e., `dec.Hash` is not equal to `common.Hash{}`).
- If a valid hash is present, the function computes the transaction hash using `tx.Hash()` and compares it with the JSON-provided …

core/types: remove unneeded todo marker

---

cmd/clef/intapi_changelog.md
signer/core/testdata/README.md

Fixed broken or outdated links and improved documentation formatting to ensure consistency and correct references.
**Notes to Reviewers**  
This PR contains only documentation updates to correct broken links and ensure proper references. No functional changes were made.
**How has it been tested?**
- Manually verified that all updated links point to the correct locations.
- Checked markdown syntax and formatting to ensure consistency.

cmd/clef: Link to relevant EIPs in readme

---

eth/backend.go
p2p/dnsdisc/client.go

I ran into this while trying to debug a discv5 thing. I tried to disable DNS discovery using `--discovery.dns=false`, which doesn't work. Annoyingly, geth started anyway and discarded the error silently. I eventually found my mistake, but it took way longer than it should have.
Also including a small change to the error message for invalid DNS URLs here. The user actually needs to see the URL to make sense of the error.

eth: report error from setupDiscovery at startup

---

core/txpool/errors.go
core/txpool/legacypool/legacypool.go
core/txpool/legacypool/legacypool_test.go
core/txpool/validation.go

In this PR, several improvements have been made:
Authorization-related validations have been moved to legacyPool. 
Previously, these checks were part of the standard validation procedure, 
which applies common validations across different pools. Since these 
checks are specific to SetCode transactions, relocating them to legacyPool 
is a more reasonable choice.
Additionally, authorization conflict checks are now performed regardless 
of whether the transaction is a replacement or not.

core/txpool: move setcode tx validation into legacyPool

---

params/config.go

We forgot to add the deposit contract address for holesky, causing deposits to not be flagged correctly

params: add deposit contract addresses

---

eth/protocols/eth/discovery.go
p2p/server.go

See https://github.com/ethereum/go-ethereum/pull/31232#issuecomment-2681262601

eth/protocols/eth: fix loading "eth" ENR key in dial filter

---

build/ci.go

Fix the lint error
```
go run build/ci.go check_generate
build/cache/protoc-27.1-linux-x86_64.zip is stale
downloading from https://github.com/protocolbuffers/protobuf/releases/download/v27.1/protoc-27.1-linux-x86_64.zip
10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
build/cache/protoc-gen-go.v1.34.2.linux.amd64.tar.gz is stale
downloading from https://github.com/protocolbuffers/protobuf-go/releases/download/v1.34.2/protoc-gen-go.v1.34.2.linux.amd64.tar.gz
10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
>>> /home/appveyor/.gvm/gos/go1.24.0/bin/go generate ./...
ci.go:404: File changed: .git/index
ci.go:407: One or more generated files were updated by running 'go generate ./...'
exit status 1
Command exited with code 1
```

build: filter out .git folder for generation check

---

eth/gasprice/feehistory.go

This change divides BlobGasUsed by MaxBlobGasPerBlock instead of MaxBlobsPerBlock. Dividing by MaxBlobsPerBlock 
meant the blobGasUsedRatio was an incorrect large number. This bug was introduced by a typo [here](https://github.com/ethereum/go-ethereum/commit/e6f3ce7b168b8f346de621a8f60d2fa57c2ebfb0#diff-3357b2399699d7cf954c543cbfb02ff442eb24491e55f5e813e3cc85829b3e8dR110)
Fixes https://github.com/ethereum/go-ethereum/issues/31245

eth/gasprice: fix eth_feeHistory blobGasRatio

---

eth/gasprice/feehistory_test.go

Follow on to #31246. Adds a sanity check in the test to make sure the ratio value never goes over 1. Would have avoided the issue in #31245.

eth/gasprice: sanity check ratio values

---

core/txpool/legacypool/legacypool.go
core/txpool/legacypool/legacypool_test.go
core/types/transaction.go

when remove an non-SetCodeTxType transaction, error logs flood
```
t=2025-02-25T03:11:06+0000 lvl=error msg="Authority with untracked tx" addr=0xD5bf9221fCB1C31Cd1EE477a60c148d40dD63DC1 hash=0x626fdf205a5b1619deb2f9e51fed567353f80acbd522265b455daa0821c571d9
t=2025-02-25T03:11:06+0000 lvl=error msg="Authority with untracked tx" addr=0xc5098ce789965A19A17987e02b0F789E65A21F16 hash=0x626fdf205a5b1619deb2f9e51fed567353f80acbd522265b455daa0821c571d9
t=2025-02-25T03:11:06+0000 lvl=error msg="Authority with untracked tx" addr=0x563D4ADD8461dA7B617e0da08Bb096A0971DF49e hash=0x626fdf205a5b1619deb2f9e51fed567353f80acbd522265b455daa0821c571d9
t=2025-02-25T03:11:06+0000 lvl=error msg="Authority with untracked tx" addr=0xD5bf9221fCB1C31Cd1EE477a60c148d40dD63DC1 …
```

core/txpool: fix error logs flood caused by removeAuthorities

---

build/checksums.txt
build/ci.go

This is for fixing the PPA build, which has been failing since the update to Go 1.24.
In Go 1.24, the required Go version for bootstrapping was updated to 1.22. In general, they
are following through with always depending on the Go version two releases ago for
bootstrapping.
Since we still support Ubuntu Xenial (16.04) until its EOL date of 04/2026, and Xenial only
has golang 1.10 as a package, we now need to build Go a total of four times to get the most
recent version. I'm adding a step for Go 1.23 here. This should last us until Go 1.25, which should
be out around 04/2026, and we can hopefully drop the first bootstrapping step at that time.

build: update PPA Go bootstrap version to 1.23

---

cmd/devp2p/internal/ethtest/chain.go
cmd/evm/blockrunner.go
core/state/snapshot/difflayer.go
core/txpool/blobpool/evictheap.go
core/txpool/legacypool/legacypool.go
core/txpool/locals/tx_tracker.go
go.mod
go.sum
p2p/netutil/net.go
triedb/pathdb/history.go
triedb/pathdb/states.go

This is a not-particularly-important "cleanliness" PR. It removes the last remnants of the `x/exp` package, where we used the `maps.Keys` function. 
The original returned the keys in a slice, but when it became 'native' the signature changed to return an iterator, so the new idiom is `slices.Collect(maps.Keys(theMap))`, unless of course the raw iterator can be used instead. 
In some cases, where we previously collect into slice and then sort, we can now instead do `slices.SortXX` on the iterator instead, making the code a bit more concise. 
This PR might be _slighly_ less optimal, because the original `x/exp` implementation allocated the slice at the correct size off the bat, which I suppose the new code won't. 
Putting it up for discussion.

all: drop x/exp direct dependency

---

build/deb/ethereum/deb.rules

Next attempt at fixing the build on launchpad.net

build/deb: add step for new Go bootstrap to debian rules

---

core/txpool/blobpool/blobpool.go
core/txpool/legacypool/legacypool.go
core/txpool/locals/tx_tracker.go
core/txpool/subpool.go
core/txpool/txpool.go
eth/api_backend.go

check if tx is successful before add tx to localTxTracker.
As localTxTracker keep tx and tries to add the tx to txpool, it can make failed rpc tx to success in some case
which is confused for developer.
---
rpc failed due to insufficient funds for gas. 
developer might think the tx was not accepted by node but the tx is in localTxTracker
after developer send eth to the address for gas, the tx in localTxTracker will be in block

eth: do not add failed tx to localTxTracker

---

cmd/devp2p/internal/ethtest/conn.go
cmd/devp2p/internal/ethtest/suite.go
core/txpool/validation.go
core/types/tx_blob.go
eth/handler_eth.go

This ensures that if we receive a blob transaction where we cannot link the tx header to the sidecar commitments, we will drop the sending peer.  This check is added in the protocol handler for the `PooledTransactions` message.
closes https://github.com/ethereum/go-ethereum/issues/31162

eth: check blob transaction validity on the peer goroutine when received

---

ethclient/ethclient.go
ethclient/ethclient_test.go

Ref:
https://ethereum.github.io/execution-apis/api-documentation/
https://docs.metamask.io/services/reference/ethereum/json-rpc-methods/eth_blobbasefee/

ethclient: add BlobBaseFee method to retrieve base fee per blob gas

---

core/state_processor.go

This resolves a situation on the Sepolia testnet, which has a different deposit contract. The contract on that network emits two kinds of logs, instead of only deposit events like the deposit contract on mainnet. So we need to skip events with mismatched topics.

core: match on deposit contract log topic

---

build/checksums.txt

This error was introduced by #31088
```shell
$ go run build/ci.go sanitycheck
/tmp/fixtures_pectra-devnet-6.tar.gz is stale
downloading from https://github.com/ethereum/execution-spec-tests/releases/download/pectra-devnet-6%40v1.0.0/fixtures_pectra-devnet-6.tar.gzfixtures_pectra-devnet-6.tar.gz
gotool.go:177: download error: status 404
```

build: fix execution-spec-tests sanitycheck URL

---

core/rawdb/accessors_state.go
core/rawdb/schema.go
core/state/metrics.go

1. The metric of preimage/hits are always the same as preimage/total, prefer to replace the hits with miss instead.  
2. For the state/read/accounts metric, follow the same naming of others, change inot a singuar.

core/rawdb,state: add preimage miss metric 

---

core/txpool/legacypool/legacypool.go

This error log in `legacypool.go` isn't necessary, since even though the behavior is unexpected, it is handled correctly. A discussion on issue #22301 concluded that this should instead be a warning log.

core/txpool: demote error log to warn

---

core/genesis.go
miner/worker.go

Prefund the precompile addresses for the new precompiles in the developer genesis block

core: prefund prague precompiles in developer genesis

---

cmd/geth/chaincmd.go
cmd/utils/cmd.go

When I press Ctrl-C during the import of multiple files, the import process will still attempt to import the subsequent files. However, in normal circumstances, users would expect the import to stop immediately upon pressing Ctrl-C.
And because the current file was not finished importing, subsequent import tasks often fail due to an `unknown ancestor` error.

cmd/geth: fix ctrl-c interrupt in import command

---

cmd/geth/main.go
cmd/utils/flags.go
core/blockchain.go
core/genesis.go
eth/backend.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go
eth/ethconfig/historymode.go

Here I am adding a config option and geth flag (`--history.chain`) for configuring history pruning. There are two options available:
- `--history.chain all` is the default and will keep all history like before.
- `--history.chain postmerge` will configure the history cutoff point to the merge block. 
The option doesn't actually do anything right now, but we need it as a precursor for other history pruning changes.

eth/ethconfig: add HistoryMode

---

core/blockchain.go

This PR moves the updating of the `blockProcFeed` event feed from `InsertChain` to `insertChain` in order to ensure that the feed subscribers are notified whenever block processing happens.
Note that this event is not subscribed to anywhere in our codebase at the moment, earlier it was used by the LES server to avoid slowing down block processing. Now I want to do the same with the log indexer, the problem is that back then every block insertion was done by `InsertChain`, now the regular payload insertion is done by `InsertBlockWithoutSetHead`. Both of these (and also `SetCanonical` if needed) calls `insertChain` so I moved the feed update there.

core: update blockProcFeed in insertChain

---

accounts/abi/argument.go
accounts/abi/unpack_test.go

Slightly improves performance of abi.Unpack
```
Before
BenchmarkUnpack/0-14   5965714       210.9 ns/op     280 B/op       5 allocs/op
BenchmarkUnpack/1-14   2148283       569.7 ns/op     688 B/op      16 allocs/op
After:
BenchmarkUnpack/0-14  	 7693365	       151.2 ns/op	     136 B/op	       4 allocs/op
BenchmarkUnpack/1-14  	 2261294	       508.9 ns/op	     544 B/op	      15 allocs/op
```
replaces https://github.com/ethereum/go-ethereum/pull/31292 since I was unable to push to your branch @Exca-DK

accounts/abi: improve unpack performance

---

log/root.go
log/root_test.go

Currently, even though it takes in a `Logger` interface, `log.SetDefualt` enforces that the concrete type of the provided logger is `*logger` because:
1. in `init` `root.Store` is called with a `*logger`
2. `atomic.Value` panics if the concrete type provided in `Store` is not consistent across calls. ([ref](https://pkg.go.dev/sync/atomic#Value.Store))
> All calls to Store for a given Value must use values of the same concrete type.
This PR changes to use `sync.RWMutex` and adds a test that panics on `master`.

log: fix SetDefault for custom loggers

---

cmd/evm/staterunner.go

Fixes `evm statetest` for state test fixtures with multiple fork entries in their `post` field (e.g., [chainId.json](https://github.com/ethereum/tests/blob/81862e4848585a438d64f911a19b3825f0f4cd95/GeneralStateTests/stChainId/chainId.json#L39)). 
When these re-activated flags aren't exposed, `statetest` only executes the fixture for a single fork entry instead of all of the forks as expected.
This only affects ethereum/tests state test fixtures, not ethereum/execution-spec-tests (EEST) state tests. EEST writes a separate fixture/test case (i.e. a separate top-level dict entry in the .json) for each fork configuration as apposed to combining multiple forks in one fixture test case: New EEST state tests targeting Prague behavior are not affected.

cmd/evm: fix statetest with multi-fork statetest fixtures

---

metrics/meter.go
metrics/metrics.go

Addresses https://github.com/ethereum/go-ethereum/issues/31244
> ... Can't we move the startup into package metrics somehow? Like launching the goroutine the first time a value is reported on a timer?
We could launch the goroutine the first time we hit Meter.Mark (some meters are not behind timers) but I feel the most logical place to initialize the routine is when we enable the metrics system. It seems this ticker is fundamental to the metrics system, it doesn't appear to ever make sense to run metrics without it.

metrics: spin up meter ticker routine when enabling metric system

---

eth/catalyst/simulated_beacon_test.go

This pull request enhances the unit test, avoiding unnecessary failure in CI.
```
--- FAIL: TestSimulatedBeaconSendWithdrawals (12.08s)
simulated_beacon_test.go:139: timed out without including all withdrawals/txs
FAIL
```

eth/catalyst: fix flaky test

---

eth/tracers/api.go
eth/tracers/api_test.go

Hey! I've discovered that the state override field `movePrecompileToAddress` is being ignored by accident on `debug_traceCall`.
I've implemented a fix by using the same logic that `eth_call` uses, and added tests using these resources - [1](https://github.com/hyperledger/besu/blob/main/ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_call_stateOverride_overridePrecompileCode.json) [2](https://github.com/hyperledger/besu/blob/main/ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_call_stateOverride_movePrecompileToAddress.json)

eth: Fix `movePrecompileToAddress` ignored on debug_traceCall

---

internal/ethapi/simulate.go

Geth was returning empty logsBloom for the simulated block.

internal/ethapi: fix logs bloom in eth_simulateV1

---

ethclient/ethclient.go
ethclient/ethclient_test.go

The main use case I see of this is that it allows users to estimate gas against the same state that they query for their nonce, and the same state they base the data of their transaction against. This helps ensure that gas estimation won't fail and the transaction won't revert on-chain because of a mismatch between the state used for gas estimation and the state used to generate the inputs to gas estimation or the transaction's nonce when submitted to the mempool.
This PR also updates the EstimateGas comment based on the new geth `eth_estimateGas` default of using latest state as of v1.12.0: https://github.com/ethereum/go-ethereum/pull/24363

ethclient: Add EstimateGasAt[Hash] to estimate gas against a specific block

---

core/txpool/blobpool/blobpool.go
core/txpool/legacypool/legacypool.go
core/txpool/subpool.go
core/txpool/txpool.go
eth/handler.go
eth/handler_test.go
eth/protocols/eth/handler.go
eth/protocols/eth/handler_test.go
eth/protocols/eth/handlers.go

Currently, when answering GetPooledTransaction request, txpool.Get() is used. When the requested hash is blob transaction, blobpool.Get() is called. This function loads the RLP-encoded transaction from limbo then decodes and returns. Later, in answerGetPooledTransactions, we need to RLP encode again. This decode then encode is wasteful. This commit adds GetRLP to transaction pool interface so that answerGetPooledTransactions can use the RLP-encoded from limbo directly.

core/txpool, eth: add GetRLP to transaction pool

---

core/types/transaction.go
core/types/transaction_signing.go
core/types/transaction_test.go
core/types/tx_access_list.go
core/types/tx_blob.go
core/types/tx_dynamic_fee.go
core/types/tx_legacy.go
core/types/tx_setcode.go

This PR roughly halves the number of allocations needed to compute the sigHash for a transaction.
This sigHash is used whenever we recover a signature of a transaction, so quite often. During a recent benchmark full syncing on Holesky, roughly 2.8% of all allocations were happening here because the fields from the transaction would be copied multiple times.
```
66168733  153175654 (flat, cum)  2.80% of Total
.          .    368:func (s londonSigner) Hash(tx *Transaction) common.Hash {
.          .    369:	if tx.Type() != DynamicFeeTxType {
.          .    370:		return s.eip2930Signer.Hash(tx)
.          .    371:	}
.   19169966    372:	return prefixedRlpHash(
.          .    373:		tx.Type(),
26442187   26442187    374:		[]interface{}{
.          .    375:			s.chainId,
6848616    6848616 …
```

core/types: reduce allocs in transaction signing

---

cmd/evm/internal/t8ntool/tx_iterator.go
core/types/transaction_signing.go
params/forks/forks.go

This removes the signer type-train in favor of defining a single object that can handle all tx types. Supported types are enabled via a map. Notably, the new signer also supports disabling legacy transactions.

core/types: cleanup tx signer logic

---

cmd/utils/flags.go

`geth` can't catch this situation:
- Init geth db
`geth init genesis.json --state.scheme=path`
- `geth` can start normally with `archive` mode and `path` scheme, but it's not right
```geth --gcmode=archive --history.transactions=0 --state.scheme=path```

cmd/utils: force hash scheme for archive mode

---

cmd/workload/filtertest.go
cmd/workload/filtertestgen.go
cmd/workload/filtertestperf.go

This PR fixes the broken request error handling of the workload filter tests. Until now `validateHistoryPruneErr` was invoked with `fq.Err` as an input which was always nil and a timeout or http error was reported as a result content mismatch.
Also, in case of `errPrunedHistory` it is wrong to return here without setting an error because then it will look like a valid empty result and the check will later fail. So instead `errPrunedHistory` is always returned now (without printing an error message) and the callers of `run` should handle this special case (typically ignore silently).

cmd/workload: fixed filter test request error handling

---

eth/tracers/api_test.go

This pull request fixes a broken unit test
```
=== CONT  TestTracingWithOverrides
api_test.go:1012: result: {"gas":21167,"failed":false,"returnValue":"0x0000000000000000000000000000000000000000000000000000000000000002","structLogs":[{"pc":0,"op":"PUSH1","gas":24978860,"gasCost":3,"depth":1,"stack":[]},{"pc":2,"op":"CALLDATALOAD","gas":24978857,"gasCost":3,"depth":1,"stack":["0x0"]},{"pc":3,"op":"PUSH1","gas":24978854,"gasCost":3,"depth":1,"stack":["0x1"]},{"pc":5,"op":"ADD","gas":24978851,"gasCost":3,"depth":1,"stack":["0x1","0x1"]},{"pc":6,"op":"PUSH1","gas":24978848,"gasCost":3,"depth":1,"stack":["0x2"]},{"pc":8,"op":"MSTORE","gas":24978845,"gasCost":6,"depth":1,"stack":["0x2","0x0"]},{"pc":9,"op":"PUSH1","gas":24978839,"gasCost":3,"depth":1,"stack":[]},{"pc":11,"op":"PUSH1","gas":249788 …
```

eth/tracers: fix test

---

core/filtermaps/filtermaps.go
core/filtermaps/indexer.go
core/filtermaps/map_renderer.go
core/filtermaps/matcher_backend.go

This PR changes the matcher syncing conditions so that it is possible to run a search while head indexing is in progress. Previously it was a requirement to have the head indexed in order to perform matcher sync before and after a search. This was unnecessarily strict as the purpose was just to avoid syncing the valid range with the temporary shortened indexed range applied while updating existing head maps. Now the sync condition explicitly checks whether the indexer has a temporary indexed range with some head maps being partially updated.
It also fixes a deadlock that happened when matcher synchronization was attempted in the event handler called from the `writeFinishedMaps` periodical callback.

core/filtermaps: allow log search while head indexing

---

core/rawdb/accessors_chain.go
core/rawdb/accessors_indexes.go
core/txindexer.go
core/txindexer_test.go

In the #31384 we unindex txes prior to the merge block. However when the node starts up it will try to re-index those back if the config is to index the whole chain.

core: respect history cutoff in txindexer

---

cmd/geth/chaincmd.go
cmd/geth/main.go
core/blockchain.go
core/rawdb/accessors_indexes.go
core/rawdb/chain_iterator.go
core/rawdb/chain_iterator_test.go
core/rawdb/database.go
core/txindexer.go

cmd/geth: add prune history command

---

internal/ethapi/api.go

Currently we only return a `revertError` from `BlockchainAPI.(DoCall,EstimateGas)` when execution reverts with non-empty revert reason.
If the revert data is empty, the RPC response is constructed with a generic `errCodeDefault` code [here](https://github.com/ethereum/go-ethereum/blob/master/rpc/json.go#L125).
By altering the behavior to return a `revertError` from `DoCall`/`DoEstimateGas` upon revert regardless of whether there was a reason supplied, we consistently return the same revert error code whenever a revert occurs from `eth_estimateGas`/`eth_call`.
Using the genesis files I have attached in [this](https://gist.github.com/jwasinger/013eb28996f63549bbf7f63dba4ec819) gist:
Spin up a dev-mode instance of Geth.  The genesis contains an account …

internal/ethapi: return code 3 from call/estimateGas even if a revert reason was not returned

---

core/rawdb/accessors_indexes.go
core/rawdb/database.go
core/rawdb/schema.go

Instead of reporting all filtermaps stuff in one line, I'm breaking it down into the three separate kinds of entries here.
```
+-----------------------+-----------------------------+------------+------------+
|       DATABASE        |          CATEGORY           |    SIZE    |   ITEMS    |
+-----------------------+-----------------------------+------------+------------+
| Key-Value store       | Log index filter-map rows   | 59.21 GiB  |  616077345 |
| Key-Value store       | Log index last-block-of-map | 12.35 MiB  |     269755 |
| Key-Value store       | Log index block-lv          | 421.70 MiB |   22109169 |
```
Also added some other changes to make it easier to debug:
- restored bloombits into the inspect output, so we notice if it doesn't get deleted for some reason
- tracking of …

core/rawdb: improve database stats output

---

core/filtermaps/filtermaps.go
core/filtermaps/indexer.go
core/filtermaps/matcher_backend.go
eth/backend.go

This PR adds an extra condition to the log indexer initialization in order to avoid initializing with block 0 as target head. Previously this caused the indexer to initialize without a checkpoint. Later, when the real chain head was set, it indexed the entire history, then unindexed most of it if only the recent history was supposed to be indexed. Now the init only happens when there is an actual synced chain head and therefore the index is initialized at the most recent checkpoint and only the last year is indexed according to the default parameters.
During checkpoint initialization the best available checkpoint is also checked against the history cutoff point and fails if the indexing would have to start from a block older than the cutoff. If initialization fails then the indexer …

core/filtermaps: fix log indexer init conditions

---

core/chain_makers.go

Verkle is post-Prague, so it must support EIP-7002 EL requests. However, it is not the case, so this PR fixes this.

core: fix GenerateVerkleChain not processing EL requests

---

cmd/utils/export_test.go
common/math/big.go
common/math/integer.go
core/state/snapshot/generate_test.go
core/state/snapshot/iterator_test.go
p2p/nat/nat.go
p2p/nat/natpmp.go
signer/core/apitypes/signed_data_internal_test.go
signer/core/signed_data_test.go
triedb/pathdb/iterator_test.go

I just had a benchmark, the `fmt.Appendf` is a little faster and it uses less memory.
```go
import "fmt"
func FormatByte1(n int) []byte {
return []byte(fmt.Sprintf("key-%04d", n))
}
func FormatByte2(n int) []byte {
return fmt.Appendf(nil, "key-%04d", n)
}
func BenchmarkFormatByte(b *testing.B) {
const n = 1024
b.Run("FormatByte1", func(b *testing.B) {
for b.Loop() {
FormatByte1(n)
}
})
b.Run("FormatByte2", func(b *testing.B) {
for b.Loop() {
FormatByte2(n)
}
})
}
```
```
BenchmarkFormatByte
BenchmarkFormatByte/FormatByte1
BenchmarkFormatByte/FormatByte1-16         	17977934	        66.30 ns/op	      24 B/op	       3 allocs/op
BenchmarkFormatByte/FormatByte2
BenchmarkFormatByte/FormatByte2-16         	20140873	        59.02 ns/op	      16 B/op	       2 allocs/op
PASS
coverage: 100.0% of …
```

all: use fmt.Appendf instead of fmt.Sprintf where possible

---

trie/committer.go
trie/hasher.go
trie/node.go
trie/trie.go
trie/trie_test.go
triedb/database/database.go

This pull request removes the node copy operation to reduce memory allocation. Key Changes as below:
**(a) Use `decodeNodeUnsafe` for decoding nodes retrieved from the trie node reader**
In the current implementation of the MPT, once a trie node blob is retrieved, it is passed to `decodeNode` for decoding. However, `decodeNode` assumes the supplied byte slice might be mutated later, so it performs a deep copy internally before parsing the node.
Given that the node reader is implemented by the path database and the hash database, both of which guarantee the immutability of the returned byte slice. By restricting the node reader interface to explicitly guarantee that the returned byte slice will not be modified, we can safely replace `decodeNode` with `decodeNodeUnsafe`. This eliminates the …

trie: optimize memory allocation

---

core/state/statedb.go

The measurement `s.AccountLoaded` has been updated here, so no need to increase again https://github.com/ethereum/go-ethereum/blob/c49aadc4b628c55da9948b0a1f37f487129ce28a/core/state/statedb.go#L580-L603

core/state: the metric of accountLoaded added once more

---

eth/handler.go

Lowers the logging level when a missing Ethereum peer is unsuccessfully deleted 
from ERROR to WARN, since this situation is not a critical system error.
The absence of a pir in the list when attempting to delete it may be expected in some 
situations, such as if the pir has been deleted by another process or has shut down on its own. 
Such events do not require immediate intervention and do not affect core network processes.
This change will reduce false positives in monitoring systems 
and improve the readability of the event log by keeping ERROR-level error messages 
only for truly critical situations.

eth: downgrade peer removal error to warning level

---

core/txpool/txpool.go

This PR enforces a transaction pool synchronization before clearing it in the `(c *SimulatedBeacon) Rollback()` function.
An alternative approach would be to modify `(p *TxPool) Clear()` to call `(p *TxPool) Sync()` directly before clearing, but this PR opts to perform the synchronization explicitly in `Rollback()`.
In the example below, without the enforced sync, transactions from blocks between `oldHead` and `newHead` are unexpectedly included in the newly committed block, rendering the rollback ineffective. 
```go
simulatedBeacon.Fork(newHead)
simulatedBeacon.Rollback()
simulatedBeacon.Commit()
```
However, introducing a `time.Sleep` between `Fork()` and `Rollback()` produces the expected behavior, where transactions from intermediate blocks are correctly dropped, confirming the flakey …

eth/catalyst: force sync of txpool before clearing subpools in Rollback

---

core/filtermaps/chain_view.go
core/filtermaps/indexer.go

This PR changes log indexer error handling so that if an indexing error happens then it disables the indexer and reverts to unindexed more without resetting the database (except in case of a failed database init).
Resetting the database on the first error would probably be overkill as a client update might fix this without having to reindex the entire history. It would also make debugging very hard. On the other hand, these errors do not resolve themselves automatically so constantly retrying makes no sense either. With these changes a new attempt to resume indexing is made every time the client is restarted.
The PR also fixes https://github.com/ethereum/go-ethereum/issues/31491 which originated from the tail indexer trying to resume processing a failed map renderer.

core/filtermaps: revert to unindexed mode in case of indexing error

---

.gitignore

Ignores all hand-built binaries (built with go build, everything built with make is already ignored)

.gitignore: ignore binaries

---

core/blockchain_reader.go
core/rawdb/accessors_metadata.go
eth/api_backend.go
eth/ethconfig/historymode.go
eth/filters/api.go
eth/filters/filter.go
eth/filters/filter_system.go
eth/filters/filter_system_test.go
internal/ethapi/api.go
internal/ethapi/api_test.go
internal/ethapi/backend.go
internal/ethapi/transaction_args_test.go
rpc/types.go

Implements #31275 
I find it a bit weird to define the error type in `eth/` but I feel like that is the place to return it.

eth, eth/filters: implement API error code for pruned blocks

---

p2p/nat/natupnp.go

It introduces a new variable to store the external port returned by the addAnyPortMapping function and ensures that the correct external port is returned even in case of an error.

p2p/nat: improve AddMapping code

---

cmd/utils/flags.go

Fix an issue of the snapshot fastcache's size can't be applied by the cmd argument

cmd: apply snapshot cache flag

---

triedb/pathdb/nodes.go

This PR refactors the `nodeSet` structure in the path database to use separate maps for account and storage trie nodes, resulting in performance improvements. The change maintains the same API while optimizing the internal data structure.
The original implementation used a single nested map structure for both account and storage nodes:
```
nodes map[common.Hash]map[string]*trienode.Node // node set, mapped by owner and path
```
This required two map lookups for account nodes (first by owner hash, then by path). By separating account nodes into their own dedicated map, we can eliminate one level of indirection for account operations.
Refactored `nodeSet` to use two separate maps:
```
accountNodes map[string]*trienode.Node // for account trie nodes
storageNodes …
```

triedb/pathdb: improve perf by separating nodes map

---

core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go
core/txpool/blobpool/evictheap_test.go
core/txpool/blobpool/lookup.go
core/txpool/legacypool/legacypool.go
core/txpool/subpool.go
core/txpool/txpool.go
eth/handler.go
eth/handler_test.go
eth/protocols/eth/broadcast.go
eth/protocols/eth/handler.go

This is an alternative to #31309
With eth/68, transaction announcement must have transaction type and size. So in announceTransactions, we need to query the transaction from transaction pool with its hash. This creates overhead in case of blob transaction which needs to load data from billy and RLP decode. This commit creates a lightweight lookup from transaction hash to transaction size and a function GetMetadata to query transaction type and transaction size given the transaction hash.

core/txpool: add GetMetadata to transaction pool

---

p2p/discover/v5_udp_test.go
p2p/discover/v5wire/encoding.go
p2p/discover/v5wire/msg.go

When resending the whoareyou packet data, a new nonce and random IV will not be generated.

p2p/discover: cache raw bytes of whoareyou packet

---

p2p/discover/v5_talk.go
p2p/discover/v5_udp.go
p2p/discover/v5_udp_test.go
p2p/discover/v5wire/encoding.go
p2p/discover/v5wire/encoding_test.go
p2p/discover/v5wire/session.go

This is for the implementation of Portal Network in the Shisui client. Their handler needs access to the node object in order to send further calls to the requesting node. **This is a breaking API change** but it should be fine, since there are basically no known users of TALKREQ outside of Portal network.

p2p/discover: pass node instead of node ID to TALKREQ handler

---

cmd/clef/README.md

Hey, I just noticed some typos here:
1- "asks" should be "ask"
Original: "...provide the user with context and asks for permission..."
Corrected: "...provide the user with context and ask for permission...".
2- "users" should be "user"
Original: "If the users grants the signing request..."
Corrected: "If the user grants the signing request...".
3- "An example (insecure) proof-of-concept of has been implemented..." should be "An example (insecure) proof-of-concept has been implemented..."
"of" is unnecessary.
4- "text/validator: hex data with custom validator defined in a contract" should be "text/validator: hex data with a custom validator defined in a contract"
Missing article "a".
Thanks.

README: fixup typos

---

eth/protocols/eth/handler_test.go
eth/protocols/eth/handlers.go

This PR handles overflow and underflow attack vectors for the `GetBlockHeaders` request via specially crafted `Skip` value.
The issue was first brought to attention in this issue: https://github.com/erigontech/erigon/issues/13931

eth/protocols/eth: Fix overflows in  `GetBlockHeaders`

---

cmd/geth/chaincmd.go
cmd/utils/cmd.go
cmd/utils/history_test.go
core/blockchain.go
core/blockchain_reader.go
core/blockchain_test.go
core/error.go
core/headerchain.go
core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go
core/txindexer.go
eth/backend.go
eth/downloader/beaconsync.go
eth/downloader/downloader.go
eth/downloader/metrics.go
eth/downloader/queue.go
eth/downloader/resultstore.go

This pull request introduces new sync logic for pruning mode.
**Pruning Mode**:
Geth now supports two chain history modes (`-history.chain`): `all` and `postmerge`.
- `all` (default): Retains the entire historical chain as usual.
- `postmerge`: Discards chain segments before the configured cutoff point and skips them during synchronization.
The cutoff point is defined as the first block after the Paris fork and will be dynamically
adjusted in the future.
--- 
**Sync mechanism with chain cutoff**
A consensus has been reached across different EL implementations that chain 
segments before the merge point will be pruned by default in the near future. 
This means these segments—specifically block bodies and receipts—will no longer
be available in the P2P network. As a result, these components …

core, eth/downloader: implement pruning mode sync

---

eth/api_backend.go
internal/ethapi/api_test.go

These were caused by crossed merges of recent PRs #31414 and #31361

eth: fix calls to HistoryPruningCutoff

---

cmd/devp2p/internal/v5test/discv5tests.go

This adds the test description text to the output, instead of keeping it as a Go comment. Logs are visible in the hive UI where these tests run, while Go comments are not.
I made a similar change for eth/snap tests in https://github.com/ethereum/go-ethereum/pull/28996

cmd/devp2p/internal/v5test: log test descriptions

---

beacon/blsync/client.go
beacon/light/head_tracker.go
beacon/params/config.go
cmd/blsync/main.go
cmd/geth/main.go
cmd/utils/flags.go

This PR adds a new `--beacon.checkpoint.file` config flag to geth and blsync which specifies a checkpoint import/export file. If a file with an existing checkpoint is specified, it is used for initialization instead of the hardcoded one (except when `--beacon.checkpoint` is also specified simultaneously). Whenever the client encounters a new valid finality update with a suitable finalized beacon block root at an epoch boundary, it saves the block root in hex format to the checkpoint file.

beacon/blsync: add checkpoint import/export file feature

---

p2p/nat/natpmp.go
p2p/nat/natupnp.go
p2p/server_nat.go

Since `addAnyPortMapping` is implemented, we don't need `DeleteMapping` to remove an existing port mapping and make a forceful port mapping (which somewhat goes against the concept of upnp).
Also there is some chance `n.randomPort()` in `addAnyPortMapping` returns an occupied port, so it's safer to try it couple of times. Three looks like  enough according to [libp2p](https://github.com/libp2p/go-nat/blob/01a3d9956ae145b41d9a72bb1e3a2bdad57a7606/upnp.go#L265).
Edit: Fixed so it would only delete port mapping only if the external port was originally used by geth.

p2p/nat: remove forceful port mapping in upnp

---

internal/era/e2store/e2store.go
internal/era/era.go
internal/era/era_test.go

This will be required to serve API requests for header and receipts.

internal/era: random access to header and receipts

---

ethdb/remotedb/remotedb.go

This PR improves error handling in the remotedb package by fixing two issues:
1. In the `Has` method, we now properly propagate errors instead of silently returning false. This makes the behavior more predictable and helps clients better understand when there are connection issues.
2. In the `New` constructor, we add a nil check for the client parameter to prevent potential panics. This follows Go best practices for constructor functions.
These changes make the code more robust and follow Go's error handling idioms without requiring any changes to other parts of the codebase.
Changes:
- Modified `Has` method to return errors instead of silently returning false
- Added nil check in `New` constructor
- Fixed field name in constructor to match struct definition

eth/remotedb: improve error handling

---

core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go
core/txpool/errors.go
core/txpool/legacypool/legacypool.go
core/txpool/legacypool/legacypool2_test.go
core/txpool/legacypool/legacypool_test.go
core/txpool/reserver.go
core/txpool/subpool.go
core/txpool/txpool.go
eth/backend.go
eth/protocols/eth/handler_test.go

This pull request introduces two constraints in the blobPool:
(a) If the sender has a pending authorization or delegation, only one in-flight 
executable transaction can be cached.
(b) If the authority address in a SetCode transaction is already reserved by 
the blobPool, the transaction will be rejected.
These constraints mitigate an attack where an attacker spams the pool with 
numerous blob transactions, evicts other transactions, and then cancels all 
pending blob transactions by draining the sender’s funds if they have a delegation.
Note,  because there is no exclusive lock held between different subpools
when processing transactions, it's totally possible the SetCode transaction
and blob transactions with conflict sender and authorities are accepted
simultaneously. I think it's …

core/txpool: add 7702 protection to blobpool

---

p2p/nat/natupnp.go
p2p/server_nat.go

Make UPnP more robust
- Once a random port was mapped, we try to stick to it even if a UPnP refresh fails. Previously we were immediately moving back to try the default port, leading to frequent ENR changes.
- We were deleting port mappings before refresh as a possible workaround. This created issues in some UPnP servers. The UPnP (and PMP) specification is explicit about the refresh requirements, and delete is clearly not needed (see https://github.com/ethereum/go-ethereum/pull/30265#issuecomment-2766987859). From now on we only delete when closing.
- We were trying to add port mappings only once, and then moved on to random ports. Now we insist a bit more,  so that a simple failed request won't lead to ENR changes.
Fixes https://github.com/ethereum/go-ethereum/issues/31418

p2p/nat: fix UPnP port reset

---

core/txpool/blobpool/blobpool.go
core/txpool/legacypool/legacypool.go
core/txpool/txpool.go

The `Sync(..)` function explicitly says not to rely on in production code, but it is used in `Clear(..)` so should add a similar mention.

core/txpool: add notice to` Clear` that is not meant for production code

---

core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go
core/txpool/legacypool/legacypool.go
core/txpool/legacypool/legacypool_test.go
core/txpool/reserver.go
core/txpool/subpool.go

This PR proposes a change to the authorizations' validation introduced in commit cdb66c8. These changes make the expected behavior independent of the order of admission of authorizations, improving the predictability of the resulting state and the usability of the system with it. 
The current implementation behavior is dependent on the transaction submission order: This issue is related to authorities and the sender of a transaction, and can be reproduced respecting the normal nonce rules. 
The issue can be reproduced by the two following cases:
**First case**
- Given an empty pool.
- Submit transaction `{ from: B, auths [ A ] }`: is accepted.
- Submit transaction `{ from: A }`: Is accepted: it becomes the one in-flight transaction allowed.
**Second case**
- Given an empty pool.
- Submit …

core/txpool: allow tx and authority regardless of admission order

---

accounts/usbwallet/trezor.go

This fix allows Trezor to support full 32bit chainId in geth, with the next version of firmware.
For `chainId > 2147483630` case, Trezor returns signature bit only.
- Trezor returns only signature parity for `chainId > 2147483630` case.
- for `chainId == 2147483630` case, Trezor returns `MAX_UINT32` or `0`, but it doesn't matter.
(`2147483630 * 2 + 35` = `4294967295`(`MAX_UINT32`))
chainId | returned signature_v | compatible issue
---------|------------------------|--------------------
0 < chainId <= 255 | chainId * 2 + 35 + v | no issue (firmware `1.6.2` for Trezor one)
255 < chainId <= 2147483630 | chainId * 2 + 35 + v | ***fixed.*** *firmware `1.6.3`*
chainId > 2147483630 | v | *firmware `1.6.3`*
Please see also: full 32bit chainId support for Trezor
- Trezor one: …

accounts/usbwallet: full 32bit chainId support for Trezor

---

internal/testlog/testlog.go
internal/testlog/testlog_test.go

When we instantiate a sub-logger via `go-ethereum/internal/testlog/logger.With`, we copy the reference to the `bufHandler` from the parent logger.  However, internally, `go-ethereum/internal/testlog/logger.With` calls `log/slog/Logger.With` which creates a new handler instance (via `internal/bufHandler.WithAttrs`).
This PR modifies sub-logger instantiation to use the newly-instantiated handler, instead of copying the reference from the parent instance.  The type cast from `slog.Handler` to `*bufHandler` in `internal/testlog/Logger.With` is safe here because a `internal/testlog/Logger` can only be instantiated with a `*bufHandler` as the underlying handler type.
Note, that I've also removed a pre-existing method that broke the above assumption.  However, this method is not used in our …

internal/testlog:  fix log output from sub-loggers

---

p2p/metrics.go
p2p/peer.go

Our previous success metrics gave success even if a peer disconnected right after connection. These metrics only count peers that stayed connected for at least 1 min.
The 1 min limit is an arbitrary choice. We do not use this for decision logic, only statistics.

p2p: better dial/serve success metrics

---

cmd/geth/chaincmd.go
cmd/workload/testsuite.go
core/block_validator_test.go
core/blockchain.go
core/blockchain_reader.go
core/blockchain_test.go
core/history/historymode.go
eth/api_backend.go
eth/backend.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go
eth/filters/api.go
eth/filters/filter.go
eth/filters/filter_system.go

I added the history mode configuration in eth/ethconfig initially, since it seemed like the logical place. But it turns out we need access to the intended pruning setting at a deeper level, and it actually needs to be integrated with the blockchain startup procedure.
With this change applied, if a node previously had its history pruned, and is subsequently restarted **without** the `--history.chain postmerge` flag, the `BlockChain` initialization code will now verify the freezer tail against the known pruning point of the predefined network and will restore pruning status. Note that this logic is quite restrictive, we allow non-zero tail only for known networks, and only for the specific pruning point that is defined.

core: initialize history pruning in BlockChain

---

p2p/metrics.go
p2p/server.go
p2p/server_test.go

Our metrics related to dial errors were off. The original error was not wrapped, so the caller function had no chance of picking it up. Therefore the most common error, which is "TooManyPeers", was not correctly counted.
The metrics were originally introduced in https://github.com/ethereum/go-ethereum/pull/27621
I was thinking of various possible solutions.
- the one proposed here wraps both the new error and the origial error. It is not a pattern we use in other parts of the code, but works. This is maybe the smallest possible change.
- as an alternate, I could write a proper `errProtoHandshakeError` with it's own wrapped error
- finally, I'm not even sure we need `errProtoHandshakeError`, maybe we could just pass up the original error.

p2p: fix dial metrics not picking up the right error

---

core/state/dump.go

Log `key` in hexadecimal string format.

core/state: fix log format

---

core/txpool/legacypool/legacypool.go

The race detector flagged this in some automated tests I run against the simulated backend.
LegacyPool.Clear is only called by the simulated beacon chain so i'm not sure if this applies to anything other than the simulated backend. But other methods, like LegacyPool.SetGasTip, access pool.all while holding the pool lock, which could create a data race with LegacyPool.Add.
```
Read at 0x00c004f8bf18 by goroutine 38690:
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).Add()
/home/runner/work/exchange/exchange/vendor/github.com/ethereum/go-ethereum/core/txpool/legacypool/legacypool.go:932 +0x12c
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).Add()
/home/runner/work/exchange/exchange/vendor/github.com/ethereum/go-ethereum/core/tx …
```

core/txpool/legacypool: fix data race of txlookup access

---

core/blockchain.go

This fixes an issue where running geth with `--history.chain postmerge` would not work on an empty database.
```
ERROR[04-16|23:11:12.913] Chain history database is pruned to unknown block tail=0
Fatal: Failed to register the Ethereum service: unexpected database tail
```

core: fix history pruning initialization for empty DB

---

eth/handler.go

BroadcastTransactions needs the Sender address to route message flows from the same Sender address consistently to the same random subset of peers.
It however spent considerable time calculating the Sender addresses, even if the Sender address was already calculated and cached in other parts of the code.
Since we only need the mapping, we can use any signer, and the one that had already been used is a better choice because of cache reuse.

eth: fix transaction sender cache miss before broadcast

---

core/era_backend.go
eth/catalyst/simulated_beacon.go

eth/catalyst: sanitize simulated beacon period to avoid overflowing time.Duration

---

core/filtermaps/map_renderer.go

This PR makes the conditions for using a map rendering snapshot stricter so that whenever a reorg happens, only a snapshot of a common ancestor block can be used. The issue fixed in https://github.com/ethereum/go-ethereum/pull/31642 originated from using a snapshot that wasn't a common ancestor. For example in the following reorg scenario: `A->B`, then `A->B2`, then `A->B2->C2`, then `A->B->C` the last reorg triggered a render from snapshot `B` saved earlier. Now this is possible under certain conditions but extra care is needed, for example if block `B` crosses a map boundary then it should not be allowed. With the latest fix the checks are sufficient but I realized I would just feel safer if we disallowed this rare and risky scenario altogether and just render from snapshot `A` after …

core/filtermaps: only use common ancestor snapshots

---

core/filtermaps/chain_view.go

This PR makes `filtermaps.ChainView` thread safe because it is used concurrently both by the indexer and multiple matcher threads. Even though it represents an immutable view of the chain, adding a mutex lock to the `blockHash` function is necessary because it does so by extending its list of non-canonical hashes if the underlying blockchain is changed.
The unsafe concurrency did cause a panic once after running the unit tests for several hours and it could also happen during live operation.

core/filtermaps: make ChainView thread safe

---

eth/gasprice/feehistory.go

The API `eth_feeHistory` returns `{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"json: unsupported value: NaN"}}`, when we query `eth_feeHistory` with a old block that without a blob, or when the field `config.blobSchedule.cancun.max` in genesis.config is 0 (that happens for some projects fork geth but they don't have blob).
So here we specially handle the case when maxBlobGas == 0 to prevent this issue from happening.

eth/gasprice: fix eth_feeHistory blobGasUsedRatio divide zero

---

accounts/abi/abigen/bind_test.go
core/filtermaps/chain_view.go
core/filtermaps/filtermaps.go
core/filtermaps/indexer.go
core/filtermaps/map_renderer.go
core/filtermaps/matcher.go
core/filtermaps/matcher_backend.go
eth/api_backend.go
eth/filters/filter.go
eth/filters/filter_system.go
eth/filters/filter_system_test.go
eth/filters/filter_test.go
internal/ethapi/api_test.go
internal/ethapi/backend.go
internal/ethapi/transaction_args_test.go

This PR changes the chain view update mechanism of the log filter. Previously the head updates were all wired through the indexer, even in unindexed mode. This was both a bit weird and also unsafe as the indexer's chain view was updates asynchronously with some delay, making some log related tests flaky. Also, the reorg safety of the indexed search was integrated with unindexed search in a weird way, relying on `syncRange.ValidBlocks` in the unindexed case too, with a special condition added to only consider the head of the valid range but not the tail in the unindexed case.
In this PR the current chain view is directly accessible through the filter backend and unindexed search is also chain view based, making it inherently safe. The matcher sync mechanism is now only used for indexed …

eth/filters, core/filtermaps: safe chain view update

---

core/filtermaps/filtermaps.go
core/filtermaps/indexer.go
core/filtermaps/indexer_test.go
core/filtermaps/map_renderer.go

This PR ensures that caching a slice or a slice of slices will never affect the original version by always cloning a slice fetched from cache if it is not used in a guaranteed read only way.

core/filtermaps: clone cached slices, fix tempRange

---

cmd/utils/flags.go
internal/debug/api.go
internal/web3ext/web3ext.go

when send too many transaction to txpool during my benchmark, the golang gc will take 1/3 CPU profile.
I want to use the `ballast` mechanism to reduce the gc times to reduce golang GC CPU cost. I try GOGC = 500 and GOMEMLIMIT=10G, but it doesn't work. mainly because this section of code limits the GOGC to never be over 100. 
https://github.com/ethereum/go-ethereum/blob/03cc2942c2c25208dac1b7c8fc1bc19f3d72fd97/cmd/utils/flags.go#L1583-L1597
Assuming the memory is 30G, GOGC value is 20 after the calculation. It also means the larger the memory, the smaller the gogc. This will make the Golang GC very frequent, wasting the CPU resources, so suggest removing this part.
If we wonder about the large number of txs that trigger the OOM, the suggestion is to set GOMEMLIMIT depending on the …

internal/debug: add debug_setMemoryLimit

---

core/txpool/legacypool/legacypool.go

TruncatePending shows up bright red on our nodes, because it computes the length of a map multiple times. 
I don't know why this is so expensive, but around 20% of our time is spent on this, which is super weird.
```
//PR: BenchmarkTruncatePending-24    	   17498	     69397 ns/op	   32872 B/op	       3 allocs/op
//Master: BenchmarkTruncatePending-24    	    9960	    123954 ns/op	   32872 B/op	       3 allocs/op
```
```
benchmark                       old ns/op     new ns/op     delta
BenchmarkTruncatePending-24     123954        69397         -44.01%
benchmark                       old allocs     new allocs     delta
BenchmarkTruncatePending-24     3              3              +0.00%
benchmark                       old bytes     new bytes     delta
BenchmarkTruncatePending-24     32872 …
```

core/txpool/legacypool: refactor truncatePending

---

trie/proof.go
trie/proof_test.go

This PR adds checking for an edgecase which theoretically can happen in the range-prover. Right now, we check that a key does not overwrite a previous one by checking that the key is increasing. However, if keys are of different lengths, it is possible to create a key which is increasing _and_ overwrites the previous key. Example: `0xaabbcc` followed by `0xaabbccdd`. 
This can not happen in go-ethereum, which always uses fixed-size paths for accounts and storage slot paths in the trie, but it might happen if the range prover is used without guaranteed fixed-size keys. 
This PR also adds some testcases for the errors that are expected.

trie: add edgecase for rangeproof correctness

---

core/genesis.go

This PR applies the config overrides to the new config as well, otherwise they will not be applied to defined configs, making shadowforks impossible.
To test:
```
>  ./build/bin/geth --override.prague 123 --dev --datadir /tmp/geth
INFO [04-28|21:20:47.009]  - Prague:                      @123
> ./build/bin/geth --override.prague 321 --dev --datadir /tmp/geth
INFO [04-28|21:23:59.760]  - Prague:                      @321
``

core: apply overrides to new chainconfig

---

cmd/geth/chaincmd.go

In the latest code, if `SetupGenesisBlockWithOverride` returns a `ConfigCompatError`, it will be ignored silently by `geth init`.
I think it should fail out loud since the new chain config isn't actually stored.
It's introduced in this pr 3 months ago: https://github.com/ethereum/go-ethereum/pull/30907

cmd/geth: fix `initGenesis`

---

eth/fetcher/tx_fetcher.go

BatchSize was silently defined in middle of code in multiple places. Better to define it as const.

eth/fetcher: define BatchSize as constant

---

ethclient/ethclient.go
ethclient/ethclient_test.go

It's null in a pending block
https://github.com/ethereum/go-ethereum/blob/a82303f4e3cedcebe31540a53dde4f24fc93da80/internal/ethapi/api.go#L500-L504

ethclient: fix retrieval of pending block

---

cmd/devp2p/internal/ethtest/suite.go

We added tests for GetBlockHeaders data similar to what we did in the [D2PFuzz](https://github.com/AgnopraxLab/D2PFuzz) project to the devp2p suite.

cmd/devp2p: verify client doesn't disconnect when non-existent block is requested

---

core/state_transition.go
eth/gasestimator/gasestimator.go

Alternative to https://github.com/ethereum/go-ethereum/pull/31682

core, eth/gasestimator: introduce MaximumGasUsed for estimation

---

core/filtermaps/chain_view.go
core/filtermaps/filtermaps.go
core/filtermaps/map_renderer.go

This PR fixes an initialization bug that in some cases caused the map renderer to leave the last, partially rendered map as is and resume rendering from the next map. At initialization we check whether the existing rendered maps are consistent with the current chain view and revert them if necessary. Until now this happened through an ugly hacky solution, a "limited" chain view that was supposed to trigger a rollback of some maps in the renderer logic if necessary. This whole setup worked under assumptions that just weren't true any more. As a result it always tried to revert the last map but also it did not shorten the indexed range, only set `headIndexed` to false which indicated to the renderer logic that the last map is fully populated (which it wasn't).
Now an explicit rollback of …

core/filtermaps: fix log index initialization

---

core/txpool/legacypool/legacypool.go

I believe this was missed in https://github.com/ethereum/go-ethereum/pull/31641 where fixing one data race created another. Should only apply to the simulated backend.
go-ethereum v1.15.10
The race detector flagged this in some automated tests I run against the simulated backend.
```
Write at 0x00c00177bba8 by goroutine 36573:
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).Clear()
/home/repo/vendor/github.com/ethereum/go-ethereum/core/txpool/legacypool/legacypool.go:1937 +0x44d
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).Clear()
/home/repo/vendor/github.com/ethereum/go-ethereum/core/txpool/txpool.go:508 +0x1af
github.com/ethereum/go-ethereum/eth/catalyst.(*SimulatedBeacon).Rollback() …
```

core/txpool/legacypool: fix data race of pricedList access

---

params/config.go

`DefaultBlobSchedule` is actually used downstream to calculate blob fees (e.g., [src](https://github.com/ethereum-optimism/optimism/blob/601a380e47853c2922ea1f8944cda05f0eac16f4/op-service/eth/blob.go#L301)), this PR makes it explicit that these params are for `Ethereum prod` instead of `test chains`.

params: fix comment for `DefaultBlobSchedule`

---

core/filtermaps/indexer.go

updates the log entries in `core/filtermaps/indexer.go` to remove double quotes around keys like "first block" and "last block", changing them to `firstblock` and `lastblock`. This brings them in line with the general logging style used across the codebase, where log keys are unquoted single words.
For example, the log:
`  INFO [...] "first block"=..., "last block"=...
`
Is now rendered as:
`  INFO [...] firstblock=..., lastblock=...
`
This change improves readability and maintains consistency with logs such as:
`  INFO [...] number=2 sealhash=... uncles=0 txs=0 ...
`
No functional behavior is changed — this is purely a formatting cleanup for better developer experience.

logs(indexer)Clean up log format in head index progress messages

---

rpc/handler.go
rpc/json.go
rpc/websocket_test.go

rpc: add method name length limit
This change adds a limit of 256 characters for RPC method names to prevent potential abuse where large method names could lead to large response sizes.
The limit is enforced in:
- handleCall for regular RPC method calls
- handleSubscribe for subscription method calls
Added tests in websocket_test.go to verify the length limit functionality for both regular method calls and subscriptions.

rpc: add method name length limit

---

eth/tracers/api.go
eth/tracers/api_test.go

Previously, we were only setting a default `vm.Config` on the EVM instance which kept the tracer disabled.
With this PR, the tracer is always enabled.  However, the output is discarded unless we are tracing a transaction that we want the dump of the output from.

eth/tracers: fix `standardTraceBlockToFile`

---

cmd/geth/consolecmd_test.go
cmd/utils/flags.go

Seems like the network id override for preset networks isn't really relevant after the ETC hardfork?  I think we can explicitly disallow it.

cmd/utils:  don't allow network ID override if a preset network is specified

---

beacon/blsync/engineclient.go

This fixes an issue where blocks containing CL requests triggered an error in the engine API. The encoding of requests used base64 instead of hex.

beacon/blsync: fix requests encoding in engine_newPayloadV4

---

p2p/metrics.go
p2p/server.go

Add metics detailing reasons we reject inbound connections for, and reasons these connections fail during the handshake.

p2p: add metrics for inbound connection errors

---

internal/web3ext/web3ext.go

The function `BacktraceAt` has been removed in #28187 . But the API end-point `debug_backtraceAt` is not removed from the file `internal/web3ext/web3ext.go`.

internal/web3ext: remove the legacy backtraceAt method

---

core/bench_test.go
core/blockchain.go
core/blockchain_repair_test.go
core/blockchain_sethead_test.go
core/blockchain_snapshot_test.go
core/blockchain_test.go
core/headerchain.go
core/rawdb/chain_freezer.go
core/rawdb/database.go
core/rawdb/freezer.go
core/rawdb/freezer_memory.go
core/rawdb/freezer_resettable.go
core/rawdb/freezer_test.go
core/rawdb/table.go
ethdb/database.go
ethdb/leveldb/leveldb.go
ethdb/memorydb/memorydb.go
ethdb/pebble/pebble.go
ethdb/pebble/pebble_test.go
ethdb/remotedb/remotedb.go
node/database.go
trie/trie_test.go
triedb/pathdb/buffer.go
triedb/pathdb/database.go

This pull request introduces a SyncKeyValue function to the ethdb.KeyValueStore 
interface, providing the ability to forcibly flush all previous writes to disk.
This functionality is critical for go-ethereum, which internally uses two independent
database engines: a key-value store (such as Pebble, LevelDB, or memoryDB for 
testing) and a flat-file–based freezer. To ensure write-order consistency between 
these engines, the key-value store must be explicitly synced before writing to the 
freezer and vice versa.
Fixes 
- https://github.com/ethereum/go-ethereum/issues/31405
- https://github.com/ethereum/go-ethereum/issues/29819

core, ethdb: introduce database sync function

---

cmd/geth/consolecmd_test.go
cmd/geth/run_test.go
eth/api_backend_test.go
internal/cmdtest/test_cmd.go

This pull request bumps the timeout for flaky console tests on appveyor.

cmd/geth, internal: fix flaky console tests

---

core/blockchain.go
core/blockchain_insert.go
core/state/database.go
core/state/reader.go
core/state/statedb.go
core/state_prefetcher.go
core/state_transition.go
triedb/pathdb/metrics.go

This pull request enhances the block prefetcher by executing transactions in parallel
to warm the cache alongside the main block processor.
Unlike the original prefetcher, which only executes the next block and is limited to chain 
syncing, the new implementation can be applied to any block. This makes it useful not 
only during chain sync but also for regular block insertion after the initial sync.
TODO

core: implement in-block prefetcher

---

eth/catalyst/api.go

While running kurtosis and spamoor, I noticed occasional `null` entries coming back from `getBlobsV2`. After investigating, I found that spamoor can use the same blob data across multiple transactions, so with larger blob counts, there's an increased chance that a blob is included in a block more than once. As a result, previous indexes in the hash-to-index map in `getBlobsV2` would get overwritten.
I changed the map from `map[common.Hash]int` to `map[common.Hash][]int` to handle this case. I decided to go this route because it's the smallest-possible fix, but it could also make sense to update `blobpool.GetBlobs` to de-duplicate the hashes.

eth/catalyst: allow duplicate blob hashes

---

core/types/transaction.go
core/types/transaction_test.go
eth/tracers/js/goja.go

This PR introduces an allocation-free version of the Transaction.EffectiveGasTip method to improve performance by reducing memory allocations.
- Added a new `EffectiveGasTipInto` method that accepts a destination parameter to avoid memory allocations
- Refactored the existing `EffectiveGasTip` method to use the new allocation-free implementation
- Updated related methods (`EffectiveGasTipValue`, `EffectiveGasTipCmp`, `EffectiveGasTipIntCmp`) to use the allocation-free approach
- Added tests and benchmarks to verify correctness and measure performance improvements
In high-transaction-volume environments, the `EffectiveGasTip` method is called frequently. Reducing memory allocations in this method decreases garbage collection pressure and improves overall system performance.
As-Is …

core/types: reduce allocations in tx.EffectiveGasTip

---

core/blockchain.go
core/blockchain_insert.go

This adds a metric called `chain/mgasps`, which records how many million gas per second are being used during block insertion.
The value is calculated as `usedGas * 1000 / elapsed`, and it's updated in the `insertStats.report` method. Also cleaned up the log output to reuse the same value instead of recalculating it.
Useful for monitoring block processing throughput.

metrics: add chain/mgasps to track gas usage rate

---

core/state/statedb.go
core/vm/interface.go

Hi, I just want to make sure which is the bug, the comment or the implementation?
https://github.com/ethereum/go-ethereum/blob/32c6aa8a1a2595cbb89b05f93440d230841f8431/core/state/statedb.go#L294-L298
https://github.com/ethereum/go-ethereum/blob/32c6aa8a1a2595cbb89b05f93440d230841f8431/core/state/statedb.go#L569-L579
Based on her behavior here, I removed the erroneous description, could you check that?
https://github.com/ethereum/go-ethereum/blob/32c6aa8a1a2595cbb89b05f93440d230841f8431/core/vm/evm.go#L466-L472

core/state: fix incorrect description of function behavior

---

core/blockchain.go

fixes:
1. use current timestamp to check the fork activation instead of the block's, so when syncing behind the head, it will not print the below log;
2. add a time check ensure current time is before the fork activation time
```
INFO [05-10|08:52:03.779] Ready for fork activation                fork=Prague date="07 May 25 18:05 CST" remaining=-62h46m53s timestamp=1,746,612,311
```

core: use unix time to check fork readiness

---

cmd/utils/flags.go

Fix a todo: force-enable this in --dev mode

cmd/utils: always record preimages in dev mode

---

p2p/enode/iter.go
p2p/enode/iter_test.go

This adds support for naming the source iterators of `FairMix`, like so:
```go
mix.AddSource(enode.WithSourceName("mySource", iter))
```
The source that produced the latest node is returned by the new `NodeSource` method.

p2p/enode: add support for naming iterator sources

---

docs/fundamentals/command-line-options.md

Replaced outdated command-line options documentation with the latest stable output from `geth --help` to reflect current Geth usage. This ensures accuracy for users referencing CLI flags.

docs: update CLI options from latest `geth --help` output

---

eth/api_debug.go
eth/api_debug_test.go

Using `header` is enough, so it doesn't need to get the whole block from the database.

eth: use headers in debug.GetModifiedAccountsBy*

---

cmd/devp2p/internal/ethtest/conn.go
cmd/devp2p/internal/ethtest/suite.go

I added a test for BlockRangeUpdate in #29158 but forgot to enable it. Here I'm adding two more tests for it. Also applied a small refactoring to combine calls to `dial()` and `peer()` into a single function, since these two calls are duplicated in each test.

cmd/devp2p/internal/ethtest: tests for BlockRangeUpdate

---

core/filtermaps/filtermaps.go
core/rawdb/accessors_indexes.go

When I'm running the geth node, I found this warning log, it's annoying, because my node is just started, and it should not log the `invalid log index database version` warning.
```
WARN [05-14|12:14:22.393] Invalid log index database version; resetting log index
```
commits:
1. core/rawdb: implicitly return nil if no error, check error first
2. core/filtermaps: don't warning if not initialized

core: don't emit the warning of log indexing if the db was not initialized

---

internal/jsre/deps/web3.js

The `compile` and `eth_getWork` `eth_submitWork` apis were not available anymore, so try to remove them

internal: remove eth_{compile,getWork,submitWork} from console

---

internal/reexec/reexec.go

Hey team—noticed a dead link, replaced it with a working URL
https://github.com/moby/moby/blob/master/pkg/reexec/reexec.go - old link
https://github.com/moby/moby/blob/master/pkg/reexec/reexec_deprecated.go - new link

internal/reexec: fix broken link to Docker/Moby in comment

---

README.md

I've updated the broken link to point to the current official Ethereum JSON-RPC API documentation at https://ethereum.org/en/developers/docs/apis/json-rpc/. This is the correct and up-to-date location for the Ethereum Execution Layer APIs documentation. The link should now work properly.

README: update broken JSON-RPC API documentation link

---

core/state/statedb.go

I couldn't really believe it myself, but turns out this saves us one heap allocation
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/state
cpu: Intel(R) Core(TM) Ultra 7 155U
│ /tmp/old.txt │            /tmp/new.txt             │
│    sec/op    │   sec/op     vs base                │
UpdateStateObject-14   782.6n ± 19%   674.1n ± 6%  -13.86% (p=0.002 n=10)
│ /tmp/old.txt │           /tmp/new.txt            │
│     B/op     │    B/op     vs base               │
UpdateStateObject-14     368.0 ± 0%   344.0 ± 0%  -6.52% (p=0.000 n=10)
│ /tmp/old.txt │            /tmp/new.txt            │
│  allocs/op   │ allocs/op   vs base                │
UpdateStateObject-14     8.000 ± 0%   7.000 ± 0%  -12.50% (p=0.000 n=10)
```
Benchmark:
```go
func BenchmarkUpdateStateObject(b …
```

core/state: reduce allocation in updateStateObject

---

internal/era/accumulator.go

Updated reference URL in accumulator.go comment to point to the correct location of the historical-hashes-accumulator documentation in the Ethereum portal network specs

internal/era: update link to documentation

---

core/state/journal.go

missing field `origvalue` when copy `storageChange`

core/state: fix copy of storageChange

---

internal/build/env.go

This adds support for the Github actions environment in the build tool. Information from environment variables, like the build number and branch/tag name, is used to make decisions about uploads and package filenames.

internal/build: add support for Github Actions CI environment

---

core/blockchain_insert.go

Since this field was not used anymore, so try to remove it.

core: remove unused queued import status

---

.travis.yml

Release artefact building has been migrated to another system (Gitea), so we can finally stop using Travis CI. However, in order to have a fail-safe for the release, I'm leaving the config in and it will still trigger builds on Travis for tagged releases. That way, if our new system fails to work for the next release, we will still have the option of using Travis.

.travis.yml: remove master branch push builds

---

go.mod
go.sum

newer version has a stub implementation for unsupported targets. Which allows us to compile to more exotic targets.

go.mod: bump flock package version

---

eth/api_backend.go

This changes the API backend to return null for not-found blocks. This behavior is required by the RPC When `BlockByNumberOrHash` always returned an error for this case ever since being added in https://github.com/ethereum/go-ethereum/pull/19491. The backend method has a couple of call sites, and all of them handle a `nil` block result because `BlockByNumber` returns `nil` for not-found. 
The only case where this makes a real difference is for `eth_getBlockReceipts`, which was changed in #31361 to actually forward the error from `BlockByNumberOrHash` to the caller.

eth: return null for not-found in BlockByNumberOrHash

---

eth/catalyst/api.go

This situation was failing quietly for me recently when I had a partial data corruption issue. Changing the log level to Error would increase visibility for me.

eth/catalyst: change warning to error for 'too many bad block attempts'

---

eth/catalyst/api.go
eth/catalyst/witness.go

Replaces some locks with atomics in the engine api

eth/catalyst: use atomics instead of locks

---

crypto/kzg4844/kzg4844.go

LLVM is not able to handle large arrays on stack

crypto/kzg4844: avoid copying blobs for marshaling

---

eth/backend.go
p2p/enode/iter.go
p2p/server.go

This PR improves the speed of Disc/v4 and Disc/v5 based discovery by adding a pre-fetch buffer to discovery sources, eliminating slowdowns due to timeouts and rate mismatch between the two precesses.
The PR was split out from #31678, builds on #31592

eth, p2p: improve dial speed by pre-fetching dial candidates

---

ethdb/pebble/pebble.go

This pull request adjusts the number of allowed memory tables in Pebble.
Pebble allows configuring an arbitrary number of memory tables to hold 
unflushed data. When the current memtable becomes full, it is scheduled 
for flushing, and a new memtable is allocated to accept subsequent writes. 
However, if too many memtables accumulate and are waiting to be flushed, 
subsequent writes will stall.
Originally, only two memtables were configured, each with a size of 512 MB
for Ethereum mainnet.  While this setup works well under normal conditions, 
it becomes problematic under heavy write loads. In such scenarios, flushing 
is only triggered when more than 512 MB of data is pending, which may not 
be responsive enough. Even worse, if compactions are running concurrently,
flushing memtables can …

ethdb/pebble: adjust the number of memory tables

---

crypto/kzg4844/kzg4844.go

This fixes a regression in the state tests where we always initialized the KZG library.
This was added to test some stuff in #31791

crypto/kzg4844: remove kzg initialization

---

core/blockchain.go
core/blockchain_insert.go

This is a followup to #31753.
A cumulative counter is more useful when we need to measure / aggregate the metric over a longer period of time.
It also means we won't miss data,
e.g. our prometheus scrapes every 30 seconds,
and so may miss a transient spike in the preaggregated mgas/s.

metrics: add chain/gas for cumulative gas usage

---

trie/database_test.go
trie/secure_trie.go
triedb/database.go

As the preimage will only be stored if `t.preimages != nil`, so no need to save them into local cache if not enabled, ref https://github.com/ethereum/go-ethereum/blob/959f00d9226135ec94d0fb32460e1661d41de456/trie/secure_trie.go#L265-L267
This will reduce the memory wasted to copy the bytes

trie: no need to store preimage if not enabled

---

metrics/counter.go
metrics/counter_float64.go
metrics/gauge.go
metrics/gauge_float64.go
metrics/gauge_info.go
metrics/histogram.go
metrics/meter.go
metrics/registry.go
metrics/registry_test.go
metrics/resetting_timer.go
metrics/runtimehistogram.go
metrics/timer.go

motivation is to remove the dependency on reflect.Call
Throughout the codebase, `GetOrRegister()` is mostly used with lazy construction while `Register()` is strictly used with eagerly constructed metric objects. So it makes sense to isolate the lazy construction to `GetOrRegister()` and make caller decide on which function makes sense for them.

metrics: remove use of reflect in metrics registration code

---

node/rpcstack.go

This fixes a data race when accessing the `httpConfig.prefix` field. This field can be modified while the server is running through `enableRPC`. The fix is storing the prefix in the handler, which is accessed through the atomic pointer.
alternative to #32035
fixes https://github.com/ethereum/go-ethereum/issues/32019

node: fix data race on httpConfig.prefix

---

core/state/dump.go

When `GetKey` (see https://github.com/ethereum/go-ethereum/blob/v1.15.11/trie/secure_trie.go#L235) is called, a missing preimage can cause the function to return a `nil` key. This, in turn, makes `account.Storage` persist an incorrect value.

fix: skip storage entries with missing preimage keys

---

accounts/manager.go

Fixes a data race on the `wallets` slice when closing an account Manager.
At the moment, there is a data race between a go-routine calling the Manager's `Close` function and the background go-routine handling most operations on the `Manager`. The `Manager`'s `wallets` field is accessed without proper synchronization.
By moving the closing of wallets from the `Close()` function into the background thread, this issue can be resolved.

accounts: fix data race when closing manager

---

crypto/bn256/google/bn256.go
oss-fuzz.sh
tests/fuzzers/bn256/bn256_fuzz.go
tests/fuzzers/bn256/bn256_test.go

Adds marshaling fuzzing for G1 and G2 to oss-fuzz. 
Also aligns the behavior of the google library to that of gnark and cloudflare, which only ever read the first 64 / 128 bytes of the input, regardless of how long the input is

tests/fuzzers: added bn marshaling fuzzers

---

eth/catalyst/api.go
eth/downloader/beacondevsync.go

closes https://github.com/ethereum/go-ethereum/issues/31254

eth/catalyst: fetch header on forkchoiceUpdated

---

crypto/bn256/cloudflare/mul_arm64.h

Pulls in https://github.com/cloudflare/bn256/pull/48 to remove usage of R27 and R29 [which are reserved](https://go.dev/doc/asm#arm64).

crypto/bn256/cloudflare: pull in upstream fix for R27 and R29 usage

---

core/blockchain.go
eth/downloader/downloader.go

closes https://github.com/ethereum/go-ethereum/issues/32058
Test with the hoodi testnet in full-sync, the results as below
> master branch about 36seconds
```
INFO [06-18|15:08:01.553] Got interrupt, shutting down...
INFO [06-18|15:08:01.553] HTTP server stopped                      endpoint=[::]:4545
INFO [06-18|15:08:01.553] HTTP server stopped                      endpoint=[::]:4546
INFO [06-18|15:08:01.553] HTTP server stopped                      endpoint=[::]:8551
INFO [06-18|15:08:01.553] IPC endpoint closed                      url=/data/geth.ipc
... 
INFO [06-18|15:08:37.213] Blockchain stopped
```
> this branch about 5seconds
```
INFO [06-18|15:05:20.774] Got interrupt, shutting down...
INFO [06-18|15:05:20.774] HTTP server stopped                      endpoint=[::]:4545
INFO …
```

eth,core: terminate the downloader immediately when shutdown signal is received

---

core/rawdb/accessors_indexes.go
core/rawdb/accessors_indexes_test.go

Reading a single transaction out of a block shouldn't need decoding the entire body

core/rawdb: don't decode the full block body in ReadTransaction

---

crypto/bn256/gnark/g2.go

Aligns the marshaling behavior of gnark to google and cloudflare
Co-authored-by: kevaundray <kevtheappdev@gmail.com>

crypto/bn256/gnark: align marshaling behavior

---

crypto/bn256/cloudflare/twist.go
crypto/bn256/google/twist.go

This PR improves the IsOnCurve method for BN254 G2 points by:
* Clarifying its behavior in the docstring, making it explicit that it verifies both the point being on the curve and in the correct subgroup.
* Adding an in-line comment explaining the subgroup membership check (c.Mul(Order)).
* Minor wording adjustments for readability and consistency.

crypto/bn256: add documentation on subgroup checks for G2

---

core/rawdb/table.go
core/rawdb/table_test.go
ethdb/batch.go
ethdb/database.go
ethdb/dbtest/testsuite.go
ethdb/leveldb/leveldb.go
ethdb/memorydb/memorydb.go
ethdb/pebble/pebble.go
trie/trie_test.go

ethdb: Implement DeleteRange in batch

---

core/blockchain.go
core/state/database.go
core/state/reader.go
core/state_prefetcher.go

This pull request introduces a mechanism to expose statistics from the state reader, 
specifically related to cache utilization during state prefetching.
To improve state access performance, a pair of state readers is constructed with a 
shared local cache. One reader to execute transactions ahead of time to warm up the 
cache. The other reader is used by the actual chain processing logic, which can benefit
from the prefetched states.
This PR adds visibility into how effective the cache is by exposing relevant usage statistics.

core/state: expose the state reader stats

---

core/state_prefetcher.go

Improve the prefetcher concurrency allowance.
Moved to its own PR from #31998, which adds the statistics.
Author: @rjl493456442

core/state: improve the prefetcher concurrency allowance

---

core/state_prefetcher.go

We need at least one prefetch goroutine. SetLimit(0) would block prefetch.

core/state: fix prefetch on single core CPU

---

core/blockchain.go
core/blockchain_snapshot_test.go
core/genesis_test.go
core/state/snapshot/generate_test.go
core/state/statedb_test.go
core/state/sync_test.go
triedb/pathdb/buffer.go
triedb/pathdb/database.go
triedb/pathdb/database_test.go
triedb/pathdb/disklayer.go
triedb/pathdb/generate.go
triedb/pathdb/generate_test.go
triedb/pathdb/iterator_binary.go
triedb/pathdb/iterator_fast.go
triedb/pathdb/iterator_test.go
triedb/pathdb/journal.go
triedb/pathdb/layertree.go
triedb/pathdb/layertree_test.go

Previously, PathDB used a single buffer to aggregate database writes, which needed to be flushed atomically. However, flushing large amounts of data (e.g., 256MB) caused significant overhead, often blocking the system for around 3 seconds during the flush.
To mitigate this overhead and reduce performance spikes, a double-buffer mechanism is introduced. When the active buffer fills up, it is marked as frozen and a background flushing process is triggered. Meanwhile, a new buffer is allocated for incoming writes, allowing operations to continue uninterrupted.
This approach reduces system blocking times and provides flexibility in adjusting buffer parameters for improved performance.
TODO:

triedb/pathdb, eth: use double-buffer mechanism in pathdb

---

core/blockchain.go
eth/api_backend.go
eth/downloader/downloader.go
internal/ethapi/api.go

If Geth is engaged in a long-run block synchronization, such as a full syncing over a large number of blocks, invoking `debug_setHead` will cause `downloader.Cancel` to wait for all fetchers to stop first. 
This can be time-consuming, particularly for the block processing thread. 
To address this, we manually call `blockchain.StopInsert` to interrupt the blocking processing thread and allow it to exit immediately, and after that call `blockchain.ResumeInsert` to resume the block downloading process.
Additionally, we add a sanity check for the input block number of `debug_setHead` to ensure its validity.

eth: quick canceling block inserting when debug_setHead is invoked

---

cmd/clef/README.md

Replaced the outdated and broken link to the Web3 Secret Storage Definition with the current official URL from ethereum.org in the Clef README. This ensures users have access to up-to-date and accurate documentation for the keystore file format.

Update Web3 keystore spec link to official Ethereum documentation

---

cmd/geth/snapshot.go
triedb/database.go
triedb/pathdb/verifier.go

This pull request ports the snapshot iteration logic from the legacy implementation.

cmd/geth, triedb: add pathdb state verification

---

cmd/utils/flags.go

Noticed that the errors for the blsync flags were not formatted correctly for `Fatalf(..)`.

cmd/utils: fix formatting for beacon flag errors to fit Fatalf form

---

triedb/pathdb/iterator_test.go
triedb/pathdb/states.go

This pull request fixes a flaw in the PBSS state iterator, which could return empty 
account or storage data.
In PBSS, multiple in-memory diff layers and a write buffer are maintained. These 
layers are persisted to the database and reloaded after node restarts. However, 
since the state data is encoded using RLP, the distinction between nil and an empty 
byte slice is lost during the encode/decode process. As a result, invalid state values 
such as `[]byte{}` can appear in PBSS and ultimately be returned by the state iterator.
Checkout https://github.com/ethereum/go-ethereum/blob/master/triedb/pathdb/iterator_fast.go#L270
for more iterator details.
It's a long-term existent issue and now be activated since the snapshot integration.
The error `err="range contains deletion"` will occur …

triedb/pathdb: fix journal resolution in pathdb

---

core/blockchain_reader.go
eth/api_backend.go
eth/downloader/api.go
ethclient/ethclient.go
graphql/graphql.go
interfaces.go
internal/ethapi/api.go
internal/jsre/deps/web3.js
triedb/database.go
triedb/pathdb/database.go
triedb/pathdb/history_indexer.go

This pull request tracks the state indexing progress in `eth_syncing` endpoint.
```
> eth.syncing
{
currentBlock: 22788274,
healedBytecodeBytes: 0,
healedBytecodes: 0,
healedTrienodeBytes: 0,
healedTrienodes: 0,
healingBytecode: 0,
healingTrienodes: 0,
highestBlock: 22788259,
startingBlock: 22788248,
stateIndexRemaining: 17217133,
syncedAccountBytes: 0,
syncedAccounts: 0,
syncedBytecodeBytes: 0,
syncedBytecodes: 0,
syncedStorage: 0,
syncedStorageBytes: 0,
txIndexFinishedBlocks: 3001324,
txIndexRemainingBlocks: 19786951
}
```

all: incorporate state history indexing status into eth_syncing response

---

node/database.go

For no apparent reason, KV stores were getting wrapped in `nofreezedb` first and then in `freezerdb`.

node: do not double-wrap KV stores

---

eth/backend.go

core.BlockChainConfig.VmConfig is not a pointer, so setting the Tracer on the `vmConfig` object after it was passed to options does *not* apply it to options.VmConfig
This fixes the issue by setting the value directly inside the `options` object and removing the confusing `vmConfig` variable to prevent further mistakes.

eth: correct tracer initialization in BlockchainConfig

---

.gitea/workflows/release.yml

This is to avoid compatibility issues with mismatched glibc versions between the builder and deployment target.
Fixes #32102

.gitea: switch release builds to static linking

---

triedb/pathdb/database.go
triedb/pathdb/history_indexer.go

Running geth on hoodi network with path archive node, with the below command:
```bash
--hoodi
--gcmode=archive
--db.engine=pebble
--datadir=/data
--port=30303
--http
--http.addr=0.0.0.0
--http.port=8545
--http.vhosts=*
--http.corsdomain=*
--http.api=engine,web3,eth,net,miner,txpool,debug,admin
--authrpc.addr=0.0.0.0
--authrpc.port=8551
--authrpc.vhosts=*
--authrpc.jwtsecret=/jwt/jwt.hex
```
This datadir was copied from another instance, only the chaindb/ancient directory was retained, and the data of other kvdb was deleted, so geth will download the statedb data again, and after downloading and repairing the snapshot, the following problem occurred:
```
NewPayload: inserting block failed       error="history indexing is out of order, last: null, requested: 1"
```
Not sure if we have saved …

triedb: reset state indexer after snap synced

---

core/filtermaps/chain_view.go

This PR resolves Issue #31929 by reducing log noise generated by the log indexer after `debug_setHead` operations.
When `debug_setHead` is called to rewind the blockchain, blocks are removed from the database. However, the log indexer's `ChainView` objects may still hold references to these deleted blocks. When `extendNonCanonical()` attempts to access these missing headers, it results in:
1. **Repeated ERROR logs**: `Header not found number=X hash=0x...`
2. **Log noise** that can mask other important errors  
3. **User confusion** about whether this indicates a real problem
The issue occurs because:
- `debug_setHead` removes blocks from the blockchain database
- Log indexer's `ChainView` may still reference deleted block hashes
- `extendNonCanonical()` in `core/filtermaps/chain_view.go` …

Fix log indexer noise after debug_setHead operations

---

core/filtermaps/filtermaps.go
core/filtermaps/indexer.go

Sorry for not fully fixed in https://github.com/ethereum/go-ethereum/pull/31761, now the log format of unindexing message is cleaned up, to make it consistent with the indexing message.

core/filtermaps: clean up log format of unindexing message

---

cmd/utils/flags_legacy.go

This is a follow up PR after #32128 , Seems I've missed to add --txlookuplimit as hidden.
In hte meanwhile, I also add the other deprecated flags into the output of `show-deprecated-flags`

cmd/utils: show full deprecated flags

---

core/vm/interpreter.go
core/vm/interpreter_test.go

simple enough. benchmark of a dummy EVM loop shows ~%2 speed up on my machine.

core/vm: hoist jumptable nil-check out of the interpreter loop

---

core/txpool/blobpool/limbo.go

- Change the log level to `warning`, during syncing blocks, the `final == nil` is normal.
- Change to log tx hash.

core/txpool/blobpool: lower log level for warnings

---

eth/catalyst/simulated_beacon_api.go

alternate approach to https://github.com/ethereum/go-ethereum/pull/31328 suggested by @MariusVanDerWijden .  This prevents Geth from outputting a lot of logs when trying to commit on-demand dev mode blocks while the client is shutting down.
The issue is hard to reproduce, but I've seen it myself and it is annoying when it happens.  I think this is a reasonable simple solution, and we can revisit if we find that the output is still too large (i.e. there is a large delay  between initiating shut down and the simulated beacon receiving the signal, while in this loop).

eth/catalyst:  abort dev mode block commit if shut down is triggered

---

core/block_validator.go
core/error.go
core/types/block_test.go
core/types/transaction.go
miner/worker.go
params/protocol_params.go

This PR adds a check against the maximum block size, as required by EIP-7934, and also applies a slightly lower
size limit during block building.

core,miner: implement EIP-7934 - RLP Execution Block Size Limit

---

cmd/clef/extapi_changelog.md

This PR updates the outdated documentation URL from docs.gnosis.io to the new official docs.safe.global domain. The change reflects the rebranding from Gnosis Safe to Safe and ensures that users are directed to the current API documentation for transaction service reference.
Changes:
- Replace old URL: https://docs.gnosis.io/safe/docs/contracts_tx_execution/#transaction-hash
- Add new URL: https://docs.safe.global/core-api/transaction-service-reference/gnosis

Update Safe API documentation links

---

eth/downloader/downloader.go

This pull request fixes an issue in disabling direct-ancient mode in snap sync.
Specifically, if `origin >= frozen && origin != 0`, it implies a part of chain data
has been written into the key-value store, all the following writes into ancient
store scheduled by downloader will be rejected with error 
`ERROR[07-10|03:46:57.924] Error importing chain data to ancients   err="can't add block 1166 hash: the append operation is out-order: have 1166 want 0"`.
This issue is detected by the https://github.com/ethpandaops/kurtosis-sync-test, which
initiates the first snap sync cycle without the finalized header and implicitly disables
the direct-ancient mode. A few seconds later the second snap sync cycle is initiated
with the finalized information and direct-ancient mode is enabled incorrectly.

eth/downloader: fix ancient limit in snap sync

---

cmd/geth/testdata/vcheck/data.json
cmd/geth/testdata/vcheck/minisig-sigs-new/data.json.minisig
cmd/geth/testdata/vcheck/minisig-sigs/vulnerabilities.json.minisig.1
cmd/geth/testdata/vcheck/minisig-sigs/vulnerabilities.json.minisig.2
cmd/geth/testdata/vcheck/minisig-sigs/vulnerabilities.json.minisig.3
cmd/geth/testdata/vcheck/signify-sigs/data.json.sig
cmd/geth/testdata/vcheck/sigs/vulnerabilities.json.minisig.1
cmd/geth/testdata/vcheck/sigs/vulnerabilities.json.minisig.2
cmd/geth/testdata/vcheck/sigs/vulnerabilities.json.minisig.3
cmd/geth/testdata/vcheck/vulnerabilities.json
cmd/geth/version_check_test.go

Fixed typo in security release URL by replacing:
Old: https://blog.ethereum.org/2020/11/12/geth_security_release/
New: https://blog.ethereum.org/2020/11/12/geth-security-release/

cmd/geth: update vcheck testdata, add docs on generating signatures

---

accounts/keystore/keystore.go
accounts/keystore/passphrase.go

---
**Description:**  
- Replaced outdated GitHub wiki links with the official Ethereum documentation for Web3 Secret Storage.
- Updated references in `keystore.go` and `passphrase.go` for improved accuracy and reliability.
---

accounts/keystore: update links to documenation

---

internal/ethapi/api.go
internal/ethapi/errors.go

Replace outdated GitHub wiki reference with official ethereum.org documentation link for `eth_sign` JSON-RPC method.
- **Before:** `https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign`
- **After:** `https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sign`
-  **Official source**: ethereum.org is the current official documentation hub
-  **Better maintenance**: Links to ethereum.org are more stable and maintained
- `internal/ethapi/api.go` (line 1552)
---

all: fix outdated ethereum wiki json-rpc json-rpc doc links

---

core/types/tx_blob.go
eth/catalyst/api.go

- In the `CellProofsAt` method, if the proofs are `kzg proof` and when the param `idx == 0`, then the method will return part of the blob proofs. It's not what we want.
- Add the missed `Version` field when copying blob tx.

core/types: fix CellProofsAt method

---

core/rawdb/freezer_batch.go
core/rawdb/freezer_table.go

This pull request slightly improves the freezer fsync mechanism by scheduling the 
Sync operation based on the number of uncommitted items and original time interval.
Originally, freezer.Sync was triggered every 30 seconds, which worked well during 
active chain synchronization. However, once the initial state sync is complete, the 
fixed interval causes Sync to be scheduled too frequently.
To address this, the scheduling logic has been improved to consider both the time 
interval and the number of uncommitted items. This additional condition helps avoid 
unnecessary Sync operations when the chain is idle.

core/rawdb: change the mechanism to schedule freezer sync

---

rpc/doc.go
tests/block_test_util.go

---
**Description:**  
- Replaced outdated GitHub wiki links with current, official documentation URLs.
- Removed links that redirect or are no longer relevant.
- Ensured all references point to up-to-date and reliable sources.
---

all: update dead wiki links

---

trie/hasher.go

I don't know how often a fullnode has empty children, but seemed like a nobrainer.

trie: avoid spawning goroutines for empty children

---

accounts/abi/bind/v2/base.go
accounts/abi/bind/v2/lib.go
accounts/abi/bind/v2/lib_test.go

The root cause of the flaky test was a nonce conflict caused by async contract deployments.
This solution defines a custom deployer with automatic nonce management.

account/abi/bind/v2: fix TestDeploymentWithOverrides

---

eth/tracers/api.go
eth/tracers/api_test.go
internal/ethapi/override/override.go

Fixes #32175.
This fixes the scenario where the blockhash opcode would return 0x0 during RPC simulations when using BlockOverrides with a future block number. The root cause was that BlockOverrides.Apply() only modified the vm.BlockContext, but GetHashFn() depends on the actual types.Header.Number to resolve valid historical block hashes. This caused a mismatch and resulted in incorrect behavior during trace and call simulations.
**Changes:**
Added a new ApplyHeader method to BlockOverrides, which mutates the *types.Header with overridden fields. Updated the RPC simulation/tracing paths to apply header overrides directly to the Header object before creating the EVM block context. This makes sure that there is consistency between BlockContext.BlockNumber and Header.Number to allow …

eth/tracers: apply block header overrides correctly

---

core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go

This PR removes the now‑unused `txValidationFn` field from BlobPool.
It became obsolete after a PR https://github.com/ethereum/go-ethereum/pull/31202 was merged
Resolves https://github.com/ethereum/go-ethereum/issues/32236

core/txpool/blobpool: remove unused `txValidationFn` from BlobPool

---

core/rawdb/chain_freezer.go

When initializing the genesis state, the block number is set to 0, and the genesis hash is empty in the database. Since this is expected behavior, why not adjust the log level to 'warning' instead?

core/rawdb: change log level

---

triedb/pathdb/history_index_block.go
triedb/pathdb/history_index_block_test.go

`binary.AppendUvarint` offers better performance than using append directly, because it avoids unnecessary memory allocation and copying. 
In our case, it can increase the performance by +35.8% for the `blockWriter.append` function:
```
benchmark                        old ns/op     new ns/op     delta
BenchmarkBlockWriterAppend-8     5.97          3.83          -35.80%
```

triedb/pathdb:  use binary.append to eliminate the tmp scratch slice

---

triedb/pathdb/history_indexer.go
triedb/pathdb/history_indexer_test.go

Seems the `signal.result` was not sent back in shorten case, this will cause a deadlock.

triedb/pathdb: fix an deadlock when shorten a non fully indexed history 

---

cmd/devp2p/internal/ethtest/conn.go
cmd/devp2p/internal/ethtest/suite.go
cmd/geth/chaincmd.go
cmd/workload/testsuite.go
core/state/snapshot/journal.go
core/tracing/journal.go
core/txpool/validation.go
core/types/bal/bal_encoding.go
eth/catalyst/api_test.go
eth/ethconfig/config.go
ethdb/leveldb/leveldb.go
ethdb/memorydb/memorydb.go
ethdb/pebble/pebble.go
signer/core/apitypes/types.go
tests/transaction_test_util.go
triedb/pathdb/history_index.go

Following #32274. Replace most cases except for tests.
The errors.new function does not require string formatting, so its performance is better than that of fmt.Errorf.

all: replace the empty fmt.Errorf with errors.New

---

ethclient/simulated/backend_test.go
ethclient/simulated/rollback_test.go

This PR addresses a flakiness in the rollback test discussed in https://github.com/ethereum/go-ethereum/issues/32252
I found `nonce` collision caused transactions occasionally fail to send. I tried to change error message in the failed test like: 
```
if err = client.SendTransaction(ctx, signedTx); err != nil {
t.Fatalf("failed to send transaction: %v, nonce: %d", err, signedTx.Nonce())
}
```
and I occasionally got test failure with this message:
```
=== CONT  TestFlakyFunction/Run_#100
rollback_test.go:44: failed to send transaction: already known, nonce: 0
--- FAIL: TestFlakyFunction/Run_#100 (0.07s)
```
Although `nonces` are obtained via `PendingNonceAt`, we observed that, in rare cases (approximately 1 in 1000), two transactions from the same sender end up with the same nonce. This …

ethclient/simulated: Fix flaky rollback test

---

eth/ethconfig/config.go
eth/filters/filter.go
eth/filters/filter_system.go

ethconfig/config.go:
*   Fixed a small typo and spacing issue in a comment to improve readability.
eth/filters/filter.go:
*   Removed an outdated comment that was describing a feature that no longer exists in the code.
eth/filters/filter_system.go:
*   Updated a comment that was referring to an old variable name.

eth: fix typos and outdated comments

---

eth/ethconfig/config.go
eth/gasestimator/gasestimator.go
internal/ethapi/override/override_test.go

This PR makes 2 changes to how [EIP-7825](https://github.com/ethereum/go-ethereum/pull/31824) behaves. 
When `eth_estimateGas` or `eth_createAccessList` is called without any gas limit in the payload, geth will choose the block's gas limit or the `RPCGasCap`, which can be larger than the `maxTxGas`. 
When this happens for `estimateGas`, the gas estimation just errors out and ends, when it should continue doing binary search to find the lowest possible gas limit. 
This PR will: 
- Add a check to see if `hi` is larger than `maxTxGas` and cap it to `maxTxGas` if it's larger. And add a special case handling for gas estimation execute when it errs with `ErrGasLimitTooHigh`
- Decrease the `RPCGasCap` to 30M (== maxTxGas) to make `createAccessList` choose 30M as the highest gas cap for the tx. …

eth/gasestimator: check ErrGasLimitTooHigh conditions

---

ethdb/leveldb/leveldb.go

Add missing it.Error() check after iteration in Database.DeleteRange to avoid silently 
ignoring iterator errors before writing the batch.
Aligns behavior with batch.DeleteRange, which already validates iterator errors.
No other functional changes; existing tests pass (TestLevelDB).

ethdb/leveldb: check iterator error in Database.DeleteRange

---

eth/downloader/queue_test.go

The previous comment stated that every 3rd block has a tx and every 5th has an uncle.
The implementation actually adds one transaction to every second block and does not add uncles.
Updated the comment to reflect the real behavior to avoid confusion when reading tests.

downloader/queue_test: correct makeChain comment to match implementation

---

eth/downloader/beacondevsync.go

The GetHeader function was incorrectly returning an error when encountering
nil peers in the peers list, which contradicted the comment "keep retrying
if none are yet available". 
Changed the logic to skip nil peers with 'continue' instead of returning
an error, allowing the function to properly iterate through all available
peers and attempt to retrieve the target header from each valid peer.
This ensures the function behaves as intended - trying all available peers
before giving up, rather than failing on the first nil peer encountered.

eth/downloader: skip nil peer in GetHeader

---

core/state/statedb.go
trie/committer.go
trie/proof.go
trie/tracer.go
trie/tracer_test.go
trie/trie.go
trie/trie_test.go
trie/trienode/node.go
trie/trienode/node_test.go
trie/verkle.go

These changes made in the PR should be highlighted here
The trie tracer is split into two distinct structs: opTracer and prevalueTracer.
The former is specific to MPT, while the latter is generic and applicable to all 
trie implementations.
The original values of dirty nodes are tracked in a NodeSet. This serves as the 
foundation for both full archive node implementations and the state live tracer.

trie, core: rework tracer and track origin value of dirty nodes

---

cmd/geth/chaincmd.go
cmd/workload/filtertest.go

fix inconsistent function name in comment

cmd: fix inconsistent function name in comment

---

core/state/reader.go
trie/transition.go

This add some of the changes that were missing from #31634. It introduces the `TransitionTrie`, which is a façade pattern between the current MPT trie and the overlay tree.

trie, core/state: add the transition tree (verkle transition part 2)

---

cmd/evm/blockrunner.go

This is a preparatory change for Verkle/binary trees, since they don't support the hash-based database scheme. This has no impact on the MPT.

cmd/evm: use PathScheme in blockrunner

---

consensus/misc/eip4844/eip4844.go
consensus/misc/eip4844/eip4844_test.go

This changes the implementation to resolve the blob parameters according to the current header timestamp. This matters for EIP-7918, where we would previously resolve the UpdateFraction according to the parent header fork, leading to a confusing situation at the fork transition block.

consensus/misc/eip4844: use blob parameters of current header

---

eth/syncer/syncer.go

- Add defer ticker.Stop() after time.NewTicker in Syncer.run.
- Aligns with project pattern in other long-running loops.
- Prevents potential goroutine/resource leak when the service stops.

eth/syncer: stop ticker to prevent resource leak

---

ethclient/gethclient/gethclient.go

- Unifies hash argument encoding: TraceTransaction now passes common.Hash directly, matching TraceBlock and other RPC calls.
- Leverages common.Hash JSON marshaling (0x‑prefixed hex via MarshalText); no functional change expected. 
- Aligns with RPC handler signature (tracers.API.TraceBlockByHash(ctx, hash common.Hash, ...)) and existing ethclient usage (e.g., eth_getBlockByHash, eth_getTransactionByHash). 
- Simplifies code by avoiding unnecessary Hex() conversion and improves consistency/readability.

ethclient/gethclient: use common.Hash to debug_traceTransaction

---

accounts/scwallet/wallet.go

fixes missing protection of nil pointer dereference in scwallet

---

p2p/peer.go

as metioned in https://github.com/ethereum/go-ethereum/pull/32351,  I think this comment is unnecessary.

p2p: remove todo comment, as it's unnecessary

---

node/api.go

I guess it should be vhosts in this context. Otherwise, vhosts is not used at all in this function.

node: fix vhosts for adminAPI

---

core/state/reader.go
trie/transition.go

Change `NewTransitionTree` to the correct `NewTransitionTrie`.

core,trie: fix typo in TransitionTrie

---

.github/workflows/validate_pr.yml

Full disclosure: this has been generated by AI. The goal is to have a quick check that the PR format is correct, before we merge it. This is to avoid the periodical case when someone forgets to add a milestone or check the title matches our preferred format.

.github/workflows: naive PR format checker

---

triedb/pathdb/database.go
triedb/pathdb/database_test.go
triedb/pathdb/disklayer.go
triedb/pathdb/history_index_test.go
triedb/pathdb/history_indexer.go
triedb/pathdb/history_indexer_test.go
triedb/pathdb/history_inspect.go
triedb/pathdb/history_reader_test.go
triedb/pathdb/history_state.go
triedb/pathdb/history_state_test.go
triedb/pathdb/reader.go

This is a internal refactoring PR, renaming the history to stateHistory.
It's a pre-requisite PR for merging trienode history, avoid the name conflict.

triedb/pathdb: rename history to state history

---

triedb/pathdb/database.go
triedb/pathdb/disklayer.go
triedb/pathdb/history_indexer.go

This pull request refactors the internal implementation in path database a bit,
specifically:
- purge the state index data in batch
- simplify the logic of state history construction and index, make it more readable

triedb/pathdb: refactor state history write

---

rpc/websocket_test.go

closes #32240 #32232
The main cause for the time out is the slow json encoding of large data. In #32240 they tried to resolve the issue by reducing the size of the test. However as Felix pointed out, the test is still kind of confusing.
I've refactored the test so it is more understandable and have reduced the amount of data needed to be json encoded. I think it is still important to ensure that the default read limit is not active, so I have retained one large (~32 MB) test case, but it's at least smaller than the existing ~64 MB test case.

rpc: refactor read limit test

---

core/state_processor.go

Add better error context for EIP-6110, EIP-7002, and EIP-7251 processing in state processor to improve debugging capabilities.

core: improve error context in state processor for Prague EIPs

---

core/rawdb/accessors_state.go
triedb/pathdb/database.go
triedb/pathdb/disklayer.go
triedb/pathdb/history.go
triedb/pathdb/history_reader.go
triedb/pathdb/history_reader_test.go
triedb/pathdb/history_state.go
triedb/pathdb/history_state_test.go
triedb/pathdb/reader.go

This pull request preserves the root->ID mappings in the path database even 
after the associated state histories are truncated, regardless of whether the 
truncation occurs at the head or the tail.
The motivation is to support an additional history type, trienode history. Since 
the root->ID mappings are shared between two history instances, they must 
not be removed by either one.
As a consequence, the root->ID mappings remain in the database even after 
the corresponding histories are pruned. While these mappings may become 
dangling, it is safe and cheap to keep them.
Additionally, this pull request enhances validation during historical reader 
construction, ensuring that only canonical historical state will be served.

triedb/pathdb, core: keep root->id mappings after truncation

---

core/stateless/stats.go
core/stateless/stats_test.go

Filtering for leaf nodes was missing from #32388, which means that even the root done was reported, which made little sense for the bloatnet data processing we want to do.

core/stateless: only report leaf depth in witness stats

---

core/txpool/blobpool/blobpool_test.go

Fix the duplicate function comment in blobpool_test.go where both `makeUnsignedTx` and `makeUnsignedTxWithTestBlob` had identical comments. 
Updated the comment for `makeUnsignedTxWithTestBlob` to accurately reflect its functionality of creating a transaction with a specific test blob.

core/txpool: fix duplicate function comment in blobpool_test.go

---

cmd/geth/chaincmd.go
cmd/geth/dbcmd.go
cmd/geth/snapshot.go
cmd/utils/flags.go

As in #32060 we introduced the file based journal path, for the other sub command(eg: snapshot, db), we should also pass the directory to the triedb, else the subcommand(eg: `geth snapshot`) failed to run:
```bash
geth snapshot verify-state --datadir /geth-data
...
INFO [09-02|02:12:29.493] Allocated cache and file handles         database=/geth-data/geth/chaindata cache=512.00MiB handles=524,288
INFO [09-02|02:12:32.746] Opened ancient database                  database=/geth-data/geth/chaindata/ancient/chain readonly=true
INFO [09-02|02:12:32.746] Opened Era store                         datadir=/geth-data/geth/chaindata/ancient/chain/era
INFO [09-02|02:12:32.758] State scheme set to already existing     scheme=path
INFO [09-02|02:12:32.760] Load database journal from disk
INFO …
```

cmd/geth: set trie journal for pathdb

---

triedb/pathdb/database_test.go
triedb/pathdb/history_indexer.go
triedb/pathdb/history_reader_test.go
triedb/pathdb/journal.go

Alternative of #32335, enhancing the history indexer recovery after unclean shutdown.

triedb/pathdb: add recovery mechanism in state indexer

---

core/rawdb/ancienttest/testsuite.go

Replace TruncateTail(0) with TruncateHead(0) in basicWrite. TruncateTail only advances the tail (prunes prunable tables) and does not reset the head/items count, so it does not “truncate everything.” Using TruncateHead(0) properly clears the ancient store to an empty state, allowing re-appending from index 0 and aligning with existing tests and the documented semantics in ethdb.

core/rawdb: improve the test suite for ancient store

---

triedb/pathdb/journal.go

This pull request addresses the corrupted path database with log indicating:
`history head truncation out of range, tail: 122557, head: 212208, target: 212557`
This is a rare edge case where the in-memory layers, including the write buffer
in the disk layer, are fully persisted (e.g., written to file), but the state history
freezer is not properly closed (e.g., Geth is terminated after journaling but
before freezer.Close). In this situation, the recent state history writes will be
truncated on the next startup, while the in-memory layers resolve correctly.
As a result, the state history falls behind the disk layer (including the write buffer).
In this pull request, the state history freezer is always synced before journal, 
ensuring the state history writes are always persisted before the …

triedb/pathdb: sync ancient store before journal

---

params/config.go

The tabs aren't consistently spaced with the other items in the description. This fixes it.
Before:
After:

params: use spaces instead of tabs in config description

---

core/vm/contracts.go

The `divisor` const is not needed in the gas cost calculation in `osakaModexpGas`.
From [EIP-7883](https://eips.ethereum.org/EIPS/eip-7883):
The gas cost calculation is modified from:
`    return max(200, math.floor(multiplication_complexity * iteration_count / 3))`
to:
`    return max(500, math.floor(multiplication_complexity * iteration_count))`
This change increases the minimum gas cost from 200 to 500 and triples the general cost by removing the division by 3.

core/vm: fix comment and remove unused divisor in osakaModexpGas

---

core/rawdb/accessors_trie.go

Correct the inline comment in HasTrieNode for the path-based scheme. The code returns true only when the node exists and its Keccak256 matches the expected hash, but the comment incorrectly said “exists but not match”. This change aligns the comment with actual behavior and with ReadTrieNode and trie/sync.go semantics, avoiding confusion for maintainers and users.

core/rawdb: fix misleading comment in HasTrieNode

---

core/overlay/state_transition.go

This change ensures TransitionState.Copy preserves BaseRoot. During a Verkle transition, ts.BaseRoot is required to construct the overlay MPT when ts.InTransition() is true. Previously, copies dropped BaseRoot, risking an invalid zero-hash base trie and inconsistent behavior.

core/overlay: copy BaseRoot in TransitionState.Copy

---

core/txpool/blobpool/blobpool.go
core/txpool/legacypool/legacypool.go
core/txpool/subpool.go
eth/sync.go
miner/worker.go

As a consequence of moving blob sidecar version migration code around, we ended up building blocks
with a mix of v0 and v1  blob transactions (different proof encoding in the sidecar).
This PR makes sure we are not building illegal blocks after Osaka. Blob migration is left for another PR.
Related issues and PRs:
- https://github.com/ethereum/go-ethereum/pull/31791
- https://github.com/ethereum/go-ethereum/pull/32347
- https://github.com/ethereum/go-ethereum/pull/31966
- https://github.com/ethereum/go-ethereum/issues/32235

core/txpool/blobpool: Do not use blobs with wrong sidecar version while building block after Osaka

---

core/tracing/journal_test.go

This test iterated over Hooks fields and skipped a field named copy. The Hooks struct has no such field, making the condition dead code.

core/tracing: remove unnecessary 'copy' field skip in TestAllHooksCalled

---

go.mod
go.sum

Updates c-kzg to the latest release: https://github.com/ethereum/c-kzg-4844/releases/tag/v2.1.3

go.mod: update c-kzg

---

go.mod
go.sum

Updates go-eth-kzg: https://github.com/crate-crypto/go-eth-kzg/releases/tag/v1.4.0

go.mod: update go-eth-kzg

---

cmd/geth/main.go
cmd/utils/flags.go
core/blockchain.go
core/stateless/stats.go
core/stateless/stats_test.go
eth/backend.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go

The format that is currently reported by the chain isn't very useful, at it gives an average for ALL the nodes, and not only the leaves, which skews the results.
Also, until now there was no way to activate the reporting of errors.
We also decided that metrics weren't the right tool to report this data, so taking input from @cskiraly we decided to dump it to the console. A better system should be built, but for now, printing to the logs does the job.

core/stateless: add vmwitnessstats cli flag to report leaf stats + log to console

---

triedb/pathdb/database.go
triedb/pathdb/disklayer.go
triedb/pathdb/history.go
triedb/pathdb/history_index.go
triedb/pathdb/history_index_test.go
triedb/pathdb/history_indexer.go
triedb/pathdb/history_indexer_test.go
triedb/pathdb/history_reader.go
triedb/pathdb/history_reader_test.go
triedb/pathdb/history_state.go
triedb/pathdb/history_state_test.go

This pull request is based on #32306 , is the second part for shipping trienode history.
Specifically, this pull request generalize the existing index mechanism, making is usable
by both state history and trienode history in the near future.

triedb/pathdb: generalize the history indexer 

---

core/blockchain.go
params/forks/forks.go

When I implemented in #31340 I didn't expect multiple forks to be configured at once, but this is exactly how BPOs are defined. This updates the method to determine the next scheduled fork rather than the last fork.
Additionally I missed the fork<>string map when adding the BPOs, so adding those here too.

core: fix fork readiness log

---

beacon/engine/gen_epe.go
beacon/engine/types.go
eth/catalyst/api.go
eth/catalyst/witness.go

Addresses https://github.com/ethereum/go-ethereum/issues/32630
This pull request enables the stateless engine APIs for Osaka and the following BPOs.
Apart from that, a few more descriptions have been added in the engine APIs, making
it easier to follow the spec change.

eth/catalyst, beacon/engine: enable BPO and Osaka on stateless APIs

---

cmd/geth/main.go
cmd/utils/flags.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go
eth/filters/api.go
eth/filters/api_test.go
eth/filters/filter_system.go
eth/filters/filter_system_test.go

Add cli configurable limit for the number of addresses allowed in eth_getLogs filter criteria: https://github.com/ethereum/go-ethereum/issues/32264
Key changes:
- Added --rpc.getlogmaxaddrs CLI flag (default: 1000) to configure the maximum number of addresses
- Updated ethconfig.Config with FilterMaxAddresses field for configuration management
- Modified filter system to use the configurable limit instead of the hardcoded maxAddresses constant
- Enhanced test coverage with new test cases for address limit validation
- Removed hardcoded validation from JSON unmarshaling, moving it to runtime validation
Please notice that I remove the check at FilterCriteria UnmarshalJSON because the runtime config can not pass into this validation. 
Please help review this change!

eth/filters, cmd: add config of eth_getLogs address limit

---

core/state_transition.go
eth/tracers/api.go
internal/ethapi/api.go
internal/ethapi/simulate.go
internal/ethapi/transaction_args.go

This disables the tx gaslimit cap for eth_call and related RPC operations.
I don't like how this fix works. Ideally we'd be checking the tx gaslimit somewhere else, like in the block validator, or any other place that considers block transactions. Doing the check in StateTransition means it affects all possible ways of executing a message.
The challenge is finding a place for this check that also triggers correctly in tests where it is wanted.

internal/ethapi: skip tx gas limit check for calls

---

beacon/blsync/block_sync_test.go

This PR improves `TestBlockSync` so that it also tests the finality update validation.
Note: to this date four long and complex (at least partly AI generated) PRs arrived that did something related to testing finality but honestly we do not need a bloated "comprehensive" test to test a trivial feature because maintaining these tests can also be a pain over the long term. This PR adds some sufficient sanity checks to detect if finality ever gets broken by a future change.

beacon/blsync: test validated finality

---

crypto/bn256/bn256_fast.go

We recently update our default implementation to gnark in https://github.com/ethereum/go-ethereum/pull/32024
Then we found a consensus issue and reverted it in https://github.com/ethereum/go-ethereum/commit/65d77c51295c3b5c237a082af856a6926766a51c
We fixed the consensus issue and have been fuzzing it more since then in 
https://github.com/ethereum/go-ethereum/pull/32055/files
https://github.com/ethereum/go-ethereum/pull/32065
https://github.com/ethereum/go-ethereum/pull/32055/files
So I think now is the time to update it back to gnark

crypto/bn256: switch to gnark again

---

core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go
eth/catalyst/api.go

This disables blob proof conversion in `GetBlobs` by default, making it conditional.

core/txpool/blobpool: remove conversion in GetBlobs

---

core/state/snapshot/difflayer_test.go
core/state/snapshot/iterator_test.go
core/state/state_object_test.go

before:
go test -run=^$ -bench=. ./core/state/...  120.85s user 7.96s system 129% cpu 1:39.13 tota
after:
go test -run=^$ -bench=. ./core/state/...  21.32s user 2.12s system 97% cpu 24.006 total

core/state: using testing.B.Loop

---

eth/filters/filter_test.go
eth/protocols/snap/sync_test.go
eth/tracers/internal/tracetest/calltrace_test.go
eth/tracers/internal/tracetest/flat_calltrace_test.go
eth/tracers/tracers_test.go

before:
go test -run=^$ -bench=. ./eth/...  827.57s user 23.80s system 361% cpu 3:55.49 total
after:
go test -run=^$ -bench=. ./eth/...  281.62s user 13.62s system 245% cpu 2:00.49 total

eth: using testing.B.Loop

---

core/vm/analysis_legacy_test.go
core/vm/contracts_test.go
core/vm/instructions_test.go
core/vm/interpreter_test.go
core/vm/runtime/runtime_test.go

before:
go test -run=^$ -bench=. ./core/vm/... -timeout=1h  1841.87s user 40.96s system 124% cpu 25:15.76 total
after:
go test -run=^$ -bench=. ./core/vm/... -timeout=1h  1588.65s user 33.79s system 123% cpu 21:53.25 total

core/vm: using testing.B.Loop

---

core/types/block_test.go
core/types/bloom9_test.go
core/types/hashing_test.go
core/types/transaction_test.go
core/types/types_test.go

before:
go test -run=^$ -bench=. ./core/types  47.80s user 2.18s system 102% cpu 48.936 tota
after:
go test -run=^$ -bench=. ./core/types  42.42s user 2.27s system 112% cpu 39.593 total

core/types: using testing.B.Loop

---

crypto/blake2b/blake2b_test.go
crypto/crypto_test.go
crypto/ecies/ecies_test.go
crypto/kzg4844/kzg4844_test.go
crypto/secp256k1/secp256_test.go
crypto/signature_test.go

before:
go test -run=^$ -bench=. ./crypto/...  94.83s user 2.68s system 138% cpu 1:10.55 tota
after:
go test -run=^$ -bench=. ./crypto/...  75.43s user 2.58s system 123% cpu 1:03.01 total

crypto: using testing.B.Loop

---

common/math/integer_test.go

Fix typo in test error message where "MustParseBig" was incorrectly 
used instead of "MustParseUint64" in the TestMustParseUint64Panic 
function. 
The test still functions correctly, but now the error message 
accurately reflects the function being tested.

fix: correct typo in TestMustParseUint64Panic error message

---

common/hexutil/json_test.go
eth/protocols/snap/gentrie_test.go
eth/protocols/snap/sync_test.go

Remove redundant duplicate test vectors. The two entries were identical and back-to-back, providing no additional coverage while adding noise. Keeping a single instance maintains test intent and clarity without altering behavior.

common, eth: remove duplicate test cases

---

core/rawdb/accessors_chain_test.go

Fix the t.Fatalf format arguments in TestBadBlockStorage to match the intended #index output. Previously, the left number used i+1 and the right index used the block number, producing misleading diagnostics. Correct mapping improves test failure clarity and debuggability.

core/rawdb: fix bad blocks sorted failure message to map index→number correctly

---

core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go
core/txpool/blobpool/conversion.go
core/txpool/blobpool/conversion_test.go
core/txpool/validation.go

This pull request introduces a queue for legacy sidecar conversion to handle 
transactions that persist after the Osaka fork. Simply dropping these transactions 
would significantly harm the user experience.
To balance usability with system complexity, we have introduced a conversion 
time window of two hours post Osaka fork. During this period, the system will 
accept legacy blob transactions and convert them in a background process. 
After the window, all legacy transactions will be rejected. Notably, all the blob
transactions will be validated statically before the conversion, and also all 
conversion are performed in a single thread, minimize the risk of being DoS.
We believe this two hour window provides sufficient time to process in-flight 
legacy transactions and allows submitters …

core/txpool/blobpool: introduce sidecar conversion for legacy blob transactions

---

cmd/era/main.go

This change replaces wrapping a stale outer err with the iterator’s own error after Next(), and switches the post-BlockAndReceipts() check to use the returned err. According to internal/era iterator contract, Error() should be consulted immediately after Next() to surface iteration errors, while decoding errors from Block/Receipts are returned directly. The previous code could hide the real failure (using nil or unrelated err), leading to misleading diagnostics and missed iteration errors.

cmd/era: fix iterator error source handling in checkAccumulator

---

build/ci.go
internal/build/util.go

This fixes `go run build/ci.go install`. It was failing because we resolved all main packages by parsing sources, which fails when the source directory contains multiple modules.

build: module-aware FindMainPackages

---

trie/proof_test.go

- Correct the error message in TestOneElementProof to expect 'v' instead of 'k'.
- The trie is updated with key "k" and value "v"; on mismatch the expected value must be 'v'.
- Aligns the message with the actual test logic and other similar checks in this file, reducing confusion during test failures. No behavioral changes.

trie: fix TestOneElementProof expected value message

---

internal/ethapi/api.go

- bail out of decodeHash when the raw hex string is longer than 32 bytes
- keep error semantics identical while avoiding unnecessary hex decoding work

ethapi: reject oversize storage keys before hex decode

---

eth/tracers/native/keccak256_preimage.go
eth/tracers/native/keccak256_preimage_test.go

This is a tracer I've been missing quite a lot when analyzing changes performed by a transactions.
For example: by having a preimage of each sha3 calculation in the transaction, it is possible to decipher the keys used indexes used to mutate state of a smart contract. 
see #32570

eth/tracers/native: add keccak256preimage tracer

---

eth/catalyst/api.go
eth/catalyst/api_test.go

ref https://github.com/ethereum/execution-apis/blob/main/src/engine/osaka.md#cancun-api
> Client software MUST return -38005: Unsupported fork error if the Osaka fork has been activated.

eth/catalyst: check osaka in engine_getBlobsV1

---

core/rawdb/freezer.go
core/rawdb/freezer_table.go

- Replace outdated NewFreezer doc that referenced map[string]bool/snappy toggle with accurate description of -map[string]freezerTableConfig (noSnappy, prunable).
- Fix misleading field comment on freezerTable.config that spoke as if it were a boolean (“if true”), clarifying it’s a struct and noting compression is non-retroactive.

core/rawdb: update comments

---

params/config.go

Fixes issue #32762 where ChainConfig logging displays pointer addresses instead of actual timestamp values for fork activation times.
Before: ShanghaiTime:(*uint64)(0xc000373fb0), CancunTime:(*uint64)(0xc000373fb8)
After: ShanghaiTime: 1681338455, CancunTime: 1710338135, VerkleTime: nil
The String() method properly dereferences timestamp pointers and handles nil values for unset fork times, making logs more readable and useful for debugging chain configuration issues.

params: implement String() method for ChainConfig

---

params/config.go

Extend the chain banner with blob config information, e.g,
INFO [09-29|10:39:40.999]  - Shanghai:                    @1677557088 (https://ethereum.github.io/execution-specs/src/ethereum/forks/shanghai/__init__.py.html)
INFO [09-29|10:39:40.999]  - Cancun:                      @1706655072 blob: (target: 3, max: 6, fraction: 3338477) (https://ethereum.github.io/execution-specs/src/ethereum/forks/cancun/__init__.py.html)
INFO [09-29|10:39:40.999]  - Prague:                      @1741159776 blob: (target: 6, max: 9, fraction: 5007716) (https://ethereum.github.io/execution-specs/src/ethereum/forks/prague/__init__.py.html)
INFO [09-29|10:39:40.999]  - Osaka:                       @1760427360 blob: (target: 6, max: 9, fraction: 5007716) …

params: add blob config information in the banner

---

core/txpool/txpool.go

The TxPool.signer field was never read and each subpool (legacy/blob) maintains its own signer instance. This field remained after txpool refactoring into subpools and is dead code. Removing it reduces confusion and simplifies the constructor.

core/txpool: remove unused signer field from TxPool

---

core/state/access_events_test.go

Fix misleading failure message in TestMessageCallGas by printing params.WitnessChunkReadCost instead of 0 when CodeHashGas should only incur a chunk read cost. This aligns the error message with the actual expectation and avoids confusion during test failures.

core/state: correct expected value in TestMessageCallGas

---

p2p/enode/iter.go

Hi, we found a occasionally node hang issue on BSC, I think Geth may also have the issue, so pick the fix patch here.
The fix on BSC repo: https://github.com/bnb-chain/bsc/pull/3347
When the hang occurs, there are two routines stuck.
- routine 1: AsyncFilter(...)
On node start, it will run part of the DiscoveryV4 protocol, which could take considerable time, here is its hang callstack:
```
goroutine 9711 [chan receive]:  // this routine was stuck on read channel: `<-f.slots`
github.com/ethereum/go-ethereum/p2p/enode.AsyncFilter.func1()
github.com/ethereum/go-ethereum/p2p/enode/iter.go:206 +0x125
created by github.com/ethereum/go-ethereum/p2p/enode.AsyncFilter in goroutine 1
github.com/ethereum/go-ethereum/p2p/enode/iter.go:192 +0x205
```
- Routine 2: Node Stop
It is the main routine to …

fix: discovery AyncFilter deadlock on shutdown

---

core/blockchain.go
core/evm.go
core/state_processor.go
core/stateless.go
core/vm/runtime/runtime_test.go
eth/tracers/api.go
eth/tracers/api_test.go
internal/ethapi/api.go
internal/ethapi/simulate.go
tests/state_test_util.go

This pr implements https://github.com/ethereum/go-ethereum/issues/32733 to enable StateProcessor to be accepted custom data format.
This introduces a breaking change to users using geth EVM as a library. The `NewStateProcessor` function now takes one parameter which has the chainConfig embedded instead of 2 parameters.

core: refactor StateProcessor to accept ChainContext interface

---

p2p/enode/iter.go

p2p/enode: fix asyncfilter comment

---

.github/workflows/go.yml
appveyor.yml
build/ci.go

This PR does a few things:
- Sets the gh actions runner sizes for lint (s) and test (l) workflows
- Runs the tests on gh in parallel
- Skips fetching the spec tests when unnecessary (on windows in appveyor)
- Removes ubuntu appveyor runner since it's essentially duplicate of the gh action workflow now
The gh test seems to go down from ~35min to ~13min.

build: faster gh actions workflow, no ubuntu on appveyor

---

core/rawdb/accessors_chain.go

- Replace local storedReceiptRLP with types.ReceiptForStorage in receiptLogs.DecodeRLP.
- Eliminates duplication and risk of format drift with core/types.
- Preserves behavior and performance (no Bloom construction).

core/rawdb: remove duplicated type storedReceiptRLP

---

eth/protocols/eth/handshake.go

Enforcing having to pass a whole `*core.BlockChain` instance for the Handshake makes it really hard to use outside of a full node. Using an interface with minimal methods is preferable.

eth/protocols/eth: use BlockChain interface in Handshake
